### ISSUE TITLE
/ /g regex is parsed as MATH token

### ISSUE THREAD

**Issue by gabebw** [jashkenas/coffeescript#1083]
As of 83a86aacb51e8fbdcb135295b1059ba5d5bfae79, coffeescript fails to parse this code  correctly:

```
rspace = / /g
```

It should be a regex, but CS thinks it's two division operators.

This is the error:

```
Error: Parse error on line 1: Unexpected 'MATH'
  at Object.parseError (/usr/local/lib/coffee-script/lib/parser.js:472:11)
  at Object.parse (/usr/local/lib/coffee-script/lib/parser.js:542:22)
  at /usr/local/lib/coffee-script/lib/coffee-script.js:26:22
  ...etc...
```

And here's the output of <code>coffee -t</code>:
<code>[IDENTIFIER rspace] [= =] [MATH /] [MATH /] [IDENTIFIER g] [TERMINATOR \n]</code>

**Comment by osyed** [comment]
It should be mentioned in the coffeescript document page (http://coffeescript.org/) that a regular expression starting with a space should escape the leading space character. Otherwise it seems like an error in the coffeescript compiler.
http://stackoverflow.com/questions/10098021/coffeescript-why-does-str-replace-g-give-coffeescript-compile-error

**Comment by michaelficarra** [comment]
This is already in the FAQ.

**Comment by osyed** [comment]
I don't see that on this page:
https://github.com/jashkenas/coffeescript/wiki/FAQ

Also it would not hurt to mention it on the main coffeescript page.

**Comment by lydell** [comment]
`"str".replace(/ /g, "")` works as expected in CoffeeScript 1.9+.

**Comment by vendethiel** [comment]
It's only the interaction with implicit calls that's messing it up

**Comment by osyed** [comment]
Oh yeah. That's great. Thanks.

**Comment by lydell** [comment]
You may also read more about it here: https://github.com/jashkenas/coffeescript/wiki/Common-Gotchas

**Comment by osyed** [comment]
Wow, all the items on the Gotchas page are so significant to the language,
they should all be mentioned on the main coffee-script-page rather then
being so hard to find (the Gotchas page is not even directly linked on the
main coffee-script page). Please add a Gotchas section on the main page.

BTW, I'm using iced-coffee-script and it is not yet using 1.9 of
coffee-script. If only coffee-script had adopted 'await' and 'defer' :-)
