### ISSUE TITLE
Unintuitive error message on unclosed token

### ISSUE THREAD

**Issue by satyr** [jashkenas/coffeescript#1120]
http://www.pastie.org/1540468

```
$ coffee -bsp
->
  f(
Error: unclosed INDENT on line 2
...

$ coco -bsp
->
  f(
SyntaxError: unclosed CALL( on line 2
...
```

**Comment by GeoffreyBooth** [comment]
Closing this issue as it doesn’t appear to be affecting enough people to warrant attention. If someone wants to do further investigation into this and can devise a fix, a pull request is welcome.
