### ISSUE TITLE
Unoptimised concatenation after splat

### ISSUE THREAD

**Issue by TPReal** [jashkenas/coffeescript#1125]
```
[a..., 0, 0, 0, 0, 0]
```

compiles to
    __slice.call(a).concat([0], [0], [0], [0], [0]);
which could easily be optimised to a single array of zeros.

**Comment by GeoffreyBooth** [comment]
Closing this as it’s not relevant in CS2, now that we’re compiling destructuring as is.
http://coffeescript.org/v2/#try:%5Ba…%2C%200%2C%200%2C%200%2C%200%2C%200%5D
