### ISSUE TITLE
Allow line breaks in function parameter lists 

### ISSUE THREAD

**Issue by niklasl** [jashkenas/coffeescript#1135]
The following code:

```
run = (a,
    b) ->
  console.log "#{a} #{b}"

run "hello", "world"
```

results in `Error: In some.coffee, Parse error on line 2: Unexpected 'INDENT'`.

Having line breaks in parameter lists is useful when having either lots of arguments or long default argument values.

**Comment by msabramo** [comment]
What is the proper syntax for this?

**Comment by michaelficarra** [comment]
@msabramo It's what you would think:

```coffee
f = (
  a
  b
) ->
  a
```

**Comment by carlsmith** [comment]
If you can, it's often better to just pass in a hash once the params get too complicated.

**Comment by msabramo** [comment]
Any ideas on how to express the following in a readable (multi-line) way...?

```coffeescript
robot.hear /\b[a-zA-Z]{2,12}-[0-9]{1,10}\b/, {rateLimits:{minPeriodMs:60000, keyFunction: (context) -> "foo"}}, (msg) ->

    return if msg.message.user.name.match(new RegExp(ignored_users, "gi"))
   ...
```

I tried:

```coffeescript
  robot.hear (
    /\b[a-zA-Z]{2,12}-[0-9]{1,10}\b/
    {rateLimits:{minPeriodMs:60000, keyFunction: (context) -> "foo"}}
    (msg)
  ) ->

    return if msg.message.user.name.match(new RegExp(ignored_users, "gi"))
   ...
```

but I got `SyntaxError: unexpected REGEX`.

**Comment by carlsmith** [comment]
I'd assign the regex and the hash to variables first, then use the names to shorten the expression. You're doing too much on one line.

**Comment by msabramo** [comment]
@carlsmith: Makes sense. Thanks!

**Comment by connec** [comment]
I agree the arguments should be put into variables, however your code [compiles] if you remove the space before the opening `(`.

[compiles]: http://coffeescript.org/#try:robot.hear(%0A%20%20%20%20%2F%5Cb%5Ba-zA-Z%5D%7B2%2C12%7D%5B0-9%5D%7B1%2C10%7D%5Cb%2F%0A%20%20%20%20%7BrateLimits%3A%7BminPeriodMs%3A60000%2C%20keyFunction%3A%20(context)%20-%3E%20%22foo%22%7D%7D%0A%20%20%20%20(msg)%0A%20%20)%20-%3E%0A%0A%20%20%20%20return%20if%20msg.message.user.name.match(new%20RegExp(ignored_users%2C%20%22gi%22))
