### ISSUE TITLE
Raise compile-time error for `(x=x) ->`

### ISSUE THREAD

**Issue by TrevorBurnham** [jashkenas/coffeescript#1145]
Someone [tweeted](http://twitter.com/pokarim/status/38870535685279744) recently that they were surprised about the behavior of `(x=x) ->`; namely, that it's a no-op (`x ?= x`), since both `x`s are within the function scope.

The way I see it, we have two options: We can either fundamentally change the behavior of default arguments (I favor allowing `x=x` in `do` functions, but not elsewhere; see #960); or we can prevent users from compiling such code.

More generally, I'd like to see any default argument code that references an argument name yield something like

```
Syntax error: arguments may not be used as default values
```

This would slightly reduce the power of the language, since currently you can write things like

```
(x = 1, y = x) ->
```

but I think this is an acceptable tradeoff to encourage readability and make the language more accessible to newcomers.

(Related: See #1091 for a proposal to make default arguments more powerful.)

**Comment by GeoffreyBooth** [comment]
Amazingly, `(function(x = 1, y = x) {});` is valid ES, which is what `(x = 1, y = x) ->` compiles to. I guess we need to leave this as is.
