### ISSUE TITLE
Nested comprehensions, bug or a feature?

### ISSUE THREAD

**Issue by ocanbascil** [jashkenas/coffeescript#1191]
I'm having problem with nested array comprehensions.

In python: [ [i,j] for i in range(3) for j in range(3) ]
gives you a 2D array:  
[ [0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2] ]

When I try the same in coffescript : ( [i,j] for i in [0..2] for j in [0..2] )

I end up with a 3D  array:
[ [ [ 0, 0 ], [ 1, 0 ], [ 2, 0 ] ],
  [ [ 0, 1 ], [ 1, 1 ], [ 2, 1 ] ],
  [ [ 0, 2 ], [ 1, 2 ], [ 2, 2 ] ] ]

When I increase the nest depth, python keeps giving flattened results whereas CS increases the array dimensions.

So is this a bug or a feature?

**Comment by GeoffreyBooth** [comment]
Closing this in the interest of cleaning up old issues. If someone would like to implement a new comprehension feature that uses a new syntax that isn’t a breaking change, please feel free to submit a PR.
