### ISSUE TITLE
compiler option to include comments in output javascript code

### ISSUE THREAD

**Issue by donpark** [jashkenas/coffeescript#1202]
I like the fact that I can always move back to javascript by compiling. But if there was a way to avoid losing the comments in source code, it would be even better.

Yes, I am aware that block comments ### are passed through intact but I tend to use inline comments more and I don't really see a compelling reason for these comments to not be in javascript output.

**Comment by baklanoid** [comment]
You may leave comments starting from new line. It wont require any tricky parsing. So do it. It's a would be great.

**Comment by GeoffreyBooth** [comment]
This has been implemented via #4572. Sorry it took a while.
