### ISSUE TITLE
Javascript equivalent of string range (['a'...'z']) is possible, but not working when executed.

### ISSUE THREAD

**Issue by OnesimusUnbound** [jashkenas/coffeescript#1217]
I've tried the following expression

```
'a' in ['a'...'z']
```

and a JavaScript code was generated. However, when I ran it on Try CoffeeScript, it appears to run indefinitely.

**Comment by GeoffreyBooth** [comment]
This currently gets compiled to:

```js
var i, results,
  indexOf = [].indexOf;

indexOf.call((function() {
  results = [];
  for (var i = ‘a’; ‘a’ <= ‘z’ ? i < 'z’ : i > ‘z’; ‘a’ <= 'z’ ? i++ : i--){ results.push(i); }
  return results;
}).apply(this), 'a’) >= 0;
```

I’m not sure what the original poster was expecting, so I can’t tell if this is good or bad. But it doesn’t run forever, at least, so I’m presuming that whatever the issue was has since been fixed.
