### ISSUE TITLE
[a >>>= b] = c

### ISSUE THREAD

**Issue by satyr** [jashkenas/coffeescript#1325]
```
$ coffee -bpe '[a >>>= b] = c'
var b;
b = c.a;
```

**Comment by GeoffreyBooth** [comment]
In CS2 this compiles to:

```js
var a;

[a >>>= b] = c;
```

Which is invalid JavaScript, but probably not worth our time for the compiler to catch as opposed to the runtime.

**Comment by lydell** [comment]
The compiler should not emit invalid JavaScript.

**Comment by GeoffreyBooth** [comment]
That’s not quite true. The compiler should not emit invalid JavaScript _for valid CoffeeScript,_ but we’re not trying to catch all potentially catchable errors at compile time. We don’t validate potentially invalid regular expressions, for example:

```coffee
new RegExp("(?<=\\s)(?<!\\:\\s)#.*?\\{.*?\\}","gm");
```
That [compiles to JavaScript](http://coffeescript.org/v2/#try:new%20RegExp(%22(%3F%3C%3D%5C%5Cs)(%3F%3C!%5C%5C%3A%5C%5Cs)%23.*%3F%5C%5C%7B.*%3F%5C%5C%7D%22%2C%22gm%22)%3B), and the runtime throws `Invalid regular expression`.

See [this comment](https://github.com/jashkenas/coffeescript/issues/1718#issuecomment-2152464). It’s not worth the added complexity and performance hit for the compiler to catch all possible edge cases, especially ones that will be caught by the runtime anyway.

**Comment by lydell** [comment]
Unicode and regex are completely different beasts. This case is perfectly possible to fix with way less complexity. I’m fine if you close this with your go-to “This doesn’t affect many people. PRs welcome”, but not with your previous comment.

**Comment by GeoffreyBooth** [comment]
Okay. If someone would like to fix this, please be our guest.
