### ISSUE TITLE
Inconsistent slice/splice caching for splats and ranges

### ISSUE THREAD

**Issue by jed** [jashkenas/coffeescript#1332]
Seeing that

``` coffeescript
(args...) ->
  args[1..2] = null
```

currently yields

``` javascript
var __slice = Array.prototype.slice;
(function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return ([].splice.apply(args, [1, 2].concat(null)), null);
});
```

is there any reason that `slice` is cached from `Array.prototype`, but not `splice` is used from a new array instance?

**Comment by GeoffreyBooth** [comment]
Since #4526 this compiles to:

```js
var splice = [].splice;

(function(...args) {
  return (splice.apply(args, [1, 2].concat(null)), null);
});
```

which is consistent with `slice`. It would still be a great test to compare the performance of `[].splice` versus the cached reference versus `Array.prototype.splice`, but that can be another issue.
