### ISSUE TITLE
Proposal: Dot notation for numerical property names

### ISSUE THREAD

**Issue by jed** [jashkenas/coffeescript#1334]
Just an idea, but is there any reason why

```
first = arguments.0
```

(c|sh)ouldn't be converted to

```
first = arguments[0];
```

?

It always bugged me that only numbers need to use the bracket syntax despite a lack of ambiguity... Or am I missing something?

**Comment by utkarshkukreti** [comment]
@GeoffreyBooth would you accept a PR implementing this feature?

**Comment by utkarshkukreti** [comment]
Just saw #3828. I can try updating that PR to work with CoffeeScript 2 if you'll accept it!

**Comment by vendethiel** [comment]
@utkarshkukreti That'd be welcomed. https://github.com/jashkenas/coffeescript/pull/3828#issuecomment-298298122

**Comment by GeoffreyBooth** [comment]
@utkarshkukreti yes that would be great. My only word of caution is that a new PR can’t introduce any breaking changes. There was some discussion elsewhere of no longer allowing floats with leading decimal points, e.g. `.5` instead of `0.5`; we need to avoid breaking changes like that.

**Comment by GeoffreyBooth** [comment]
Closing per https://github.com/jashkenas/coffeescript/pull/5006#issuecomment-559665873
