### ISSUE TITLE
alternative compilation for functions with splats

### ISSUE THREAD

**Issue by michaelficarra** [jashkenas/coffeescript#1338]
I'd like to propose the following compilations for functions that contain splats. This alternative compilation will get rid of the `_i` iterator and a bunch of unnecessary incrementation and `.length` accesses on `arguments`. It should both read and execute better.
## `(a..., b, c) -> ...`

<pre>
function(a/*...*/, b, c) {
  var _numArgs;
  _numArgs = arguments.length;
  a = 3 &lt;= _numArgs ? __slice.call(arguments, 0, _numArgs - 2) : [];
  b = arguments[_numArgs - 2];
  c = arguments[_numArgs - 1];
  ...
}
</pre>

## `(a, b, c..., d, e) -> ...`

<pre>
function(a, b, c/*...*/, d, e) {
  var _numArgs;
  _numArgs = arguments.length;
  c = 5 &lt;= _numArgs ? __slice.call(arguments, 2, _numArgs - 2) : [];
  d = arguments[_numArgs - 2];
  e = arguments[_numArgs - 1];
  ...
}
</pre>

## `(a, b, c...) -> ...`

<pre>
function(a, b, c/*...*/) {
  c = 3 &lt;= arguments.length ? __slice.call(arguments, 2) : [];
  ...
}
</pre>

**Comment by GeoffreyBooth** [comment]
No longer relevant in CS2 where we use rest parameters. Not that the CS2 function parameter splat implementation for splats as non-final parameters couldn’t be improved, but it would need to start from a baseline of assuming that rest parameters exist and can be used.
