### ISSUE TITLE
Pipeline support

### ISSUE THREAD

**Issue by klumsy** [jashkenas/coffeescript#1339]
I know that this has been written up before , and the current consensus is that 1) it has a limitation that it doesn't allow functions with multiple arguments, and that it is a niche functionality only useful for DSLs.. I think that 1) it doesn't have to have that limitation, and you can look at F#'s implementation to show this, and 2 it can be very generic and useful, as seen in both F# and more so in powershell.

here is a link to how it is done in F# http://lorgonblog.wordpress.com/2008/03/30/pipelining-in-f/

Here is some coffee of mine doing a scenario. first how i have to call it now, then how i'd like to be able to call it, and third how i can do it with a helper function, then following up with how it can be done in kaffiene currently. The example is rather contrived but it should be sufficient to communicate 

``` ruby
where = (list,func) -> item for item in list when (func.call _ :item)  
select = (list, prefix,postfix) -> "#{prefix}#{item}#{postfix}" for item in list
getnums = (x) -> [1..x]
```

 # is there any easier way i can write the following below

``` ruby
results = select( (where (getnums 10) ,-> @_ > 5) , "pre","post" )
```

alert res for res in results
### 

what it really would like to do is be able, whether using | or say |> for a pipe do

``` ruby
getnum | where -> @_ > 5 | select "pre","post"
```

basically the pipe takes the output of the previous command and puts it as teh first argument, and then takes any other arguments after that (so 1st argument becomes 2nd, and second becomes third..

with my own pipe i can do something like
pipe getnum .to where, -> @_ > 5 .to select , "pre","post"

kaffiene though not complete lets me do this with

``` javascript
getnums = { [1,2,3,4,5,6,7,8,9,10] }select = (list,prefix,postfix) {
  res = []
  for x of list {
   res.push("#{prefix}#{x}#{postfix}")
    }
  return res
  }
```

and call it like this in kaffiene

``` javascript
getnums | select "pre","post"
```

generates the following javascript

``` javascript
var getnums, select; getnums = function() { return [1,2,3,4,5,6,7,8,9,10] }select = function(list,prefix,postfix) {
  var _a, x, res; res = []
  for(_a = 0; _a < list.length; _a++) { x = list[_a];
   res.push("" + (prefix) + (x) + "" + (postfix) + "")
    }
  return res
  }
__.select.call(this, getnums, "pre","post")
```

and

``` javascript
getnums | select "pre","post" | select "yo","dude"
```

``` javascript
__.select.call(this, __.select.call(this, getnums, "pre","post"), "yo","dude")
```

**Comment by hzamani** [comment]
@vendethiel so is this open?!
