### ISSUE TITLE
Multi-line comments and indentation level

### ISSUE THREAD

**Issue by aseemk** [jashkenas/coffeescript#1350]
Easier to show code than to try and describe the problem: ;)

https://gist.github.com/965677

It would be great if that first example worked, i.e. matching indentation level wasn't a requirement for multi-line comments. Makes e.g. commenting out chunks of code easier.

What do you think? Thanks in advance!

**Comment by GeoffreyBooth** [comment]
The first example,
```coffee
for i in foo
    print 'hello'
###
hello?
###
    print 'world'
```
compiles now, as of #4572. Sorry it took awhile.
