### ISSUE TITLE
compiler option to use ES5 bind method.

### ISSUE THREAD

**Issue by krisnye** [jashkenas/coffeescript#1363]
current output is a __bind method and this:

__bind(function() {}, this)

desired output with a new compiler option set would be this:

function(){}.bind(this)

**Comment by GeoffreyBooth** [comment]
[CoffeeScript 2](http://coffeescript.org/v2/) targets ES2015. Part of its goal is to remove old shims and polyfills, and use modern ES syntax wherever possible. Pull requests to help modernize are welcome, against the `2` branch.
