### ISSUE TITLE
Command-line option for leaving off .js extension on compiled classes

### ISSUE THREAD

**Issue by brasten** [jashkenas/coffeescript#1415]
I'm using coffeescript on a collection of source files that I'd like to compile down to files without .js extensions (some of them, anyway).

What I'm doing now is essentially:

lib/file.json.coffee --> _compile_ --> lib/file.json.js
lib/file.js.coffee --> _compile_ --> lib/file.js.js
bin/file.coffee --> _compile_ --> bin/file.js

-- rename *_/_.coffee to *_/_

**Comment by GeoffreyBooth** [comment]
The current compiler can output to stdout, which you can redirect to any filename. `--print`.
