### ISSUE TITLE
new A?

### ISSUE THREAD

**Issue by TrevorBurnham** [jashkenas/coffeescript#1424]
The declarations

```
new A?()
```

and

```
new A? arg
```

work as you'd expect, instantiating `A` if `A` exists. However,

```
new A?
```

parses as the useless `new (A?)`.

**Comment by GeoffreyBooth** [comment]
In CS2 `new A?` becomes
```js
new (typeof A !== "undefined" && A !== null);
```
which is what I would expect it to become. Without parentheses, there’s no reason the `?` would be soaked. Yes it’s useless, but true to the user’s input.
