### ISSUE TITLE
uncaughtException masked

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#1438]
I cant get this scrpt to work using the latest Node and latest CoffeeScript

```
process.removeAllListeners 'uncaughtException'
process.on 'uncaughtException', (er) ->
  console.log 'Unhandled exception'
  console.log 'Unhandled exception'
  console.log 'Unhandled exception'
  console.log 'Unhandled exception'
  console.log 'Unhandled exception'
  console.log 'Unhandled exception'
  console.log 'Unhandled exception'
  console.log 'Unhandled exception'
  return

throw new Error("aAH")
```

Running coffee test.coffee just throws the normal stacktrace.

Howver the generated test.js (from coffee compile) works as planned with node test.generated.js

**Comment by suprMax** [comment]
We're using coffee executable on the server. We're catching most of our errors with domain. Is this still an issue we should be aware about? We wanted to use bugsnag and their docs refer to this page.

**Comment by a7madgamal** [comment]
"We wanted to use bugsnag and their docs refer to this page"
still the case in 2016!

**Comment by Nowaker** [comment]
As we can see, CoffeeScript isn't for serious production deployments.
