### ISSUE TITLE
Minor documentation omissions

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#1457]
A couple things that have bugged me about the docs:
- the fact that # are comments isn't mentioned - starting out I kept trying //, because 'it's just Javascript'. :-)
- the fact that function calls with multiple arguments need to have the left paren start immediately after the function name isn't mentioned. (I might not have this quite right - Coffeescript experts, please correct me.)
- it would be nice if there was a little section on how to pass anonymous functions - only after half an hour of trial and error did I figure out that I have to put parens around an anonymous function in a function call if there are arguments after it
- there's a typo: search for 'as as', which should be 'as a'

Hope this is helpful.

**Comment by GeoffreyBooth** [comment]
The v2 docs mention `#` comments and have fixed the typo. Personally I don’t think the other two need documenting.
