### ISSUE TITLE
avoid long ternaries

### ISSUE THREAD

**Issue by michaelficarra** [jashkenas/coffeescript#1491]
We're generating some [particularly](https://github.com/jashkenas/coffee-script/blob/5ab892d0099a30be8a44/lib/nodes.js#L818) [long](https://github.com/jashkenas/coffee-script/blob/5ab892d0099a30be8a44/lib/nodes.js#L1857) ternaries that don't quite meet our readability standards. We should do something about it.

**Comment by GeoffreyBooth** [comment]
Clearly this hasn’t been a high priority since 2011. Closing this issue as I don’t see it becoming a priority, but if someone wants to submit a PR that improves ternary output style, that would be welcome.
