### ISSUE TITLE
Improve chaining syntax

### ISSUE THREAD

**Issue by JulianBirch** [jashkenas/coffeescript#1495]
Since chaining is a pretty common feature of Javascript libraries, how about a dedicated syntax for it?

e.g.

```
$("p.neat").addClass("ohmy").show("slow");
```

could be written

```
$("p.neat")..       # Note the "dot dot"
  addClass "ohmy"
  show "slow"
```

Alternatively, you could go with something insanely LISPy

```
->>
  $ "p.neat"
  addClass "ohmy"
  show "slow"
```

NB, the semantics I'm proposing would be equivalent to

```
a = $ "p.neat"
b = a.addClass "ohmy"
c = b.show "slow"
```

**Comment by brendan** [comment]
Nested cascades in CoffeeScript would be a snap with the .. syntax:

    document.queryAll "#mypanel TABLE.firstCol"
      ..classes.remove "firstCol"
        ..style
          ..background = "red"
          ..border = "2px solid black"
      ..nodes.add(new Element.html "<spam>This cell is now red</span>")

**Comment by 1j01** [comment]
@brendan `.classes.remove(...).style`? Also, `new Element.html` means `new (Element.html)`
I guess you're used to dart with `.classes.remove` etc.
```coffee
document.querySelector "#mypanel table tr"
  .classList.remove "first-row"
  .style
    console.log "current background is: ", .background
    .background = "red"
    .border = "2px solid black"
  .appendChild new Element
    .innerHTML = "<span>This cell is now red</span>"
```
I'm not sure how I feel about this. The `.` after `console.log` is ambiguous unless you will no longer be able to do `.` on a new line without indenting as you can now.

At any rate, I can't disagree with notion that *"writing functions to return a certain thing just to cater to how you like to write programs is hacking around a missing language feature"*

**Comment by brendan** [comment]
Didn't realize that CoffeeScript would interpret
```
x
  .y
  .z
```
as `x.y.z`.

I guess I'd amend the example you posted to be:

```coffee
document.querySelector "#mypanel table tr"
  ..classList.remove "first-row"  # querySelector result's classList
  ..style # querySelector result's style
    console.log "current background is: ", ..background # style's background
    ..background = "red" # style's background
    ..border = "2px solid black" # style's border
  ..appendChild new Element # querySelector result's appendChild
    ..innerHTML = "<span>This cell is now red</span>" # appendChild result's innerHTML
```

**Comment by stugol** [comment]
Is this likely to be implemented soon?

**Comment by GeoffreyBooth** [comment]
I’m not sure what is even still being debated on this thread. If someone wants to improve chaining from where it stands in v2, please open a new issue with a specific proposal.
