### ISSUE TITLE
Named Functions

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/coffeescript#15]
For debugging purposes, it would be better if CoffeeScript generated only named functions, ie: 

```
square: x => x * x.
```

Compiles into:

```
var square = function square(x) { return x * x; };
```

Questions:

Are there any namespace problems with this, if function names in different scopes collide? If so, what are the consequences (debuggers getting confused, perhaps)? Is it safe to take the final portion of the id as the function name when defining a function on a nested object?

**Comment by carlsmith** [comment]
Named functions would be really helpful for constructor functions. The objects you construct can easily have their constructor bound to them, so you can do `isType Constructor, instance`, but there's no way [I know of] to get a string of the name, so you implement a function that does `isType "Constructor", instance`. This is a fairly serious issue for me personally right now.

**Comment by devinrhode2** [comment]
ES6 now specifies that `var func = function(){};` which should ultimately put this issue to rest. @carlsmith if you really need named functions, dig back through the commit log, @michaelficarra added the feature on some thread I was on but then reverted it, so iirc it is somewhere in the commit log of coffeescriptredux

**Comment by carlsmith** [comment]
@devinrhode2 - I didn't know that. Do you have a link?

It'd be nice to know if this going to be applied to all JS code, or only the code in ES6 classes and modules?

If JS engines are going to make lambda assignments name the function, that would solve the problem in some cases. Will `a.b = ->` name the function `b`?

**Comment by epidemian** [comment]
> @devinrhode2 - I didn't know that. Do you have a link?

http://wiki.ecmascript.org/doku.php?id=harmony:function_name_property

As far as i understand, JS engines would apply the new function naming semantics to all JS code, not just ES6 classes/methods.

IDK if this proposal has been formalized in the ECMAScript spec though.

> Will `a.b = ->` name the function `b`?

Yes! :smiley_cat:

**Comment by carlsmith** [comment]
@epidemian - Thanks man. Looks good.

**Comment by objectkit** [comment]
I know this is closed, but just in case I missed anything in subsequent releases, the capability to transpile named functions by reference name would be great, esp in node contexts, and in web browsers. Daft general example, already well understood. From this

````
methodLogger = 
    log: (method) ->
        console.log method.name

A = ->

methodLogger.log A # "A"
````
to this
````
var A, methodLogger;

methodLogger = {
  log: function(method) {
    return console.log(method.name);
  }
};

function A () {};

methodLogger.log(A); // "A"
````
from this at present
````
var A, methodLogger;

methodLogger = {
  log: function(method) {
    return console.log(method.name);
  }
};

A = function() {};

methodLogger.log(A); // "undefined"
````
really would be useful in many situations IMO e.g. custom error logging, bindings, application contexts, <add your own here>... Perhaps a compiler option? Obviously not all deployment environments will support Function#name properties yet, but in certain deployment specific environments e.g. WebKit based apps outside of the browser context... Thats borderline everyday as far as I can see... my tuppence. Out of here!

**Comment by penne12** [comment]
Why not something like:

```coffeescript

-(test)>
  # do something

```

**Comment by SuperPaintman** [comment]
@penne12 
```coffee
       |=._
       |    \
       |     |
  >>>--|-----(-(arg)>
       |     |
       |   _/
       |=*
```

sorry :D

**Comment by pke** [comment]
Just got a notification that this is still being discussed and not available in CS.
Happily unsubscribing now because I have moved on to ES6 some time ago anyway.

**Comment by youurayy** [comment]
pls at least change the label from `fixed` to `wontfix`

**Comment by carlsmith** [comment]
If ES6 will fix it for us, then it's essentially fixed. Just have to be patient.
http://wiki.ecmascript.org/doku.php?id=harmony:function_name_property

**Comment by avalanche1** [comment]
I really need named functions instead of anonymous functions assigned to variables!
When stupid ass support for IE 6 will be dropped??

**Comment by connec** [comment]
@avalanche1 what use-case do you have that demands named functions?

IE6 is being dropped in the `2` branch, though there is currently no plans to compile no named functions as evergreen environments can determine function names from the assigned variable.

```js
var foo, bar
(foo = function () {}).name // 'foo'
(bar = () => {}).name       // 'bar'
```

**Comment by avalanche1** [comment]
I need this for:
1)'name' property of a function
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name only latest Chrome supports names for anonymous functions:
![image](https://cloud.githubusercontent.com/assets/10534563/21427986/bcb6d03e-c868-11e6-88b7-9dbfa0e78956.png)
2) function hoisting. I DO like to code like:
```
doStuff()
doOtherStuff()

doStuff = ->stuff
doOtherStuff = ->other stuff
```
(pls dont tell me it's 'bad', cause I like to have freedom of choice, you know - if I want to code in a 'bad' way - that's my choice)

**Comment by epidemian** [comment]
> 2) function hoisting. I DO like to code like:

The problem with that is that the assignment operator means two completely different things depending on whether the assigned value is a (literal) function or some other value. Personally, i dislike that sort of complexity on language constructs. If named functions where to be added, they should use some other syntactical form than the existing assignment.

**Comment by connec** [comment]
@avalanche1 cool, thanks for the references. I didn't realised anonymous function names were only available in V8.

Even if we started using named functions, which we could feasibly do in `2`, I don't think hoisting would change, since that would make a function assignment different from any other assignment, e.g. we would probably compile:

```coffee
doStuff = ->

doStuffWithThis = =>
```

into

```js
var doStuff, doStuffWithThis
doStuff = function doStuff () {}

// ruh roh, bound function syntax doesn't allow for a name
doStuffWithThis = () => {}
```

SO I'm not sure the status of this issue should change, `carlsmith`'s comment above still stands - we can't reliable add names to all functions, to we just have to wait for JS engines to catch up with the spec. Discussions of a "named function declaration" syntax have ranged back and forth over the years, but those discussions are independent of IE6.

**Comment by penne12** [comment]
Wait a second.... just noticed that CoffeeScript infact **does** support named functions currently. It's just not pretty.

```
class namedFunction then constructor: ->
    doSomething()
```

compiles to:

```
var namedFunction;

namedFunction = (function() {
  function namedFunction() {
    doSomething();
  }

  return namedFunction;

})();
```

making `namedFunction` a named function. Yay!

Sadly, that pollutes the global namespace. Instead, you can just do this, which returns the named function & doesn't pollute the namespace:

    do -> class namedFunction then constructor: ->
      doSomething()

**Comment by vendethiel** [comment]
> Sadly, that pollutes the global namespace.

huh? how so?

**Comment by penne12** [comment]
@vendethiel I meant if you are using it globally...... maybe I'll make that a bit clearer.

**Comment by penne12** [comment]
@vendethiel that better?

**Comment by vendethiel** [comment]
> @vendethiel that better?

No. I don't see any difference.

> which returns the named function & doesn't pollute the local namespace:

Sure, but you still need to assign it to *something*. Which will "pollute" the local namespace much the same way.

> Or, you can just use Javascript interpolation

That also "pollutes" the local namespace the same way

**Comment by penne12** [comment]
@vendethiel 

Sure - but in some cases, you be passing a named function as an argument - idk. I guess I'll take out the whole part.

**Comment by vendethiel** [comment]
@jashkenas why reopen?

**Comment by jashkenas** [comment]
@GeoffreyBooth @lydell —

Now that IE8 and below aren't relevant anymore, is there a good reason why CoffeeScript 2.0 shouldn't bring back our old-school named-by-default functions everywhere?

**Comment by connec** [comment]
I'd be concerned about users expecting the same behaviour from bound functions, for which there is no named syntax.

With the rules of the ES spec named functions are basically redundant in CS (where an assignment is needed for the name anyway).

**Comment by jashkenas** [comment]
> I'd be concerned about users expecting the same behaviour from bound functions, for which there is no named syntax.

Huh? That's not true. We can put names on bound functions in exactly the same way as unbound ones:

```coffeescript
hello = ->
```

```javascript
hello = function hello() {};
```

```coffeescript
hello = =>
```

```javascript
hello = (function(_this) {
  return function hello() {};
})(this);
```

**Comment by jashkenas** [comment]
Oh, of course -- sorry. I forgot about those.

**Comment by avalanche1** [comment]
@jashkenas what about function hoisting? let's also support that!

**Comment by GeoffreyBooth** [comment]
@jashkenas We were discussing named classes [here](https://github.com/jashkenas/coffeescript/pull/4354#discussion_r89940008) in the CS2 reimplementation of classes. Basically the CS2 version of classes will output code like `var Foo; Foo = class Foo {`. I was suggesting that if we’re doing this, we should be consistent and do the same for functions.

So yes, I think function declarations like `var foo; foo = function foo () {` would be great. Even if we can’t do it in all circumstances, we might as well do it where we can to make debugging easier. I’m not worried about the increase in file size, because CS output wasn’t meant to be minified in the first place, and a minifier would make short work of this duplication.

**Comment by mauskin** [comment]
> what about function hoisting?

@avalanche1 It was clearly pointed out that [function declaration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function) (or hoisting) is not a part of this thread. Please create a separate issue where we could have a focused discussion about its necessity and implementation.

**Comment by avalanche1** [comment]
well, function hoisting without named functions doesnt make sense to me - so I'll wait if named functions are set upon as an agreed solution - than I'll make a sep request if it's needed.

**Comment by ionewt** [comment]
This thread might be a github record! Not sure when github started, lol. 2009!

**Comment by ionewt** [comment]
I'm not actually joking... Github started in 2008, so this may actually be the longest running active thread on github, dunno.

**Comment by avalanche1** [comment]
WHOA! Super duper kool!
I've just found that named functions DO EXIST in Coffeescript. And they ARE hoisted to!!
```
f()
f = foo = ->log arguments.callee.name
// foo
```

**Comment by penne12** [comment]
@avalanche1 That's not coffee script - it's the browser doing it for you, and it has limited support (and is undocumented behavior). This issue still should be worked on to make it work in all browsers.

**Comment by avalanche1** [comment]
@penne12 
huh?
1. Don't spoil all the happines!
2. Care to explain!

**Comment by penne12** [comment]
Oops... sorry bout that 😨 

Anyways, basically, a named function looks like this:

```js
function namedFunction(){
  // this is a namedFunction
}
```

But, with your example, CoffeeScript generates:

```js
var f, foo;

foo();

foo = f = function() {
  return log(arguments.callee.name);
};
```

Which means that the function isn't named - but some browsers will assume the name based on what they're assigned too, but not always. 

In terms of hoisting, CoffeeScript is smart and declares variables the first time they're used, and many browsers will do a "first past" while parsing Javascript to define variables before running the rest of the code (as far as I understand it, maybe someone more familiar with the inner workings of the language could explain better). 

**Comment by avalanche1** [comment]
I see.
Does this feature have a name? So that I can lookup JS engine compatibility?

**Comment by GeoffreyBooth** [comment]
@avalanche1 It’s not a feature with a name like you would find in an ES6 compatibility table. I would refer to it as debugging tools inferring anonymous function names from their assigned references. See https://www.bennadel.com/blog/2836-anonymous-functions-assigned-to-references-show-up-well-in-javascript-stack-traces.htm

**Comment by avalanche1** [comment]
Ahem, after further investigating, it turns out that what I've posted above is actually void.
I was testing aforementionned techniques in Coffeescript Console extension for Chrome;
On the first run everything it throws en error, on the second, though - it works as described above.
Guess, that's the effect of working till 3AM.

Anyway, still no function hoisting; function names inferred from variable assignement works only if JS engine supports it.

**Comment by penne12** [comment]
Here's a simple little script if you want to force names onto functions, but this uses runtime evaluation, and might not be the best choice except in some very specific scenarios.

```coffee
nameFunc = (n, func) ->
  new Function("func",
    "return function #{n}(){return func.invoke(this, Array.prototype.slice.call(arguments))}"
  )(func)
```

Then just:

```coffee
nameFunc 'namedFunc', (a) -> console.log a
```

might be somewhat broken, also shouldn't be used for user input.

**Comment by avalanche1** [comment]
@penne12 , thanks mate!
Thankfully my dev environment supports named functions. And I'll make sure not to use them in production builds.

**Comment by GeoffreyBooth** [comment]
Per #4531, it was decided that CoffeeScript will not be supporting function declarations (outputting `function foo()` as opposed to `foo = function ()`) or outputting named functions as part of the currently output function expressions (so still `foo = function()`, not `foo = function foo()`).

**Comment by dotnetCarpenter** [comment]
@GeoffreyBooth I was cleaning up [an old coffeescript project](https://github.com/geejs/gulp-tap/) and came across `arguments.callee`, because coffeescript does not have support for named functions.

```coffee
if obj instanceof baseStream && !obj._readableState.ended
  obj.on('end', next)
  obj.on('data', ->
    obj.removeListener('end', next)
    obj.removeListener('data', arguments.callee)
    next()
  )
else
  next()
```

In es5 you would do:

```js
if (obj instanceof baseStream && !obj._readableState.ended) {
  obj.on('end', next)
  obj.on('data', function data() {
    obj.removeListener('end', next)
    obj.removeListener('data', data)
    next()
  })
} else
  next()
```

**If coffeescript had support for named functions**, you could do:

```coffee
if obj instanceof baseStream && !obj._readableState.ended
  obj.on('end', next)
  obj.on('data', \data ->
    obj.removeListener('end', next)
    obj.removeListener('data', data)
    next()
  )
else
  next()
```

Which is a nicer than:
```coffee
if obj instanceof baseStream && !obj._readableState.ended

  # don't inline event handlers in coffeescript (no support for named functions)
  # arguments.callee is deprecated so don't use it to remove event handler
  data = () ->
    obj.removeListener('end', next)
    obj.removeListener('data', data)
    next()

  obj.on('end', next)
  obj.on('data', data)
else
  next()
```

The **`\name`** is the anti _Lambda Abstractions_ hehe ;). Joke aside, I don't know how the syntax should be, but **\\** is an anonymous function in Haskell, so perhaps it could be a named function in coffee.

**Comment by connec** [comment]
What's wrong with

```coffee
if obj instanceof baseStream && !obj._readableState.ended
  obj.on('end', next)
  obj.on('data', data = ->
    obj.removeListener('end', next)
    obj.removeListener('data', data)
    next()
  )
else
  next()
```
