### ISSUE TITLE
New escape javascript (`) token

### ISSUE THREAD

**Issue by matthewmueller** [jashkenas/coffeescript#1504]
I'm building an asset bundler that can merge both coffeescript and javascript together. It works fine placing coffeescript inside javascript -- compile it and stick it in the js file. 

The problem I'm running into is when I try to include javascript into coffeescript. My approach was to bring in the javascript, escape with **`**, and then compile the coffeescript.

The problem is _many_ libraries use **`** in comments -- including backbone. One thought is to use **```** to escape javascript like comment blocks in coffeescript.

Please let me know your thoughts on this.

**After some discussion:** The whole point of this issue is to point out that the single backtick _does not always_ work the way it's intended. Use cases and outside discussion should be irrelevant here. Currently, the backtick does not work if you try to escape a file like backbone or jquery or even a two line javascript file that has a comment that includes a backtick. 

Thanks,
Matt

**Comment by rstacruz** [comment]
Just chiming in to bump this for 2 reason:

1) ES6 will have template strings made using backticks, ie, `` a = `Hello, ${name}` ``.

2) We've been working on a new [js2coffee](http://js2.coffee) that uses `` ` `` extensively when "compatibility mode" is on to preserve JS behavior in things it can't translate (eg, `==`). It would be nice to make backticks escapable in case they're converting ES6.

**Comment by rstacruz** [comment]
Also, GitHub markdown uses backticks to escape code, and it lets you surround text with as many `` ` ``s as you need so to allow backticks inside the strings:

`` `code` ``
``` `` code with ` backticks `` ```
```` ``` code with `` and ` backticks ``` ````

**Comment by jashkenas** [comment]
Escapable backticks plus here-backticks would be nice to have.

**Comment by runemadsen** [comment]
+1

**Comment by varblob** [comment]
+1 
backticks are becoming a thing in ember for inline template compilation.  It would be really nice to be able to escape a backtick either `\`` -> ` or the markdown way.

**Comment by guigrpa** [comment]
+1

**Comment by nickdima** [comment]
Would changing [this line](https://github.com/jashkenas/coffeescript/blob/master/src/lexer.coffee#L255) from:
```coffee
@token 'JS', (script = match[0])[1...-1], 0, script.length
```
to
```coffee
@token 'JS', (script = match[0])[1...-1].replace(/\\`/g,'`'), 0, script.length
```
be enough for escaping backticks?
It seems to work but maybe I'm missing something.

**Comment by guigrpa** [comment]
This is a really important feature, considering how the lack of convenient JavaScript escaping prevents the use of CoffeeScript with, for example, Relay (a complement to React). Currently, I'm being forced away of CoffeeScript, and into the extremely verbose realm of ES6, by this single little feature. After 2+ years with CoffeeScript and a huge codebase, it's not so easy :(

An example of what should be possible to embed in CoffeeScript:

```javascript
var fragments = {
  viewer: () => Relay.QL`
    fragment on Viewer {
      projects { edges { node {
        id, name
      }}}
    }
  `,
};
```

Any chance this 2-year issue might get some love? ;)

**Comment by nickdima** [comment]
@guigrpa what you could do meanwhile this gets figured out is to keep the queries in a separate JS file and require them from your components. I know the query is supposed to stay inside the component itself but at least it works for now...

**Comment by guigrpa** [comment]
@nickdima That's a good workaround, thanks!

**Comment by guigrpa** [comment]
@nickdima What about the fix for escaping backticks you suggested above (Oct 2, 2015)? Did it indeed solve the bug mentioned by @michaelficarra?

**Comment by vendethiel** [comment]
It doesn't escape escaped escapes (...), but it should work for simple cases, I guess.

**Comment by bdkjones** [comment]
Just to clarify: is there any official strategy for handling backticks (especially those in ES6) or is CoffeeScript kinda saying, "Meh, screw it."? Just trying to plan and can't keep straight the various issues referencing this problem. It's been 4 years, so I'm guessing the CoffeeScript team just doesn't care?

**Comment by bjmiller** [comment]
CS already has the template string feature using double quotes.  You don't want to emit an ES6 template string.  Just code it to work that way in CS to begin with.

**Comment by vendethiel** [comment]
No, I think it's about ```foo(f``)```

**Comment by langri-sha** [comment]
@bjmiller without additional support for escaping backticks, this makes testing JS tag functions in CS impossible, since a template string cannot be provided.

**Comment by lydell** [comment]
@langri-sha Not _impossible,_ just inconvenient.

```
> JSON.stringify(((...a)=>a)`a${1}b${2}c${3}${4}`)
"[["a","b","c","",""],1,2,3,4]"
```

You can test tag functions by calling with an array of all string parts and then each interpolation as separate arguments.

**Comment by langri-sha** [comment]
@lydell ahh, thank you for taking the time to explain! It's very obvious once you clearly point it out, but my initial attempt was to escape JS and backslash-escape the backticks therein. It's a harsh blow, not understanding how template strings can be built from other primitives and CS not meeting your expectations at the same time.

```
reality = [['', '', '', ''], 0, 'bar', quux]
anewhope = `\`${0}${'bar'}${quux}\``
theforceawakens = anewhopepart2 = ```${0}${'bar'}${quux}```
```

**Comment by langri-sha** [comment]
Hello again all. I've found that writing the backtick in one of the supported escape sequences is a quick way to make friends with the compiler. The hexadecimal escape sequence for the backtick is `\x60`, the unicode is `\u0060`.

```
# Smallest example of how to output a backtick in your code.
`\u0060`
```

Now, this only gets you half way to writing template strings, since JS sources do not support escape sequences and you will get a `SyntaxError`. The last bit missing is to pass it to something that can evaluate raw strings as sources, like `eval` or `Function`.

```
horray = "huzzah"
alert `eval("\u0060${horray}!\u0060")` # huzzah!
```

**Comment by huan-ji** [comment]
@langri-sha Any idea how this would work in the case of Relay queries mentioned by @guigrpa ?

**Comment by guigrpa** [comment]
@huan-ji Sad to say this, but this was just one of the issues that finally triggered my conversion to ES6. I miss CoffeeScript's terse syntax, though.
