### ISSUE TITLE
Default function argument: empty function

### ISSUE THREAD

**Issue by jeremywarne** [jashkenas/coffeescript#1510]
If you're defining a function with multiple callbacks, it doesn't seem that you can do more than one with a default value of an empty function (->)

example:

ajaxFunction = (data, success = ->, failure = ->)  ->
    # handle ajax function using success and failure as callbacks

Am I missing something or should this work? It does work if only the last argument has a default:

ajaxFunction = (data, success, failure = ->)  ->
    # this compiles OK

**Comment by shramee** [comment]
Thanks @michaelficarra 👍
