### ISSUE TITLE
Performance impact by using arguments array

### ISSUE THREAD

**Issue by niclashoyer** [jashkenas/coffeescript#1519]
Hi,

there has been some discussion about a performance impact when using the arguments array in some way, because the jit compilers can't optimize some usages.

See https://plus.google.com/111090511249453178320/posts/ikjTyY6UKcE and there were changes in node.js that replaced calls to Array.prototype.slice with a for loop, see this commit: https://github.com/joyent/node/commit/91f1b250ecb4fb8151cd17423dd4460652d0ce97

Does this also have an effect on coffeescript? Maybe coffeescript should compile any usage of the arguments array in a different way? I don't know if compiler developers are going to solve this issue.

**Comment by vendethiel** [comment]
folding into #3274
