### ISSUE TITLE
Application and binding/currying operators

### ISSUE THREAD

**Issue by alexkg** [jashkenas/coffeescript#1520]
I've been working on a couple of operators for function application. The branch is available [here](https://github.com/alexkg/coffee-script/compare/master...alexkg%2Fapply).

The first operator `<-` applies the function on the left to the arguments on the right.

The second operator `<~` is similar except it binds the function on the left and partially applies it to the arguments on the right.

Here are a couple of examples:

```
f <-
# f()

f <- x, y
# f(x, y)

f <~ x, y
# __curry.call(f, x, y)

o.f <~ x, y
# __curry.call(__bind(o.f, o), x, y)
```

The implementation of __curry is as follows:

```
function () {
  var f = this, xs = Array.prototype.slice.call(arguments);
  return function () {
    var ys = Array.prototype.slice.call(arguments);
    return f.apply(this, xs.concat(ys));
  }
}
```

The operators touch on a number of issues including:

[The deprecated binding/currying operator](https://github.com/jashkenas/coffee-script/issues/431)
[Indentation as application](https://github.com/jashkenas/coffee-script/issues/1355)
[Parameterless function calls](https://groups.google.com/forum/#!topic/coffeescript/NZAs6552Sc8)
[Avoiding parentheses](https://github.com/jashkenas/coffee-script/issues/1614)

Now for the tour...

The operators are left associative:

```
f <- x, y <- z
# f(x, y(z))
```

Complex nested calls can be defined without parentheses:

```
a <-
  b <-
    c <- d, e <- f
    g <- h, j <- k
  l <- m, n,
    o <- p
    q <- r

###
a(
  b(
    c(d, e(f)),
    g(h, j(k))
  ),
  l(m, n,
    o(p),
    q(r)
  )
)
###
```

The following section from src/rewriter.coffee:

```
not token.generated and @tag(i - 1) isnt ',' and (tag in IMPLICIT_END or
(tag is 'INDENT' and not seenControl)) and
(tag isnt 'INDENT' or
 (@tag(i - 2) isnt 'CLASS' and @tag(i - 1) not in IMPLICIT_BLOCK and
  not ((post = @tokens[i + 1]) and post.generated and post[0] is '{')))
```

Can be written as:

```
where = (args...) ->
  args.reduce (x,y) -> x and y

either = (args...) ->
  args.reduce (x,y) -> x or y

where <-
  not token.generated
  @tag(i - 1) isnt ','
  either <-
    tag in IMPLICIT_END
    tas is 'INDENT' and not seenControl
  either <-
    tag isnt 'INDENT'
    where <-
      @tag(i - 2) isnt 'CLASS'
      @tag(i - 1) not in IMPLICIT_BLOCK
      not ((post = @tokens[i + 1]) and post.generated and post[0] is '{')
```

We can use the curry operator to partially apply a function:

```
sum = (args...) ->
  args.reduce (x, y) -> x + y

f = sum <~ 1, 2
g = f <~ [3, 4]..., 1
console.log g <- # => 11
console.log g <- 100 # => 111
```

The operator will bind if the given function is bound to an object:

```
goon = 
  status: 'drunk'
  toString: -> @status

status = goon.toString <~
console.log status <- # => 'drunk'
```

We can bind and curry at the same time:

```
xs = []
append = xs.push <~ 1, 2, 3
append 4, 5, 6
console.log xs # => [1,2,3,4,5,6]
```

We can bind a function to an arbitrary receiver by currying the first argument to `call`:

```
some.function.call <~ receiver
```

For example:

```
queue = new ->
    @length = 0
    @push = Array.prototype.push.call <~ @
    @pull = Array.prototype.shift.call <~ @
    this

queue.push 1, 2, 3
console.log queue.pull <- # => 1
console.log queue.pull <- # => 2
console.log queue.pull <- # => 3
```

The operators can be used anywhere normal function application can be used.

Post-control:

```
f <- if b
# f() if b

f <- for x in xs
# f() for x in xs
```

Expression and splat arguments:

```
f <- if b then 5 else 6
# f(b ? 5 : 6)

f <- 1, [2, 3, 4]..., 5
# f(1, [2, 3, 4]..., 5)
```

As an argument to another function:

```
eq f <-, g <-
# eq f(), g()

eq 5, f <- 6, 7
# eq 5, f(6,7)
```

Part of the motivation was to have more robust class methods:

```
ID = (x) -> x

class Collection
  @map = (f, coll) ->
    result = @zero <-
    @each <-
      (e, i) => @cons result, f(e, i), i
      coll
    result

class Hash extends Collection
  @zero = -> {}
  @cons = (coll, e, i) -> coll[i] = e
  @each = (f, coll) ->
    f <- e, i for i, e of coll
    undefined

# Though the implementation of @map uses @zero, @cons, and @each,
# it can be isolated and used independently:
copy = Hash.map <~ ID

original = a:1
impostor = copy original

console.log original.toString() is impostor.toString() # => true
console.log original is impostor # => false
```

As you can see, the operators are quite versatile. I'm currently writing a charting library so I will be able to add more tests and examples in the next week or so.

Cheers, Alex.

**Comment by GeoffreyBooth** [comment]
Closing as there doesn’t appear to be much interest in this proposal lately. If someone wants to submit a PR it would be considered.
