### ISSUE TITLE
CoffeeScript `use strict`

### ISSUE THREAD

**Issue by geraldalewis** [jashkenas/coffeescript#1547]
# use strict

ECMAScript 5 introduces a `strict` mode that reduces bugs, increases security, and eliminates some difficult to use language features. The coding standards `strict` mode requires should be adopted by CoffeeScript.

---
### Better Code

CoffeeScript emits lowest common denominator JavaScript. From a different angle: CoffeeScript emits JavaScript that is not implementation specific. Just as there are constraints on output imposed by IE6's nonconforming behavior (no `function declaration`s), there too should be constraints on input imposed by _better engineered_ environments.
### User Expectations

CoffeeScript throws errors when it encounters syntax errors (e.g., one can't write `-> return return`). A user employing the `use strict` directive will expect to see syntax errors at compile time (pre-evaluation), just as they would in a JavaScript environment.
### Best Practices

CoffeeScript emits JavaScript that adheres to best practices. ES5 `strict` codifies many best practices, and fixes some unsafe and error-prone operations. CoffeeScript already shares some constraints with `strict` (e.g., no `with`) and fixes others that `strict` targets (e.g., in CoffeeScript, vars are auto-declared for variable safety).
## Early Errors

["Early errors"](http://es5.github.com/#x16) are syntax errors detected prior to evaluation (all others are **runtime** errors). _Most_ `strict` mode errors are syntax errors (of type `SyntaxError`). CoffeeScript should only check for these types of errors. [16 Errors](http://es5.github.com/#x16) states:  "**An implementation shall not treat other kinds of errors as early errors** even if the compiler can prove that a construct cannot execute without error under any circumstances" (emphasis mine). 
### Early Strict Syntax Errors

The following CoffeeScript snippets would be considered "early errors" under ES5 `strict`.

[**7.8.3** Numeric Literals](http://es5.github.com/#x7.8.3)

```
oct = 0121            # octals
```

[**B.1.2** String Literals](http://es5.github.com/#B.1.2)

```
octEscSeq = "\121"    # octal escape sequences
```

[**11.1.5** Object Initialiser](http://es5.github.com/#x11.1.5) 

```
x: 1, x: 1            # duplicate prop names in object literal
```

[**11.4.1** The delete Operator](http://es5.github.com/#x11.4.1) 

```
x = 1; delete x       # delete var
delete undefined      # delete undefined 
(x)-> delete x        # delete function argument 
```

[**13** Function Definition (13.1 Strict Mode Restrictions)](http://es5.github.com/#x13)

```
(x,x)->               # duplicate formal param
```

[**7.6.1.2** Future Reserved Words](http://es5.github.com/#x7.6.1.2)

```
implements = 1        # assigning to future reserved keyword
interface = 1
let = 1
package = 1
private = 1
protected = 1
public = 1
static = 1
yield = 1
```

**`eval` and `arguments` restrictions**

[**12.14** The try Statement (12.14.1 Strict Mode Restrictions)](http://es5.github.com/#x12.14)

```
try e catch eval      # catch identifier eval
try e catch arguments # catch identifier arguments
```

[**13** Function Definition (13.1 Strict Mode Restrictions)](http://es5.github.com/#x13.1)

```
(eval)->              # identifier "eval" in formal params
(arguments)->         # identifier "arguments" in formal params
class eval            # function declaration `function eval(){}`
class arguments       # function declaration `function arguments(){}`
```

[**11.13.1** Simple Assignment](http://es5.github.com/#x11.13.1)

```
eval = 1              # assigning to eval
arguments = 1         # assigning to arguments
```

[**11.3.1** Postfix Increment Operator](http://es5.github.com/#x11.3.1)

```
eval++                # incrementing eval
arguments++           # incrementing arguments
```

_&nbsp;&nbsp;as well as Postfix Decrement and Prefix Increment and Decrement_

---
### What Users Would Give Up

Some coding conventions would need to be abandoned, namely:

**Identical param names**  
- used for parameters that are not germane to the function's body
- useful in callbacks

e.g.,  

```
(_,_,_,buffer) -> #read buffer
```

However, as @jashkenas stated "_...is a serious antipattern. For the reader who comes across your function, intending to modify it ... not only are they unable to use the first three parameters -- they also have not the slightest clue what the parameters might be._"

@satyr also offered a workaround: `({},{},{},buffer) -> #read buffer` would still be legal

**Identical prop names in object literals**
- could be useful for debugging

@satyr's example:  

```
o =
  a: console.debug "before a"
  a: getA()
  b: console.debug "before b"
  b: getB()
```

I'd argue that it's likely this feature is more often the cause of bugs `foo: 1, bar: 2, bar: 3 # user meant 'baz'` and catching those errors would outweigh its other uses.

(and one could still write):

```
o =
  a: do -> console.debug "before a"; getA()
  b: do -> console.debug "before b"; getB()
```

**Sources/More Information**
[Annotated ES5 Spec](http://es5.github.com/)
[ES5 Spec: Annex C "The Strict Mode of ECMAScript "](http://es5.github.com/#C)
[JavaScript Strict Mode Tests](http://pastebin.com/bd5Z2XuE)
[ECMA-262-5 in detail. by Dmitry Soshnikov](http://dmitrysoshnikov.com/ecmascript/es5-chapter-2-strict-mode/)
[ES5 Browser Compatibility Table by @kangax](http://kangax.github.com/es5-compat-table/strict-mode/)

**Comment by dannyphung** [comment]
+1 : Cannot delete any variable. 
```
-module.coffee:101:5: error: delete operand may not be argument or var
    delete   parser
    ^^^^^^^^^^^^^^^
    L100:     delete   parser
```
