### ISSUE TITLE
Shortcut for array[array.length - 1]

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/coffeescript#156]
While implementing the parser, I've often wished that CoffeeScript supported negative array indexes, to peek at elements towards the end.

```
last: array[-1]
```

Do you all think it would be a worthwhile addition?

**Comment by lydell** [comment]
In my opinion, the only thing that needs a shortcut here is a way to get the last element of an array as a single expression.

Want the next to last element? Use `[..., nextToLast, last] = arr; doSomethingWith nextToLast`.

Need to get an element at a possibly negative index? Use `arr = someArray` followed by `arr[if index < 0 then arr.length + index else index]` or `arr[index %% arr.length]` or whatever is appropriate for your case.

Want the last element? Idea: Use `arr[]`. `if items[].beautiful? then console.log 'go for it!' else throw new SyntaxError`.

**Comment by carlsmith** [comment]
SugarJS does the `last` thing suggested by @brookr: No args gets the last item, or you can pass a number. `list.last 4`. It's nice to use. If you don't want to extend prototypes, using a function is an ok option, `last 4, list`.

Negative indexes are really nice to have, but they're problematic to implement, easy to live without, and we often end up wrapping their use with functions anyway. `+0`

**Comment by xavieryao** [comment]
Sounds really great.
