### ISSUE TITLE
Inconsistencies in `prototype` shorthand (::) and `this` shorthand (@)

### ISSUE THREAD

**Issue by geraldalewis** [jashkenas/coffeescript#1601]
### The `::` `.prototype(.)` shorthand should behave consistently with the `@` `this(.)` shorthand.

Adding symmetry in how each shorthand is implemented will give developers a better mental model of their behavior and reduce issues.

`@`  currently compiles to a literal `this`, access `this.` or invocation `this(` depending on context.
`::` [currently](https://github.com/jashkenas/coffee-script/pull/1590) compiles to a literal `.prototype` or access `.prototype.` depending on context. 
It does not compile to an invocation. 

`@` will not behave as `::` in every context. Below is a breakdown of where they behave consistently and where they behave inconsistently.

---

**Consistent**

```
# JavaScript output indicated in comments
# code wrapped in -> as :: can indicate a line continuation
```

as value _(unless :: standalone)_  

```
-> @              # this
-> C::            # C.prototype
```

member access _(unless :: standalone)_  

```
-> @member        # this.member
-> C::member      # C.prototype.member
```

index  

```
-> @['member']    # this['member']
-> C::['member']  # C.prototype['member']
```

applying `::`  

```
-> @::   # this.prototype
-> C:::: # C.prototype.prototype
```

**Inconsistent**

invocation  

```
class C; C:: = (a) -> console.log a

-> @ 'invoke'     # this('invoke');
-> C:: invoke     # C.prototype.invoke; // (acts as member access)
# -> C:: 'invoke' # error (unexpected 'STRING')
```

list comprehensions  _(from #1477 by @dbrans)_

```
for k of @ when k isnt constructor then   # for (k in this) { if (k !== constructor) {} }
for k of A:: when k isnt constructor then # for (k in A.prototype.when(k !== constructor)) {}
```

instanceof  

```
@ instanceof C   # this instanceof C;
C:: instanceof B  # C.prototype["instanceof"](B);
```

standalone  

```
-> @              # this
# -> ::           # error; any use-case?
```

standalone member access  

```
-> @member        # this.member
# -> ::member     # error; any use-case?
```

---
### Proposal

`::` should:  
- still raise an error if used standalone
- behave like `@` in all other ways:
  - not indicate a line continuation
  - work in list comprehensions
  - ~~be callable~~ **Edit: See @jashkenas comment**  
    (it technically is, but it looks like [this line](https://github.com/jashkenas/coffee-script/blob/master/src/lexer.coffee#L83) prevents implicit calls)

**or**
- `::` should always compile to `.prototype.`
- `@`  should always compile to `this.`
- `@`  should continue lines 

_Personally, I'm in favor of `#1`_

---

Related issues: #1477, #1554 (fixed), #1234 (fixed)

**Comment by otse** [comment]
I have an extended class `Klas`, and I want `Klas`'s to use its own method `foo`, not the override-`foo`

I achieve this with `Klas::foo.call this, param`. Good form ye?

**Comment by GeoffreyBooth** [comment]
Skimming through this thread, I don’t see a consensus on any action to be taken as a result of the original proposal. If I’m mistaken on this please comment and I’ll reopen, but at this point if anyone desires further changes to `::` it’s probably best to start a new issue with a concise proposal concretely defined.
