### ISSUE TITLE
super should be accessible within sub-functions of class methods

### ISSUE THREAD

**Issue by devongovett** [jashkenas/coffeescript#1606]
Right now the following CoffeeScript generates the error "cannot call super on an anonymous function":

```
class Test extends Foo
  method: ->
    setTimeout -> 
      super
      # ...
    , 1000
```

This makes sense for anonymous functions outside the scope of a class, but for those within class methods, like the one above, I think super should still be accessible.  How difficult would this be to implement?

**Comment by shaunc** [comment]
+1 ... hmm... no progress or comments on this for a while. Is there a hitch?

**Comment by ncodeIO** [comment]
+1 Would be good

**Comment by Blasz** [comment]
+1 Having to resort to `__super__` and `apply` to use fairly standard OOP functionality seems to go against what coffeescript is about.

**Comment by lydell** [comment]
@Blasz couldn't you have resorted to a `=>` function?

**Comment by Blasz** [comment]
@lydell I was referring to `super.method` instead of the subfunctions mentioned in the OP.

**Comment by mitar** [comment]
Hm, but `arguments` are then those of the inside function, not the method. :-(

**Comment by GeoffreyBooth** [comment]
This [works in CS2](http://coffeescript.org/v2/#try:class%20Test%20extends%20Foo%0A%20%20method%3A%20-%3E%0A%20%20%20%20setTimeout%20-%3E%20%0A%20%20%20%20%20%20super()%0A%20%20%20%20%20%20%23%20…%0A%20%20%20%20%2C%201000):

```coffee
class Test extends Foo
  method: ->
    setTimeout -> 
      super()
      # …
    , 1000
```
