### ISSUE TITLE
Implicit function calls can't accept functions as arguments

### ISSUE THREAD

**Issue by kitcambridge** [jashkenas/coffeescript#1611]
**Outsider** [reported this issue](http://groups.google.com/group/coffeescript/msg/d81390050f2906ad) on the Google Group...I'm not sure if this is intentionally disallowed or simply a bug, but [Coco](http://satyr.github.com/coco) compiles both examples correctly.

```
% coco -bpe "func (x) -> x, (y) -> y"
func(function(x){
  return x;
}, function(y){
  return y;
});

% coffee -bpe "func (x) -> x, (y) -> y"
Error: Parse error on line 1: Unexpected ','

% coco -bpe "func((x) -> x, (y) -> y)"
func(function(x){
  return x;
}, function(y){
  return y;
});

% coffee -bpe "func((x) -> x, (y) -> y)"
Error: Parse error on line 1: Unexpected ','
```

Wrapping both functions in parentheses eliminates the parse error.

```
% coco -bpe "func ((x) -> x), ((y) -> y)"
func(function(x){
  return x;
}, function(y){
  return y;
});

% coffee -bpe "func ((x) -> x), ((y) -> y)"
func((function(x) {
  return x;
}), (function(y) {
  return y;
}));
```

**Comment by GeoffreyBooth** [comment]
Closing as this isn’t really a bug. If someone wants to enable support for functions as parentheses-less arguments, a PR would be welcomed.
