### ISSUE TITLE
reconstruction feature

### ISSUE THREAD

**Issue by mark-hahn** [jashkenas/coffeescript#1617]
I have asked for this before but I have now run into about a dozen places in my app where I have code like this (production code) ...

```
view = 
    id: doc._id
    thread: doc.thread
    lastEdited: doc.lastEdited
    name: doc.name
    posted: doc.posted
    html: doc.html
    ptrNum: ptrNum
    okToEdit: (doc.author is userId)
```

... and I would really like to shorten it to ...

```
view = {id, thread, lastEdited, name, posted, html, 
        ptrNum:ptrNum, okToEdit: (doc.author is userId)} = doc
```

This allows one to select a subset of an object to create a new object.  I do this all the time.  In this particular example it is doing deconstruction  and then reconstruction in one operation.

I don't really care what the syntax is, I just don't want to repeat the source object over and over.  Another syntax option would be something like this (just replace the right = with "in") ...

```
view = {name, id, age}  in  doc
```

The token "in" could be any token/operator that doesn't break the language.  The token means "use the following as the default object for this constructor instead of the local scope".

Each time I write code like this I pine for the feature more and more.  How hard would it be to add this feature?  I would be willing to spend whatever time it takes to code this for a pull request.

**Comment by GeoffreyBooth** [comment]
Closing this request as it’s not a priority at the moment. That said, if someone feels like implementing this as a PR that doesn’t introduce any breaking changes, it would be considered.
