### ISSUE TITLE
Existential/conditional statement returning the value that was checked

### ISSUE THREAD

**Issue by nevir** [jashkenas/coffeescript#1618]
I'm have a really hard time describing this guy in words, so here's some example patterns that I find are prevalent (at least in my code):

```
thing.foo = bar if bar

return baz if baz

raise blargh if blargh
```

etc.  Would it make sense to add some syntactic sugar for this case?  Something like

```
thing.foo = ?if bar

return ?if baz

raise ?if blargh
```

(Further muddying up the existential operator seems a bit awkward, but I don't have any better syntactic ideas yet)

**Comment by GeoffreyBooth** [comment]
There doesn’t appear to be much interest in this proposal, however a pull request implementing it would be considered.
