### ISSUE TITLE
Docs: enhance documentation of existential operators

### ISSUE THREAD

**Issue by michaelficarra** [jashkenas/coffeescript#1631]
Right now, the documentation for our existential operators is either poor or non-existent. We should list all of the following operators along with proper definitions of their behaviour and possibly individual names (taken from #1613, the issue that inspired this one):
- unary `?`:
  - `a?` tests that `a` is in scope and `a != null`
- binary `?`:
  - `a ? b` returns `a` if `a` is in scope and `a != null`; otherwise, `b`
- `?.` and `?[ ]`: soaked property access:
  - `a?.b` or `a?['b']` returns `a.b` if `a` is in scope and `a != null`; otherwise, `undefined`
- `?( )`: soaked function invocation:
  - `a?(b, c)` (or `a? b, c`) returns the result of calling `a` (with arguments `b` and `c`) if `a` is in scope and callable; otherwise, `undefined`
- `?=`: existential assignment:
  - `a ?= b` assigns the value of `b` to `a` if `a` is not in scope or if `a == null`; produces the new value of `a`

Some particular parts of the current documentation that bother me:
- "fails for zero, the empty string, and false"
  - the list should be exhaustive or somehow acknowledge that it is not
- "returns true unless a variable is null or undefined"
  - doesn't mention how undeclared variables are handled
- doesn't really distinguish between the different operators

**Comment by GeoffreyBooth** [comment]
Done in #4536.
