### ISSUE TITLE
advanced object construction: obj.{ prop0: a, prop1: b } or similar

### ISSUE THREAD

**Issue by michaelficarra** [jashkenas/coffeescript#1632]
I wanted to start a discussion about the syntax mentioned in the title and [originally on es-discuss](https://mail.mozilla.org/pipermail/es-discuss/2011-August/016187.html). It produces a modified clone of an object. So I'd like to hear whether people would have a use for it, how well it will play with other features, and exactly how we'd like it to compile/behave. I'd recommend at least reading the linked thread from es-discuss.

I believe the suggested syntax `obj.{ a: b, c: d }` is equivalent to [Coco](https://github.com/satyr/coco)'s `{...obj, a: b, c: d}`, which is another possible syntax we can consider. Coco's syntax actually has a few advantages over the one above:
- the ability to set defaults: `{a: b, ...o, c: d, e: f}`
- the ability to use other objects in place of keys: `{...defaults, ...o, ...overrides}`
- the curly braces on the outside as a visual signifier that a new object is being created

Though a negative of that syntax is the fact that it forces us to define merging semantics; something that's always a problem. But Coco's always-overwrite with only own-keys seems like a pretty sane choice.

**Comment by steffansluis** [comment]
So what is the status on this? I see this PR has been open for a long time, and it appears that everybody thinks it's a good idea to add something like this to CS. Is this a 'PR welcome' kind of situation, is there something in the works somewhere?

**Comment by danschumann** [comment]
It's getting to be that time...

**Comment by GeoffreyBooth** [comment]
Yes, this is a ‘PR welcome’ situation 😄
