### ISSUE TITLE
default arguments don't work with super

### ISSUE THREAD

**Issue by dwt** [jashkenas/coffeescript#1635]
With code like this:

```
class Foo
  constructor: (arg) -> console.log arg
class Bar extends Foo
  constructor: (arg='bar') -> super
```

the output is not 'bar' as the way that default arguments are implemented doesn't modify the arguments array which is nevertheless passed through to super.

I'm not sure how to fix this, could be that it just needs modifying the arguments array (not sure if that's possible) or constructing a fresh one from the signature of the method and the remaining entries from the arguments array.

**Comment by GeoffreyBooth** [comment]
Assuming that this is irrelevant now that we’re using native `super` in CS2.
