### ISSUE TITLE
put utility functions at the bottom of the script

### ISSUE THREAD

**Issue by weepy** [jashkenas/coffeescript#1638]
At the moment, CoffeeScript puts the utility functions at the top of the script (as it does with all other variables).  Unfortunately This causes the preamble of the file to be quite long - and it pushes line numbers further out. 

If named functions were used instead, the functions could be placed at the bottom of the file as they would still be in scope. 

Here's an example as a gist :   https://gist.github.com/1180503

**Comment by GeoffreyBooth** [comment]
As of #4526 we have only one-liner helper functions, so the readability issue is less urgent. This doesn’t appear to be a priority, so I’m closing the issue. If someone wants to submit a PR that improves things, it would be welcome.
