### ISSUE TITLE
soaks on lhs of assignment

### ISSUE THREAD

**Issue by mark-hahn** [jashkenas/coffeescript#1642]
It would be nice if this ...

```
a = {}
# b not defined
a.b?.c = 1
```

did this ....

```
a.b = {}
a.b.c = 1
```

It is very intuitive, doesn't break anything, and matches soaks on rhs in terms of handling missing properties.

**Comment by fernandortdias** [comment]
Thank you, @vendethiel, for finding all related issues (actuall, features requests) and closing mine (really). Although this one is already closed almos ten years already, I woud like to join and "refresh" the discussion mentioning that, for me, not having to declare a variable before it has a value assigned to it is a kind of a "autovivification", and if CS handles its variables its way, I see no reason for not behaving the same way for key-value pairs in objects, so no special compiler mode, directive or sintaxe should be needed to specify that autovivifaction is intended. For me, it signalled an inconsistent behaviour. At most, maybe turning off autovivification should be considered the exception, as it is the annotation of types on version 2.5.1. So, if @vendethiel or some of you guys enlisted as collaborators agree on my argument, maybe one of you would like to reopen this features request, or mine, or any one of the other related to them.
