### ISSUE TITLE
heregex compresses relevant spaces

### ISSUE THREAD

**Issue by hildjj** [jashkenas/coffeescript#1668]
It seems as if I should be able to use a space inside square brackets at least in a heregex:

```
i = '   aaa   '
a = ///
    [ ]+
    ///
b = /[ ]+/

# prints null
console.log a.exec(i)
# prints [ '   ', index: 0, input: '   aaa   ' ]
console.log b.exec(i)
```

As a workaround, one can use `[\x20]+`, but that is less readable.

**Comment by alinex** [comment]
Flipped over the spaces problem but found out that you may mask the space with an backslash to stay in your regexp:

    ///
      [\t\r\ ] # whitespace but no newline
    ///
