### ISSUE TITLE
object slice/reconstruction: pulling selected properties from an object

### ISSUE THREAD

**Issue by michaelficarra** [jashkenas/coffeescript#1708]
I would like to propose a syntax similar to one in #1632 for creating an object from specified properties of another object. This syntax would solve the same problem that the proposal in #1617 is trying to solve (and I briefly mentioned over there).

```
# proposed:
a = b.{c, d, e}
# current:
a = { c: b.c, d: b.d, e: b.e }
```

The only downside that I can find shows itself when you need to reference a dynamic property name:

```
# proposed:
a = b.{ "#{c}" }
# current:
_ref = null; a = {}; a[_ref = b[c]] = _ref
```

It's still a lot better than the current alternative. Though, we should probably only allow those dynamic properties if we also bring back dynamic property names in object literals.

This syntax is already available in [coco](https://github.com/satyr/coco), so you can try it out and see example compilations by using [cup](http://satyr.github.com/cup/). So, thanks @satyr.

**Comment by GeoffreyBooth** [comment]
A PR for this would be welcome.
