### ISSUE TITLE
Inconsistency in loop comprehensions

### ISSUE THREAD

**Issue by wavded** [jashkenas/coffeescript#1750]
e.g.

``` coffeescript
my_obj =
  attributes: i for i in [0..10]
```

and

``` coffeescript
  attributes = i for i in [0..10]
```

When using a comprehension on a property of an object I get back an array, however when using it on a regular assignment I get back the last value (10).  Seems like it should be one or the other.  My feeling is since its an array comprehension, it should return an array.  Thoughts?

**Comment by albertnetymk** [comment]
>  I'd love to direct you to the issue where we changed it to be this way, but I've no idea how to find it.

@michaelficarra I wonder what's the behavior before the change. The current semantics is favoring multiple assignment to the same variable, which is rarely what the developer wants, according my own development experience.
```
f = (v) -> v*2
x = f i for i in [1..10]
console.log x # 20
```

@wavded Maybe you have already discovered it, but still ...
```
[some,destructuring,assignment] = a for a in [0..2] # since = has high precedence, `some` gets assigned multiple times
somefunction a for a in [0..10] # no =, so no surprisings.
# others...
```

@showell It's nice that `for` and `if` behave similarly, but this behavior makes sense for `if`, but not so much for `for`.

**Comment by connec** [comment]
This is nice for concise `find` type operations:

```coffee
ok = true
ok = false for result in results when not_ok result
```

Though admittedly it'd be more efficient in those cases to expand the loop, and break as well:

```coffee
ok = true
for result in results when not_ok result
  ok = false
  break
```
