### ISSUE TITLE
"bare" attribute for type="text/coffeescript" script tags

### ISSUE THREAD

**Issue by mahemoff** [jashkenas/coffeescript#1792]
There are situations where bare compilation (equivalent to --bare, ie no closure) would be useful, so I'd propose an extra attribute on the script tag:

``` html
<script type='text/coffeescript' data-bare='true' src='foo.coffee'></script>
```

... where "data-bare" of course defaults to false.

A typical case is JSONP, where various frameworks auto-generate a local-scoped function. On such framework is Google's Ajax Feed API. Here's an example of a CoffeeScript which fails normally, but works with bare compilation:

CoffeeScript:

``` coffeescript
google.load 'feeds', '1'
init = ->
  console.log 'Yes it worked!'
google.setOnLoadCallback init
```

HTML:

``` html
<script type="text/javascript" src="https://www.google.com/jsapi?key=YOUR_KEY_HERE"></script>
```

**Comment by GeoffreyBooth** [comment]
As these script tags aren’t really intended for much use beyond CoffeeScript’s own docs (we expect everyone to be compiling to JavaScript and possibly further transpiling and minifying) we don’t plan to add many, if any, more features to CoffeeScript script tags.
