### ISSUE TITLE
Add object shortcut {foo, bar} to the docs

### ISSUE THREAD

**Issue by Wilfred** [jashkenas/coffeescript#1806]
It's really neat that I can write `{foo, bar}` to get `{foo: foo, bar:bar}`. This doesn't seem to be mentioned in the docs. The natural place to put in would be http://jashkenas.github.com/coffee-script/#objects_and_arrays .

**Comment by GeoffreyBooth** [comment]
It’s in there now: http://coffeescript.org/v2/#objects-and-arrays
