### ISSUE TITLE
Static typing?

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#1852]
Would it be a good idea to introduce static typing in CS?

Eg.

string greet = (Coder me, number|string age, string name) -> "Hi. I am a #{me.getTitle()}. My name is #{name} and I am #{age} years old"

This could solve some issues we have with JS:
- Provide a way for IDEs to autocomplete. So when I type "me." it will give me all the instance methods for Coder. This is impossible atm.
- Good for documentation and clean code.
- No need for manual checking code.
- Less bugs.

Thoughts?

UPDATE:

Found this one that seems to be very popular: http://disnetdev.com/contracts.coffee/

Any thoughts on implementing it into the core of CS?

**Comment by denya133** [comment]
We are working on CoffeeScript v2.0 now. I propose to consider the possibility of implementing "Static Types" as language feature?

**Comment by idchlife** [comment]
@denya133 are static types in consideration now or was it left as possible future feature?

**Comment by denya133** [comment]
@idchlife Sorry, I've been misunderstood. I'm not a contributor, I've made just a suggestion only.

**Comment by GeoffreyBooth** [comment]
https://coffeescript.org/#type-annotations

**Comment by laurentpayot** [comment]
For those interested I've created [Floweret](https://github.com/laurentpayot/floweret), a flow-inspired _dynamic_ type checking library specially for CoffeeScript.

The type annotations example

```coffee
# @flow

###::
type Obj = {
  num: number,
};
###

f = (str ###: string ###, obj ###: Obj ###) ###: string ### ->
  str + obj.num
```

can be rewritten with a decorator-like syntax:

```coffee
import { fn } from 'floweret'

Obj =
  num: Number

f = fn String, Obj, String,
  (str, obj) ->
    str + obj.num
```

It's not _static_ typing, types are checked at runtime. But it's nice to trust your functions inputs/outputs in production and there was no humanly-detectable performance impact for my web app.
