### ISSUE TITLE
Liberal Block Comments

### ISSUE THREAD

**Issue by quangv** [jashkenas/coffeescript#1925]
I'm not sure if I'm doing something wrong, please correct me if I am, but I think the block comments of Coffee-Script is too strict...

I don't think block comments should adhere to indent rules, and should be more liberal.  

```
foo = 'bar'
###

   Only this works.

###
      ###
          This should work I think.
      ###

###  Maybe even this
    ###
```

As in no indents parse errors on block comments. I think block comments should be of the highest level.

Idk, I think comments should be _deal simple_ to use... I think it should be very liberal, cause you never know when you want to "comment out" stuff... to test etc.

Actually, I wouldn't mind if CoffeeScript implemented comments in the exact same as JavaScript comments... `/* */`, `//`

... maybe we should support all _four_ syntax, the `//` & `#` can be used when you want buffering. You can do things like:

```
/* that didn't work, let's block out more things...

foo = 'bar'   

###
       First let's block this out...
###

*/

# Don't print me out
// Print me out
```

idk, maybe 4 formats is too much... but I'd rather have it be real easy to leave comments without parse errors vs hard to comment out stuff.

---

Just realized that you can use here-docs to comment out code, just like _[Python document strings](http://en.wikibooks.org/wiki/Python_Programming/Source_Documentation_and_Comments)_

```
"""
   All this...
   ###
    Are there any negatives to writing comments with here-docs ?
    would be blocked out
        ###
"""
```

Are there any negatives to writing comments this way, with here-docs ?

**Comment by GeoffreyBooth** [comment]
This is fixed via #4572. Sorry it took awhile.
