### ISSUE TITLE
Using expressions for prototype method names

### ISSUE THREAD

**Issue by shesek** [jashkenas/coffeescript#1987]
It could be nice if `[k]: v` inside class body would compile into `Class.prototype[k]=v`. Also, currently it [throws `UNEXPECTED '{'`](http://coffeescript.org/#try:class%20Foo%20then%20%5Bk%5D%3A%20v), which seems wrong - there's no `{`... shouldn't that be `UNEXPECTED '['`?

**Comment by GeoffreyBooth** [comment]
In CS2 these compile into the ES class method syntax.
