### ISSUE TITLE
Unnecessary __slice() on splat arguments

### ISSUE THREAD

**Issue by shesek** [jashkenas/coffeescript#1997]
The `__slice()` used for splats in function invocation could be omitted when the variable came from a splat argument, as its known to already be an array. For example, `(a...) -> fn 1, a...` compiles into:

``` javascript
function() {
  var a;
  a = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return fn.apply(null, [1].concat(__slice.call(a)));
};
```

The second slice in `[1].concat(__slice.call(a))` is unnecessary.

**edit**: Actually, coming to think about it... why are the variables used for splats in function invocation are assumed to always be non-arrays? Other than the `arguments` object, its more common to already have a regular array. Wouldn't it be better to special-case `arguments` and always assume other variables are already arrays? IMHO its better to make the developer responsible for casting non-arrays (other than `arguments`) into arrays than taking the performance hit of `__splice()` every time.

**Comment by GeoffreyBooth** [comment]
In CS the example compiles to:

```js
(function(...a) {
  return fn(1, ...a);
});
```
