### ISSUE TITLE
Add "Contributors Guide" to Wiki

### ISSUE THREAD

**Issue by codelahoma** [jashkenas/coffeescript#1999]
As @jashkenas [said](https://github.com/jashkenas/coffee-script/issues/1351#issuecomment-1221613)

> There isn't a contributor's guide written up anywhere ... but we should really add one to the Wiki.

I can get a good start on one just from the things that core contributors have had to take the time to explain to me.

**Comment by GeoffreyBooth** [comment]
We have this: https://github.com/jashkenas/coffeescript/blob/master/CONTRIBUTING.md
