### ISSUE TITLE
Function overloading (and enforcing number of parameters)

### ISSUE THREAD

**Issue by behnam** [jashkenas/coffeescript#2005]
Function (or method) overloading has been discussed before (issue #531), and the reason for not implementing it was the lack of a design that does not add to the complexity and/or confuse the users. Thus, I would like to suggest the following syntax and conversions:

```coffeescript
func = *> (
	(a) ->
		'one'
	(a, b) ->
		'two'
	(a...) ->
		'many'
)
```

The new `*>` operator says that a list of functions will follow, which:
* no two of them can have the same number of parameters; and
* at most one of the parameters can have a splatted parameter.

**Knowing the number of formal arguments**, the compiler generates the following javascript:

```javascript
var func = function() {
	switch (arguments.length) {
		case 1: return (function(a) {
				return 'one';
			}).apply(this, arguments);

		case 2: return (function(a, b) {
				return 'two';
			}).apply(this, arguments);

		default: return (function() {
				var a;
				a = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
				return 'many';
			}).apply(this, arguments);
	}
}
```

When there's no function with splatted arguments, the `default` case shall throw an exception.

And an additional feature could be to ban using `arguments` inside these functions (who needs `arguments` when there are splatted parameters?!), thus the number of arguments passed to the overloaded function can be verified on compile-time and otherwise a compile-error will be generated.

Having this feature also allows user to *enforce* the number of arguments passed to a function and get a compile-error otherwise. As most of such functions would not need *overloading*, we can also allow `*> Code` in syntax, making it possible to apply the enforcement easily as follows. 

```coffeescript
func = *> (a) ->
	'one'
```

It worths noting that this feature *cannot* be implemented in javascript that easily, as the number of formal parameters of the functions are not known before they are actually running (otherwise, we could implement this features using a couple of helper functions!). Thus, having this features, and the fact that we can catch the errors on compile-time, would be a big improvement to coffeescript.

**Comment by steelbrain** [comment]
Open since "Jan 4, 2012". Oo Lala
+1

**Comment by michaelficarra** [comment]
@steelbrain I'll fix that for you.
