### ISSUE TITLE
Multiline "when"

### ISSUE THREAD

**Issue by copygirl** [jashkenas/coffeescript#2014]
I just noticed this while coding along happily, and while it's not a big problem, it still kind of bugs me.
Following code does not compile:

``` coffee-script
switch order
  when "bread", "cake", "pizza", "water",
       "rotten fish", "horn of a unicorn"
    console.log "You receive a #{order}."
  when "pistol", "machine gun",
       "rocket launcher", "katana"
    console.log "We don't sell any weapons."
```

I think it should be possible to break up `when` statements into multiple lines.

**Comment by chinmay43** [comment]
is it possible to execute multiple statements on a 'when' match ?

**Comment by lydell** [comment]
@chinmay43 Yes!

```coffee
switch 1
  when 1
      console.log 'statement 1'
      console.log 'statement 2'
```

**Comment by GeoffreyBooth** [comment]
Seeing all the difficulties we’re having with leading periods for chaining, I’m not sure we want to be expanding the number of scenarios where we support multiline constructs. But if someone wants to submit a PR, it would be considered.
