### ISSUE TITLE
Block comment parse error

### ISSUE THREAD

**Issue by bhuga** [jashkenas/coffeescript#2025]
I found some weird behavior today. I block-commented a class while testing and coffee failed to parse, but moving the block-commented class to the bottom of the file allowed the parsing to complete. I could not replicate the behavior with a trivial example, so I posted the file I was working with.

https://gist.github.com/1590793

I'm not sure if this is me using block comments wrong, but it seems unlikely that that the location of syntactically correct comments should cause a parse error. If I am using them incorrectly, the section of the docs on block comments does not note it, and the error message is not terribly helpful.

Thanks.

**Comment by GeoffreyBooth** [comment]
This is fixed via #4572. Sorry it took awhile.
