### ISSUE TITLE
Nested comprehensions question

### ISSUE THREAD

**Issue by gkz** [jashkenas/coffeescript#2030]
_(This is not about the result being flat or not.)_

First of all, thank you to all CoffeeScript contributors. I've been using CS a lot, and doing some pretty weird things with it.

Now here is an issue I've encountered while working with CS recently that I hope you guys could clarify:

In python:
`["{0}|{1}".format(x,y) for x in [1,2,3] for y in [7, 8, 9]`
produces
`['1|7', '1|8', '1|9', '2|7', '2|8', '2|9', '3|7', '3|8', '3|9']`

In CS
`("#{x}|#{y}" for x in [1,2,3] for y in [7, 8, 9])`
produces (when **flattened**)
`["1|7", "2|7", "3|7", "1|8", "2|8", "3|8", "1|9", "2|9", "3|9"]`

I am confused about this difference. The python results makes sense to me, the CS result does not.

Furthermore, in python (notice the if condition)
`["{0}|{1}".format(x,y) for x in [1,2,3] for y in [7, 8, 9] if x + y != 10]`
produces (note that the combination of 3|7, 2|8, and 1|9 are gone due to the attached condition)
`['1|7', '1|8', '2|7', '2|9', '3|8', '3|9']`

however, in CS
`("#{x}|#{y}" for x in [1,2,3] for y in [7, 8, 9] when x + y != 10)`
produces no change
`["1|7", "2|7", "3|7", "1|8", "2|8", "3|8", "1|9", "2|9", "3|9"]`

but if the when condition is moved to the middle (?)
`("#{x}|#{y}" for x in [1,2,3] when x + y != 10 for y in [7, 8, 9])`
produces the proper
`["1|7", "2|7", "1|8", "3|8", "2|9", "3|9"]`

I find the behavior in python more intuitive - or am I missing something here.

**Comment by GeoffreyBooth** [comment]
Reimplementing comprehensions, or adding new types of comprehensions, isn’t a priority at the moment; but pull requests are welcome. Closing as there doesn’t appear to be anything to do to resolve the issue discussed by the original post.
