### ISSUE TITLE
Destructuring and empty return values

### ISSUE THREAD

**Issue by jdonnerstag** [jashkenas/coffeescript#2040]
Functions like RegExp.exec may return null, if no match was found. Which means that

re = /xxx(.*?)yyy/
[a, b] = re.exec value

fails with a runtime exception, because _req[0] doesn't exist. Instead I have to do

ref = re.exec(value)
if ref?
      [a, b] = ref

I'd like to suggest that  a = _ref[0] gets replaced with a = _ref[0] if _ref

Thanks for considerung

**Comment by GeoffreyBooth** [comment]
With CS2 using ES syntax for destructuring, I don’t see further improvements in this area.
