### ISSUE TITLE
"class Namespace.XYZ" clobbers (locally) the global XYZ object

### ISSUE THREAD

**Issue by benjie** [jashkenas/coffeescript#2084]
For example, the following CoffeeScript:

```
class Namespace
class Namespace.Math
  @A:Math.PI
```

causes `Math.PI` to be read from the new (empty) constructor function, rather than the global `Math` object and thus leaves `Namespace.Math.A` as `undefined`. 

A potential workaround to this would be to take the full class name `Namespace.Math` as the internal function name for the constructor (modified as needed), for example:

```
var Namespace;
Namespace = (function() {
  function Namespace() {}
  return Namespace;
})();
Namespace.Math = (function() {
  function Namespace_Math() {}
  Namespace_Math.A = Math.PI;
  return Namespace_Math;
})();
```

(This solution is far from perfect - it still conflicts with any `Namespace_Math` object - but makes conflicts less likely?)

**Comment by GeoffreyBooth** [comment]
Not sure this is relevant anymore in CS2 now that we compile to ES `class`.
