### ISSUE TITLE
String symbol character

### ISSUE THREAD

**Issue by ollym** [jashkenas/coffeescript#2095]
I know this is probably unnecessary but I like the ruby syntax for denoting keys/symbols

`:some-text-without-spaces` => `'some-text-without-spaces'`

`phone.ring :tom` => `phone.ring('tom')`

`db.query.select(:all).from(:users).where(id: 1).order(id: :desc)`

**Comment by Naxmeify** [comment]
> How so? :foo in CoffeeScript would become "foo" in JavaScript.

if this would be the only function of a symbol in coffeescript then coffeescript should do without it...

the symbol have to be really like a ruby symbol...
