### ISSUE TITLE
Postfix comparisons on chains

### ISSUE THREAD

**Issue by randallb** [jashkenas/coffeescript#2099]
This is a feature request.

When I'm chaining multiple args together, ideally, I'd like to optionally chain things together based on a postfix if clause.

For instance:

```
@model.where(@name)
  .where(matchObj)
    .skip(numberOfItems * (page-1)) #if numberOfItems && page
    .limit(numberOfItems) #if numberOfItems
```

Make sense? I'm not certain this belongs in the language, but thought I'd put it out there.

**Comment by GeoffreyBooth** [comment]
Patches welcome.
