### ISSUE TITLE
switch proposal

### ISSUE THREAD

**Issue by johngeorgewright** [jashkenas/coffeescript#2112]
Hello there,

I've just started using coffee script with node.js and I'm quickly falling in love. I have a proposal though... I understand the logic behind the switch statements generally requiring to break after each case, however, in most other languages I quite often like to use the fall through option. I.e:

```javascript
switch (resp.statusCode) {
  case 409:
    console.log('Product is already assigned.');

  case 403:
    // save it locally
    save(item);
    break;

  case 404:
    console.error('Product doesn\'t exist');
    break;

  case 500:
    console.error('Something went really wrong');
    break;
}
```

When writing this in coffee script I have to duplicate code:

```ruby
switch res.statusCode
  when 409
    console.log 'Product is already assigned.'
    # save it locally
    save item
  # save it locally
  when 403 then save item
  when 404 then console.error 'Product doesn\'t exist'
  when 500 then console.error 'Something went really wrong.'
```

What would be great is if I could somehow recreate the usual fall through... with something like a "continue" command:

```ruby
switch res.statusCode
  when 409
    console.log 'Product is already assigned.'
    continue
  # save it locally
  when 403 then save item
  when 404 then console.error 'Product doesn\'t exist'
  when 500 then console.error 'Something went really wrong.'
```

I know this example is very small, but sometimes there is a fair amount that can be abstracted with the fall through.

Thanks,
John

**Comment by LKorowicki** [comment]
Hi, I have encountered problem, where fall through option would be very, very useful.
I do not think that language preprocessor should impoverish language that it compiles to, I think it should allow with some additional annotations use even anti patterns.
Additional characters for many programmers is enough discouragement to avoid anti patterns.

**Comment by lydell** [comment]
@LKorowicki Why don't you share that case where fall through would be very, very useful?

**Comment by LKorowicki** [comment]
@lydell I am not authorized to share code which I am currently working on

**Comment by vendethiel** [comment]
But we need a reason to add something. It doesn't have to be copy-pasted code from production.

**Comment by jashkenas** [comment]
Not allowing fallthrough is a nice feature — and all of the examples on this page are only furthering the argument that fallthrough wouldn't be a desirable addition.

**Comment by psmitt** [comment]
If somebody sees benefit in fallthrough statement, why not to make the language richer by that? Do you have any strong arguments _against_ fallthrough?
