### ISSUE TITLE
Single line comments

### ISSUE THREAD

**Issue by yocontra** [jashkenas/coffeescript#2165]
Is there any way to retain single line comments? I want to do source annotations in this format

``` coffee-script
console.log 'some debug text' #!>>events::debug
```

and have the output javascript look like

``` javascript
console.log('some debug text'); //!>>events::debug
```

There doesn't appear to be any compiler flags that do this and the only solution I've seen is to use ### which doesn't fit this case.

**Comment by GeoffreyBooth** [comment]
This is implemented via #4572. Sorry it took awhile.
