### ISSUE TITLE
Add character range to tokens

### ISSUE THREAD

**Issue by WolfgangKluge** [jashkenas/coffeescript#2172]
In addition to the line numbers, it would be quite useful to have exact position data of the tokens. The range should be exposed to the AST, too (similar to #1734).

In fact, I need it to extend my code coverage tool (coveraje) to support coffeescript.

**Comment by lydell** [comment]
As of today, all tokens have the starting line/column as well as the ending line/column on them, making it entirely possible to calculate ranges. Close this one, or keep open as a reminder to also store pre-calculated range info on the tokens?

**Comment by jashkenas** [comment]
We don't need to precalculate. Let's keep the minimal set of useful information on the tokens.
