### ISSUE TITLE
Calling a constructor on a built-in type using splats fails

### ISSUE THREAD

**Issue by bilts** [jashkenas/coffeescript#2183]
```
date = [2010, 00, 01]
console.log(new Date(date[0], date[1], date[2]))
console.log(new Date(date...))
```

The third line above fails.  This seems related to issue #667, but that fix only addresses CoffeeScript classes.  Splats still fail for built-in classes like Date.

**Comment by GeoffreyBooth** [comment]
[Works in CS2.](http://coffeescript.org/v2/#try:date%20%3D%20%5B2010%2C%200%2C%201%5D%0Aconsole.log(new%20Date(date%5B0%5D%2C%20date%5B1%5D%2C%20date%5B2%5D))%0Aconsole.log(new%20Date(date…)))
