### ISSUE TITLE
Multiple existential operators work weirdly.

### ISSUE THREAD

**Issue by xfix** [jashkenas/coffeescript#2199]
``` coffee-script
variable = a ? b ? ':-)'
console.log variable
```

This code returns "ReferenceError: Undefined variable: b" in CoffeeScript (I've tested 1.2.0 and 1.2.1-pre).

This issue doesn't happen in Coco. Also, following code doesn't cause this issue.

``` coffee-script
variable = a ? (b ? ':-)')
console.log variable
```

**Comment by GeoffreyBooth** [comment]
A pull request for this would be considered, but I’m not sure it’s worth doing at this point due to the breaking change it would cause.
