### ISSUE TITLE
Document how to package a Coffeescript project

### ISSUE THREAD

**Issue by hickford** [jashkenas/coffeescript#2216]
I'm grateful for Npm's wonderful documentation on how to package and publish a project written in Node is . http://npmjs.org/doc/developers.html

However Coffeescript desperately lacks documentation explaining how to package a project. We should tell people to compile to Javascript before publishing. It's obvious enough [why](https://github.com/isaacs/npm/issues/1991), but it's far from obvious _how_. Sensibly [Isaacs tells us](https://github.com/isaacs/npm/issues/1991#issuecomment-3364459)  to put a 'prepublish' script in `package.json` so developers can build and publish with a single command `npm publish` but few projects follow this. Instead,  a lot of projects check compiled code into version control including Github's own [Hubot](https://github.com/github/hubot/blob/master/package.json).

Why is it undesirable to put compiled code under version control? For starters, many of the reasons that we don't for other languages. But additionally because we can run Coffeescript without compiling, there's a risk a developer makes a change to the source without building. If they commit now, `lib` will be behind `src`. Conversely, it allows a new to developer to fork the code and edit the compiled code. When the source is rebuilt, their change will be lost.

Today I tried to package my Coffeescript project. My project has only a single `.coffee` file. Following isaac, I put a prepublish script in my [package.json](https://github.com/matt-hickford/imgurgitate/blob/master/package.json)  

```
"scripts": {
  "prepublish": "coffee -o lib -c src/*.coffee"
```

This _almost_ worked. It built my script to Javascript and it would be fine if my script were a library, but my script is an executable. The script had a `#!/usr/bin/env coffee` shebang, but the Coffeescript compiler [saves code without a shebang](https://github.com/jashkenas/coffee-script/issues/2215). If a user executes Javascript without a shebang their shell runs it as a shell script and they get a silly error.

Now, it's easy enough to prepend the shebang manually, but it's a major challenge to do that from the prepublish script in a platform-independent way. Other Coffeescript projects such as [Pow](https://github.com/37signals/pow/blob/master/bin/pow) get round this by writing one line executables that rarely change and checking in the compiled Javascript executable. 

Documentation should also explain the `src`, `lib`, `bin` convention and which of these you should check into version control. 

Previous discussion https://github.com/isaacs/npm/issues/1991#issuecomment-4675322

**Comment by toolbear** [comment]
Many ways to skin a cat. The following works nicely for me.

1. Prepublish step compiles CoffeeScript in `lib` to JavaScript in `lib`:
  ```
    "scripts": {
      "prepublish": "coffee -co lib lib"
    }
  ```

2. Telling git to ignore `/lib/**/*.js` and npm to ignore `/lib/**/*.coffee`

3. JavaScript executable, `bin/my-command`, that registers the CoffeeScript compiler and loads our lib:

   ```javascript
  #!/usr/bin/env node
  
  process.title = 'my-command';
  require('coffee-script/register');
  require('./../lib/cli.js')();
  ```

4. Running `git clean -fx` following an `npm publish`

Has no compiled code checked in; doesn't require compilation when developing; npm package only contains JavaScript; and — sans executable — is 100% CoffeeScript.

**Comment by hems** [comment]
when compiling coffee to js a good idea is to use --bare so you don't get any extra "wrapping" on your code, as in: 

````./node_modules/.bin/coffee --bare -o lib/ -c src/````
