### ISSUE TITLE
Private and public variables or methods in classes

### ISSUE THREAD

**Issue by rainerborene** [jashkenas/coffeescript#222]
It would be great to have private and public variables in classes. Any possibility for that? I have no idea on how this could be implemented on JavaScript... But in CoffeScript I'm thinking of something like this:

```
class Person
  constructor: (name) ->
    @name: name

  say: (something) ->
    alert something

  sayHello:
    @say "Hello World"

  private :say
```

**Comment by firedev** [comment]
It would be nice to simply allow word private to be inserted in code for easier reading. I know I can add comment, that's what I do. But it would read really nice if I could mark the rest of the file as `private`
