### ISSUE TITLE
"Compiled with ..." message breaks --bare compiled shebang scripts.

### ISSUE THREAD

**Issue by edwardmsmith** [jashkenas/coffeescript#2248]
Given a script like

```
`#!/usr/bin/env node`
console.log "Hello, World!"
```

When compiled with --bare, the shebang was maintained, and the resulting javascript file was executable.

With 1.3, the file starts:

```
// Generated by CoffeeScript 1.3.0
#!/usr/bin/env node
```

Which causes execution to fail.

Either the 'compiled by' message should be suppressed during --bare, or there should be another compiler option to suppress the message.

In general, I think there should be an option to suppress this "Compiled by" message.

**Comment by aleclarson** [comment]
Sorry to revive an old thread. Why doesn't coffeescript pass `#!` thru when it's the first line in a file?

**Comment by GeoffreyBooth** [comment]
The compiler might not be outputting for Node, for starters. Node may ignore hashbangs, but they're not standard JavaScript.
