### ISSUE TITLE
Invalid JS: `return if not x?` creates empty `if` block

### ISSUE THREAD

**Issue by colinhowe** [jashkenas/coffeescript#2298]
We have some code like:

```
return if not x?
```

And this generates:

```
if (!(x != null)) return
```

As I understand it, this should output:

```
if (x == null) return
```

Or am I missing something unusual about JS? :)

**Comment by GeoffreyBooth** [comment]
Even more minimal case:

```coffee
-> return if yes
```

___

```js
(function() {
  if (true) {

  }
});
```

**Comment by connec** [comment]
This seems like some kind of optimisation. If there's anything after the `return if yes` line everything is fine.

[Example](http://coffeescript.org/#try:-%3E%0A%20%20return%20if%20yes%0A%20%20'hello')
```coffee
->
  return if yes
  'hello'
```
---
```js
(function() {
  if (true) {
    return;
  }
  return 'hello';
});
```

**Comment by vendethiel** [comment]
[Yup, it's an optimisation](https://github.com/jashkenas/coffeescript/blob/master/src/nodes.coffee#L272)

**Comment by Defiled** [comment]
The phrasing on this one is a bit strange and can lead to confusion. Heres an example:

`return 'Please enter a number.' if not consumer.number? or consumer.number.length is < 9`

So this is saying to return an error message of "Please enter a number" when the two specified conditions have been met. The first one being that there is no data in consumer.number?. The second condition checks for valid data, so it doesn't take any strings with a length less than 9.

**Comment by GeoffreyBooth** [comment]
I can’t seem to write a test for this. Returning `void` (i.e. a plain `return` statement) produces the same return value as a function that doesn’t return. So

```js
(function() {
  if (true) {

  }
})();
```

is the same, really, as

```js
(function() {
  if (true) {
    return;
  }
})();
```

And as @connec [wrote](https://github.com/jashkenas/coffeescript/issues/2298#issuecomment-298325234), as soon as you put a value anywhere (`return 1 if yes`, or a second `return` after the line with the `if yes`) it compiles as we’d expect.

So I guess this is just an optimization that works. It’s a bit confusing to read, but `-> return if yes` is such a weird edge case that we shouldn’t do anything special here just for readability.

As for the question about the readability of `if not` versus `unless`, I don’t think the generated output is confusing enough to justify revision.

So I don’t see anything here that needs fixing. Please comment if I’m wrong, and I’ll reopen.
