### ISSUE TITLE
Loosening restriction for obj.method?() checks

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/coffeescript#2315]
I know we added it originally for good reasons ... but it bugs me that the check for `obj.method?` is if the method exists ... and at the same time, the check for `obj.method?()` is if the method both exists and is a function.

It's certainly stricter as is, but I think that any code that relies on the semantics of `obj.method?()` to _not_ call `method` when it exists and _is not_ a function, is overly fragile code that we shouldn't be encouraging. 

Should we change the existential operator to only ever test for existence, regardless of the context in which it's used?

**Comment by lzrski** [comment]
+1

Consider how *existential family* of operators in CoffeeScript is consistent, except for the function invocation:

operator | meaning
---------|---------
`a?` | does `a` **exist**?
`a ? b` | if `a` **exists** then `a` else `b`
`a ?= b` | set `a` to `b` if `a` does not **exist**
`a?.b` | take `b` of `a` if `a` **exists**
`a? b` | call `a` if `a` **is a function** 💥 

Changing the meaning of `a? b` to mean "call `a` if `a` **exists**" would make it more consistent (and thus intuitive) and also prevent following kind of bugs:

I had a perfectly good piece of code like this:

```coffeescript
if data.value? then do_something_with data.value
else default_value
```

Then I decided that it will read better if I put the conditional logic on new lines:

```coffeescript
if data.value? th # <-- but by mistake I left th out of then, a stupid typo!
  do_something_with data.value
else
 default_value
```

Now my code was compiling and running without errors, but the *truthy* branch of the `if` statement was never being executed. Note that `data.value` is not a function and `th` variable is not even declared. Both facts should rise a `TypeError`! You can imagine that in a large codebase it was quite hard to figure out where does the wrong value come from.

**Comment by GeoffreyBooth** [comment]
Looks like we probably shouldn’t make this breaking change at this point.
