### ISSUE TITLE
`super` apply instead of call

### ISSUE THREAD

**Issue by quangv** [jashkenas/coffeescript#2354]
Any syntax to get `super` to do an `apply` instead of a `call` with you pass in arguments?

``` coffee
class Child extends Parent
  constructor : ->
    super.apply ['one', 'two']
    # want -> Child.__super__.constructor.apply(this, ['one', 'two']);
```

[repl link](http://coffeescript.org/#try:class%20Child%20extends%20Parent%0A%20%20constructor%20%3A%20-%3E%0A%20%20%20%20super.apply%20%5B'one'%2C%20'two'%5D%0A%20%20%20%20%20%20%20%20)

Thanks

**Comment by GeoffreyBooth** [comment]
Closing as no longer relevant in CS2.
