### ISSUE TITLE
Docs: Lexical Scoping and Variable Safety

### ISSUE THREAD

**Issue by Kerrick** [jashkenas/coffeescript#2360]
I was just checking out CoffeeScript for the first time, and I came to the section "[**Lexical Scoping and Variable Safety**](http://coffeescript.org/#lexical_scope)" at [coffeescript.org](http://coffeescript.org/). It says:

> This behavior is effectively identical to Ruby's scope for local variables.

However, it's _not_.

The following script in Ruby is _not_ effectively identical to its CoffeeScript counterpart below, namely the value of `outer` after all is said and done.

``` ruby
outer = 1
def change_numbers
  inner = -1
  outer = 10
end
inner = change_numbers
puts inner # => 10
puts outer # => 1
```

``` coffeescript
outer = 1
changeNumbers = ->
  inner = -1
  outer = 10
inner = changeNumbers()
alert inner # => 10
alert outer # => 10
```

While I'm not necessarily asking this _behavior_ be changed in CoffeeScript (as I'm sure it's there for good reason), I do wish the documentation wasn't misleading.

**Comment by GeoffreyBooth** [comment]
Done in #4536.
