### ISSUE TITLE
Syntax error script type="text/coffeescript" does not tell in which file

### ISSUE THREAD

**Issue by nh2** [jashkenas/coffeescript#2368]
Hi,

I use `coffee-script.js` and includes like `<script type="text/coffeescript" src="js/my.coffee"></script>` for development.

For some reason, if I have a syntax error in a file, I just get `Uncaught Error: Parse error on line 75: Unexpected 'COMPARE'` with a stack trace showing only line numbers of `coffee-script.js` - **it does not tell me in which file the error is**!

This happens in both Chromium and Firefox + Firebug.

Has this always been like this?
Why cannot it tell me in what file the error is?

**Comment by 1j01** [comment]
This is still a problem in 2016. I don't even get line numbers, just e.g. `SyntaxError: unexpected (`

**Comment by GeoffreyBooth** [comment]
This should have been fixed in #4428. Please comment if that isn’t the case and I will reopen.
