### ISSUE TITLE
is behaviour of `a? b c` desirable?

### ISSUE THREAD

**Issue by michaelficarra** [jashkenas/coffeescript#2383]
Currently, `a? b c` compiles to

``` js
if (typeof a === "function") {
  a(b(c));
}
```

which doesn't call `b` if `a` isn't callable. I was a little surprised by this today, expecting to see the side effects of `b` regardless, and only call `a` on `b`'s result when `a` is callable. I was forced to resort to

``` coffee
tempVar = b c
a? tempVar
```

We don't like requiring temporary variables in CoffeeScript. I think the inner expression(s) should always be evaluated first. This would make `t = b c; a? t` and `a? b c` identical, which I feel is both the proper and expected behaviour. The new compilation _would_ use a temporary variable:

``` js
var _ref = b(c);
if(typeof a === "function") a(_ref);
```

And as an expression: `+(a? b c)`

``` js
var _ref;
+(_ref = b(c), typeof a === "function" ? a(_ref) : void 0);
```

**Comment by GeoffreyBooth** [comment]
Changing this now would be a breaking change, and there doesn’t seem to be much interest since 2013.
