### ISSUE TITLE
Can't catch uncaughtException event

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#2390]
Is CS hooking up into uncaughtException so other libs won't work if they depend on it?

Here is a JS script that is using winston:

https://gist.github.com/2953428

It works just fine, the exception is caught and it's printed to the console.

I was running the file with `node test.js`

The equivalent CS version however doesn't work:

https://gist.github.com/2953143

I was running the file with `coffee test.coffee`

The code is similar so I think it has to do with the node vs coffee interpreter. Coffee must be doing something with the uncaughtException.

What is the problem?

**Comment by ryoqun** [comment]
We're stumbled on this issue too.

What's the rationale of this behavior?

**Comment by ryoqun** [comment]
Here is my two cents (i.e.: minimal test case):

```
ryoqun@mymachine:~$ node -v
v0.12.7
ryoqun@mymachine:~$ coffee -v
CoffeeScript version 1.10.0
ryoqun@mymachine:~$ echo 'process.on("uncaughtException", -> console.log({text: "worked!"})); process.nextTick(-> throw "bad")' | coffee --stdio
{ text: 'worked!' }
ryoqun@mymachine:~$ echo 'process.on("uncaughtException", -> console.log({text: "worked!"})); process.nextTick(-> throw "bad")' | coffee --compile --stdio | node
{ text: 'worked!' }
ryoqun@mymachine:~$ echo 'process.on("uncaughtException", -> console.log({text: "worked!"})); (-> throw "bad")()' | coffee --stdio
bad
ryoqun@mymachine:~$ echo 'process.on("uncaughtException", -> console.log({text: "worked!"})); (-> throw "bad")()' | coffee --stdio --compile | node

[stdin]:10
    throw "bad";
    ^
{ text: 'worked!' }

```

Ideally, the third one and the forth should behave identically,  considering CoffeeScript is a just **compiler**, which conceptually shouldn't affect program's runtime behaviour.

**Comment by jashkenas** [comment]
The reason this is happening is because CoffeeScript wraps code that it compiles and executes directly in a `try/catch`, in order to give you better error messages:

```
  try
    answer = compile(stripped, {filename, sourceMap, literate: helpers.isLiterate filename})
  catch err
    # As the filename and code of a dynamically loaded file will be different
    # from the original file compiled with CoffeeScript.run, add that
    # information to error so it can be pretty-printed later.
    throw helpers.updateSyntaxError err, stripped, filename
```

You shouldn't be running servers directly from the `coffee` executable. You should be compiling into JavaScript first.

**Comment by GeoffreyBooth** [comment]
The `coffee` command is intended for compiling and debugging, not as a replacement for the `node` executable.

**Comment by audunolsen** [comment]
`cat test.coffee | coffee -sc | node`

That's what I do for this specific case. Probably not the most robust workaround though.
