### ISSUE TITLE
Add `const` support

### ISSUE THREAD

**Issue by paulmillr** [jashkenas/coffeescript#2393]
I propose to add `const` support that will be compiled to `var` (in order to have compat with current js engines), but that will catch re-assigns to variables. It will be extremely useful in functional programming and, if used, decrease overall bug count.

``` coffeescript
const hello = ['world', 1, 2, 3]
const bye = [4, 5, 6]

bye = 8  # Compile-time error.
```

output:

``` javascript
var hello, bye;

hello = ['world', 1, 2, 3];
bye = [4, 5, 6];
```

**Comment by samccone** [comment]
:+1: for at least letting us pass through const

**Comment by cotko** [comment]
I'd also like to see coffee allowing me to use the const, but I'm surprised nobody mentioned escaping the code, supported by coffee?
```coffee
`const my_const = 'foo'`
```

**Comment by Fresheyeball** [comment]
Livescript has const via the compiler (it looks for reassignment and then complains), perhaps there is code over there that could be re-used over here to make this dream a reality?

**Comment by algesten** [comment]
see #3571

**Comment by bertolo1988** [comment]
"Having a const introduces a new type of variable that is entirely unnecessary for runtime semantics"

This is a new level of stupidity.

**Comment by vendethiel** [comment]
> What if i desire to pass an unchangeable object to a user of my module?

You're looking for `Object.freeze`, not `const`.

Also calling people "stupid" is a bad idea...
