### ISSUE TITLE
Option to compile top-level block comment inside of safety wrapper

### ISSUE THREAD

**Issue by mbezjak** [jashkenas/coffeescript#2403]
This is related to #1509.

Now that top-level block comments are compiled outside of safety wrapper, documentation generators, suck as [jsduck](https://github.com/senchalabs/jsduck) have a hard time with it. Essentially, JSDuck tries to infer as much information from code as possible, so that developer doesn't have to write a lot of comment tags. By splitting function documentation (top-level block comment) away from function definition, JSDuck can't infer anything.

Could we get a (command line) option when compiling, to put top-level block comments near function definition?

**Comment by GeoffreyBooth** [comment]
I don’t think this is something we plan to address. I suggest you compile with the `bare` option and add your own safety wrapper after compilation if you find it necessary.

**Comment by GeoffreyBooth** [comment]
This should now be possible via #4572.
