### ISSUE TITLE
Python-like try-catch-cont?

### ISSUE THREAD

**Issue by aseemk** [jashkenas/coffeescript#2413]
Hey there,

I've done a bit of searching, but didn't find any previous issue making this same request.

Just wanted to toss in a feature request for a Python-like `try-catch-else` syntax. The [documentation](http://docs.python.org/tutorial/errors.html) for this Python feature says it best:

> The use of the `else` clause is better than adding additional code to the `try` clause because it avoids accidentally catching an exception that wasn’t raised by the code being protected by the `try` ... `except` statement.

It might look like this: _[Edited to be `continue` instead of `else` based on discussion below.]_

``` coffee
try
    foo()
catch err
    error()
continue
    success()
```

And it might compile to something like this:

``` js
var _success = false;

try {
    foo();
    _success = true;
} catch (err) {
    error();
}

if (_success) {
    success();
}
```

(`_success` might actually be better off as an anonymous `_ref`; just naming it here to illustrate its purpose.)

I make this request because I've found myself doing this kind of thing plenty of times manually when I need to be robust and precise in my error handling, and this is the kind of feature that seems to fit well into CoffeeScript's strengths of making it easier to write better code. =)

The compilation becomes a bit trickier if a `finally` clause is present, but nothing insurmountable.

Thanks for your consideration!

**Comment by aseemk** [comment]
I find myself regularly wishing for this. =)

If it helps anyone else, discovered this less elegant but equivalent option:

```coffee
try
    foo()
    try    # equivalent to `else`/`continue`
        success()
catch err
    error()
```

Supports `finally`, and lets you also handle errors from the `else`/`continue` block if you wish.

([via](http://stackoverflow.com/a/20506988/132978))

**Comment by loveencounterflow** [comment]
FWIW, I discovered you can write 

```coffee
try
   compute something
catch error
    handle error 
unless error?
    handle success
```
This is possible since CS puts the variable of the `catch` clause into the surrounding scope, which JS does not do. One might even argue that saying `unless error?` is clearer than both `else` (this is not an `if` clause) and `continue` (this is not a loop) in that position. 

People who insist on oneliners can even write 

```coffee
try compute something catch error then handle error unless error? then handle success
```

which is somewhat cool and somewhat unreadable.
