### ISSUE TITLE
Why CS doesn't support the one liner if-then-else: ... ? ... : ...

### ISSUE THREAD

**Issue by 51mon** [jashkenas/coffeescript#2428]
Why not keeping this nice feature of JS into CS ? To me "x ? y : z" is more readable than "if x then y else z"

Ok that would conflict with the following syntax:
footprints = yeti ? "bear"

But is that syntax really worth it ?

When allowing x ? y : z the previous expression becomes:
footprints = yeti? ? "bear"

Not so bad to me.

**Comment by attenzione** [comment]
I want to know, how many developers, except developers of coffeescript, like this syntax.
this syntax ( ? : ) is known by everyone in 2016 year and you (devs of cs) talking about "new syntax"?
btw, i've never seen "if then else" in one line.
As I see in the web, there is huge amount of questions about ternary operator, many issues here. But you stay with your principals, that costs nothing.
You should create poll about this, ask as many developers as you can. If you took responsibilities for creating popular syntax, you should do it in the right way.

sorry, like much about coffee, thanks for your great work, but I hate your "new syntax" of ternary operator.

**Comment by vendethiel** [comment]
> btw, i've never seen "if then else" in one line.

That's fine if you don't know (recent) Ada, Python, Scala, the ML family, but it doesn't mean CoffeeScript can't borrow from them :).

> I want to know, how many developers, except developers of coffeescript, like this syntax.

I do, because it's very consistent.

> talking about "new syntax"?

Note that this issue is 4 years old. And as I quoted, many other languages do it like that as well.

**Comment by attenzione** [comment]
Python has another syntax, don't "if then else" and order of logic is another.
> I do, because it's very consistent.

I don't, it's not readable. and you're collaborator, your opinion is for coffee and not clear.
> many other languages do it like that as well.

many don't.

As you stated, CS borrow from many of languages, I don't see real arguments for not support both of syntax. Only as I can read - it's not consistent, don't like it. And this is from CS developers.
Make a poll, with about 50K developers, without CS developers. If normal ternary syntax nobody choose, sorry, my mistake, but what if not?

**Comment by carlsmith** [comment]
CoffeeScript is not a democracy. It's designed by its developers, and reflects their opinions and preferences. That's just how it is. If fifty thousand developers want something different, they will need to implement it themselves. It doesn't matter how you or I feel about that.

**Comment by attenzione** [comment]
That's not about democracy and election. That's about listening. 
We are talking about little addition in huge project, not breaking anything.
> CoffeeScript is an attempt to expose the good parts of JavaScript in a simple way.

really?

**Comment by milleniumbug** [comment]
Features don't exist in vaccum, they need to be implemented and maintained. You don't introduce a feature because "why not". You have to have a rationale for introducing one. Clearly this feature hasn't received the points [to recover from the starting -100 points](https://blogs.msdn.microsoft.com/ericgu/2004/01/12/minus-100-points/), so it's not included in CoffeeScript.

**Comment by attenzione** [comment]
http://ryanflorence.com/2011/case-against-coffeescript/
> We Process Images and Symbols Faster than Words

**Comment by milleniumbug** [comment]
Okay, assuming this is a relevant argument in this case (it's not, but don't feel arguing about this at the moment, maybe later), then your feature got 5 points.

Congratulations.

You have to get 95+ points more to outweigh the cost/benefit analysis.
