### ISSUE TITLE
compile order in sub-directories

### ISSUE THREAD

**Issue by brunoimbrizi** [jashkenas/coffeescript#2437]
Compiler seems to follow alphabetical order instead of folder hierarchy.
Please consider the following example:

src/App.coffee
src/view/B.coffee
src/view/a/A.coffee

Where class A extends B.

Compile with this line:

```
coffee --join js/app.js --compile src/view/ src/App.coffee
```

This throws an error in the browser:

```
Uncaught TypeError: Cannot read property 'prototype' of undefined 
```

If folder _a_ is renamed to _z_, the error is gone and everything works fine.

Shouldn't the compiler read all files from src/view/ _before_ it moves on to src/view/[sub-dir] ?

**Comment by GeoffreyBooth** [comment]
This can be resolved using modules, CommonJS, or tools like Gulp or Webpack or Browserify. It is out of scope for the CoffeeScript compiler.
