### ISSUE TITLE
correct placed comments have effects on the compilation process 

### ISSUE THREAD

**Issue by nomoral** [jashkenas/coffeescript#2445]
hello

the following code does not compile:

```coffee
$("body").on "namespace-" + event,
    ###
     <|line: 19|> 
    ###
    () -> handler()
```

but the following does:

```coffee
$("body").on "namespace-" + event,
    () -> handler()
```

the idea of comments (my interpretation) is that they are separated from the code.
they are like removed from the code leaving no effect.

**Comment by GeoffreyBooth** [comment]
This is fixed via #4572. Sorry it took awhile.
