### ISSUE TITLE
Request: Multiline conditionals can begin with operator (and/or/etc)

### ISSUE THREAD

**Issue by mrak** [jashkenas/coffeescript#2448]
I would like to propose the following for increased readability on multiline conditional statements:

``` coffeescript
if thesun is bright
and thesky is blue
and theair is clean
   console.log "My oh my, It's a wonderful day!"
```

Which I find much more readable than

``` coffeescript
if thesun is bright and
thesky is blue and
theair is clean
   console.log "My oh my, It's a wonderful day!"
```

**Comment by GeoffreyBooth** [comment]
```coffee
if thesun is bright and
   thesky is blue and
   theair is clean 
  console.log "My oh my, It's a wonderful day!"
```

[compiles now](http://coffeescript.org/v2/#try:if%20thesun%20is%20bright%20and%0A%20%20%20thesky%20is%20blue%20and%0A%20%20%20theair%20is%20clean%20%0A%20%20console.log%20%22My%20oh%20my%2C%20It's%20a%20wonderful%20day!%22).
