### ISSUE TITLE
`unless variable?` compiles to two different things.

### ISSUE THREAD

**Issue by Zegnat** [jashkenas/coffeescript#2455]
Setting any variable depending on its own existence (checked with the existential operator `?`) results in different JavaScript code depending on whether the variable has been assigned a value somewhere prior to the check. See code examples below.

I would expect the JavaScript output to be the same in both cases. Because both cases add the `var` statement and therefor neither has to check via `typeof`.

---

**Input**

``` CoffeeScript
a = {} unless a?
```

**Output**

``` JavaScript
var a;
if (typeof a === "undefined" || a === null) {
  a = {};
}
```

**Input**

``` CoffeeScript
a = a # Setting a to itself, the most pointless of variable assignments.
a = {} unless a?
```

**Output**

``` JavaScript
var a;
a = a;
if (a == null) {
  a = {};
}
```

**Comment by matrinox** [comment]
Still broken here
I think it just makes sense to keep the `?` as an existential check only. None of this smart "this variable once defined can never be `undefined`" logic.

This code:
```coffee
if a?.b?.c
  a.b.c
```

Compiles to:
```js
var ref;

if (typeof a !== "undefined" && a !== null ? (ref = a.b) != null ? ref.c : void 0 : void 0) {
  a.b.c;
}
```

It's like it gives up after the first try...
Safe navigation is really great syntax that provides safety to developers. Would be nice to get this to check for `undefined` as well

**Comment by jashkenas** [comment]
That's not broken.

If you really think it's broken, submit a failing test that proves it.

**Comment by vendethiel** [comment]
Why was this issue reopened, by the way?

**Comment by jashkenas** [comment]
It looks like the comments on that commit are why — but I'm not sure if they're still relevant or not.

**Comment by matrinox** [comment]
Just curious if the purpose of the `?` operator is to always check for `null`/`undefined` or just `null`. The website says the former but code output often produces the latter

**Comment by vendethiel** [comment]
That's how `!=` works -- differently from `!==`. It's in the FAQ and in a dozen other issues.

**Comment by matrinox** [comment]
@vendethiel In Coffeescript, you can't do `!==` and they automatically convert `!=` and `isnt` to `!==`. Ditto with `==`/`is` becoming `===`

**Comment by vendethiel** [comment]
We're talking about generated code here, not coffeescript code.

**Comment by matrinox** [comment]
I see, you're right @vendethiel. Thanks for the help! `!= null` is `false` for `undefined` and `void 0`, as well as `null`

**Comment by SuzanaK** [comment]
Another example to show that the compiler should not omit the check for undefined: 

This:

```
someobject = {}
x = someobject['key']
console.log(x) if x?
```

compiles to: 

```
var someobject, x;
someobject = {};
x = someobject['key'];
if (x != null) {
  console.log(x);
}
```

When the key does not exist, x will be undefined. This just created a bug in my code that was difficult  to find until I looked at the generated JS...

**Comment by SuzanaK** [comment]
Another example to show that the compiler should not omit the check for undefined:

This:

```
someobject = {}
x = someobject['key']
console.log(x) if x?
```

compiles to:

```
var someobject, x;
someobject = {};
x = someobject['key'];
if (x != null) {
  console.log(x);
}
```

When the key does not exist, x will be undefined. This just created a bug in my code that was difficult to find until I looked at the generated JS...
