### ISSUE TITLE
Blocks with comments only throw ParseError

### ISSUE THREAD

**Issue by StanAngeloff** [jashkenas/coffeescript#246]
Run the following on [coffeescript.org](http://coffeescript.org):

```
a: 1
if a
    # I don't like comments
else
    a: 2
```

It used to compile just fine, but on _master_ it seems comments cannot be the only token in a block. May have something to do with how the rewriter is adjusting them? If you put a newline just before the comment, it will compile OK.

**Comment by GeoffreyBooth** [comment]
This is fixed via #4572. Sorry it took awhile.
