### ISSUE TITLE
Function.length in fat arrow class method

### ISSUE THREAD

**Issue by leeola** [jashkenas/coffeescript#2489]
In the following code, how is it possible to get the length of `wtf.bar` ?

``` CoffeeScript
foo = (a, b, c) ->
bar = (a, b, c) =>

class Wtf
  foo: (a, b, c) ->
  bar: (a, b, c) =>

wtf = new Wtf()
results =
[
  foo.length
  bar.length
  wtf.foo.length
  wtf.bar.length
]
console.log results
# Ouputs: [ 3, 3, 3, 0 ]
```

As you can see, the combination of the fat arrow and a class instance causes `wtf.bar.length` to return zero. Is there a workaround for this? Is this "working as intended"? All sorts of various code uses the handy `Function.length` checks, and the inability to trust `Function.length` if the user declared the function as a fat-arrow function could cause problems (and already has for me).. Thoughts?

**Comment by GeoffreyBooth** [comment]
Believe it or not, this is still an issue in CS2. The example above now (2.0.0-beta1) compiles to:

```js
var Wtf, bar, foo, results, wtf,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

foo = function(a, b, c) {};

bar = (a, b, c) => {};

Wtf = class Wtf {
  constructor() {
    this.bar = bind(this.bar, this);
  }

  foo(a, b, c) {}

  bar(a, b, c) {}

};

wtf = new Wtf();

results = [foo.length, bar.length, wtf.foo.length, wtf.bar.length];

console.log(results);
```
And still outputs `[ 3, 3, 3, 0 ]`.

But if we change the `class` part to:

```js
Wtf = class Wtf {
  constructor() {
    this.bar = (a, b, c) => {}
  }

  foo(a, b, c) {}

};
```

It suddenly outputs `[ 3, 3, 3, 3 ]` as desired. _And_ we would be able to get rid of the `bind` helper function, as we would no longer need it. @connec, does this seem like a doable change?

**Comment by GeoffreyBooth** [comment]
Thanks to #4526, this now compiles to:

```js
var Wtf, bar, foo, results, wtf;

foo = function(a, b, c) {};

bar = (a, b, c) => {};

Wtf = class Wtf {
  constructor() {
    this.bar = this.bar.bind(this);
  }

  foo(a, b, c) {}

  bar(a, b, c) {}

};

wtf = new Wtf();

results = [foo.length, bar.length, wtf.foo.length, wtf.bar.length];

console.log(results);
```
And it outputs `[ 3, 3, 3, 3 ]` 😄 So this bug is finally fixed.

I’m not sure it’s worth the effort to compile to the alternative in my last comment, or if that’s even an improvement, but that can be left for another issue or PR.

**Comment by connec** [comment]
I think the current compilation is best - the method still exists on the prototype, but a 'copy' is bound to the instance on construction. It means a bound method is still a method.
