### ISSUE TITLE
`do for item in list` ?

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/coffeescript#2518]
An interesting proposal raised by @lehni, here:

https://github.com/jashkenas/coffee-script/issues/2382#issuecomment-8032361

... is to somehow combine the `do` and `for` keywords to give you a quick and easy way to write a loop that closes over its variables ... _without_ hiding the fact that you're working with an implied inner function, and all of the scope changes that involves. I think it might work out nicely.

```
do for num in [1, 2, 3]
```

... becomes the equivalent of:

```
for num in [1, 2, 3]
  do (num) ->
```

Any ideas?

**Comment by GeoffreyBooth** [comment]
A pull request for this would be welcome.

**Comment by connec** [comment]
I think for CS2 the right solution to the actual problem here would be a `for let` syntax.

```coffee
for let i in [1..5]
  setTimeout -> console.log i

for let key, value of object
  ...
```

Another option would be to take the proposal here and combine it with #4514 to produce the same output.

**Comment by connec** [comment]
Just gonna drop a link to https://github.com/jashkenas/coffeescript/issues/959#issuecomment-634034 - the original issue adding `do` also makes several mentions of possible shortcuts for IIFEs in loops.

**Comment by treeform** [comment]
I was going to propose `for bar in foo ->` syntax. I feel like its better syntax then `for let bar in foo ->`, `for bar in foo do ->`, `for scope bar in foo ->`, `do for scope bar in foo ->` and feels just like a shorter version of `for bar in foo then do (bar) ->` which we use a ton.

Is this issue closed or patches welcome?

**Comment by jashkenas** [comment]
Let's leave this closed — it's been long enough that we don't need to be adding a new iteration construct at this point...
