### ISSUE TITLE
Starting offset and negative steps for array loops <enhancement>

### ISSUE THREAD

**Issue by claystreet** [jashkenas/coffeescript#2526]
**I'd like to see an enhancement to start at a non-zero offset when looping over arrays such as:**

``` coffeescript
x for x in testA start 2
```

**Could generate this:**

``` javascript
_results = [];
for (_i = 2, _len = testA.length; _i < _len; _i++) {
x = testA[_i];
_results.push(x);
}
_results;
```

**Negative start values could start from the end of the array**

``` coffeescript
x for x in testA start -2
```

**Could generate this:**

``` javascript
_results = [];
for (_i = testA.length-2, _len = testA.length; _i < _len; _i++) {
x = testA[_i];
_results.push(x);
}
_results;
```

**A negative start value WITH a negative step:**

``` coffeescript
x for x in testA start -2 by -1
```

**Could generate this:**

``` javascript
_results = [];
for (_i = testA.length-2, _len = -1; _i > _len; _i--) {
x = testA[_i];
_results.push(x);
}
_results;
```

**A negative step WITHOUT a start value implies a start value of -1**

``` coffeescript
x for x in testA by -1
```

**Could generate this:**

``` javascript
_results = [];
for (_i = testA.length-1, _len = -1; _i > _len; _i--) {
x = testA[_i];
_results.push(x);
}
_results;
```

**Summary**
- A positive (or zero) start is relative to zero, effectively: `_i = start`
- A negative start is relative to _array.length_: `_i = array.length + start` (remember start is negative so we're really subtracting from array.length)
- A negative step implies
  - _len will be initialied to: `_len = -1`
  - The end test is: `_i > _len`
  - The default start is -1:  `_i = array.length-1`  
- A positive step (today's only real assumption) implies
  - _len will be initialied to: `_len = array.length`
  - The end test is: `_i < _len`
  - The default start is 0: `_i = 0`

**An Extra Safety Check is Potentially Necessary in Two Situations:**
1. When _step_ is positive and _start_ is negative it is possible for `_i` to be initialized below 0 (with the loop  incrementing up towards array.length).
   Given,
   
   ``` coffeescript
   testA = [1,2]
   x for x in testA start -5
   ```
   
   The safety check clips the start value at zero:
   
   ``` javascript
   _results = [];
   _istart = testA.length-5;
   if (_istart < 0) _istart = 0;
   for (_i = _istart, _len = testA.length; _i < _len; _i++) {
       x = testA[_i];
       _results.push(x);
   }
   _results;
   ```
2. When _step_ is negative and _start_ is positive it is possible for `_i` to be initialized beyond array.length (with the loop decrementing down to -1).
   Given,
   
   ``` coffeescript
   testA = [1,2]
   x for x in testA start 5 by -1
   ```
   
   The safety check limits the start value to `array.length-1`
   
   ``` javascript
   _results = [];
   _istart = 5;
   if (_istart >= testA.length) _istart = testA.length -1;
   for (_i = _istart, _len = -1; _i > _len; _i--) {
       x = testA[_i];
       _results.push(x);
   }
   _results;
   ```

**Comment by ryabenko-pro** [comment]
This is good idea. [2...list.length] will create new array by calling ````slice```` method when I just want to iterate from second element.
