### ISSUE TITLE
Lexer: Indenting within object literal produces unexpected behavior, unhelpful error message

### ISSUE THREAD

**Issue by FiloSottile** [jashkenas/coffeescript#2667]
This code compiles

```
{ a: 1
b: 2 }
```

while this other Syntax Errors

```
{ a: 1
  b: 2 }
```

(And generally every time you indent inside a `{}` literal.)

Not sure it is a bug, but I can't find why in the docs.
[Test it](http://coffeescript.org/#try:%7B%20a%3A%201%0Ab%3A%202%20%7D%0A%0A%7B%20a%3A%201%0A%20%20b%3A%202%20%7D)

**Comment by GeoffreyBooth** [comment]
Currently
```coffee
{ a: 1
  b: 2 }
```
throws
```
[stdin]:2:6: error: unexpected indentation
  b: 2 }
     ^
```
which I believe is correct. The `b` line is indented when it shouldn’t be. It would be better if the caret pointed at the `b`, but that’s a quibble. The error message is specific enough.

As a general policy I don’t think we should be creating more exceptions where CoffeeScript ignores indentation. We’re a whitespace-significant language, and people just need to get used to that.

If you want the keys to start on the same column, just write it like:
```coffee
{
  a: 1
  b: 2
}
```
