### ISSUE TITLE
isa operator

### ISSUE THREAD

**Issue by maxnordlund** [jashkenas/coffeescript#2705]
I think most of you, like me, had trouble with when to use `typeof` and `util.isArray` or the like. Therefore I suggest that coffeescript adds a new keyword, `isa` that correctly use `typeof` or a helper function, like `util.isArray`.

Compare

```
if typeof arg is "function" or (Object::toString.call(arg) is "[object Function]")
  arg "Hello
else if typeof arg is "string"
  hash[arg] "World"
```

to

```
if arg isa Function
  arg "Hello"
else if arg isa String
  hash[arg] "World"
```

I think the last one is much cleaner, and even if a new keyword might go against the "it's just javascript" it's worth it. The `of` keyword or the splat magic might also be viewed as a violation, but worth it every time. Any feedback welcomed.

**Comment by andrewminer** [comment]
Sorry to dig up an old topic, but I just ran across this desire myself.  What if the proposed operator only worked on CoffeeScript-style classes by using the `@constructor.name` for a comparison?  In that case, some CoffeeScript like:

```CoffeeScript
if foo isa Bar then console.log "Let's get a drink!"
```

would translate to:
```JavaScript
if (foo && foo.constructor && foo.constructor.name == 'Bar') {
    console.log("Let's get a drink!");
}
````

However, I can see that this may also be treading too close to hairy type logic for CoffeeScript as well, so please feel free to ignore this alternative if that doesn't seem workable either.

**Comment by jashkenas** [comment]
> I can see that this may also be treading too close to hairy type logic for CoffeeScript as well

Quite. In CoffeeScript, and in JavaScript (and in any other flexible dynamic language), prefer duck typing to runtime static type checks.

    if foo.sells('drinks')
      console.log "Let's get a drink!"
