### ISSUE TITLE
Source maps when compiling with --output

### ISSUE THREAD

**Issue by phenomnomnominal** [jashkenas/coffeescript#2806]
There seems to be an issue when outputting a source map to a specified folder using **--output** - someone please tell me if I'm missing something!
## Issue:

If you compile with **--maps/-m**, everything seems to be golden and you get a shiny source map:

```
coffee --compile --map coffeescript/index.coffee
```

**coffeescript/index.map**

```
{
  "version": 3,
  "file": "index.js",
  "sourceRoot": "",
  "sources": [
    "index.coffee"
  ],...
```

However, if you use **--output/-o**, you get the same result, despite the fact that the source is now in a different place relative to the map. The source map does end up in the specified output folder though.

```
coffee --output javascript/ --compile --map coffeescript/index.coffee
```

**javascript/index.map**

```
{
  "version": 3,
  "file": "index.js",
  "sourceRoot": "",
  "sources": [
    "index.coffee"
  ],...
```
## Expected result:

This is what should be generated instead:

```
{
  "version": 3,
  "file": "index.js",
  "sourceRoot": "",
  "sources": [
    "../coffeescript/index.coffee"
  ],...
```

**Comment by GeoffreyBooth** [comment]
The source maps code has been refactored since this issue was opened. Please comment if this is still an issue and I will reopen.
