### ISSUE TITLE
Inline sourcemaps line number mismatching

### ISSUE THREAD

**Issue by Page-** [jashkenas/coffeescript#2861]
When using coffee-script with inline sourcemaps I have an issue that my mappings seem to be off by one by debugging.
It appears to be caused by 5fb047930ece21fc8f5b5a43a91f74ca07f48db5, because if I remove the `or options.inline` then it maps nicely, however I'm confused as the commit message says it fixes them (am I doing something wrong?).

**Comment by timaschew** [comment]
any updates here? I figured out that some lines working fine, other are not working if I set breakpoints in chrome, see  https://github.com/substack/coffeeify/issues/7#issuecomment-95120033

**Comment by GeoffreyBooth** [comment]
The fix above has been merged in a while ago.
