### ISSUE TITLE
unexpected INDENT error even on an empty line 

### ISSUE THREAD

**Issue by brodo** [jashkenas/coffeescript#2868]
While I was working today I encountered a strange unexpected INDENT error. [Here is the code I'm working on](https://gist.github.com/brodo/5204377). 

I always get an unexpected INDENT error on the same line (130), no matter what there is on this line. If I use the -c compiler flag it works with no problems.

**Comment by navaneethcsiva** [comment]
I am facing the indentation error for one of my slack bot project. I am using Hubot framework, which is developed in coffee script. even the freshly created hubot using "yo hubot" is not working and throwing indent error. I am stuck with this. It would be great if someone helps me with this. I have to run my hubot by going into the hubo directory and run "bin/hubot". What is the -c option? How should I run that.
Any help will be greatly appreciated. 

Thanks.

**Comment by Inve1951** [comment]
`-c` tells coffeescript to export the compiled js to disk instead of running it
