### ISSUE TITLE
Remove extraneous new line after block comments?

### ISSUE THREAD

**Issue by brian428** [jashkenas/coffeescript#2889]
As you can see from Js2Coffee, this:

```
###*
* A comment
###
math =
  root:   Math.sqrt
```

Compiles to this:

```
/**
* A comment
*/

var math;

math = {
  root: Math.sqrt,
};
```

Is there any way to omit the extraneous new line, so it compiles to something like:

```
/**
* A comment
*/
var math;

math = {
  root: Math.sqrt,
};
```

I realize this doesn't affect the compiled code at all. However, some (non-CoffeeScript) people prefer looking at the JavaScript if they are studying the code, and this makes the JavaScript look strange. If it's a total pain to do this, that's fine. But if it's something that would be easy to do, could this be implemented?

Thanks,

Brian

**Comment by GeoffreyBooth** [comment]
This is fixed via #4572. Sorry it took awhile.
