### ISSUE TITLE
bodyless class as argument in implicit call

### ISSUE THREAD

**Issue by shesek** [jashkenas/coffeescript#2895]
``` coffee
# unexpected end of input:
x class

# works as expected:
x class then

# passes `a` as an argument to `f`
# (also works as expected with `class then`)
->
  f class
  a
```

**Comment by GeoffreyBooth** [comment]
This compiles in CS2. Not sure if it should, or if some other behavior is expected:

```js
x(class {}, x(class {}), function() {
  return f(class {}, a);
});
```

**Comment by shesek** [comment]
Try compiling the code snippets independently, not concatenated to each-other. This appears to still be an issue in CS2 (though a pretty minor one - bodyless classes are not very common).

Here's an alternative example that might make this clearer:

```coffee
x = class

# compiles to: x = class {};
```

```coffee
x = y class

# error: unexpected end of input
```

```coffee
y class

# error: unexpected end of input
```

```coffee
x = y(class)

# compiles to: x = y(class {})
```


```coffee
x = y class
  z: -> 1

# compiles to:
# x = y(class {
#   z() {
#     return 1;
#   }
# });
```

**Comment by GeoffreyBooth** [comment]
What output would you expect? And why is this important (as in, why are bodyless classes worth supporting at all)?

**Comment by shesek** [comment]
> What output would you expect?

`y class` should be `y(class {})`.

> And why is this important (as in, why are bodyless classes worth supporting at all)?

I had some reason back in 2013, but I honestly don't remember now. Might've had something to do with testing and dynamically creating new classes, I think?

I'm not sure that this is important and worth supporting, but I find the inconsistency a bit odd.
