### ISSUE TITLE
boolean 'in' expressions for numeric ranges build inefficient code

### ISSUE THREAD

**Issue by rattigan** [jashkenas/coffeescript#2915]
It would be nice if the special treatment in for-loops extended to boolean expressions using 'in':

{code}
success = code in [200..299]
{code}

Currently this builds very inefficient code.

**Comment by GeoffreyBooth** [comment]
If someone feels like refactoring this, a pull request would be welcome. Until then, the chained comparison syntax (`success = 200 <= code <= 299`) is pretty good.
