### ISSUE TITLE
literate Cakefile

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#2927]
Hi

It would seem to me I should be able to write a Cakefile literally! Below does not work in vesion _1.6.2_.

```
Cakefile
======

Require.

    {spawn, exec} = require 'child_process'

Build helper.

    build = () ->

      console.log 'built.'

Commands
-----------------

Build task.

    task 'build', 'Build help.', () ->
      build()

```

Is there support planned for this? If so, how soon? I _love_ literate development :)

**Comment by nathancarter** [comment]
In the meantime, you can use this workaround.  Make your Cakefile just contain the following.  Then put everything in `cake.litcoffee`.
```coffeescript
require 'coffee-script/register'
require './cake'
```

**Comment by GeoffreyBooth** [comment]
Closing as [the workaround](https://github.com/jashkenas/coffeescript/issues/2927#issuecomment-102171465) seems sufficient for people’s needs.
