### ISSUE TITLE
Extending a class doesn't copy static properties

### ISSUE THREAD

**Issue by lukesutton** [jashkenas/coffeescript#296]
I was expecting the following to work:

```
class Example

  instance_method: ->
    "I'm an instance method."

  @class_method: ->
    "I'm a class method."

class Jam extends Example
```

Unfortunately it doesn't appear that the reference to 'class_method' is being copied over to Jam, which is not what I expected.

If I inspect the property on each, I can see Example has it defined, but not Jam.

**Comment by JulianKingman** [comment]
I followed your thread for a similar issue elsewhere, and was referred to this package: https://github.com/mridgway/hoist-non-react-statics
