### ISSUE TITLE
Lexer: Object literal with inconsistent indentation parsed as multiple objects

### ISSUE THREAD

**Issue by loveencounterflow** [jashkenas/coffeescript#2998]
today i wrote

```
known_colors =
   45:              'cyan'
   52:              'sepia'
  100:              'olive'
  124:              'red'
```

in an effort to neatly align those figures. of course, this is isn't syntactically valid, as it doesn't keep indentation... BUT it didn't generate an error, either, so my script silently failed. so i compiled it, and this is what came out:

```
  known_colors = {
    45: 'cyan',
    52: 'sepia'
  };

  ({
    100: 'olive',
    124: 'red'
  });
```

could the result be meaningful in any real-life situation? it seems rather meaningless to me. i think the above code should throw a syntax error.

**Comment by GeoffreyBooth** [comment]
As of 2017-05-05 in CS2, the initial example still fails, in my opinion:

```js
var known_colors;

known_colors = {
  45: 'cyan',
  52: 'sepia'
};

({
  100: 'olive',
  124: 'red'
});
```

At the very least we should throw an “inconsistent indentation” error. Compiling into two objects is worse than outputting invalid JavaScript. At least invalid JS throws an error in the runtime.

**Comment by GeoffreyBooth** [comment]
Related to #2667.

**Comment by GeoffreyBooth** [comment]
Closing per discussion in #4630. Unfortunately it appears there’s no solution for this that doesn’t cause unwanted side effects that may be breaking changes.
