### ISSUE TITLE
another indentation bordercase 

### ISSUE THREAD

**Issue by loveencounterflow** [jashkenas/coffeescript#3010]
looks like this is becoming a habit: https://github.com/jashkenas/coffee-script/issues/2998

all of these will compile & run just fine:

```
if true
# ok
  x = 1

if true
  # ok
  x = 1

if true
  ### ok ###
  x = 1
```

but not this one:

```
if true
### oops ###
  x = 1
```

the error message says, unhelpfully:

```
error: unexpected POST_IF
if true
^^
```

which makes it look like i had inserted an expression, not a comment at the point in question.

use case:

```
f = ->
  ###TAINT this clause will always be executed ###
  if true
    x = 1
  ###TAINT else clause is unreachable ###
  else
    x = 0
```

i like to comment on clauses etc _before_ the indent when the comment is about the entire clause. that's ok with ordinary comments, but not w/ herecomments (which have the distinction to be preserved for the accidental JS aficionado). 

incidentally, the error message is just as unhelpful in this case:

```
error: unexpected INDENT
###TAINT else clause is unreachable ###
                                      ^ 
```

i can somehow understand & live w/ the first message, but this is bollocks: how can the last character on a line not be correctly indented? or have an unexpected indent? **only line-initial linear whitespace followed by non-whitespace ('printing') characters can ever constitute indentation** and is, therefore, the only eligible entity for this kind of complaint. other stuff–the rest of the line, blank lines, and, i'd've thought, comments, too–are simply not in a position for that (quite literally). 

(i'll try and get a module online the next few days that does nothing but line-initial whitespace parsing. btw i was a little sad the other day when realizing that CS Redux would appear to have major issues concerning indentation, which seems to support my hunch that whitespace grammar should be kept apart from the rest of the language.)

**Comment by GeoffreyBooth** [comment]
```coffee
if true
### oops ###
  x = 1
```
compiles now, via #4572. Sorry it took awhile.
