### ISSUE TITLE
Forward-slashes are escaped for block regular expressions. Feature or bug?

### ISSUE THREAD

**Issue by Kerrick** [jashkenas/coffeescript#3022]
In JavaScript regular expressions you must escape a forward slash, but doing so in CoffeeScript block regexes means you get an escaped backslash followed by a forward slash that terminates your compiled regex early.

``` bash
kerrick@kadabra:~ $ coffee -sp
```

``` coffeescript
reg = /// ^
  test
  \/
  ing
$ ///
```

``` bash
^D
```

``` javascript
(function() {  var reg;

  reg = /^test\\/ing$/;

}).call(this);
```

If it's a feature, it should be documented in [the appropriate section of coffeesrcipt.org](http://coffeescript.org/#regexes), because it is non-obvious. Perhaps instead of:

> extended regular expressions that ignore internal whitespace and can contain comments and interpolation. 

Maybe it could say:

> extended regular expressions that ignore internal whitespace, can contain comments and interpolation, and automatically escape forward slashes.

**Comment by django-class-based-views** [comment]
@Kerrick https://openjs.space/questions/pattern-matching-for-spaces-and-quotation-marks
