### ISSUE TITLE
Interpolated dynamic keys are allowed if the interpolation string is empty

### ISSUE THREAD

**Issue by aaylward** [jashkenas/coffeescript#3039]
As of https://github.com/jashkenas/coffee-script/commit/4cab45c759e1699822ea3508355b43d1ecd0b5a1 , dynamic keys are not allowed.

```
➜  coffee-script git:(master) ✗ coffee -e 'console.log "#{1}":1'
[stdin]:1:19: error: unexpected {
console.log "#{1}":1
                  ^
```

This is as it should be, but

```
➜  coffee-script git:(master) ✗ coffee -e 'console.log "#{}":1'
{ '': 1 }
```

As @michaelficarra noted in #3038 , this should be a syntax error.

**Comment by lydell** [comment]
I’d vote for closing this and implement https://github.com/jashkenas/coffeescript/issues/3597#issuecomment-68623619 instead.

**Comment by jashkenas** [comment]
Nah -- If we bring back dynamic keys, we should implement them reliably.

That said, we would need a patch that brings back dynamic keys and also allows you to call `super` (somehow) from a method defined with a dynamic key as the property name.

**Comment by vendethiel** [comment]
This works in coco:

```livescript
class A
  (b + "a"): -> super
```

which compiles to

```js
var key$, A;
A = (function(){
  A.displayName = 'A';
  var key$, prototype = A.prototype, constructor = A;
  prototype[key$ = b + "a"] = function(){
    return superclass.prototype[key$];
  };
  function A(){}
  return A;
}());
```

**Comment by jashkenas** [comment]
Looks like a fine solution. I guess there wouldn't be any strange situations where the value of the super reference needs to be known somewhere that isn't in lexical scope for the generated name...

**Comment by lydell** [comment]
Does that mean that

```coffee
a::[x]=->super
```

should compile to:

```js
var _key;
a.prototype[_key = x] = function() {
  return a.__super__[_key].apply(this, arguments);
};
```

?

**Comment by jashkenas** [comment]
Nah -- In general, we the current error message is fine for those. We're never going to be able to detect at compile-time when you're dynamically assigning prototype methods. For example, even if you "fixed" the above, that wouldn't fix this:

    proto = a.prototype

    proto[key] = ->
      super

**Comment by lydell** [comment]
I see, thanks.

**Comment by lydell** [comment]
But still:

```coffee
class A
  x: -> super # currently valid
  @::x = -> super # current valid
  "x": -> super # currently valid
  "#{x}": -> super # decided to be ok

A.x = -> super # currently invalid (we know the key but not the superclass)
A::x = -> super # currently valid (we know both)
A::["x"] = -> super # currently valid (we know both)
A::["#{x}"] = -> super # shouldn’t this be valid, since the two above are? (we _do_ know both!)
```

In other words, if you think that `a::["#{x}"]=->super` (aka `a::[x]=->super`) should be invalid, why is `a::x=->super` valid?

**Comment by jashkenas** [comment]
I see what you're saying -- sure, why not.

    A::["x"] = -> super

... was a special-case that was added as a bonus. I guess if we're going to add dynamic keys, then dynamic values are fine there as well.
