### ISSUE TITLE
Add yield support

### ISSUE THREAD

**Issue by gunta** [jashkenas/coffeescript#3073]
I know that the policy was not new adding new ES6 features.

But now, it's 2013, 
and the latest V8 and Node.js 0.12 supports `yield`, 
which is one of the best features to prevent callback hell.

We should add support for it, because it really improves the current situation of callbacks spaghetti in Node.js.

Thank you.

**Comment by socketpair** [comment]
I did not understand, is ``yield`` supported or not now.

**Comment by monolithed** [comment]
You do not understand. 
We have the operator `%%`, which is much more important and useful :stuck_out_tongue_winking_eye

:racehorse:

**Comment by socketpair** [comment]
@monolithed, your joke is not relevant. Please write on the case.

**Comment by monolithed** [comment]
@socketpair, try ES6

**Comment by bjmiller** [comment]
Generator support now exists on master, and will go out with the next major release.

(Unless I'm missing something?)

**Comment by let4be** [comment]
You are missing ES6, why would you need to use outdated coffee when you can
use ES6 generators with traceur or 6to5? ;)
classes, modules, arrow function and many else

2015-01-26 17:04 GMT+03:00 Brian Miller <notifications@github.com>:

**Comment by bjmiller** [comment]
https://github.com/jashkenas/coffeescript/issues/3162#issuecomment-70960807

**Comment by MattKunze** [comment]
Bummer, seems like there's no support for [`yield*`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*) - we've started using redux-saga and it's been working great, but just came across a case where `yield*` made things a lot simpler and had to escape it with backticks.

**Comment by lydell** [comment]
@MattKunze `yield*` is called `yield from` in CoffeeScript.

**Comment by MattKunze** [comment]
Awesome, thanks! Somehow missed that in the docs

**Comment by foxbunny** [comment]
> Agreed. I think that we should start considering the new features as soon as they begin to work in browsers, and on Node.

@jashkenas Do you think it would be unreasonable to target Babel and similar with CS output, rather than the 'bare-metal' runtimes? Cause that's kinda what I was contemplating. :)
