### ISSUE TITLE
Node Domain, Sync Code & Running from Command Line

### ISSUE THREAD

**Issue by iamdoron** [jashkenas/coffeescript#3139]
Let's say the following code is within a file called app.coffee:

``` coffee
domain = require 'domain'

dom = domain.create()
dom.on 'error', (err) ->
    console.log("the domain caught the error")

dom.run ->
    # some syncronous code
    throw new Error();

```

if you run:
`> coffee app.coffee`
the exception will not get caught via the domain, but will be thrown as an uncaught exception (the application will exit).
If, on the other hand, you compile to js, and then run, it works like a charm.

the reason behind it is that the `module._compile` is being wrapped by a `try-catch` block, which means that any sync code that will throw an exception will be caught by this try catch, including one that is wrapped by node domain module.

see/follow https://github.com/joyent/node/issues/6127 , as I'm not sure if it's a feature or a bug :-) :bug:

**Comment by GeoffreyBooth** [comment]
Not sure if this is still an issue, but even if it is, the `coffee` command is meant for compilation and debugging, not replacing `node` as a way to launch the runtime. Certain edge cases will require compilation first and then execution via `node`, as opposed to `coffee`.
