### ISSUE TITLE
regexp with equal /=/

### ISSUE THREAD

**Issue by bline** [jashkenas/coffeescript#3182]
currently the compiler gives an error unexpected MATH if you have a regular expression where the only character in it is equal (=) sign.

example:

```
bline@magus:~$ coffee -e '"foo=bar".match /=/'
[stdin]:1:19: error: unexpected MATH
"foo=bar".match /=/
                  ^
```

work around:

```
bline@magus:~$ coffee -e '"foo=bar".match /[=]/'
bline@magus:~$ 
```

If anything else is in the regexp along with the =, it parses fine. Also this works:

```
bline@magus:~$ coffee -e '"foo=bar".match new RegExp "="'
bline@magus:~$
```

```
bline@magus:~$ coffee --version
CoffeeScript version 1.6.3
```

I also tested the above code on http://coffeescript.org/ and http://js2coffee.org/ and got the same error.

**Comment by lydell** [comment]
@epidemian compare one of your examples with:

```coffee
foo.sum +=bar+
Math.floor 42.1
```

The compiled JS is expected to me. Should `/` be a special case? I don't think so, at least.

**Comment by epidemian** [comment]
@lydell fair point.

It seems a bit sad to me that `s.match(/=/)` is valid JS but not valid CS. It *looks* like valid code. But i understand where the ambiguity comes from.
