### ISSUE TITLE
CLI: Generate source map when running file directly too

### ISSUE THREAD

**Issue by aseemk** [jashkenas/coffeescript#3187]
Really terrific work on source maps so far. I'm finally trying it out for the first time, and it's so cool! =)

I tend to run CoffeeScript mostly on the server-side / with Node.js, rather than in the browser. There exists the equally awesome [node-inspector](https://github.com/node-inspector/node-inspector) for debugging server-side code, and StrongLoop [recently added](http://strongloop.com/strongblog/announcing-a-new-and-improved-node-js-debugger/) source maps support to it as well.

However, I tend to run server-side CoffeeScript with the `coffee` binary directly, rather than compiling it to JS first, and unfortunately CoffeeScript doesn't support outputting a source map file when running code directly right now.

Is this something y'all would be open to supporting? Example use case:

```
coffee --map --nodejs --debug app.coffee
```

Thanks for the consideration!
## 

Implementation notes:

Running a file directly means ultimately compiling it on the fly via a `require()` hook.

CoffeeScript 1.6.3 does/did at least generate a source map on such on-the-fly compiles:

https://github.com/jashkenas/coffee-script/blob/1.6.3/src/coffee-script.coffee#L145-L157

It just didn't output it anywhere.

However, that source map generation was removed after 1.6.3:

https://github.com/jashkenas/coffee-script/commit/3d761e73e3bd38fe097aac3f33dcb74917acb8c4

So perhaps the best solution would be to keep the latest behavior by default, but support generating _and outputting_ the map if a `--map` argument was given.

This would, however, necessitate a change in the CLI, which currently only runs the given file if no options are given.

**Comment by benlambt** [comment]
If  `coffee --map --nodejs --debug app.coffee` were to append source maps to the javascript output in base64 then we could see the coffeescript in node inspector.

See: https://github.com/node-inspector/node-inspector/issues/224#issuecomment-38785891

**Comment by GeoffreyBooth** [comment]
This is possible now, via `--inline-map`.

```bash
node --inspect-brk ./bin/coffee --inline-map test.coffee
```

![image](https://user-images.githubusercontent.com/456802/30898815-02d4d5be-a312-11e7-823a-d4b287e44735.png)


If this is somehow insufficient please comment and I’ll reopen.
