### ISSUE TITLE
Add Yield Support with Fallback?

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/coffeescript#3215]
As another alternative to adding simple `yield` pass-throughs ... Facebook has a project which claims (and seems) to be able to implement generators as a state-machine transformation pretty cleanly:

http://facebook.github.io/regenerator/

Should we consider something like this?

**Comment by lydell** [comment]
This can be closed now, right?

**Comment by GeoffreyBooth** [comment]
Yes. We now compile to ES generator syntax.
