### ISSUE TITLE
Unexpected 'HERECOMMENT' when trying to embed comment blocks between switch cases

### ISSUE THREAD

**Issue by mizzao** [jashkenas/coffeescript#3219]
Trying to embed multi-line comments such as

``` coffeescript
foo = switch
  ### This is a comment ###  
  when bar > 2 then "This is a bug"
  ###
    This is another comment 
  ###
  when bar > 3 then "This is also a bug"
```

Generates errors such as 

```
Error: Parse error on line 2: Unexpected 'HERECOMMENT'
```

I'm guessing this is a bug, because single-line comments work fine. Feel free to test that snippet at http://js2coffee.org/#coffee2js.

**Comment by GeoffreyBooth** [comment]
This is fixed via #4572. Sorry it took awhile.
