### ISSUE TITLE
`@@` shortcut for `this.constructor`

### ISSUE THREAD

**Issue by steckel** [jashkenas/coffeescript#3222]
Apologies if this has been previously discussed (which I couldn't find any evidence of though it's difficult to imagine it hasn't.)

Would it be a horrendous idea to have `@@property` compile down to `this.constructor.property`?

Out of curiosity, I may take a stab at hacking it together for fun, but I'm curious of the decision not to do that from the beginning?

**Comment by uMaxmaxmaximus** [comment]
sooo?
