### ISSUE TITLE
ctor appearing in the nodejs heap instead of the classname

### ISSUE THREAD

**Issue by pflannery** [jashkenas/coffeescript#3236]
I recently discovered that a call like this 

```
new SomeClassName(args...) 
```

gets referenced as ctor in nodejs heap snapshots and not as SomeClassName. 
The bummer about this is if you have multiple classes using the syntax above then you end up with a mixed bag of classes called ctor in the heap.

Here is a screen shot of a heap output I'm seeing 

![coffee-nodejs-heap-ctor](https://f.cloud.github.com/assets/1727302/1519269/42599b50-4b57-11e3-8d48-780d965140aa.png)

The line of code that is causing this is [here](https://github.com/jashkenas/coffee-script/blob/efb9809d3b4c67cfb483dcdc4563e8c1548f6cb1/src/nodes.coffee#L694)

I've pondered what could be done when this happens and I came up with a possible solution. We could rename the variable "ctor" to  use the class name as the variable instead. 

So as an example the javascript output ends up like this for the class called "SomeClassName"

```
(function(func, args, SomeClassName) {
    SomeClassName.prototype = func.prototype;
    var child = new SomeClassName, result = func.apply(child, args);
    return Object(result) === result ? result : child;
})(SomeClassName, args, function(){}))
```

I've tried this javascript code and the list of ctor disappear and the expected class names appear as expected in the snapshot heap.

Does that make sense, would it be possible or is there a caveat I'm not aware of?

**Comment by pflannery** [comment]
I've recently come across this again and I found a way to separate the ctor's in to something that will relate each instance to its original class being created.

```js
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args);
      return typeof result === "object" ? result : child;
    })(SomeClass, args, function SomeClass(){});
```
the only other way that works but suffers a performance loss is to use ```new (Function.prototype.bind.apply(SomeClass, [null].concat(args)))```

**Comment by pflannery** [comment]
I've just found a memory issue with ```new SomeClass(args...)``` in the current version of coffee 1.9.1

I used the following test scripts for comparision. 

**Coffee script** I used [here](http://js2.coffee/#coffee/try:class%20A%20%0A%20%20constructor%3A%20()%20-%3E%20%0A%0Aclass%20B%20extends%20A%20%0A%20%20constructor%3A%20(args...)%20-%3E%20%0A%20%20%20%20this.arg0%20%3D%20args%5B0%5D%3B%0A%20%20%0A%20%20%40create%3A%20(args...)%20-%3E%20%0A%20%20%20%20return%20new%20B(args...)%0A%20%20%0A%23%20test%20code%0Alist%20%3D%20%5B%5D%3B%0Ai%20%3D%200%0Awhile%20i%20%3C%2010000%0A%20%20i%2B%2B%0A%20%20list.push(B.create(i))%3B)

**Babel script** I used [here](https://babeljs.io/repl/#?experimental=false&playground=false&evaluate=true&loose=true&spec=false&code=class%20A%20%7B%0A%20%20%0A%7D%0A%0Aclass%20B%20extends%20A%20%7B%0A%20%20constructor(...args)%20%7B%0A%20%20%20%20this.arg0%20%3D%20args%5B0%5D%3B%0A%20%20%7D%20%20%0A%20%20%0A%20%20static%20create(...args)%20%7B%0A%20%20%20%20return%20new%20B(...args)%0A%20%20%7D%0A%7D%0A%0Alet%20list%20%3D%20%5B%5D%2C%0A%20%20i%20%3D%200%0Awhile%20(i%20%3C%2010000)%20%7B%0A%20%20i%2B%2B%0A%20%20list.push(B.create(i))%3B%0A%7D)

**Function.prototype.bind script** I used [here](http://jsbin.com/sinenefeli/1/edit)

For each test I took heap snapshots in Chrome 41 and noted the overall memory usage in the statistics chart (see screenshots below)
Each test was taken with 10000 iterations and then with 100000 iterations.

**Results**

procedure used| iteration count|memory stats
------------ | -------------| -------------
babel|10000|1.9MB
babel|100000|4.7MB
coffee|10000|3.7MB
coffee|100000|22MB (massive jump here)
Function.prototype.bind.apply|10000|1.8MB
Function.prototype.bind.apply|100000|3.6MB

**Babel 10000 iterations**
- ![babel 10000](https://cloud.githubusercontent.com/assets/1727302/6785536/0f5627a6-d17e-11e4-89c4-1cb8af12a75d.png)

**Babel 100000 iterations**
- ![babel 100000](https://cloud.githubusercontent.com/assets/1727302/6785539/14e4cb0a-d17e-11e4-9250-6ad4184cecbb.png)

**Coffee 10000 iterations**
- ![coffee 10000](https://cloud.githubusercontent.com/assets/1727302/6785553/1e638c84-d17e-11e4-854a-ee0de05bffd5.png)

**Coffee 100000 iterations**
- ![coffee 100000](https://cloud.githubusercontent.com/assets/1727302/6785555/23d55e68-d17e-11e4-80f1-1065ec3a7c4a.png)

**Function.prototype.bind 10000** iterations
- ![function proto 10000](https://cloud.githubusercontent.com/assets/1727302/6785561/309a692c-d17e-11e4-9779-8193b0fcb519.png)

**Function.prototype.bind 100000** iterations
- ![function proto 100000](https://cloud.githubusercontent.com/assets/1727302/6785564/35d992be-d17e-11e4-9dc5-593459b00536.png)

**Comment by balupton** [comment]
@pflannery and if:

```
	static create (a, b, c, d, e, f, g) {
		return new this(a, b, c, d, e, f, g)
	}
```

Is used instead?

**Comment by pflannery** [comment]
> @pflannery: Nope. You need the target of new to have an empty list of SourceElements in its [[Code]] internal property. Take a closer look at the current implementation.

@michaelficarra This code does exactly the same thing as the current implementation but without the excessive overhead in memory plus being placed at the top would save some repetitive code output.
```js
function __applyConstructor(ctor, args) {
  // using apply with constructors 
  // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#Example:_Using_apply_to_chain_constructors
  var instance = object.create(ctor.prototype);
  ctor.apply(instance, args);
  return instance;
}
```

Funny thing is that instead of `ctor` every class created this way will be defined as `Object` in a heap snapshot but it's a better place than the current situation and it would be easy for an analyst to swap the body of `__applyConstructor` to use `return new (Function.prototype.bind.apply(ctor, [null].concat(args)))`  when they want to analyse classes created this way.

I'm happy to PR on this.

**Comment by pflannery** [comment]
@balupton I'm guessing are conversions got crossed in to this issue :)
>   @pflannery and if:
    static create (a, b, c, d, e, f, g) {
        return new this(a, b, c, d, e, f, g)
    }
    Is used instead?

I've not made any perf tests to see and I don't think it will fulfil rest argument class constructor creation requirements.

**Comment by GeoffreyBooth** [comment]
This should no longer be an issue on the `2` branch now that we compile to ES classes.
