### ISSUE TITLE
problem with non-utf8 encoded files

### ISSUE THREAD

**Issue by kittee** [jashkenas/coffeescript#3251]
When working with non-utf8 encoded files (i.e. koi8r) compiling process damages non-latin characters so they cannot be read in resulting .js
I came to this https://github.com/kittee/coffee-script/commit/deb8ade32ed8a349c1dc7de7651821188bbdd17f workaround but I don't know if it is safe to use or not. Please tell me.

**Comment by GeoffreyBooth** [comment]
I don’t think supporting non-UTF-8 or UTF-16 files is something that we consider to be in our scope.
