### ISSUE TITLE
Backtick Javascript Escape Bug: Adds Semicolon

### ISSUE THREAD

**Issue by bdkjones** [jashkenas/coffeescript#3265]
If you use the backtick to escape a piece of Javascript that ends with a semicolon like this:

```
`alert("hello");`
```

The compiler duplicates the semicolon, turning the line into:

```
alert("hello");;
```

It looks like the compiler is just blindly throwing a semicolon on the end of any backtick-escaped Javascript snippets. This is definitely bad behavior. It's present in 1.6.3.

Can we get this one fixed before 2016? (Given that the other bugs related to backticks haven't been fixed in a year and the amount of whining that took place in those threads about just how dumb it was to ever write anything other than CoffeeScript, I understand that this feature isn't the most popular one with the team. Still, it's badly broken and needs some attention, please.)

**Comment by adamdanielsdesign** [comment]
@jashkenas Old issue at this point, however, could an additional syntax be implemented using for example two backticks to specify fully compiler skipped,  1:1 compile, code?
```
#example:
``
/**
* Some doc comment
* @method someMethod
*/
``
```
