### ISSUE TITLE
(args...) v8 disabled optimisation issue

### ISSUE THREAD

**Issue by pflannery** [jashkenas/coffeescript#3274]
When using the `args...` statement V8 disables optimization for the method.

The reason being is that when the arguments variable is passed to other methods during a call i.e. slice. V8 will disable the optimization for the calling method.

V8 trace output

```
[disabled optimization for %methodName%, reason: bad value context for arguments value]
```

I know this is V8 specific but I have done some benchmark tests that show using slice on small arrays is slower than actually copying them on most browsers (also using node).

[Arguments Copy Benchmark](http://jsperf.com/copy-fn-arguments-test)
[Array Copy Benchmark](http://jsperf.com/copy-array-test)

So changing `args...` to use a manual copy of the arguments instead of using slice would benefit plus we would get optimisation with `args...` functions in chrome and node.

To recreate the trace then go to this related issue bevry/taskgroup#12

**Comment by jashkenas** [comment]
Bumping this with a new JSPerf.

http://jsperf.com/rest-parameters

**Comment by pflannery** [comment]
:+1:  I tested on IE 11 too, it's getting similar results

In case anyone missed it, this is the change that was committed in NodeJs - https://github.com/joyent/node/commit/7ced966a32dd18b4de2768f41796af76638341f9

**Comment by sgentle** [comment]
What about @michaelficarra's solution minus the external helper? The `Array` constructor accepts any number of arguments (except 1 because Javascript) and turns them into an array. So you can call `Array.apply(null, arguments)` without causing a deopt.

http://jsperf.com/rest-parameters/2

**Comment by balupton** [comment]
Considering rest parameters aren't landing anytime soon, can we get the:

``` javascript
    var args = new Array(arguments.length);
    for (var i = 0; i< arguments.length; i++) {
            args[i] = arguments[i];
    }
```

Added instead of the current method? As it is much faster...

This method doesn't work when arguments are none:

```
var i$ = 1, l$ = arguments.length, args = new Array(l$ - i$);
for(; i$ < l$; ++i$) args[i$ - 1] = arguments[i$];
```

**Comment by balupton** [comment]
I've setup a benchmark repo here: https://github.com/bevry/es6-benchmarks

**Comment by DylanPiercey** [comment]
Is this waiting for someone to implement or a decision to be made?

**Comment by isiahmeadows** [comment]
@jashkenas What do you think of this?

I believe this optimization would benefit most modern engines at this point, as they aggressively avoid arguments object allocations to reduce the overhead of calling variable-length functions. This includes Spidermonkey, V8, JSC, Chakra, and [even IE 11](https://github.com/jashkenas/coffeescript/issues/3274#issuecomment-75271850). Babel, TypeScript, LiveScript, and several others convert rest arguments to use effectively the same process, shallow-copying part of the arguments object manually. I don't see why this wouldn't hurt.

**Comment by balupton** [comment]
@jashkenas is currently doing a year of zen and the art of motorcycle maintenance it seems, so perhaps best to delegate to another who has maintainance privelleges?

**Comment by STRML** [comment]
Any news on this? We would immediately see performance improvements in hundreds of projects.

**Comment by GeoffreyBooth** [comment]
CS2 compiles to ES2015 rest/spread syntax, at least for the last parameter which is the only one where it is supported in ES.
