### ISSUE TITLE
Alternate compilation for array filtering comprehensions

### ISSUE THREAD

**Issue by ethanresnick** [jashkenas/coffeescript#3291]
When a return value is being produced, array comprehensions of the form `(identifier for identifier in collection when boolean)` currently compile to this:

```
(function() {
  var _k, _len, _results;
  _results = [];
  for (_k = 0, _len = collection.length; _k < _len; _k++) {
    identifier = collection[_k];
    if (boolean) {
      _results.push(identifier);
    }
  }
  return _results;
}).call(this);
```

It seems to me that a compilation like the following would be more elegant:

```
__filter(collection, function(item) {
  return boolean;
}, this);
```

Where `__filter` is defined as:

```
function __filter(collection, fn, thisArg) {
  var _k, _len, _results, item;
  _results = [];
  for (_k = 0, _len = collection.length; _k < _len; _k++) {
    item = collection[_k];
    if (fn.call(thisArg, item)) {
      _results.push(item);
    }
  }
  return _results;   
}
```

In addition to being shorter, this alternative compilation [seems](http://jsperf.com/array-filtering-approaches/3) to generally run a little faster, though I'm not sure why. 

Thoughts?

(Note that __filter isn't meant to be a shim for `Array.prototype.filter`, which is a more complex algorithm; it's just meant to match the semantics of the current comprehension.)

**Comment by GeoffreyBooth** [comment]
Closing as there doesn’t seem be consensus that this should be changed.
