### ISSUE TITLE
SourceMap: Consistency in map filename

### ISSUE THREAD

**Issue by am11** [jashkenas/coffeescript#3297]
LESS and SASS / SCSS compilers generate the SourceMap file with the following naming convention:

> sourceFileName.css.map

For consistency, please change the CoffeeScript's map filenames with the same format:

> sourceFileName.js.map

*(as opposed to current implementation: `soucrFilename.map`)*

In general:

> sourceFileName.targetExtension.map

**Comment by dgoldstein0** [comment]
Hm, I believe this is fixed in 1.9 or 1.10?

**Comment by lydell** [comment]
@dgoldstein0 You're right.

**Comment by am11** [comment]
Great! thanks for the info guys. 🎉 🎆
