### ISSUE TITLE
Adding for/else?

### ISSUE THREAD

**Issue by 2rs2ts** [jashkenas/coffeescript#3298]
Would it be possible to work in a `for/else` construct? Such as in python:

```
for x in lst:
    if cond(x):
        do_stuff_with(x)
        break
else:
    do_other_stuff()
```

Currently I'd write my coffeescript like this to do the same:

```
found = false
for x in lst
    if cond x
        found = true
        do_stuff_with x
        break
if not found
    do_other_stuff()
```

It's just a little syntactic sugar, but it'd be nice.

**Comment by edemaine** [comment]
Sorry to revive an old issue, but lots of the discussion has been around Coco's for...else semantics (which seems not especially useful), and not so much about Python's for...else semantics, which I've used a lot and find very helpful.  Yes, you can use the idiom:

    found = false
    for ...
      if ...
        found = true
        break
    unless found
      ...

But the idea is to avoid having to write the idiom (2-3 lines worth), and just say

    for ...
      if ...
        break
    else
      ...

This is especially useful if there's lots of computation between the `for` and `if`, many `break` cases, etc.  It's actually error prone to have to write `found = true` next to each `break`.

Another fun example you can do with these semantics is to `break` out of two loop levels:

    for x in ...
      for y in ...
        break if ...
      else
        continue
      break

Admittedly, this is pretty unreadable... but it is convenient. :-)

Perhaps another name than `else` would make people happier?  In any case, I think it deserves further discussion.  I definitely miss this feature coming from Python.

**Comment by jashkenas** [comment]
Python's for/else feature isn't good enough for us to want to add to JavaScript. For a good introduction, see:

http://python-notes.curiousefficiency.org/en/latest/python_concepts/break_else.html

The first section, **Reasons for Confusion**, is especially relevant.

In any case, doing manual `found = true` searching through loops probably isn't what you should be writing most of the time. Instead of: 

```coffeescript
found = false
for item in list
  if item.property is 'value'
    found = item
    break
if found
  ...
```

Try something like:

```coffeescript
found = where list, property: 'value'
if found ...
