### ISSUE TITLE
Support real heredocs (and rename triple quote syntax)

### ISSUE THREAD

**Issue by ingydotnet** [jashkenas/coffeescript#3299]
Retitled this issue. Triple quotes are not heredocs. They should be called triple quotes as other languages do. Also it would be fantastic to have real heredocs in CoffeeScript such that literal chunks of programming related texts could be coded.

Original post below:

---

This gist https://gist.github.com/6b91be7ec9c623025782 shows how Bash, Perl and Ruby do single-quoted heredocs vs coffee.

With heredocs you want to be able to have a block of any untouched text. (Only the terminator is special). Double quote semantics are very useful, but single quoted ones, much less so.

I found this trying to load a yaml doc like this: https://gist.github.com/185217222594a161bada

You can easily imagine wanting to heredoc a block of coffeescript, or many other syntaxes that include backslashes.

**Comment by GeoffreyBooth** [comment]
Heredocs would be cool. The docs don’t call triple-quoted strings heredocs anymore (though the word does appear, erroneously in the changelog; not sure that’s worth revising).

Closing as this isn’t a top priority at the moment, but a PR that implements heredocs would be welcomed.

**Comment by johndeighan** [comment]
If I get the chance, I might attempt to create that PR (I'm pretty busy right now). Meanwhile, here's an example of what you can do with real HEREDOC syntax aka Perl, that you can't do with triple quoted strings:

hVars = {name: 'John', age: 68}
assert.equal(process(<<"", hVars), <<"", "variables in square brackets should be replaced")
This is a junk line
Hi, my name is [name] and I'm [age] years old

This is a junk line
Hi, my name is John and I'm 68 years old

Note how the line containing the assert is a complete statement all on one line - no need to scan down to past the strings to see what's being compared, what the name of the test is, etc. Also, FYI, I prefer to terminate each HEREDOC string with a blank line (works best if you set up your text editor to always strip all trailing whitespace). Much easier to grok.
