### ISSUE TITLE
child_process.fork doesn't work with coffee script file without extension

### ISSUE THREAD

**Issue by chulkilee** [jashkenas/coffeescript#3311]
coffee-script's child_process.fork is using `helpers.isCoffee` to determine whether to override binary with `coffee`.

The problem is that `isCoffee` only checks file extension, so it does not handle a file without extension but having shebang line. Why no extension? it's a run script for a cluster...

I can fix the problem by manually setting `process.execPath` before fork calls, but I wonder if there is a way to do it magically by coffee-script.

``` coffeescript
path = require 'path'
process.execPath = path.resolve __dirname, '../node_modules/coffee-script/bin/coffee'
```

I thought it would be nice if `isCoffee` reads shebang and detect it's coffee script, but I'm not sure it's good idea to add blocked call in that function.
Another way is to allow node's child_process.fork to accept execPath option,

**Comment by GeoffreyBooth** [comment]
This seems like quite an edge case for the `coffee` command to handle. The `coffee` command is intended for compiling and debugging, not as a substitute for the `node` command and runtime. We don’t intend to support every scenario that `node` supports—especially when the workaround is as simple as the one-liner you’ve posted here.
