### ISSUE TITLE
Disallow bare references to ivar params

### ISSUE THREAD

**Issue by vendethiel** [jashkenas/coffeescript#3318]
Forked from #1007

Disallow `(@a) -> a`

**Comment by lydell** [comment]
I’m working on this right now. Should `(@a, a) ->` be allowed or not? There are currently [tests](https://github.com/jashkenas/coffeescript/blob/bec8f27e8a68e68383eef254af2b4de67acf0d81/test/strict.coffee#L69) that specifically say that that example counts as duplicate parameter names, but in my opinion they’re not.

**Comment by vendethiel** [comment]
Probably shouldn't. That doesn't sound like something I'd want to happen

**Comment by connec** [comment]
It would be bad (terrible?) style for sure, but I wouldn't call them duplicate parameters if this change is made.

**Comment by michaelficarra** [comment]
Nope, they're not duplicates. We should change the tests.

**Comment by lydell** [comment]
Alright!

**Comment by lydell** [comment]
Fixed by #3784.

**Comment by connec** [comment]
Was the conclusion was that `(@one, one) ->` should be allowed?  On master currently that throws "multiple parameters named 'one'".
