### ISSUE TITLE
Error on late shadowing?

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/coffeescript#3339]
Currently, in CoffeeScript, shared variables through a closure proceed in order of the source:

```
# Shared:
one = 1
func = ->
  one = 2

# Not shared, shadowed:
func = ->
  one = 2
one = 1
```

The second case is nasty — both because of the inconsistency, and because you have shadowing, and no way to access the outer `one` variable from any place within the `func` scope.

Should we instead throw an early error: `"Late variable 'one' would be shadowed on line X"` ?

**Comment by GeoffreyBooth** [comment]
Closing as there doesn’t appear to be consensus that anything should be changed. Personally I would recommend as a best practice keeping your code split apart into as many separate files as possible, merged together via `require` or `import` statements with a tool like Browserify.
