### ISSUE TITLE
Conform Windows EOL characters to \n

### ISSUE THREAD

**Issue by ZombieHippie** [jashkenas/coffeescript#3341]
Windows's EOL character is `\r\n` while *nix EOL is just `\n`, so when a windows developer generates files from compilation, the files all use `\r\n` instead of the `\n` which causes git to believe many changes have occurred wherever there are those carriage return characters

**Comment by slang800** [comment]
:+1:

**Comment by GeoffreyBooth** [comment]
Modern versions of Git don’t have this issue, as far as I’m aware: https://help.github.com/articles/dealing-with-line-endings/

Regardless, I think it’s better solved through Git, not through the CoffeeScript compiler.
