### ISSUE TITLE
class A extends Array

### ISSUE THREAD

**Issue by gcao** [jashkenas/coffeescript#3344]
I wanted to create a subclass of Array. However the standard CS syntax won't work:

``` coffee
class A extends Array
```

It seems the only way to extend Array is like this

``` coffee
A = (args...) ->
  @push arg for arg in args

A.prototype = new Array
A.prototype.doSomething = ->
```

Should CS treat 'extends Array' as a special case and make 'class A extends Array' to work?

**Comment by sfinktah** [comment]
sweet, so which one of you is volunteering to make **coffeescript6**  🔨 

no takers? damn.

the flock of people leaving coffee to write in es6 is shameful, although the many things es6 stole from coffee has to be gratifying.  pity they had to mess around with things, i mean... 

    (...args)

seriously?
