### ISSUE TITLE
Expose functions to compile files and directories

### ISSUE THREAD

**Issue by manuelcabral** [jashkenas/coffeescript#3350]
The coffee-script module could export functions such as `compileFile()` and `compileDir()`, which would allow that to be used from node. These could then be used by `command`, instead of having all the code there. These functions could even have a `watch` flag to enable the watching functionality.

I have been trying to use node as a "task runner" ([tu](https://github.com/digisfera/tu)) and I ended up implementing a wrapper around the coffee-script module for this ([coffee-files](https://github.com/digisfera/coffee-files)). However, since the `coffee` binary already does everything that this wrapper does, I think it would make more sense if the coffee-script module exported functions to work with files.

**Comment by GeoffreyBooth** [comment]
A pull request that implements this would be welcome, however it is not a priority since this can easily be achieved with other tools such as Gulp or Webpack.
