### ISSUE TITLE
TypeError: bind on a method that's overriden as a value

### ISSUE THREAD

**Issue by hellochar** [jashkenas/coffeescript#3396]
``` coffeescript
class A
  constructor: (@a) ->
  property: () =>
    @a

class B extends A
  property: "test"

b = new B()
alert b.property
```

Expected output: should alert "test"
Actual output: Alerts the `__bind` method used by Coffeescript

What's worse, actually calling `b.property()` makes `__bind` throw `TypeError: object "test" has no method 'apply'` since the `fn` parameter isn't actually a function but is the value

**Comment by GeoffreyBooth** [comment]
This is no longer relevant in CS2.
