### ISSUE TITLE
Chain method calls omitting parentheses

### ISSUE THREAD

**Issue by Industrial** [jashkenas/coffeescript#3398]
Hi.

I often stumble over scenario's where I have some code that calls a method with more then one argument and need to chain a call after it;

``` coffee
myMethod 1, 2, 3
```

With the 1.7.0 syntax changes, this means I could write it as;

``` coffee
myMethod 1, 2, 3
  .otherMethod 'more', 'args'
  .maybeSomethingElse {}, [], 4, 5, 6
```

Why not also allow the syntax to live on one line?

``` coffee
myMethod 1, 2, 3 .otherMethod 4, 5, 6 .otherMethod 7, 8, 9
```

With the current syntax, it means I should add a lot of parentheses or restructure the code vertically, which is not that nice if the arguments and method names are small and there's several invocations and I'd argue that this:

``` coffee
myMethod 1, 2, 3 .otherMethod 4, 5, 6
myMethod 1, 2, 3 .otherMethod 4, 5, 6
myMethod 1, 2, 3 .otherMethod 4, 5, 6
```

looks way better then this:

``` coffee
myMethod 1, 2, 3
  .otherMethod 4, 5, 6
myMethod 1, 2, 3
  .otherMethod 4, 5, 6
myMethod 1, 2, 3
  .otherMethod 4, 5, 6
```

and I'd argue that the space before the dot makes the meaning unambiguous (not belonging to the last argument of the previous method but the return of that call).

gr,

Tom

**Comment by eskhool** [comment]
+1 whitespace is very significant in coffee and the inline option should be available to those who like it. not making it work seems to overstretch the I-don't-like-it-argument

**Comment by GeoffreyBooth** [comment]
If someone wants to submit a PR for this, it would be considered. However there are many open issues with chaining/leading periods, so those would need to be fixed first.
