### ISSUE TITLE
getting rlwrap to work with coffeescript's repl

### ISSUE THREAD

**Issue by novodinia** [jashkenas/coffeescript#3399]
How would you utilize rlwrap with coffeescript's builtin repl?

I can do it with the node repl like this:
    NODE_NO_READLINE=1 rlwrap coffee

**Comment by GeoffreyBooth** [comment]
This isn’t really a bug, as we’re not advertising this feature. If you want to submit a PR that enables support for this but doesn’t harm any current functionality, I would consider it.
