### ISSUE TITLE
error.stack should not have ANSI escape sequences (color)

### ISSUE THREAD

**Issue by joliss** [jashkenas/coffeescript#3407]
It's great that CoffeeScript prints colorized error output. However, I wish `error.stack` didn't contain ANSI escape sequences.

In this build tool I'm writing (similar to the Rails asset pipeline), I'm showing `error.stack` on the error page. The CoffeeScript Node package is called programmatically, so we catch any exceptions it throws. Because the development server typically is run in the terminal, CoffeeScript [detects](https://github.com/jashkenas/coffee-script/blob/8b15d8218d801a8b312fe5abf87dec35353aab70/src/helpers.coffee#L179) that stdout is a tty and colorizes. This leads to broken output in the browser:

![build_error-5](https://f.cloud.github.com/assets/524783/2398751/ac35f7c6-a9f8-11e3-9e60-2702f75d7efe.png)

Perhaps there is a way to make CoffeeScript print pretty errors when it's used from the command line but still keeping the `stack` property on the `error` object uncolorized?

**Comment by GeoffreyBooth** [comment]
It’s pretty trivial to find-and-replace CoffeeScript’s output to remove ANSI color codes.
