### ISSUE TITLE
spawning a coffee child process doesn't work as expected

### ISSUE THREAD

**Issue by paulpflug** [jashkenas/coffeescript#3427]
I have two files

test.coffee

``` coffee
spawn = require('child_process').spawn
child = spawn("coffee",["subtest.coffee"])
child.stdout.on 'data', (data) -> 
  console.log('stdout: ' + data)
console.log(child.pid)
```

and 
subtest.coffee

``` coffee
console.log(process.pid)
```

Output when running `coffee test.coffee`

```
6596
stdout: 6436
```

The pids should match..
So coffee makes its own child process?
The problem is, that the child process cannot be killed..
See [here](https://github.com/ericclemmons/grunt-express-server/pull/50)
and [here](https://github.com/remy/nodemon/issues/195)

**Comment by GeoffreyBooth** [comment]
The `coffee` command is intended primarily for compiling and secondarily for debugging, not as a replacement for the `node` command that is intended to run code.
