### ISSUE TITLE
CLI: Issue with coffeescript --map and --out

### ISSUE THREAD

**Issue by gilbertg** [jashkenas/coffeescript#3429]
Hi, i'm using coffee-script v1.7.1 and compiling (on Windows) like this:
`coffee --compile --map --output "..\" ".\"`
so, i want to send the js _and_ map files to another folder.

The result is my map files `sourceRoot` still references the source folder, and my debugger (Intellij IDEA) does not stop at the breakpoints.

The only way i can get this right is by compiling all to the source folder, then moving it out (which is a bit of a pain), so i get a [correct] map header like this:

```
{
  "version": 3,
  "file": "utils.js",
  "sourceRoot": "",
  "sources": [
    "utils.coffee"
  ],
  "names": [],
```

**Comment by GeoffreyBooth** [comment]
See also #3440.

**Comment by GeoffreyBooth** [comment]
Is this still an issue?

**Comment by GeoffreyBooth** [comment]
This happens now:

```bash
▶ coffee --compile --map --output /tmp/test test.coffee
▶ ls /tmp/test
test.js       test.js.map
```
