### ISSUE TITLE
Add hint to documentation for windows user

### ISSUE THREAD

**Issue by paulpflug** [jashkenas/coffeescript#3431]
Using nodejs spawn in windows does not work with `"coffee"`, but only with `"coffee.cmd"`

``` coffee
spawn = require('child_process').spawn
spawn "coffee", ["file.coffee"] # does not work on windows
spawn "coffee.cmd", ["file.coffee"] # does work on windows
```

I'm not sure where to put this hint

( see also #3371 and [here](https://github.com/metaskills/mocha-phantomjs/issues/61) )

**Comment by GeoffreyBooth** [comment]
The `coffee` command is intended primarily for compiling and secondarily for debugging, not as a replacement for the `node` command that is intended to run code.
