### ISSUE TITLE
Add isArray to coffeescript operators

### ISSUE THREAD

**Issue by NickRSearcy** [jashkenas/coffeescript#3483]
I find myself re-writing the same `typeIsArray` code all the time to test if an object is an array. Coffeescript has already added the `in` array-specific operator. I think `isArray` would also be helpful and within the scope of coffeescript. I'd like to see what others think before submitting a pull request.

I'm thinking something along the lines of the recipes in the [coffeescript cookbook](http://coffeescriptcookbook.com/chapters/arrays/check-type-is-array).

**Comment by GeoffreyBooth** [comment]
CoffeeScript 2 assumes ES2015+, so `Array.isArray` is assumed to be present and available. We don’t plan on adding any further shims.
