### ISSUE TITLE
Script.createContext is undefined in node 0.11.9

### ISSUE THREAD

**Issue by chrisyip** [jashkenas/coffeescript#3498]
I noticed that node had move `Script.createContext` to `vm.createContext` (http://nodejs.org/api/vm.html#vm_vm_createcontext_initsandbox).

I wonder if it's acceptable to use something like

``` js
var createContext = Script.createContext || vm.createContext;
```

to make it compatible with older and newer versions of node.

**Comment by balupton** [comment]
Because of this bug `require('coffee-script').eval` is broken in Node 0.12. This is not good.

**Comment by jashkenas** [comment]
@mbrio Is there a new pull we can take a look at?

**Comment by mbrio** [comment]
@jashkenas I'll look into it right now, we've been using this fix for months now and haven't had any issues with it.

**Comment by mbrio** [comment]
@jashkenas I just submitted a PR, the browser file didn't match the output of the compiled 1.9.0 source code. When I compiled it and overwrote the browser file supplied by coffee-script-source ruby gem, the error no longer occurred.

**Comment by GeoffreyBooth** [comment]
CoffeeScript 2 supports only Node 7+. If this issue only occurs in old versions of Node, I think we can stop worrying about it. Please comment if I’m wrong and I’ll reopen.
