### ISSUE TITLE
Generic Enumerable Comprehensions

### ISSUE THREAD

**Issue by JHawkley** [jashkenas/coffeescript#3499]
Lately, I've found myself using linked lists in CoffeeScript a lot and have been craving some of the same syntactical sugar other enumerable types enjoy.  JavaScript's `for` loop was designed for more than just incrementing an index for array traversal.  You could traverse many types of data structures with it.

As it stands, linked-list traversal in CoffeeScript requires a lot of boiler plate, as in this slightly contrived example:

```
node = list.head
results = while node?
  if check(node.value) is false
    node = node.next
    continue
  result = process node.value
  node = node.next
  result
```

JavaScript's `for` makes this much cleaner:

```
var results = [];
for (node = list.head; node != null; node = node.next) {
  if (check(node.value) === false) continue;
  results.push(process(node.value));
}
```

I'd like to discuss a syntax for iterating on any data structure whose iteration ends with `null` or `undefined` (to avoid just reimplementing classic `for` in CoffeeScript).  Perhaps something like:

`for (variable) with (initial_exp) then (next_exp) [when (condition)]`

The above examples could be re-stated concisely as:

```
results = (process node.value for node with list.head then node.next when check node.value)
```

More relevant, it'd make working with DOM objects a little easier in certain circumstances.

```
for element with document.getElementById('item1') then element.parentNode
  element.classList.remove 'error'
```

Finally, more complicated data structures could provide an enumerator object that operates well with this control structure, allowing any class to take advantage of comprehensions while abstracting its inner workings.

So, does anything here have any merit?

**Comment by GeoffreyBooth** [comment]
There doesn’t appear to be much interest in this proposal, so closing. I’m not sure how much we can improve over the native `forEach` or `map` methods that iterable objects now have.
