### ISSUE TITLE
Make the volatile and the persisted REPL history consistent

### ISSUE THREAD

**Issue by datenreisender** [jashkenas/coffeescript#3504]
When I enter `.history` in the REPL, the `.history`is also shown within the `.history`, just like other commands, such as `.load`. 

But the line `.history`isn't persisted to `.coffee_history` (caused by `code isnt '.history'` in repl.coffee). 

Because of this, the volatile history within a session and the persisted & restored history are slightly different. IMHO the best fix would be to also insert the `.history` command to the volatile history, just like other commands like `.load`.

**Comment by GeoffreyBooth** [comment]
Closing as there doesn’t appear to be consensus on making a change here.
