### ISSUE TITLE
[source maps] Should not use Windows path separator in sourceRoot and sources

### ISSUE THREAD

**Issue by jcwilson** [jashkenas/coffeescript#3518]
I'm developing on a Windows machine and since those paths are generated with path.sep, it uses "\\" instead of the expected "/". This is a problem since those strings should be urls.

As it is, it's impossible to serve my dev app through a local node http-server and have Chrome successfully locate the map files.

I have fixed it locally by hacking the built javascript, and have taken a swing at a modification to the src coffee script here: jcwilson/coffeescript@6778954

Sorry, there are no tests, but I thought this might help get the ball rolling on this one.

**Comment by GeoffreyBooth** [comment]
Generally the sourcemaps nowadays are embedded. If the above is still an issue for certain workflows, a pull request would be welcome.
