### ISSUE TITLE
Cleaner syntax for accessing "illegal" object members: object.'some-value'

### ISSUE THREAD

**Issue by kbaltrinic** [jashkenas/coffeescript#3520]
This comes up a lot when working with compiled templates in SPAs and I imagine in other places as well. We end up with template objects that have a lot of members who's names are not legal JavaScript identifiers because they are based on the original file names of the templates.  Needing to wrap brackets and quotes around the member names seems like more syntax that is needed.

Would it be possible to make:

```
templates.'my-template-name'
#and
templates."another-template-name"
```

valid syntax equivalent to:

```
templates.['my-template-name']
#and
templates.["another-template-name"]
```

**Comment by GeoffreyBooth** [comment]
Closing in favor of #3828.
