### ISSUE TITLE
REPL keeps running after runtime error on node 0.11.13

### ISSUE THREAD

**Issue by mbrio** [jashkenas/coffeescript#3528]
There seems to be an issue with REPL, running tests on node 0.11.13 I found that REPL fails on the test labelled _keeps running after runtime error_. I did some investigation and found that the `eval` method in /src/repl.coffee is properly calling `cb err` on line 38; so it seems as though passing an error to node's `eval` `callback` does not cause REPL to end as it did in the past.

Unfortunately since node 0.11.13 is an unstable release, I do not know as of yet whether this is a change in REPL's behavior or a bug in node.

**Comment by GeoffreyBooth** [comment]
Please comment if this is still an issue on the `2` branch with Node > 7.9.0.
