### ISSUE TITLE
Interpolations at beginning of strings compile to an empty string concatenation

### ISSUE THREAD

**Issue by benjaminbrent** [jashkenas/coffeescript#3529]
Any string interpolation occurring at the start of the string results in an empty string concatenation in the compiled JavaScript output.

For example:

```
"#{x}world"
```

compiles to:

```
"" + x + "world";
```

Note the empty string concatenation at the start of the output. It would be best if the compiled output was simply:

```
x + "world";
```

**Comment by lydell** [comment]
@benjaminbrent I’m currently working on stuff related to strings, so I might end up doing something about this. Just one question: What should `"#{x}"` compile to? `"" + x`? `String(x)`?

**Comment by lydell** [comment]
> the output "" + x + "world"; is a result of the recursive processing of string interpolations

I just found that that’s not true: [lexer.coffee#L579-L580](https://github.com/jashkenas/coffeescript/blob/8e4fb1b9378a08cbeafd3659995de178d4c81588/src/lexer.coffee#L579-L580):

```coffee
# If the first token is not a string, add a fake empty string to the beginning.
tokens.unshift @makeToken('NEOSTRING', '', offsetInChunk) unless tokens[0][0] is 'NEOSTRING'
```

**Comment by michaelficarra** [comment]
> What should `"#{x}"` compile to?

`"" + x`

**Comment by benjaminbrent** [comment]
Yes, `"#{x}"` should compile to `"" + x`.
