### ISSUE TITLE
Postfix conditionals in object literals

### ISSUE THREAD

**Issue by couchand** [jashkenas/coffeescript#3534]
There seems to be some inconsistency in the handling of postfix conditionals within nested object literals.  For instance, this compiles as one would expect:

``` coffeescript
# this compiles correctly
one =
  foo:
    baz: 1337
    bar: 42 if qux
```

However, this (apparently equivalent code) fails to compile at all (`error: unexpected newline`):

``` coffeescript
# this does not compile
two =
  foo:
    bar: 42 if qux
    baz: 1337
```

Additionally, adding a function call into the mix makes things even more confused.  While this example compiles as expected:

``` coffeescript
# this compiles correctly
three =
  foo: call
    baz: 1337
    bar: 42 if qux
```

This one splits up what should be a single object literal:

``` coffeescript
# this compiles incorrectly
four =
  foo: call
    bar: 42 if qux
    baz: 1337
```

Compiling to:

``` javascript
  four = {
    foo: call(qux ? {
      bar: 42
    } : void 0, {
      baz: 1337
    })
  };
```

And this similar example:

``` coffeescript
five =
  foo: call
    bar: 1337
  baz: 42 if qux
```

Compiles to:

``` javascript
  five = qux ? {
    foo: call({
      bar: 1337
    }),
    baz: 42
  } : void 0;

```

And since reversing the order of `foo` and `baz` results in `error: unexpected newline`, there doesn't seem to be a right way to express this with postfix conditionals.

I can start looking into the lexing and parsing to sort this out if it's agreed that it's a bug and nobody has an immediate idea for a fix.

_n.b._ I believe this is the same issue as #3507, but since the title there wasn't great I decided to open a new one.  Feel free to close or file as appropriate.

**Comment by GeoffreyBooth** [comment]
Reading this thread, I’m not sure what the bug is, or what the expected output would be. Perhaps someone could open a new issue with a narrower focus.

**Comment by couchand** [comment]
@GeoffreyBooth, I think my original report was pretty complete, can you expand on what about that description is unclear?
