### ISSUE TITLE
Lexer: Chaining: Compilation fails if object method called on first object key

### ISSUE THREAD

**Issue by ilikebits** [jashkenas/coffeescript#3546]
``` coffeescript
class some_class
  @method_name: some_object
    .callable_property some_input
  @another_method_name: some_other_variable
```

fails to compile with `error: Invalid object key` , but

``` coffeescript
class some_class
  @method_name: some_other_variable
  @another_method_name: some_object
    .callable_property some_input
```

compiles as expected on CoffeeScript v1.7.1, Node v0.10.29.

**Comment by GeoffreyBooth** [comment]
Minimal examples:

```coffee
class A
  @b: c
  .d e

obj =
  @b: c
  .d e
```

**Comment by GeoffreyBooth** [comment]
I just noticed that `@method_name: some_object` is missing a `->`. You also can’t chain from a one-line function (when you put a return value after `->`). The original example should be:

```coffee
class some_class
  @method_name: ->
    some_object
    .callable_property some_input
  @another_method_name: -> some_other_variable
```

Which works. The original code deserves to throw errors, it’s just incorrect syntax. It _almost_ works, in the sense that this compiles:

```coffee
key: val
# ({
#   key: val
# });
```

But it’s not what you’re intending.
