### ISSUE TITLE
Optimize destructuring assignment

### ISSUE THREAD

**Issue by lovasoa** [jashkenas/coffeescript#3565]
It would be great if simple destructuring assignment didn't need to systematically create an array.

That is, I'd like to see

``` coffeescript
[a,b] = [1,2]
```

compiled to 

``` javascript
a=1, b=2;
```

.

And if variable swaps didn't need arrays either, that would be even greater.
Like

``` coffeescript
[a,b] = [b,a]
```

compiled to

``` javascript
_a = a;
a = b;
b = _a;
```

**Comment by GeoffreyBooth** [comment]
Fixed in CoffeeScript 2.
