### ISSUE TITLE
Support annotations for optimization compilers

### ISSUE THREAD

**Issue by colelawrence** [jashkenas/coffeescript#3581]
Specifically referring to the [google closure compiler](https://developers.google.com/closure/compiler/) in my case, many classes can receive improved minification/obfuscation when `/** @constructor */` is located above a constructor function. For example:

``` javascript
var Dum, talkDum;

Dum = (function() {
  /** @constructor */
  function Dum(message) {
    this.message = message;
  }

  Dum.prototype.talk = function() {
    return alert(this.message);
  };

  return Dum;

})();

talkDum = function(message) {
  return new Dum(message).talk();
};
/** @extern */
window.say = function(msg) {
  return talkDum(msg);
};
```

Can compile into:

``` javascript
var c, d;
c = function() {
  function b(b) {
    this.a = b;
  }
  b.prototype.b = function() {
    return alert(this.a);
  };
  return b;
}();
d = function(b) {
  return(new c(b)).b();
};
window.say = function(b) {
  return d(b);
};
```

On the other hand, when the `@constructor` annotation is not included in the javascript source, `this.message` won't be renamed to `this.a`.

**Comment by benmcginnis** [comment]
@jashkenas @bolinfeset 's fork is about 1500 commits behind now, is it still your recommended solution?
