### ISSUE TITLE
Proposal to add return identifier or default value in the function declaration.

### ISSUE THREAD

**Issue by xyrius** [jashkenas/coffeescript#3583]
I would love to see the default return value/identifier in the function statement or a undefined return
as we have in Javascript

I very often see myself adding an extra line to force a undefined or other return value.

This would also eliminate the need for ending a function with @ or this (taking up a whole line for a single @) to chain functions

Any return statement inside the function should override the default return value

for example:

``` coffeescript
    class Person
        constructor: ( @name ) ->

        setNickName: @ ( nickName ) -> @nickName= nickName

        setAge: @ ( age ) -> @age= age

        addRoomMate: true ( somePerson ) ->
            return false if @roomIsFull()
            @roomMates.push( somePerson )
            @doSomeMoreInitialization()

    john= new Person 'john'
    john.setNickName('jt').setAge(24)
    letsParty() if john.addRoomMate( harry )


instead of:

    class Person

        constructor: ( @name ) ->

        setNickName: ( nickName ) ->
            @nickName= nickName
            @

        setAge: ( age ) ->
            @age= age
            @

        addRoomMate: ( somePerson ) ->
            return false if @roomIsFull()
            @roomMates.push( somePerson )
            @doSomeMoreInitialization()
            true

```

**Comment by GeoffreyBooth** [comment]
`setNickName: @ ( nickName ) -> @nickName= nickName` already compiles, so you would need to come up with a new syntax. I’m not sure there is a syntax like what you’re asking for that wouldn’t be a breaking change.

Removing implicit returns has been discussed before, and isn’t currently on the roadmap. If you want a function to return `undefined` like in JavaScript, end your function with `return` by itself on a line.
