### ISSUE TITLE
Make a patch release once a month (at a fixed schedule)

### ISSUE THREAD

**Issue by lydell** [jashkenas/coffeescript#3590]
I would be really great if somebody was given the job of, say once a month, making a patch release to npm. I’m really tired of nice bug fixes sitting unreleased in the master branch forever, causing people to report the same bugs over and over again—and worse: Getting bitten by those bugs when they shouldn’t have to.

**Comment by lydell** [comment]
For anyone finding this issue and wants to make a release PR, I’ve written a [guide](https://github.com/jashkenas/coffeescript/wiki/%5BHowto%5D-Hacking-on-the-CoffeeScript-Compiler#11-preparing-a-new-release) on how to do it.

**Comment by rstacruz** [comment]
not sure if this is the best place to add this, but:

> sed -i 0,/1\.9\.9/s//2.0.0/g package.json bower.json src/coffee-script.coffee documentation/index.html.js

...[bump-cli](http://npmjs.com/bump-cli) might be a better way to do this.
