### ISSUE TITLE
Switch keyword should never need to be on its own line

### ISSUE THREAD

**Issue by jtbandes** [jashkenas/coffeescript#3593]
Usually, `switch` can be on the same line as earlier arguments to a function, as you'd expect:

``` coffeescript
# Works as expected
f.on "foo", switch    #   f.on("foo", (function() {
    when b then c     #     switch (false) {
.on "bar", baz        #       case !b:
                      #         return c;
                      #     }
                      #   })()).on("bar", baz);
```

But when passing the `switch` result inside a function, you get a syntax error:

``` coffeescript
# Syntax error? :(
f.on "foo", -> switch
    when b then c
.on "bar", baz        # "unexpected ."
```

and instead, it has to be on a separate line to get the desired output:

``` coffeescript
# Works as expected, but annoying
f.on "foo", ->           #  f.on("foo", function() {
    switch               #    switch (false) {
        when b then c    #      case !b:
.on "bar", baz           #        return c;
                         #    }
                         #  }).on("bar", baz);
```

**Comment by GeoffreyBooth** [comment]
Using a leading period to imply chaining is supported more or less by accident, and we don’t plan to make the compiler support such a construct any better. If anything it should be disallowed, but at this point we don’t want to break lots of old code.

In your specific case, just add parentheses:

```coffee
f.on("foo", -> switch
    when b then c
).on "bar", baz
```
