### ISSUE TITLE
`switch when x in arr`, `switch when x of obj`

### ISSUE THREAD

**Issue by jamisonwilde** [jashkenas/coffeescript#3594]
I know that this has been requested before in other formats (  #3488 #2561 ), but I think it would be useful to have  'when in [array]' and 'when of [object]' syntax available.

``` coffeescript
movie_extension = [ '.mkv', '.avi','.wmv']
switch file.extension
  when '.url'
    ;
  when in movie_extensions
    ;

```

This is what I had to do instead (more whens listed here obviously):

``` coffeescript
      switch 
        when file.extension == '.url'
          ;
        when file.extension == '.jpg'
          ;
        when file.extension == '.nfo'
          ;
        when config.subtitle_extensions.indexOf(file.extension) != -1
          ;
        when config.movie_extensions.indexOf(file.extension) != -1
          ;
        else
          console.log "Unknown filetype"

```

This is a nice compact, intuitive way to express this.
Having to do when file_extension == '.url' over and over in a switch with no initial expression is annoying. Not saying there aren't other ways to do it either, but this is nice and concise.

I think there is also an interesting usage around 'when of':

``` coffeescript
movie_extensions = 
  '.mkv': 'Matroska Video'
  '.wmv': 'Windows Media Video

extension_longname = switch file.extension
  when '.url'
    'Internet Shortcut'
  when of movie_extensions
     movie_extensions[file.extension]
```

Maybe this particular  grammar has been recommended before, if so, I apologize for the noise. My guess is that this would require a lookforward mechanism to detect if any of the when in/of were present and convert to the switch(false) form for everything if detected. 

Still, seems like a sexy grammar addition IMO :) The discussion in #2561 seemed to indicate an openness to the idea in general, and I am hoping that this particular expression of it may be interesting. Would love for someone to point me in the direction of what the issues would be in implementing something like this. I can obviously run the compiler in debug and see what happens but any pointers on where to look first would be helpful.

**Comment by tigerhawkvok** [comment]
I came here to add precisely this comment, @jamisonwilde .

What I like about it is that you can then do dynamic switches:

```coffee
list = ["foo","bar"]
if thatCondition then list.push("baz")
switch aThing
  when in list
    true
```

Currently, you have to do

```coffee
switch aThing
  when "foo", "bar"
    true
  else
    if thatCondition and aThing is "baz" then true
```

which is, IMO, much messier mentally.

**Comment by JHawkley** [comment]
LiveScript had the `that` keyword.  Well, actually, `that` was a variable with special meaning where the result of an expression used in conditionals is assigned to it whenever `that` was used in the body that followed.  Borrowing it for `switch` statements in CoffeeScript, it could work like this:
```
switch file.extension
  when '.url' then (...)
  when that + 'l' is '.html' then (...)
  when that in movie_extensions then (...)
```

The above would compile into something like:
```
that = file.extension;
switch (false) {
  case !(that === '.url'): (...)
  case !(that + 'l' === '.html'): (...)
  case !(movie_extensions.indexOf(that) !== -1): (...)
}
```

An imperfect solution since it may break someone's code if they used a variable by the same name.  Since `that` would only have meaning following a `when`, I imagine this would be so rare that it could possibly be disregarded and have an ambiguity error thrown by the compiler when this specific case came up.

**Comment by GeoffreyBooth** [comment]
A pull request for this would be welcome.
