### ISSUE TITLE
trailing implicit object in function call woes

### ISSUE THREAD

**Issue by loveencounterflow** [jashkenas/coffeescript#3595]
these samples compile OK (with CS 1.7.1):

``` coffee
for i in f x, ( y: 3 )
  continue if i < 10
```

``` coffee
for i in f x, { y: 3 }
  continue if i < 10
```

``` coffee
for i in f x, y: 3, a
  continue if i < 10
```

but this does not:

``` coffee
for i in f x, y: 3
  continue if i < 10
```

```
error: unexpected continue
  continue if i < 10
  ^^^^^^^^
```

the error message makes it _look like_ the `continue` statement is the culprit here, but in fact, like, _everything_ (i didn't explicitly test everything though) will cause an error:

``` coffee
for i in f x, y: 3
  g 42
```

```
error: unexpected (
  g 42
  ^
```

> (aside: there is no `(` in my code so there can't be an unexpected one, only a missing one.)

so the suspicion is that CS thinks there's gotta be a multi-line, brace-less object literal as the last argument in the function call. ok, check it out:

``` coffee
for i in f x, y: 3
  z: 24
```

causes

```
error: unexpected :
  z: 24
   ^
```

meh.

then again, i can write the following `if` clause as the only thing in a module—so there cannot be a continue statement, right?—and it _will_ compile:

``` coffee
if i in f x, ( y: 3 )
  continue if i < 10
```

but then i do get a `SyntaxError` _at runtime_:

```
      continue;
      ^^^^^^^^
SyntaxError: Illegal continue statement
```

of course, this error is, as such, unrelated to the issue at hand. it cropped up when i tried to mangle my source code to make it CS-digestible. turns out i have to actually run my code sometimes to catch all the syntax errors.

may i share the following observations:
- this feature / bug has been talked about **several times** here;
- scanning the CS homepage for `implicit object` reveals the authors have made **numerous tweaks** to how implicit objects work in the syntax;
- the combination of significant indentation, implicit object literals, and implicit function calls makes for a **difficult field**;
- Joe the the average programmer **should be shielded** from the thorny issues and gory details of parsing as well as from an over-sophisticated grammar that has too many special rules ('parking allowed except on business days, but not from 3 to 4 pm on Tuesdays, except for public holidays');
- however **the opposite happens** here:
  - the **error messages are misleading**; in the last error above, it _is_ the `continue` statement which is misplaced; in the other cases,
  - the message is **"too specific to be helpful"** in one case ("you can't have `continue` here"—right, but then you can't have anything else here, either), and
  - **"too obscure to be helpful"** in the other case (bringing up implementation details of the parser that is inserting missing elements and then complains about it having done so);
  - **some errors occur too late** (`SyntaxError`s at runtime? really?)
- people stating that CS has a horrible grammar do have a point here.

i can remember @michaelficarra remarking that "using an implicit object literal in a function signature is asking for trouble". that was said inside an issue discussion, not in a place that would be very visible to a n00b. i can state that in _years_ of using CoffeeScript this has very rarely bitten me, and i use a lot of implicit calls and implicit object literals.

**proposals**:
- definitely, the **error messages have to get better**. this may be difficult with the current parser.
  
  i've tried http://coffeelint.org, but that doesn't help a lot in this case. AFAICS it gets a little better in the current CoffeeScriptRedux. it still trips up when starting the function body with an implit object literal tho.
  
  from my tests, i conclude that the trailing implicit object literal in the function signature in conjunction with the ensuing indentation makes the parser think the object literal is about to continue, but when the source _does_ have a continuing literal, some other part throws. **this contradictory behavior should be fixed**.
- **nowhere in the documentation is it stated** that _signature-final implicit object literals can be troublesome_; then again, it is **not desirable to burden the grammar** with such a seemingly arbitrary rule.
- there should be **a principled approach** to resolving this issue. maybe like this:
  - both a function call and an implicit object literal can continue with an indented suite of lines. in cases where it could be either,
    
    `(_)` the function signature takes precedence
    
    `(_)` the object literal takes precedence
    
    `(_)` the construct is rejected.

having just written the above lines i realize some fuzzyness—both the function call signature and the function body may be indicated by indentation... but the function signature normally requires a trailing comma:

not ok:

``` coffee
f
  42
  108
  256
```

not ok:

``` coffee
f 42
  108
  256
```

ok (and, correctly, equivalent to `f(42, 108, 256)`):

``` coffee
f 42,
  108
  256
```

seen this way, the second line of

``` coffee
for i in f x, y: 3
  z: 24
```

should be understood as the function body and compile to

``` js
_ref = f(x, { y: 3 });
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  i = _ref[_i];
  ({ z: 24 });
}
```

as the missing trailing comma indicates the end of the call signature.

**Comment by GeoffreyBooth** [comment]
Your problematic example can be fixed by simply adding some parentheses:
```coffee
for i in f(x, y: 3)
  continue if i < 10
```

The error messages and documentation can always be improved, but that’s not a reason to keep this issue open. Pull requests to address the various critiques in the above post would be welcome.
