### ISSUE TITLE
CoffeeScript 2.0: “UNIX philosophy compilation strategy”?

### ISSUE THREAD

**Issue by lydell** [jashkenas/coffeescript#3596]
I suggest that CoffeeScript should always compile to the latest “stable-enough” standard JavaScript. If the user’s environment doesn’t support that JavaScript, it is up to the user to include needed polyfills—perhaps using [autopolyfiller](http://azproduction.ru/autopolyfiller/)—and/or pipe the JavaScript into another transpiler, such as [esnext](https://github.com/esnext/esnext).

Wanting to use future JavaScript features isn’t unique to CoffeeScript. Regular JavaScript wants that too.

Examples:
- Compile spread/rest/splat/whatever into ES6 `...foo` whenever possible. [es6-spread](https://github.com/esnext/es6-spread)
- Compile classes into ES6 classes. [es6-classes](https://github.com/esnext/es6-class)
- Compile `=>` functions into ES6 `=>` functions when possible. [es6-arrow-function](https://github.com/esnext/es6-class)
- Compile `a in b` into `b.indexOf(a) >= 0`. [polyfill](https://github.com/jonathantneal/polyfill/blob/master/source/Array.prototype.indexOf.js).
- Compile `yield` into `yield`. [regenerator](http://facebook.github.io/regenerator/)
- Compile destructuring into ES6 destructuring.
- Compile `a.throw` to `a.throw` (not `a["throw"]`) etc.
- Remove the “bare” option and always compile bare. Users should use a module system, or a separete “wrap-in-IIFE”-tool instead.

Pros:
- Allows the user to choose which environments they want to support, which has been asked for numerous times.
- Simplifies CoffeeScript compilation a lot.
- Easy to support the latest ES specs (no need to worry about old browsers).
- Follows the UNIX philosophy better. CoffeeScript becomes an alternate syntax with more features, such as chained comparisons (`0 < a < 5`), more splats (`(a, b..., c) ->`), expansion (`[..., last] = foo`), etc.

What do you think?

**Comment by adambiggs** [comment]
> In my opinion, CoffeeScript 2 should become ES6++. CoffeeScript 3 should be ES7++.

Amen :raised_hands:

**Comment by lydell** [comment]
Just for the fun of it, I wrote up a bit about my “dream compile-to-JS” language with UNIX philosophy in mind: https://github.com/lydell/frappe. If you also like fantasizing about syntax it might be worth a read ;)

**Comment by vendethiel** [comment]
I guess everyone has the... "Coffee of their dreams" ;-).

**Comment by backspaces** [comment]
In my conversion to es6, I've been using:
    JavaScript Standard Style
    https://github.com/feross/standard#javascript-standard-style
It too is semi-less.

After doing it for 3 months, it's been such a relief. Sorta like an AA
meeting: I've been of them for 3 months! I often challenge people to tell
me where semi's should be.  They can't. It's really easy to tell where they
can safely be omitted and the few corner cases. And yes, its way more
readable.

Coffee folks will really like es6:
- It's got a lot of coffee already
- Subtle new syntax features are great
- You'll gain back all the friends that have abandoned all your CS projects.
- Modules. Imagine HTML without 20 <script> tags
.. there's more but jump in, babel is the new coffee compiler.

   -- Owen

**Comment by bjmiller** [comment]
I strongly disagree.  
- Every "coffee-feature" ES6 does, CS still does better.
- Many of the "subtle" new syntax features aren't great, they're confusing.
- If people have religious problems with CS, I submit that you don't need them.
- Modules are actually orthogonal to syntax, and ES6 modules are still really unpleasant to use compared to Common JS.

If CS "needs" to do anything, it's that it needs to respond to the cases where ES6 allows you to do something, and CS doesn't because of its own syntax rules.  Which is to say that you should somehow be able to make CS output any valid JS, without needing the backtick-escape to hack around things.  But, things like that are all small adjustments at heart.
