### ISSUE TITLE
Lexer: Chaining: Inconsistency with indented function chaining vs. other indented constructs

### ISSUE THREAD

**Issue by connec** [jashkenas/coffeescript#3620]
This compiles:

``` coffee
->
  if a
    b
# or
-> if a
  b
```

``` js
(function() {
  if (a) {
    return b;
  }
});
```

And this compiles:

``` coffee
->
  a
    .b c
```

``` js
(function() {
  return a.b(c);
});
```

But this does not:

``` coffee
-> a
  .b c
# [stdin]:2:3: error: unexpected .
#   .b c
#   ^
```

I expected the last example to 'behave in the same way' as the `if` example (which behaves the same as other indented constructs I could think of).

For context, I was writing an escape function that looked like:

``` coffee
escape = (html) -> html
  .replace /</g, '&lt;'
  .replace />/g, '&gt;'
  ...
```

**Comment by GeoffreyBooth** [comment]
Not sure what the bug is here.

**Comment by connec** [comment]
I suppose it's a request for more subtle whitespace interpretations 😄  Probably best to let it lie.
