### ISSUE TITLE
Pattern Matching but also Entire Result

### ISSUE THREAD

**Issue by yfeldblum** [jashkenas/coffeescript#363]
It would be nice to be able to specify both a name for the whole value and also the names for the parts of the value in the LHS (or in a formal parameter). Here's sample syntax:

```
myobj: { p1: { a: 1, b: 2 }, p2 : { c: 3, d: 4 } }
myp1@{x, y}: myobj.p1
# myp1 == { a: 1, b: 2 }, x == 1, y == 2
```

The `@` is the character that Haskell uses for this feature. CoffeeScript should choose the syntax most appropriate for and integrated with the rest of CoffeeScript for this particular feature.

**Comment by lydell** [comment]
@mitar use `{ a: x, b: y } = myp1 = myobj.p1` :)
