### ISSUE TITLE
add "short form" array declaration syntax: .['cat' 'dog' 'mouse']

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#3636]
The "Falcon" Language has an alternate syntax for declaring arrays, a short form.

Falcon supports both ['cat', 'dog', 'mouse'] and .['cat' 'dog' 'mouse'] where each item separated by whitespace is treated like the thing to go in at that index without any syntactic ambiguity.

I'd love it if Coffeescript could support the same, or similar <3  The commas can be an eyesore sometimes, and I do like arranging arrays/lists with whitespace more.  It's visually cleaner to me.

The short form wouldn't be able to handle something like: .[some_func 1, 2 + 3 'cat']  <-- too ambiguous

I'm not sure I'd want to match Falcon identically -- but maybe / 'cat' 'dog' 'mouse' / would be fun?

Some ideas:

.[1 2 3]
:[1 2 3]
/1 2 3/
| 1 2 3 |
] 1 2 3 [

etc...

**Comment by ohcibi** [comment]
+1 for reopening this issue. `%w[this is an array of strings]` is - as pointed out - a special form to create an array of STRINGS and not arbitrary elements.

The point is, that those `,` are unnecessary and should just be optional. And yes, the fact that arrays can be arranged with new lines is not a fix for this problem. In fact it makes it worse.
Say you have a list like the one from @jashkenas. I might decide that this list will never grow and I can put it into one line. Most editors make this very easy, I'd press `3J` in vim e.g. but the code would now be broken as a single line array needs `,`, so I'm better off to leave those `,` in anyways, as long as they are not fully optional.
