### ISSUE TITLE
rename ctor to Ctor

### ISSUE THREAD

**Issue by socketpair** [jashkenas/coffeescript#3641]
when coffeescript define `__extends` it use `new ctor` in that code. If you change to `new Ctor`, this will not break jshint about naming of classes. And also in code `function Ctor() { this.constructor = child; }` it understand that `Ctor` is a contructor, so `this.constructor = child;` does not break strict mode.

**Comment by GeoffreyBooth** [comment]
CoffeeScript 2 has removed `__extends`.
