### ISSUE TITLE
"error: unexpected newline" on indented method calls

### ISSUE THREAD

**Issue by errendir** [jashkenas/coffeescript#3652]
Hello

The following code doesn't compile (tested with the CoffeeScript 1.8.0):

```
a = 
  b
    .c (d) ->
      d
        .f ->
          l()
        .k()
      e
      d
```

the reported error is:

```
error: unexpected newline
      e
      ^
```

while the following:

```
a = 
  b
    .c (d) ->
      d
      .f ->
        l()
      .k()
      e
      d
```

or 

```
a = 
  b
  .c (d) ->
    d
      .f ->
        l()
      .k()
    e
    d
```

compiles perfectly well (and to the same exact code as one can expect).

What's even worse is that the following:

```
a = b
  .c (d) ->
    d
      .f ->
        l()
      .k()
    e
    d
```

compiles to

```
var a;

a = b.c(function(d) {
  return d.f(function() {
    return l();
  }).k();
});

e;

d;
```

This is not what the indentation suggests the snippet should compile to. Is this an error?

Just like in the previous example unindenting one of the method call blocks fixes the problem.

Could you please look into this issue?

**Comment by GeoffreyBooth** [comment]
The original example seems to compile fine in 2.0.0-beta1:

```js
var a;

a = b.c(function(d) {
  d.f(function() {
    return l();
  }).k();
  e;
  return d;
});
```

But remember that CoffeeScript is a whitespace-significant language. Putting a newline before a leading period is basically relying on a lax compiler—in other words, it’s a hack, and probably _shouldn’t_ work. Use `\` if you want to continue on a new line.
