### ISSUE TITLE
proposal: "for value on object" & "value on object"

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#3657]
I'd like to propose another meaning for `on` when not used as an alias for `true`:

``` coffeescript
console.log value for value on obj
```

As opposed to:

``` coffeescript
console.log value for value in obj
```

`on` would iterate over the keys an object "has" in no defined order.  As in: `Object.getOwnPropertyNames()`:

It would become something like this:

``` javascript
(function() {
  var value, _i, _len;
  var _ks = Object.getOwnPropertyNames(obj);

  for (_i = 0, _len = _ks.length; _i < _len; _i++) {
    value = obj[_ks[_i]];
    console.log(value);
  }
}).call(this);
```

`on` would also be supported in a conditional context, like so:

``` coffeescript
has_value = value on obj
```

Which would translate to a function that fetches the keys `obj` **has** and then loops to detect if the value is present.

I believe `on` should be supported in these 2 contexts (in a for loop and within a conditional) because this exact use is not covered in Coffeescript.  `of` works like the traditional Javascript `in`, iterating over enumerable properties or testing their existence.  `in` works on array-like objects **only**.  With the addition of `on` we can iterate over all [immediate] values in an object, or test for the existence of a value -- regardless of whether the object is array-like (if it hosts a .length or has numeric keys).

An alternative would be using `for value at some_object`, but I feel like `on` is clearer about intention.

"If we have this value on..."  "Iterate over all the values on...."

**Comment by GeoffreyBooth** [comment]
I think this has been addressed with `for…from`. Please comment or open a new issue if not.
