### ISSUE TITLE
Incorrect error message when reserved word 'with' appears in unclosed multiline comment

### ISSUE THREAD

**Issue by kentwilliam** [jashkenas/coffeescript#3660]
This

``` coffeescript
console.log("doesn't work")
###
with
```

gives

```
test.coffee:3:1: error: reserved word "with"
with
^
```

Whereas the actual error is that the file needs a second set of `###`. Is this easily fixable?

**Comment by GeoffreyBooth** [comment]
It’s not really anything to do with `with`. It’s just that there are two errors in your code, and the compiler happens to come across the `with` one first and throw that error first. Change it to:

```coffee
console.log("doesn't work")
###
console.log('foo')
```

and you get

```sh
error: unexpected #
###
^
```
