### ISSUE TITLE
yield keyword does not work in for loop expression

### ISSUE THREAD

**Issue by GabrielRatener** [jashkenas/coffeescript#3665]
When one tries to do the following

```
array = [1, 2, 3]
outvar = for i in array
  yield i * 2
  i * 2
```

Inside a gennerator function, the loop gets wrapped in another generator closure and an iterator is returned to `outvar` instead of an array, I presume this is a bug.

**Comment by pepkin88** [comment]
@jashkenas @alubbe Unfortunately there are cases, where this issue is still not fixed. Namely, when in switch or for expression `yield` and `@` (or `this`) is used.

This code:
```CoffeeScript
->
  foo = switch
    when true then yield @
  bar = (yield @ for item in arr)
```
compiles to this:
```JavaScript
(function*() {
  var bar, foo, item;
  foo = (function*() {
    switch (false) {
      case !true:
        return (yield this);
    }
  }).call(this);
  return bar = (function*() {
    var i, len, results;
    results = [];
    for (i = 0, len = arr.length; i < len; i++) {
      item = arr[i];
      results.push((yield this));
    }
    return results;
  }).call(this);
});
```
instead of:
```JavaScript
(function*() {
  var bar, foo, item;
  foo = (yield* (function*() {
    switch (false) {
      case !true:
        return (yield this);
    }
  }).call(this));
  return bar = (yield* (function*() {
    var i, len, results;
    results = [];
    for (i = 0, len = arr.length; i < len; i++) {
      item = arr[i];
      results.push((yield this));
    }
    return results;
  }).call(this));
});
```

Notice the `yield*` in 3rd and 9th lines.

**Comment by alubbe** [comment]
Hey @pepkin88 
Thanks for the clear and structured error report.

I have found and fixed the issue locally, and will write some more tests over the weekend to check for further issues with ```this```.

Could you create a separate issue for this bug please?

**Comment by pepkin88** [comment]
Ok, I will.
