### ISSUE TITLE
Chained multiline function calls in object declaration

### ISSUE THREAD

**Issue by FibHeap** [jashkenas/coffeescript#3667]
Depending on the first key in an object declaration multiline-function-chaining works differently. Why? 

So for example:

``` coffee
wrong = c.func
  b: c.func2()
    .func3()
  d: c.func2()
    .func3()
```

compiles to

``` js
wrong = c.func({
    b: c.func2()
  }.func3(), {
    d: c.func2()
  }.func3());
```

however if I change the first line to be a non multiline chain all other keys (even the same multilines) seem to also work

``` coffee
correct = c.func
  b: c.func2().func3()
  d: c.func2()
    .func3()
```

compiles to

``` js
correct = c.func({
    b: c.func2().func3(),
    d: c.func2().func3()
  });
```

This changed seemed to have changed in coffeescript at some point.  (for example Webstorm builtin compiler always creates the 'correct' version)

**Comment by albertywu** [comment]
I ran into this issue today as well :(

A slightly simpler example that illustrates the problem:
```coffeescript
# coffee v1.9.1

# BROKEN: coffeescript does not compile this.
broken =
  chained: doThis()
    .thenThis()
  foo: 'bar'

# WORKS: coffeescript does compile this.
works =
  chained:
    doThis()
      .thenThis()
  foo: 'bar'
```

**Comment by lbeschastny** [comment]
@xixixao closing all function calls on leading `.` is an awesome idea. It greatly simplified chaining syntax in many cases.

But I believe that you shouldn't close object literals as well, because it may confuse CS users.

I think, you should allow people to write chains like the following one:

```coffee
data =
  chained: foo 'bar'
    .then 'baz'
  foo: 'bar'
```

**Comment by GeoffreyBooth** [comment]
As CoffeeScript is a whitespace-significant language, using things like leading periods is essentially relying on hacks or gaps in the compiler. If you want to chain onto a new line, use `\`.

The “solution” for such issues would be to clamp down more against this abuse of the compiler’s laxness, but that would break a lot of existing code.

**Comment by xixixao** [comment]
This is certainly a bug and there is no reason for closing "enclosing" objects. At least there is a workaround, so it's probably lower pri than some of the other chaining issues.
