### ISSUE TITLE
Source Maps: Reference errors in 'name only expressions' are broken

### ISSUE THREAD

**Issue by carlsmith** [jashkenas/coffeescript#3672]
Basically this...
![screen shot 2015-03-09 at 02 00 50](https://cloud.githubusercontent.com/assets/7561668/6548941/b495ad56-c600-11e4-93bc-e23f8e14c28a.png)
The JavaScript errors are always correct, but only the third example has the correct position for CoffeeScript.

**Comment by carlsmith** [comment]
I updated this with a screenshot. It's just easier to show the problem than explain it.

**Comment by carlsmith** [comment]
I'm going to investigate this today. The problem may be in CoffeeShop, so I'll dive into it, and hopefully get it sorted. I'll open a new, more concrete issue if it is a CoffeeScript problem.

**Comment by polkovnikov-ph** [comment]
Was it fixed? The status of this issue is unclear.

**Comment by carlsmith** [comment]
Yep. Sorry. It was fixed. I'm on my phone, so can't find the issue just now, but it was fixed by a PR dealing with this problem when the compiler has `bare` set to `true`.

**Comment by carlsmith** [comment]
The IIFE would always hide this bug.
