### ISSUE TITLE
Existential operator and harmony proxy has: function compatibility.

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [jashkenas/coffeescript#3685]
I doubt if that an issue or not, but proxies can construct objects that could return "inexistent" properties and it probably would be good to add `"property" in object` check to the coffeescript existential operator.

``` coffeescript
require 'harmony-reflect'

class PushHelper
  constructor: (@target,@targetKey) ->
  push: (item) ->
    console.log "Pushing #{@targetKey}"
    @target[@targetKey] = [item]

DataProxy = 
  has: (target,key) ->
    return target[key]?
  get: (target,key) ->
    unless target[key]?
      return new PushHelper(target,key)
    else
      return target[key]
  set: (target,key,val) ->
    target[key] = [val]

proxy = new Proxy({},DataProxy)

proxy["2014-10-14"] = "Message 1"
proxy["2014-10-14"].push "Message 2"

console.log proxy["2014-10-15"]?
`console.log("2014-10-15" in proxy)`

proxy["2014-10-15"].push "Message 3"
proxy["2014-10-15"].push "Message 4"

console.log proxy["2014-10-15"]?
`console.log("2014-10-15" in proxy)`

for key,val of proxy
  console.log(key,val)
```

This example proxy returns a `PushHelper` object instead of `undefined` to allow to apply push method to undefined properties as well as to a defined ones. But coffeescript existential operator tells us that undefined property exists while at the same time javascript `in` operator tells that there is no such property because proxy `has` method returns `false` on it. Output:

```
$ coffee test63.coffee
Running node v0.11.13
true
false
Pushing 2014-10-15
true
true
2014-10-14 [ 'Message 1', 'Message 2' ]
2014-10-15 [ 'Message 3', 'Message 4' ]
```

**Comment by GeoffreyBooth** [comment]
At this point I don’t see us changing the implementation of the existential operator, as that has the potential of breaking a lot of existing code.
