### ISSUE TITLE
Use Fast.js Array Techniques

### ISSUE THREAD

**Issue by backspaces** [jashkenas/coffeescript#3693]
Looking at the generated JS from CS, I'm surprised how often push is used rather than allocating the array initially to be the correct size, then assigning by index.

Fast.js uses this and other techniques to achieve better-than-native speed (..as CS already does in many places)

Please consider a performance review, especially with array and object comprehensions using pre-allocated arrays and other Fast.js techniques.

**Comment by GeoffreyBooth** [comment]
Pull requests that implement performance improvements are always welcome.
