### ISSUE TITLE
"if" and "by" are not always special

### ISSUE THREAD

**Issue by smurfix** [jashkenas/coffeescript#3694]
"by" or "if" must not always be treated reserved tokens. (Among others, probably.)

Protractor tests use a "by" global; see the AngularJS tutorial app:

```
phoneList = element.all(by.repeater("phone in phones"))
```

. "gulp.if" is a perfectly valid object accessor.

```
npm install gulp-if
gulp = require("gulp-load-plugins")()
…
    gulp.src(…)
    .pipe(gulp.if(…))
```

I can of course work around the problems using gulp['if'] and global['by'], but solving this in coffeescript would be preferable.

**Comment by GeoffreyBooth** [comment]
Not sure we can do anything about this.
