### ISSUE TITLE
Document official policy on future ES features

### ISSUE THREAD

**Issue by DavidSouther** [jashkenas/coffeescript#3698]
I've seen snippets of a conversation in various threads (#3596, #1363, 3240). 2011 was very ES3, 2012 had a lot of ES5, 2013 started adding ES6. End of 2014, Google and Microsoft both seem to be pushing forward with TypeScript, and people in Google are pushing for an even further extension with AtScript. IE8 support is only another year and a half. It seems safe to say that the JS we have today is not the JS enterprise and browser vendors want.

Is there an official policy documented on when ES features will be willing to add to CS? (Beyond the threads I've pointed out - which come down to "@jashkenas says no, until enough devs complain, then he grudgingly says yes" ;) )

**Comment by umhan35** [comment]
> That's because this is the jashkenas/coffeescript fork. There's also the satyr/coco fork, the gkz/LiveScript fork, and the michaelficarra/CoffeeScriptRedux fork, just to name a few.

This doesn't make sense at all.

> There are no "official policies" in CoffeeScript ;) This is an open source project, not a government.

This doesn't make sense at all too. Most issues are closed by one person. This is a despotic land.

The JS getter and setter have been here so long. People writing JS or CS not only work with browsers but also Node.js.

**Comment by J4G-** [comment]
+1 for getter and setter support

**Comment by zimt28** [comment]
I'd also like support for getters/setters and named functions.
Generally speaking I don't see the point of not adding new features - if they were just included in CoffeeScript people could decide on their own if they wanted to to use those or not, just like they can with plain JavaScript.
