### ISSUE TITLE
Follow the XDG directory spec for .coffee_history

### ISSUE THREAD

**Issue by jasonkarns** [jashkenas/coffeescript#3705]
The coffee history file should be stored/read from the `$XDG_CACHE_HOME` directory (which defaults to `$HOME/.cache`

Suggested file: `$XDG_CACHE_HOME/coffee/history`

reference spec: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by jasonkarns** [comment]
While this implementation is an improvement, it is still not spec compliant.

The spec defines `$HOME/.cache` as the default value for `$XDG_CACHE_HOME`. It is not correct to require `$XDG_CACHE_HOME` to be set.

(Further improvement would be to write the history file to a `coffee/` _directory_ within the cache dir, rather than a top-level file, as this would be flexible to support future cached coffee files other than history. But the more important thing is to still default to the correct cache dir.)

**Comment by GeoffreyBooth** [comment]
Do you care to submit a new PR that corrects this?

**Comment by jasonkarns** [comment]
can-do
