### ISSUE TITLE
unreadable generated JS for comma-separated statements

### ISSUE THREAD

**Issue by makoConstruct** [jashkenas/coffeescript#3729]
Currently, when you assign the result of a conditional to something, the code in each block of the conditional will be generated as comma separated statements rather than semicolon separated statements. The problem is that these statements are not each given their own line. To illustrate:

```
a = if true
  do_things()
  do_more_things()
  generate_result()
else
  0
```

resolves to

```
a = true ? (do_things(), do_more_things(), generate_result()) : 0;
```

If the conditionals have a lot of content in the branches, this can make for some very unreadable generated code. It would be easier to debug our code if, instead, we got

```
a = true ? (
  do_things(),
  do_more_things(),
  generate_result()
) : (
  0
);
```

**Comment by GeoffreyBooth** [comment]
A PR that implements this would be welcome.
