### ISSUE TITLE
Coffeescript test suite errors after parser build?

### ISSUE THREAD

**Issue by GabrielRatener** [jashkenas/coffeescript#3750]
When forking coffeescript, I run `$ cake test`, with all but 3 tests passing. But after running

```
$ cake build
$ cake build:parser
$ cake test
```

with no modifications, 9 tests fail. Is there something I am doing wrong or is this a bug?

**Comment by lydell** [comment]
Fixed by #3794.

**Comment by KID-WuMeng** [comment]
@lydell Thank you very much ! It's nice !
