### ISSUE TITLE
Regular expressions can't start with whitespace

### ISSUE THREAD

**Issue by cscott** [jashkenas/coffeescript#3756]
This might be bug or an "undocumented feature" -- but it's the latter, it should be better documented.
See also #3182 (regexps can't start with the equals sign either).
```
$ coffee -e '/a/'
$ coffee -e '/ a/'
[stdin]:1:1: error: unexpected /
/ a/
^
$ coffee -e 'console.log / a/'
[stdin]:1:17: error: unexpected end of input
console.log / a/
                ^
$ coffee -e 'console.log(/ a/)'
[stdin]:1:13: error: unexpected /
console.log(/ a/)
            ^
$ coffee -e 'r=/ a/'
[stdin]:1:3: error: unexpected /
r=/ a/
  ^
```
Escaping the initial whitespace as `/\ a/` is a workaround.

**Comment by lydell** [comment]
It would be great if the error messages were better: A `/` is _not_ unexpected when it could have been a regex. Explicitly telling that the `/` (or `/=`) was parsed as division would be better: 

```
$ coffee -e '/ a/'
[stdin]:1:1: error: unexpected / (division)
/ a/
^
$ coffee -e 'console.log(/ a/)'
[stdin]:1:13: error: unexpected / (division)
console.log(/ a/)
            ^
$ coffee -e 'r=/ a/'
[stdin]:1:3: error: unexpected / (division)
r=/ a/
  ^
```

or something like that.

Does anyone know how to customize Jison to do this?

**Comment by lydell** [comment]
#3782 + the section I just added in the [Common Gotchas wiki page](https://github.com/jashkenas/coffeescript/wiki/Common-Gotchas) should be enough in my opinion. No reason to add edge cases to the docs.

Regarding my comment about those error messages above: They’re not needed anymore because of #3782.
