### ISSUE TITLE
Enhancement: functions that by default have no return result, aka 'undefined'

### ISSUE THREAD

**Issue by silkentrance** [jashkenas/coffeescript#3762]
coffee-script@1.8.0

As of now, you will always have to include an undefined on the last line of a function's block, i.e.

```
a = ->
  do_something
  undefined
```

otherwise, coffee-script will try to compile a return result from either the last invocation or assignment, or, if that fails, it will compile an array, injecting the required code and thus making things overly complex.

How about adding the following syntax extension to functions that will instruct the compiler to just return undefined, aka void 0?

```
a = ->>
  do_something
```

or, for bound functions

```
a = =>>
  do_something
```

I think that this extra syntactic sugar will make things more easier for all of us.

Please note that I settled on doubling the `>` instead of introducing yet another character. Having tried out multiple alternatives, for example `->:` or `->u`, simply doubling the `>` seems to be more readable and also easier to type.

**Comment by eranimo** [comment]
If this discussion keeps being brought up, maybe that's a sign that something in the language should be changed.
