### ISSUE TITLE
Method aliases for CS classes

### ISSUE THREAD

**Issue by nicholasrq** [jashkenas/coffeescript#3764]
I haven't found any issues about that, so i decided to open one.

It will be really awesome to add `alias` functionality for classes. I mean when you writing code you can add an alias for any already declared method to bring, for example, back compatibility in your lib. I believe that such syntax will be not very complex (for reading):

```coffeescript
class A
  hello: (name)-> console.log("Hello, #{name}!")

  alias greet, hello
```

which should be compiled into:

```javascript
var A;

A = (function() {
  function A() {}

  A.prototype.hello =
  A.prototype.greet = function(name) {
    return console.log("Hello, " + name + "!");
  };

  return A;

})();
```

And if there are multiple aliases for one method:

```coffeescript
class A
  hello: (name)-> console.log("Hello, #{name}!")

  alias greet, hello
  alias say_hello, hello
```

then it should do something like that:

```javascript
var A;

A = (function() {
  function A() {}

  A.prototype.hello =
  A.prototype.greet =
  A.prototype.say_hello = function(name) {
    return console.log("Hello, " + name + "!");
  };

  return A;

})();
```

And now i'm not sure what we should do when someone is trying to create an alias of an alias. I mean something like that:

```coffeescript
class A
  hello: (name)-> console.log("Hello, #{name}!")

  alias greet, hello
  alias say_hello, greet
```

I guess there should happen some resolving of already declared aliases and if you trying to create an alias of an alias we should check original method and, if it was declared, make an alias of it, but not of another alias.

In case when you trying to create an alias of undeclared method then compiler error must be raised.

P.S. Of course we can make a function `alias` inside of a class which will just create new methods on `prototype`, but i think that doing such things at compile time is more accurate way.

**Comment by jashkenas** [comment]
greet: this::hello

... is a totally groovy way to write it. No need for extra fluff — and in general, you never want to be adding aliases (unless you're deprecating a previously mis-named method). We shouldn't be adding sugar to make it easier.
