### ISSUE TITLE
debug at terminal? like nodejs debug?

### ISSUE THREAD

**Issue by TangMonk** [jashkenas/coffeescript#3767]
I offen use `$ node debug app.js` to debug nodejs application and into REPL :

``` js
< debugger listening on port 5858
connecting... ok
break in app.js:1
  1 global.root = __dirname;
  2
  3 var config = require('./config/config.js');
debug>
(^C again to quit)
debug>
```

the CoffeeScript official document shows:

![http://i.imgur.com/dUqDP9w.png](http://i.imgur.com/dUqDP9w.png)

So i type: `$ coffee --nodejs --debug index.coffee`

but nothing happend

**Comment by TangMonk** [comment]
@caseyWebb , thanks for your reply.
I installed node-inspector:

```bash
Node Inspector v0.8.1
```

But when I run ```coffee --nodejs --debug index.coffee```, and terminal show:

```bash
$ coffee --nodejs --debug index.coffee
debugger listening on port 5858
$ 
```

But nothing happed

**Comment by caseyWebb** [comment]
@TangMonk That allows the debugger which runs in the browser to connect to the app. In another terminal tab, run `node-inspector` and go to `localhost:8080/debug?port=5858` in your browser
