### ISSUE TITLE
Comma in list of object behaves inconsistently.

### ISSUE THREAD

**Issue by i4han** [jashkenas/coffeescript#3768]
obj = [
        name: 'john', age: 25
    ,   name: 'kim',  age: 21
    ,   name: 'nick', age: 23
    ]
complies to 

    var obj;
    
    obj = [
      {
        name: 'john',
        age: 25
      }, {
        name: 'kim',
        age: 21,
        name: 'nick',
        age: 23
      }
    ];

**Comment by jashkenas** [comment]
CoffeeScript is not a comma-first language. That's compiling correctly.

**Comment by connec** [comment]
If you add an extra linebreak after the comma it will compile as expected:

```coffee
obj = [
  name: 'john', age: 25
,
  name: 'kim',  age: 21
,
  name: 'nick', age: 23
]
```

**Comment by jashkenas** [comment]
Also correctly.
