### ISSUE TITLE
Coffeescript Mimetype

### ISSUE THREAD

**Issue by DevynCJohnson** [jashkenas/coffeescript#3769]
I think you may find it interesting to know that Coffeescript now has an officially registered mimetype with the IANA. The details can be seen here - http://dcjtech.info/topic/coffeescript-mimetype/

**Comment by vendethiel** [comment]
Nice to know, thanks.

**Comment by jashkenas** [comment]
Let's tag 'em as we close 'em.

**Comment by vendethiel** [comment]
That's not a "question"

**Comment by jashkenas** [comment]
Ha ha. Considering that it's not the correct mime-type that CoffeeScript actually uses, perhaps it's a new "bug" ;)

**Comment by michaelficarra** [comment]
We should add a "should have been posted to the making list" label.
