### ISSUE TITLE
@ of inside do -> inside => is not properly set 

### ISSUE THREAD

**Issue by ippeiukai** [jashkenas/coffeescript#3772]
`@` (this) inside `do ->`  is not properly set when used inside a function defined with `=>` (fat arrow).
Either
* ``do`` keyword should keep same @ inside and outside ``->``, or
* this behaviour should be clearly documented.

The non-issue case with no ``do ->`` for comparison:
```CoffeeScript
obj0 =
  greet: -> 
    console.log 'hi'
  hi5: ->
    [1..5].forEach =>
      @greet()

obj0.hi5() # OK
```

The issue with ``do ->`` inside ``=>``:
```CoffeeScript
obj1 =
  greet: -> 
    console.log 'hi'
  hi5: ->
    [1..5].forEach =>
      do -> @greet()
   
obj1.hi5() # TypeError: undefined is not a function (evaluating 'this.greet()')
```

Very tedious, but if every nested function uses a fat arrow, the issue can be avoided:
```CoffeeScript
obj2 =
  greet: -> 
    console.log 'hi'
  hi5: ->
    [1..5].forEach =>
      do => @greet()
   
obj2.hi5() # OK
```

Alternatively, manually binding to ``@`` instead of ``do`` keyword works too:
```CoffeeScript
call = (_this) -> (fn) -> fn.call(_this)

obj3 =
  greet: -> 
    console.log 'hi'
  hi5: ->
    [1..5].forEach =>
      call(@) -> @greet()

obj3.hi5() # OK
```

**Comment by epidemian** [comment]
No need for using `do` inside a `=>` to reproduce this. This simplified case will also break:

```coffeescript
obj1 =
  greet: -> 
    console.log 'hi'
  hi: ->
    do -> @greet()

obj1.hi() # TypeError: this.greet is not a function
```

It's actually the correct behaviour, if you wan't `this` to be preserved inside the `do`, you should use a fat arrow:

```coffeescript
obj1 =
  greet: -> 
    console.log 'hi'
  hi: ->
    do => @greet()

obj1.hi() # OK
```

**Comment by ippeiukai** [comment]
I see.

This behaviour is not very intuitive. It would be nice if the documentation of `do` keyword could be improved.

Would there be any drawback to always using ``do =>`` where ``do ->`` is used? I'm now thinking of consistently using ``do =>`` throughout my codebase if this behaviour indeed is correct; it would be one thing less to worry about. May it even be something to be recommended in an improved documentation?

**Comment by michaelficarra** [comment]
Sure, always use a fat arrow with `do`. I don't think any documentation change is warranted. `do` is just function application with zero arguments. If you know that and you know how CoffeeScript functions work, the semantics of their combination is obvious.

**Comment by jashkenas** [comment]
Let's tag 'em as we close 'em.

**Comment by ippeiukai** [comment]
> I don't think any documentation change is warranted. do is just function application with zero arguments.

I disagree about this statement.
`do` keyword immediately followed by a function definition actually passes the value of variables of same name (or the default value if specified) as arguments. This behaviour is special, and it is usually used to create a variable scope in the flow.
As such, I find the change of `@` within `do ->` rather unexpected and in my opinion warrants a mention in the documentation.

**Comment by michaelficarra** [comment]
If we've not documented that special form of `do`, we should. I only claimed we did not need to document trivial, unsurprising interactions between any two features.

**Comment by ippeiukai** [comment]
> If we've not documented that special form of do, we should.

As far as I can see, `do` keyword is hardly documented:
> CoffeeScript provides the do keyword, which immediately invokes a passed function, forwarding any arguments.

To me, the only trivial case is when `do` works as a unary operator of "function application with zero arguments". The statement "immediately invokes a passed function, forwarding any arguments" here is not at all trivial to understand and strictly speaking incorrect; with `do` keyword, the generated JS function is different. 

function:
``` Coffee
# (bar = 10) goes inside the function
fn = (foo = (bar = 10)) ->
  undefined
```
`do` keyword:
``` Coffee
# (bar = 10) happens outside the function.
do (foo = (bar = 10)) ->
  undefined
```
