### ISSUE TITLE
A Method: Single-Direction Scoping/Shadowing

### ISSUE THREAD

**Issue by eshinn** [jashkenas/coffeescript#3773]
I've only been at CoffeeScript for a week but came across a 2-yr old gripe. After reading hoards of people asking for `:=` or something similar to another language or at least the `var` to be usable, I came across one method by using:

    do (x = 10) ->
      also some other code

This a little on the manual, human-error-prone side considering that a developer needs to re-assign the value. It also returns some ugly-looking JavaScript:

    (function(x) {
      return also(some(other(code)));
    })(10);

What's 'X'? Answer is in Appendix: Arg! ..scroll down.

I've also read a blog post on using back-ticks to simply write '\`var x = 10\`'. Nothing quite like going against the design principle. Less said about that the better.

With a slight modification to the `do` method, adding `{` and `}` around the list of variables to be shadowed, and you have:

    do ({that, scope, thing}) ->

That's it. Use it in a function like so:

    someMethod = (_foo) -> do ({that, scope, thing}) ->
      also some other code
      scope = _foo # "Kung"->_foo

    someMethod "Kung"

Turns into:

    someMethod = function(_foo) {
      return (function(_arg) {
        var scope, that, thing;
        that = _arg.that, scope = _arg.scope, thing = _arg.thing;
        also(some(other(code)));
        return scope = _foo;
      })({
        that: that,
        scope: scope,
        thing: thing
      });
    };

    someMethod("Kung");

Et voici! CoffeeScript hoists the variables listed via the _arg object then assigns the variables their respective values at time of invocation. Access to variable values higher up, ability to assign values locally, and without the nasty destruction of global variables and methods.

**Comment by michaelficarra** [comment]
Okay.
