### ISSUE TITLE
Block comment for class property is made for __extends call

### ISSUE THREAD

**Issue by FredyC** [jashkenas/coffeescript#3775]
Well this is rather surprising and I wonder what change happened between 1.6.3 and 1.8 that has caused this. Simple looking piece of coffee script code...

```
class SomeChild extends SomeParent

  ###*
    Messages' Time-To-Live in milliseconds
    After this time messages are considered expired
    @type {number}
    @const
  ###
  @MessageTTL = 5000
```

And this is basically when compiled by CS@1.8

```
SomeChild = (function(_super) {

  /**
    Messages' Time-To-Live in milliseconds
    After this time messages are considered expired
    @type {number}
    @const
   */
  __extends(SomeChild, _super);

  SomeChild.MessageTTL = 5000;
```

You can see that `__extends` is wrongly placed after the comment. Since we are parsing this to create docs, it cannot work correctly. When you try same piece of code in CS@1.6.3, it is correct.

```
SomeChild = (function(_super) {
  __extends(SomeChild, _super);

  /**
    Messages' Time-To-Live in milliseconds
    After this time messages are considered expired
    @type {number}
    @const
  */

  SomeChild.MessageTTL = 5000;
```

Unfortunately 1.6.3 has other issues that concerns us. I am wondering if this would be hard to fix.

**Comment by FredyC** [comment]
Ok, I think I have found the commit that caused this... https://github.com/jashkenas/coffeescript/commit/9ba1d41ec8532ec6b85927000945d030eafea21a

In case it isn't this commit, I am pretty much sure that things has broken [between these two commits](https://github.com/jashkenas/coffeescript/compare/0d662c3ad2f6bfbe923b19b45a9805947a42a297...efe8c68c759f5bf9034c0b7ae28c5140b53d7114)

I am not really sure what was reason for this commit or how to fix this. Hopefully somebody can have a look at it please ?

**Comment by GeoffreyBooth** [comment]
[This doesn’t appear to be an issue in CoffeeScript 2.](http://coffeescript.org/v2/#try:class%20SomeChild%20extends%20SomeParent%0A%0A%20%20%23%23%23*%0A%20%20%20%20Messages’%20Time-To-Live%20in%20milliseconds%0A%20%20%20%20After%20this%20time%20messages%20are%20considered%20expired%0A%20%20%20%20%40type%20%7Bnumber%7D%0A%20%20%20%20%40const%0A%20%20%23%23%23%0A%20%20%40MessageTTL%20%3D%205000)

**Comment by FredyC** [comment]
Ah, that's nice. Didn't even knew there is a CS2 with such support for ES6+. Although I am not using CS anymore, it's definitely good to know. Thanks :)
