### ISSUE TITLE
Sometimes possible to alter how many times a for loop is run, sometimes not

### ISSUE THREAD

**Issue by lydell** [jashkenas/coffeescript#3778]
```
$ coffee -e 'a=2; for i in [1..10] by a then a=i; console.log i'
1
2
4
8
$ coffee -e 'a=2; for i in [1..10] by a+0 then a=i; console.log i'
1
3
5
7
9
```

If the by expression is `_ref`ed you cannot change the number of times the loop runs, otherwise you can.

`for i in [a..b]`: Same thing, unless `a` or `b` is `_ref`ed you can alter how many times the loop is run. I guess that should not be possible, just like modifying `array.length` inside a `for item in array` loop does not alter the loop.

The solution might be to _always_ cache range starts and ends as well as the step in for loops if they reference a variable (even if `.isComplex()` returns false).

Extracted from https://github.com/jashkenas/coffeescript/issues/3598#issuecomment-69221755.

**Comment by michaelficarra** [comment]
Agreed, always cache it.
