### ISSUE TITLE
code at http://coffeescript.org/#lexical-scope could be more clearer

### ISSUE THREAD

**Issue by haandol** [jashkenas/coffeescript#3779]
I think original coffee code requires knowledge of hoisting and it may confuses javascript novices like me.
for an example, below code does not set 'inner' variable in anonymous function.
```javascript
outer = 1
inner = changeNumbers()    // JavaScript only hoists declarations, not initializations.
changeNumbers = ->
  inner = -1
  outer = 10
```

by the section's description, I think below code is more clearer.
```javascript
outer = 1
changeNumbers = ->
  inner = 10
outer = changeNumbers()
```

this coffee code will be compiled to
```javascript
var changeNumbers, outer;
outer = 1;
changeNumbers = function() {
  var inner;
  return inner = 10;
}
outer = changeNumbers();
```

**Comment by michaelficarra** [comment]
This has been brought up many times before (it's actually the *opposite* of hoisting), and this behaviour will not be changing.

**Comment by haandol** [comment]
I should've searched first.. thanks :+1:
