### ISSUE TITLE
Does this exist?

### ISSUE THREAD

**Issue by zimt28** [jashkenas/coffeescript#3793]
Does coffee offer a shorthand for `aVar = aVar.someFunction()`? It would be great if we could just do something like `!aVar.someFunction()`. This could even work for things like `!aNumber * 30 +5` (`aNumber = aNumber * 30 + 5`)

**Comment by epidemian** [comment]
Not in Coffee AFAIK. LiveScript has the `.=`, which is similar to the `+=` or similar operators but for method calls:

```livescript
foo.name .= toUpperCase()
```

```javascript
// Generated by LiveScript 1.3.1
foo.name = foo.name.toUpperCase();
```

I personally find it intuitive enough and think it could be a good addition to Coffee, but wouldn't mind if it were shut down either, it's not a *killer* feature.

**Comment by matthewlucock** [comment]
I think the `.=` behaviour is something that happens often enough that it would be nice to have this as a feature.

**Comment by ymeine** [comment]
@epidemian A small fix: in LiveScript this works for property access more generally, whether you call the value or not then.

This is quite a useful feature, especially in algorithms around `while` loops for instance. However I don't see how it could be reasonably implemented for any kind of expression such as complex arithmetic ones (as @zimt28 showed).

**Comment by matthewlucock** [comment]
Yeah, I don't see any way an implementation of this kind of behaviour could work with arithimetic. @zimt28  proposed syntax using `!`, but using `!` for this behaviour doesn't seem feasible, both because it is cryptic and doesn't express intent, but also because `!value` syntax obviously already exists in JavaScript, so this would be especially confusing and potentially break already-existing scripts. I think something like LiveScript's  `.=` is a good way to implement this kind of behaviour, but of course, arithmetic assignment operators already exist.

**Comment by goto-bus-stop** [comment]
Coco also has `<unary> = <lhs>` like `! = foo` → `foo = !foo`, but that's a bit more magical.

I've found `lhs .= property` to be very useful though. :+1: on that.

**Comment by jashkenas** [comment]
I'm afraid I'm not a fan of this particular operator. Even aside from being very mutation-oriented ... In the given example:

    foo.name .= toUpperCase()

It looks to the reader like `toUpperCase()` is a free function being called by itself ... not a method of the `name` property.

Let's leave it out.

**Comment by blitmap** [comment]
@jashkenas Would you approve of this if the operator were reversed?  (`=.`)

I think the reverse visually associates `toUpperCase()` with `foo.name`:

```coffeescript
foo.name =. toUpperCase()
```

Another consideration (if this were supported) would be to also support `x =:: method()`

I don't particularly care about invoking functions like this, I just want a shorter way of writing:

`longMeaningfulIdentifier = longMeaningfulIdentifier.member`

I do this a lot to extract the `value` yielded from an iterator: `iterItem =. value`
