### ISSUE TITLE
Invalid generated string literals

### ISSUE THREAD

**Issue by lydell** [jashkenas/coffeescript#3795]
It is currently possible to write CoffeeScript that results in invalid JavaScript when it comes to strings literals:

- Both the U+2028 and the U+2029 characters are passed through into the JavaScript output. However, in JavaScript they are line terminators (just like \n and \r), and string literals may not contain (unescaped) line terminators. Redux handles this case by converting those characters to the escape sequences `\u2028` and `\u2029`. Another way of handling it could be to just like JavaScript allow them to be line terminators, and normalize them into \n characters in `Lexer::clean`, similarly to how \r\n is handled.

- Invalid escape sequences beginning with `\u` or `\x` are also passed through into the JavaScript output, but that is syntactically invalid. Redux handles this by turning the `\u` into `u` and `\x` into `x`, making them work like most other characters (such as `\a`, `\+`, etc.). An argument against that could be that if a string literal contains `a\u002b` the author probably meant to type `a\u0020b` and might prefer an error (just like in JavaScript). This could be checked together with octal literals in `Lexer::makeString`.

**Comment by lydell** [comment]
I think the best would be to do it like Redux does, unless the second point above is an accident, @michaelficarra?

**Comment by michaelficarra** [comment]
I'd go with the CSR behaviour for the former, and either behaviour for the latter, as long as you mean *compile time* error, not passing the value through and waiting for a runtime error.

**Comment by lydell** [comment]
OK, then let’s

- turn U+2028 and U+2029 into `\u2028` and `\u2029` escapes
- throw a compile time error for invalid `\u` and `\x` escapes

**Comment by lydell** [comment]
I have no idea why, but in JavaScript, `"\u002"` is an error while `/\u002/` isn’t (`/\u002/.test("u002") === true`). Moreover, in strict mode, octal escapes are forbidden in strings but not in regexes. Wouldn’t it be more helpful if regexes worked like strings in these cases? We could do so in CoffeeScript.

**Comment by jashkenas** [comment]
Your plan sounds fine to me as well.

**Comment by lydell** [comment]
> Moreover, in strict mode, octal escapes are forbidden in strings but not in regexes.

That’s because for example `\1` is a backreference in a regex, not an octal escape.
