### ISSUE TITLE
"for key in myObject" is translated incorrectly

### ISSUE THREAD

**Issue by jochemgeussens** [jashkenas/coffeescript#3797]
Dear community

I recently got started with Coffeescript and I love the clean syntax! ;) Even though the JS could be better in some occasions (e.g. for-loops are ugly after translation :o ).

However when I want to merge 2 Objects, I found that Coffeescript translates "for key in myObject" incorrectly .

This code:
>     myObject = test : "something"
>     for key in myObject
>         console.log(key)

Translates into:
>     var key, myObject, _i, _len;
>     myObject = {
>         test: "something"
>     };
>     for (_i = 0, _len = myObject.length; _i < _len; _i++) {
>         key = myObject[_i];
>         console.log(key);
>     }

NOTE the `myObject.length`, this is not permitted by Google Chrome. Someone on SO wrote that you should get the length of an object by doing: `Object.keys(myObject).length`. 

I'm not sure why Coffeescript discards translations to `for ... in ...`, but it they hadn't it would work like expected.

I'll use this code as an alternative for now:
>     keys= Object.keys(myObject)
>     for i in [0 ... keys.length] by 1
>         key= keys[i]
>         otherObject[key] = myObject[key]

Thanks for developing Coffeescript, keep up the good work ;)

Kind regards, 
Jochem

**Comment by epidemian** [comment]
It's `for key of object` in CoffeeScript (which unfortunately conflicts with the newly added [`for ... of` loops in JS](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of)). See http://coffeescript.org/#loops

Cheers!

**Comment by jochemgeussens** [comment]
Thanks! :+1:
