### ISSUE TITLE
Found a bug in combining string without a whitespace after +

### ISSUE THREAD

**Issue by wdhwg001** [jashkenas/coffeescript#3801]
```coffeescript
obj={'en-us':{ID:'X-1'}}
console.log('233' + obj['en-us'].ID +'233')
```

will be compiled to:

```javascript
// Generated by CoffeeScript 1.8.0
(function() {
  var obj;

  obj = {
    'en-us': {
      ID: 'X-1'
    }
  };

  console.log('233' + obj['en-us'].ID(+'233'));

}).call(this);

//# sourceMappingURL=test.js.map
```

instead of:

```javascript
console.log('233' + obj['en-us'].ID + '233');
```

Well since only a few people will use +'233' as a parameter(although it could work like parseInt('233')), so it it a bug?

BTW, there is another [bug in my webstorm](https://youtrack.jetbrains.com/issue/WEB-14939) which force me to use original string combining way...

**Comment by vendethiel** [comment]
See the [FAQ](https://github.com/jashkenas/coffeescript/wiki/FAQ).
