### ISSUE TITLE
syntax like "for item in array in arrayOfArrays"?

### ISSUE THREAD

**Issue by QxQ** [jashkenas/coffeescript#3803]
This would be a small change that I think can make nested for loops look a lot nicer.

    for item in array in arrayOfArrays
        doSomething()

would be the equivalent to

    for array in arrayOfArrays
        for item in array
            doSomething()

It could also be used like this:

    for key in object,i of arrayOfObjects

or this

    doSomething(item) for item in array in arrayOfArrays

and maybe even the below code (though arguably no, because it's kind of ugly). Useful if you just don't care about the middle variable.

    for item in in arrayOfArrays
        doSomething()

which means

    for _var in arrayOfArrays
        for item in _var
            doSomething()

**Comment by christopherdumas** [comment]
This seems like extra bloat, or a feature that would only be rarely used.

**Comment by connec** [comment]
```coffee
for array in arrayOfArrays then for item in array
  doSomething()
```

Close enough.

**Comment by QxQ** [comment]
oh, I didn't know about the `for array in arrayOfArrays then for item in array`, that's nice to know.

extra bloat? maybe, but a feature rarely used? I find myself often with two for loops right next to each other, and it seems nice and readable to be able to have them squished into one line.

**Comment by jashkenas** [comment]
for array in arrayOfArrays
      for item in array
        do something

Is the nicer way to write this.
