### ISSUE TITLE
why not use some short extension names than "coffee", suck as,  "cf".

### ISSUE THREAD

**Issue by michael-lu-cn** [jashkenas/coffeescript#3806]

**Comment by carlsmith** [comment]
Same reason as people avoid one letter variable names: Typing stuff is easy, decoding tons of abbreviations isn't. People generally prefer the shortest English word that works.

**Comment by michael-lu-cn** [comment]
but ruby use rb, python use py, and javascript use js.

**Comment by bjmiller** [comment]
".cs" was (and, remains) already in use by C#.  ".coffee" is the next best thing.  We're not living in a DOS/Windows 3.1 world.  File extensions don't have to be three chars or less anymore.

**Comment by shunsukeaida** [comment]
I think you should've claimed it much earlier (perhaps 5 or 6 years ago), as it comes off as one of the critical choices for a language design.

I personally like `.coffee` (and `.scala`) lots though.

**Comment by michael-lu-cn** [comment]
I agree coffee is the next best thing,  but coffee is to make things simple, why not use a short extension like "cf" to reduce gratuitous type， everytime type a long extension name when create a file is not  elegance ｉthink .

**Comment by XiKuuKy** [comment]
Well it would cause a lot of confusion hence CoffeeScript developers are used to '.coffee'. It isn't that hard to just write out '.coffee' and is a lot more straight forward. CoffeeScript is much younger than C# by the way...

**Comment by carlsmith** [comment]
> but ruby use rb, python use py, and javascript use js.

Yeah, those names are from the 1900s. Py and JS are natural as people use those abbreviations a lot in practice. No one uses CF for CoffeeScript, it tends to be CS, and that's gone.

**Comment by vendethiel** [comment]
> CF

that'd probably be coldfusion ;-)

**Comment by jashkenas** [comment]
For the record, historically, CoffeeScript used to use a `.cs` extension. We switched over to `.coffee` pretty early on.

**Comment by michael-lu-cn** [comment]
can you simply add the 'cf' extension support ? like litcoffee and coffee.md .  some guys like me may  prefer the simplify version extension name.

**Comment by michael-lu-cn** [comment]
can you simply add the `cf` extension support ? like `litcoffee` and `coffee.md` . some guys like me may prefer the simplify version extension name.

**Comment by jashkenas** [comment]
> can you simply add the cf extension support ?

No.

**Comment by ymeine** [comment]
I don't know for what purpose additional extensions are wished and I personally agree with @carlsmith about keeping meaningful names and thus avoiding awful and confusing abbreviations, however I see that the `coffee-script` module exposes a `FILE_EXTENSIONS` property (which is used by `register` for module loading for instance, but also at some other places), maybe this could be used.

**Comment by michael-lu-cn** [comment]
> I don't know for what purpose additional extensions are wished and I personally agree with ....

but extension name is so frequently used,  i think it deserve a abbreviation.  I do know how to add it,  just don't want to fork another coffee.

**Comment by epidemian** [comment]
> but extension name is so frequently used, i think it deserve a abbreviation.

This highly depends on your workflow. I personally don't find myself creating lots of new files in my everyday job. And i'd much rather have readable file names than quickly-writeable ones. The shell will \<tab\> complete long file names when i have to open or pass them to some command.

In any case, if you find that creating `.coffee` files is taking too much of your time, you can always automate that. A little Bash function like `cof() { touch "$1.coffee"; }` will let you create files by simply saying `cof hello`.

**Comment by danielbayley** [comment]
What about `.cfe`?

**Comment by GeoffreyBooth** [comment]
```bash
echo 'console.log "Dumb idea!"' > test.cfe
cat test.cfe | coffee -bps
```

**Comment by danielbayley** [comment]
`coffee -bps < test.cfe`

No need for `cat` 😼

Obviously it _could_ be _anything_… but why not a more ‘official’ shorthand?

**Comment by carlsmith** [comment]
> Obviously it could be anything… but why not a more ‘official’ shorthand?

Just to try and lay this to rest...

Languages and file formats pretty much universally stick to one extension each. There has to be a really good reason to alias an extension, especially as you need all the text editors, file browsers and other tools to add support for it.

CoffeeScript and Literate CoffeeScript are different languages, so it was natural for them to have their own extensions. Literate CoffeeScript does sort of have two, but note that the`.coffee.md` extension actually *enabled support by existing tools*. All the reasons for not aliasing an extension were inverted in that case. It's also technically not another extension at all; it's a sub-extension for `.md` files.

CoffeeScript is no freer with the extensions than any other project. There's one per language, and I can't see that ever changing.

**Comment by danielbayley** [comment]
Well Markdown has 4 or 5… which is silly. I just wondered what the reasoning might be other than ‘historical’…

It doesn’t exactly bother me a whole lot, but I have seen people list it under ‘cons’ against CoffeeScript and really the fewer of those, the better for it’s adoption… which _is_ something I’m bothered about.

**Comment by carlsmith** [comment]
Who has filename length on their list of pros and cons when deciding which language would work best for a project?

**Comment by danielbayley** [comment]
Not me! But I have seen it a few times.
