### ISSUE TITLE
In-browser compiler tries to "require('fs')"

### ISSUE THREAD

**Issue by scottb** [jashkenas/coffeescript#3811]
Sourcing the 1.8.0 code from CDNJS into the browser gets an error: "Uncaught ReferenceError: require is not defined"...

    <html>
      <script src='//cdnjs.cloudflare.com/ajax/libs/coffee-script/1.8.0/coffee-script.min.js'></script>
      <script type='text/coffeescript'>
          alert "Hello world"
      </script>
    </html>

**Comment by vendethiel** [comment]
Require is added by the cakefile before the rest of the code. Seems to me there's something else going on.

**Comment by jashkenas** [comment]
Something else indeed. We don't publish to CDNJS — so if they have a problem, you'll have to take it up with them.
