### ISSUE TITLE
Do we need any syntax to leverage generators/promises coding patterns?

### ISSUE THREAD

**Issue by Artazor** [jashkenas/coffeescript#3815]
I believe that JS community is agree that generators+promises coding patterns will be the next big thing in JavaScript development world. With such things as io.js it looks like the future already is here. And I want to start a discussion on possible new syntax and semantics of the corresponding language elements. 

I invite you to take a brief look at the one of the possible implementations #3813, and provide a constructive critics for it, as well as discussion around it.

TL;DR - for demonstration I've implemented a toy feature (diamod arrows - [see the test case](https://github.com/Artazor/coffeescript/blob/e384eedc91dd0ca20cb91078fc78df05cc768cdc/test/generators/async.coffee)) that allows concisely write async/await like functions. This feature interplays very well with CoffeeScript classes and inheritance and have a very small footprint (comparable with _extends utility). I agree that the syntax chosen is a bit ridiculous, but I want to discuss the semantics and the future general line rather than the particular syntax

**Comment by jashkenas** [comment]
Why open a ticket just to refer to another ticket? We can take a look at #3813 directly.

**Comment by Artazor** [comment]
Sorry, I've thought that PR tickets without corresponding Issue ticket is not a normal situation. Will not do it again -)
