### ISSUE TITLE
In 1.9.0, Coffeescript breaks Angular dependency injection

### ISSUE THREAD

**Issue by bcherny** [jashkenas/coffeescript#3816]
If I had the following code:

```coffee
beforeEach ->
  module 'foo'
  inject (@$httpBackend, @$templateCache, @foo) =>
```

**1.8.0** compiles it to:

```js
beforeEach(function() {
  module('foo');
  return inject((function(_this) {
    return function($httpBackend, $templateCache, foo) {
      _this.$httpBackend = $httpBackend;
      _this.$templateCache = $templateCache;
      _this.foo = foo;
    };
  })(this));
});
```

While **1.9.0** produces:

```js
beforeEach(function() {
  module('foo');
  return inject((function(_this) {
    return function(_at_$httpBackend, _at_$templateCache, _at_foo) {
      _this.$httpBackend = _at_$httpBackend;
      _this.$templateCache = _at_$templateCache;
      _this.foo = _at_foo;
    };
  })(this));
});
```

The issue is that Angular parses the function parameters to figure out which dependencies to inject into the test. `$httpBackend` is a valid dependency, but `_at_$httpBackend` is not, breaking the test.

**Comment by jashkenas** [comment]
In general, we don't aim to produce generated JavaScript that suits the whims of tools that depend on brokenly reverse-parsing function bodies at runtime ... but that said ...

@lydell? The `_at_` doesn't seem terribly elegant. Do we need it?

**Comment by lydell** [comment]
See https://github.com/jashkenas/coffeescript/pull/3784#discussion_r22762512.

**Comment by jashkenas** [comment]
I see, but it looks like you fixed the underlying bug as well. Can we just make it `$httpBackend` for the local variable name? If not — why not.

**Comment by lydell** [comment]
If so, what should `(@case)->` compile to?

**Comment by jashkenas** [comment]
Ha ha! Asking for trouble, but, `_case`, I would think.

**Comment by lydell** [comment]
Well, if somebody feels like refactoring `Scope::freeVariable` then go for it.

**Comment by vendethiel** [comment]
Note that `_case` won't fix the OP's case.

**Comment by jashkenas** [comment]
I'm not sure that this fixes your Angular woes ... but it does remove the `_at_` prefix.

**Comment by lydell** [comment]
> .. but it does remove the _at_ prefix.

... and replaced it with an `_` prefix. I think Angular is looking for things starting with `$`.

**Comment by bcherny** [comment]
Angular needs the argument name to be the same as the dependency name. Eg. If my dependency is "foo", the argument name can only be "foo". The $ sign is not special in any way, that's just what the dependency's name starts with.

**Comment by lydell** [comment]
What about ditching the leading underscore for _all_ generates vars?

**Comment by jashkenas** [comment]
Having the naked name (without and underscore) would be fine, except for the duplicate case:

    (@one, one) ->

... and for the invalid reference case:

    (@case) ->

... unless you do two-pass or some other kind of smarter naming. I'd be fine with that — but I'm also fine with the current version. We shouldn't be jumping through hoops for Angular's massively fragile runtime source decompilation and parsing.

**Comment by lydell** [comment]
Those are _not_ problems with the current implementation.

**Comment by jashkenas** [comment]
They are if you remove the leading underscore. Give it a try — the tests crash.

**Comment by lydell** [comment]
This will be a lot easier to show with a PR. Unfortunately, I will not have time for one this weekend.

**Comment by lydell** [comment]
Ok, I got the time anyway.

**Comment by DavidSouther** [comment]
Not sure if better to jump on here, or open a new issue - but isn't this technically a breaking change? Shouldn't this have bumped the semver to 2.0? If anyone is depending on '~1.x' and accidentally did something like

```
class Foo
  constructor: (@bar)->
    @baz += bar
```

their code will break, and it's very unclear why.

**Comment by vendethiel** [comment]
> semver

That's probably not a word you want to use here... ;-)


Basically, this was not a "feature" to start with (no examples in the docs or anything), so it's not a breaking change

**Comment by DavidSouther** [comment]
As closed in the referenced 3817, as well as numerous threads on Coffee Script Redux, this is expected and dependent behavior that WILL cause issues with installed codebases and WILL break existing deployments.

**Comment by DavidSouther** [comment]
This portion of the documentation, especially, is what I think implicitly encouraged many to use this behavior - 

https://github.com/jashkenas/coffeescript/blob/81047d45ee823dbfd534b7aa518d800ae5cedd6c/index.html#L1474-L1615

**Comment by DavidSouther** [comment]
Which, coincidentally, is incorrect in the latest docs: http://coffeescript.org/#try:class%20Animal%0A%20%20constructor%3A%20(%40name)%20-%3E vs https://github.com/jashkenas/coffeescript/blob/master/index.html#L1507-L1510

**Comment by bioball** [comment]
Weren't scenarios like `(@case) ->` already accounted for in 1.8, using underscores? I believe it was just prepending underscores to just reserved keywords. Angular aside, not using underscores is still more elegant if it's not needed.

As far as the duplicate case, I'm thinking it should just throw an error.

**Comment by lydell** [comment]
@bioball try latest master and see what you think.

**Comment by bioball** [comment]
Ah, cool. Sorry, didn't see a commit message that referenced going back to naked variable names, so I thought we were going with underscores for everything.
