### ISSUE TITLE
Destructuring Arguments defaults

### ISSUE THREAD

**Issue by zimt28** [jashkenas/coffeescript#3818]
I just learned that I can I can do

```coffeescript
({prop1, prop2, prop3}) ->
```

This is great, but I'm used to doing 

```coffeescript
(optional = 'Default') ->
```

When I try to combine these two great things, it won't work. 

```coffeescript
({property, optional = 'Default'}) ->
```

I think this would be really nice to have, why isn't it implemented?

**Comment by vendethiel** [comment]
Duplicate of #2427.
