### ISSUE TITLE
Constructor @parameter assignment 1.7.1 -> 1.8+ regression

### ISSUE THREAD

**Issue by ssboisen** [jashkenas/coffeescript#3819]
We might have discovered a regression from 1.7.1 to 1.8+.

Concerning the following codesnippet:

```
class ColumnBase
    constructor: (@colConf) ->
      @type = colConf.Type
      @params = colConf.Params
      @colData = colConf.ColData
```

In 1.7.1 it compiles to this working JavaScript:

```
 function ColumnBase(_at_colConf) {
        this.colConf = _at_colConf;
        this.type = this.colConf.Type;
        this.params = this.colConf.Params;
        this.colData = this.colConf.ColData;
}
```

In 1.8 and 1.9 however it compiles to this none-working JavaScript:
```
function ColumnBase(_at_colConf) {
        this.colConf = _at_colConf;
        this.type = colConf.Type;
        this.params = colConf.Params;
        this.colData = colConf.ColData;
}
```

Anyone know if this is intentional? It wasn't mentioned in the change-log so I'm assuming no.

**Comment by vendethiel** [comment]
This is perfectly normal, you're not allowed to access to at-parameter without the at-sign.

**Comment by ssboisen** [comment]
In that case I wonder why it wasn't marked as a compile error when it was changed?

**Comment by vendethiel** [comment]
That's not a "regression". That's never been a feature to start with -- if you have `(@foo) ->` you should refer to it as `@foo` in your function body.

**Comment by ssboisen** [comment]
So it was a bug in every previous version? Then I wish it would have been mentioned as a bug-fix :-)

**Comment by connec** [comment]
Perhaps this should be mentioned specifically in the changelog, since there's been two issues raised since yesterday.

**Comment by nwinter** [comment]
I would've really appreciated seeing it in the changelog; it's so easy to leave the `@` off and not notice in the older versions.

**Comment by jashkenas** [comment]
Voilá. Added to the changelog.

**Comment by ssboisen** [comment]
+1 for adding it to the change-log. And I don't think it should have been changed - why introduce an unnecessary backwards incompatibility? I don't think you can argue that it's not valid to refer to `@param` as param in the scope of the constructor. That's somewhat similar to how TypeScript works with it's *parameter property declaration* feature. Seeing as TypeScript was architected by one of the greatest language designers in the world Anders Hejlsberg, I think it can be seen as a guiding light when in doubt :-)
