### ISSUE TITLE
CS1.9 returns wrong position for string properties in object literals

### ISSUE THREAD

**Issue by swang** [jashkenas/coffeescript#3822]
The following code in 1.8 
```cs
stringyObject =
  'stringkey' : 'ok'
```
The token for string, 'stringkey' returns
```cs
[ 'STRING', 
  '\'stringkey\'', { first_line: 1, first_column: 2, last_line: 1, last_column: 12 }, 
  spaced: true ]
```
However, in 1.9 it returns
```cs
[ 'STRING', 
  '\'stringkey\'', { first_line: 1, first_column: 3, last_line: 1, last_column: 11 }, 
  spaced: true ]
```

Using git bisect I traced this back to 0dcff507fbeafb3d37ed22296def5fdcc2deb069 which was the large refactoring of the lexer by @lydell.

**Comment by lydell** [comment]
Is this a problem?

**Comment by swang** [comment]
Yeah it messes with the spacing rules in coffeelint since `stringkey` in 1.9 is now counted as being 2 spaces away from the colon.

**Comment by lydell** [comment]
Why not update coffeelint then?

**Comment by connec** [comment]
The content of the token includes the quotes.  The quotes are at columns 2 and 12.  I'd say the first column and last column should match the token content... Otherwise what do they mean?

**Comment by swang** [comment]
@lydell But why not fix it in the lexer?

I mean the gist of this issue is, "is this a bug or not?" I think it is, and if it is, shouldn't it be fixed upstream so that developers working with it downstream are not affected? I appreciate that nice PR you put up, as it allows me to get rid of this clutchski/coffeelint@5d818a5a4b4310cc147614e54d972b23f47cad88 but now I will have to contend with string tokens being shorter than they are (maybe trivial to fix in coffeelint).

Anyways I thought I would get your attention since you are the one most familiar with that code and it would probably be much easier for you to change than it would be for me. But assuming the owners/contribs consider it a bug and would accept a PR for it, I wouldn't mind making the PR if you're too busy.

**Comment by lydell** [comment]
Oh I mixes up the 1.8 and 1.9 outputs above. Yes, I think the 1.8 locations are more logical.

**Comment by rcrichton** [comment]
@jashkenas any chance we could get a patch release with this fix? It's preventing me from being able to convert my generators because we are using coffeelint.

**Comment by jashkenas** [comment]
Feel free to use **master** for the time being ... but yes, we can do a patch sometime soonish.
