### ISSUE TITLE
If the keyword yield is the only way to define a generator, then it can't be compatible with koa

### ISSUE THREAD

**Issue by hwoarangzk** [jashkenas/coffeescript#3823]
My coffee code:
<pre>
koa = require 'koa'
app = koa()

app.use (next) ->
	yield next
	console.log this.req.url

app.use (next) ->
	this.body = 'hello koa'

app.listen 3000
</pre>

And the compiled js:
<pre>
// Generated by CoffeeScript 1.9.0
(function() {
  var app, koa;

  koa = require('koa');

  app = koa();

  app.use(function*(next) {
    (yield next);
    return console.log(this.req.url);
  });

  app.use(function(next) {
    return this.body = 'hello koa';
  });

  app.listen(3000);

}).call(this);

</pre>

Then it reported an error on the 2nd middleware: 
### TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "hello koa"

Then I modified my code in coffee:
<pre>
koa = require 'koa'
app = koa()

app.use (next) ->
	yield next
	console.log this.req.url

app.use (next) ->
	yield this.body = 'hello koa'

app.listen 3000
</pre>
I added the yield keyword in my 2nd middleware

And the compiled js:
<pre>
// Generated by CoffeeScript 1.9.0
(function() {
  var app, koa;

  koa = require('koa');

  app = koa();

  app.use(function*(next) {
    (yield next);
    return console.log(this.req.url);
  });

  app.use(function*(next) {
    return (yield (this.body = 'hello koa'));
  });

  app.listen(3000);

}).call(this);

</pre>
It also reported the same error.

Does anyone know a solution to this issue? Thanks.

BTW, I'm very happy to see that coffee script now supports generator. I've been waiting for a long time for this feature :)

**Comment by vendethiel** [comment]
You can use `yield return` to have a non-yielding generator function.

**Comment by hwoarangzk** [comment]
But sometimes we don't want to write yield in a koa's middleware, e.g.:
<pre>
app.use(function *(next) {
    this.body = 'hello world';
});
</pre>
How could get this done in coffee script?
If I don't write yield keyword, koa will assume that I didn't pass a generator to the use() and then throw an error

**Comment by vendethiel** [comment]
As I explained in my previous comment -- add `yield return` at the end of your function to not yield but make the function a generator

**Comment by hwoarangzk** [comment]
Thanks for your reply, this really could solve the issue.
Anyway, I still wonder whether the grammar of the generator in coffee script could be better improved in the future. In the issue I listed above, I don't want to yield anything, so why do I have to write the yield keyword?
Thank you again for your reply :)

**Comment by RobinQu** [comment]
Why should I yield something I don't need......
