### ISSUE TITLE
Plans for ES6?

### ISSUE THREAD

**Issue by ccorcos** [jashkenas/coffeescript#3824]
There is probably a post somewhere about this, but I can't find it -- what are coffeescript's plans for ES6? Any new feature ideas? ES6 has added a lot of new functionality that emulates coffeescript, but you still need damn parentheses and braces everywhere.

**Comment by jashkenas** [comment]
There are comments floating around the depths of these issues, but to recapitulate:

CoffeeScript only deals with JavaScript that actually exists. Not hypothetical JavaScript, not hidden-behind-flags-and-about:config-JavaScript. And for the record, "ES6" isn't even a thing anymore. The committee has decided to call it "ECMAScript 2015": https://esdiscuss.org/topic/javascript-2015

CoffeeScript adopts useful new features from new versions of JavaScript as they happen.

**Comment by ccorcos** [comment]
ok. so coffeescript is going to continue to be more badass than javascript? ;)

**Comment by jashkenas** [comment]
CoffeeScript was inherently first designed for an ES3 world ... but we're going to try.

**Comment by Racum** [comment]
+1

**Comment by paveltaran** [comment]
+1, please, do it, coffeescript better then pure javascript, great work

**Comment by AsaAyers** [comment]
> CoffeeScript only deals with JavaScript that actually exists

How did Generators make the cut when they only exist in [2 browsers](http://kangax.github.io/compat-table/es6/)?

**Comment by lydell** [comment]
Don't forget iojs and node 0.12.

**Comment by umhan35** [comment]
CoffeeScript is just getting outdated.

**Comment by zimt28** [comment]
> CoffeeScript is just getting outdated.

@umhan35 Same feeling

**Comment by ccorcos** [comment]
Outdated how?

**Comment by FranzSkuffka** [comment]
I checked  out ES6 the other day and honestly, I don't get the hype. No complete native support on browsers or node, babel is somewhat slow. Clunky syntax compared to CS, and not a single feature that would make the downsides bearable from my POV. Writing coffeescript still seems more future proof. @umhan35 why outdated?

**Comment by rajbits** [comment]
@jashkenas - Many of us still love coffeescript though we have been using ES6 as well in equal measures. Looking forward to your message on what are the plans for coffeescript going forward.

**Comment by ccorcos** [comment]
So I do like CoffeeScript, but I have since moved to ES6. Here's my 2 cents:

- Everyone is using it. That's actually important -- the big reason we're even using JavaScript and not Elm or OCaml or even Python is because so many people are developing libraries and tools for JS.

- ES6 Generators are pretty cool.

- ES7 async-await is even cooler.

That said, CoffeeScript has all of the syntactic sugar. I just wish it would support these new featues as they come out.

**Comment by anodynos** [comment]
I agree with the points - ES6 Generators are supported BTW since 1.9 - "CoffeeScript now supports ES6 generators. A generator is simply a function that yields". 

But there are many cool features of ES6 that just aren't part of coffeescript, and its a shame :-(
