### ISSUE TITLE
Extra 'end of interpolation' tag

### ISSUE THREAD

**Issue by swang** [jashkenas/coffeescript#3831]
Take this interpolated string:
```cs
"A #{a} B #{b}"
```
which generates these tokens:
```
[ '(', '(', { first_line: 0, first_column: 0, last_line: 0, last_column: 0 }, origin: [ '', 'interpolation', { first_line: 0, first_column: 2, last_line: 0, last_column: 3 } ] ]
[ 'STRING', '"A "', { first_line: 0, first_column: 0, last_line: 0, last_column: 2 } ]
[ '+', '+', { first_line: 0, first_column: 4, last_line: 0, last_column: 4 } ]
[ '(', '(', { first_line: 0, first_column: 4, last_line: 0, last_column: 4 } ]
[ 'IDENTIFIER', 'a', { first_line: 0, first_column: 5, last_line: 0, last_column: 5 }, variable: true ]
[ ')', ')', { first_line: 0, first_column: 6, last_line: 0, last_column: 6 }, origin: [ '', 'end of interpolation', { first_line: 0, first_column: 6, last_line: 0, last_column: 6 } ] ]
[ '+', '+', { first_line: 0, first_column: 7, last_line: 0, last_column: 7 } ]
[ 'STRING', '" B "', { first_line: 0, first_column: 7, last_line: 0, last_column: 9 } ]
[ '+', '+', { first_line: 0, first_column: 11, last_line: 0, last_column: 11 } ]
[ '(', '(', { first_line: 0, first_column: 11, last_line: 0, last_column: 11 } ]
[ 'IDENTIFIER', 'b', { first_line: 0, first_column: 12, last_line: 0, last_column: 12 }, variable: true ]
[ ')', ')', { first_line: 0, first_column: 13, last_line: 0, last_column: 13 }, origin: [ '', 'end of interpolation', { first_line: 0, first_column: 13, last_line: 0, last_column: 13 } ] ]
[ ')', ')', { first_line: 0, first_column: 14, last_line: 0, last_column: 14 }, stringEnd: true ]
[ 'TERMINATOR', '\n', { first_line: 0, first_column: 15, last_line: 0, last_column: 15 } ]
```
Which looks like this:
```
("A "+(a)+" B "+(b))
^       ^         ^
|       +---------+---> end of interpolation tags
|
+---> start of interpolation tag
```
This is one possible fix, which moves the 'end of interpolation' tag into the last parenthesis to match the 'interpolation' tag on the first parenthesis:
```patch
:100644 100644 e216403... 0000000... M	src/lexer.coffee

diff --git a/src/lexer.coffee b/src/lexer.coffee
index e216403..be83fe5 100644
--- a/src/lexer.coffee
+++ b/src/lexer.coffee
@@ -504,7 +504,6 @@ exports.Lexer = class Lexer
       [open, ..., close] = nested
       open[0]  = open[1]  = '('
       close[0] = close[1] = ')'
-      close.origin = ['', 'end of interpolation', close[2]]
 
       # Remove leading 'TERMINATOR' (if any).
       nested.splice 1, 1 if nested[1]?[0] is 'TERMINATOR'
@@ -588,6 +587,7 @@ exports.Lexer = class Lexer
         last_line:    lastToken[2].last_line
         last_column:  lastToken[2].last_column + 1
       }
+      rparen.origin = ['', 'end of interpolation', rparen[2]]
       rparen.stringEnd = true
 
   # Pairs up a closing token, ensuring that all listed pairs of tokens are
```
However this causes some problems when running the tests:
```
  #1316: unexpected end of interpolation 
  AssertionError: Expected [stdin]:1:5: error: unexpected end of interpolation
"#{+}"
    ^ to equal [stdin]:1:5: error: unexpected )
"#{+}"
```
The error goes from `unexpected end of interpolation` to `unexpected )`
## Importance
Coffeelint needs to know when string interpolations occur so it can ignore the '+' signs that are added since they interfere with rules about spacing between operators. Personally I think the patch I suggested is the easiest fix to the problem even though it changes the error message to be less helpful. Not sure which way is "correct" but would prefer it to be a way that makes it easier for coffeelint to ignore the generated '+' tokens.

Thanks.

**Comment by lydell** [comment]
I don't understand what's wrong here, and how it is a problem for coffeelint. Each interpolation inside a string is _supposed_ to have that "end of interpolation" origin. That the first parenthesis has an "interpolation" origin is just a hack to get a better error message for `{"#{a}":b}`—if you look at the line/column info it points to the first interpolation, not the start of the string.

**Comment by swang** [comment]
Interesting, I had thought the end interpolation tag was originally in the string in previous versions. Turns out I was wrong and there wasn't one.

There is a rule in coffeelint that makes sure operators are properly spaced. Since interpolated strings always had '+' tokens that were unspaced, it would always trigger this rule. To get around it coffeelint would just skip interpolated strings. The extra parentheses throws it off.

Anyways, It just seems weird that there is no consist start/end of the interpolation. I will look to see if there's another way around this.

**Comment by lydell** [comment]
We used to _sometimes_ wrap interpolations with paren tokens. In 1.9 we _always_ do. Moreover, the ending such paren now has an `origin` property, which it didn't before. I don't see how this can cause any trouble.

**Comment by swang** [comment]
I ended up with another way around this.
