### ISSUE TITLE
"yield return" from a conditional does not return if followed by a statement

### ISSUE THREAD

**Issue by ide** [jashkenas/coffeescript#3837]
If you have `yield return` in a conditional that has a statement after it, it doesn't actually return. This is a serious bug.

```coffeescript
example = ->
  if a
    yield return b
  return c
```
compiles to
```javascript
var example;

example = function*() {
  if (a) {
    b;
  }
  return c;
};
```

**Comment by nfour** [comment]
Woah, I'm surprised I haven't encountered code breakage from this yet.

**Comment by jashkenas** [comment]
Paging @alubbe.

If things like this are lingering, it would also be advisable to further beef up the `yield` test suite.

**Comment by alubbe** [comment]
@nfour 
That's because it is unusual to use yield return anywhere but on your last line of code.

@ide 
Use this in the mean time:
```
example = ->
  if a
    return b
  yield return c
```

@jashkenas 
I'm on it, hope to fix it by the weekend. How close are we to publishing a 1.9.1, to get this fix in?

**Comment by ide** [comment]
We replaced all yield returns with return yields as an easy fix (also easy to change back). It incurs an extra pass of generator delegation but that was fine for our workload.

**Comment by alubbe** [comment]
Or you could just use ```return``` as always and use ```yield return``` only for the last case.

In any case, it'll get fixed.

**Comment by jashkenas** [comment]
We can publish one soon, if you like.

**Comment by alubbe** [comment]
fixed with https://github.com/jashkenas/coffeescript/pull/3854

**Comment by georgy7** [comment]
I don't know if I right or wrong, but I think that is also an incorrect behaviour.

    fact = (n) ->
      n * fact(n-1) if n >= 1
      1
    
    console.log fact 10

Result:

    var fact;
    
    fact = function(n) {
      if (n >= 1) {
        n * fact(n - 1);  ///// return n * fact(n - 1); expected
      }
      return 1;
    };
    
    console.log(fact(10));

(Generated right now on coffeescript.org)

**Comment by alubbe** [comment]
hi @georgy7, the behavior you are observing is intended. What you need to do is to make your ```else``` explicit 
```coffee
fact = (n) -> if n >= 1 then n * fact n - 1 else 1
```
or to ```return``` on your if condition
```coffee
fact = (n) ->
  return n * fact n - 1 if n >= 1
  1
```

**Comment by georgy7** [comment]
@alubbe, thanks to your response.
In that case I would prefer this.

    fact = (n) ->
      if n >= 1
        n * fact(n - 1)
      else
        1

Or

    fact = (n) ->
      return n * fact n - 1 if n >= 1
      return 1

Because I think it's bad to use implicit and expicit returns together.
