### ISSUE TITLE
Edge case of string concatenation causes unmatched left parentheses 

### ISSUE THREAD

**Issue by robertg** [jashkenas/coffeescript#3844]
*Didn't find an existing issue from a previous search.*

The following bug is interesting: [coffeescript.org link](http://coffeescript.org/#try:appModule.directive%20'backImg'%2C%20-%3E%0A%20%20(scope%2C%20element%2C%20attrs)%20-%3E%0A%20%20%20%20attrs.%24observe%20'backImg'%2C%20(value)%20-%3E%0A%20%20%20%20%20%20element.css(%7B%0A%20%20%20%20%20%20%20%20'background-image'%3A%20'url('%20%2B%20value%20%2B')'%2C%0A%20%20%20%20%20%20%20%20'background-size'%20%3A%20'cover'%0A%20%20%20%20%20%20%7D)%0A)

Essentially:

```
appModule.directive 'backImg', ->
  (scope, element, attrs) ->
    attrs.$observe 'backImg', (value) ->
      element.css({
        'background-image': 'url(' + value +')',
        'background-size' : 'cover'
      })
```
Transpiles to:
```
appModule.directive('backImg', function() {
  return function(scope, element, attrs) {
    return attrs.$observe('backImg', function(value) {
      return element.css({
        'background-image': 'url(' + value(+')', {
          'background-size': 'cover'
        })
      });
    });
  };
});
```
Note the `'url(' + value(+')'`. If you add a space between `+')'`, it will not add a left parans.

**Comment by connec** [comment]
`+<thing>` is treated as a unit `(+')')`, which means `value +')'` is treated as a function call.

**Comment by vendethiel** [comment]
See the FAQ in the wiki and the thousands of duplicates.
