### ISSUE TITLE
Weird array being inserted into a generated brace ({) token

### ISSUE THREAD

**Issue by swang** [jashkenas/coffeescript#3846]
An implicit curly brace now returns a token like this
```
[ '{', [ { '0': '{' }, undefined, generated: true ], 
  generated: true,
  origin: [ ':', ':', { first_line: 12, first_column: 15, last_line: 12, last_column: 15 },
  spaced: true ]
]
```

[Pretty sure it's this thing generating it, but not sure how to fix and/or it's late here.](https://github.com/jashkenas/coffeescript/blob/8130e63e43d3932180a90049c34154b322086a1c/src/rewriter.coffee#L174)

**Comment by jashkenas** [comment]
Blame says that @xixixao added that line?

**Comment by swang** [comment]
I just did a git bisect and it blames this commit from back in 2013 1666716c3168f70e9eb6c997e0fff5f2b7815fc0

It initially started out as just `[ '{', ['{', null], (rest of token)]` and was never fixed and has just been propagating since.

**Comment by jashkenas** [comment]
Sounds like it's worth doing a patch, then.

**Comment by lydell** [comment]
Looks like `generate(new String('{'))` should be replaced with `'{'`.
