### ISSUE TITLE
How to run generator with coffee file.coffee without compiling the coffee file first?

### ISSUE THREAD

**Issue by hwoarangzk** [jashkenas/coffeescript#3847]
My code(test.coffee):
```
koa = require 'koa'
app = koa()

app.use (next) ->
	console.log 'hello'
	yield next

app.listen 3000
```

But if I run like this:
```
coffee test.coffee
```
It said that:
```
app.use(function*(next) {
                ^
ntaxError: Unexpected token *
at exports.runInThisContext (vm.js:69:16)
at Module._compile (module.js:443:25)
```
Is there anyway to run the file directly calling ``coffee test.coffee`` without compiling the coffee file into js file? Thanks :)

**Comment by michaelficarra** [comment]
You want to use the `--nodejs` flag to pass the `--harmony` flag to node. The compiler will always compile your CoffeeScript first. It is not an interpreter.

**Comment by hwoarangzk** [comment]
So there is no way to run my code like ``coffee --harmony test.coffee``? I have to compile the coffee file into js first?

**Comment by michaelficarra** [comment]
Red my comment.

```
coffee --nodejs --harmony test.coffee
```
