### ISSUE TITLE
Is it possible to define and declare a variable in the same line?

### ISSUE THREAD

**Issue by acroca** [jashkenas/coffeescript#3848]
I'm using a library that evaluates the JS code statically and doesn't work havingthe declaration and definition of variables in two different lines.

Is it possible to add the `var` in the same line when it doesn't affect the context?

For example, a simple user.coffee file like
```
class User

module.exports = User
```

it doesn't really need to do the `var User` and `User = ...` in different lines.

**Comment by epidemian** [comment]
You mean if there's a way for the generated JS to have the variable declaration and assignment on the same statement? I.e., compiling:

```coffeescript
foo = 42
```

... to:

```javascript
var foo = 42;
```

If that's the case, then no, there's no way to do that now. But i think it'd be a nice if there was. It would make the generated JS more similar to what most people would write. 

It's not a simple thing though. We'd have to decide how to compile multiple assignment lines, assignments inter-mixed with other statements, etc.

**Comment by jashkenas** [comment]
No. The current compilation is nicer, more similar to how JS semantics actually work, and more expression-oriented.

If your library can't figure this out, then I hate to be the one to inform you — but your library is broken.

Cheers.

**Comment by acroca** [comment]
No problem. Thanks anyway :grinning:
