### ISSUE TITLE
repl test breaks on 0.12

### ISSUE THREAD

**Issue by alubbe** [jashkenas/coffeescript#3855]
This test https://github.com/jashkenas/coffeescript/blob/master/test/repl.coffee#L106 now fails on 0.12. I'm not sure what's going on here because when I run the coffee repl it does keep running after runtime errors, so the test must be testing something incorrectly. Could someone help me figure this out?
```
  keeps running after runtime error 
  AssertionError: Expected 0 to equal -1
  at global.eq (/home/andreas/coffee-script/Cakefile:313:65)
  at /home/andreas/coffee-script/test/repl.coffee:106:28
  at Function.<anonymous> (/home/andreas/coffee-script/test/repl.coffee:38:17)
  at global.test (/home/andreas/coffee-script/Cakefile:276:12)
  at testRepl (/home/andreas/coffee-script/test/repl.coffee:38:8)
  at Object.<anonymous> (/home/andreas/coffee-script/test/repl.coffee:104:1)
  at Object.<anonymous> (/home/andreas/coffee-script/test/repl.coffee:1:1)
  at Module._compile (module.js:460:26)
 
  function () {
      return fn(input, output, repl);
    }
```

**Comment by jashkenas** [comment]
On that line, what *is* the value of `output.lastWrite()`?

**Comment by alubbe** [comment]
```"coffee> "```

**Comment by jashkenas** [comment]
Voilá. An overly fragile test. I'd remove that line, and the two following, and just make it: 

   eq output.lastWrite(), "coffee> "

**Comment by alubbe** [comment]
but that doesn't work on 0.10, where lastWrite equals ```"undefined"```

**Comment by alubbe** [comment]
I've compiled their outputs across their version.
```coffee
testRepl "keeps running after runtime error", (input, output) ->
  input.emitLine 'a = b'
  # on 0.10, output.lastWrite() === "ReferenceError: b is not defined\n    at repl:3:9\n    at REPLServer.replDefaults.eval .........."
  # on 0.12, output.lastWrite() === "coffee> "
  eq 0, output.lastWrite().indexOf 'ReferenceError: b is not defined'
  input.emitLine 'a'
  # on 0.10, output.lastWrite() === "undefined"
  # on 0.12, output.lastWrite() === "undefined"
  eq 'undefined', output.lastWrite()
```
My understanding is that the test really only whats to make sure that the repl keeps running after ```a=b```, so we could remove ```eq 0, output.lastWrite().indexOf 'ReferenceError: b is not defined'```, reducing the test to this, which passes on both 0.10 and 0.12:
```coffee
testRepl "keeps running after runtime error", (input, output) ->
  input.emitLine 'a = b'
  input.emitLine 'a'
  eq 'undefined', output.lastWrite()
```
See https://github.com/jashkenas/coffeescript/pull/3858

**Comment by jashkenas** [comment]
Sounds good.

**Comment by alubbe** [comment]
closed via https://github.com/jashkenas/coffeescript/pull/3858
