### ISSUE TITLE
Injection issues introduced by 1.9

### ISSUE THREAD

**Issue by NickClark** [jashkenas/coffeescript#3856]
In libraries like AngularJS that use dependency injection, the new `@val` to `_at_val` conversion in function params breaks it. Understandably, Angular doesn't want to support these kind of special cases angular/angular.js/pull/11074

**Comment by NickClark** [comment]
Sorry, I search first, somehow didn't see the existing issue. Found it now.

**Comment by slang800** [comment]
For reference, the issue that this is a duplicate of is #3816
