### ISSUE TITLE
in operator should support strings

### ISSUE THREAD

**Issue by adam-lynch** [jashkenas/coffeescript#3857]
Or at least return something other than an integer if `'a' in 'abc'` is called.

`'a' in ['a']` returns `true` but `'a' in 'abc'` returns `false` (because `[].indexOf.call('abc', 'a')` returns `-1` underneath).

**Comment by vendethiel** [comment]
#3238

**Comment by connec** [comment]
Also, `'a' in 'abc'` returns true (because `[].indexOf.call('abc', 'a')` returns `0`).

`in` works fine for checking if a character appears in a string.

**Comment by adam-lynch** [comment]
Yeah @connec, it's a mistake. Should've used a multi-character test string

**Comment by Inve1951** [comment]
Just came accross this unexpected behavior myself.

What's the reason for coffeescript to use `[].indexOf.call('abc', 'a')` over `'abc'.indexOf('a')`?

I found 1 case which probably serves as a good enough reason: `NodeList` objects don't have `indexOf`.

Are there any others?

**Comment by GeoffreyBooth** [comment]
I just stumbled into this one myself, writing code like `'foo' in str` and expecting it to work.

> What's the reason for coffeescript to use `[].indexOf.call('abc', 'a')` over `'abc'.indexOf('a')`?

@Inve1951 I would guess it’s because we want to ensure that `indexOf` is defined. Sure, if you’re comparing against a string literal like `'abc'` you know that `'abc'.indexOf` is defined, but if it’s a variable `str` you don’t know that `str` is truly an array or string (or defined).

**Comment by connec** [comment]
Another fun one is 'array-like' things, e.g.

```coffee
do (a = 1, b = 2, c = 3) ->
  alert 2 in arguments            # true

do (a = 1, b = 2, c = 3) ->
  alert arguments.indexOf(2) >= 0 # TypeError: arguments.indexOf is not a function
```

**Comment by jashkenas** [comment]
Yes. The reason is for array-like support. There are a bunch of JS objects that behave like arrays, but don't necessarily have all of the Array.prototype methods on them.
