### ISSUE TITLE
Long term stability of this project

### ISSUE THREAD

**Issue by user-three** [jashkenas/coffeescript#3859]
What is the long term viability of this project? 

I have used this language for 3 years, but I am hearing concerns from many people. I would love to continue using this language, it's such a pleasure to read and write.

@jashkenas, do you plan to stop maintaining the project with ES6 around? If you plan on stopping support for the language, are there any strategies for handing off support to an individual or a group?

Are worries about future maintenance and improvement of the language inaccurate? I hope so.

**Comment by jashkenas** [comment]
In bullet-point form:

* This is an open-source project. The long term viability is whatever you (the community) make of it. CoffeeScript already lives on in LiveScript, ES6 and ES7 and onwards — in bits and pieces, and elsewhere.

* I do not plan to stop maintaining the project with ES6 around. But for many years, CoffeeScript has been mostly "done" — the language hasn't changed much. It could certainly use more polish in places, but I don't see it transforming radically. That would be a different language.

* The vast majority of the work on CoffeeScript is already done by contributors. I don't mind wearing the "BDFL" hat and giving input for the indefinite future, but I can also see handing it off someday. A "strategy" for doing that is not required.

* CoffeeScript compiles to JavaScript. To the extent that JavaScript from 2015 is viable for the long-term, CoffeeScript from 2015 is equally viable for the long-term.

* FUD about the future of the language is just that — fear, uncertainty, and doubt. People like to use emotional reasons and follow trends when deciding what languages they want to program in. CoffeeScript has certainly been the beneficiary of that in the past, but the fads of fashion only last so long. Ultimately, it's just a programming language. Use it if you like it. Don't if you don't. Personally, I don't get to use it for very much in my day-to-day (but my day-to-day also doesn't involve a ton of programming).

* Do you have any specific questions?

**Comment by user-three** [comment]
@jashkenas That is a very nice response which answers my questions. Thank you!
