### ISSUE TITLE
To which extent has the ECMASCript 5 strict mode directive been implemented.....

### ISSUE THREAD

**Issue by larssb** [jashkenas/coffeescript#3860]
Hi CoffeeScript community.

I'm currently writing a project where I look at how CoffeeScript and TypeScript can potentially assist JavaScript developers circumvent pitfalls of JavaScript. In correspondence with that, it has great relevance to know at what extent CoffeeScript has implemented the restrictions of the strict mode directive in ECMAScript v5. Have they all been implemented or mainly the syntax related restrictions as discussed in this issue: https://github.com/jashkenas/coffeescript/issues/1547 ??

Looking forward to hear from you and thank you very much.
Regards
/Larssb

**Comment by lydell** [comment]
Have a look at test/strict.coffee.

**Comment by larssb** [comment]
Hi Lydell,

Thank you very much for your reply. Looked through the code in test/strict.coffee and can see that it is only the syntax related restriction of ECMAScript v5 strict mode that has been implemented.

Again thank you.
/larssb
