### ISSUE TITLE
Error: The two following source files have the same output file

### ISSUE THREAD

**Issue by Inversion-des** [jashkenas/coffeescript#3863]
After updating to v1.9.1 constantly receive error on file modification (notice same file path):
`Error: The two following source files have the same output file:`
`    D:\proj\public\js\coffee\orgFolders2.coffee`
`    D:\proj\public\js\coffee\orgFolders2.coffee`
It is on Windows, using watch-mode:
`coffee --output compiled/ --compile --watch --bare coffee/`
Rolling back to v1.9.0 resolves the problem.

**Comment by vendethiel** [comment]
Seems like #3758 is to blame?

**Comment by andilabs** [comment]
I was facing same issue with newer version on OS X (if it matters)
just as mentioned roll back to 1.9.0
`sudo npm install -g coffee-script@1.9.0`

**Comment by HandyAndyShortStack** [comment]
I am also getting this error whenever **coffee-script** v1.9.1 compiles a file. I am running the command `coffee -o build/js/ -cw coffee/`.  Specifying v1.9.0 in my **package.json** fixes the issue for me.

**Comment by javiercornejo** [comment]
Same problem here... I got error with 1.9.1 but with 1.9.0 not

**Comment by jwerre** [comment]
I'm also getting this when I watch

**Comment by max-m** [comment]
Same for me, 1.9.0 works fine.

**Comment by EdwardReed** [comment]
Can confirm on 1.9.0

**Comment by wildeyes** [comment]
Still happens on 1.9.1, using both -w and -c, doesn't happen on 1.9.0.

**Comment by lydell** [comment]
Still happens on 1.9.1 and will always happen on 1.9.1.

**Comment by Jmlevick** [comment]
Can confirm... 1.9.1 has this problem when using the command:

```
coffee -o js/ -cw coffee/
```

For compiling ".coffee" src files on-the-fly (I'm using Linux by the way)

**Comment by vendethiel** [comment]
Yes. This commit was made **after** 1.9.1 was tagged.

**Comment by eugene-piatenko** [comment]
Same problem with -w switch.
Installed 1.9.0 and it works fine.

**Comment by reddec** [comment]
I have the same bug when the file is changing (first compilation is successful).

- **Options:**  `-o . -wcm core.coffee`
- **Version:** CoffeeScript version 1.9.1
- **OS:** Ubuntu 14.04.2 LTS
- **node-js:** v0.10.25

**Comment by max-m** [comment]
`1.9.1` is `1.9.1` and will always be `1.9.1`
If an error exists in `1.9.1` it will ever exist in `1.9.1`
This error doesn’t occur in `1.9.0` and won’t in `1.9.2` or whatever version will be the next after `1.9.1`.

So: Either downgrade to `1.9.0`, apply [this patch](https://github.com/jashkenas/coffeescript/commit/c8147c046af21b4e0d94dcf784fac457f8c598c8) or wait for the next version.

**Comment by rex** [comment]
Beating a dead horse at this point, I know, but I wanted to chime in to confirm that reverting to `1.9.0` from `1.9.1` resolved this issue for me on Mac OS X Yosemite. 

*For the record, the command I was running in my `Procfile` was:*

```
coffee -cbw --no-header -o public/javascripts app/assets/coffeescripts
```

**Comment by gghez** [comment]
Thanks @andilabs for rollback information.
