### ISSUE TITLE
Problem with .delete

### ISSUE THREAD

**Issue by sebaplaza** [jashkenas/coffeescript#3864]
Hi,

There is a problem when you use variable.delete call

Example:
http://js2.coffee/#coffee/try:app.delete%20'bye%20baby'%0Aapp.hi%20'hi%20there'%0A%0A%23%20---%0A%23%20generated%20by%20js2coffee%202.0.1

Thanks !

**Comment by vendethiel** [comment]
Which is correct.

**Comment by sebaplaza** [comment]
Maybe is nothing, it's working anyway.

But the doc says that the normal behaviour is...

When i write
  CS -> app.delete 'bye'
I get
  JS -> app.delete('bye')

What i'm getting now 
  app["delete"]('bye');

**Comment by goto-bus-stop** [comment]
`object.property` and `object["property"]` are equivalent. `delete` is also a keyword, so some older JS environments might interpret it as the `delete` keyword instead of a property name. CoffeeScript "escapes" it to prevent that.

**Comment by sebaplaza** [comment]
Thank you, that is a good answer.
Of course is not an issue, my mistake.

**Comment by vendethiel** [comment]
Before you reported this "issue", did you try it and confirmed it was producing incorrect results?

**Comment by sebaplaza** [comment]
Yes, and it's correct.
