### ISSUE TITLE
feature request: fn(){} syntax

### ISSUE THREAD

**Issue by rebelwarrior** [jashkenas/coffeescript#3869]
While the stabby is great it's very different from normal JS, particularly its order:
```{coffeescript}
(args_first)-> 
  body
```
is equivalent of
`function(args_second){body}`

Can we have an alternate way of defining functions using 'fn' like this:
```
fn(args) {
  blah
} 
```
I know the curly brackets suck but it would be easier to understand by newbs to coffeescript like me.

Or even:
```
fn(args)->
  body
```

**Comment by carlsmith** [comment]
Nearly there...

**Comment by jashkenas** [comment]
Nope.
