### ISSUE TITLE
Use Loops instead of Slice for splats?

### ISSUE THREAD

**Issue by jashkenas** [jashkenas/coffeescript#3870]
... or perhaps a looping "slice"-ish helper function?

http://jsperf.com/rest-parameters

**Comment by vendethiel** [comment]
Isn't that a duplicate of #3274 ?

**Comment by jashkenas** [comment]
Ah yes — I thought it was, but couldn't find it.

**Comment by vendethiel** [comment]
Just doing my job :-).
