### ISSUE TITLE
Possible wrong behaviour with array comprehension

### ISSUE THREAD

**Issue by youtux** [jashkenas/coffeescript#3880]
Consider the following code, that given a list of `shows` it logs the one with `id = 1`:
```coffee
shows = [{
  id: 1
  title: 'a'
}, {
  id: 2
  title: 'b'
}]
show = item for item in shows when item.id == 1
console.log show
>>> {id: 1, title: 'a'}
```
Everything works nice, however if I try to use the same variable `item` instead of `show`:
```coffee
shows = [{
  id: 1
  title: 'a'
}, {
  id: 2
  title: 'b'
}]
item = item for item in shows when item.id == 1
console.log item
>>> {id: 2, title: 'b'}
```
The `item` variable gets assigned to the latest iteration of the for, giving an unexpected result. Is this behaviour legal or is it a bug?

**Comment by michaelficarra** [comment]
This is expected. Referencing a loop variable after the loop gives you its final value.
