### ISSUE TITLE
Can CoffeeScript add a feature similar to C#'s "extension methods"

### ISSUE THREAD

**Issue by zhanzhenzhen** [jashkenas/coffeescript#3884]
Can CoffeeScript add a feature similar to C#'s "extension methods"
https://msdn.microsoft.com/en-us/library/bb383977.aspx

So we can write:
```
[3, 4, 5] |> _.map (x) -> x + 1 |> _.max
```
It's equivalent to:
```
_.max(_.map([3, 4, 5], (x) -> x + 1))
```
But more intuitive.

I know underscore has a chaining feature, but the above syntax can be used for any libraries, without the need for developing a wrapper.

It's different from the pipeline and currying in many functional languages - every part between the `|>` operators isn't treated as a valid expression (but the whole chain is an expression). Compiler will recover the missing first parameters. So here no currying needed.

Syntax is like:
```
|> function-name [param1, [param2, ...]] |>
```
where param1 means the 2nd parameter of this function, param2 means the 3rd.

**Comment by jashkenas** [comment]
See previous tickets on a pipeline operator.

**Comment by vendethiel** [comment]
This is not what extension methods are. Extension methods are about adding methods to already-created classes by using the `(this Type obj)` syntax in parameters. It's not related to user-defined operators.
