### ISSUE TITLE
iterating over object generates slow js code

### ISSUE THREAD

**Issue by albertnetymk** [jashkenas/coffeescript#3889]
```
for k,v of obj
  console.log(k)
```
is translated to:
```
var k, v;

for (k in obj) {
  v = obj[k];
  console.log(k);
}
```
According to this [jsperf](http://jsperf.com/object-keys-iteration/86), this `in` construct is quite slow compared to `Object.keys()`.

**Comment by jashkenas** [comment]
And yet — it's what you wrote. Browser performance changes dramatically over time. CoffeeScript isn't going to second-guess you.

**Comment by hccampos** [comment]
Also, for-in includes the inherited properties of the object while Object.keys returns a given object's own enumerable properties. Therefore, the two are not equivalent.

**Comment by albertnetymk** [comment]
@hccampos Thanks for the tip. Didn't know this before. If so, wouldn't it make more sense to translate
```
for own k,v of obj
  console.log(k)
```
into sth using `Object.keys()`, instead of
```
var k, v,
  hasProp = {}.hasOwnProperty;

for (k in obj) {
  if (!hasProp.call(obj, k)) continue;
  v = obj[k];
  console.log(k);
}
```
