### ISSUE TITLE
Anonymus functions as a parameter issue

### ISSUE THREAD

**Issue by pmucha** [jashkenas/coffeescript#3895]
Here are three similar functions that do nothing, but should compile. The first two do, and the last one doesn't.
```
func1 ()->
    foo1 = foo2
    foo1
  ,()->
    foo3 = foo4
    foo3

func2( ()->
    foo1 = foo2
      .internalFunc1 ()->
        foo5 = foo6
        foo5
      .internalFunc2()
    foo1
  ,()->
    foo3 = foo4
    foo3
) 

func3 ()->
    foo1 = foo2
      .internalFunc1 ()->
        foo5 = foo6
        foo5
      .internalFunc2()
    foo1
  ,()-> # error: unexpected ,
    foo3 = foo4
    foo3
```
The introduction of the anonymous function in `internalFunc1` followed by `internalFunc2` messes things up. I don't suppose that's a feature.

**Comment by connec** [comment]
This compiles fine if you use consistent indentation (2 spaces):

```coffee
func1 ()->
  foo1 = foo2
  foo1
,()->
  foo3 = foo4
  foo3

func2( ()->
  foo1 = foo2
    .internalFunc1 ()->
      foo5 = foo6
      foo5
    .internalFunc2()
  foo1
,()->
  foo3 = foo4
  foo3
)

func3 ()->
  foo1 = foo2
    .internalFunc1 ()->
      foo5 = foo6
      foo5
    .internalFunc2()
  foo1
,()->
  foo3 = foo4
  foo3
```

**Comment by vendethiel** [comment]
Yeah, it just seems like poor indentation, nothing surprising here.

**Comment by pmucha** [comment]
Wrong! It's the compiler that has a problem with indentation. You see, my example was derived from the code similar to this:
```
Promise.all()
  .then ()=>
    allSettings = _(footerTemplateSettings)
      .extend headerTemplateSettings
      .thru (settings)->
        settings.templateId = settings.id
        settings
      .extend invoiceSettings
      .value()

    resolve allSettings
    @app.trigger "success", allSettings
    "success"

  ,(ajax)=>
    failureMessage = "A problem occured while..."
    reject failureMessage
    @app.trigger "error", failureMessage
    "error"
  
  .then (status)=>
    @app.trigger "complete", status
    return
```
It also does not compile, and it should.
1) The compiler _should_ allow for _even more_ indentation to separate:
```
Promise.all()
  .then ()=>
...
  ,(ajax)=>
...
  .then (status)=>
```
The `,(ajax)=>` part needs to be now in the same line as otherwise there could be problems. And it should be one level up, since it's an argument of `then()`. And that's not poor indentation, that's indentation on purpose, so there's no need to use any braces.
2) The above example could start working when it's changed to:
```
Promise.all()
  .then ()=>
    allSettings = _(footerTemplateSettings)
    .extend headerTemplateSettings
    .thru (settings)->
      settings.templateId = settings.id
      settings
    .extend invoiceSettings
    .value()
```
which is rather ridiculous, and again, indentation is to show that `extend`, `thru` etc. are for LoDash right? And as @connec clearly showed indentation here should work and the whole example shouldn't depend on it being there or not.

So, sorry, but no, this example is not invalid. The CS's indentation mechanism is invalid. Either it _requires_ the same indentation everywhere, or it learns to be flexible.

**Comment by connec** [comment]
OK, I think there is a bug here:

```coffee
promise
  .then ->
    ids = $(selector)
      .map (el) ->
        el.id
      .get()
    ids
```

Compiles to:

```javascript
promise.then(function() {
  var ids;
  return ids = $(selector).map(function(el) {
    return el.id;
  }).get();
});

ids; // why is this outside `then` function?
```

Most of the elements in the snippet are needed:

- `.then` must be on new line
- `.then` callback must be multiline
- `.map` callback must be multiline
- `.get()` must be present

Changing any one of them makes the snippet compile.

Another variant with the same issue:

```coffee
promise
  .then ->
    ids = $(selector).map (el) ->
        el.id
      .get() # works if this is indented the same as `ids =`
    ids
```

**Comment by vendethiel** [comment]
Then it's just a duplicate of #3845 and #3305.

**Comment by Panoplos** [comment]
(Copied from #3845 comment, as it was *closed* for some reason.)

I am having a similar issue with *bluebird* `Promise` code, as follows:

```coffeescript
doSomething argument
  .then (res) ->
    console.log res
  .catch (err) ->
    console.error err
```

this result in the following JavaScript:

```javascript
doSomething(argument).then(function(res) {
  console.log(res);
})["catch"](function(err) {
  console.error(err);
});
```

Which of course is seriously wrong...
