### ISSUE TITLE
lt, lte, gt, gte operators for testing inequality

### ISSUE THREAD

**Issue by olmokramer** [jashkenas/coffeescript#3897]
I would like to use the following operators in text form:
```
CS        JS
------------
lt        <
lte       <=
gt        >
gte       >=
```

**Comment by elseym** [comment]
+1 for consistency with `is` and `isnt`

**Comment by vendethiel** [comment]
"is" and "isnt" exist because coffee doesn't have js' "==", and it's less confusing that our "==" which translates in JS to "===".

**Comment by carlsmith** [comment]
The `==` and `!=` operators are different to `<`, `>`, `<=` and `>=` operators. It's normal to use the first two on lots of different value types, like `a is undefined`, but the other four generally only work well with numbers.

The proposed names are also less readable.

    if a lte b then c

    if a < b then c

**Comment by elseym** [comment]
@carlsmith well, i actually get the point from your example :) readability suffers with `if a lte b then c`.
@vendethiel isn't it the other way 'round? `is` means identity and `==` means equality?

**Comment by jashkenas** [comment]
No thanks. `lte` isn't a readable word, it's a strange abbreviation. `<=` is more readable.

**Comment by olmokramer** [comment]
Fair enough. I predicted this outcome, but worth the shot :)

**Comment by lydell** [comment]
@elseym `is` and `==` ar equivalent in coffee. Both compile to js' `===`.

**Comment by michaelficarra** [comment]
@olmokramer: Use a helper

```coffee
lt = (a, b) -> a < b
```

**Comment by olmokramer** [comment]
@michaelficarra Thanks, but then it reads 
```coffee
if lt a, b then do stuff
```
which is extremely unreadable

**Comment by michaelficarra** [comment]
It's just as readable as `a lt b`.
