### ISSUE TITLE
inline regex and split

### ISSUE THREAD

**Issue by dcsan** [jashkenas/coffeescript#3898]
there seems to be a bug when you use split() and a regex with spaces in it.

```coffee
    opts = str.split(/OR/i)     # ok
    opts = str.split(/ OR /i)   # not ok

```

with no spaces its OK:
![image](https://cloud.githubusercontent.com/assets/514002/6650213/380e8138-c9c3-11e4-90d0-23cf6d9e4820.png)

my CS linter doesn't like it for the same reason i guess.
![image](https://cloud.githubusercontent.com/assets/514002/6650214/44801864-c9c3-11e4-8e44-a5cb56734e2e.png)

also using embedded JS it works fine.

    `opts = str.split(/ or /i)`

**Comment by lydell** [comment]
This of course has nothing to do with the split method.

Starting a regex with a space used to be an error, but that was changed in 1.9.0. Your code is valid. Your syntax highlighter and linter need to be updates. File issues for those projects, if needed.
