### ISSUE TITLE
Are the source maps zero or one indexed?

### ISSUE THREAD

**Issue by carlsmith** [jashkenas/coffeescript#3899]
In CoffeeScript source maps, are the line numbers zero or one indexed? Same question for column numbers?

**Comment by michaelficarra** [comment]
There is a Google group for questions. Also, the source map is a standard, not of CoffeeScript's design. Also, you can just look for yourself.

**Comment by carlsmith** [comment]
I thought questions are welcome here. I was looking myself and was going to post the answer here if no one answered. For reference.

Moz use different indexing in their  source maps to Chrome tracebacks, so it's not always done the same way. It's not a simple thing to deduce what each component is doing in practice.

I only asked dude.

**Comment by carlsmith** [comment]
You seriously gonna close it without an answer?

**Comment by michaelficarra** [comment]
Don't take it personally. This space is for issues. Discussion belongs on the mailing list. FAQ is on the wiki.

**Comment by carlsmith** [comment]
Cool. Probably best to tighten up on here anyway. No worries.
