### ISSUE TITLE
=> always introduces _this, even when not used

### ISSUE THREAD

**Issue by wmertens** [jashkenas/coffeescript#3900]
`=>` converts to

``` javascript
(function(_this) {
  return (function() {});
})(this);
```

It would be nice if the wrapper was only generated when _this is actually being used.

**Comment by vendethiel** [comment]
Why would you use `=>` if you don't plan to use `this`?

**Comment by michaelficarra** [comment]
@vendethiel refactoring

@wmertens :+1: I believe I implemented this in CoffeeScriptRedux.

**Comment by vendethiel** [comment]
@michaelficarra I thought we already had a ticket for this, but I can't find it.

**Comment by jashkenas** [comment]
This would be nice to have ... and super easy to do.

**Comment by wmertens** [comment]
I'd rather almost always use fat arrow, because that's almost always what I
intend. I had many issues due to unexpected this targets, but very rarely
should I have used thin arrow.

It's also the only thing in ES6 (same semantics) so it makes coffeescript
more familiar for ES6 users.

**Comment by wmertens** [comment]
so... anybody think this is  easy to implement? :)

**Comment by GeoffreyBooth** [comment]
No longer relevant in CS2, where `=>` compiles to `=>`.
