### ISSUE TITLE
Broken compatibilty with Windows Script Host

### ISSUE THREAD

**Issue by ukoloff** [jashkenas/coffeescript#3908]
Since v1.9.0 coffee-script.js fails to run under Windows' cscript/wscript

Error is thrown on Object.create (in parser.js). WSH's Object has no create method. I think new version of jison uses Object.create, while old (0.4.13) didn't.

Possible workaround is to implement Object.create. I tried:

``` js
if(!Object.create)
  Object.create=function(proto)
  {
    function f(){}
    f.prototype=proto
    return new f
  }
```

and it helped.

**Comment by GeoffreyBooth** [comment]
We don’t aim to support all possible JavaScript runtimes. Please pass CoffeeScript’s output through Babel or a similar transpiler to generate ES3 or whatever other compatible JS you need.
