### ISSUE TITLE
Unneeded variable with computed property names?

### ISSUE THREAD

**Issue by DylanPiercey** [jashkenas/coffeescript#3917]
Currently
```coffeescript
x = "x#{"z"}": 1
```
becomes:
```javascript
var obj, x;

x = (
  obj = {},
  obj["x" + "z"] = 1,
  obj
);
```

I am just curious why it is not possible to simply re-use the variable x (I am assuming i'm missing an edge case) and output this:

```javascript
var x;

x = (
  x = {},
  x["x" + "z"] = 1,
  x
);
```

And have zero variable pollution.

---

**Example 2**

```coffeescript
x = {};

x.y = { "#{"o"}k": 1 };
```

Becomes:

```coffeescript
var x;

x = {};

x.y = (
  x.y = {},
  x.y["o" + "k"] = 1,
  x.y
);
```

Which may output more code.

**Comment by pepkin88** [comment]
The second example can give different results because of setters.
