### ISSUE TITLE
Impossible to use short form of prototype like a function.

### ISSUE THREAD

**Issue by Svoloch** [jashkenas/coffeescript#3919]
I use functtion based types and need to use functions as prototypes. Thus I need to call prototype.

```coffeescript
@constructor::(smth)
``` 
not compiled.
And now I need to use
```coffeescript
(@constructor::)(smth)
```
or
```coffeescript
(@constructor::) smth
```

It is a problem because I have many code with such constructions.

**Comment by michaelficarra** [comment]
See #1601. The unary postfix `::` syntax will be removed (eventually?), and should be treated as deprecated. Use 

```coffee
@constructor.prototype smth
```
