### ISSUE TITLE
switch interferes with "break" even though "break" not needed in switch

### ISSUE THREAD

**Issue by shaunc** [jashkenas/coffeescript#3920]
I understand that "break" is not used to stop passing from one "when" of a switch statement to the next in coffeescript. This means, I would expect, that break in a switch should break out of a loop surrounding the switch, yet it doesn't:

    while true
      console.log('loop')
      switch 1
        when 1
          break

Prints "loop" forever.

**Comment by lydell** [comment]
Duplicate of #2833.
