### ISSUE TITLE
CoffeeScript now works with FlowType.org

### ISSUE THREAD

**Issue by eduveks** [jashkenas/coffeescript#3923]
I've did some experiences to code in CoffeeScript and use Flow to validate my code.

Until now only this project helps me to make this work.

My code in CoffeeScript:
```
### @flow ###
a = 1
foo1 = (y) -> y * 10
foo1('abc')
foo2 = (x, y) ->
  x * y is 5
foo2('Hello', '42')
class Bob
  calculate: (x) ->
    x * x
b = new Bob()
b.calculate('4abc')
```
Now run:
```
$ coffee-to-typescript -cma index.coffee
```
Compile the final JavaScript code:
```
$ tsc index.ts
```
Now Flow works like a charm:
```
$ flow
```
>index.js:7:6,10: string
>This type is incompatible with
>  index.js:5:12,17: number
>
>index.js:11:6,12: string
>This type is incompatible with
>  index.js:9:12,16: number

>index.js:11:15,18: string
>This type is incompatible with
>  index.js:9:12,16: number
>
>index.js:21:13,18: string
>This type is incompatible with
>  index.js:16:16,20: number
>
>Found 4 errors

Finally a miracle! :D

**Comment by vendethiel** [comment]
I'm not sure why the coffee-to-ts step is required (class declaration?) but anyway, this is better suited for the mailing list :).

**Comment by eduveks** [comment]
Yes! And to normal functions too.
Because the coffee compiles like this:
```
foo1 = function(y) {
  return y * 10;
};
```
Flow is unable to interpret the code above.
But with coffee-to-typescript will generate a code like this:
```
function foo1(y) {
    return y * 10;
}
```
Much more straightforward to be interpreted by Flow.

You can try:
```
coffee -c index.coffee
```
```
flow
```
>No errors!

No errors detected! :(

Even with --bare the result is the same.

**Comment by emptist** [comment]
this is really interesting

**Comment by ArmorDarks** [comment]
This is great, but I can barely name double transpilation a solution.
