### ISSUE TITLE
Function parameter name modified after compilation when it's prefixed by @ (at-sign)

### ISSUE THREAD

**Issue by kayhadrin** [jashkenas/coffeescript#3927]
*First of all, apologies for raising a similar defect as #3891 but this previous one was reviewed and closed within 1 day without much of a debate.*

Coffeescript was generating a local variable with the same name as the method's "@" parameter name for a bit more than 4 years.

I often rely on it to save properties on an object and use them afterwards.

e.g.

```coffee
class Animal
	setName: (@name) ->
		console.log "Changed name = ", name
		name
```

But this type of algorithm doesn't work anymore in version 1.9.1 because the `name` variable is not defined anymore.

```js
// v1.9.1
var Animal;
Animal = (function() {
  function Animal() {}
  Animal.prototype.setName = function(name1) {
    this.name = name1;
    console.log("Changed name = ", name); // `name` is undefined!
    return name;
  };
  return Animal;
})();
```

So I checked how this type of code was converted to JS for the past releases.

```coffee
fn = (@name) ->
  console.log name
```

Compiles to:

* From 0.9.5 (released on the Nov 22, 2010) to 1.8.0 (released on the Aug 27, 2014). `@name` becomes `name`.

```js
// v0.9.5 to 1.8.0
var fn;
fn = function(name) {
  this.name = name;
  return console.log(name);
};
```

* At version 1.9.0 (30 Jan 2015). *`@name` becomes `_at_name`*

```js
// v1.9.0
var fn;
fn = function(_at_name) {
  this.name = _at_name;
  return console.log(name);
};
```

* At version 1.9.1 (19 Feb 2015). *`@name` becomes `name1`*

```js
// v1.9.1
var fn;
fn = function(name1) {
  this.name = name1;
  return console.log(name);
};
```

As you can see, converting `@varName` to `varName` was a fairly constant behaviour for more than 4 years (a very long time in the IT world).
It's not surprising that many developers relied on this compiler behaviour.

So what was the reason for this change in the first place?
It would help understanding the big picture for everyone.

And more importantly, would you consider reverting this change?

**Comment by lydell** [comment]
Please look at #3318 (and the issue it links to) as well as https://github.com/jashkenas/coffeescript/issues/3891#issuecomment-88740738.
