### ISSUE TITLE
Conditional object keys

### ISSUE THREAD

**Issue by connec** [jashkenas/coffeescript#3928]
This feels like something that will have come up before, but I couldn't find anything.

It is sometimes important to distinguish between a null/undefined key and a missing key in an object.  When using such APIs, you often want to conditionally add keys to an object, which currently has to be done by creating the object, then setting the keys conditionally.

```coffee
o = {}
o.key1 = 'value' if condition
o.key2 = 'value' unless condition
```

Now that we have dynamic object keys, I wonder if we could (and should?) add conditional object keys, as the savings are basically the same:

```coffee
o =
  key0: 'value'
  key1: 'value' if condition
  key2: 'value' unless condition

# More weird

o =
  key0: 'value'
  if condition then key1: 'value' else key2: 'value'

o =
  key0: 'value'
  if condition
    key1: 'value'
  else
    key2: 'value'

o = {
  if condition
    key0: 'value'
    key1: 'value'
}
```

This would compile to something like:

```js
var o, obj;
o = (
  obj = {},
  obj.key0 = 'value',
  (condition ? obj.key1 = 'value' : void 0),
  (!condition ? obj.key2 = 'value' : void 0),
  obj
)

o = (
  obj = {},
  obj.key0 = 'value',
  (condition ? obj.key1 = 'value' : obj.key2 = 'value'),
  obj
)

o = (
  obj = {},
  obj.key0 = 'value',
  (condition ? obj.key1 = 'value' : obj.key2 = 'value'),
  obj
)

o = (
  obj = {},
  obj.key0 = 'value',
  (condition ? obj.key0 = 'value', obj.key1 = 'value' : void 0),
  obj
)

o = (
  obj = {},
  (condition ? (obj.key0 = 'value', obj.key1 = 'value') : void 0),
  obj
)
```

This is similar to how class bodies work.

I'm struggling to come up with a concise, relatable use-case, but this is definitely something I've wanted to do before.

**Comment by epidemian** [comment]
Nice idea, but i personally find APIs that make a distinction between a property being undefined and it not being a key in the object *very* unfriendly to use. I don't think CS should provide a special syntactical form for this if the only use case are user-unfriendly APIs.

**Comment by adamdanielsdesign** [comment]
@connec try
```
a = [1,null] #list of json perhaps
o =
  key0: if a[0] then a[0] else 'is null'
alert o.key0
```

**Comment by adamdanielsdesign** [comment]
@connec Try
```
a = [1,null]
o =  {}
o['key0'] = a[0] if a[0] != null
alert o.key0
```

**Comment by connec** [comment]
Huh?  I know you can use conditionals in the normal way, this is about moving the conditions inside the object definition, to avoid typing the temporary `o = {}` and returning `o` afterwards.

At any rate, I don't think this is really worth having for the limited use cases.

**Comment by adamdanielsdesign** [comment]
@connec 
```
#try
o = (-> return {
  a: 1 if true
})()
```

**Comment by adamdanielsdesign** [comment]
@connec 
```
#suppose this would be the current method
a = [null,1]
o = {}
o['key0'] = a[0] if a[0] != null && a[0] != 'undefined'
o['key1'] = a[1] if a[1] != null && a[1] != 'undefined'
(delete o[k] if o[k] == null || o[k] == 'undefined') for k of o 
alert k for k of o
```

**Comment by connec** [comment]
Yes, though I think you mean `undefined` (without quotes), and CoffeeScript has the `?` postfix to check for null and undefined (e.g. `o.key0 = a[0] if a[0]?`).  Also there's no need to `delete` if you're already assigning the keys conditionally.

**Comment by adamdanielsdesign** [comment]
@connec tx! edited, saves a bit of code. 
it was actually sort of surprising that coffeescript didn't already have this functionality.
seems like it wouldn't take much to add it into the key parsing area of the compiler.
