### ISSUE TITLE
Inconsistency in the compilation process

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [jashkenas/coffeescript#3932]
Hello,

I think I found an inconsistency while compiling the existencial operator `?`

Here are two examples : 

```coffeescript
console.log "yes" if test?
```
compiles to : 
```javascript
if (typeof test !== "undefined" && test !== null) {
  console.log("yes");
}
```
(which is what is expected)

But now if I add a statement (that should do nothing) 

```coffeescript
test = ({a : 1}).b
console.log "yes" if test?
```
I get 
```javascript
var test;
test = {
  a: 1
}.b;
if (test != null) {
  console.log("yes");
}
```

I think the compiler try to do static check (ie test is declared then it cannot be undefined so we don't need to check it). In my opinion this is really a bad idea in this case. What's your opinion ?

Best,

Guillaume Leclerc

**Comment by vendethiel** [comment]
My opinion? Search and Wiki (FAQ) are underrated features :).
