### ISSUE TITLE
Lexer: Missing `then` doesn’t trigger nearby error

### ISSUE THREAD

**Issue by jcmf** [jashkenas/coffeescript#3933]
I was recently trying to compile a syntactically invalid CoffeeScript program, and the resulting compiler error was not as helpful as I'd hoped.  Here's a boiled-down example:

```
% cat test.coffee 
for x in y do ->
  foo()
console.log 'baz'
% coffee test.coffee
test.coffee:3:1: error: unexpected newline
console.log 'baz'
^
% coffee --version
CoffeeScript version 1.9.1
```

The syntax error in `test.coffee` is that it's missing a `then` -- if I instead write `for x in y then do ->` it works fine.

When I first encountered this problem, the loop was quite long and nested, and the error was flagged quite far from where the problem occurred.  I started commenting out lines in the middle of the loop, and started seeing "unexpected indentation" errors attributed to comment lines:

```
% cat test2.coffee                       
do ->
  for x in y do ->
    foo()
#    bar()
#    baz()
console.log 'qux'
% coffee test2.coffee
test2.coffee:5:11: error: unexpected indentation
#    baz()
          ^
```

I found this very surprising, so I figured I'd send a bug report, in case this sort of thing is useful to know about.

**Comment by lydell** [comment]
I think the problem can be reduced down to:

```
$ coffee -bpe 'for a in b
c'
[stdin]:1:11: error: unexpected newline
for a in b
          ^
```

**Comment by danschumann** [comment]
Why are you using `do` like that?  Is it to wrap the for loop in a closure?

I usually use `do` in the unintended way of self invoking a function during definition ( for recursion )

```
pages = {
  layout: '<html>{inner}</html>',
  index: '<body>HI</body>',
}

HTML = do makePage = ( page = 'layout' ) ->
  str = pages[page]
  _.each str.match(/{(\w+)}/g)?[1..], (m, n) =>
    str = str.replace /{(\w+)}/, makePage pages[m[1...]]
  str
```

```
var HTML, makePage, pages;

pages = {
  layout: '<html>{inner}</html>',
  index: '<body>HI</body>'
};

HTML = (makePage = function(page) {
  var ref, str;
  str = pages[page];
  _.each((ref = str.match(/{(\w+)}/g)) != null ? ref.slice(1) : void 0, (function(_this) {
    return function(m, n) {
      return str = str.replace(/{(\w+)}/, makePage(pages[m.slice(1)]));
    };
  })(this));
  return str;
})('layout');
```
