### ISSUE TITLE
Existential operator broken?

### ISSUE THREAD

**Issue by TimHugh** [jashkenas/coffeescript#3934]
Noticed this issue locally (coffee version 1.9.1), and checked the live REPL on the site to confirm:

The documentation seems to indicate that `0?` should be expressed as `(typeof 0 !== "undefined" && 0 !== null)`, but the actual output is just `0 != null`. Am I missing something here?

![screen shot 2015-04-09 at 10 02 28 am](https://cloud.githubusercontent.com/assets/1452403/7072310/1784bf80-dea0-11e4-9a49-95b9fda4e0e1.png)

**Comment by michaelficarra** [comment]
There are countless duplicates of this issue.

**Comment by jashkenas** [comment]
> Am I missing something here?

Yes ;)

**Comment by TimHugh** [comment]
Whoops. Accidentally searched open issues, not closed ones.

Get it now. Thanks, guys
