### ISSUE TITLE
Conditional Throwing

### ISSUE THREAD

**Issue by Gaelan** [jashkenas/coffeescript#3936]
Feature/Syntax Idea:
```coffee
throw foo?
```
Compiles to:
```js
if (foo != null) {
  throw foo
}
```

**Comment by Gaelan** [comment]
Whoops, just added description.

**Comment by michaelficarra** [comment]
This can be done with a helper.

```js
throwNonNull = x ->
  if x? then throw x
  return
```

Someone else may want to throw only if the value is truthy or only if the value is an object. Also, your proposed syntax is already taken.

**Comment by Gaelan** [comment]
My logic is that throwing a boolean is a very rare requirement, so special-casing the syntax doesn't seem like a problem to me. However, I have an alternate syntax:

```coffee
throw? foo
```

Also, my example use case is sanity-testing in node callbacks that you expect to never fail:

```coffee
doSomethingSuccessful (error) ->
  throw? error
  # ...
