### ISSUE TITLE
Homepage link on rubygems is a 404

### ISSUE THREAD

**Issue by jaredbeck** [jashkenas/coffeescript#3938]
1. https://rubygems.org/gems/coffee-script-source/versions/1.9.1.1
2. Click on "Homepage"
3. See a 404

**Comment by vendethiel** [comment]
That's on @sstephenson's side, I think.

**Comment by michaelficarra** [comment]
I think it is @josh actually. https://github.com/josh/ruby-coffee-script

**Comment by vendethiel** [comment]
Good catch, thanks @michaelficarra (and sorry @sstephenson!)

**Comment by josh** [comment]
Should be fixed next time we push a gem.

**Comment by vendethiel** [comment]
Thanks!
