### ISSUE TITLE
Changelog missing 1.9.1.1

### ISSUE THREAD

**Issue by jaredbeck** [jashkenas/coffeescript#3939]
1. Visit https://rubygems.org/gems/coffee-script-source/versions/1.9.1.1
2. See that 1.9.1.1 has been released
3. Visit http://coffeescript.org/#changelog
2. See that 1.9.1.1 is missing

Thanks!

**Comment by vendethiel** [comment]
That's internal to the gem, we don't have a 1.9.1 version (as explicit by our git tags).

**Comment by jaredbeck** [comment]
Where is the changelog for the gem?  Thanks.

**Comment by michaelficarra** [comment]
I think this is the gem: https://github.com/josh/ruby-coffee-script

**Comment by jaredbeck** [comment]
@vendethiel https://github.com/josh/ruby-coffee-script does not have a changelog, and it has disabled issues.  I don't see any way to report this issue, sorry.  I give up. :)
