### ISSUE TITLE
Option to detect unused stuff

### ISSUE THREAD

**Issue by binarykitchen** [jashkenas/coffeescript#3940]
When writing raw JS, I have linters telling me what's not used anymore. But when I compile CoffeeScript into Vanilla JS, then I cannot lint that Vanilla JS properly anymore.

Let's assume I have just this line in the file where the Dispatcher is obviously obsolete:

```coffee
Dispatcher = require('dispatcher')
```

which will get compiled into

```js
var Dispatcher;

Dispatcher = require('dispatcher');
```

The Vanilla JS linter won't tell me that the variable `Dispatcher` is not used because it's used again for the require() call`

That's something Coffee is doing and preventing me from linting the Vanilla JS properly. Hence I wonder if Coffee itself could do that job instead of the linter?

**Comment by lydell** [comment]
What linter do you use?

**Comment by binarykitchen** [comment]
the sublime linter

**Comment by epidemian** [comment]
Isn't this a linting problem? If a variable is only assigned and never referenced, i would expect a linter that warns about unused variables to complain about it.

![unused-var-lint](https://cloud.githubusercontent.com/assets/722544/7130909/2342d0ee-e24e-11e4-970f-2c2073eeff7c.png)

![unused-var-lint-coffee](https://cloud.githubusercontent.com/assets/722544/7130910/2bac17fe-e24e-11e4-864c-85ac2565dc19.png)

Font spacing issues aside, the IDEA linter seems to get this right both in JS and in CS.

If a popular JS linter is failing to warn about an unused variable in something like `function() { var a; a = 42; }` i think it would be best to improve that linter than changing the CS output so the linter likes it better. It would potentially benefit much more code :)

**Comment by lydell** [comment]
I agree. Some people declare all variables at the top of each scope and assign them later—juat like CoffeeScript—when writing JavaScript too, so improving the linter would benefit them as well.

**Comment by binarykitchen** [comment]
Hmmmm, I ll double check my sublime linter. Thx for the comments!
