### ISSUE TITLE
Invalid/Broken url in Coffescript documentation/homepage

### ISSUE THREAD

**Issue by palerdot** [jashkenas/coffeescript#3941]
The link mentioned about a blog post on Literate CoffeeScript is broken. The broken link is  [http://ashkenas.com/literate-coffeescript](http://ashkenas.com/literate-coffeescript)

The corresponding code for that broken link documentation is
https://github.com/jashkenas/coffeescript/blob/master/documentation/index.html.js#L364

**Comment by GeoffreyBooth** [comment]
Yeah I asked where this went in #4509. Removed the reference to it for now.
