### ISSUE TITLE
Bound instance method side-effect with dual-use constructor

### ISSUE THREAD

**Issue by pjeby** [jashkenas/coffeescript#3943]
Consider the following class:

```coffeescript
class Button extends React.Component

  constructor: ->
    if this not instanceof Button
      return React.createElement Button, arguments...
    else super

  onClick: =>
```

The constructor is dual-use: it can be called with or without `new`.  The class works fine, *but* every time the constructor is called without `new`, it does the equivalent of `window.onClick = bind(window.onClick, window)` as a side effect, because the generated constructor looks like this:

```javascript
function Button() {
    this.onClick = bind(this.onClick, this);
    if (!(this instanceof Button)) {
      return React.createElement.apply(React, [Button].concat(slice.call(arguments)));
    } else {
      Button.__super__.constructor.apply(this, arguments);
    }
  }
```

ISTM that bound instance methods should only be bound when the constructor is invoked with `new`, in order to avoid patching whatever random `this` is in effect.  So, the constructor whould look more like this:

```javascript
function Button() {
    if (this instanceof Button) {
      this.onClick = bind(this.onClick, this);
    }
    // ... rest of constructor here
  }
```

That is, with the binding of bound instance methods should be wrapped in an `instanceof` check.

**Comment by jashkenas** [comment]
CoffeeScript constructors should not be called without `new`. Simple.
