### ISSUE TITLE
Jison file?

### ISSUE THREAD

**Issue by ccorcos** [jashkenas/coffeescript#3945]
[This wiki](https://github.com/zaach/jison/wiki/ProjectsUsingJison) says Coffeescript is using jison to compile from coffeescript to javascript. Where is this jison file?

Thanks

**Comment by lydell** [comment]
https://github.com/jashkenas/coffeescript/blob/master/src/grammar.coffee

**Comment by ccorcos** [comment]
Thanks! This is so overwhelming. Not to mention the recursive inception of coffeescript from coffeescript

**Comment by jashkenas** [comment]
> Not to mention the recursive inception of coffeescript from coffeescript

I know!

For a nicely formatted version, check this out: http://coffeescript.org/documentation/docs/grammar.html

**Comment by ccorcos** [comment]
Honestly, I wish I had any idea how this works...
