### ISSUE TITLE
Useful return value for `delete`

### ISSUE THREAD

**Issue by gampleman** [jashkenas/coffeescript#3948]
Can 

``` coffeescript
a = delete b.c
```

compile to

``` javascript
var a;
a = b.c;
delete b.c;
```

**Comment by vendethiel** [comment]
(for the record, this works in coco/livescript)

**Comment by michaelficarra** [comment]
How would one get the result of the `delete` operation? This operator has effects *and* produces a meaningful value.

**Comment by jashkenas** [comment]
I believe this has been suggested before?

**Comment by vendethiel** [comment]
I thought so, but I couldn't find it.

@michaelficarra [here](https://github.com/satyr/coco/wiki/additions#pluck-v--delete-op)'s how coco's doing it.

**Comment by gampleman** [comment]
While the value might be meaningful, it's not particularly useful. As far as I can tell from the docs, it basically does the same thing as the `own` operator. Whereas I would argue that the idiom of:

~~~coffeescript
myApi = (options = {}) ->
  behavior = delete options.behavior
  doSomething(behavior).then(delegate options)
~~~

is fairly common.

**Comment by DylanPiercey** [comment]
+1
Would be awesome with #3956.

**Comment by GeoffreyBooth** [comment]
Closing as this hasn’t attracted much interest. A pull request would be considered.
