### ISSUE TITLE
Add sugar for private object properties using Symbol

### ISSUE THREAD

**Issue by GabrielRatener** [jashkenas/coffeescript#3950]
Using `Symbol()` in ES6, one can have properties on objects that are only accessible from certain scopes.

The JS syntax feels a bit ugly for this:
```
var objWithPrivateProperties = (function(){
	var symbols = {};

	function priv(name) {
		if (!(name in symbols)) {
			symbols[name] = Symbol();
		}

		return symbols[name];
	}

	return {
		getValue: function() {
            // powerfull functionality yet nasty syntax
			return this[symbols.value];
		},
		[priv("value")]: 55
	}
}());
```

I am uncertain of what syntax CS should use for this, but it really seems CS should provide sugar for this, as privacy is critical on the web. Any thoughts?

**Comment by lydell** [comment]
I think you might be interested in this blog post: http://fitzgeraldnick.com/weblog/53/.

I don’t think anything like this is likely to be added in CoffeeScript. See https://github.com/jashkenas/coffeescript/issues/3597#issuecomment-72745401 and https://github.com/jashkenas/coffeescript/issues/3832#issuecomment-73303121.

**Comment by GabrielRatener** [comment]
It is not clear to me why @jashkenas would be opposed to the use of symbol's for privacy, but it appears that he is based on the first post. On the web, where XSS attacks are a very real problem, making privacy easy seems like a no brainer.

In such a case isn't using symbols much simpler than pulling private objects out of a weakmap?

**Comment by michaelficarra** [comment]
@GabrielRatener 

0. How does this help prevent XSS?
0. Remember that symbol keys are not private due to `Object.getOwnPropertySymbols`.
0. Why do we need special syntax for this pattern if we can do this with just computed property names?

**Comment by GabrielRatener** [comment]
@michaelficarra Ouch, Was not aware of #2! In that case, using symbolic properties does nothing to prevent XSS attacks. Too bad, hiding through closures has its drawbacks.

**Comment by vendethiel** [comment]
Since @jashkenas recently said we aren't going to support Symbol stuff, I'll close this one.

( https://github.com/jashkenas/coffeescript/pull/4003#issuecomment-129554995 )
