### ISSUE TITLE
Moving directives to the top of the function

### ISSUE THREAD

**Issue by tomca32** [jashkenas/coffeescript#3951]
Would it be possible to always move directives such as "use strict" and "ngInject" from ng-annotate to the top of the function?

My use case is with Angular and ng-annotate. I need to annotate the dependency injection and in some cases the only way to do that is to use the "ngInject" directive as the first line in the function. However with the @parameters to the constructor, it's impossible to do so. [Example](http://coffeescript.org/#try:class%20SomeClass%0A%20%20constructor%3A%20%28%40a%2C%20%40b%29%20-%3E%0A%20%20%20%20%22ngInject%22%20%23this%20needs%20to%20be%20the%20first%20line%20in%20the%20constructor%20to%20properly%20inject)

**Comment by bchociej** [comment]
The workaround is pretty reasonable, IMO:

```coffeescript
class MyClass
  constructor: (a, b) ->
    'use strict'
    @a = a
    @b = b
```

I will admit it's a little bit of a hassle that could be cleaned up in the language. Frankly, I have no opinion on whether the sugar should be implemented; I'm just here to discuss the feasibility.

That said, if this were to be implemented, it'd be necessary to disambiguate that from a function returning "use strict", for example. Here are some possibilities to chew on. Again, I'm not invested in any particular choice.

```coffeescript
class MyClass
  constructor: (@a, @b) ->
    ^use strict

class MyClass
  constructor: (@a, @b) ->
    :'use strict'

class MyClass
  constructor: (@a, @b) 'use strict' ->

class MyClass
  constructor: (@a, @b) ->
    directive 'use strict'
```

I suppose you could also make the argument list construction implicit unless it's explicitly called for:

```coffeescript
class MyClass
  constructor: (@a, @b) ->
    'use strict'
    @constructor # argument list gets converted here
```

**Comment by GeoffreyBooth** [comment]
In CS2 we compile to ES classes, which enable strict mode automatically.
