### ISSUE TITLE
Reserved word "long" as class parameter - wrong compiling

### ISSUE THREAD

**Issue by VladislavSournine** [jashkenas/coffeescript#3954]
Source code: 
```
class Some 
  let: 1
  static: 2
  long:2
```
We got:

```
var Some;

Some = (function() {
  function Some() {}

  Some.prototype["let"] = 1;

  Some.prototype["static"] = 2;

  Some.prototype.long = 2;

  return Some;

})();
```

And have problem with obfuscating in Some.prototype.*long*

**Comment by vendethiel** [comment]
Long isn't a reserved JS word, that's why it doesn't use the brackets. This is in our FAQ.

**Comment by VladislavSournine** [comment]
Ok.
http://www.w3schools.com/js/js_reserved.asp

**Comment by vendethiel** [comment]
Seems like I was mistakenly led to believe those were ES4 keywords! I stand corrected. Are they protected in any runtime, though? One problem I'm thinking of is that adding this as a reserved JS keyword will disallow assigns to it, and that might break code in the wild...

**Comment by connec** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) gives a bit more information about this.  In particular, `long`, `int`, etc. are listed as "Future reserved keywords in older standards ES [1-3]".  

I guess if CS is supposed to target ES3 it should respect the reserved words of that revision -- or, it could drop ES3 support :o
