### ISSUE TITLE
Destructuring in delete? (Feature request)

### ISSUE THREAD

**Issue by rill-js** [jashkenas/coffeescript#3956]
I understand that the "delete" keyword isn't very efficient and whatnot but it would be nice if it was a little more usable for bulk deletes.

I was thinking something like:

``` coffeescript
delete obj { x, y, z } 
```

Could become:

``` javascript
delete obj.x;
delete obj.y;
delete obj.z;
```

It would also be handy if it kept the references to these values so that you could destructure an object and also remove the values from it like so:

``` coffeescript
delete {x, y, x} = obj
```

``` javascript
var x = obj.x, y = obj.y, z = obj.z;
delete obj.x;
delete obj.y;
delete obj.z;
```

Alternatively we could allow the delete keyword inside of the destructing for more explicit deletes:

``` coffeescript
{delete x, y, x} = obj
```

``` javascript
var x = obj.x, y = obj.y, z = obj.z;
delete obj.x;
```

Any thoughts?
### Edit - Better syntax

``` coffeescript
delete { x, y, z } of obj

# -->
delete obj.x;
delete obj.y;
delete obj.z;
```

As mentioned below.

**Comment by vendethiel** [comment]
This exists in Coco(/LS), and is called [unary spread](https://github.com/satyr/coco/wiki/additions#unary-spread-a-b) (though the syntax uses `[]` as it should). I'm not sure what's wrong with `delete[k] for k in ['x', 'y', 'z']` though?

**Comment by rill-js** [comment]
@vendethiel Interesting. As far as using a loop goes I was simply thinking that it would be convenient syntactic sugar that would be more efficient than using a loop.

**Comment by JamenMarz** [comment]
+1

```
delete {x, y, x} = obj 
```
This option looks the most most correct in my opinion...

Because,
```
delete obj {x, y, x}
```
at first glance would appear that you're deleting the object...  Although it would work, just looks different from how object destructuring is usually done.

And,
```
{delete x, y, x} = obj
```
That appears like you're deleting only `x`...

So I vote on `delete {x, y, x} = obj `

**Comment by DylanPiercey** [comment]
On second thought maybe the

```coffeescript
delete {x, y, z} = obj

# -->
var x = obj.x, y = obj.y, z = obj.z;
delete obj.x;
delete obj.y;
delete obj.z;
```

Is a little unclear since it may read like you are deleting the values before pulling them from obj.
I would suggest this instead:

``coffeescript
delete { x, y, z } obj
# or (reads more like coffeescript)
delete { x, y, z } of obj
```

Which would simply become:

```javascript
delete obj.x;
delete obj.y;
delete obj.z;
```

**Comment by JamenMarz** [comment]
I agree with Dylan,  `delete {x, y, z} of obj` seems more like plain English and makes more sense in the context of what the issue here is trying to do.

**Comment by GeoffreyBooth** [comment]
I think [this is good enough](http://coffeescript.org/v2/#try:delete%20obj%5Bkey%5D%20for%20key%20of%20obj%20when%20key%20in%20%5B'a'%2C%20'b'%2C%20'c'%5D):

```coffee
delete obj[key] for key of obj when key in ['x', 'y', 'z']
```
___
```js
var key;

for (key in obj) {
  if (key === 'a' || key === 'b' || key === 'c') {
    delete obj[key];
  }
}
```
But if someone wants to take the time to implement an even shorter syntax, feel free to submit a PR.
