### ISSUE TITLE
Consecutive switches don't return properly

### ISSUE THREAD

**Issue by bcherny** [jashkenas/coffeescript#3957]
```coffee
foo = (bar, baz) ->

  switch bar
    when 1 then 1
    when 2 then 2

  switch baz
    when 3 then 3
    when 4 then 4
```

compiles to

```js
var foo;

foo = function(bar, baz) {
  switch (bar) {
    case 1:
      1;
      break;
    case 2:
      2;
  }
  switch (baz) {
    case 3:
      return 3;
    case 4:
      return 4;
  }
};
```

`1` and `2` should be `return`ed.

**Comment by vendethiel** [comment]
No, obviously not. It'd prevent getting to the `baz` case if `bar` matched, which is incorrect, and to start with -- it's the last expression in a block that gets returned.

The easiest solution for you is probably a topicless switch (bare `switch` with `when baz == 1`)
