### ISSUE TITLE
Documentation: %% modulo is not 'true mathematical modulo'

### ISSUE THREAD

**Issue by xixixao** [jashkenas/coffeescript#3959]
The website says that `%% provides true mathematical modulo`. This is not the case, %% provides **dividend dependent modulo**, see http://en.wikipedia.org/wiki/Modulo_operation . True mathematical modulo would always be positive - http://en.wikipedia.org/wiki/Remainder (well, maybe "mathematical modulo" is a misnomer). Good news is I wrote it :sob: .

**Comment by michaelficarra** [comment]
I think it's fine; `%%` is modulo and `%` is remainder. Were you just looking to remove the words "true mathematical"?

**Comment by xixixao** [comment]
Yes, it's misleading. I wouldn't say `%% is modulo and % is remainder` either (maybe other way around, but apart from **divident dependent modulo** there is no clear name for it). Not sure what's the best and shortest way to explain it.

**Comment by epidemian** [comment]
> Not sure what's the best and shortest way to explain it.

Maybe show a case where where `%` and `%%` differ?:

```coffeescript
-7 % 5 == -2 # The reminder of 7 / 5
-7 %% 5 == 3 # n / 5 is always between 0 and 4
```
