### ISSUE TITLE
Marking a value for returning

### ISSUE THREAD

**Issue by Aarilight** [jashkenas/coffeescript#3960]
I write code like this pretty frequently:

```
foods = ['broccoli', 'spinach', 'chocolate']
result = for food in foods 
   "some " + food
```

Often there are things I need to do after I create the value. Unfortunately, the syntactic sugar stops there. =(

```
foods = ['broccoli', 'spinach', 'chocolate']
result = []
for food in foods 
   result.push "some " + food
   eat food
```

I propose a new keyword which marks a value as to be one of the values to be 'returned' at the end of the loop. I would have given it the name `yield`, but that's already taken. =P 

```
foods = ['broccoli', 'spinach', 'chocolate']
result = for food in foods 
   demit "some " + food
   eat food
```

This compiles into this javascript:

```
var food, foods, result;

foods = ['broccoli', 'spinach', 'chocolate'];

result = (function() {
  var i, len, results;
  results = [];
  for (i = 0, len = foods.length; i < len; i++) {
    food = foods[i];
    results.push("some " + food);
    eat(food);
  }
  return results;
})();
```

Basically, all the keyword does is add a hook into the compiled variable `results` so that the loop can add to it whenever it likes.

**Comment by bcherny** [comment]
i'm not sure how useful this feature is. i would rewrite your code instead:

```coffee
foods = ['broccoli', 'spinach', 'chocolate']
result = foods
  .map (_) -> "some #{ _ }"
  .forEach eat
```

**Comment by Aarilight** [comment]
For one, it's harder to read that code, and for two, it doesn't even do the same thing. You're `eat`ing from `result`, but it's supposed to `eat` from the base array `foods`. Thirdly, it's not as performant: I believe there would be two loops going there behind the scenes when it really only should take one; you're using the same values twice.

The most recent time I encountered a need for this is writing a compiler for a language.

    arr = until @next @punctuation.array.close, false
        demit @value()
        @next @punctuation.value.end

What this code would do is loop until the next characters in the input are equivalent to the symbol for an array closing (`}`), and inside the loop it would run the code to get a 'value' next (like, a string, or a number). Afterwards it requires the next characters are equivalent to `punctuation.value.end`, which is `;`.

I was trying not to do an example too confusing in my first post, but I can't think of a better one. 

Without demit, the cleanest solution is this:

    arr = until @next @punctuation.array.close, false
        val = @value()
        @next @punctuation.value.end
        val

However, that doesn't give you access to the results as nicely as `demit` would. You can't push to the result multiple times, for example. Also, it makes an unnecessary variable. I mean, seriously, this is just silly code:

    val = this.value();
    this.next(this.punctuation.value.end);
    results.push(val);

Some other, hacky alternatives:

    arr = until @next @punctuation.array.close, false
        `results.push(this.value())`
        @next @punctuation.value.end
        continue

    arr = []
    until @next @punctuation.array.close, false
        arr.push this.value()
        @next @punctuation.value.end

The last one is without a doubt the best solution, but I'm not sure about the repercussions of removing the function wrapper from the loop. I don't think there are any. (Besides good ones that come from the probably insignificant processing time shrinkage). I'm hoping for this to become a feature, but if it doesn't, I'll probably stick with the last one. =P

**Comment by Aarilight** [comment]
It'd make sense if `demit` was used as a sort of lazy `return`. Basically, it would wait as long as possible before `return`ing the value. In a loop, `demit` would save the variable to the result array, while in another construct, like, `if`, `demit` would return the value given to it after the end of all the other code.

    value = if true
        demit "hello"
        do_some "other stuff"

Compiled:
  
    var value;
    value = true ? (result = "hello", do_some("other stuff"), result) : void 0;

If there were more than one, all it would do is replace the value to be `demit`ed.

    value = if true
        demit "hello"
        demit "world"
        do_some "other stuff"

    var value;
    value = true ? (result = "hello", result = "world", do_some("other stuff"), result) : void 0;

    // value: "world"

**Comment by vendethiel** [comment]
Seems to complicate control flow a lot for not much. There are several alternatives that could be added to Coffee (if deemed necessary -- the use case isn't quite be enough a justification for me).

The alternative that already exists in coco/LS as `with` is a [`prog1`](http://clhs.lisp.se/Body/m_prog1c.htm):

```livescript
x = with value
  call(..) # in LS, .. represents the value
  call(&) # in Coco, & represents the value
# x is value
```

**Comment by epidemian** [comment]
Sorry, but i don't think this addition is worth the increased syntax complexity.

The first given example mixes a loop with side effects and an array comprehension unnecessarily. It's much clearer to write this as two separate steps, and the algorithm is still *O(n)*:

```coffeescript
foods = ['broccoli', 'spinach', 'chocolate']
eat food for food in foods
result = ("some #{food}" for food in foods)
```

And about the second example, as you said, the version that explicitly initializes `arr = []` and collects the values as `arr.push @value()` is probably the best one, as it clearly shows the intention of the code: "i want to collect these values *before* calling `@next @punctuation.value.end`".

But i think there's nothing wrong with the array comprehension version that does `val = @next(); @next @punctuation.value.end; val` as the loop body, as it also communicates the same same meaning quite clearly: "`val` is the value before advancing to the next end value, and i want to collect those values into `arr`". If you think it in terms of the generated JS code then, yes, the `val` variable seems silly. But looking at the CS code and thinking it as an array comprehension –a higher-level construct than manually constructing an array via `Array#push`– the `val` variable makes sense as a holder of the value that you want to collect in the final array.

So, unless a more convincing use-case is shown, i don't that adding a new keyword just for indicating which value inside a comprehension is worth the cost of increased language complexity. A plain-old variable can serve the same purpose just fine. And i prefer a language with fewer but more applicable constructs than one with many different but very case-specific constructs :smiley:
