### ISSUE TITLE
[Feature Request] Allow `if "propName", propVal of object`

### ISSUE THREAD

**Issue by mrapogee** [jashkenas/coffeescript#3964]
Compile this:
```
if 'propName', propVal of object
   ...
```

to:
```
if ( 'propName' in object ) {
  var propVal = object['propName'];
  ...
}
```
This way, it would be consistent with the ```for propName, propVal of object``` syntax. What do you think?

**Comment by lydell** [comment]
There’s `if CONDITION` and `for ASSIGNABLE in EXPRESSION`. They are not the same thing, and therefore I don’t think you can propose something in order for them to be consistent.

Speaking of consistency, wouldn’t that be inconsistent with `if a in b` vs `for a in b`?

Also, if anything I’d expect `if 'propName', propVal of object then` to compile to `if ('propName' in object && object['propName'] === propVal) {}`.

I don’t see how your suggestion is any better than:

```coffee
if 'propName' of object
  propVal = object.propName
  ...
```

**Comment by michaelficarra** [comment]
This adds complexity for basically no gain. Use the pattern suggested by @lydell.
