### ISSUE TITLE
Placeholder syntax

### ISSUE THREAD

**Issue by lydell** [jashkenas/coffeescript#3972]
This has been discussed _lots_ before, so I’m not going to repeat the background here. Please start by reading https://github.com/jashkenas/coffeescript/issues/3449#issuecomment-40889556 and follow the links from there.

The whole thing is about being able to skip values that you don’t care about, instead of assigning them to variables that will never be used. For example:

```coffee
[match, raw, quote, contents] = code.match /(r?)(["'])(.*?)\2/
doSomethingWith contents, {raw}
```

In the above code, we’re only interested in the`raw` and `contents` variables, but have to name the others as well to get them. Ok, there is a “hack” you can use: `[[], raw, [], contents] = foo`. But that’s super ugly. Earlier proposals have suggested adding a one-character placeholder syntax, such as: `[?, raw, ?, contents] = foo`. That’s a tiny bit prettier, but it is still quite cryptic. The crypticness is what have shot down the previous tickets.

```coffee
someFunc (?, ?, ?, foo, ?, bar) ->
  # wtf are those `?`s ???
```

The solution? Let’s do the best of both worlds!

I propose using `&` as a placeholder character (I’m not married to that choice, but let’s use it for now). That would allow me to write my initial example as:

```coffee
[&, raw, &, contents] = code.match /(r?)(["'])(.*?)\2/
doSomethingWith contents, {raw}
```

That’s in no way any clearer than using `[]`, `{}` or `?` as a placeholder, but it should be allowed. Now comes the cool part: Optionally you may append an identifier after the `&`. It makes no difference at all, except that it lets you have the best of both naming variables and skipping them with placeholders.

```coffee
[&match, raw, &quote, contents] = code.match /(r?)(["'])(.*?)\2/
doSomethingWith contents, {raw}
```

Here’s another example:

```coffee
Object.values = (obj) -> (value for own &key, value of obj)
```

It could also be used to deprecate the `for [a..b]` syntax: `for & in [a..b]`.

These placeholders would be allowed in any destructuring, as parameters of a function (callbacks) and in the assignment part of `for` loops. Also in `catch` to be consistent (although it is quite useless to do so there, since assigning the error is already optional). It might even make sense to allow placeholders in regular assignment, if you want to make it really explicit that you execute a function for its side effects and don’t care about the return value, for example: `&length = array.push 5`.

About the `&` character: I know that `&` already is a bitwise operator. But I don’t think there’s any conflict.

---

But why stop there? These placeholders could be used for … _partial application_ as well!

An argument against partial application is that it can make code cryptic, just like in the above examples. But, again, that is mitigated by naming your placeholders:

```coffee
process.argv[2..]
  .map fs.readFileSync &file, encoding: 'utf8'
  .forEach doSomething
```

Note that this partial application makes the function accept _exactly_ that many arguments, and no more. This replaces the old `single = (fn) -> (arg) -> fn arg` helper:

```coffee
['10', '11'].map parseInt # [10, NaN]
['10', '11'].map single parseInt # [10, 11]
['10', '11'].map parseInt &num # [10, 11]

text.split('\n').map(chalk.red).join('\n') # Oops! `chalk` colors _all_ of its arguments!
text.split('\n').map(chalk.red &line).join('\n') # That’s better.
```

If you want a partially applied function to take any number of arguments you may use `...`:

```coffee
min = Math.min defaultMinValue, ...
asyncMin = AsyncMath.min ..., (value) -> console.log value
```

---

But why stop there? The lack of partial application has been a reason that the `|>` and `<|` piping operators (which exist in LiveScript for example) that have been requested many times have been rejected, because without partial application those operators would only work if the functions in the pipe only take one argument. Perhaps they could be reconsidered?

```coffee
compiled = compile(parse(tokenize code, loc: true), bare: true)
compiled = tokenize code loc: true |> parse &tokens |> compile &ast, bare: true

setTimeout &callback, 1000 <| ->
  alert 'One second has passed!'
```

A note about the `&` bitwise operator: The above would make it behave like the `+` operator:

```
a+b → a + b
a&b → a & b
a +b → a(+b)
a &b → a(&b)
a+ b → a + b
a& b → a & b
a + b → a + b
a & b → a & b
```

What do you all think?

**Comment by vendethiel** [comment]
I think that `&` doesn't carry any meaning like that. Having a variable both named and "excluded" feels wrong to me, but I also know several proposals were shot down **because** the skipped variables were unnamed.

Maybe this proposal contains a *bit* too much in it?

**Comment by lydell** [comment]
> Maybe this proposal contains a bit too much in it?

Well, my post above has three sections, ordered by importance. I think that at least the first section should be reasonable.

**Comment by michaelficarra** [comment]
I'd prefer to align with ES6, which would use elision (`[,,,a] = b`) or empty destructuring targets (`[{}, {}, {}, a] = b`) for placeholders. We already allow the latter (as you mentioned); we can add support for the former.

There was also a similar partial application proposal for ES6, but it was shot down because it's so easy and succinct to use an inline arrow for this purpose. I tend to agree with them about this. Partial application is far from the most bothersome omission in CoffeeScript.

I'm not compelled by either proposal, and it is not helped by overloading the `&`. :confused:

**Comment by vendethiel** [comment]
Problem with elision is that people get confused on `[a]` vs `[a,]` vs `[a,,]`

**Comment by michaelficarra** [comment]
Yeah, I know :disappointed:. It's unquestionably a bad feature, but it has precedent. I could go either way on it.

**Comment by tigerhawkvok** [comment]
I think this idea -- maybe, though, instead of `&`, which would be overloaded, a standalone `.`?

It has an analog as the "this matches anything" character in regular expressions, so it being the any-throwaway-character here could be a logical extension. (Though I do kind of like the "reading" of `&`).

So, `[a,.,.] =  b` would be the  syntax.

**Comment by lydell** [comment]
But that does not look so good when appending the optional comment identifier, does it?

```coffee
[.match, raw, .quote, contents] = str.match regex

process.argv[2..]
  .map fs.readFileSync .file, encoding: 'utf8'
```

**Comment by jashkenas** [comment]
Placeholders + partial appliation + pipelining is a very interesting proposal ... But I'm **strongly against** named placeholders. Either a thing has a name or it doesn't. In-syntax "comments" would be gross.

**Comment by lydell** [comment]
Ok, named placeholders was the whole thing about this proposal. Closing.

**Comment by jashkenas** [comment]
Thanks, @lydell. Lovely writeup. Good show.
