### ISSUE TITLE
Expose default options to compile() in coffee-script.coffee

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#3977]
Plain and simple: I'm wrapping the coffeescript extension handler in node and I can't get access to the options that are passed to `compile()` in `_compileFile`:

https://github.com/jashkenas/coffeescript/blob/master/src/coffee-script.coffee#L187

I would have wrapped the exported `compile()` but `_compileFile()` uses a local `compile()` reference, not `exports.compile`.  It would be very helpful if I could affect changes in the default options `compile()` uses if they were exported.

Something to change around here:

https://github.com/jashkenas/coffeescript/blob/master/src/coffee-script.coffee#L43

I would appreciate hearing any suggestions - my task at the moment is wrapping the coffeescript extension handler, not duplicating its source.  I feel like exposing default compile() options would be very flexible.

(thanks for reading)

**Comment by GeoffreyBooth** [comment]
If you’d like to submit a PR to achieve this, it would be welcomed. It should start after #4501 as its baseline.
