### ISSUE TITLE
highlight.js github repo is missing on build

### ISSUE THREAD

**Issue by rwdim** [jashkenas/coffeescript#3981]
bower highlight.js#~8.0.0      ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/danielditgens/highlight.js.git", exit code of #128 fatal: remote error:    Repository not found.

**Comment by michaelficarra** [comment]
What command are you running? It looks like you're installing dependencies through bower?

**Comment by olleicua** [comment]
I got the same error:

```
$ git clone git@github.com:jashkenas/coffeescript.git

$ cd coffeescript

$ bower install
bower uglify-js#~2.2        not-cached git://github.com/mishoo/UglifyJS.git#~2.2
bower uglify-js#~2.2           resolve git://github.com/mishoo/UglifyJS.git#~2.2
bower highlight.js#~8.0.0   not-cached git://github.com/danielditgens/highlight.js.git#~8.0.0
bower highlight.js#~8.0.0      resolve git://github.com/danielditgens/highlight.js.git#~8.0.0
bower underscore#~1.5.2         cached git://github.com/jashkenas/underscore.git#1.5.2
bower underscore#~1.5.2       validate 1.5.2 against git://github.com/jashkenas/underscore.git#~1.5.2
bower highlight.js#~8.0.0      ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/danielditgens/highlight.js.git", exit code of #128 fatal: remote error:    Repository not found.

Additional error details:
fatal: remote error: 
  Repository not found.
```

Are there instructions for contributers somewhere that I'm missing?

**Comment by GeoffreyBooth** [comment]
Is there a reason we have this `bower.json`? It doesn’t seem to be used.

**Comment by GeoffreyBooth** [comment]
We’ve since removed the dependencies from `bower.json` and now `bower install` doesn’t throw any errors (though it also doesn’t do anything). The file is still there for _other_ tools to use the CoffeeScript module via Bower.
