### ISSUE TITLE
foo = ({bar: foo=42}) -> fails with "c is undefined"

### ISSUE THREAD

**Issue by mitar** [jashkenas/coffeescript#3983]
```coffee
foo = ({bar: foo=42}) ->
```

fails with `c is undefined`. Probably a better error message would be needed?

**Comment by vendethiel** [comment]
Seems to fail with `Cannot read property 'length' of undefined`. I agree a better error message would be better, though :).

**Comment by mitar** [comment]
Oh, I tried at http://coffeescript.org/ in "Try CoffeeScript". There you get the error I mentioned above.

**Comment by mitar** [comment]
(BTW, so this is not how you specify default values to keyword args? :-) )

**Comment by vendethiel** [comment]
There's no default value for properties syntax in CoffeeScript.

**Comment by lydell** [comment]
But it is proposed in #3288.

**Comment by anfedorov** [comment]
This should be closed, as it is fixed by #4069.

**Comment by vendethiel** [comment]
You're right, thanks!
