### ISSUE TITLE
Stop enforcing parameter name uniqueness

### ISSUE THREAD

**Issue by bcherny** [jashkenas/coffeescript#3986]
Currently enforced on this line - https://github.com/jashkenas/coffeescript/blob/769f02ec05c7e329a33ae0f49281457d12387324/src/nodes.coffee#L1431

This is already enforced by linters (eg. http://eslint.org/docs/rules/no-dupe-args), and is not CoffeeScript's responsibility. Instead, we should have a smarter variable naming scheme that doesn't rely on uniqueness of param names.

A side effect of enforcing this from within CoffeeScript is that pattern matching syntax doesn't work. Eg. I can't do:

```coffee
foo = (_, _, count) -> count + 1
foo(1,2,3)
```

But the above does work in JS.

**Comment by vendethiel** [comment]
Nope, the above isn't allowed in strict mode, and that's why it was disallowed in CoffeeScript.

**Comment by vendethiel** [comment]
See #1002.

**Comment by lydell** [comment]
You might also be interested in #3972 and the following syntax:

```
foo = ({}, {}, count) -> count + 1
foo = ([], [], count) -> count + 1
```

**Comment by vendethiel** [comment]
(that syntax is also mentioned [in #1002](https://github.com/jashkenas/coffeescript/issues/1002#issuecomment-1629479))

**Comment by bcherny** [comment]
thanks for the links, i didn't realize it's not allowed in strict mode!

it would be nice to make an exception for pattern matching style (transpiling `_` to non-repeated names), like what [this commenter](https://github.com/jashkenas/coffeescript/issues/1002#issuecomment-27612010) said. this style is idiomatic in many functional languages, and it would be nice to get support for it in cs.

**Comment by jashkenas** [comment]
The Party Line™ on this is that it's better to name your variables, even if you aren't going to use them. You might want to use them later, and it's better to document what they are, instead of being mystery meat free variables floating around.

**Comment by bcherny** [comment]
@jashkenas many functional languages (scala, haskell, f#, ...) disagree. param names don't tell you much about what the variable is anyway. you need docs (jsdoc/jsig/flow), type annotations, or to look at context and consumers to get a good idea of what a param is for. the name by itself is not enough to conclude much, unless it's an idiomatic param name (like `event`, or `error`).

**Comment by vendethiel** [comment]
@bcherny just as you said – you don't have those annotations in coffee.

**Comment by bcherny** [comment]
exactly. i'm arguing that param names are not usually useful otherwise.

```coffee
# useful:
# (foo: number) => number
fn = (_, bar) ->
  bar + 1

# less useful:
fn = (foo, bar) ->
  bar + 2

# equally less useful:
fn = (_, bar) ->
  bar + 1
```

**Comment by michaelficarra** [comment]
If you have so many positional parameters that you need to omit their names, it's time to use named parameters (passing an object and using destructuring).

**Comment by bcherny** [comment]
@michaelficarra that works for some cases, but does not work for composing functions that operate on lists. here's a contrived example:

```coffee
first = (a) -> a
second = (_, a) -> a
third = (_, _, a) -> a
last = (_..., a) -> a

list = [1,2,3,4,5]
first list... # 1
second list... #2
third list... #3
last list... #5
```
