### ISSUE TITLE
There is no way to avoid redeclaration of bind, indexOf, extend etc.

### ISSUE THREAD

**Issue by fracz** [jashkenas/coffeescript#3988]
Let's suppose I have the following class:

```coffee
class Something
  constructor: (@myArray) ->
  isInMyArray: (element) =>
    element in @myArray
```

It produces the following JS:

```js
var Something,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Something = (function() {
  function Something(myArray) {
    this.myArray = myArray;
    this.isInMyArray = bind(this.isInMyArray, this);
  }

  Something.prototype.isInMyArray = function(element) {
    return indexOf.call(this.myArray, element) >= 0;
  };

  return Something;

})();
```

As you know, it defines "helper" funcions like `bind`, `indexOf`, `extend`. The problem is that when I have many classes in many coffee files that use these features, resulting JS files contain definitions of these helpers many times.

Currently, I have managed it with `--join` argument that [has been deprecated](https://github.com/jashkenas/coffeescript/issues/3472).

Is there any non-deprecated way to avoid this? Now, I merge files with [`gulp-concat`](https://www.npmjs.com/package/gulp-concat) and then minifies it with Uglify, but repeated definitions of these methods are not removed.

To clarify - this does not lead to any errors in my code. I just have noticed that I spare a few precious kBs when these functions are defined only once :smirk:

**Comment by lydell** [comment]
See #1820 (especially the last comment).
