### ISSUE TITLE
Destructuring fails for certain reserved keywords

### ISSUE THREAD

**Issue by tigerhawkvok** [jashkenas/coffeescript#3991]
Try this:

```coffee
[stuff, things] = undefined
[stuff, things] = false
[stuff, things] = true
[stuff, things] = null
```

For all of those, you'd expect both `stuff` and `things` to independently equal the value on the right, but this only works for `undefined`, with the compiler returning

```javascript
var ref, stuff, things;

ref = void 0, stuff = ref[0], things = ref[1];

stuff = false[0], things = false[1];

stuff = true[0], things = true[1];

stuff = null[0], things = null[1];
```

which is illegal syntax, and will actually give all of them the value of `undefined`, always.

**Comment by michaelficarra** [comment]
This is not an invalid program. The first assignment only looks different because we're (unnecessarily) caching the undefined value.

**Comment by tigerhawkvok** [comment]
Except `false[0]` === undefined`, `true[0] === undefined`, and `null[0] === undefined` -- which is to say, the **destructuring is broken**. 

```coffee
[stuff, things] = false

console.log(stuff) # Returns undefined
console.log(stuff is false) # returns false
```

That's just WRONG.

**Comment by tigerhawkvok** [comment]
Let's one-up it:

![image](https://cloud.githubusercontent.com/assets/165937/7801760/b5e0fd94-02de-11e5-8163-156eb59c9ba4.png)

It doesn't even **compile**.

![image](https://cloud.githubusercontent.com/assets/165937/7801790/0196e438-02df-11e5-88db-d801779714f0.png)


@michaelficarra , I don't see how you can say

> This is not an invalid program

with that.

**Comment by michaelficarra** [comment]
You're looking at a runtime exception. I don't see how you can say "I don't see how you can say 'This is not an invalid program' with that" with that.

**Comment by tigerhawkvok** [comment]
o_0 but I never typed `null[0]` anywhere. `null` isn't a variable. If the compiler only wants array-type objects, it should throw an error when compiling with an invalid assignment; or, it should do 

`stuff = null, things=null`

(and `true`, etc) but it shouldn't make an array out of something that it is literally impossible to make an array of (because it's a reserved keyword) then have it fail to run.

I'm not saying that `[stuff, things] = foo` should pass this test, but for reserved keywords SOMETHING different should happen. I'm pretty sure ANY other behaviour would be more clear -- eg,

```coffee
[stuff,things] = function
```

Throws an error for a reserved word, and that'd be fine here, too.

**Comment by michaelficarra** [comment]
Because we cannot detect errors in the program

```coffee
a = if Math.random() < 0.5 then [] else null
[b] = a
```

or the program

```coffee
[a] = globalObject.a
```

then we do not bother to catch obvious errors like

```coffee
[a] = null
```

There is much precedent for this in CoffeeScript. Note that this (detecting unconditional runtime errors statically) is very different from the case you listed (a grammatical error).
