### ISSUE TITLE
Double semicolon error shouldn't happen with embedded js after compiling

### ISSUE THREAD

**Issue by CodyKochmann** [jashkenas/coffeescript#3994]
I've noticed quite often that I forget if embedded coffeescript adds a semi colon after compiling. When I guess wrong and assume that there's probably a protection for that, I end up with errors and useless semicolons laying around. 

Here's a shell script that I threw together to take care of the general issue occurring. I'm not too great with regex yet though so the situation where there is whitespaces or tabs between the double semicolons is still an issue. 

``` bash
cat compiled.js | perl -pe 's/;;/;/g' > fixed.compiled.js
```

**Comment by vendethiel** [comment]
How is that an issue?

**Comment by CodyKochmann** [comment]
It's more a suggestion to add to the compiler if you want. Sorry, I've never submitted an issue before so it seemed like the right place to donate the snippet for the common problem myself and a couple others have had. Is there a better place for this?

**Comment by vendethiel** [comment]
Sorry, I meant this part:

> I end up with errors

What kind of errors occur due to these semicolons?

**Comment by GeoffreyBooth** [comment]
A pull request that prevents the compiler from outputting redundant semicolons this would be welcome; but as they don’t appear to cause any issues, closing this as not really a bug.
