### ISSUE TITLE
Strong Script

### ISSUE THREAD

**Issue by rill-js** [jashkenas/coffeescript#3995]
https://developers.google.com/v8/experiments

Is there potential for coffeescript to eventually adhere to this standard?
Seems one of the biggest hurdles would be allowing block scoped variables.

Any thoughts on this?

**Comment by jashkenas** [comment]
> Is there potential for coffeescript to eventually adhere to this standard?

Nope. CoffeeScript compiles into regular JavaScript — not Google's flavor of the year.

Also, CoffeeScript tries to be a good dynamically typed syntax, not a faux-statically typed one.

**Comment by carlsmith** [comment]
It's was a good question, perhaps better on the mailing list. I liked the response more. As a user, it's good to know where the red lines are with your BDFL. They don't just do whatever seems like a good idea at the time.

**Comment by rill-js** [comment]
@jashkenas Thanks for the reply.

I gave this a little thought and it seems like the scopeing issue might be as simple as changing all "var" to "let" since they are defined at the top of the scope anyways this wouldn't break any existing cs.

I'm sure there are other issues (ie for of) that would make it a bit difficult to implement but I just wanted to check to see if it was something that would be considered for node js users to get better perfs.

I tend to agree with @jashkenas in that we shouldn't transform the nature of coffeescript to satisfy google but it would be cool if this was considered when potentially implementing some other new es6 features if it's a possible easy win.
