### ISSUE TITLE
Miscellaneous errors pop up when compiled coffeescript is converted to single line.

### ISSUE THREAD

**Issue by CodyKochmann** [jashkenas/coffeescript#3996]
For elements such as bookmarklet's or JavaScript that is compiled within a HTML elements onclick tag, I need the JavaScript to be a single line. So far though, every compiler that I use breaks the JavaScript once it's compiled because of syntax errors based on the assumption that the JavaScript was going to remain in that perfect syntax.

For example: 
```javascript 
return true;
// or anything in a double slashed comment
```

 Is there a compiler out there that is compiled coffee script friendly? Or is there a safe output mode in the compiler that uses slightly bulkier code to protect its syntax?

**Comment by michaelficarra** [comment]
What are you using? Use UglifyJS or esmangle. Also, this should be on the mailing list, not an issue.

**Comment by CodyKochmann** [comment]
I use closure compiler because it's the only one that produces script that reliably runs in bookmarklet's. If any of those three levels don't work (including white space only) then I try to find a compilation that works through compressorrater which has been really destructive towards any script with html strings in it. I'm open to any suggestions for a better compiler if there's one that coffeescript works well with.
