### ISSUE TITLE
Right side existential operator suggestion: =?

### ISSUE THREAD

**Issue by MathieuLoutre** [jashkenas/coffeescript#3997]
I love the using the existential operator for all left side checks, but I find myself doing a lot of these lately when I deal with optional payloads:

```coffee
res.foo = payload.foo if payload.foo?
```

So I was wondering if adding support for right side checks was possible so that it can be written:

```coffee
res.foo =? payload.foo
```

I'm not familiar with the compiler's code, but I'd be happy to dive in if PRs are welcome. Any thoughts?

**Comment by vendethiel** [comment]
Coco has this feature, spelled `a? = b`

**Comment by christopherdumas** [comment]
I do think this would be very cool. But as a single operator, because it seems to make more sense.

**Comment by MathieuLoutre** [comment]
@vendethiel isn't that a little confusing? The assignment should be done if `b` exists and not if `a` exists. Coffeescript can do `?=` already which assigns if the left side is not null. 

@christopherdumas I wouldn't be against another notation, only suggesting `=?` because `?=` already exists. Do you have another operator in mind?

**Comment by jashkenas** [comment]
Hmm...

The `=?` syntax is very appealing. Any more opinions? Anyone not like it?

**Comment by bjmiller** [comment]
:-1:  I don't feel that it's necessary, nor very readable.  It wouldn't hurt things to have, though.  So, call me a 2 out of 10 on it.

**Comment by christopherdumas** [comment]
I think the `=?` operator is very appealing. That would be a nice addition to CS.

**Comment by srb-** [comment]
I'm for it, and would use it regularly. I never did like writing stuff like:
```
opts.prompt = argv.prompt if argv.prompt?
```
=? would complement ?= perfectly IMO.

**Comment by jashkenas** [comment]
Actually, this would be a confusing feature to add:

    a ?= b

Assigns the value `b` to the name `a`, only if `a` **is** null.

    a =? b

Assigns the value `b` to the name `a`, only if `b` **is not** null.

Let's leave this out.

**Comment by michaelficarra** [comment]
I was just about to say the same thing. I feel I would be regularly confused when reading this syntax.

**Comment by MathieuLoutre** [comment]
Sure, I understand the concern. Any thoughts on an alternative syntax? What I'm looking for is a sort of "assign if exist" or maybe "don't assign". I'm saying this half jokingly (because the syntax isn't great), but maybe it's not to do with the `=` but with the right side:

```coffee
res.foo = payload.foo?!
```

or maybe

```coffee
res.foo = payload.foo or not assign
```

Obviously this looks a strange, but if the idea is appealing maybe there's a better syntax than `=?`.

**Comment by jashkenas** [comment]
res.foo = payload.foo if payload.foo?

Is a fine way to write it. If you're really doing this all the time — write a helper function.

**Comment by MathieuLoutre** [comment]
Fair enough. Thanks for considering it!

**Comment by jashkenas** [comment]
No problem.

```coffeescript
assign = (from, to, keys) ->
  for key in keys
    to[key] = from[key] if from[key]?
  return to
```

**Comment by MathieuLoutre** [comment]
Thanks, that looks sweet. I guess I could also use `_.extend` if I needed to deal with multiple object attributes (provided they have the same name).
