### ISSUE TITLE
Weird bug with incorrect whitespace calculation

### ISSUE THREAD

**Issue by ashtuchkin** [jashkenas/coffeescript#3998]
```coffeescript
query.stream()
    .on 'data', (items) ->
        arr = items
            .map (item) -> 
                calcValue(item)
            .sort()
           
        process arr[0]
```
is compiled to (in [coffeescript.org](http://coffeescript.org/#try:query.stream()%0A%20%20%20%20.on%20'data'%2C%20(items)%20-%3E%0A%20%20%20%20%20%20%20%20arr%20%3D%20items%0A%20%20%20%20%20%20%20%20%20%20%20%20.map%20(item)%20-%3E%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20calcValue(item)%0A%20%20%20%20%20%20%20%20%20%20%20%20.sort()%0A%0A%20%20%20%20%20%20%20%20process%20arr%5B0%5D%0A))
```javascript
query.stream().on('data', function(items) {
  var arr;
  return arr = items.map(function(item) {
    return calcValue(item);
  }).sort();
});

process(arr[0]);
```

process(arr[0]) is expected to be in the callback of course.

**Comment by christopherdumas** [comment]
I would guess that it is the newline?

**Comment by ashtuchkin** [comment]
Which one? :)

--
Alexander Shtuchkin

On Sun, May 31, 2015 at 8:20 PM, Christopher Dumas <notifications@github.com

**Comment by akre54** [comment]
Try aligning the `map` and `sort` lines to the right of `items`. ([fix](http://coffeescript.org/#try:query.stream()%0A%20%20%20%20.on%20'data'%2C%20(items)%20-%3E%0A%20%20%20%20%20%20%20%20arr%20%3D%20items%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map%20(item)%20-%3E%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20calcValue(item)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.sort()%0A%0A%20%20%20%20%20%20%20%20process%20arr%5B0%5D%0A)). You can see the difference by changing the spacing on the `sort` line.

**Comment by ashtuchkin** [comment]
Thanks Adam. I solved the immediate problem by moving code around.

The thing is, shouldn't it work as is with the code I posted? There could
be a parsing problem that I wanted to highlight.

--
Alexander Shtuchkin

**Comment by ashtuchkin** [comment]
I mean, why does it even depend on this kind of changes?

--
Alexander Shtuchkin

**Comment by lydell** [comment]
Yes, your code should work as you posted it. IMO there are lots that could be improved regarding how CoffeeScript handles indentation.

**Comment by akre54** [comment]
Agreed, it definitely should.

**Comment by jashkenas** [comment]
Nope — CoffeeScript doesn't do absolute indentation, it does relative indentation, and in your example, you outdent three times, closing three levels of indentation:

```coffeescript
query.stream()
    .on 'data', (items) ->
        arr = items
            .map (item) -> 
                calcValue(item)   # <-- Innermost Block.
            .sort()    # <-- Block Level 2, outside of the map.

        process arr[0]    # <-- Block Level 3, outside of the callback.
```

For the record, the idiomatic way to write this in CoffeeScript would be like this:

```coffeescript
query.stream().on 'data', (items) ->
  arr = items.map((item) -> 
    calcValue(item)
  ).sort()
  process arr[0]
```

**Comment by lydell** [comment]
> doesn't do

but _could do,_ right? Don’t you agree that it is a bit unexpected?

**Comment by jashkenas** [comment]
Relative versus absolute indentation is a choice — both have advantages and drawbacks. Entertaining a switch to absolute would be an interesting PR, and a massively breaking change ... but this particular example is not a bug.

One thing that relative does, that absolute doesn't, is stuff like this:

```coffeescript
if condition
    items.map (item) ->
        transform item
  else
    reject items
```

... basically a little bit of sloppiness, which otherwise would be rejected. We're counting the number of times you indent and outdent — not trying to add them up and guess where you meant your code to land.

In @ashtuchkin's example, the `.sort()` and `process arr[0]` are not on the same level of indentation — that's why CoffeeScript doesn't think they're meant to be in the same block.

**Comment by lydell** [comment]
Then why does @akre54’s fixed version (which he linked to) work? Is _that_ a bug? :)

**Comment by akre54** [comment]
Or [this one](http://coffeescript.org/#try:query.stream()%0A%20%20%20%20.on%20'data'%2C%20(items)%20-%3E%0A%20%20%20%20%20%20%20%20arr%20%3D%20items%0A%20%20%20%20%20%20%20%20.map%20(item)%20-%3E%20%0A%20%20%20%20%20%20%20%20%20%20%20%20calcValue(item)%0A%20%20%20%20%20%20%20%20.sort()%0A%0A%20%20%20%20%20%20%20%20process%20arr%5B0%5D%0A)?

**Comment by jashkenas** [comment]
Again -- it's about the number of times that you outdent. That last version works great because `.sort()` and `process arr[0]` are *on the same level of indentation.* So they're part of the same block of code.
