### ISSUE TITLE
yield issue when using koa && koa-route

### ISSUE THREAD

**Issue by Tsher** [jashkenas/coffeescript#4000]
### a bit different
when i code this in coffee

    ... `index.coffee`
    route= require 'koa-route'
    app= koa()
    app.use route.get '/', list
    list= ()->
	@body= yield render 'list', {posts: posts}
    ....

which could compile into javascript like below

    ... `index.js`
    var route = require('koa-route');
    var app = koa();
    app.use(route.get('/', list));
    list = function * () {
      return this.body= (yield render('list', {posts: posts}))
    }
Neither command `coffee --nodejs --harmony index.coffee` nor `node --harmony index.js` work well.
These two command revealed an error: 
![qq 20150603175733](https://cloud.githubusercontent.com/assets/1813968/7957448/0a92d9a6-0a1a-11e5-817c-54558e9560f6.png)

Web page comes to an `Internal Server Error` error

Only if i turn the coffeescript into below:

    app.use route.get '/', ()->    @body= yield render 'list', {posts: posts}
or javascript like this:

    app.use(route.get('/', list));
    function *list() {
      this.body = yield render('list', { posts: posts });
    }
Will work!

it's interesting to solve the problem , cos i i don't know which part go wrong. Coffee? Koa? or koa-route?
waiting for reply~~

**Comment by vendethiel** [comment]
CoffeeScript's functions are not hoisted. This means they're not available before you defined them:

```
a(); // won't work!
var a = function () {
  console.log("hey"); 
};

**Comment by Tsher** [comment]
Thank u for reply soon! it's my name sequence go wrong~
