### ISSUE TITLE
Meta: cdnjs-hosted CoffeeScript is unusable

### ISSUE THREAD

**Issue by metalim** [jashkenas/coffeescript#4001]
https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.9.3/coffee-script.js points to uncompiled file instead of one from /extras/
That makes it useless for prototyping with `<script type="text/coffeescript">`

**Comment by vendethiel** [comment]
That's an issue with cdnjs though. It's probably due to the `bower.json`'s `main` property?

**Comment by PeterDaveHello** [comment]
We fetched the file from npm package, what should I do to fix it? Thanks,

**Comment by humbletim** [comment]
... submitted a PR (https://github.com/cdnjs/cdnjs/pull/4927) with what I think are correct builds of the coffee-script 1.9.3 browser module.

And here are links to historical versions that seem to work fine (and might be useful in the meantime for prototyping via CDN):

[**1.1.2**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.1.2/coffee-script.min.js) | 1.1.3 | [**1.2.0**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.2.0/coffee-script.min.js) | 1.3.0 | [**1.3.1**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.3.1/coffee-script.min.js) | 1.3.2 | [**1.3.3**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.3.3/coffee-script.min.js) | [**1.4.0**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.4.0/coffee-script.min.js) | 1.5.0 | 1.6.0 | 1.6.1 | [**1.6.2**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.6.2/coffee-script.min.js) | [**1.6.3**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.6.3/coffee-script.min.js) | 1.7.0 | [**1.7.1**](https://cdnjs.cloudflare.com/ajax/libs/coffee-script/1.7.1/coffee-script.min.js) | 1.8.0 | 1.9.0 | 1.9.1 | 1.9.2 | 1.9.3

**Comment by PeterDaveHello** [comment]
@metalim @vendethiel @jashkenas Would you please confirm cdnjs/cdnjs#4927? Thanks.

**Comment by PeterDaveHello** [comment]
BTW @humbletim, so the versions without links you think they won't work properly?

**Comment by humbletim** [comment]
@PeterDaveHello -- yup, many of the historical versions on cdnjs are incomplete.  I'll paste a more exhaustive version analysis over on the local ticket https://github.com/cdnjs/cdnjs/issues/4869

**Comment by PeterDaveHello** [comment]
Thanks @humbletim

**Comment by GeoffreyBooth** [comment]
This isn’t a bug in CoffeeScript, and it’s already being tracked by cdnjs at https://github.com/cdnjs/cdnjs/pull/4927.

**Comment by maximelafarie** [comment]
For those who are still looking for an answer as neither this issue or the linked PR are bringing news or ways to fix that, I'm personally using the official [CoffeeScript Compiler (v2.3.2)](https://coffeescript.org/browser-compiler/coffeescript.js) from their live editor. So directly use the link or download it and include it in your projects. 😉 

Cheers! 🖖

**Comment by metalim** [comment]
"It's his fault" 👉          👈 "It's his fault"

"Whatever... I'll just copy the file"  🖖
