### ISSUE TITLE
new keyword: thus becomes @valueOf()

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#4004]
Hello.  Very simple -> I'd like to propose `thus` for translation to `@valueOf()`

I frequently find myself monkey-patching things like Number and String (disregard this tragedy).  When adding a method to these prototypes and invoking `valueOf()` I get frustrated because I know it's returning the associated primitive from a part of the runtime I can't reference.  (3) in the [Number: 3] is something you can't directly reference as it's invoking a native-code getter to somewhere "underground".  I'd like a `thus` keyword to make it less apparent that the primitive is actually very separate from the object that is meant to otherwise contain it as a property.  I also think it'd be pretty funny.

``` coffeescript
return thus if typeof this is 'Number'
```

It's not equivalent but I'd like writing:
```coffeescript
return thus?
```

Obvious concerns are it would be easy to typo this-thus.  I like simple candy. :-)

**Comment by vendethiel** [comment]
Since no one has shown any interest in this issue, I'm gonna go ahead and close it.
