### ISSUE TITLE
`([a = {}]..., b) ->` does not define `a`

### ISSUE THREAD

**Issue by xarvh** [jashkenas/coffeescript#4005]
With both 1.8.0 and 1.9.3, running
```
whatever = ([a = {}]..., b) ->
  console.log a

whatever()
```
will produce `ReferenceError: a is not defined`.

If the default assignment `= {}` is removed, `a` is defined correctly.

**Comment by bjmiller** [comment]
I'm sort of amazed that this compiles.  What is it trying to do, exactly?

**Comment by metalim** [comment]
Get the first array element of first argument and default it to empty object. Kinda cheesy...

**Comment by xarvh** [comment]
@metalim Nice solution.
However, coffee should either reject the syntax, either define the variable.

**Comment by pepkin88** [comment]
While ECMAScript 2015 does, CoffeeScript does not support default values for destructuring assignment.

**Comment by xarvh** [comment]
The problem is not whether or not it should be supported.
The problem is that it produces non viable js code without any error or warning for the user.

**Comment by lydell** [comment]
Fixed by #4069.
