### ISSUE TITLE
.eval works in repl but not in script

### ISSUE THREAD

**Issue by ccorcos** [jashkenas/coffeescript#4011]
The following works from the coffeescript REPL but doesnt work if I put it in a file and run it. It says that "a is not defined"

``` coffee
Coffee = require 'coffee-script'
a = {b: 1}
console.log Coffee.eval('a.b')
```

**Comment by ccorcos** [comment]
Also, is there any documentation on `.eval`? I couldn't find any...

**Comment by ccorcos** [comment]
Hmm. `sandbox` is what I needed:

https://github.com/jashkenas/coffeescript/blob/master/src/coffee-script.coffee#L144

I'll leave this issue open for the moment, because I think this ought to be documented

**Comment by GeoffreyBooth** [comment]
These are methods for internal use in the REPL.
