### ISSUE TITLE
destructuring suggestion?: whatever{ f1, f2, f3 } = require 'whatever'

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#4012]
I have something I hope would not lead to very ambiguous, horrible grammar rules.

It's common to do this:
```coffeescript
whatever = require 'whatever'
{ f1, f2, f3 } = whatever
```

The objective being to have easy references to f1, f2, and f3 from `whatever` - but also to have a reference to whatever itself.

I'd like to have it shortened to just this:

```coffeescript
whatever{ f1, f2, f3 } = require 'whatever'
```

It would expand to:

```javascript
var whatever = require('whatever');
var f1 = whatever.f1, f2 = whatever.f2, f3 = whatever.f3;
```

I'm not familiar with Coffeescript's parser definition, but it would just be an optional Javascript-legal identifier followed by destructuring syntax (I imagine this matches only at the beginning of a line after whitespace).

Very simple - any problems with this idea?

**Comment by vendethiel** [comment]
What's wrong with `{a} = b = c` ?

```
{ f1, f2, f3 } = whatever = require 'whatever'
```

**Comment by blitmap** [comment]
In my opinion, `b{a} = c` looks cleaner than `{a} = b = c`

I tried to search for duplicate suggestions - can you link me to the importing properties one?

**Comment by blitmap** [comment]
I had a new thought about this - what if `b{a} = c` acted more like a filtered assignment?

I write things like:
```coffeescript
{ readFile, writeFile } = require 'fs'
```

I'd like to still contain it in an `fs` object, but not with everything from fs.  I'd like to write this:

```coffeescript
fs{ readFile, writeFile } = require 'fs'
```

It would become:
```coffeescript
fs = {}
fs.readFile = require('fs').readFile
fs.writeFile = require('fs').writeFile
```

^ as a bad example

**Comment by vendethiel** [comment]
This'd require some kind of smart autovivification, though.

**Comment by blitmap** [comment]
How do you mean?  Is this related to the double-require() in my example?

**Comment by DylanPiercey** [comment]
```coffeescript
whatever = { f1, f2, f3 } = require 'whatever'
```

Also works and is closer to your example.

**Comment by blitmap** [comment]
@DylanPiercey I agree, that is very much what I want - I just was hoping for a shorterhanded version of that.  In my opinion it's a syntax worth supporting - in my coffeescript projects I enforce a style guide where I don't allow `a = b = c`  (multiple assignment on one line)

I don't know if my preferred style is very common but I thought it would be nice to have.  It doesn't sound like this is something others want though - perhaps I should close..

**Comment by DylanPiercey** [comment]
@bitmap I'd personally bite the bullet since the syntax you want is one character away :p

**Comment by blitmap** [comment]
ONE CHARACTER MAKES OR BREAKS THE STORY, DYLAN

- okay I'll close :p -
