### ISSUE TITLE
cant find a way to select arguments to define

### ISSUE THREAD

**Issue by CodyKochmann** [jashkenas/coffeescript#4014]
In functions that take in a ton of arguments (lets say 8 for this example) but do have defaults, I can't find a clean and easy way to define select and sometimes find myself wishing unordered arguments were a thing too (unordered just keeps syntax for APIs looser). 

For example, I had an object with a function that generated a div with a certain set of rules for its behavior set up to be injected with it. In order to keep the defaults for the injector but select a certain argument to change I would prefer to be able to do something like this:

```coffeescript
gen_div( circle = true )
```
That though doesn't assign anything to the circle argument so I'm forced to write out to the index of the argument like so:
```coffeescript
gen_div( undefined, undefined, undefined, undefined, undefined, undefined, true )

# or for somewhat cleaner but still hard to quickly comprehend:
u=undefined
gen_div( u, u, u, u, u, u, true )
```
Is there something in the coffeescript library that I'm missing? Or is this type of argument parsing just not in coffeescript? 

I know there are quick and easy ways to manipulate a div that would just be another line to adjust what the function made but if this was an option for something a little more complex like machine learning, stuff like this is really appreciated.

**Comment by vendethiel** [comment]
The recommended approach is usually to pass in an object.

**Comment by connec** [comment]
It's interesting that default values for destructured arguments have been shot down so often, yet it is a nice pattern for this situation, since all others would require duplication or constant object access.

```coffee
# Get options into variables, need to repeat variable names
f = (options = {}) ->
  { a, b } = merge {}, options,
    a: 1
    b: 2
  a + b

# No duplication, need to use `options.` for all accesses
f = (options = {}) ->
  options = merge {}, options,
    a: 1
    b: 2
  options.a + options.b

# Wouldn't this (or something similar) be nice?
f = ({ a = 1, b = 2 }) ->
  a + b

merge = (dest, srcs...) ->
  dest[k] = v for k, v of src for src in srcs
  dest
```

**Comment by lydell** [comment]
#3288
