### ISSUE TITLE
heredocs with no non-whitespace content don't trim in CS 1.9.0+ as in earlier versions

### ISSUE THREAD

**Issue by danielbprice** [jashkenas/coffeescript#4016]
I don't know if this is a bug, but I found this to be a surprising difference during our upgrade from CS 1.7.1 to 1.9.x.

```
$ cat a.coffee
a = """
    test string
    """

b = """
    """
```

Here's a diff of the code generated by CS 1.7.1 versus 1.9.3:

```
$ diff a.js.1.7.1 a.js.1.9.3
1c1
< // Generated by CoffeeScript 1.7.1

---
> // Generated by CoffeeScript 1.9.3
7c7
<   b = "";

---
>   b = "    ";
```

What I found surprising was the different treatment of `a` versus `b`.  I don't understand why CS would not trim the string `b` as is does `a`.  This broke many dozens of test cases for us so it has been a time suck.

**Comment by GeoffreyBooth** [comment]
It trims based on the indentation to the first non-whitespace character. This is just the expected behavior now, sorry.
