### ISSUE TITLE
How to repeatable schemas definition?

### ISSUE THREAD

**Issue by carrot93** [jashkenas/coffeescript#4017]
how coffescript could do the repeatable schemas defined? like

```
Schemas= { 
      a1:{
           a1_1,define1_1,
           a_2,define2}
      ....
      a100:{
            a100_1:define100_1,
            a100_2:define100_2}
} 
```

**Comment by vendethiel** [comment]
Sorry, this is not very clear. Could you explicit the issue a bit?

**Comment by carrot93** [comment]
em,yep.Example:
 A schema of mongo collection, I need a1,a1_1,a1_2 a2 a2_2 .... a100,a100_1,a100_2 fields name and all fields item type is String.  But the mongo needs pre-defined schema that I need write down a1-a100. 
If I could write some like
Schemas ={ a_{variable}:{type:string},a_{variable}_1:{type:String}......} (variable from 1-100) ?

**Comment by GeoffreyBooth** [comment]
I don’t understand the question.
