### ISSUE TITLE
Finite generators return [undefined, undefined, ...] as final return result

### ISSUE THREAD

**Issue by bernhard-42** [jashkenas/coffeescript#4018]
The following two implementations of a simple generator

	squares1 = ->
		num = 0
		while num < 2
			num += 1
			yield num * num
		return

	squares2 = ->
		for num in [1..2]
			yield num * num

	x1 = squares1()
	x2 = squares2()

	console.log x1.next(), x2.next()
	console.log x1.next(), x2.next()
	console.log x1.next(), x2.next()

have different outputs

	{ value: 1, done: false } { value: 1, done: false }
	{ value: 4, done: false } { value: 4, done: false }
	{ value: undefined, done: true } { value: [ undefined, undefined ], done: true }

The implementation seems to differentiate between an obviously finite generator (`[1..2]`) and a conditional, where one cannot judge on whether it gets to an end.

But what is `[ undefined, undefined ]`?

Let's compile it:

	// Generated by CoffeeScript 1.9.3
	var squares1, squares2, x1, x2;

	squares1 = function*() {
		var num;
		num = 0;
		while (num < 2) {
			num += 1;
			(yield num * num);
		}
	};

	squares2 = function*() {
		var i, num, results;
		results = [];
		for (num = i = 1; i <= 2; num = ++i) {
			results.push((yield num * num));
		}
		return results;
	};

	x1 = squares1();

	x2 = squares2();

	console.log(x1.next(), x2.next());

	console.log(x1.next(), x2.next());

	console.log(x1.next(), x2.next());

One can see the different implementations here. Maybe this is for getting back the complete generated array, e.g. for splat assignments? But yield doesn't seem to return the value as expected by the code, at least in node `v0.12.4`. If I change the javascript to

	squares2 = function*() {
		var i, num, results;
		results = [];
		for (num = i = 1; i <= 2; num = ++i) {
			var _tmp = num * num
			results.push(_tmp);
			yield _tmp
		}
		return results;
	};

then `node --harmony test.js` delivers

	{ value: 1, done: false } { value: 1, done: false }
	{ value: 4, done: false } { value: 4, done: false }
	{ value: undefined, done: true } { value: [ 1, 4 ], done: true }

which would make slightly more sense. Unfortunately the destructuring doesn't seem to support generators:

	[x, y] = squares2()

is transpiled without using `next()`:

	ref = squares2(), x = ref[0], y = ref[1];

So what is the variant for `squares2` good for?

**Comment by michaelficarra** [comment]
This is working as intended. Those are the value you passed to `next`. Try passing something else.

**Comment by bernhard-42** [comment]
@michaelficarra I see. However I don't think this is obvious. I haven't seen this as a default behaviour in articles about ES generators.
Would it be worth documenting on coffeescript.org?

**Comment by michaelficarra** [comment]
No, this has nothing to do with generators. Function return values are documented just fine.If you disagree, let me know what specifically you think should be added.

**Comment by bernhard-42** [comment]
Agreed, I was too much focused on generators and ignored the default coffeescript behavior (implicit return of the results of the last for loop).
Thanks!
