### ISSUE TITLE
Optimization: Unreachable break added when throwing in switch cases

### ISSUE THREAD

**Issue by dpatti** [jashkenas/coffeescript#4020]
Example Coffee:

``` coffee
switch foo
  when "bar"
    throw Error("bar")
  when "baz"
    true
```

Compiles to:

``` javascript
switch (foo) {
  case "bar":
    throw Error("bar");
    break;
  case "baz":
    true;
}
```

Which, while valid, throws off some linters because the `break` statement is unreachable.

**Comment by nickdima** [comment]
Why are you linting the generated javascript?

**Comment by dpatti** [comment]
Because the tooling for JavaScript surpasses the tooling for CoffeeScript. We use a combination of coffeelint and jshint for this reason.

That said, I don't think our choice of linting tools is entirely relevant. CoffeeScript already omits the `break` statement if the `when` block contains a `return` statement, so it should similarly omit it if there is a `throw` statement.

**Comment by lydell** [comment]
Seems like checking for `throw` needs to be added on [this line](https://github.com/jashkenas/coffeescript/blob/52b1749d5710789936255caf428ffeb011175e45/src/nodes.coffee#L2137).

**Comment by msonnabaum** [comment]
Same thing happens when the return value is either assigned, or the return value of the switch statement is also the return of a function.

```coffeescript
b = switch
    when a > 10
      "greater than 10"
    when a < 10
      if a > 5
        "greater than five"
      else
        "less than five"
    else
      "is 10"
```

```javascript
var b;

b = (function() {
  switch (false) {
    case !(a > 10):
      return "greater than 10";
    case !(a < 10):
      if (a > 5) {
        return "greater than five";
      } else {
        return "less than five";
      }
      break;
    default:
      return "is 10";
  }
})();
```
