### ISSUE TITLE
[Feature Request] Optional TypeScript-style static type-safety for parameters

### ISSUE THREAD

**Issue by alexbuzzbee** [jashkenas/coffeescript#4023]
TypeScript has an interesting static typing system; in TypeScript, a function may be defined with fixed-type parameters. The compiler checks these types for every call at compile time. I propose that CoffeeScript implement optional static typing in a different way: The compiler adds type checks to the beginning of the function body it generates.

I do not propose that CoffeeScript implement TypeScript-style static return types; they are difficult to implement dynamically. If someone else comes up with a way to do that, It'd be really cool, but I can't come up with a way to do it.

### Examples

NOTE: These examples were compiled by hand, as I'm not 1337 enough to hack the CoffeeScript compiler to implement static typing all on my own. Therefore, there may be differences between what the compiler generates and these examples.

#### Simple types

Input
```coffeescript
add = (a: number, b: number) -> a + b

add 2, 3 # Works fine, returns 5.
add 2, "hello, world" # In unmodified CoffeeScript, returns "2hello, world". In this version, throws a TypeError: Expected a number for 'b'.
```

Output
```javascript
(function() {
  var add;
  add = function(a, b) {
    if(typeof(a) !== "number") {
      throw new TypeError("Expected a number for 'a'.");
    }
    if(typeof(b) !== "number") {
      throw new TypeError("Expected a number for 'b'.");
    }
    return a + b;
  };

  add(2, 3);
  add(2, "hello, world");
}).call(this);
```

#### Objects

Input
```coffeescript
get = (a: object) -> a.gettable

someObject = 
  gettable: 13

get someObject # Works fine, returns 13.
get 7 # In unmodified CoffeeScript, returns undefined. In this version, throws a TypeError: Expected a object for 'a'.
```

Output
```javascript
(function() {
  var someObject, get;
  get = function(a) {
    if(typeof(a) !== "object") {
      throw new TypeError("Expected a object for 'a'.");
    }
    return a.gettable;
  };

  someObject = {
    "gettable": 13
  };

  get(a);
  get(7);
}).call(this);
```

#### Classes (not strictly required, but TypeScript does this.)

Input
```coffeescript
class SomeClass
  constructor: (a) ->
    @gettable = a

get = (a: SomeClass) -> a.gettable

instance = new SomeClass(4)

someObject = 
  gettable: 13

get instance # Works fine, returns 4.
get someObject # In unmodified CoffeeScript, returns 13. In this version, throws a TypeError: Expected a SomeClass for 'a'.
```

Output

```
I'm not going to compile this manually. It's too hard.
```

**Comment by alexbuzzbee** [comment]
Duplicate of what? At least tell me!

**Comment by vendethiel** [comment]
https://github.com/jashkenas/coffeescript/issues?utf8=%E2%9C%93&q=typescript+flow

**Comment by alexbuzzbee** [comment]
Ah. Sorry.
