### ISSUE TITLE
Module: requiring compiler for client-side use

### ISSUE THREAD

**Issue by jannavarro** [jashkenas/coffeescript#4024]
I installed coffeescript in a clientside javascript project using webpack and babel. My intention is to use coffeescript modules in my javacsript project similar to [this](http://stackoverflow.com/questions/7375778/can-i-mix-js-and-coffeescript-in-a-project). After installing it I run the project and it is looking for node module components. some of the errors are:

Module not found: Error: Cannot resolve module 'child_process' in D:...\node_modules\coffee-script\lib\coffee-script

Module not found: Error: Cannot resolve module 'module' in in D:...\node_modules\coffee-script\lib\coffee-script

I am not sure if there is just a setup issue in what I am doing.

**Comment by nickdima** [comment]
Are you using [coffee-loader](https://github.com/webpack/coffee-loader) with `webpack`?

**Comment by jannavarro** [comment]
@nickdima not yet. thanks for your response. I will try this and update this thread.

**Comment by GeoffreyBooth** [comment]
Fixed by #4501

**Comment by jannavarro** [comment]
I haven't tried this again but based on the comment, #4501 fixed this.
