### ISSUE TITLE
Feature request: Not maybe equals operator

### ISSUE THREAD

**Issue by bcherny** [jashkenas/coffeescript#4026]
```
a = 1
a ?= 2    # a is still 1
a !?= 3   # a is now 3
```

**Comment by metalim** [comment]
What's the realistic use case?

**Comment by jashkenas** [comment]
Thanks, but no thanks.

**Comment by bcherny** [comment]
my use case is i'm getting data from an api, and a key may or may not be defined. if it is defined, i want to map it. eg.

```coffee
# data: [
#  { foo: "1", bar: "1" }
#  { foo: null, bar: "2" }
# ]
(do api.getData).then (data) ->
  data.map (d) ->
    d.foo !?= Number d.foo
    d
  # data: [
  #  { foo: 1, bar: "1" }
  #  { foo: null, bar: "2" }
  # ]
```

**Comment by jashkenas** [comment]
d.foo ?= Number d.foo

**Comment by bcherny** [comment]
that will assign foo, if foo is undefined. i want the opposite, to assign foo only if foo is already defined. this is a problem i come across pretty frequently.

**Comment by connec** [comment]
I guess the standard in that case would be to do `d.foo = Number d.foo if d.foo?`, which does feel quite redundant.

If you're not too worried about `false` values, you could also use `and=` (`d.foo and= Number d.foo`).

**Comment by bcherny** [comment]
> `d.foo and= Number d.foo`

that's clever, i like it :)

though a dedicated `!?=` operator would still be ideal.

**Comment by connec** [comment]
Actually that reminds me I made an issue along these lines last year (#3505)

```coffee
a = 1
a ? 2  # 1
a !? 2 # 2
```
