### ISSUE TITLE
Shorthand return

### ISSUE THREAD

**Issue by jamen** [jashkenas/coffeescript#4027]
I saw on another issue that detailed a lot of changes, it was closed because the key focus of the issue was on how CoffeeScript automatically returns the last item in a function...

But I'm not here to make another post on that, I'm here to bring attention to one little feature he recommended, a shorthand return statement.

Opposite to the `->` function declaration , we could add a opposite `<-` for returning.  Here is an example that applies this:

_(Old bad examples)_
```coffeescript
example = (test) ->
  if test
    <- test

test = (example) ->
  <- example if 1 < 2
```

_(Better new examples)_

```coffeescript
example = (data, test) ->
  if test
    someGlobal.someMethod()
    <- # exit
  else
    data.someMethod()
    data
```

**Comment by vendethiel** [comment]
Is this supposed to hace different semantics from return, or only to save 4 chars?

**Comment by mechMach** [comment]
+1. This is a very good idea! I switched to Coffeescript because I was tired to typing 'function', 'var' , 'that' , commas, brackets etc. I always thought that the absence of a shorthand for 'return' was very un-Coffeescript.

**Comment by DylanPiercey** [comment]
Returns are implicit for both examples above.

```coffeescript
example = (test) ->
  if test
    test

test = (example) ->
  example if 1 < 2
```
```javascript
var example, test;

example = function(test) {
  if (test) {
    return test;
  }
};

test = function(example) {
  if (1 < 2) {
    return example;
  }
};
```

Returns are automatically the last expression in coffeescript. The "return" keyword is only needed when you wish to exit a function early.

I'm -1 on this personally, coffeescript is about readability more than shortcuts and in this case you don't get much of either.

**Comment by JamenMarz** [comment]
I guess my examples were bad, sorry.  :P

**Comment by nodegin** [comment]
+1, I hate automatically return

just imagine:
```
setRed = (q)->
  e = document.querySelector q
  e.style.background = 'red'
```

which compiles to

```
setRed = function(q) {
  var e;
  e = document.querySelector(q);
  return e.style.background = 'red';
};
```

it's odd, isn't it?

**Comment by YoYoYonnY** [comment]
@nodegin in my opinion coffeescript should only automatically return if the last statement is not a assignment anyway.

**Comment by DylanPiercey** [comment]
@YoYoYonny, I think that'd be too confusing for people. It's probably better that it's all or nothing.

**Comment by carlsmith** [comment]
Spelling `return` as `<-` doesn't really make it an operator. It's still a statement that now looks like an expression. Jump statements (break, continue, return, yield) very conventionally use those keywords.

For this to be useful, the two must do different things. If adding `<-` to a function disabled auto-return, some people would like it. I doubt Jeremy would be one of them though.

`-1`

**Comment by jashkenas** [comment]
It's cute, but the best style in CoffeeScript would be to simply use short methods with implicit returns the vast majority of the time.

In cases where explicit returns are desired, `return` isn't too much to type.
