### ISSUE TITLE
Quick access to object's constructor

### ISSUE THREAD

**Issue by Strate** [jashkenas/coffeescript#4030]
To access class static methods I should write:
```
class One
  @method: -> 1+1

  do: -> @constructor.method()
```
Much better use shorthand. Best is `::`, but it busy for access `prototype` property. So, I suggest to use double `@` sign:

```
do: -> @@method()
```

or `::` without leading `@`:
```
do: -> ::method()
```

**Comment by vendethiel** [comment]
I thought this was a duplicate, but I was unable to find the issue, so I'm only going to link to satyr/coco#53 instead (`@@` in LS)

**Comment by vendethiel** [comment]
Oh, found it finally. #3222
