### ISSUE TITLE
array.length -1 being parsed as a function

### ISSUE THREAD

**Issue by jbarker4682** [jashkenas/coffeescript#4032]
this is something that I just came across that I spent a bit of time trying to find/fix.

we had a one space typo trying to pass the last index of an array to the splice method:

arr.splice arr.length -1, 0, foo

resulted in:     path.splice(path.length(-1, 0, foo));

instead of:      path.splice(path.length - 1, 0, foo)

removing the space in front of the minus, or adding a space after the minus results in the correct output.

**Comment by michaelficarra** [comment]
Please see duplicates.
