### ISSUE TITLE
Compiler bug involving parenless chaining and multiline object literals.

### ISSUE THREAD

**Issue by pepkin88** [jashkenas/coffeescript#4035]
The following code can't get compiled.

``` CoffeeScript
aaa
  .bbb ccc:
    ddd: 111
  .eee()
```

but those snippets are compiled without problems:

``` CoffeeScript
aaa
  .bbb
    ddd: 111
  .eee()
```

``` CoffeeScript
aaa
  .bbb ccc,
    ddd: 111
  .eee()
```

``` CoffeeScript
aaa
  .bbb { ccc:
    ddd: 111 }
  .eee()
```

``` CoffeeScript
aaa
  .bbb(ccc:
    ddd: 111
  ).eee()
```

(Strangely, those snippets put together in one file will also produce a compilation failure, but can be compiled one by one)

**Comment by phaux** [comment]
Even if it compiled, it wouldn't be very useful, because you're calling the method on the object with `ccc` property:

```coffee
aaa.bbb( { ccc: {ddd: 111} }.eee() )
```

It would be cool if it worked **and** did the correct thing automagically, though. Consider this:

```coffee
fs.readFileAsync filename, 'utf8'
.then (source) -> switch extension
  when 'json' then JSON.parse source
  when 'cson' then CSON.parse source
.then (object) -> …
# ^ this doesn't work because you're trying to call `.then` on the `switch` body
# even though it's pretty unambiguous...
```

**Comment by pepkin88** [comment]
> (...) because you're calling the method on the object with ccc property

@phaux No, I'm not. Why do you think so? Indentation level is the same as previous method call. Can you show me an example, where
```CoffeeScript
aaa
  .bbb # ... something
  # ... something
  .ccc()
```
actually compiles to (not fails to compile):
```JavaScript
aaa( (that something).bbb() )
```

**Comment by phaux** [comment]
```coffee
a: 1
.f()
# compiles to
{a: 1}.f()

f
 a: 1
 .f()
# compiles to
f( {a: 1}.f() )

f a:
 b: 1
.f()
# might be as well
f( { a: {b:1} } ).f()
# or
f( { a: {b:1} }.f() )
```

The switch example shows that CS tries to append the `.method()` to the last block opened on the matching opening line, so calling a method on the object would make for a consistent behaviour (although not very useful). Of course I would prefer it to be smart and do the right thing. Just pointing out the other cases which should be changed as well.

**Comment by pepkin88** [comment]
> The switch example shows that CS tries to append the .method() to the last block opened on the matching opening line

@phaux No, the switch example only shows that there is an error in CoffeeScript compiler regarding multiline chaining mechanisms with use of parenless invocation (there were similar bugs (https://github.com/jashkenas/coffeescript/issues/3484), apparently this mechanism isn't completely fixed). Because it doesn't compile, you cannot be sure, that it is in cause of attaching a method call to the switch expression (which is legal in CS).

As you have written, because there is a compilation error, it can be interpreted both ways.
But I've shown an example with use of object literals, that it would be coherent to be interpreted my way, it is:
```
f a:
  b: 1
.f()
# -->
f( { a: {b:1} } ).f()
```

**Comment by xixixao** [comment]
You need to indent both examples:

```coffee
aaa
  .bbb
    ccc:
      ddd: 111
  .eee()
```

```coffee
fs.readFileAsync filename, 'utf8'
.then (source) ->
  switch extension
    when 'json' then JSON.parse source
    when 'cson' then CSON.parse source
.then (object) ->
```
and they work fine. Working as intended imho.
