### ISSUE TITLE
"Try catch" optimisation

### ISSUE THREAD

**Issue by AndreyAntipov** [jashkenas/coffeescript#4036]
The following code compiles with additional self assignment in catch section when user set exception variable name as _error.

```coffeescript
try something()
catch _error
  console.log _error
```

compiles to:
```javascript
try {
  something();
} catch (_error) {
  // unnecessary operations
  _error = _error;

  console.log(_error);
}
```

Here is extra assignment operation

```coffeescript
try something()
catch error
  console.log error
```

compiles to:
```javascript

try {
  something();
} catch (_error) {
  // extra assignment
  error = _error;
  console.log(error);
}

```
Maybe coffeescript compiler may remove this unnecessary code?

**Comment by vendethiel** [comment]
Seems like the generated variable shouldn't be called "_error" if there's already one in scope.

**Comment by michaelficarra** [comment]
@AndreyAntipov This is done to make catch variables in CoffeeScript code essentially var-scoped. But you have found a case where we are not guarding against user-defined and generated symbols clashing.

**Comment by BrunoBernardino** [comment]
I created a Pull Request for this. Let me know if there's something I should be doing differently.
