### ISSUE TITLE
Extra unused var in js output

### ISSUE THREAD

**Issue by app** [jashkenas/coffeescript#4038]
Looking into compiled rewriter.coffee of coffescript source code I found this

```javascript
    Rewriter.prototype.removeLeadingNewlines = function() {
      var i, k, len, ref, tag;
      ref = this.tokens;
      for (i = k = 0, len = ref.length; k < len; i = ++k) {
        tag = ref[i][0];
        if (tag !== 'TERMINATOR') {
          break;
        }
      }
      if (i) {
        return this.tokens.splice(0, i);
      }
    };
```
It seems to me 'k' variable is unused in this method?
Is it ok?

**Comment by vendethiel** [comment]
Look at the for

**Comment by app** [comment]
Hi vendethiel! And thanks for replay!

Sorry for my stupid question, but why we need
    for (i = k = 0, len = ref.length; k < len; i = ++k) {
instead of
    for (i = 0, len = ref.length; i < len; ++i) {
?
AFAICS 'k' not used inside for cycle.
Thanks.

**Comment by michaelficarra** [comment]
`k` is used to keep track of the actual iteration, while `i` is exposed to the user (and therefore mutable).
