### ISSUE TITLE
Object comprehension (to complement array comprehensions)

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#4039]
I was just writing some code that was essentially this:

```coffeescript
FLAGS = {}
for f, i in 'A B C D E'.split ' '
  FLAGS[f] = 1 << i
```

I'd like to propose a syntax for creating objects similar to array comprehension:

```coffeescript
FLAGS = { f: 1 << i for f, i in 'A B C D E'.split ' ' }
# or
FLAGS = { f, 1 << i for f, i in 'A B C D E'.split ' ' }
# or
FLAGS = { f: 1 << i } for f, i in 'A B C D E'.split ' '
```

This seems like a pretty ambiguous syntax though - I just wanted to put forth the idea.

~ or maybe it's not worth it ~

**Comment by vendethiel** [comment]
Duplicate of #77. LS adopted the `{[key, value] for ...}` syntax for this construct.

**Comment by blitmap** [comment]
Ahh, I thought I searched pretty well for duplicates - thanks for letting me know :-)
