### ISSUE TITLE
cod is embeded inside function

### ISSUE THREAD

**Issue by jerome2** [jashkenas/coffeescript#4040]
when i write code from a view directory (rails-4.2.3), then this coffeescript code move alone inside a function (i don't want it). Why ? (i think it is a bug OR a design patern choice, but... why ? how to use it this way ?) 
And how to do for not have this happen ?

**Comment by vendethiel** [comment]
You can set the `--bare` option to remove this wrapper, but instead, it's recommended you "export" variable to window by using `window.a = ...` (or `@a = ...`, when `this` is `window`).

**Comment by jerome2** [comment]
lake of explaications.
set the --bare option... ok... but where and how ? 
why you talk me about variable ?
sorry, but could you be more explicit (imagine you try to explain something someone don't know...) or share a link who really fully explain something ?
thanks for answer and try to provide an efficient help.

**Comment by vendethiel** [comment]
> "set the --bare option"... ok... but where and how ?

No idea. I guess googling "rails coffeescript option" would have given you an answer on the first result (and also explain the second part of my answer):

http://stackoverflow.com/questions/6099342/how-can-i-use-option-bare-in-rails-3-1-for-coffeescript
