### ISSUE TITLE
Dead link to Digital Web article in Coffeescript docs

### ISSUE THREAD

**Issue by rupertrutland** [jashkenas/coffeescript#4042]
![image](https://cloud.githubusercontent.com/assets/1215981/8773442/9f70a006-2ed4-11e5-8a8d-24ad678b33ba.png)

This link doesn't seem to be working:

http://www.digital-web.com/articles/scope_in_javascript/

**Comment by elidiazgt** [comment]
The entire site of that link is down, so i suggest use one of this links

- http://toddmotto.com/everything-you-wanted-to-know-about-javascript-scope
- http://javascriptplayground.com/blog/2012/04/javascript-variable-scope-this

What do you think?

**Comment by nvignola** [comment]
Is possible to mantain the old link grabbing it by http://web.archive.org.
Here the link: https://web.archive.org/web/20150316122013/http://www.digital-web.com/articles/scope_in_javascript

**Comment by ttimasdf** [comment]
This site is still alive but changed to another IP which doesn't bind to original domain name. New link:
http://64.13.255.16/articles/scope_in_javascript

**Comment by nvignola** [comment]
Thanks @ttimasdf. I'll fix this issue with the url that you provided.

**Comment by michaelficarra** [comment]
Fixed by https://github.com/jashkenas/coffeescript/pull/4212.

**Comment by joech4n** [comment]
http://64.13.255.16/articles/scope_in_javascript/ seems to be dead again.

**Comment by GeoffreyBooth** [comment]
https://web.archive.org/web/20150316122013/http://www.digital-web.com/articles/scope_in_javascript still works. Reopening this so we remember to fix it again.
