### ISSUE TITLE
"is undefined" possibly incorrect transpilation to javascript

### ISSUE THREAD

**Issue by ducin** [jashkenas/coffeescript#4043]
Let's analyse the following coffee code:

    if typeof abc is undefined
      abc = null

It gets transpiled down to:

    var abc;

    if (typeof abc === void 0) {
      abc = null;
    }

    // ---
    // generated by coffee-script 1.9.2

(I'm using http://js2.coffee/, but the result of using npm's `coffee-script@1.7.1`).

----

When checking `typeof abc is undefined`, I'd expect such expression to work correctly (coffeescript should be read as a natural language, right?), but it doesn't. `typeof abc` returns a string and `undefined` is just `undefined`. And the `is` operator does the strict comparison, i.e. `===`. And we all know that `"undefined"` is not strictly equal `undefined`. Hance `if typeof abc is undefined` is buggy/invalid expression.

Is that on purpose? I know that `typeof` is whacky, just as all low-level JavaScript is. But isn't coffeescript's main reason is to abstract out the whackiness of JavaScript?

**Comment by vendethiel** [comment]
`typeof` works with strings, that hasn't been change (remember, it's just javascript).

You should use the soak `?` operator:

```
if abc?
  # abc is defined
```

For the reason your code wouldn't work anyway, see the [Common Gotchas wiki page](https://github.com/jashkenas/coffeescript/wiki/Common-Gotchas#q-why-does-coffeescript-require-foo-to-be-defined-when-doing-foo--value-or-foo--value)
