### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by BinaryAssembler** [jashkenas/coffeescript#4044]
I'm working with Node.js and has a piece of code that I need to write:

```
app.use express.static("#{ dirname }/public")
```

in order to use the directories of express , but CoffeeScript compiles to:

```
app.use(express ["static"](__ dirname + "/public"));
```

when the output I expected was:

```
app.use (express.static(__ dirname + "/public"))
```

From what I understand the static is a reserved word CoffeeScript but I have not found in the documentation.
I'm bypassing the problem with embedded JavaScript however wanted to do everything with  CoffeeScript. :coffee: 

Was this a bug?
:question:

**Comment by michaelficarra** [comment]
Not a bug. Try actually running it.

**Comment by vendethiel** [comment]
This is on our [Wiki "Common Gotchas"](https://github.com/jashkenas/coffeescript/wiki/Common-Gotchas#q-why-is-coffeescript-sometimes-using-bar-notation-over-bar-)

**Comment by BinaryAssembler** [comment]
Thank you, I did not know that his behavior. I will read the link that recommended me. 
:+1: :smile: :coffee:
