### ISSUE TITLE
Feature Request: Extend DRY-style object creation

### ISSUE THREAD

**Issue by nickretallack** [jashkenas/coffeescript#4045]
I find it strange that you can say

```coffeescript
a = "hello"
x = {a} # {a:"hello"}
```

and you can say

```coffeescript
@a = "hello"
x = {@a} # {a:"hello"}
```

but you can't say

```coffeescript
foo = {a:"hello"}
x = {foo.a} # {a:"hello"}
```

Should we add that to the syntax?  I think the general rule should be that the property name should match the identifier after the last dot in the value provided.  So this should also work:

```coffeescript
a.b.c.d.e = "hello"
x = {a.b.c.d.e} # {e:"hello"}
```

**Comment by vendethiel** [comment]
Duplicate of #1089
