### ISSUE TITLE
Interior objects in array require extra braces

### ISSUE THREAD

**Issue by jessaustin** [jashkenas/coffeescript#4046]
I suspect that many people already know about these behaviors, but they surprise me occasionally so I wanted to document them clearly. In the simple case, a leading comma indicates a new object in an array:
```coffeescript
[
  a: 'first'
, a: 'second'
]
```
...is transpiled to...
```javascript
[
  {
    a: 'first'
  }, {
    a: 'second'
  }
];
```
This seems reasonable. However that understanding doesn't work for three objects in an array:
```coffeescript
[
  a: 'first'
, a: 'second'
, a: 'third'
]
```
...becomes...
```javascript
[
  {
    a: 'first'
  }, {
    a: 'second',
    a: 'third'
  }
];
```
That's not what we want! We can get that with some extra braces:
```coffeescript
[
  a: 'first'
, a: 'second'
, {a: 'third'}
]
```
...transpiles to...
```javascript
[
  {
    a: 'first'
  }, {
    a: 'second'
  }, {
    a: 'third'
  }
];
```
...which is what we want, but doesn't seem *right*.

Adding another object to the array...
```coffeescript
[
  a: 'first'
, a: 'second'
, {a: 'third'}
, a: 'fourth'
]
```
...still works...
```javascript
[
  {
    a: 'first'
  }, {
    a: 'second'
  }, {
    a: 'third'
  }, {
    a: 'fourth'
  }
];
```
But adding yet another...
```coffeescript
[
  a: 'first'
, a: 'second'
, {a: 'third'}
, a: 'fourth'
, a: 'fifth'
]
```
...does not...
```javascript
[
  {
    a: 'first'
  }, {
    a: 'second'
  }, {
    a: 'third'
  }, {
    a: 'fourth',
    a: 'fifth'
  }
];
```
In general, the first two and last one of the objects in the array *don't* need to be (but may be) wrapped in braces, and all other objects *do* need to be wrapped in braces. [Except when there are only three objects in the array, in which case either the second or third (or both or all three) need to be wrapped in braces.] For example:
```coffeescript
[
  a: 'first'
, a: 'second'
, {a: 'third'}
, {a: 'fourth'}
, {a: 'fifth'}
, {a: 'sixth'}
, a: 'seventh'
]
```
...transpiles to...
```javascript
[
  {
    a: 'first'
  }, {
    a: 'second'
  }, {
    a: 'third'
  }, {
    a: 'fourth'
  }, {
    a: 'fifth'
  }, {
    a: 'sixth'
  }, {
    a: 'seventh'
  }
];
```
This seems kind of arbitrary! That's OK, coffeescript doesn't have many complications, but this is one. I totally understand if this isn't something that maintainers want to "fix". It just seems that the leading comma works about half-way. To look at it from another perspective, it makes total sense that with no leading commas to dedent out of the object back into the array...
```coffeescript
[
  a: 'first'
  a: 'second'
  a: 'third'
  a: 'fourth'
]
```
...only one object is created...
```javascript
[
  {
    a: 'first',
    a: 'second',
    a: 'third',
    a: 'fourth'
  }
];
```

**Comment by netlovers** [comment]
I always use it like this:
```coffee
[
  a: 'first'
,
  a: 'second'
,
  a: 'third'
]
```
Generates:
```js
[
  {
    a: 'first'
  }, {
    a: 'second'
  }, {
    a: 'third'
  }
];
```

**Comment by jessaustin** [comment]
@netlovers that's good but it uses more lines. Compactness is one of coffeescript's most pleasing attributes.
