### ISSUE TITLE
Feature: Reverse existential assignment

### ISSUE THREAD

**Issue by Aldlevine** [jashkenas/coffeescript#4047]
Instead of writing:

```coffeescript
@a = b ? @a
```

It would be great to have something like a reverse existential assignment.

```coffeescript
@a =? b
```

This would be great for situations where you have a class/object with default properties and you'd like to assign other properties over the defaults if they exist, otherwise leave the defaults.

Thoughts?

**Comment by lydell** [comment]
Duplicate of #3997.

**Comment by Aldlevine** [comment]
@lydell Thanks, I looked but I couldn't find this idea referenced. Too many closed issues to sort through.
