### ISSUE TITLE
CLI: `npm install` should not warn that CoffeeScript prefers global installation

### ISSUE THREAD

**Issue by pjeby** [jashkenas/coffeescript#4049]
In order to publish a usable npm package with CoffeeScript, one must compile it first.  In order to do that, you need coffee-script as a `devDependency`, so that anyone contributing to the package will end up with the same version of the coffee-script package for development and deployment.

Their `npm install`, however, will then result in a warning about global installation, when no global installation is either desirable or necessary (if one has used another build tool or an npm `script` entry in `package.json`, which will both use a local install in _preference_ to a global one).  The warning then becomes noise, either irritating people or teaching them to ignore warnings of this type in general.  (Especially since local installs of the coffee-script package are more frequent than global installs.)

In other words, beginning with npm 2, PR #3415 introduced a spurious warning for all non-commandline uses of the coffee-script package, since it is not really true that the package is "primarily a command-line application".  (The npm shipping with node 0.10 didn't do anything with `preferGlobal`, so the warning only shows up for most people at node 0.12.)

At one point, it was perhaps arguable that the preferred usage of CoffeeScript was as a globally-installed command-line tool.  But for node-related development _today_. it is anything but: best practice for development of node modules is to build via the npm `prepublish` script option (so that downstream developers can build a package from source), which doesn't require a global install even if you use a `coffee` command line in it.  (And of course, different packages may in fact be built with different versions of CoffeeScript, making a global install counterproductive.)

So, the warning is not only unnecessary, it actually advises _against_ what it should be advocating _for_: defining a project-local `devDependency` on the specific version required for that project.  Meanwhile, unless there were lots of people getting confused about global installs before #3415 who _aren't_ getting confused now, it's not clear that the warning is actually benefiting anyone.

(Indeed, other command-line tools such as `gulp` do not include this warning.  Best practice for global command-line development tools nowadays is for the global cli to specifically always invoke the _local_ installation of the same package when run, to ensure the correct version is used.  I don't know if the `coffee` tool should go so far as to do that, but it's an illustration of how far out-of-sync the use of `preferGlobal` is, here.  `preferGlobal` is for things that are _just_ command-line tools, not cli-plus-library things.)

**Comment by splatteredbits** [comment]
I agree. This warning needs to go away.

**Comment by GeoffreyBooth** [comment]
Fixed via #4543.
