### ISSUE TITLE
memory leak in coffescript / nodejs

### ISSUE THREAD

**Issue by nekdolan** [jashkenas/coffeescript#4050]
EDIT: does not leak in OSX

OS Windows 7
NodeJS 0.12.2
Coffeescript 1.9.3

Not sure why this leaks but it is really bad

```javascript
boo = ->
  newPoints = (1 for index in [0..2])
  1

boo2 = ->
  i = 1000
  while i -= 1 >= 0
    boo()
  setTimeout boo2, 0

boo2()
```

The problem is with this line:
```javascript
newPoints = (1 for index in [0..2])
```

In javascript it looks like this:
```javascript
// Generated by CoffeeScript 1.9.3
(function() {
  var boo, boo2;

  boo = function() {
    var index, newPoints;
    newPoints = (function() {
      var j, results;
      results = [];
      for (index = j = 0; j <= 2; index = ++j) {
        results.push(1);
      }
      return results;
    })();
    return 1;
  };

  boo2 = function() {
    var i;
    i = 1000;
    while (i -= 1 >= 0) {
      boo();
    }
    return setTimeout(boo2, 0);
  };

  boo2();

}).call(this);
```
Maybe it is because index is outside the clousure.. dunno...

**Comment by JamenMarz** [comment]
I feel like this is an issue for the node repo, since CoffeeScript compiles to JavaScript, there isn't much we can do besides have it compile to a different set of code (which seems hacky, if it's even possible).

**Comment by JamenMarz** [comment]
Also, perhaps this is just with v8 in general.  You could try it in Chrome and see if it happens.

**Comment by falafflepotatoe** [comment]
does it leak without the setTimeout?

I would guess setTimeout(anycode(), 30) has a lot of potential to leak. the objects are created and probably never collected. (guessing v8 expects the webpage wont run forever?)

perhaps the .call(this) causes the object to not get garbage collected.

**Comment by indera** [comment]
how did you determine that on MacOS it does not have a memory leak?

**Comment by nekdolan** [comment]
I tried it on OSX and looked at memory consumption of the app. It didn't reach 50 Megs and it was very stable.

**Comment by jashkenas** [comment]
It's just javascript, folks.

**Comment by JamenMarz** [comment]
Adding the the above, perhaps it would be good to open / report an issue on V8.
