### ISSUE TITLE
Why existential operator chain returns `undefined` instead of `null`

### ISSUE THREAD

**Issue by zhanzhenzhen** [jashkenas/coffeescript#4051]
Sorry maybe this is a stupid question. But today I found Groovy's nagivation operator and the new C# 6.0 Null-conditional operators both return `null` if the chain is broken. So I suddenly have this question. Maybe just because JavaScript has `undefined`? I also remember in an old ticket @jashkenas said assigning `undefined` to a variable for initialization is bad - we should assign `null` to it instead.

**Comment by vendethiel** [comment]
CoffeeScript doesn't differentiate between `null` and `undefined`
