### ISSUE TITLE
Calling member function of result of if/else

### ISSUE THREAD

**Issue by lorenz** [jashkenas/coffeescript#4053]
I'd like to call a member function on the result of an if/else expression, like that:

``` javascript
if x > 10
  doSomethingAsync()
else
  doSomethingElseAsync()
.then (someValue) ->
```

It works using paranthesis around the whole expression but I think that looks really ugly. It is really cool to use with promises as you can do synchronous flow control on whole async chains. From my point of view nothing prevents that from working, it cannot be ambigous.

Any chance that's getting added?

**Comment by borestad** [comment]
Although I'd rather split up the code, this is a possible solution using underscore. Using lodash would give you lazy execution, but this is the simplest I could come up with.
```
_ switch true
	when x > 10
  	  doSomethingAsync()
	else
	  doSomethingElseAsync()
.tap (value) ->
  console.log value 
```

**Comment by GeoffreyBooth** [comment]
One way without parentheses:

```coffee
result = if x > 10
  doSomethingAsync()
else
  doSomethingElseAsync()
  
result.then (someValue) ->
```

Other than that, I don’t think parentheses are so terrible.
