### ISSUE TITLE
the value of '{x, y} = d' should be {x, y} instead of d

### ISSUE THREAD

**Issue by luochen1990** [jashkenas/coffeescript#4054]
```
alert JSON.stringify ({x, y} = {x: 1, y: 2, z: 3})
```
returns
```
{"x": 1, "y": 2, "z": 3}
```
which should be
```
{"x": 1, "y": 2}
```
So that when we want to extract some fileds from an Object, we can write it like this:
```
r = ({x, y} = d)
```

you can try that [here](http://coffeescript.org/#try:alert%20JSON.stringify%20(%7Bx%2C%20y%7D%20%3D%20%7Bx%3A%201%2C%20y%3A%202%2C%20z%3A%203%7D)%0A)

**Comment by michaelficarra** [comment]
Assignment always produces the RHS. You're looking for a different operation, not assignment. See previous issues that have requested this for more info.
