### ISSUE TITLE
/usr/bin/env node no such file or directory

### ISSUE THREAD

**Issue by puzzl3r** [jashkenas/coffeescript#4057]
Not sure if I should report it here. When running a coffee script as root ran into this problem. 

    /usr/bin/env node no such file or directory

This is because coffee uses shebang points to node that's in /usr/bin. But it's actually installed under /usr/local/bin. I've to `ln` it to the correct directly.

    pi@foobar-rpi:~$ vim /tmp/picam.log
    pi@foobar-rpi:~$ coffee --version
    CoffeeScript version 1.9.3
    pi@foobar-rpi:~$ node --version
    v0.12.6
    pi@foobar-rpi:~$ cat /usr/local/bin/coffee
    #!/usr/bin/env node
    
    var path = require('path');
    var fs   = require('fs');
    var lib  = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');
    
    require(lib + '/coffee-script/command').run();
    pi@foobar-rpi:~$
    pi@foobar-rpi:~$ which node
    /usr/local/bin/node
    pi@foobar-rpi:~$ which nodejs
    /usr/bin/nodejs
    pi@foobar-rpi:~$ which coffee
    /usr/local/bin/coffee
    pi@foobar-rpi:~$ uname -a
    Linux foobar-rpi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux

**Comment by michaelficarra** [comment]
Try `which env` and `type /usr/bin/env`. Then run `/usr/bin/env node`.
