### ISSUE TITLE
Promote CoffeeShop for Learning CoffeeScript.

### ISSUE THREAD

**Issue by carlsmith** [jashkenas/coffeescript#4060]
I've been working on CoffeeShop, on and off, for nearly a year now, and it has come a long way. It offers important features that are not available in other CoffeeScript shells.

CoffeeShop has really good tracebacks. Each item in the stack is clickable, to reveal the compiled JS. The error in both the CS and the JS are highlighted. No other shell does tracebacks as nicely.

CoffeeShop is graphical. You can output strings or DOM to stdout, so you can print anything, from HTML forms to web components. Standard out is just a DOM element, so you can output a UI widget, then bind event listeners to it and so on. It's just regular web programming, in a shell.

CoffeeShop allows you to create and edit files, which you can also publish as little, stand-alone web apps.

There are lots of other features, but having proper tracebacks, having a DOM, and being able to write and publish scripts are the killers.

I would recommend using CoffeeShop as the main CoffeeScript shell on coffeescript.org, but there are a couple of reasons why it would be a poor choice for that. Firstly, it only works in Chrome [and Opera]. The other browsers lack features CoffeeShop depends on. Secondly, it has a dozen functions and half a dozen keyboard shortcuts that you need to spend some time getting comfortable with to really use the shell well.

CoffeeShop is easily the best environment for learning and exploring CoffeeScript. Can we promote CoffeeShop [on coffeescript.org] as the recommended way to learn CoffeeScript? If not, what would it take?

~ [Try CoffeeShop](https://coshmain.github.io) ~

**Comment by jashkenas** [comment]
I agree that replacing the shell with a not-totally-compatible one would be foolish. How about starting with a link + description for the "Examples" list?

**Comment by carlsmith** [comment]
The Examples list on coffeescript.org? That section currently just has options for using the CoffeeScript shell in a terminal, and cosh is a webapp, but yeah, adding a link and description at the bottom of that section would be great, if that's what you're thinking?

Really, it's just that I don't want to start telling people that it's the best app to use for exploring CoffeeScript if I made it and am the only guy who thinks that. If it had a little prop on the site, that'd make it feel kind of accepted by the community, and obvious helps with getting new users.

Thanks for considering it by the way.

**Comment by carlsmith** [comment]
Given the lack of general interest, it seems best to leave this for now. Thank you @jashkenas for looking at it. Appreciated.
