### ISSUE TITLE
"@" with no property compiles to "this", without the dot accessor symbol

### ISSUE THREAD

**Issue by macgyver** [jashkenas/coffeescript#4061]
More of a question than an issue, but the only reference to `@` in the Coffeescript documentation is this:
>As a shortcut for `this.property`, you can use `@property`.

You can also use `@` as a replacement for `this`, e.g:

```coffeescript
  render: ->
    ...
    @
```

I guess it's an undocumented feature... in your opinion is this a good practice? Is it safe to use or could it change in future versions?

**Comment by vendethiel** [comment]
This has been discussed to great length here: #1601 (and some other issues)

**Comment by macgyver** [comment]
Great, thanks @ven for the link.

**Comment by vendethiel** [comment]
I don't think poor @ven wants to be mentioned here ;)

**Comment by macgyver** [comment]
Lol, I mixed up the display name and the user name
