### ISSUE TITLE
propose a functional let grammar

### ISSUE THREAD

**Issue by winterland1989** [jashkenas/coffeescript#4062]
Here is my little proposal to bring `let` into coffee:
- let ... in statements

``` coffee
zipWith = (xs, ys, fn) ->
  result = []
  let xl = xs.length, yl = y.length in
    if xl >= yl
       ...
    else 
       ...
  result
```

will be compiled to

``` js
var zipWith = function(xs, ys, fn){
  var result = []
  {
    let xl = xs.length, yl = y.length;
    if(xl >= yl){
       ...
    }else{
       ...
    }
  }
  return result;
}
```
- let ... in expressions

always turn them into a IIFE, just like a `do` notion.
- special for let

``` coffee
for let i in [1..100]
  ...
```

will be compiled to

``` js
for(let i = 1; i<=100; i++){
  ...
}
```

**Comment by michaelficarra** [comment]
I'm all for the first part of this proposal, with a few notes.

* CoffeeScript will not be targeting ES2015 any time soon, so we will emit IIFEs for the foreseeable future
* We used to automatically capture loop variables that were closed over. Now, users are expected to manually capture them using this syntax, which isn't far off from what you propose:

    ```coffee
    for a in b then do a =>
      ...
    ```

A related tip: when making proposals like this, try to keep them limited to the basic functionality that you require. Adding on these semi-related concepts only confuses the message and distracts conversation, ultimately hurting your proposal's chances. The only thing I'd recommend including with your proposal next time is usage examples.

**Comment by vendethiel** [comment]
There's an issue about `for let`: #2518

**Comment by michaelficarra** [comment]
Good, then we can safely ignore that part of this proposal. On the remaining `let a = b in ...` part, I prefer it to `do (a = b) => ...` syntactically, but I don't know if that is enough to warrant adding what is essentially sugar for something we already have.

**Comment by winterland1989** [comment]
Sorry for not bringing such simple idea clearly, my original purpose is trying to bring es2015 feature `let` into language, after reading your suggestion, it looked like it's better to directly add  `let..in` and `for let` and translate to `let` version, just like how we bring into `yeild`, use it or not is depended on user's own choice.

You can continue use `for a in b then do a =>` to emit an IIFE if you want, this proposal is just a clean way to write `let` in coffee IMO.

BTW, i don't miss any other features in es2015 anyway, but `let` is a nice feature IMO, so let's do this : )

**Comment by winterland1989** [comment]
Proposal updated, does it look ok to you?

**Comment by GeoffreyBooth** [comment]
http://coffeescript.org/v2/#unsupported-let-const
