### ISSUE TITLE
Dynamic keys for objects

### ISSUE THREAD

**Issue by delijah** [jashkenas/coffeescript#4063]
Hey!

I'd like to propose an easy syntax to define objects with dynamic keys. I would suggest to implement it the same way, ES6 has already in it's draft:

Old:
-- 
    theKey = 123
    a = {}
    a[theKey] = "b"
    console.log a.123 # = "b"

New:
--
    theKey = 123
    a = [theKey]: "b"
    console.log a.123 # = "b"

As discussed on: http://stackoverflow.com/questions/19837916/javascript-creating-object-with-dynamic-keys

We could use that on MANY MANY parts of our code and could decrease amount and complexity of it largely!

Cheers

**Comment by michaelficarra** [comment]
You're looking for `a = "#{theKey}": "b"`.

**Comment by delijah** [comment]
Awesome! Thank you! Did not find this in the docs though.

**Comment by lydell** [comment]
It might be a bit difficult to find, but it _is_ mentioned in the docs, in the [String Interpolation, Block Strings, and Block Comments](http://coffeescript.org/#strings):

> You may even use interpolation in object keys.

**Comment by delijah** [comment]
I knew that notation for strings already, and yes it is in the docs. But i didn't know, that you can use #{} for keys in object declarations as well. That particular case i did not find in the docs ;)
