### ISSUE TITLE
Broken link for "High-Rez Logo download "

### ISSUE THREAD

**Issue by SusanthCom** [jashkenas/coffeescript#4064]
// low priority,  website update

at https://github.com/jashkenas/coffeescript/downloads
on clicking "coffeescript-logo.zip" it results, >> File was not found.

**Comment by jashkenas** [comment]
I think GitHub killed it off.

https://github.com/blog/1302-goodbye-uploads

I'll delete 'em.

**Comment by SusanthCom** [comment]
Thanks @jashkenas
is there any way to get "coffeescript-logo.zip" ? 
we need it to print seminar banners. graphics are good promotional materials.

**Comment by jashkenas** [comment]
Here it is.

http://cl.ly/Ylug
