### ISSUE TITLE
Compiler changes variable name

### ISSUE THREAD

**Issue by genu** [jashkenas/coffeescript#4065]
This may be a bug, but I'm not sure why the compiler is changing the variable name if two classes share the same name. For example:

````
class classA
  aMethod: ->
    aMethod.doSomething( param: (paramA) -> console.log("test"))

class classB
  constructor: (@paramA) ->
````

compiles to:
```javascript
var classA, classB;

classA = (function() {
  function classA() {}

  classA.prototype.aMethod = function() {
    return aMethod.doSomething({
      param: function(paramA) {
        return console.log("test");
      }
    });
  };

  return classA;

})();

classB = (function() {
  function classB(paramA1) {
    this.paramA = paramA1;
  }

  return classB;

})();
````

Why is `paramA` in classB renamed to `paramA1`?

This problem would impact angular apps which the angular dependency injection mechanism relies on the proper naming of the parameters.

-Eugen

**Comment by lydell** [comment]
See https://github.com/jashkenas/coffeescript/issues/3891#issuecomment-93401849.
