### ISSUE TITLE
[proposal] treat indented lines as arguments list

### ISSUE THREAD

**Issue by metalim** [jashkenas/coffeescript#4067]
Current syntax (cc.sequence with 3 arguments):

```coffee
anims.push cc.repeatForever cc.sequence cc.delayTime(10 + _random 20),
	cc.moveBy(0.3, 0, 400),
	cc.moveBy 3, 0, -400
```
Proposed syntax (currently gives "Error on line 2: unexpected indentation"):

```coffee
anims.push cc.repeatForever cc.sequence
	cc.delayTime 10 + _random 20
	cc.moveBy 0.3, 0, 400
	cc.moveBy 3, 0, -400
```

**Comment by jashkenas** [comment]
Nope. Here's why:

    sequence
      first()
      second()
       third()

vs.

    if sequence
      first()
      second()
      third()

**Comment by metalim** [comment]
Thing is: it already works if argument is Object:

```
func
  a: 1
  b: 2
```

compiles to

```
func({
  a: 1,
  b: 2
});
```

While

```
if func
  a: 1
  b: 2
```

compiles to

```
if (func) {
  ({
    a: 1,
    b: 2
  });
}
```
