### ISSUE TITLE
Lone expansion: Bad error message

### ISSUE THREAD

**Issue by lydell** [jashkenas/coffeescript#4070]
Lone expansions `[...]=a` are not allowed in CoffeeScript, and there are tests for this. However, the tests only check that the compiler throws—not _what_ it throws—which has slipped through a bad error message:

    $ coffee -bpe '[...]=a'
    [stdin]:1:2: error: Expansion must be used inside a destructuring assignment or parameter list
    [...]=a
     ^^^

That _is_ inside a destructuring assignment.

I see two things that can be done here:

- Since `[]=a` is allowed, an easy and consistent (IMO) way would be to make `[...]=a` equivalent to
`[]=a`. I initially implemented this as part of #4069.

- Improve the error message. “lone expansion is not allowed”

Which one is better? I’ll whip up a PR as soon as we’ve decided.

**Comment by lydell** [comment]
Meh. I found it was just as easy both way, so I went ahead and created a PR preserving the current semantics. No need to decide on anything.

**Comment by jashkenas** [comment]
Both ways make sense to me. It's bad code either way.

If you choose the error message route, let's make it read: "Destructuring assignment has no target", or something along those lines.

**Comment by lydell** [comment]
@jashkenas I’ve updated the PR with your error message now.
