### ISSUE TITLE
Allow underscores in large numbers similar to Ruby

### ISSUE THREAD

**Issue by ezekg** [jashkenas/coffeescript#4072]
I searched and searched, and surprisingly, I couldn't find an existing feature request for this. As I've been getting more involved in WebGL and Canvas, it's been a growing challenge to deal with large numbers i.e. `100000`. Is that 10,000 or 100,000? Allowing a syntax similar to Ruby where you can add underscores into the number in place of commas would be grand.

Example:
```ruby
large_num = 1_000_000_000
puts large_num #=> 1000000000
```

The underscore `_` is ignored and used for readability, so `10_000` is equivalent to 10,000 (or `10000` in JavaScript-land). This allows for a huge increase in readability.

Thoughts? (Forgive me if some of these numbers are off by a `0` – I hope you can see the problem.)

**Comment by vendethiel** [comment]
I'm not sure you searched, I pasted your title in the "search" bar and found #632

**Comment by ezekg** [comment]
Sorry, I guess I was just searching "underscores" and "underscores integers". I didn't try "underscore numbers". Thanks for the link.

**Comment by vendethiel** [comment]
Sorry, I didn't mean it that way. Search engines (usually) don't understand synonyms.

**Comment by ezekg** [comment]
No problem. I did look at the first few pages of my "underscores" search. Didn't mean to create a duplicate issue. Thanks for the link though. Looks like it came to consensus... sort of.
