### ISSUE TITLE
Specify start index in for loop.

### ISSUE THREAD

**Issue by DylanPiercey** [jashkenas/coffeescript#4076]
Currently there is not (that I know of) a clean and performant way to specify where to start in a `for in` loop.

Available options:

```coffeescript
arr = [1, 2, 3]
# all loops skip first two.


for i in [2...arr.length] by 1
    item = arr[i] # sad non coffee-esc syntax
    # do stuff...

for item, i in arr[2..]
    # i is not the real index.
    # we created a copy of the array for no reason.
    # do stuff...
  
```

I am proposing something like this

```coffeescript
for item, i in arr from 2
    # from just specifies initial value for i.
    # i is the correct index and no intermediary arrays created.
```

`from` could easily be skip or something else.

**Comment by jashkenas** [comment]
for i in arr
      continue if i < 2

**Comment by DylanPiercey** [comment]
@jashkenas that is a better solution. Thanks.

To bad it adds an "if" to every iteration, but it's not as bad as copying the array.

**Comment by lydell** [comment]
```coffee
for item, i in arr when i >= 2
  ...
```

**Comment by DylanPiercey** [comment]
@lydell same deal :p.

**Comment by kemicofa** [comment]
Any updates regarding this?

**Comment by Inve1951** [comment]
This should be fine.
```coffee
for i in [2...arr.length] by 1
  item = arr[i]
  # do stuff...
```
Has you write a little more code but adds no overhead to the js.
