### ISSUE TITLE
Backticks within embedded JavaScript

### ISSUE THREAD

**Issue by guigrpa** [jashkenas/coffeescript#4086]
I'm trying to use Facebook's Relay framework in CoffeeScript, but Relay uses ES6 template strings and they seem to be incompatible with CoffeeScript.

I've tried to embed those template strings in CoffeeScript, but the template's backticks can't be escaped, or am I missing something?

Would it be possible in CoffeeScript to delimit embedded JavaScript using something in the line of multiline comments (###), say ```?

**Comment by jarkonik** [comment]
This feature has already been requested here: https://github.com/jashkenas/coffeescript/issues/1504

**Comment by vendethiel** [comment]
Seems like it. Thanks @jarkonik
