### ISSUE TITLE
Proposal: Existential Splat

### ISSUE THREAD

**Issue by olleicua** [jashkenas/coffeescript#4091]
I really want an existential splat operator:

``` coffee
a(b, c...)
```

compiles to

``` javascript
a.apply(null, [b].concat(slice.call(c)));
```

which fails when `c` is `null` or `undefined`

It would be nice to have a syntax like:

``` coffee
a(b, c?...)
```

compiles to

``` javascript
a.apply(null, typeof c !== "undefined" && c !== null ? [b].concat(slice.call(c)) : [b]);
```

Is there any reason not to do this?

**Comment by olleicua** [comment]
I'm looking into implementing this.  It's tricky for a couple of reasons:

When I tried the naive solution:

```coffee
  # A splat that occurs outside of a parameter list.
  Splat: [
    o 'Expression ? ...',                       -> new Splat new Existence $1
    o 'Expression ...',                         -> new Splat $1
  ]
```

Jison gives me a grammar conflict:

```
Conflict in grammar: multiple actions possible when lookahead token is ... in state 243
- reduce by rule: Operation -> Expression ?
- shift token (then go to state 293)

States with conflicts:
State 243
  Operation -> Expression ? . #lookaheads= ... .. , ] FOR UNTIL WHILE POST_IF RELATION LOGIC COMPARE SHIFT ** MATH - + ? INDENT TERMINATOR CALL_END OUTDENT
  Splat -> Expression ? .... #lookaheads= ] , TERMINATOR INDENT CALL_END OUTDENT
```

The best solution I can think of is to modify the lexer to pick out `?...` as a separate token.  I'm currently pouring over the lexer to see if I can figure out how best to do that.

Also, I'm realizing that the existing `Existence` node isn't quite what I want because I want `null` and `undefined` to be replace with `[]`.  In light of this I'm guessing I will either need to modify the `Splat` node or make a new `ExistentialSplat` node.  The latter seems less likely to interfere with existing code.

Any advice or direction on this would be greatly appreciated.

**Comment by lydell** [comment]
I think it make sense to lex `?...` as a single token, just like `?.` is.

**Comment by michaelficarra** [comment]
Are `.`, `..`, and `...` not lexed individually (and greedily)?

**Comment by jashkenas** [comment]
> Is there any reason not to do this?

The main reason not to do this is because it probably isn't obvious what it does when you read it. 

... Or perhaps it is.

**Comment by olleicua** [comment]
@michaelficarra Unless I'm missing something the grammar conflict message Jison gave me implies they are not.

**Comment by michaelficarra** [comment]
Well doing that would probably resolve this conflict. It would disambiguate it by preferring the longest stretch of dots.

**Comment by olleicua** [comment]
I got the lexer working now I'm trying to understand the logic in nodes.coffee that compiles splats:

https://github.com/olleicua/coffeescript/commit/1a366b3359740bcddbf41a5874c349bf4ce14013

I'm pretty sure the code I want to change is at `nodes.coffee:707` but it may also be at `nodes.coffee:1571`.  In any event, I'm a bit confused by both parts of the code but I'll keep staring at them.  In the mean time if anyone with more familiarity with this code has any pointers that would be most helpful.

**Comment by xixixao** [comment]
Although tiny bit slower, but not requiring any new syntax:
```coffee
a(b, (c ? [])...)
```
Similar to #2040 (suggested somewhere else before I'm sure). That also happens much more often (thanks to `.match` and likes).

**Comment by GeoffreyBooth** [comment]
Closing due to lack of interest and the existence of a workaround (see [@xixixao’s comment](https://github.com/jashkenas/coffeescript/issues/4091#issuecomment-143371818)).
