### ISSUE TITLE
Generator access by interactor support 

### ISSUE THREAD

**Issue by davidNHK** [jashkenas/coffeescript#4100]
I attempt use ES6 new feature which is generator function (yield) and read it by for...loop
In javascript i can simple write below : 
```
function* hello(){
    var i = 10;
    for (var j =0 ;j<i;j++){
        yield j
    }
}

for(var i of hello()){
    console.log(i)
}
```

In coffeescript:
```
hello = ()->
    for i in [0..10]
        yield i
    return
for i of hello()->
    console.log i
```

coffee script nothing output.... this is due to compiled js still using for...in instead of for...of, currently i just using embed javascript to solve this problem , could you please fix it ?

**Comment by lydell** [comment]
Duplicate of #3832.
