### ISSUE TITLE
Update coffee-script-source gem for 1.10.0

### ISSUE THREAD

**Issue by tony** [jashkenas/coffeescript#4106]
(I may be looking or asking in the wrong place, I can't find where the coffee-script-source repo is, but other issues refer to it.)

http://coffeescript.org/#1.10.0

https://rubygems.org/gems/coffee-script-source is still at 1.9.1.1.

**Comment by vendethiel** [comment]
Paging @josh for this one!

**Comment by JuanitoFatas** [comment]
@tony 1.10.0 is released. So can close this issue.

But I also wonder where the source repository is. @josh Could you tell us where the source code repository is? Thank you.

**Comment by ryoqun** [comment]
well, I had stumbled on this issue too... https://gitter.im/rails/rails?at=55dd56f704a673003162ba60

Where exactly does the gem come from?
