### ISSUE TITLE
could the -> replaced by ::

### ISSUE THREAD

**Issue by biolee** [jashkenas/coffeescript#4107]

**Comment by vendethiel** [comment]
What does that mean? Use a `::` operator to define a function? That's taken already.

**Comment by biolee** [comment]
@vendethiel sorry  `:::` 
`->` is not easy to type

**Comment by vendethiel** [comment]
-> uses 3 keypresses (one is shift). ::: is 4 keypresses (one is shift, and you have to hold it). Anyways, this is not gonna change 4 years after the fact.

**Comment by carlsmith** [comment]
Typing `->` feels pretty natural before long.

**Comment by shanemikel** [comment]
not to mention it looks nice and functional, many functional languages use this operator

safeCall = (fn) -> (obj) -> fn? obj
Why would you want to remove ^ that?
