### ISSUE TITLE
Elvis operator

### ISSUE THREAD

**Issue by JamenMarz** [jashkenas/coffeescript#4108]
The [Elvis operator](https://en.wikipedia.org/wiki/Elvis_operator) is a shorthand ternary for checking a defined and non-null value, then resorting to a second value as a fallback.

Take this piece from the Wiki artical:

> ... which evaluates to `foo` if `foo` exists and has a non-null value, then `var = foo;` otherwise `var = bar`.

So essentially:

```coffeescript
example = foo ?: bar
```

to

```javascript
var example = (typeof foo !== 'undefined' && foo ? foo : bar);
```

Which follows the spread out logic of:

```javascript
var example;
if (typeof foo !== 'undefined' && foo) {
  example = foo;
} else {
  example = bar;
}
```

**Comment by vendethiel** [comment]
Basically, our `?` operator:

```coffee
example = foo ? bar
```

**Comment by JamenMarz** [comment]
Yup, that's exactly what the operator does, my bad.
