### ISSUE TITLE
Multiline string still seeing indentation spaces

### ISSUE THREAD

**Issue by ghostsquad** [jashkenas/coffeescript#4110]
```Coffeescript
describe 'this is just a test', () ->
  console.log "this should look
    like a normal
    sentence"
```

#actual output:
`this should look    like a normal    sentence`

#compiled looks fine:
```Javascript
(function() {
  describe('this is just a test', function() {
    return console.log("this should look like a normal sentence");
  });

}).call(this);
```
![capture](https://cloud.githubusercontent.com/assets/903488/10112371/7557a090-638f-11e5-8d62-4ef649282559.PNG)

**Comment by xixixao** [comment]
@ghostsquad Are you sure the version of CoffeeScript that is used by your mocha set up is current? The compilation of multiline double-quoted strings changed in 1.7.

**Comment by ghostsquad** [comment]
I'm on the latest version. 1.10 I believe

**Comment by lydell** [comment]
Try to also log `3 ** 2`. If you see a 9, then we at least know you're running 1.7, bcause that's when exponentiation was added, too. If you get an error you're definitely running some older version.

**Comment by ghostsquad** [comment]
running 'grunt'
grunt-contrib-coffee is with the headers options shows `// Generated by CoffeeScript 1.9.3`
and I get an error
```
Running "mochaTest:unit" (mochaTest) task
>> Mocha exploded!
>> Error: In C:\dev\twobit\test\unit\foo.coffee, Parse error on line 6: Unexpected 'MATH'
```

if I just run "mocha" though, the test passes, and I get the result of `9`.

so, this sounds like I have various different modules all running different versions of CoffeeScript.

Grunt-Mocha-Test which is what I have in my grunt file, and it is using coffeescript 1.8
https://github.com/pghalliday/grunt-mocha-test/blob/master/package.json

Mocha is also using coffeescript 1.8 (for dev, maybe this isn't an issue)
https://github.com/mochajs/mocha/blob/master/package.json

as stated above, grunt-contrib-coffee is using coffeescript 1.93
https://github.com/gruntjs/grunt-contrib-coffee/blob/master/package.json

how do I unify all these things?

**Comment by ghostsquad** [comment]
I had a feeling that this problem would require the authors of these grunt modules to fix it. Switched to Gulp, seems to have resolved this.
