### ISSUE TITLE
Existential operator doesn't include undefined check when used with an expression containing an @ symbol

### ISSUE THREAD

**Issue by ManniCS** [jashkenas/coffeescript#4117]
`fromName = (@refs.fromName.state.value) ? @props.fromName` compiles to 

```
var fromName, ref;

fromName = (ref = this.refs.fromName.state.value) != null ? ref : this.props.fromName;
```
Is this intended behavior? It seems to me that it should also do a `typeof !== "undefined"` check, as `a = undefined` returns `undefined`. 

`b = a ? c` compiles to 

```
var b;

b = typeof a !== "undefined" && a !== null ? a : c;
```
so this seems to be a problem with using the @ symbol as part of a variable upon which the existential operator is operating.

**Comment by jussiry** [comment]
Notice the difference between !== and != operator. null == undefined is true, so it don't matter if you compare it to null or undefined.

**Comment by vendethiel** [comment]
..As explained in our FAQ (see our wiki).
