### ISSUE TITLE
using for..of with do, doesn't behave as expected (newbie disclaimer)

### ISSUE THREAD

**Issue by shanemikel** [jashkenas/coffeescript#4118]
I'm new to using coffeescript, so thanks for this first of all.  It's got it's nuances, but overall a beautiful language.

I would like to point out I've had some troubling experience with the way the do operator works
consider:

    for own key, symbol of LEVELS
        do (key, val) -> makeGetter key, get: -> return val

That compiles to:

    fn1 = function(key, val) {
      return makeGetter(key, {
        get: function() {
          return val;
        }
      });
    };
    for (key in LEVELS) {
      if (!hasProp.call(LEVELS, key)) continue;
      symbol = LEVELS[key];
      fn1(key, val);
    }

(Which wouldn't work in this case)

where I would actually expect the parameters named after the do operator, to only be relevant to the names they're given in the function definition.

The actual behavior would be more clear if the names weren't required to look like a function parameter definition, but could be passed without parens as if they were arguments to the do op.

**Comment by vendethiel** [comment]
I'm not sure what you mean. The fact that `key` and `symbol` exist in the outer scope is the thing that bugs you?

**Comment by shanemikel** [comment]
what I'm saying, is I would expect the original coffee code to compile to this:

    fn1 = function(key, val) {
      return makeGetter(key, {
        get: function() {
          return val;
        }
      });
    };
    for (key in LEVELS) {
      if (!hasProp.call(LEVELS, key)) continue;
      symbol = LEVELS[key];
      fn1(key, symbol);
    }

**Comment by vendethiel** [comment]
Those are global variables. They shouldn't be. What's the issue?

**Comment by connec** [comment]
There is no relationship between the `for` variables and the `do` arguments.  If you look at the compilation of your `do` by itself:

```js
// do (key, val) -> makeGetter key, get: -> return val
(function(key, val) {
  return makeGetter(key, {
    get: function() {
      return val;
    }
  });
})(key, val);
```

Notice that `(key, val)` val are the argument names. This doesn't change when you use `do` in a loop.

You can rewrite your code to:

```coffee
for own key, symbol of LEVELS
    do (key, symbol) -> makeGetter key, get: -> return symbol

# OR, more clearly?

for own key, symbol of LEVELS then do (key, symbol) ->
  makeGetter key, get: -> symbol
```

**Comment by shanemikel** [comment]
Okay, well I figured it out, and there's no need to dwell on the issue.  Perhaps it's more productive to figure out if this is clearly described in the language guide?  But I guess it's just as easy to look at the generated code.

**Comment by connec** [comment]
See #2518 for some discussion about `for` and `do`, in particular.
