### ISSUE TITLE
Should nameless classes be allowed?

### ISSUE THREAD

**Issue by swang** [jashkenas/coffeescript#4119]
I'm not really sure if this problem should be called anonymous classes since that's an actual used term so I used nameless instead.

This seems fine
```coffeescript
class A extends B
    C: ->
        'Hello World'
```
This even makes some sense.
```coffeescript
A = class extends B
    C: ->
        'Hello World'
```
But why is this valid?
```coffeescript
class extends B
    C: ->
        'Hello World'
```
or this:
```coffeescript
class
    C: ->
        'Hello World'
```
I can grok internally why those last two can/would generate valid code but essentially it's generating code that will never be used.

**Comment by vendethiel** [comment]
The compiler doesn't check that you don't throw values away -- ever. This could be at the end of a function, and get returned.

**Comment by KenanSulayman** [comment]
Just think deeper..

```
(new class
    constructor: ->
        # sup

    identify: (args) ->
    	do_something(args)
).identify
	type: 'customer'
	recurring: true
```
