### ISSUE TITLE
Souce map for several source files in coffee-script.js

### ISSUE THREAD

**Issue by off-border** [jashkenas/coffeescript#4121]
when I trying to use more than one .coffee file

```
<script data-src="js/file1.coffee"      type="text/coffeescript"></script>
<script data-src="js/file2.coffee"      type="text/coffeescript" ></script>

<script src="lib/coffee-script.js"></script>
```

The content of the 1st script is:

```
console.log 'file1'
```

The content of the 2st script is:

```
console.log 'file1'
```

I get the source map for the 1st file only. And all runtime errors and output in the chrome console refer to an unexisting last string file1.coffee

And the console output is:

```
file1        file1.coffee:1 
file2        file1.coffee:1 
```

**Comment by GeoffreyBooth** [comment]
The source map implementation has been refactored since this issue was opened, including improvements to tracking filenames. If the above is still an issue in 2.0.0-beta1 or later, please comment and I can reopen.
