### ISSUE TITLE
CallBack HELL solution for CoffeeScript

### ISSUE THREAD

**Issue by SusanthCom** [jashkenas/coffeescript#4122]
##### Enhancement Request

Is it possible to have some solution for **CallBack HELL** built into CoffeeScript ?

[IcedCoffeeScript (ICS)](http://maxtaco.github.io/coffee-script/) solution is this

> IcedCoffeeScript (ICS) adds two new keywords: **await** and **defer**. These additions simply and powerfully > streamline asynchronous control flow, both on the server and on the browser. Say goodbye to callback > pyramids; say adios to massive code rewrites when synchronization requirements change slightly. Say > hello to clean, readable, maintainable control flow for network and asynchronous operations!

```CoffeeScript
# Search for 'keyword' on twitter, then callback 'cb'
# with the results found.
search = (keyword, cb) ->
  host = "http://search.twitter.com/"
  url = "#{host}/search.json?q=#{keyword}&callback=?"
  await $.getJSON url, defer json
  cb json.results
```

```CoffeeScript
# Search for 'keywords' in parallel, then callback
# 'cb' with an array of the parallel results
parallelSearch = (keywords, cb) ->
  out = []
  await 
    for k,i in keywords
      search k, defer out[i]
  cb out
```

```CoffeeScript
# Search for 'keywords' in serial, then callback
# 'cb' with an array of the parallel results
serialSearch = (keywords, cb) ->
  out = []
  for k,i in keywords
    await search k, defer out[i]
  cb out
```
@jashkenas  Many Many Thanks for your Wonderful Works :heart:

**Comment by vendethiel** [comment]
Something like Iced with such a complicated compilation scheme probably won't fly, but see #2762. (and #2662, #1942)

**Comment by SusanthCom** [comment]
Thanks Ven ( @vendethiel ) for quick response.  
Checked  those links >  #2762. (and #2662, #1942)

 Hope Promises is the future :+1: - [BlueBird](https://github.com/petkaantonov/bluebird) or similar one. 

Thanking you all CoffeeScript Team :heart:
