### ISSUE TITLE
Example from coffeescript.org is not working anymore.

### ISSUE THREAD

**Issue by korostelev** [jashkenas/coffeescript#4123]
Destructuring assignment example from http://coffeescript.org/ is not compatible with version 1.10.0:

    class Person
        constructor: (options) ->
        {@name, @age, @height = 'average'} = options

    tim = new Person name: 'Tim', age: 4

Please update manual.

**Comment by vendethiel** [comment]
Your indentation is wrong.

**Comment by korostelev** [comment]
![cs](https://cloud.githubusercontent.com/assets/3258871/10410828/7014291e-6f6f-11e5-924c-30df36258470.png)

**Comment by korostelev** [comment]
It was a wrong copy/paste, but issue is still occurs.

**Comment by korostelev** [comment]
![cs](https://cloud.githubusercontent.com/assets/3258871/10410857/3b76e244-6f71-11e5-89da-ac6ed2ad6e99.png)

**Comment by vendethiel** [comment]
What's your CoffeeScript version?

**Comment by korostelev** [comment]
Sorry, my mistake, I didn't update coffee-script globally.
Version 1.9.2 - error, Version 1.10.0 - OK.
