### ISSUE TITLE
Multi-line function header definitionion

### ISSUE THREAD

**Issue by googoid** [jashkenas/coffeescript#4128]
Hey everybody,

Recently found a problem with syntax highlighters.

I was playing with coffee's lexical scopes like `do (somevar = null) ->` and the count my scope variables became too many and I decided to split the definition into multiple lines like so:

```coffee
do (somevar = null, someothervar = 'hello',
    somenumber = 1231, somedoublenumber = 31.123) ->

    'hey dude'
```

Compiler didn't complain about the syntax and everything is working fine but the problem is syntax highlighting. I was not able to find an editor which would highlight that correctly. 
I tried Sublime/TextMate and some online highlighters. 
I even tried custom .tmLanguage but was not able to achieve desired results, because the beginning of definition is ambiguous, `(` may mean function call, group etc.

Some example screenshots (Sublime Text 3)

**Correct:**
![image](https://cloud.githubusercontent.com/assets/4312868/10558520/3edcd4b6-74da-11e5-9f99-e9d5ad69154d.png)

**Incorrect:**
![image](https://cloud.githubusercontent.com/assets/4312868/10558524/57ee95b6-74da-11e5-96e7-9ee5d8f1012c.png)

Anyone came across any solution?

Thanks in advance!

**Comment by vendethiel** [comment]
Please open the issue at https://github.com/jashkenas/coffee-script-tmbundle instead, this one github project is the compiler.
