### ISSUE TITLE
functional programming features -- currying and common algebraic functions

### ISSUE THREAD

**Issue by ccorcos** [jashkenas/coffeescript#4138]
I've been learning a lot about functional programming lately and I just had a radical idea of adding some sweet features -- I'm curious if there are any people who know they way around the coffeescript source that are interested.

In functional programming land, all functions should be fixed arity. And in javascript, you can inspect the number of arguments a function expects with function.length. Thus, you can create a high order function that curries your functions for you. Imagine this being baked right into coffeescript.

```coffee
add = (a,b) -> a+b
add1 = add(1)
result = add1(10)
```

compiles to:

```js
var add = CS.curry(function(a,b) { return a + b })
var add1 = add(1)
var result = add1(10)
```

or maybe it would be something more like this since I'm pretty sure coffeescript compiles directly without any helper functions...

```js
var add = function() {
  var _add = function(a,b) { return a + b }
  var args = arguments.slice(0)
  if (args.length < _add.length) {
    return function() {
      return add.apply(this, args.concat(arguments.slice(0))) 
    }
  } else {
    return _add.apply(this, args)
  }
}
```

Maybe you could use `~>` to auto-curry for your if you dont want to pollute `->`.

The other feature that would be sweet if common algebraic methods like map, concat, filter, reduce, etc. were baked right into the language. Thus I could do something like this:

```cofffee
inc = (x) -> x + 1
map(inc, list)
```

which compiles to:

```js
list.map(inc)
```

Now, if you wanted to further, you could curry map, and fill in some other common methods like `pipe`, `compose`, etc. The "readable" javascript gets a little less readable at this point though...

Anyways, I'm curious what you guys think. Its a pretty radical idea, but I think it would be really sweet it were well thought-out and perhaps a little less radical.r

**Comment by vendethiel** [comment]
LiveScript has such things (curry is `-->`, fwiw). For the other request: what's the point of language-baked functions? Just include underscore, lodash, prelude, whatever else floats your boat :).

**Comment by bjmiller** [comment]
It was decided a while back that these features should be library-level, and not language-level.  You might try looking at Livescript, which does include features like you're describing.

**Comment by ccorcos** [comment]
I use Ramda.js a lot. And it has all this stuff. R.curry, R.map, R.concat, etc. But you have to be diligent as a developer to keep with these patterns. Its easy to stray away from good patterns when you're language is SO damn flexible. Its the good and the evil of javascript...

More than anything, I think it would just be stylistic. Functions like map, filter and reduce would get special syntax highlighting. And as soon as I use a high-order function like R.curry, the highlighter no longer recognizes the return value as a function -- lol, I'm realizing that syntax highlighting is a big part of this motivation for me. But more realistically, it funnels developers into good practices...

If this isnt in the scope of what coffeescript wants to support, thats fine though. Just thought it would be pretty neat if coffeescript could start moving in a more functionally-minded direction.
