### ISSUE TITLE
Can't use Existential Operator

### ISSUE THREAD

**Issue by dogancelik** [jashkenas/coffeescript#4139]
According to the official docs, this works:

```coffee
zip = lottery
  .drawWinner?()
  .address?
```

What if you add one more check:

```coffee
zip = lottery
  .drawWinner?()
  .address?
  .somethingelse?
```

You get error: `Unexpected .`. It doesn't let me set *null* if `somethingelse` deos not exist.

Another example:

I want to check for items' existence before I modify it, would this code work? 

```
items?
  .map (item) -> item.data
  .map (item) -> "Item name: {item.name}"
  .join ', '
```

No, `Unexpected .`

But if you do like this, it works:

```
items
  ?.map (item) -> item.data
  .map (item) -> "Item name: {item.name}"
  .join ', '
```

We are checking for items but it doesn't let us put `?` near `items`.

**Comment by bjmiller** [comment]
`?.` is considered to be an operator.  It doesn't work if you separate the characters, the same way that `==` doesn't work if you put whitespace between the equals signs.

Meanwhile, the apply-if-exists form `?()` is a different syntactical construct.

**Comment by dogancelik** [comment]
I understand your point.
Though when I'm checking for something's existence, I feel like `?` should be after variable name instead of before `.` because it feels more natural that way.

**Comment by bjmiller** [comment]
It would take a lot of effort to make that happen, though it's not impossible.  The `?` operator, by itself, already has a definition, and it's different from what you're thinking of here.

CS | JS
--- | ---
`a ? b` | `if (typeof a !== "undefined" && a !== null) { a; } else {  b; };`
`a? b` | `if (typeof a === "function") { a(b); }`

The obvious argument against making such a change as you're suggesting, is that the question mark is already pretty overloaded, and adding yet another syntax case makes it less immediately clear on reading what any appearance of a question mark means (without looking it up).

**Comment by dogancelik** [comment]
Those are very clear examples and have different meanings then my examples above.

So with your examples, there are only 3 types of `?` usage.

* One for checking a variable's existence. (my example)
* One for checking if A is null or not, if null then set B. (your 1st example)
* One for checking if it's a function call A with parameters. (your 2nd example)

These are very very different things.

My suggestion is a syntactic sugar, there is no new features. You can't possibly make a bug out of this because there is always a `.` after `?` in my examples.

**Comment by bjmiller** [comment]
My point is simply that the maintainers might decide that a fourth meaning might be one too many.  I think this change could work, but it's not a question of fixing a small oversight.  It's a big lift.  The decision to make `a? .b` illegal was, I believe, intentional.

**Comment by dogancelik** [comment]
This is not a new meaning, it's the same thing when you remove the white space (\s).

A user can do:

```coffee
someFunc
	.test() # some users prefer dot here
  
someFunc. # some users prefer dot here
	test()
```

Of course `.` here is not a operator so it makes sense that it works. As I said before, it's just a syntactic sugar and there are no new features or meanings.

**Comment by dogancelik** [comment]
Your code example `a? .b` is incorrect. There will be no space after removing white space. Same as you can't do `a. b`

**Comment by vendethiel** [comment]
That's not like "a. b" or "a .b", since the operator is only one character there. Your example would be like expecting "c la ss Foo" to work.

**Comment by michaelficarra** [comment]
We're not going to allow splitting up lexemes. This wouldn't be expected by most people, and it will break things when one lexeme is a substring of another.
