### ISSUE TITLE
Optimize iterating over ranges

### ISSUE THREAD

**Issue by bopjesvla** [jashkenas/coffeescript#4141]
`for i in [x...y] then k = i` is almost three times as slow as `for i in [x...y] by 1 then k = i` (Chrome, OS X). The former recalculates the step (a constant) and the condition (which is both constant and independent of the step) every single iteration. A loop that computes the step beforehand and uses a simple equality test is only [slightly slower](http://jsperf.com/loop-through-range/5) than the loop with the explicit step:

```
for (i = j = ref = x, ref1 = y, by = ref < ref1 ? 1 : -1; j !== ref1; i = j += by) {
  k = i;
}
```

**Comment by GeoffreyBooth** [comment]
A pull request that implements this would be welcomed.
