### ISSUE TITLE
Coffee will support asynchronous grammar?

### ISSUE THREAD

**Issue by abc306396358** [jashkenas/coffeescript#4147]
Coffee will support asynchronous grammar?
We have been using the toffee for a long time.
When dealing with complex business logic, asynchronous syntax is very practical, but not update the toffee
https://github.com/jiangmiao/toffee-script

**Comment by auvipy** [comment]
why not pulling them to coffee?

**Comment by vendethiel** [comment]
You mean like #3813, #3757?

**Comment by GeoffreyBooth** [comment]
ES `async`/`await` Is now supported in CoffeeScript 2: http://coffeescript.org/v2/#fat-arrow
