### ISSUE TITLE
Variable shadowing is not fully supported in CoffeeScript

### ISSUE THREAD

**Issue by auvipy** [jashkenas/coffeescript#4149]
from a message of js2coffee converter

**Comment by vendethiel** [comment]
Correct. CoffeeScript has its own scoping rules, which are described in the docs.

**Comment by auvipy** [comment]
var need to be eliminated from generated coffee files then

**Comment by vendethiel** [comment]
js2coffee can't do a one-to-one translation. That's something with js2coffee, not coffeescript (because it won't - rightfully - rename your variables)
