### ISSUE TITLE
Inconsistent array comprehension?

### ISSUE THREAD

**Issue by loveencounterflow** [jashkenas/coffeescript#4151]
Consider these two snippets:

```coffee
( x for x in y )
```

```coffee
do => ( x for x in y )
```

Shouldn't one expect them to compile and evaluate to the exact same result?

Yet the first is equivalent to `x for x in y`, i.e. the parentheses are treated as redundant (as if I had written `a + ( b * c )`), which means the result is the last element of `y`. The second one evaluates to a copy of `y`.

My use case is that I'm compiling MarkDown documents that allow insertion of CS and JS code whose results will be interpolated into the document. The other day I tried (CS code fenced by `<<(:>>`...`<<)>>` here):

```
Yadda yadda <<(:>>( name for name of mkts )<<)>> yadda.
```

which to my surprise didn't quite work. Sure you *can* write 

```
Yadda yadda <<(:>>do => ( name for name of mkts )<<)>> yadda.
```

but that slightly changes the semantics of the snippet and is hard
to explain.

* Is this the expected behavior?
* In case this is expected, what is the reasoning?
* Are there more expression forms that show like behavior?
* Is there a generic way to reformat all such code snippets (which may contain several lines of code / several statements), i.e. by wrapping them into functions or some such so I always get the list comprehension interpretation from `( x for x in y )`, short of parsing the source myself?

For reference (slightly shortened):

```bash
coffee -cpeb "( x for x in y )"
var i, len, x;
for (i = 0, len = y.length; i < len; i++) {
  x = y[i];
  x;
}
```

```bash
$ coffee -cpeb "do => ( x for x in y )"
(function(_this) {
  return (function() {
    var i, len, results, x;
    results = [];
    for (i = 0, len = y.length; i < len; i++) {
      x = y[i];
      results.push(x);
    }
    return results;
  });
})(this)();
```

**Comment by vendethiel** [comment]
> Yet the first is equivalent to x for x in y, i.e. the parentheses are treated as redundant (as if I had written a + ( b * c )), which means the result is the last element of y.

Nope. You're not reading the first compilation correctly: since you don't use the comprehension, the compiler doesn't create an array / store the results. But it doesn't result the last element.

You can see it easily by using the value (using `[]` like an anonymous variable):

```
 coffee -cpeb "[] = ( x for x in y )"
// Generated by CoffeeScript 1.10.0
var x;

(function() {
  var i, len, results;
  results = [];
  for (i = 0, len = y.length; i < len; i++) {
    x = y[i];
    results.push(x);
  }
  return results;
})();
```

**Comment by loveencounterflow** [comment]
I#m sorry, but I'm afraid your argumentation is not convincing. 

First of all, the observation that "since you don't use the comprehension, the compiler doesn't create an array" is correct and understandable. As such, there are precedences in CS where one and the same construct (e.g. `[ 5 .. 9 ]`) may result in different translations, depending on context, so this could be one case.

However, it is questionable how much optimization should be going on. For example, when I say `coffee -cpbe "5 + 4"`, I get "5 + 4;"—which is fully expected, although one could argue that since the result of the computation is nowhere used and only literals are involved, CS could just skim over the expression and not translate it at all. I believe we all agree that that omission should not happen, the expression should stay in the generated JS, and it's up to the VM to decide how to optimize that.

When I do `coffee -cpbe "[ 5 .. 9 ]"`, I get `[5, 6, 7, 8, 9];`—again, the compiler *could* decide to omit the array. Crucially, **your observation that "since you don't use the comprehension, the compiler doesn't create an array" does not hold in this case**—why should it be true in other cases?

Second, your argumentation that "You're not reading the first compilation correctly [...] You can see it easily by using the value (using [] like an anonymous variable)" is hardly to the point; rather, **it is exactly the point I wanted to make**, namely, that when you syntactically make use of the computation (I did it using the implicit return feature of an `do`-IEFE, you did it using assignment) you get a different (unexpected) compilation result. Whatever you wanted to demonstrate with your code, it is exactly the code generated by my own example.

Third, am I not reading the compilation correctly? The JS says:

```js
for (i = 0, len = y.length; i < len; i++) {
  x = y[i];
  x;
}
```
Which you explain with: "But it doesn't result the last element."—doesn't it? What purpose does that lone `x;` line fulfill if not exactly that: **make the loop result in its last element?**

**Comment by lydell** [comment]
It is _very_ common to have a `for` loop that is _not_ used as an expression. While there are many things CoffeeScript _could_ optimize, that one is one that really makes sense.

**Comment by loveencounterflow** [comment]
@lydell just to drive that one point home: I think the principle of least surprise is more valuable that some splitmicroseconds gained in an effort to double-question a highly optimized compiler. IOW I'm against throwing away expressions that any beginner could easily tell are completely dispensible.

Unfortunately, the docs aren't very explicit about what to expect when using `( x for x in y )` when it's not on the RHS of an assignment. 

Let me ask you a question: 
* When I want to build a list from a comprehension, I enclose the `for`...`in` with parentheses, correct? Any other way to get that same result?
* When a `for`...`in` is *not* within parens, the result is the last element of the iteration, if any; correct?
* Then, what should be the result of `[ x for x in y ]`? Turns out it's a list with a copy of `y` as its only element. I believe this contradicts the first two bullet points—if I'm making the right assumptions.

Is there anything in the way of a specs document that is a bit more formal and explicit than the CS homepage?

**Comment by vendethiel** [comment]
> Which you explain with: "But it doesn't result the last element."—doesn't it? What purpose does that lone x; line fulfill if not exactly that: make the loop result in its last element?

Exactly the reason we optimize this one case: it runs the side effect. This one here doesn't have, but the general case very well might.

```coffee
# run the side effects:
eat(food) for food in [...]
```

**Comment by loveencounterflow** [comment]
Constructing a list where none is needed *but* implied by the CS syntax might very well be called a side effect that should be preserved. 

It's not for nothing that I gave a use case, it being the case when you want to give users an opportunity to construct a value using CS syntax. Obviously, CS cannot guess what's going to happen with the code it compiles, so it should be quite conservative about that. And it is indeed conservative in the case of stand-alone `4 + 5` and `[ 0 .. 9 ]`, but not so in the case of `( x for x in y )`.

I can re-word my concern like this: Though the official CS docs on http://coffeescript.org are not overly explicit on many points, they do seem to imply at one point that parens around your comprehensions is the way to go when what you want is an array. I'll readily concede that this may be a misunderstanding on my part since the docs are indeed far from a spec. However, if it's *not* the case that parens around a comprehension should unambiguously signal an array, well, in that case we must say that the parens have just been used as a convenient way to sneak that array result into the syntax, using an idiosyncrasy of the grammar, a fortuitous quirk. 

I don't think that's what we want, right, we want an unambiguous syntax. Let's not complicate matters. If it was for me to decide I'd say Python's `[ x for x in y ]` is the way to go, but it's probably too late for that proposal. That said, neither `[ x for x in y ]` nor `( x for x in y )` do in all cases observe the principle of least surprise in present CS, and I think at least one of these should be fixed.

**PROPOSAL: make `( x for x in y )` an array-constructing expressions no matter where it appears.** While you're at it, reflect on what `[ x for x in y ]` presently does, what it should really do, and whether it's worthwhile to change that if necessary.

**Comment by connec** [comment]
There's a reasonable argument that if the comprehension is in parentheses, then it is clearly an expression and should yield a value.

In any situation where a loop is executed for it's side effects only, I can't imagine it being written in parens, meaning the optimisation could still apply.

**Comment by lydell** [comment]
> I think the principle of least surprise is more valuable that some splitmicroseconds gained in an effort to double-question a highly optimized compiler.

I can assure you that if we were to change that we'd get duplicate after duplicate issue about it :)



>  When I want to build a list from a comprehension, I enclose the for...in with parentheses, correct? Any other way to get that same result?

Wrong. Parentheses are not a strict requirement to make the `for` loop into an expression:

```coffee
squares = for n in [1..10]
  n * n
```

>  When a for...in is not within parens, the result is the last element of the iteration, if any; correct?

Again, parentheses does not have very much to do with this. In CoffeeScript, as much as possible is an expression. The value of loops are lists, where each item in the list is the value of the last expression of the loop. It's up to a CoffeeScript implementation to choose how to optimize its output.

> Then, what should be the result of [ x for x in y ]? Turns out it's a list with a copy of y as its only element. I believe this contradicts the first two bullet points—if I'm making the right assumptions.

You're right about the value of that expression. See my answer to the previous question.

> Is there anything in the way of a specs document that is a bit more formal and explicit than the CS homepage?

That'd be the source code of the compiler, if anything.

> it is indeed conservative in the case of stand-alone 4 + 5 and [ 0 .. 9 ], but not so in the case of ( x for x in y )

There are of course lots of things you _could_ optimize. However, why waste time on optimizing `4 + 5` – nobody does that for real anyway. But loops whose value isn't used is a real and common use case. And it's not just about performance. It's also about the readability of the output JavaScript, which is an important goal of CoffeeScript.

> PROPOSAL: make ( x for x in y ) an array-constructing expression no matter where it appears.

So you're saying that we should _always_ compile _everything_ that can be an expression into an expression? That includes `if ... else`, `switch`, `while`, `try ... catch`, `throw` ...

> I'd say Python's [ x for x in y ] is the way to go, but it's probably too late for that proposal.

You're right, that's too late. It has also been discussed to great lengths in other issues. I'm unfortunately on a too bad connection right now to find them, though.

Finally, for your case, I'd suggest prepending `do =>` to your to-be-interpolated CoffeeScript expressions before compiling them in your markdown processor. Or, use `(x for x in y).join(', ')` which will give a nicer output than `String(x for x in y)`.

I'm not going to reply further to this thread, so don't bother writing a long reply directed at me if you're looking for further answers :)
