### ISSUE TITLE
Operator at start of line

### ISSUE THREAD

**Issue by YoYoYonnY** [jashkenas/coffeescript#4152]
I'll keep it short, but

```
settings = OBJECT
         | DATA
         | JSON
```

Gives a `unexpected indentation` error, where

```
var settings = OBJECT
             | DATA
             | JSON;
```

is valid JavaScript.

**Comment by carlsmith** [comment]
You could wrap the expression in parens, but yeah, I would have expected it to work without them, because of the indent.

**Comment by YoYoYonnY** [comment]
@carismith: The expressions doesn't work when wrapped in parenthesis either.

**Comment by carlsmith** [comment]
Ah. Hmm. I'm on my phone, so can't test anything out, but just quickly wanted to mention that CoffeeScript uses `or`, not `|`. If that doesn't fix it, and doing `settings = (...)` doesn't either...

**Comment by YoYoYonnY** [comment]
@carlsmith I know, it's a bug report, not a question.

**Comment by carlsmith** [comment]
Ah. I dont think it is a bug. I was wrong when I said it should work. Sorry. I was trying to be helpful, but wasn't being. I've been on strong painkillers lately, so should probably stop posting shit on the Web. The equals operator must be the last thing on the line. That's standard in CoffeeScript.

Sorry for the noise everyone.

**Comment by GeoffreyBooth** [comment]
CoffeeScript has significant whitespace. You’re not supposed to be able to get away with whatever you can achieve in JavaScript. If anything, CoffeeScript is too permissive.

If you want indentation like you have in your example, you need to [tell CoffeeScript to ignore the line break and indentation by using backslashes](http://coffeescript.org/v2/#try:settings%20%3D%20OBJECT%20%5C%0A%20%20%20%20%20%20%20%20%20%7C%20DATA%20%5C%0A%20%20%20%20%20%20%20%20%20%7C%20JSON):

```coffee
settings = OBJECT \
         | DATA \
         | JSON
```
