### ISSUE TITLE
Whether it will support ES7 async/await grammar in the future ?

### ISSUE THREAD

**Issue by KID-WuMeng** [jashkenas/coffeescript#4153]
It is already supported by babel, but I don't know how to use coffee-script and babel together in nodejs ?

**Comment by acterhd** [comment]
+1

**Comment by jashkenas** [comment]
When async/await are implemented in current browsers and Node, perhaps we should support compiling down to them.

**Comment by davibe** [comment]
async/await is a very practical and useful way to write better code. In Javascript you can use them today thx to babel.js even if node.js and browsers are not ready yet. The same is not true in the case of coffee. 
If coffee compiled async/await to js today we could easily transpile it with babel as a second step.
This is why i think it's worth exploring how we can use async await in coffee script today properly.

In the mean time I have been using the following technique based on ES6 generators to achieve something similar.
https://github.com/davibe/q-extended/blob/master/src/index.litcoffee
The syntax is not very heavy and it does not require additional transpiling.

It works perfectly including proper exception/error handling. This one i think is the best alternative we can use in coffeescript today.

**Comment by carlsmith** [comment]
`-1` CoffeeScript should compile to JS that can be executed in browsers, not JS that needs to be recompiled by a third-party project first. Besides, that would mess up source maps.

**Comment by lydell** [comment]
> Besides, that would mess up source maps.

Not necessarily.

**Comment by vendethiel** [comment]
Yeah, lots of tools have an "input-source-map" kind of flag that can be used to input source map as an entry point.

**Comment by carlsmith** [comment]
Nod. Last I heard, recursive maps were still just an idea. I didn't realise people have already implemented it. In that case, sorry, I was a bit too dismissive.

**Comment by isuvorov** [comment]
+1

**Comment by PeytonsProfile** [comment]
Coffee script is the glitchiest most useless creation, check out reactJS
made by facebook.

**Comment by DomVinyard** [comment]
+ 1

**Comment by RichardJECooke** [comment]
I'm new to CoffeeScript. Why is this issue closed? Does it mean it works in CoffeeScript now? I can't find how to do await for promises in the [documentation](http://coffeescript.org/).

I know it's kind of a dead language but I hoped it would have promises as I need to support a legacy project it was written in.

**Comment by GeoffreyBooth** [comment]
#3757
