### ISSUE TITLE
Commented parameters

### ISSUE THREAD

**Issue by fra9001** [jashkenas/coffeescript#4154]
quite often in javascript you can find yourself doing this (I used `underscore.js` for clarity)

    function doSomething(source /*, args*) {
        var funs = _.rest(arguments);
        ...
    }

I'm not the only one, as you can see in some [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) pages. The reason of doing this is to remind myself when I read my code that the function accepts optional parameters.

However in coffescript this

    doSomething = (source ###, args ###) -> bla()

does not compile.

Could it be implemented?

**Comment by lydell** [comment]
```coffee
doSomething = (source, funs...) ->
doSomething2 = (source, optional = 1337) ->
```
