### ISSUE TITLE
parameter is undefined when using @parameter in a constructor

### ISSUE THREAD

**Issue by chilversc** [jashkenas/coffeescript#4157]
Updating some older scripts that used to work under 1.3.1 and it seems something has broken when using `@parameter` then referring to that parameter in the body of the constructor (instead of the field).

The parameter gets aliased to `@parameter1` but the references to the parameter within the constructor body are not updated.

```coffee
class Test
	constructor: (@service) ->
		service.run()
```

```javascript
// Generated by CoffeeScript 1.10.0
(function() {
  var Test;

  Test = (function() {
	function Test(service1) {
	  this.service = service1;
	  service.run();
	}

	return Test;

  })();

}).call(this);
```

It seems coffeescript is mistaking the parameter as a variable in the outer scope. I thought that this syntax was supposed to be a shortcut for the equivalent to

```coffee
class Test
    constructor: (service) ->
        @service = service
```

**Comment by michaelficarra** [comment]
This was never supposed to work. See many duplicates of this issue.
