### ISSUE TITLE
coffee-script-source still broken in Windows

### ISSUE THREAD

**Issue by rmohan80** [jashkenas/coffeescript#4158]
Using v 1.8.0 works fine, but v1.10.0 gives the following error:

ExecJS::ProgramError at /
TypeError: Object doesn't support this property or method

Completed 500 Internal Server Error in 8468ms (ActiveRecord: 0.0ms)

ExecJS::ProgramError - TypeError: Object doesn't support this property or method:
  execjs (2.6.0) lib/execjs/external_runtime.rb:84:in `extract_result'
  execjs (2.6.0) lib/execjs/external_runtime.rb:39:in`exec'
  execjs (2.6.0) lib/execjs/external_runtime.rb:21:in `eval'
  execjs (2.6.0) lib/execjs/external_runtime.rb:46:in`call'
  coffee-script (2.4.1) lib/coffee_script.rb:78:in `compile'
  sprockets (3.5.2) lib/sprockets/coffee_script_processor.rb:21:in`block in call'
  sprockets (3.5.2) lib/sprockets/cache.rb:85:in `fetch'
  sprockets (3.5.2) lib/sprockets/coffee_script_processor.rb:20:in`call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in`block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in`load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in`fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in`block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.5.2) lib/sprockets/bundle.rb:23:in`block in call'
  sprockets (3.5.2) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.5.2) lib/sprockets/bundle.rb:24:in`call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in`block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in`load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in`fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in`block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.5.2) lib/sprockets/base.rb:66:in`find_asset'
  sprockets (3.5.2) lib/sprockets/environment.rb:30:in `find_asset'
  sprockets (3.5.2) lib/sprockets/base.rb:92:in`[]'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:190:in`check_errors_for'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:137:in `block in javascript_include_tag'
  sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:136:in`javascript_include_tag'
  app/views/layouts/application.html.erb:6:in `_app_views_layouts_application_html_erb___554822127_48185724'
  actionview (4.2.5) lib/action_view/template.rb:145:in`block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in`instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:66:in`render_with_layout'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:14:in`render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:23:in`render'
  actionview (4.2.5) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5) lib/action_controller/metal/streaming.rb:217:in`_render_template'
  actionview (4.2.5) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:32:in`render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5) lib/abstract_controller/rendering.rb:25:in`render'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in`block (2 levels) in render'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  C:/Ruby22/lib/ruby/2.2.0/benchmark.rb:303:in`realtime'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in`block in render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:10:in`default_render'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in`process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in`block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in`__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in`block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in`instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in`process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in`dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in`block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in`serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in`serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in`call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in`call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in`call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5) lib/active_record/migration.rb:377:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in`**run_callbacks**'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in`protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in`call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in`block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in`tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in`call_with_quiet_assets'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in`call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in`call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in`call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in`service'
  C:/Ruby22/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  C:/Ruby22/lib/ruby/2.2.0/webrick/httpserver.rb:94:in`run'
  C:/Ruby22/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

I can provide more errors from the browser if needed.

Thanks

**Comment by vendethiel** [comment]
What if you don't use execjs (and just install nodejs)? What's your code?

**Comment by rmohan80** [comment]
apologies if my answer isn't upto scratch. But I"m pretty new at this and learning "Ruby on Rails". My code is very simple though. I have a file called "new.html.erb"
<h3>Home</h3>
<p>Welcome to the home of <%= @owner.name %>.</p>
<p>I was born on <%= @owner.birthdate %>.</p>
<p>Only <%= @owner.countdown %> days until my birthday!</p>

I'm assuming the model and controllers are irrelevant in this case as the outputs are:

owner.name = "Foobar Kadigan"
owner.birthdate ="12-Dec-1992"
owner.countdown = <Depends> but an integer between 1 to 365

**Comment by vendethiel** [comment]
That seems to be erb code, not CoffeeScript code, though.

**Comment by rmohan80** [comment]
yes, it is ERB code. There is no CoffeeScript code/customization. Just using the default v1.10.0 - maybe I"m missing the question?

**Comment by marcomd** [comment]
Previously it was possible to downgrade to version 1.8.0 but not anymore, 1.9 and 1.10 does not works on windows

**Comment by gregors** [comment]
http://stackoverflow.com/questions/28421547/rails-execjsprogramerror-in-pageshome

**Comment by gregors** [comment]
it certainly looks like coffee script is broken on windows :(

**Comment by marcomd** [comment]
Fortunately, you can still go back to the old 1.8.0 version, it works

**Comment by ukoloff** [comment]
It is not CoffeeScript who is broken. It is Windows [Script Host] who lacks Object.create(). It can be easily polifilled:
```js
// Fix for CoffeeScript 1.9+
+function()
{
  if(Object.create) return
  Object.create=function(proto)
  {
    function f(){}
    f.prototype=proto
    return new f
  }
}()
```
This polyfill should be added to CoffeeScript or to coffee-script gem...

**Comment by joshirashmics** [comment]
Can you please elaborate more on this. Do I need to add this function after COMPILE_FUNCTION_SOURCE = <<-JS in coffee_Script.rb

**Comment by ukoloff** [comment]
Yeah, I think that will do.

In general I can imagine 3 ways:

1. Patch coff-script itself (or coffee-svript-source gem)

2. Patch coffee-script gem (your propose)

3. Use exexjs-xtrn gem, that has the polyfill applied

The latter is not recommended in production. But all the three either. And Windows itself ;-)

**Comment by chrisranney** [comment]
@ukoloff How did you come to understand this limitation in the windows scripting host? I would like to be able to recreate your steps for a better understanding and ultimately become a better developer myself.

Thanks,
Chris

**Comment by GeoffreyBooth** [comment]
CoffeeScript 2’s Node compiler assumes ES2015 support in the runtime. The browser compiler, per #4523, will run in the browsers that Babel supports by default in its `env` preset (which may or may not be a wide enough net to support Windows Scripting Host). If the browser compiler won’t run in your runtime, then a) your runtime is _really_ old and probably won’t run lots of JavaScript code; and b) you will need to take responsibility for further transpiling or polyfilling the browser compiler to a point where your runtime supports it. Babel has additional options for polyfilling and very-old runtimes that you could investigate.

Closing as out of scope for CoffeeScript.
