### ISSUE TITLE
browser.coffee can be loaded multiple times

### ISSUE THREAD

**Issue by tarnowsc** [jashkenas/coffeescript#4159]
The issue I'm struggling with is the fact that browser.coffee can be loaded multiple times and each time it registers runScripts to onload event again.

My case is not common, because I'm dynamically loading scripts that includes coffee-script.js and I end up with my coffee scripts being executed multiple times.

Still I'm wondering wouldn't it be nice to include some kind of isCoffeeBrewed flag on window object and stop further execution somewhere around [line 23 in browser.coffee](https://github.com/jashkenas/coffeescript/blob/master/src/browser.coffee#L23).

Thanks in advance for you help.

**Comment by tarnowsc** [comment]
Maybe something similar to the following would solve that:
	
	# Prevent form loading the coffeescript script multiple times
	return if window.isCoffeeBrewed?
	window.isCoffeeBrewed = true

**Comment by GeoffreyBooth** [comment]
This seems like too much of an edge case to support. You can implement your own fork of `browser.coffee` that requires the CoffeeScript compiler and does or doesn’t do whatever you want on startup.
