### ISSUE TITLE
"No function hoisting in CoffeeScript" is not on coffeescript.org

### ISSUE THREAD

**Issue by willnwhite** [jashkenas/coffeescript#4162]
I only just read that there's no function hoisting in CoffeeScript, weeks after coding in CoffeeScript, from somewhere other than coffeescript.org. It finally explains to me why my programs were only working properly when I put the functions at the top (I thought I was "hacking"). I think this should be in http://coffeescript.org/#literals, as JavaScript hoists functions.

**Comment by vendethiel** [comment]
CoffeeScript doesn't have named functions. `var a = function(){}` only hoists the variable in JS.

**Comment by willnwhite** [comment]
I still think it's worth stating explicitly that CoffeeScript function definitions must be written above calls to them. This isn't something a JavaScript programmer is used to. Even if they read about how CoffeeScript functions aren't named, that doesn't guarantee they'll realise that they have to do this.

**Comment by michaelficarra** [comment]
It does mean that because the only way to do this in CoffeeScript is via assignment, and JS devs understand that that doesn't hoist. If you want, send a PR with a more specific request, but I doubt it would be accepted.
