### ISSUE TITLE
Consider using CloudFlare to enable https://coffeescript.org

### ISSUE THREAD

**Issue by swrobel** [jashkenas/coffeescript#4165]
This is free and relatively easy to set up. Instructions are here: https://support.cloudflare.com/hc/en-us/articles/203663694-How-do-I-enable-free-Universal-SSL-with-Github-

**Comment by GeoffreyBooth** [comment]
Thanks. We’re hoping GitHub itself enables SSL for custom domains. We looked into other options when designing the v2 docs, but wound up back with http:// (see the commit history).
