### ISSUE TITLE
local variable with same name as function

### ISSUE THREAD

**Issue by szhu** [jashkenas/coffeescript#4170]
Correct behavior, in Python:

```python
def f():
  f = 1
  print "inner f =", f

f()
print "outer f =", f
```

`inner f = 1` and `outer f = <function>`

---

Incorrect behavior, in CoffeeScript:

```coffee
f = ->
  f = 1
  console.log "inner f =", f

f()
console.log "outer f =", f
```

`inner f = 1` and `outer f = 1`

---

output of `coffee --compile --bare --print`:

```js
// Generated by CoffeeScript 1.10.0
var f;

f = function() {
  f = 1;
  return console.log("inner f =", f);
};

f();

console.log("outer f =", f);
```

Note that `var f` isn't declared inside the function

**Comment by vendethiel** [comment]
Yep, scoping in Python works differently than in CoffeeScript, as noted in the docs.

**Comment by szhu** [comment]
@vendethiel I couldn't find documentation for this particular rule. Where is it and how can I force the inner `f` to be local?

**Comment by szhu** [comment]
Update for other people who might come across this issue: apparently this is [all over the internet](https://www.google.com/search?q=coffeescript+force+local+scope). I just wasn't searching for the right things.
