### ISSUE TITLE
Whitespace around property lookup (.)

### ISSUE THREAD

**Issue by royaldark** [jashkenas/coffeescript#4174]
Maybe this has been discussed before, but I couldn't find anything. Is there a reason you can have arbitrary whitespace around the property lookup operator, `.`?

I understand the use case of readability across multiple lines:

``` coffee
longObjectName
.longKeyName
.longKeyName
```

But what is the use of 

``` coffee
a



.


b
```

or

``` coffee
a   .                   b
```

being valid?

The reason I ask is I've been bitten several times by this innocent typo: `method(a. b)` when I meant `method(a, b)`. Quite a difficult bug to spot, especially in the midst of large code changes.

**Comment by GeoffreyBooth** [comment]
A fix for this would be welcome, but as it stands it’s not really a bug.
