### ISSUE TITLE
Pass variable inside backticks?

### ISSUE THREAD

**Issue by danielbayley** [jashkenas/coffeescript#4179]
I'm trying to use CoffeeScript as a preprocessor for Adobe ExtendScript (basically a superset of JavaScript). It has a bunch of additions, such as `#target [Adobe App]` and `#include '/absolute/path/to/include.jsx'`.

So I am using backticks to passthrough these extras like this ``` `#target illustrator` ```, but one issue is that I would like to be able to pass variables into these direct JavaScript statements; something like…
```coffee
include = "#{process.env.HOME}/dynamic/path/to/include.jsx"
`#include '"#{include}"'` # include '/absolute/path/to/include.jsx';
```
But what I actually get is `#include '"#{include}"';`

Trying ``` `#include '` + include + `'` ``` doesn't work either; `#include ' + include + ';`

Fortunately I can use `../..` relative paths in this case, but something like the above would be much more useful in general; not just for file paths…

**Comment by michaelficarra** [comment]
You can't use the runtime value of some variable at compile time.
