### ISSUE TITLE
Having trouble using lexer in code

### ISSUE THREAD

**Issue by mark-hahn** [jashkenas/coffeescript#4181]
I want to run the lexer in a module.  I am getting the `require 'lexer'` to work but then `new Lexer` is giving me an empty object.  Can someone tell me what I'm doing wrong here?

```
  Lexer = require 'coffee-script/lib/coffee-script/lexer'
  lexer = new Lexer.Lexer
  console.log util.inspect lexer  #  gives empty object {}
```

**Edit:** Fixed Lexer.Lexer

**Comment by mark-hahn** [comment]
I looked at the Lexer.Lexer function and saw why it was creating an empty object ...

```
function Lexer() {}
```

Looking at the lexer doc, http://coffeescript.org/documentation/docs/lexer.html, it clearly should have all the lexer code in it.  I'm baffled.  I guess I'll put logging statements in lexer.js.

**Comment by connec** [comment]
The `Lexer` class has no constructor, and therefor `Lexer` *should* be an empty function.  You could check you have the right thing by inspecting `Lexer.prototype` and/or `new Lexer().__proto__`.

**Comment by mark-hahn** [comment]
So I should be just using the class functions directly, as in new
Lexer().__proto__.functionName()?  I'll give that a try.  It seems a bit
weird though that I can't access them as instance methods.

**Comment by mark-hahn** [comment]
Thanks.  I should have known that.  It seemed to me that even an empty instance should have access to the inherited function.
