### ISSUE TITLE
Add consistent and secure soak unfolding for slices

### ISSUE THREAD

**Issue by yosbelms** [jashkenas/coffeescript#4183]
``` coffeescript
myFunc?()
```

compiles to

``` javascript
if (typeof myFunc === "function") {
  myFunc();
}
```

But

``` coffeescript
array?[1..2]
```

compiles to

``` javascript
if (array != null) {
  array.slice(1, 3);
}
```

For the sake of security and consistency it should compile to

``` javascript
if (array != null && typeof array.slice === 'function') {
  array.slice(1, 3);
}
```

**Comment by connec** [comment]
I'd say it's `func?()` that's the unusual one.  All the other usages simply check for `null`/`undefined`.

**Comment by michaelficarra** [comment]
These are fine. See the numerous duplicates.

**Comment by michaelficarra** [comment]
Oops, I misread the last example.

**Comment by yosbelms** [comment]
@connec right, I think that checking for `undefined/null` when compiling `obj?.prop` is fine. I've been thought about `array?[4]` I did not find an straightforward solution to get along ES6 Map, Set, Symbol.iterator ....

**Comment by GeoffreyBooth** [comment]
Closing as there doesn’t appear to be consensus to change this. While it seems useful to do a more thorough check, that’s not what the existential operator is defined to do, and this opens a can of worms to expand what `?` checks for in other contexts.

It was discussed in a very old ticket to fix the check for functions to only check for existence and not callability, but at this point it’s quite late to make such a breaking change (and if anything, the check for both existence and callability is a boon, like checking for `slice` here would be).
