### ISSUE TITLE
Killing coffee process does not kill child node process

### ISSUE THREAD

**Issue by svicalifornia** [jashkenas/coffeescript#4185]
See https://github.com/remy/nodemon/issues/195

When running `coffee --nodejs ...`, a `node` child  process is created.

Killing/restarting the `coffee` process does not kill the `node` process and can continue tying up resources that the new process needs to access. For example, if `node` was started with `--debug`, then it will keep using port 5858, preventing the newly spawned `node` process from opening that port.

Workaround is to abandon the `coffee` command and use:

```
node --debug ./node_modules/.bin/coffee path/to/script.coffee
```

However, it seems the `coffee` command is essentially useless when launching node and working with automated restart workflows.

Proposed solution: `coffee` should handle `SIGINT` and `SIGTERM` and kill any child processes it has started.

**Comment by GeoffreyBooth** [comment]
While a fix for this would be welcomed as a PR, the `coffee` command is not meant to replace the Node runtime. Its primary use is compiling CoffeeScript, and other functions are provided primarily for debugging purposes.
