### ISSUE TITLE
CoffeeScript's implementation of static inheritance missing non-enumerable properties; incompatible with ES6/7

### ISSUE THREAD

**Issue by svicalifornia** [jashkenas/coffeescript#4186]
In CoffeeScript, static inheritance is implemented by looping over **enumerable** keys in the superclass:

    extend = function(child, parent) {
      for (var key in parent) {
        if (hasProp.call(parent, key)) child[key] = parent[key];
      }

But this misses **non-enumerable** properties of the superclass. As a result, CoffeeScript cannot properly extend some ES6/7 classes. For example, the `Model` class of Objection.js has a non-enumerable static property `query`, which is inherited by subclasses in ES6/7 but not by CoffeeScript.

    Model = require('objection').Model
    class Person extends Model
    Person.query  # undefined

In Babel-transpiled ES6, static inheritance is implemented by setting the subclass's prototypical inheritance:

    function _inherits(subClass, superClass) {
      ....
      if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;
    }

This gives the subclass full access to the superclass's properties, including non-enumerables:

    var Model = require('objection').Model;
    class Person extends Model {}
    Person.query  # function query() { ...

Is there some reason why CoffeeScript does not set the subclass's prototype, as Babel does? If that is not possible, then how about copying the non-enumerable properties of the superclass using `Object.getOwnPropertyNames`? Either of these fixes should make CoffeeScript more compatible with ES6 classes.

**Comment by vendethiel** [comment]
`setPrototypeOf` and `__proto__` both became standard in ES6.

**Comment by michaelficarra** [comment]
> Is there some reason why CoffeeScript does not set the subclass's prototype

It does do this. Did you try it out or just look at the code?

**Comment by svicalifornia** [comment]
@michaelficarra I'm using coffee 0.10.0, and it **does not** copy the non-enumerable properties, nor does it set the superclass's __proto__ the way Babel does. As a result, CoffeeScript **does not** inherit non-enumerable properties from ES6 classes, as I described already above. Please re-open this issue.

**Comment by svicalifornia** [comment]
Model = require('objection').Model  # an ES6 class
    class Person extends Model   # does NOT copy the static prototype or non-enumerables properties
    Person.query  # undefined -- INCOMPATIBLE WITH ES6

**Comment by svicalifornia** [comment]
@vendethiel What about `Object.getOwnPropertyNames`? Using that would at least copy the non-enumerable static properties of the superclass.

**Comment by svicalifornia** [comment]
Is CoffeeScript really rejecting any functionality not present in IE 8? We can't even test for the existence of `Object.getOwnPropertyNames` and use it if available?

**Comment by svicalifornia** [comment]
nodes.coffee line 2264:

    # Correctly set up a prototype chain for inheritance, including a reference
    # to the superclass for `super()` calls, and copies of any static properties.
    extend: (o) -> "
      function(child, parent) {
        for (var key in parent) {
          if (#{utility 'hasProp', o}.call(parent, key)) child[key] = parent[key];
        }
        function ctor() {
          this.constructor = child;
        }
        ctor.prototype = parent.prototype;
        child.prototype = new ctor();
        child.__super__ = parent.prototype;
        return child;
      }
    "

The comment incorrectly states "copies of any static properties" because it copies **only enumerable properties, NOT non-enumerables.** And if it doesn't copy non-enumerables, then it can't use all ES6 classes. It's stuff like this that causes people to jump ship from CoffeeScript.

**Comment by michaelficarra** [comment]
@svicalifornia Chill out a bit, please. Multiple posts in a row are considered rude. Collect your thoughts and make a single, well thought out post next time.

I was referring to the prototype methods, not static methods. Code examples of what doesn't work and what you would expect would be helpful next time. As @vendethiel said, there's no way to take an existing class A and make it inherit static methods from B without `Object.setPrototypeOf` or the `__proto__` setter. Unfortunately, we need to support ancient IE (not my decision), so there's not much we can do for you.

**Comment by svicalifornia** [comment]
@michaelficarra I referred specifically to static inheritance in the subject line, and I did include code examples in my original message and in follow-up comment. I am reasonably frustrated by your hasty treatment of this issue and your invalid judgment of the above conversation.

And you guys are still not answering my suggested workaround of using `Object.getOwnPropertyNames` to get the non-enumerables. So what about that?

**Comment by michaelficarra** [comment]
> I referred specifically to static inheritance in the subject line

Yet in the text you referenced the subclass's prototype, not the subclass's constructor's prototype.

> and I did include code examples

Not the kind I just asked for.

> `Object.getOwnPropertyNames`

That is ES5+ so we can't use it. And to predict your rebuttal, using it in only environments where it is available would cause inconsistent behaviour.

**Comment by svicalifornia** [comment]
Ah, I see the confusion. I meant the subclass's `__proto__`. I thought that would be clear from the above code snippet:

      if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;

The CoffeeScript code example that fails is in the original comment:

    Model = require('objection').Model
    class Person extends Model
    Person.query  # undefined

In ES6, `Person.query` is a function. And without that function, any subclasses of `Model` are all but useless, since that function is used to get a `knex` query builder and make all the database queries.

Of course, I can call `Object.getOwnPropertyNames` from my CoffeeScript code, but that's inelegant and redundant, since I'll have lots of subclasses of `Model`.

It's stuff like this that makes people drop CoffeeScript. It's 2016 -- hardly anyone uses IE 8 anymore, and choosing IE 8 compatibility over ES 6 compatibility will kill CoffeeScript.

**Comment by carlsmith** [comment]
Asking questions that put words in other people's mouths is a bit of a troll tactic. I know you're not trolling, but it is a poor approach to contributing still. Being pushy wont help your case.

@michaelficarra is one of the hardest working and most knowledgeable devs in this community by a wide margin. Show a little respect dude.

**Comment by svicalifornia** [comment]
@carlsmith I'm upset for good reason. I took valuable time to research and report an issue, and I included more than enough information for it to be well understood. And it was flippantly closed without valid explanation. Finally @michaelficarra did explain it fully, and if he had done so in the beginning, then I wouldn't have cause to be offended. Respect has to be earned, and Michael's contributions mean little to me if he treats people's valid suggestions as badly as he did above.

I still maintain that the decision to support compatibility with IE8 over ES6 is ridiculous and tragic, but as @michaelficarra said, it's not his decision. So I guess we leave it at that.

**Comment by svicalifornia** [comment]
@carlsmith When someone takes the time to research and submit an issue, they do not deserve to be flippantly dismissed. The further reprimand that my submission should fulfill certain requirements that I  had already fulfilled just shows how hastily and carelessly @michaelficarra treated this issue. I have every reason to be upset about that, not to mention worried about the future of CoffeeScript if this is how it's being stewarded.

@michaelficarra @vendethiel Generators are an ES6 feature not available in IE 8, yet they are now in CoffeeScript, compiling to ES6 code. This disproves your above assertion that ES5+ features can't be added to CoffeeScript. Please reopen this issue and give it the consideration it deserves.

**Comment by svicalifornia** [comment]
@michaelficarra If CoffeeScript static inheritance would check for `Object.getOwnPropertyNames` and fall back to its current implementation, then the behavior would actually **not** be inconsistent in IE 8. Since IE 8 does not have `Object.defineProperties` or `Object.create`, there are no non-enumerable properties in IE 8. If `Object.getOwnPropertyNames` hypothetically did exist in IE 8, it would return the same enumerable keys as `for key in ...`. The behavior would be the same.

The fact that non-enumerable properties would break IE 8 is a moot point, because any code that tries to create non-enumerable properties already breaks IE 8. The change I'm requesting does not attempt to add any non-enumerable properties; it merely attempts to read and copy them if they exist, which they don't in IE 8. This change would not introduce different behavior in IE.

**Comment by carlsmith** [comment]
@svicalifornia - I don't want to argue the point; it's just noise for everyone else. I still think you approached it quite badly, but we'll have to agree to disagree I guess.

**Comment by svicalifornia** [comment]
Then let's keep the discussion to the issue raised. I want CoffeeScript classes to extend gracefully from ES6 classes, so CoffeeScript can remain interoperable and relevant. I've shown a case where that is broken. Are we going to fix it?

**Comment by vendethiel** [comment]
> @michaelficarra @vendethiel Generators are an ES6 feature not available in IE 8, yet they were added to CoffeeScript, compiling to ES6 code. Since ES5+ features are in fact allowed in CoffeeScript, please reopen this issue and give it the consideration it deserves.

Because it's a opt-in choice. If you decide to do use generators, you know you break <ES6 compliance.  Classes are a core feature, that's been here for a long time already (=> backwards compatibility break)

**Comment by svicalifornia** [comment]
OK. But my other point still stands about attempting to use `Object.getOwnPropertyNames` and falling back to `for key in...`. Browsers that don't have `Object.getOwnPropertyNames` also have no way to add new non-enumerable properties, so anyone adding non-enumerable properties has already chosen to break compatibility with IE 8 (same as opting to using generators).

**Comment by xixixao** [comment]
> @svicalifornia Chill out a bit, please. Multiple posts in a row are considered rude.

Wow. This is his first issue open here, I am amazed at how this discussion escalated :disappointed:

**Comment by svicalifornia** [comment]
This is not my first open issue here. But it may be my first open issue that was so quickly and incorrectly dismissed and closed. I've never felt so unwelcome to contribute to a project. And yet I remain a steadfast proponent of the simplicity and elegance of CoffeeScript syntax, and my work is quite attached to it. So I continue to stay here and plead my case for this improvement.
