### ISSUE TITLE
Rewriter: Call or reference check of `inImplicit` function in src/rewriter.coffee?

### ISSUE THREAD

**Issue by app** [jashkenas/coffeescript#4187]
Hi!
There is line of code which looks incorrect for me in src/rewreter.coffee
https://github.com/jashkenas/coffeescript/blob/master/src/rewriter.coffee#L158

```
inImplicitControl = -> inImplicit and stackTop()?[0] is 'CONTROL'
```

should it be 

```
inImplicitControl = -> inImplicit() and stackTop()?[0] is 'CONTROL'
```

instead?

**Comment by vendethiel** [comment]
That seems to be a bug, yes, but I wonder what's gonna break once that's changed.. ;)
