### ISSUE TITLE
IIFE Syntax

### ISSUE THREAD

**Issue by Qix-** [jashkenas/coffeescript#4188]
When making loops, Javascript has a problem with bindings in terms of the iterator (counter) and functors.

```js
var fns = []
for (var i = 0; i < 10; i++) {
    fns.push(function () {
        console.log(i);
    });
}

fns[0](); // 10
```

This problem exists in CoffeeScript as well.

```coffee
fns = []
(fns.push -> console.log i) for i in [0...10]
fns[0]() # 10
```

This problem is overcome by using an [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression):

```js
fns = []

for (var i = 0; i < 10; i++) {
    (function(i) {
        fns.push(function () {
            console.log(i);
        });
    })(i);
}

fns[0](); // 0
```

And (arguably even uglier) in CoffeeScript:

```coffee
fns = []
(((i) -> fns.push -> console.log i) i) for i in [0...10]
fns[0]() # 0
```

---

What would be awesome is to have a syntax for an IIFE function that basically resolves to an expression:

```coffee
fns = []
(fns.push ((i)) -> -> console.log i) for i in [0...10]
fns[0]() # 0
```

or

```coffee
fns = (((i)) -> -> console.log i) for i in [0...10]
```

The above example (not necessarily a syntactic proposal) uses two parenthesis to indicate a function that should be immediately called using the named arguments pulled from the local scope.

That means the above translates roughly to the second JavaScript example above. I haven't looked at the CoffeeScript parser but I imagine checking for a second set of parens wouldn't be too intensive.

Another idea for the syntax:

```coffee
# uses the same mechanism that pools variables at the top of a scope
# to infer which variables need to be included in the IIFE's argument list
fns = (!-> -> console.log i) for i in [0...10])
```

Not sure if that last one is possible, though.

If this is well received I could take a whack at a PR.

**Comment by Jamesernator** [comment]
You can already do this with `do` notation for example your first would become:
```coffeescript
fns = []
for i in [0...10]
    fns.push do (i) -> -> i # Create a closure with i and return a function immediately from that closure

console.log fns[0]() # 0
console.log fns[3]() # 3
```

or as a one-liner:
```coffeescript
fns = (for i in [0...10] then do (i) -> -> i)
console.log fns[0]() # 0
console.log fns[3]() # 3
```

**Comment by Qix-** [comment]
Woo! That's perfect, thanks!

**Comment by connec** [comment]
I have always used

```coffee
for i in [0...10] then do (i) ->
  # loop body in a closure
```

**Comment by vendethiel** [comment]
also see #2518
