### ISSUE TITLE
Include line comment tokens

### ISSUE THREAD

**Issue by flying-sheep** [jashkenas/coffeescript#4189]
tools using CS’s lexer/parser would profit from line comments, but non-here-comments [are ignored](https://github.com/jashkenas/coffeescript/blob/b8403bfa97e8aa662781af30d38a8c953119ab12/src/lexer.coffee#L243)

**Comment by vendethiel** [comment]
Duplicate, see https://github.com/jashkenas/coffeescript/issues/2365#issuecomment-6088676 and a few others.

**Comment by flying-sheep** [comment]
the other bug was closed due to unrelated stuff though (i.e. because of its motivation, not because the feature request was invalid)

so please reopen either this one or the other one.

**Comment by GeoffreyBooth** [comment]
Implemented via #4572.
