### ISSUE TITLE
Add private fields in Classes

### ISSUE THREAD

**Issue by Maxmaxmaximus** [jashkenas/coffeescript#4190]
When we do multiple extending, we need private fields in class

example

```coffeescript
class EventEmitter
  constructor: ->
    @_eventListeners = []
```

field _eventListeners  is private prop, but _ prefix make his just protect prop
end this behavior may lead to a conflict of names in child classes.

prop _evendListeners in PRIVATE prop EventEmitter class

solution:

```coffeescript
class EventEmitter
  constructor: ->
    private.eventListeners = []
```

compile to:

```javascript
var EventEmitter = (function() {

  var _private_prefix_ = '_EventEmitter_';
 // or  var _private_prefix_ = Math.random();

  function EventEmitter() {
    this[_private_prefix_ + 'eventListeners' ] = [];
  }

  return EventEmitter;
})();
```

NO MEMORY LEAK! FAST WORK! SIMPLY DEBUG!
JUST DO IT!! don't let your dreams be dreams!1!!

**Comment by vendethiel** [comment]
Still not private at all... One can just lookup by the "end" of the property.

**Comment by Maxmaxmaximus** [comment]
you absolutely do not understand programming, you should be ashamed. Private does not mean that we are protecting the property from hackers. Private means encapsulation inside a class. which in this case is provided neymspeysom. man, will learn at least the basics of programming.

**Comment by Maxmaxmaximus** [comment]
@vendethiel namespase this.[privatePrefix+'propName'] = privateValue

is PRIVATE prop. NAMESPACE! You know the word namespase?

**Comment by Maxmaxmaximus** [comment]
@vendethiel Come on, I'll teach you the programming:

private property - it is not a property of the buyout is not available outside.
privacy is ensured namespace. each class generated random namespace, i.e. the prefix and is used to store the private properties of this class.

the fact that these properties can be accessed from the outside does not make them not as private. privacy do not need to do this, it is necessary to prevent name conflicts with the class inheritance. and it is achieved through a unique namespace for each class.


the lesson is over. Now you're a little bit closer to my level.

**Comment by Maxmaxmaximus** [comment]
I showed you some code to be generated, I showed you how to do it. it eliminates the memory leak and generally works molneinosno. so what are you waiting for? it is realized!

**Comment by vendethiel** [comment]
> you absolutely do not understand programming, you should be ashamed

This is probably the worst way to go about this. Please stop.
