### ISSUE TITLE
Add private fields in Classes

### ISSUE THREAD

**Issue by Maxmaxmaximus** [jashkenas/coffeescript#4191]
private property - it is not a property of the buyout is not available outside.
privacy is ensured namespace. each class generated random namespace, i.e. the prefix and is used to store the private properties of this class.

the fact that these properties can be accessed from the outside does not make them not as private. privacy do not need to do this, it is necessary to prevent name conflicts with the class inheritance. and it is achieved through a unique namespace for each class.

When we do multiple extending, we need private fields in class

example

```coffeescript
class EventEmitter
  constructor: ->
    @_eventListeners = []
```

field _eventListeners  is private prop, but _ prefix make his just protect prop
end this behavior may lead to a conflict of names in child classes.

prop _evendListeners in PRIVATE prop EventEmitter class

solution:

```coffeescript
class EventEmitter
  constructor: ->
    private.eventListeners = []
```

compile to:

```javascript
var EventEmitter = (function() {

  var _private_prefix_ = '_EventEmitter_';
 // or  var _private_prefix_ = Math.random();

  function EventEmitter() {
    this[_private_prefix_ + 'eventListeners' ] = [];
  }

  return EventEmitter;
})();
```

NO MEMORY LEAK! FAST WORK! SIMPLY DEBUG!
JUST DO IT!! don't let your dreams be dreams!1!!

**Comment by Maxmaxmaximus** [comment]
solution 2:

```coffeescript
class EventEmitter
  constructor: ->
    private.eventListeners = []
```

compile to:

```javascript
var EventEmitter = (function() {

  var _private_prefix_ = '_EventEmitter_';
 // or  var _private_prefix_ = Math.random();

  function EventEmitter() {
    var _privateProps = 
    this[_private_prefix_ + 'eventListeners' ] = [];
  }

  return EventEmitter;
})();
```

**Comment by connec** [comment]
There are lots of previous tickets about this (e.g. #3645, a search for "private" will reveal many more).  The upshot seems to be that, as private properties are not supported by the runtime, and deviate from predictable JS behaviour, they won't be implemented in CS.

**Comment by Maxmaxmaximus** [comment]
@connec well, then I fork coffeescript and add support es7 and private properties in classes, iterators, generators, import itp we're tired! All have long been waiting! and you tupite! I do it myself! Since you can not!

Goodbye!
