### ISSUE TITLE
Expand string interpolation expressions into dedicated AST

### ISSUE THREAD

**Issue by flying-sheep** [jashkenas/coffeescript#4192]
Hi, as seen in #3831, string interpolation like `"A #{a} B #{b}"` is lexed as if it was `'A '+a+' B '+b`.

as mentioned in juliankrispel/decaf#2, there are use cases for having the semantic information survive lexing.

Therefore it would be awesome if we could introduce a new `StringInterpolation` AST node which is later converted to a concatenation expression.

**Comment by michaelficarra** [comment]
:+1:. This is how I did it in the CoffeeScriptRedux compiler.

**Comment by jashkenas** [comment]
IIRC, that would also help out with some other tricky issues. Like the old implicit call rewriter kludge.

**Comment by lydell** [comment]
@jashskenas I tjink that particular issue was fixed in commit 76c076db555c9ac7c325c3b285cd74644a9bf0d2 ;) But I do agree that information is lost in many places in the parser.

**Comment by juliankrispel** [comment]
awesomesauce! This would be super helpful

**Comment by lydell** [comment]
@juliankrispel I'm working on this (and have come very far, all tests are currently passing): https://github.com/lydell/coffee-script/tree/node-types

**Comment by juliankrispel** [comment]
@lydell omg this is amazing. Tbh I'm not sure what I'm looking at but it's amazing nonetheless :D

**Comment by flying-sheep** [comment]
i hope you’re looking at lydell/coffee-script@5e54fc478f95a8a133c7d88f20600b7caf2fdee0, which is mostly new, more specific Node classes.

one of which being [`StringWithInterpolations`](https://github.com/lydell/coffee-script/commit/5e54fc478f95a8a133c7d88f20600b7caf2fdee0#diff-30b5df382fb36749d0d1d282b2df9a53R150), i.e. what we need.

changes like [this](https://github.com/lydell/coffee-script/commit/5e54fc478f95a8a133c7d88f20600b7caf2fdee0#diff-d149b4f007169f06a8ad463f9b2f277bL1327) tell me that doing the other stuff also is a very good idea!

**Comment by vendethiel** [comment]
It should also fix some other long-standing bugs like ``` `this` ```
