### ISSUE TITLE
PRIVATES prop in coffeescript

### ISSUE THREAD

**Issue by Maxmaxmaximus** [jashkenas/coffeescript#4196]
> If you open an issue like this again, I will report your account to GitHub. They have banned users for far less.

@michaelficarra I fuck your stupid mother. as I was trying to improve your fucking coffeescript and you're threatening me for this? Fuck you fuck fucking dog. I Maxmaxmaximus and you did not fit to hold a candle.

I came up with a solution how to make private property, and you say to ban me for this? A fucking bastards developers coffeescript, I make my coffeescript with Blackjack and whores. Since you are so stupid and resist evolution. Dinosaurs tend to die out.

**Comment by Maxmaxmaximus** [comment]
p.s. https://en.wikipedia.org/wiki/Ad_hominem

**Comment by Maxmaxmaximus** [comment]
no arguments? ban ban ban

**Comment by vendethiel** [comment]
This is why we can't have nice things. Already report you, btw.
