### ISSUE TITLE
Establish a proper prototype chain

### ISSUE THREAD

**Issue by silkentrance** [jashkenas/coffeescript#4197]
Given the following input source

```
class A

class B extends A


console.log A.isPrototypeOf B
```

yields `false`

whereas the same using babel

```
class A {}

class B extends A {}

console.log(A.isPrototypeOf(B));
```

yields `true`.

See also [node prototype chain is broken](https://github.com/nodejs/node/issues/4179).

**Comment by GeoffreyBooth** [comment]
Returns `true` in 2.0.0-beta1.
