### ISSUE TITLE
Explicit Concatenation

### ISSUE THREAD

**Issue by allisteraligerum** [jashkenas/coffeescript#4200]
I've always been a little disappointed that JavaScript uses `+` for both concatenation and addition. It would be nice to have an explicit concatenation operator.

The compiled JavaScript would replace `.` with `+ '' +`.

```coffee
[a, b] = [1, 2]

console.log a + b    #javascript: a + b;      outputs: 3
console.log a . b    #javascript: a + '' + b; outputs: "12"
```

You could also use the `.=` operator to append.

```coffee
message = "CoffeeScript"
message .= " is awesome"

console.log message  #outputs: "CoffeeScript is awesome"
```

**Comment by michaelficarra** [comment]
This is why we have interpolation.

**Comment by allisteraligerum** [comment]
Thanks for the reply.
