### ISSUE TITLE
Object property shorthand breaks when using dot notation

### ISSUE THREAD

**Issue by ezekg** [jashkenas/coffeescript#4201]
Defining an object using the [property shorthand](http://es6-features.org/#PropertyShorthand) (i.e. `obj = { keyValue }`), if you use dot-notation for instance variables, then compilation fails. For example,

```coffee
class Component extends React.Component

  constructor: ->
    schema = {
      a: "a"
    }

    value = {
      b: "b"
    }
    
    # Passes
    @state = { schema, value, @onChange }

    # Fails
    @state = { schema, value, @.onChange }

  onChange: => # ...
```

I get that this is some-what ES6-compliant, but it doesn't really make sense. I feel like this shouldn't fail, as `@onChange` and `@.onChange` are identical. So I think that if you're going to allow one, then both should be allowed. It's a small issue, but my team uses the dot notation to differentiate methods from instance variables. [Here is an online test case.](http://coffeescript.org/#try:class%20Component%20extends%20React.Component%0A%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20schema%20%3D%20%7B%0A%20%20%20%20%20%20a%3A%20%22a%22%0A%20%20%20%20%7D%0A%0A%20%20%20%20value%20%3D%20%7B%0A%20%20%20%20%20%20b%3A%20%22b%22%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%23%20Passes%0A%20%20%20%20%40state%20%3D%20%7B%20schema%2C%20value%2C%20%40onChange%20%7D%0A%0A%20%20%20%20%23%20Fails%0A%20%20%20%20%23%20%40state%20%3D%20%7B%20schema%2C%20value%2C%20%40.onChange%20%7D%0A%0A%20%20onChange%3A%20%3D%3E%20%23%20...)

**Comment by vendethiel** [comment]
Yeah, this is a bit of an odball in CoffeeScript... see #1089
