### ISSUE TITLE
Inbrowser transpiler and language minifier required and type

### ISSUE THREAD

**Issue by gdennie** [jashkenas/coffeescript#4202]
An in-browser transpiler would make coffeescript a defacto web language piggy backing javascript. Because of it's compactness, solutions like just-in-time transpilation might become viable.

Because it is an indent/space sensitive language, minification might seem impossible. However, minification and the resultant inbrowser transpiler can coordinate to something equivalent to tab and untab to indicate levels of indentation sufficient to denote new blocks or even use braces, {}.

It would be nice if types were incorporated, similar to the way of TypeScript without all that cruft of javascript.

My $0.02

**Comment by michaelficarra** [comment]
We have this already, though we discourage its use for production code.

**Comment by gdennie** [comment]
There is coffeescript minification without compilation to javascript at all and in-browser transpiler of minified coffeescript? Nice. What are the projects?

**Comment by michaelficarra** [comment]
Yes, there is an in-browser "transpiler". No, there is no minifier.

**Comment by gdennie** [comment]
Yeah, the minifier is key.  Despite the existing brevity of CS, a
minification would express CS as not just elegant but also compressed JS.
...Anyways, that's it. :)
