### ISSUE TITLE
Function calls without parenthesis in conditionals are parsed incorrectly

### ISSUE THREAD

**Issue by danielkalen** [jashkenas/coffeescript#4203]
Take for example this conditional expression
`
if status.includes 'Restricted' or status.includes 'NotDetermined'
    askForLocation(fallbackTimeout).then ()-> Meteor.call('set_user_setting', 'location', true)
`

It gets evaluated to:
`
if ( status.includes('Restricted' || status.includes('NotDetermined')) ) {
   ...
}
`

The simple solution is to put parenthesis around the function calls but this it is very hard to notice this problem.

**Comment by michaelficarra** [comment]
This is intentional. Paren-free calls have always worked this way in CoffeeScript, for better or worse.
