### ISSUE TITLE
How about making this a github organization by itself and move all coffeescript related projects to that org?

### ISSUE THREAD

**Issue by silkentrance** [jashkenas/coffeescript#4206]
Since this project generated a lot of traction in the past, it would be sad to see this waste away due to limited resources on your behalf.
So, please pick your favorite committers as a team and get things up to speed again.

**Comment by silkentrance** [comment]
Just saw that there is such an org but without any repos.

**Comment by vendethiel** [comment]
Yeah, cc @jashkenas and @michaelficarra I guess...

**Comment by michaelficarra** [comment]
As [I commented recently](https://github.com/jashkenas/coffeescript/issues/4078#issuecomment-178074681), I am completely in favour of moving this repo. But only @jashkenas has permission to do the move. Is anybody aware of any issues this might cause? Maybe coffeescript.org DNS will need to be update in some way? But I think everything should be fine as long as we still have the CNAME file.

**Comment by juliankrispel** [comment]
@michaelficarra I'd be happy to move decaf there as well fyi @jashkenas

**Comment by GeoffreyBooth** [comment]
Not moving anytime soon.
