### ISSUE TITLE
Can't install coffee script on windows 10

### ISSUE THREAD

**Issue by appuxc** [jashkenas/coffeescript#4207]
Installed node.js and  i've used the code npm install -g coffee-script but it gets stucked somewhere. Please help me.

**Comment by vendethiel** [comment]
We need some kind of log to help you in any way. You're not providing enough information here.

**Comment by rdeforest** [comment]
I  just did an 'npm install -g coffee-script' on Window 10 from cmd.exe and also from bash.exe running in CygWin's mintty. I saw no problems.
