### ISSUE TITLE
Cannot extend ES6 classes: Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by balupton** [jashkenas/coffeescript#4208]
Just did this repo to test interopability between CoffeeScript and ES6 classes: https://github.com/balupton/javascript-coffeescript-class-interop

However it turns out that while ES6 classes can extend CoffeeScript classes, CoffeeScript cannot extend ES6 classes due to the error: `Class constructors cannot be invoked without 'new'`

As ES6 becomes more widely adopted, this seems to be a large interop issue.

**Comment by Zorgatone** [comment]
+1 :+1:

**Comment by GeoffreyBooth** [comment]
Closing in favor of #4233. (I know it came later, but it has more discussion.)

Addressed by #4354.
