### ISSUE TITLE
Add static keyword

### ISSUE THREAD

**Issue by MegaJsTeam** [jashkenas/coffeescript#4211]
add `static` keyword

`static.name`
compile to
`this.constructor.name`

=========
cuz

```coffeescript
class Animal
  @render: -> console.log('Animal Render')
  run: -> Animal.render() # call static

class Cat extends Animal
  #owerride stratic method
  @render: -> console.log('Cat Render')

cat = new Cat
cat.run() # ANIMAL RENDER BUT NEED CAT RENDER
```

we need write
```coffeescript
class Animal
  @render: -> console.log('Animal Render')
  run: -> @constructor.render() 
```

but `@constructor` is ugly. need sugar `static` keyword replace to `@constructor` and write

```coffeescript
class Animal
  @render: -> console.log('Animal Render')
  run: -> static.render() 
```

maybe:
```coffeescript
class Animal
  static render: -> console.log('Animal Render')
  run: -> static.render() 
```

**Comment by vendethiel** [comment]
Duplicate of #3222.

**Comment by MegaJsTeam** [comment]
but why this issues is closed?????

I thought of how to implement private properties.
I thought of how to implement static properties

and YOU close the tickets one by one!
you do not develop language!
do not add support ES6!

I understand coffeescript dead and my colleagues at the forum were right.
developers coffeescript buried his tongue. well. then I'll do a fork and show you how to do languages. girls.
