### ISSUE TITLE
Simplier syntax for destructuring object properties and values

### ISSUE THREAD

**Issue by Snowshield** [jashkenas/coffeescript#4213]
This syntax is some boilerplated. Can it be simplified?
From

```
keys = (key for key of obj)
vals = (val for _,val of obj)
```

or
`[keys, vals] = [(key for key of obj), (val for _,val of obj)]`

To
`[keys, vals] = ([key, val] for key,val of obj)`

**Comment by vendethiel** [comment]
Why not just define a function "keys" and "values"?

**Comment by Snowshield** [comment]
The proposal is based on idea that every functional method can be build over
`for in` / `for of `

My arguments:
1. We have similar syntax for map, filter, forEach. And can make same for unzip (scala example below).
2. This behavior is obvious
3. Objects have method `.keys()` but still dont have `.values()` ([Object.values()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values))
4. Mixins are bad

**Scala:**
```
Map(1 -> 2, 3 -> 4).unzip
// Res : (scala.collection.immutable.Iterable[Int], scala.collection.immutable.Iterable[Int])
// = (List(1, 3),List(2, 4))
```

**Comment by rdeforest** [comment]
The proposed syntax isn't clearer to me, jashkenas' other project, Underscore already has the keys and values functions. With Underscore your example becomes:

```coffeescript
[keys, values] = [_.keys obj, _.values obj]
```
which actually makes even more sense to me.

**Comment by lydell** [comment]
@rdeforest Don't you mean:

```coffee
[keys, values] = [(_.keys obj), (_.values obj)]
```

**Comment by GeoffreyBooth** [comment]
Closing for lack of consensus.
