### ISSUE TITLE
Lazy evaluation

### ISSUE THREAD

**Issue by kiberStender** [jashkenas/coffeescript#4215]
Hi all, Scala has this feature called lazy val which I think it could be cool to add this to CS. In fact it is very simple to reproduce (I use it in java and in coffee, of course, without syntax sugar). You could add (if you agree this feature is something nice to add) a 'lazy' keyword or something like this:

lazy variable = 10

and it could be compiled to:

var variable_ = null;

var variable = function(){
  if(!variable_){
    variable_ = 10;
  }
  return variable_;
};

With this idea we have the concept of evaluating variables on demand. It is very useful. What do you think? 
P.S: Yes I noticed it will become a function and it must be called variable() and it is indeed a bothering verbose.....

**Comment by vendethiel** [comment]
This wouldn't really have the same things as in scala, since it's always gonna be functions:

```coffee
memoize = (fn) -> # only memoize constants
  value = null
  didProcess = false
  ->
    if didProcess
      value
    else
      didProcess = true
      value = fn()

v = memoize -> console.log('process'); 10
console.log v()
console.log v()
```

**Comment by kiberStender** [comment]
I see. Thanks for this sample. I only used jQuery, Dojo and now I'm using RxJs, so because of this I never knew these alternatives in underscore or other libs.
