### ISSUE TITLE
Multi-line comments edge case

### ISSUE THREAD

**Issue by client9** [jashkenas/coffeescript#4216]
The parser for multi-line comments is not doing what I'd expect.

http://coffeescript.org/#try:%23%23%23%0Afoo%20bar%0A%23%23%23

```
###
foo bar
###
```

The output is expected

``` javascript
/*
foo bar
 */
```

But I add one more `#` 
http://coffeescript.org/#try:%23%23%23%23%0Afoo%20bar%0A%23%23%23

```
####
foo bar
###
```

we get...

``` javascript
foo(bar);
```

I don't know whats going on here, but  the parser / tokenizer appears to be starting immediately after the first `#` instead of starting after `###`

```
COMMENT    = /^###([^#][\s\S]*?)(?:###[^\n\S]*|###$)|^(?:\s*#(?!##[^#]).*)+/
```

(Another example might be easier in JS,  `/*/` isn't a full comment `/**/` is.)

This problem doesn't happen with multi-line strings

http://coffeescript.org/#try:'''%0Ajunk%0A'''

vs.

http://coffeescript.org/#try:''''%0Ajunk%0A'''

Thoughts?

regards,

nickg

**Comment by client9** [comment]
oh I see, it's designed so you can do `##########` banners or headlines.

and multi-line comments start with `###[^#]`

So maybe this is a doco problem actually.

**Comment by GeoffreyBooth** [comment]
Yes, this is intended behavior.
