### ISSUE TITLE
allow other assignment operators in default parameters

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#4225]
Hi!

I today learned about a difference between Coffeescript's default parameters and ES6's default parameters.

In Coffeescript:

``` coffeescript
f = (x = 'cat') -> console.log x
```

The `x = 'cat'` is equivalent to writing:

``` coffeescript
x ?= 'cat'
```

.. as one of the first statements in the compiled Javascript function body.

In ES6/Babel the default parameter assignment isn't a "not-null-and-not-undefined" check.  In ES6 when you write:

``` javascript
function f(x = 'cat') { console.log(x); }
```

It is doing this:

``` javascript
function f() {
  var x = arguments.length <= 0 || arguments[0] === undefined ? 'cat' : arguments[0];
  console.log(x);
}
```

So anyway, this annoys me - they shouldn't differ but they do.  So I wanted to see if I could be explicit about the non-null-and-non-undefined intent:

``` coffeescript
 f = (x ?= 'cat') -> console.log x
```

Which gives:

``` shell
[stdin]:1:8: error: unexpected ?=
f = (x ?= 'cat') -> console.log x
       ^^
```

Conclusions:

1) ES6's handling of default arguments is retarded.  Even if we wanted that in Coffeescript it's too late to change, it would break a lot of existing code and people are very used to this and have been for a while.
2) It might be useful to allow other assignment operators in default parameters.  Assignments like: `and=`, `or=`, `?=`, `+=`, etc...

Really this just opens up default args to be used as a sort of pre-function-body set of statements.  I wouldn't want to see anything too complex, as that would just encourage abuse.  So maybe just limit it to assignment increment/decrement operators?

This might be good or it might be bad - I just wish I could explicitly say `?=` in some projects where I'm writing both ES6 and Coffeescript.  I don't want `=` being viewed the same.

**Comment by vendethiel** [comment]
Rather than `?=`, `=` is actually viewed as `=`. It's an important difference, because it means `(x && y) ->` makes sense, but `(x += y) ->` doesn't really.

FWIW, coco/livescript allow this, so tagging as feature.

**Comment by blitmap** [comment]
@vendethiel I mean in Coffeescript `=` in the default arguments is interpreted like `?=`.  In default arguments - if other assignment operators were allowed - `=` would be the same as `?=`.  I initially wanted to propose this for instances where I'm working with both ES6 and Coffeescript in one project - so I can explicitly say `?=` in default arguments and there's no confusion about the difference between it and its interpretation in ES6.

Also, `+=`:

```coffeescript
inc = (x += 3) -> x

f = (y = 'cat', x += y) -> ...
```

My personal vote is all assignment operators and increment/decrement operators.  I think there's a chance it could lead to crazy-code, but I'm not sure Coffeescript enforces any rules on authors to 'not write dumb crap'.  Largely I see a few legitimate uses, and a lot of opportunities for bad ones. :)

Still want it.

**Comment by vendethiel** [comment]
`x += 3` doesn't really make sense – it's not a logical operator.

**Comment by blitmap** [comment]
I was interpreting that as "increment by 3" whatever gets passed in for `x`.  Why does it need to be a logical operator?

**Comment by michaelficarra** [comment]
@blitmap Numbers are passed by value. This proposals seems very poorly thought out, and I'm tempted to just close it until legitimate use cases are brought up.

**Comment by blitmap** [comment]
Well, do what you must - but my original use case was I wanted to explicitly use `?=` because `=` in default args has a differing meaning from ES6 I might write in the same project.

**Comment by GeoffreyBooth** [comment]
In 2.0.0 we follow ES semantics for default values: http://coffeescript.org/v2/#breaking-changes

It was discussed that we could keep `?=` as a way to trigger the legacy behavior, but that proposal was rejected as too confusing. Personally I think expressions within function parameters or conditionals is a bad practice that should not be encouraged.
