### ISSUE TITLE
inconsistency between anonymous and declared functions when passing callback without parameters

### ISSUE THREAD

**Issue by SJAnderson** [jashkenas/coffeescript#4230]
The following self-invoking function fails with `unexpected (`.
```coffee
((next) -> next()) ->
  console.log 'foobar'
```

However, the following runs just fine.
```coffee
foo = (next) -> next()
foo ->
  console.log 'foobar'
```

For reference, these are valid.
```coffee
((next) -> next()) (->
  console.log 'foobar'
)

((next) -> next()) () ->
  console.log 'foobar'
```

I propose that anonymous self-invoking functions can be passed callback arguments without defining parameters or wrapping the callback in parentheses.

**Comment by vendethiel** [comment]
The first one is (rightfullt) parsed as a parameter list + function body. If fails in the parameter list because the "parameter" doesn't have a name.

**Comment by SJAnderson** [comment]
@vendethiel  Are you saying that the first example is intended behavior?

**Comment by lydell** [comment]
@SJAnderson 

```coffee
run = (fn) -> fn() 

# Is `f` a function or 5?
f = (arg = run) -> 5


foo = null

# Is `g` a function, or does this throw a TypeError because you're trying to call an object?
g = ({arg: foo}) -> 
```

**Comment by vendethiel** [comment]
Yes, i am saying this is intended behavior.

**Comment by SJAnderson** [comment]
closing, thanks for clarifications everyone.
