### ISSUE TITLE
Add es6 support

### ISSUE THREAD

**Issue by MegaJsTeam** [jashkenas/coffeescript#4236]
The challenge to write sugar for es6, the same as was once written for es5.
Add es6 support iterators, getters, setters, generators, recursive import e.t.c. by compile flag -es6

And output code will be es6. then the user will be using compiler es5 to es6 (like babel), or leave the code in the initial es6 state, if his want.

example:

```coffeescript
Animal from './Animal.js'
(q) = 11

class Cat
  get name: -> alert('getter')
  set name: -> alert('setter')
```

compile to es6

```javascript
import Animal from './Animal.js';
const q = 11;

class Cat {
  get name() {return alert('getter')}
  set name(value) {return alert('setter')}
}
```

and babel translator compile is to es5:
```javascript
'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _Animal = require('./Animal.js');

var _Animal2 = _interopRequireDefault(_Animal);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var q = 11;

var Cat = function () {
  function Cat() {
    _classCallCheck(this, Cat);
  }

  _createClass(Cat, [{
    key: 'name',
    get: function get() {
      return alert('getter');
    },
    set: function set(value) {
      return alert('setter');
    }
  }]);

  return Cat;
}();
```

**Comment by MegaJsTeam** [comment]
p.s. it's not duplicate! do not mark it duplicate!

**Comment by MegaJsTeam** [comment]
i help you if you want! i hate brackets)))

**Comment by Eden-Sun** [comment]
https://github.com/decaffeinate/decaffeinate

**Comment by MegaJsTeam** [comment]
@Eden-Sun Yes but I do mean to develop coffeescript maintaining backward compatibility syntax, and do it "officially", and not third-party developers.

**Comment by Connormiha** [comment]
I like coffeescript, but if it doesn't learn to compile to ES2015+, then it is doomed.

**Comment by dadleyy** [comment]
I agree with @Connormiha. I love coffeescript and brought it into my codebase at work, and stand by that decision (over having gone with babel or some other compile-to-js choice). 

From a *compilation* standpoint, I the ability to compile into es6 is not very pressing to me. Whether or not

```coffeescript
{a, b} = this
```

becomes

```javascript
var {a, b} = this;
```

or

```javascript
var a, b;

a = this.a, b = this.b;
```

Is not really important to me right now, unless the performance benefits are wild. Same goes for arrow functions, default parameters, etc...

From a *feature* standpoint, I can't say there is a whole lot es6 brings to the table that coffescript doesn't already have. Coffeescript's arrow functions are fine, its object and array destruction are fine, its default arguments are fine, etc, etc... However, I really wish the language could re-visit it's stance on getters and setters, and I do think there is an ask out there (#4234, #4156, #3698) for just that.

**Comment by libary** [comment]
1. Animal from './Animal.js'
i think better than
Animal import './Animal.js'
2. q |= 11 
than 
const q = 11

**Comment by MegaJsTeam** [comment]
@libary in fact, I just wrote on the move the idea, of course is possible and necessary to think over the syntax, and I would have made this a separate repository.

```Animal from './Animal.js'```  is epic

```const q = 1``` maybe `q <= 11` ?

**Comment by libary** [comment]
@MegaJsTeam **q <= 11** looks like 'less or equal than'

**Comment by libary** [comment]
@MegaJsTeam for **const** we need assigning 'by three lines', but no such icon))

**Comment by MegaJsTeam** [comment]
@libary maybe ```(q) = 11``` compile to ```const q = 11``` ? cool syntax? =)

**Comment by MegaJsTeam** [comment]
we need not only to support ES6, but also sugar on ES6. on sugar constants as above, such as private property classes using Symbol and stuff like that!!!

**Comment by libary** [comment]
I would also like to be able to get the es6 result
**f = function(const x){...}**
f = ((x))->...
?

**Comment by libary** [comment]
jashkenas help with renew coffeescript2.0 ?))

**Comment by MegaJsTeam** [comment]
@libary why not? for some other reason, you can take a parameter in parentheses? 

> jashkenas help with renew coffeescript2.0 ?))
they do not want to develop coffeescript, so I want to make a fork and revive him, but there is no time. =(

**Comment by libary** [comment]
@MegaJsTeam "they do not want to develop coffeescript"
why?

**Comment by MegaJsTeam** [comment]
@libary  because I was banned 3 times when I offered to support es6? and this is my account 4 =))

as my issue voted not a lot of people, they do not even listen to and labeled as a duplicate.

**Comment by libary** [comment]
@MegaJsTeam Do I understand correctly that jashkenas does not plan to engage in further supporting and developing coffee?..

**Comment by MegaJsTeam** [comment]
@libary  Their argument is that it shall remain es3 support? and I tell them that this is just coffeescript sugar and es6 converted into es3 must deal with other translators. but they do not listen

**Comment by libary** [comment]
@MegaJsTeam and what does he want? he has his own vision of the development?

**Comment by MegaJsTeam** [comment]
@libary I do not know but it's open source, and it is not obliged us nothing and we owe him nothing. If you want, you can create your own language. since he does not want to, then we ourselves do.

**Comment by libary** [comment]
@MegaJsTeam it is of course true, but I am very sorry that he did not want. it would have been a strong support for coffee future.

**Comment by libary** [comment]
@MegaJsTeam I hope you're wrong, and he will do)

**Comment by MegaJsTeam** [comment]
@libary 
![image](https://cloud.githubusercontent.com/assets/17149958/14299564/df35a952-fb93-11e5-8592-1edac34a943f.png)
This man hinders the development of language, and I suggest to remove it from development
