### ISSUE TITLE
Private variables in coffeescript (not duplicate)

### ISSUE THREAD

**Issue by MegaJsTeam** [jashkenas/coffeescript#4237]
```coffeescript
class Cat

  constructor: ->
    @..name = 11
    @..func()
    return


  ..func: -> 1+1


(new Cat).name  #undefined
(new Cat)['..name']  #undefined
 ```
compile to:

```javascript

var Cat (function(){

  var _private_name_ = Symbol('name');
  var _private_func_ = Symbol('func');

  function Cat(){
    this[_private_name_] = 11;
    this[_private_func_]();
  }

  Cat.prototype[_private_func_] = function func() { return 1+1 }

  return Cat;

});


(new Cat).name  //undefined
 ```

and Symbol polyfilled like:

```javascript
var _crateSymbol = function(name){  
   return window.Symbol ? Symbol(name) : Math.random().toString().slice(2)+name
 }
```
   
there props not available in the child classes, since only the current class has access to the variable _private_name_. in the Symbol polyfill conflict names prevented by Math.random().

p.s. yes, people can access to private props from outside like this obj['23424235254name'] , but they don't do that, cuz not wants break theirs program.

**Comment by MegaJsTeam** [comment]
is not duplicate!

**Comment by MegaJsTeam** [comment]
this is cool syntax

**Comment by xooxdoo** [comment]
although Symbols are not meant for private keys use but as
> tool for Reflection within implementation
>
> http://blog.keithcirkel.co.uk/metaprogramming-in-es6-symbols/

but I get you :D

**Comment by MegaJsTeam** [comment]
@xooxdoo  private fields are created just to avoid name conflicts in classes successors. child classes to use some kind of field names without fear of accidentally override what the field is used in the implementation of the parent class. it is simply to avoid any name conflict. that's all. and the symbols for that perfect fit.

**Comment by xooxdoo** [comment]
yeah i just wanted to highlight the definition of `Symbol`s but as i said, I get your idea :D

**Comment by MegaJsTeam** [comment]
@xooxdoo to be precisely unique, we can do something like:

```javascript
function createSymbol(){
  var _global = (0, eval)('this');
  var lastIdProp  = '[[coffeescript_symbol_last_id]]';
  var id = global[lastIdProp] || 0;
  global[lastIdProp] = id + 1;

  return '[[Symbol(' + id + ')]]'
}
```

**Comment by xooxdoo** [comment]
yeah because based on Math.random you would need need a guid generator https://en.wikipedia.org/wiki/Globally_unique_identifier

```CoffeeScript
guid = ->
  guid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace /[xy]/g, (c)->
    r = Math.random()*16|0
    v = c == if 'x' then r else ( r & 0x3 | 0x8)
    v.toString 16
  do guid.toUpperCase
```

Translated to **CoffeeScript** from *Chapter 3: Models and Data* of **JavaScript Web Application**

**Comment by xooxdoo** [comment]
Or even better

```CoffeeScript
guid = ->
  'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'
    .replace /x/g, ->
      (Math.random()*16|0).toString 16
    .replace 'y', ->
      ((Math.random()*16|0) & 0x3 | 0x8).toString 16
    .toUpperCase()
```

**Comment by xooxdoo** [comment]
that uuid implementation is independant of global :D

**Comment by MegaJsTeam** [comment]
@xooxdoo ```Math.random()``` must be equals to ```Math.random()``` =)

**Comment by xooxdoo** [comment]
I doubt that someone would call "[[coffeescript_symbol_last_id]]", but not polluting the global space is something that got stuck in me as an instinct, reading The Good Parts, hearing that over and over in conference ... etc

Uhm... It's just my instinct, a habit, also its only in initialization time of JS code and i doubt there is a large CS code base that will create 1000000 private properties

**Comment by MegaJsTeam** [comment]
@xooxdoo do not pollute the global space is necessary in order to avoid accidental name conflicts. there will be no conflict =)

**Comment by xooxdoo** [comment]
https://en.wikipedia.org/wiki/Universally_unique_identifier

**Random UUID probability of duplicates**

> To put these numbers into perspective, the annual risk of a given person being hit by a meteorite is estimated to be one chance in 17 billion,[5] which means the probability is about 0.00000000006 (6 × 10−11), equivalent to the odds of creating a few tens of trillions of UUIDs in a year and having one duplicate. In other words, only after generating 1 billion UUIDs every second for the next 100 years, the probability of creating just one duplicate would be about 50%.

**Comment by xooxdoo** [comment]
i get you, only a complex machine such the CS compiler would use "[[coffeescript_symbol_last_id]]" as a property in window or global, any human must have surely lost it Hhhhh

**Comment by MegaJsTeam** [comment]
@xooxdoo 
my solution:

advantages:
1) faster
2) unique

limitations:
no

========
your solution:

advantages:
no
limitations:
1) slowly
2) is not unique

=================
I won, and you have no counter arguments =)

**Comment by vendethiel** [comment]
Please stop.
