### ISSUE TITLE
Computer won't sleep after installation, Mac OS 10.10.5

### ISSUE THREAD

**Issue by nhooey** [jashkenas/coffeescript#4240]
After installing CoffeeScript like so:
```bash
npm install -g coffee-script
```

My Mac won't sleep after the delay set in the system preferences.

My Energy Saver settings are set to "Turn display off after 15 minutes" for both "Battery" and "Power Adapter". I'm not sure what's going on.

Is there a background process that starts running after installation that could prevent the system from going idle?

**Comment by DiegoRBaquero** [comment]
Not really. Try `ps aux | grep coffee` in the console to see if anything related to coffee is running

**Comment by nhooey** [comment]
It was an April Fool's joke.

A little late, but I gotcha. ;)

**Comment by nhooey** [comment]
Tough crowd...
