### ISSUE TITLE
'in' operator doesn't guard against non arrays

### ISSUE THREAD

**Issue by avalanche1** [jashkenas/coffeescript#4241]
`123 in undefined`
throws `Array.prototype.indexOf called on null or undefined` whereas it should return `undefined`

**Comment by Snowshield** [comment]
No, **it shouldn't**. `in` operator in coffeescript is equal to `indexOf` in javascript. And in javascript you will get same error. I think you can close it.

**Comment by vendethiel** [comment]
Agreed. We don't do "defensive" programming in any construct that I'm aware of.

**Comment by fortybillion** [comment]
Any value in a defensive version of `in`? Something like `123 in? undefined`.

**Comment by avalanche1** [comment]
> Something like 123 in? undefined
Yeah, that could be nice

**Comment by Snowshield** [comment]
> Yeah, that would be nice

As i know `?` in works only with variables.
And you can get same result by `123 in ar if ar?`.

**Comment by vendethiel** [comment]
> And you can get same result by 123 in ar if ar?.

that wouldn't check for an Array.

**Comment by avalanche1** [comment]
> We don't do "defensive" programming

That's a real shame. Why not?

**Comment by blitmap** [comment]
This is issue has kind of been filed a few times before - once by me: #3650

I still think it's frustrating when `in` as a keyword could instead invoke a helper that checks with `.indexOf()` for an Array or walks through all the key-value pairs for an Object.  `in` should be more general - not Array-specific.  I doubt it would even matter performance-wise.

**Comment by michaelficarra** [comment]
You can use this very simple pattern:

```js
propertyName in (array ? [])
```

You should always know if a value you are working with is potentially null/undefined.
