### ISSUE TITLE
Private variables in coffeescript (please ban https://github.com/vendethiel)

### ISSUE THREAD

**Issue by MegaJsTeam** [jashkenas/coffeescript#4242]
please ban https://github.com/vendethiel user, he close this ticket. 

 private fields are created just to avoid name conflicts in classes successors. child classes to use some kind of field names without fear of accidentally override what the field is used in the implementation of the parent class. it is simply to avoid any name conflict. that's all. and the symbols for that perfect fit. For example class EventEmitter uses an internal "this.eventHandlers" property but that if he wants to rename it? suddenly have conflicts with classes successors? they do not have to know about the name of the internal field "eventHandlers", and they can use the same name inside self, if we make it private by using Symbol, or just add unique prefix field name like:

```javascript
 this[ Math.random().toString().slice(2) + 'propName' ]
```

BUT USER vendethiel STUPID  and think that if to a private property theoretically possible to get access from the outside, it becomes NOT private. Therefore this person technically illiterate.
Please ban it and remove from the team, it prevents the development of language.

Example:

```coffeescript
class Cat

  constructor: ->
    @..name = 11
    @..func()
    return


  ..func: -> 1+1


(new Cat).name  #undefined
(new Cat)['..name']  #undefined
```
compile to:

```javascript
var Cat (function(){

  var _private_name_ = Symbol('name');
  var _private_func_ = Symbol('func');

  function Cat(){
    this[_private_name_] = 11;
    this[_private_func_]();
  }

  Cat.prototype[_private_func_] = function func() { return 1+1 }

  return Cat;

});

(new Cat).name  //undefined
```

and Symbol polyfilled like:

```javascript
var _crateSymbol = function(name){  
   return window.Symbol ? Symbol(name) : Math.random().toString().slice(2)+name
 }
```

there props not available in the child classes, since only the current class has access to the variable private_name. in the Symbol polyfill conflict names prevented by Math.random().

p.s. yes, people can access to private props from outside like this obj['23424235254name'] , but they don't do that, cuz not wants break theirs program.

**Comment by milleniumbug** [comment]
wow you're fucking persistent

**Comment by carlsmith** [comment]
For the devs' sake, I hope MegaJSTeam gets hit by a bus or something, but he is pretty entertaining.

**Comment by vendethiel** [comment]
Well, it's not your mom he insulted. That hurts, you know!

**Comment by vendethiel** [comment]
Also, I'm still gonna close this one.  I'll answer in good faith, hoping you don't again plan to open 5 tickets insulting @michaelficarra's and my family:

- this is not something that's done by the JS community by and large
- coffeescript mostly ignores symbol / other non-syntactic ES6 changes
- you can't just assume `Math.random` will give unique values
- it's not private because instances can access each other's "private" values.

**Comment by carlsmith** [comment]
I didn't see him insult your mum. That's incredible. Now, I really do hope he gets hit by a bus - just gently.

**Comment by vendethiel** [comment]
- if someone really wanted into, Object.keys + filtering by suffix is easy enough

**Comment by nabijaczleweli** [comment]
@carlsmith For how long a distance is .338 lap mag effective? Asking for, um, a *friend*...

**Comment by nabijaczleweli** [comment]
Next episode: #4243
