### ISSUE TITLE
Private cariables in coffeescipt (i teach you, children)

### ISSUE THREAD

**Issue by MegaJsTeam** [jashkenas/coffeescript#4243]
It's fine if to private can be accessed OUTSIDE !! SCARY when they can conflict with the child properties CLASS !! YOU UNDERSTAND THAT FINALLY !! You are my uneducated incompetent !!

THIS IS GENERATOR UNIQUIE PROP NAMES LIKE SYMBOLS!!!!

```javascript
var _global = (0, eval)('this');
var _prop = '[[coffeescript_symbol_last_id]]';

function createSymbol(){
  var id = _global[_prop] || 0;
  _global[_prop] = id + 1;

  return '[[Symbol(' + id + ')]]'
}
```

please ban https://github.com/vendethiel user, he close this ticket. 

 private fields are created just to avoid name conflicts in classes successors. child classes to use some kind of field names without fear of accidentally override what the field is used in the implementation of the parent class. it is simply to avoid any name conflict. that's all. and the symbols for that perfect fit. For example class EventEmitter uses an internal "this.eventHandlers" property but that if he wants to rename it? suddenly have conflicts with classes successors? they do not have to know about the name of the internal field "eventHandlers", and they can use the same name inside self, if we make it private by using Symbol, or just add unique prefix field name like:

```javascript
var _global = (0, eval)('this');
var _prop = '[[coffeescript_symbol_last_id]]';

function createSymbol(){
  var id = _global[_prop] || 0;
  _global[_prop] = id + 1;

  return '[[Symbol(' + id + ')]]'
}
```

BUT USER vendethiel STUPID  and think that if to a private property theoretically possible to get access from the outside, it becomes NOT private. Therefore this person technically illiterate.
Please ban it and remove from the team, it prevents the development of language.

Example:

```coffeescript
class Cat

  constructor: ->
    @..name = 11
    @..func()
    return


  ..func: -> 1+1


(new Cat).name  #undefined
(new Cat)['..name']  #undefined
```
compile to:

```javascript
var Cat (function(){

  var _private_name_ = createSymbol('name');
  var _private_func_ = createSymbol('func');

  function Cat(){
    this[_private_name_] = 11;
    this[_private_func_]();
  }

  Cat.prototype[_private_func_] = function func() { return 1+1 }

  return Cat;

});

(new Cat).name  //undefined
```

and Symbol polyfilled like:

```javascript
var _crateSymbol = function(name){  
   return window.Symbol ? Symbol(name) : Math.random().toString().slice(2)+name
 }
```

there props not available in the child classes, since only the current class has access to the variable private_name. in the Symbol polyfill conflict names prevented by Math.random().

p.s. yes, people can access to private props from outside like this obj['23424235254name'] , but they don't do that, cuz not wants break theirs program.

**Comment by MegaJsTeam** [comment]
OMGGG/. stuupidd peopleee

It's fine if to private can be accessed OUTSIDE !! SCARY when they can conflict with the child properties CLASS !! YOU UNDERSTAND THAT FINALLY !! You are my uneducated incompetent !!

**Comment by nabijaczleweli** [comment]
>You are my uneducated incompetent !!

Tries to say the guy unable to form basic English sentences.

**Comment by vendethiel** [comment]
I'm almost angry. That's a pretty big feat. Needless to say, I reported you.
