### ISSUE TITLE
Do you have at least one argument against private property in my implementation?

### ISSUE THREAD

**Issue by MegaJsTeam** [jashkenas/coffeescript#4244]
Do you have at least one argument against private property in my implementation?

Let's discuss. I will prove to you that all your arguments are not true, but you name at least one.

p.s. https://simple.wikipedia.org/wiki/Ad_hominem

**Comment by nabijaczleweli** [comment]
I guess https://github.com/jashkenas/coffeescript/issues/4242#issuecomment-206023910 and https://github.com/jashkenas/coffeescript/issues/4242#issuecomment-206024098, that's five (5).

**Comment by milleniumbug** [comment]
It's funny hearing this coming from you

**Comment by nabijaczleweli** [comment]
(ref: previous episodes of one evening: #4243 and #4242)
