### ISSUE TITLE
It's such a shame for, more, and can not come up with the developers of coffeescript, I will show it to the whole community what javascript you miserable))

### ISSUE THREAD

**Issue by MegaJsTeam** [jashkenas/coffeescript#4247]
we can encapsulate private properties using namespase prefix  _, like this['_prop'], in fact, we are already doing so.

and despite the fact that we can access it outside, it will be all exactly private, because we documented: "User DONT USE props when prop names START ON _ symbol "!!

it's been about 8 days, I proposed this idea four times. I have not received any counterargument.... My tickets just closed. it seems to me, or I should take the development of the language in their own hands? time the developers just do not know what is "encapsulation using namespace"?

omg, I create a fork and show you how to programming, girls.

Goodbye, you are hopeless. and you will regret it, sad sack.

 Well, all the arguments are over. I understand there are no people of my level, to understand my basic ideas? It all comes in too low to understand that elementary encapsulation achieved by namespaces?

if we add the prefix properties, they have to be private, cuz that people from the outside will not cause the properties beginning with this prefix. cuz this prefix is NAMESPASE!!! like _

you understand, child?

and the conflict of names within a namespace, we prevent due to the generation of unique names.

you understand the words that I say, baby?
you  understand the letters that I write? ignoramus

mark my words)) I will be Hokage!

I suggested a new idea to improve the language !! but the language must be dead, and not develop! and developers are too dumb to realize my elementary idea! Please ban me immediately! such is not acceptable! I'm a troll! arguments are not needed! just ban me!111 just ignore me!!11

![image](https://cloud.githubusercontent.com/assets/17149958/14302316/5839bd70-fba8-11e5-8a14-56aa2ad6f47a.png)

**Comment by MegaJsTeam** [comment]
I did all that I could

**Comment by MegaJsTeam** [comment]
please close it as you read

**Comment by nabijaczleweli** [comment]
All PRs are welcome (●‿●✿)

**Comment by MegaJsTeam** [comment]
@nabijaczleweli I thought of how to implement private properties, he says that if you can get outside dosup they allegedly not private. but it is not.

**Comment by nabijaczleweli** [comment]
>I thought

I believe that is not the case. However, all PRs are welcome (●‿●✿)

**Comment by MegaJsTeam** [comment]
> I believe that is not the case. However, all PRs are welcome (●‿●✿)

 https://simple.wikipedia.org/wiki/Ad_hominem

you have some counterarguments to my words?

**Comment by MegaJsTeam** [comment]
I understand that I'm just a better programmer than you, and you just get angry =)

**Comment by MegaJsTeam** [comment]
i repeat:

```coffeescript
class Cat

  run: ->
  ..say: ->    
```


compile to:

```javascript

window.LAST_PRIVATE_ID = 0

Cat = (function(){
  var ___PRIVATE__NAME = "______PRIVATE_____PROP___PREFIXXXX__X_X_X_X_" + LAST_PRIVATE_ID++
  function Cat(){}
  Cat.prototype.run = function(){}
  Cat.prototype[___PRIVATE__NAME ] = function(){}
})
```

**Comment by nabijaczleweli** [comment]
I believe that a good counterargument would be the sentences that you've written this evening (and multiple previous ones). Oh, who am I kidding, most of those aren't actual sentences in the English language. 
Feeding the troll ends... now.

**Comment by MegaJsTeam** [comment]
@nabijaczleweli  I'm just out of Russia and I am writing through translator
besides this https://simple.wikipedia.org/wiki/Ad_hominem again

**Comment by nabijaczleweli** [comment]
Yes: it doesn't work, as Ven told you many a times.

**Comment by MegaJsTeam** [comment]
@nabijaczleweli why?

**Comment by nabijaczleweli** [comment]
I don't know. Try reading?

**Comment by MegaJsTeam** [comment]
read that?

**Comment by MegaJsTeam** [comment]
Well, all the arguments are over. I understand there are no people of my level, to understand my basic ideas? It all comes in too low to understand that elementary encapsulation achieved by namespaces?

**Comment by MegaJsTeam** [comment]
counter arguments will be? I did not hear any

**Comment by carlsmith** [comment]
@nabijaczleweli - Just ignore him. He's a troll. Anyone who writes all that crap, then criticises you for an *ad hominem* attack is obviously not serious.

**Comment by MegaJsTeam** [comment]
@carlsmith 
I suggested a new idea to improve the language !! but the language must be dead, and not develop! and developers are too dumb to realize my elementary idea! Please ban me immediately! such is not acceptable! I'm a troll!

**Comment by MegaJsTeam** [comment]
it's been about 8 days, I proposed this idea four times. I never had a single argument.... My tickets just closed

**Comment by MegaJsTeam** [comment]
please close it
