### ISSUE TITLE
parallel assignment semantics

### ISSUE THREAD

**Issue by alwendt** [jashkenas/coffeescript#4249]
What is the desired translation for

[a,a.b] = [c,a]?

should it be

tmp = a
a = c
tmp.b = a

which preserves the parallel semantics?  Current translation does not preserve parallel semantics.

**Comment by GeoffreyBooth** [comment]
The `[c,a]?` just asks if the right-hand side exists or not—so it returns true or false. Presumably you want something to happen as a result of that conditional, e.g. `[a,a.b] = [c,a] if [c,a]?`

**Comment by alwendt** [comment]
The question mark in the above was part of the question, not part of the expression.

**Comment by alwendt** [comment]
What is the semantics of [a,a.b] = [c,a]

**Comment by Inve1951** [comment]
[v1/#try](http://coffeescript.org/v1/#try:%5Ba%2Ca.b%5D%20%3D%20%5Bc%2Ca%5D)
