### ISSUE TITLE
Coffeescript compiler generates incorrect sourceRoot / sources in the presence of symlinks in the filesystem

### ISSUE THREAD

**Issue by dgoldstein0** [jashkenas/coffeescript#4250]
Spent a few hours today tracking this down... right now I'm planning to work around this by resolving to real paths before constructing my coffeescript compile command, but I figured I should document the bug in hopes that maybe it'll help someone or eventually get fixed.

I set up the following directory structure:
- ~/dontserve
- dontserve contains a folder `static`, which itself contains `javascript/compiled` and `coffee` folders
- source .coffee files go into `coffee`, and get compiled into `javascript/compiled`.  This example uses `asdf.coffee` as the only source.  (all that matters is that it's valid coffeescript.)
- ~/a as a symlink to ~/dontserve

now the command

```
$ coffee --compile --map --output ~/dontserve/static/javascript/compiled ~/dontserve/static/coffee/asdf.coffee
```

Generates the following (correct) sourcemap:

```
{
  "version": 3,
  "file": "asdf.js",
  "sourceRoot": "../../..",
  "sources": [
    "static/coffee/asdf.coffee"
  ],
  "names": [],
  "mappings": ";AAAA;EAAA,MAAA,CAAO,CAAC,GAAD,EAAM,GAAN,EAAW,GAAX,CAAP,EAAwB,SAAC,CAAD,EAAI,CAAJ,EAAO,CAAP;AACtB,WAAO,CAAA,GAAI,CAAJ,GAAQ;EADO,CAAxB;AAAA"
}
```

Whereas the alternate command - which only differs by using the symlinked locations:

```
$ coffee --compile --map --output ~/a/static/javascript/compiled ~/a/static/coffee/asdf.coffee
```

produces the sourcemap

```
{
  "version": 3,
  "file": "asdf.js",
  "sourceRoot": "../../../../dontserve",
  "sources": [
    "../a/static/coffee/asdf.coffee"
  ],
  "names": [],
  "mappings": ";AAAA;EAAA,MAAA,CAAO,CAAC,GAAD,EAAM,GAAN,EAAW,GAAX,CAAP,EAAwB,SAAC,CAAD,EAAI,CAAJ,EAAO,CAAP;AACtB,WAAO,CAAA,GAAI,CAAJ,GAAQ;EADO,CAAxB;AAAA"
}
```

It would appear that `coffee` is somehow resolving symlinks in the `--output` argument, without doing the same for the input file paths.  This is a problem because neither `a` or `dontserve` do not appear on my webserver - the root path contains `static`.

My only workaround for the moment is to resolve paths with symlinks in them to their canonical paths before invoking `coffee`.  Requiring this seems fragile though.

**Comment by GeoffreyBooth** [comment]
The sourcemap generation code has been refactored since this issue was posted. If there is still an issue in the current `2`-branch compiler, please update this issue or open a new one.

**Comment by dgoldstein0** [comment]
I worked around the issue a long time ago by resolving paths before I fed
them to coffee.  Given that, and that I'm using code 1.10 still, and that
I'm ditching coffee in favor of typescript, I'm not going to bother testing
if it's fixed or not.
