### ISSUE TITLE
Forced patch of Error.prepareStackTrace conflicts with other libraries

### ISSUE THREAD

**Issue by doublerebel** [jashkenas/coffeescript#4258]
Hello,

I've been running into issues related to [node-source-map-support#34](https://github.com/evanw/node-source-map-support/issues/34).  **source-map-support** also monkey-patches `Error.prepareStackTrace`, and it would be great to have a CoffeeScript option to disable its patching.

In this particular case, I am using **connect-assets** to autocompile .coffee files for an express app.  Although **connect-assets**'s dep **mincer** [only uses the `coffee.compile()` fn](https://github.com/nodeca/mincer/blob/33adf020804931d6fbc7276247019b5b4682361f/lib/mincer/engines/coffee_engine.js#L86), the `require("coffee-script")` call still patches `Error.prepareStackTrace`.

I had to step through a lot of packages to find which package loaded in a way that was clobbering my prepareStackTrace.

I also [recently solved this issue for **node-vault**](https://github.com/kr1sp1n/node-vault/issues/17), so it's not an isolated problem.  I don't think it's clear enough to developers that `require("coffee-script")` will have this effect, I think having the option to disable it in the docs would help.

Thanks for your work, CoffeeScript is awesome!

**Comment by GeoffreyBooth** [comment]
@doublerebel per #4428 the patched version of `Error.prepareStackTrace` now only returns a modified stack trace for compiled CoffeeScript code, otherwise passing through the original runtime stack trace. Does this solve your issue?

We’re not looking to add any additional options to the CoffeeScript compiler.

**Comment by GeoffreyBooth** [comment]
@doublerebel is this still an issue?

**Comment by GeoffreyBooth** [comment]
If this is still an issue, please comment and I will reopen.
