### ISSUE TITLE
2 hierarchy destructuring is wrong

### ISSUE THREAD

**Issue by benjaminhon** [jashkenas/coffeescript#4259]
Hi All, i have the following

```coffee
.each ({notification: {action}}) ->
 if action? do something
```

however it translates to

```js
var action;
action = arg.notification.action; 
```

Because the object might be null, or notification not present, then it fails because arg.notification is null. Why is it that coffee script does not assign notification a value? this is weird. No variable was created for notification for me to check if it is null.

**Comment by lydell** [comment]
CoffeeScript’s destructuring works more or less as ES2015. You want this:

```coffee
.each ({notification: {action} = {}}) ->
 if action? do something
```

Or possibly this:

```coffee
.each ({notification: {action} = {}} = {}) ->
 if action? do something
```

This has been discussed on the issue tracker a few times before, if you want to read more about it. However, my Internet connection is too bad to find where right now. Search! :)

**Comment by benjaminhon** [comment]
Ah Okay,
Thx
