### ISSUE TITLE
Syntax error compilator when you concat a variable and a string

### ISSUE THREAD

**Issue by radjivC** [jashkenas/coffeescript#4262]
If you don't put a space between a variable and string. Coffee script will turn the variable into a function and blow-up
```
TypeError: string_value is not a function e=[TypeError: string_value is not a function]
```

![screen shot 2016-05-02 at 11 14 35 am](https://cloud.githubusercontent.com/assets/5714138/14945580/944a8a74-1057-11e6-9760-e1464f899aa8.png)

**Comment by michaelficarra** [comment]
Please see the many many duplicates.
