### ISSUE TITLE
script type=text/coffeescript tag does not support unicode (utf-8) properly

### ISSUE THREAD

**Issue by Masterxilo** [jashkenas/coffeescript#4263]
Running this html file, saved with utf-8 encoding (no BOM) in Chrome:

```
<meta charset=utf-8>
<script src=/lib/coffee-script.js></script>
<script>
alert('js:おねがいします')
</script>
<script type=text/coffeescript>
alert('cs:おねがいします')
</script>
```

generates

```
coffee-script.js:6459 Uncaught InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

The error is generated on the lines saying

```
      case typeof btoa !== 'function':
        return btoa(src);
```

in coffee-script.js

The javascript tag has no problems with this string.

**Comment by Masterxilo** [comment]
I guess this lists solutions on how to make btoa deal with utf-8:

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_.232_.E2.80.93_rewriting_atob()_and_btoa()_using_TypedArrays_and_UTF-8

**Comment by Masterxilo** [comment]
As by these suggestions, replacing

```
      case typeof btoa !== 'function':
        return btoa(src);
```

with

```
case typeof btoa !== 'function':
function b64EncodeUnicode(str) {
    return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function(match, p1) {
        return String.fromCharCode('0x' + p1);
    }));
}
return b64EncodeUnicode(src);
```

seems to fix the problem for now. More work is needed for determining the implications of this.

(I for one don't even know why this encoding to base64 is needed).

---

Interestingly, the parser does not generally have a problem with utf-8 (that would have been noticed earlier I guess). The following works as expected:

```
<meta charset=utf-8>
<script src=/lib/coffee-script.js></script>
<script>
alert('js:おねがいします')
</script>
<div id=text>alert('cs:おねがいします')</div>
<script type=text/coffeescript>
eval(document.getElementById('text').innerHTML)
</script>
```

**Comment by vlad1777d** [comment]
I have the same error:
`<script  type="text/javascript" src="./scripts/coffee-script.js" charset="utf-8"></script>`
`<script type="text/coffeescript" charset='utf-8'>alert "Рукава и горсти"</script>`

throws me into error:
"InvalidCharacterError: String contains an invalid character"

If there will be:
`<script type="text/coffeescript" charset='utf-8'>alert "Text in English"</script>`
, all will work well.

How to solve this?

**Comment by vlad1777d** [comment]
I changed this:
![2016-11-23 02-47-14](https://cloud.githubusercontent.com/assets/12682937/20547798/4c4348d0-b127-11e6-8c0f-38ad22a909e6.png)
to this:
![2016-11-23 02-48-06](https://cloud.githubusercontent.com/assets/12682937/20547803/52c0b436-b127-11e6-8758-d01a0f7bb978.png)

And all worked.
