### ISSUE TITLE
shorthand syntax for method.call obj, args...

### ISSUE THREAD

**Issue by metalim** [jashkenas/coffeescript#4264]
`hasOwnProp.call parent, key` has syntax reversed.
`parent \\ hasOwnProp key` is more readable.
Alternative symbols:
`parent\.hasOwnProp key`
`parent..hasOwnProp key` - could conflict with .. in range.

Also, `obj \\ someMethod args...` could translate to `someMethod.apply obj, args`.

**Comment by GeoffreyBooth** [comment]
We can't use `\\` as this conflicts with escaping a backslash. Also `.call` it's short enough that your operator barely saves a few characters. I don't think `.call` is used often enough to justify a dedicated shortcut operator.
