### ISSUE TITLE
Statement regarding CoffeeScript’s relationship with ES2015 and its successors

### ISSUE THREAD

**Issue by GeoffreyBooth** [jashkenas/coffeescript#4265]
There should be a statement on coffeescript.org or in this repo’s README explaining how CoffeeScript intends to grow and adapt (or not) in relation to ES2015 and its successors. In particular, will CoffeeScript ever output ES2015 JavaScript? Will it support modules, and if so, how? How will it handle near-equivalents—will it transpile fat arrows to fat arrows, or CoffeeScript’s `class` to ES2015’s `class`? See also #3162.

**Comment by adam-h** [comment]
It's worth noting that browser support is relatively strong already for ES2015 features.

 - Chrome and Firefox supports most everything
 - MS Edge has strong support under a flag
 - Safari 9 has some, but the technology preview supports almost all
 - Node 6 (upcoming LTS) supports almost all

I would guess that if CoffeeScript started work on these, by the time they were ready everygreen browsers would support it without transpiling.

[source](https://kangax.github.io/compat-table/es6/)

**Comment by MrOutput** [comment]
@adam-h that's common knowledge. The idea is that people need to know if their existing coffeescript needs to be rewritten in native code or if coffeescript creators will adapt to the standards.

**Comment by JimPanic** [comment]
What interests me the most: *are* there plans for coffee to develop any direction (e.g. the redux fork)? 

ES6 is just one of those directions it might go, the other ones are equally interesting for me to think about though.

**Comment by loveencounterflow** [comment]
I must say I'm just as worried about the future of the language as I was enthusiastic when I started to use it years ago. I have advocated many times that in my view, what CS needs to keep developing are **1** optional language features that can be turned on on a per-module or per-function base, similar to `"use strict"` (NO command lines switches pls!), **2** implemented in a 'modular' (not necessarily in the CommonJS sense) / 'plug-in' fashion, 3rd parties welcome.

**Comment by kulicuu** [comment]
I consider CoffeeScript the most underrated language on the planet right now. Why? On the one hand you get access to the full gamut of the npm & node ecosystems, on the other you get a syntax which beats Ruby & Python out for sheer concision, on top of an already underrated JS, which is natively capable of most of the best from the functional programming patterns (most of anything you might want to do with Clojure).  
Yet it's considered an unfortunate mutant, without the hipster cachet of Clojure or Haskell, or the workhorse cachet of the Babel flavours, Ruby, and Python. While in my opinion it slightly exceeds all of these, not on every measure for every contender, but for the overall mix of benefits it offers.

The only real downside I see to adopting CffSc nowadays is that it's considered pretentious &/or taboo in so many circles, and can therefore be a drag on career, adoption, or whatever.  Which is too bad, but not the fault of the language.

I recently joked that when ES20 "adopts a terse Python/Ruby-like syntax", it will finally be accepted that it was never a fringe language, and actually has been trailblazing for the JS world the whole time.  Put another way, CffSc doesn't need to do much of anything to keep pace with ES6 or ES7, it's already way past it.  Exceptions pop up and are dealt with, implementation of generator support comes to mind -- not that I've actually used generators in a real project.
 
CffSc should be the focus of active development attention; kept simple and performant.  I wouldn't presume myself to be one to prioritise feature implementation, that's for others.  I am going to try to get into contributing some on outstanding issues.  Hopefully will have some work completed on that soon.

**Comment by danielbayley** [comment]
> it's considered pretentious

What's pretentious is pretending that plain vanilla JavaScript isn't a fugly pig of a language and ES6 isn't a thin layer of lipstick on it.

**Comment by kulicuu** [comment]
Well said.  On the other hand, for the cause so-to-speak (after all CffSc is _just_ JS), it's worth emphasising that JS is an extremely powerful and flexible functional programming language.  This is what CoffeeScript benefits from.

**Comment by danielbayley** [comment]
Sure, and it has the best ecosystem. Just the syntax is _awful._ It's totally fine if people (usually out of habit/coming from C type langs etc…) prefer it but please stop with this meme that CS is dead and we all _have_ to conform to it's poor replacement in ES6. Bracket nazis…

**Comment by kulicuu** [comment]
Agreed on that.

**Comment by mrmowgli** [comment]
+1 on what the planned ES6 to CS mappings will be in the future.  

I don't think there needs to be much actually done to CS to leverage everything.   Looking at the [compatibility map](http://kangax.github.io/compat-table/es6/) gives a nice list of the language features.

Changes would seem to fall into two categories: languages-isms (like the function*(){} vs. yield keyword) and JS keywords.  I don't think CS cares whether you use Promises or not for instance.  

Really what parts of ES6 can you not currently do in CS?

**Comment by longspear** [comment]
I prefer CoffeeScript over Python because it's nicer, doesn't have the stupid 'def' keyword that looks ugly and even uglier now with 'async def' in Python 3.5. The package system (npm) is way better and simpler than python's pip.

So there you go. Better syntax, more dynamicness and isn't ugly like vanilla JS or even ES6 ("import redis from 'redis'" -- really?).

+99999 for CoffeeScript. On a side note, will IcedCoffeeScript ever get merged into this repository?

**Comment by DomVinyard** [comment]
@mrmowgli 

Async/Await is a real paradigm shift for the entire language in terms of the cognitive representation of control flow. I think if coffeescript were to nail that (for me that means implicit async if await is detected in the function body), that would go a long way towards feeling 'up to date'.

+1 for best language on the planet.

**Comment by carlsmith** [comment]
> Really what parts of ES6 can you not currently do in CS?

You can't extend ES6 classes. There are other things, but they can be fixed - many have been fixed in forks - but unless someone knows how to make CS and JS classes compatible, we're going to need a breaking change. Otherwise, we will not be able to use certain JS library APIs from CoffeeScript.

If anyone wants to discuss how to prevent CoffeeScript from becoming obsolete, or just to tell us why we're wrong, there's [a new repo][1] that you're all welcome to contribute to.

[1]: https://github.com/coffeescript6/discuss

**Comment by crisward** [comment]
Anyone messed with this https://github.com/decaffeinate/decaffeinate ?

**Comment by danielbayley** [comment]
There are now at least 3 different repositories focused on this:
* [decaffeinate](https://github.com/decaffeinate/decaffeinate)
* [decaf](https://github.com/rainforestapp/decaf)
* [coffeescript6](https://github.com/coffeescript6/discuss)

See also #4078…

@jashkenas If only efforts could somehow not be duplicated/wasted by bringing them together under [the CoffeeScript organisation](https://github.com/coffeescript)…

**Comment by vendethiel** [comment]
related https://github.com/coffeescript6/discuss/issues/3#issuecomment-232719946

**Comment by GeoffreyBooth** [comment]
Do we want to link to [coffeescript6/discuss](https://github.com/coffeescript6/discuss) from coffeescript.org?

**Comment by GeoffreyBooth** [comment]
I think the README at https://github.com/coffeescript6/discuss and the comments on https://github.com/coffeescript6/discuss/issues/36 are pretty much what I was looking for in terms of a public statement. I accept that these are “public enough” even if they’re not in this repo or on coffeescript.org, acknowledging the concern of overly presenting our plans to the point of promoting vaporware.
