### ISSUE TITLE
Missing syntax error for destructuring assignments with `@`

### ISSUE THREAD

**Issue by maxnordlund** [jashkenas/coffeescript#4266]
Instead of a syntax error it miscompiles destructuring assignments with `@`, like so:

``` coffeescript
{ @bar: baz } = foo # Accidental reversion of `@`, should probably be `{ bar: @baz } = foo`
```

``` javascript
var baz;

baz = foo.this; // This is not what you would expect it to do
```

**Comment by connec** [comment]
This is because `@` variables are generally treated as a single variable for destructuring purposes in order to allow

```coffee
{ @a } = opts
({ @a }) ->
# etc.
```

**Comment by NikolaMandic** [comment]
what do you think on making destructuring with default assignment work for non constructors.
that would be nice

**Comment by GeoffreyBooth** [comment]
`{ @bar: baz } = foo` doesn’t compile in CS2.
