### ISSUE TITLE
SourceMap.generate now returns an object instead of a string, causing tests to fail

### ISSUE THREAD

**Issue by GeoffreyBooth** [jashkenas/coffeescript#4269]
@lydell and @michaelficarra, the [March 6 version of `SourceMap.generate`](https://github.com/jashkenas/coffeescript/commit/841b3cd2ad7e1eea8115a7d1e5ceafdf01bb9259#diff-c49e40641aa71031a2f54b0c1101b01fR131) returns an object instead of a string. This causes the tests in `test/sourcemap.coffee:34-35` to fail.

I understand the desire to not return pretty-printed JSON, but shouldn’t this function still return JSON (i.e., a string) rather than an object? Seems like lots of things could break if we change the type of what this function returns.

So either we should change `src/sourcemap.litcoffee:131` to

```coffee
JSON.stringify v3
```

to restore the previous “returning JSON string” behavior, or we should update `test/sourcemap.coffee:34-35` so that the test expects objects:

```coffee
  eqJson JSON.stringify(testWithFilenames), '{"version":3,"file":"source.js","sourceRoot":"","sources":["source.coffee"],"names":[],"mappings":"AAAA;;IACK,GAAC,CAAG;IAET"}'
  eqJson JSON.stringify(map.generate()), '{"version":3,"file":"","sourceRoot":"","sources":[""],"names":[],"mappings":"AAAA;;IACK,GAAC,CAAG;IAET"}'
```

Please let me know the intent and I can submit a PR.

**Comment by lydell** [comment]
Thanks for finding out! How sloppy of me to forget to update the tests. Please see the commit d7e752bc5db31bcba940c46bb77305c3ea6251d8 for more information.
