### ISSUE TITLE
CoffeeScript compile slow in Internet Explorer 11

### ISSUE THREAD

**Issue by dave-k** [jashkenas/coffeescript#4271]
I have a large file which takes over 30 seconds for the compiler to return syntax errors.

1. In Internet explorer
2. browse https://ace.c9.io/build/kitchen-sink.html
3. copy and paste: coffeescript/src/nodes.coffee
4. add an unmatched ']' character 
5. wait ~20 seconds for the red X

Is there a way to improve this time in IE 11?

Any suggestions appreciated.

**Comment by jashkenas** [comment]
@dave-k What happened? Figure it out?

**Comment by dave-k** [comment]
We advised users to use another browser: Chrome or Firefox.
