### ISSUE TITLE
command line

### ISSUE THREAD

**Issue by Kaseano** [jashkenas/coffeescript#4272]
I'm not sure if this counts as an issue or user error, but it was definitely a surprise and a funny story.
I have a directory of .coffee files (in windows), I usually run:
$ coffee -cw .

I typo'ed it and ran $ coffee -cw /

This locked up the command prompt, and loudly beeped at me for a minute while I panicked and tried to force shut it down while my co-workers laughed and watched.

I'm guessing it was trying to recursively compile everything on the disk.

**Comment by vendethiel** [comment]
Certainly a funny story... But I'm not sure we should detect it. :P

**Comment by bjskistad** [comment]
@Kaseano What terminal are you using? Bash?

**Comment by michaelficarra** [comment]
Closing, as there's nothing for us to do here.
