### ISSUE TITLE
Location information in some triple-quoted strings is incorrect

### ISSUE THREAD

**Issue by eventualbuddha** [jashkenas/coffeescript#4275]
For example:

``` coffeescript
"""
a
"""
```

The location information for the `STRING` token is:

``` javascript
{
  first_line: 0,
  first_column: 0,
  last_line: 1,      // should be 2
  last_column: 4     // should be 3
}
```

I'm not averse to submitting a PR for this, but it's not clear where in `lexer.coffee` needs to be changed. Is it `matchWithInterpolations`? Or `stringToken`?

**Comment by GeoffreyBooth** [comment]
A PR for this would be welcome.
