### ISSUE TITLE
using coffee-script with webpack

### ISSUE THREAD

**Issue by Radivarig** [jashkenas/coffeescript#4276]
When I require with webpack `var CoffeeScript = require ('coffee-script')` I get the following output
```
WARNING in ./~/coffee-script/lib/coffee-script/coffee-script.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/coffee-script/lib/coffee-script/coffee-script.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/coffee-script/lib/coffee-script/coffee-script.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/coffee-script/lib/coffee-script/coffee-script.js
Critical dependencies:
175:42-49 require function is used in a way in which dependencies cannot be statically extracted
179:26-33 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/coffee-script/lib/coffee-script/coffee-script.js 175:42-49 179:26-33

WARNING in ./~/coffee-script/lib/coffee-script/register.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/coffee-script/lib/coffee-script/register.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/coffee-script/lib/coffee-script/browser.js
Critical dependencies:
8:25-32 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/coffee-script/lib/coffee-script/browser.js 8:25-32

ERROR in ./~/coffee-script/bin/coffee
Module parse failed: /path_to_repo/node_modules/coffee-script/bin/coffee Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp.raise (/path_to_repo/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/path_to_repo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/path_to_repo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/path_to_repo/node_modules/webpack/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/path_to_repo/node_modules/webpack/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/path_to_repo/node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/path_to_repo/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/path_to_repo/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/path_to_repo/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/path_to_repo/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/coffee-script/lib/coffee-script/register.js 52:13-48

ERROR in ./~/coffee-script/lib/coffee-script/coffee-script.js
Module not found: Error: Cannot resolve module 'module' in /path_to_repo/node_modules/coffee-script/lib/coffee-script
 @ ./~/coffee-script/lib/coffee-script/coffee-script.js 129:23-40 169:17-34

ERROR in ./~/coffee-script/lib/coffee-script/register.js
Module not found: Error: Cannot resolve module 'child_process' in /path_to_repo/node_modules/coffee-script/lib/coffee-script
 @ ./~/coffee-script/lib/coffee-script/register.js 7:18-42

ERROR in ./~/coffee-script/lib/coffee-script/register.js
Module not found: Error: Cannot resolve module 'module' in /path_to_repo/node_modules/coffee-script/lib/coffee-script
 @ ./~/coffee-script/lib/coffee-script/register.js 25:13-30

ERROR in ./~/coffee-script/lib/coffee-script/command.js
Module not found: Error: Cannot resolve module 'child_process' in /path_to_repo/node_modules/coffee-script/lib/coffee-script
 @ ./~/coffee-script/lib/coffee-script/command.js 16:8-32

ERROR in ./~/coffee-script/lib/coffee-script/grammar.js
Module not found: Error: Cannot resolve module 'jison' in /path_to_repo/node_modules/coffee-script/lib/coffee-script
 @ ./~/coffee-script/lib/coffee-script/grammar.js 5:11-27

ERROR in ./~/coffee-script/lib/coffee-script/repl.js
Module not found: Error: Cannot resolve module 'repl' in /path_to_repo/node_modules/coffee-script/lib/coffee-script
 @ ./~/coffee-script/lib/coffee-script/repl.js 11:13-28
webpack: bundle is now VALID.
```

if I include a fatter 160kb local file of coffer-script-1.9.3-min.js everything works but I'd like to avoid adding library build to source if possible.

Any ideas? Thanks

**Comment by vendethiel** [comment]
I'd say the error message is pretty self-explanatory: don't require coffeescript directly, use a loader.

Googling "webpack coffeescript loader" gave me https://github.com/webpack/coffee-loader as the first result.

Also, please try to refrain using github issues as a help forum – it's better to use StackOverflow.

**Comment by Radivarig** [comment]
I am trying to use CoffeScript.compile("coffeescript string code") in browser so loader won't work, that is why I posted here.

**Comment by timhuff** [comment]
Future traveler: I'm struggling with the same issue. Seems to not be an unreasonable thing to want (for example, the coffeescript.org website). I was wanting to do this for the purpose of writing an Electron app. My solution was to use [IPC](https://electron.atom.io/docs/api/ipc-main/) to communicate between the browser and the renderer. The browser is a node environment, so I compile it there and then send it back.

**Comment by Radivarig** [comment]
@timhuff using the built library file works for me so I added it as npm package called `coffee-script_compiler` to avoid adding it to my source, you can try it `npm i coffee-script_compiler --save` then just require it with webpack and use in browser.

**Comment by timhuff** [comment]
@Radivarig You're a life-saver, man. That's so much nicer. Thanks.

**Comment by GeoffreyBooth** [comment]
You want `require('coffee-script/register')`. 

- http://stackoverflow.com/a/21585379/223225
- https://github.com/jashkenas/coffeescript/issues/3349

**Comment by akfish** [comment]
I built a [custom fork](https://github.com/akfish/coffeescript) for my project with compiler API exposed for webpack.

Just `npm install --save github:akfish/coffeescript#webpack` and 
```js
import { compile } from 'coffee-script'
```

**Comment by GeoffreyBooth** [comment]
@akfish how does your fork compare with https://github.com/webpack-contrib/coffee-loader? As in, why would someone use your fork rather than coffee-loader?

**Comment by timhuff** [comment]
@GeoffreyBooth The issue is not compiling coffeescript with webpack. It's using the `coffee-script` package as a compiler *inside* a webpack application. In my case, I was making a coffeescript-based REPL of sorts (similar to what's on the top of the coffeescript website).

**Comment by akfish** [comment]
@GeoffreyBooth coffee-loader works at compile time, not runtime.
If someone is trying to make a tool that takes user input and compiles on-the-fly in browser, he'll need some way to pack the coffee compiler into his build.

**Comment by GeoffreyBooth** [comment]
Can you post a minimal example app of what you’re trying to accomplish? It sounds like you want to `require` something that contains a `compile` method?

**Comment by timhuff** [comment]
@GeoffreyBooth I don't think anyone's still attempting to do this. @Radivarig's tool solved it for me. @akfish was simply contributing his work for future visitors.

**Comment by timhuff** [comment]
@GeoffreyBooth But to answer your question, yea, the idea is to write something along the lines of:

> coffee = require 'coffee-script'
> output = coffee.compile userInput

**Comment by akfish** [comment]
```js
import { compile } from 'coffee-script'

// User input coffee source
let src = editor.text;

// Compile it in browser
let compiledCode = compile(src, opts)

// Run compiled code or whatever
doStuffWith(compiledCode)
```
Or imagining tools like codepen, jsfiddle, jsperf and etc if they want to add coffee support.

In the good old days, one can simply include the compiled coffeescript bundle with `<script>` tag. 
But that's not how we do things in this new "Great JavaScript Fatigue™" era, where every projects, no matter big or small, should be packed equally with webpack.

Basically that's how this issue arises.

**Comment by akfish** [comment]
That and what @timhuff said.

**Comment by connec** [comment]
Does webpack not support bundling of NPM packages through normal `import`? I don't understand why the following won't work with vanilla CS' [`compile` function](https://github.com/jashkenas/coffeescript/blob/master/src/coffee-script.coffee#L70):

```js
// some file in a webpack bundle
import { compile } from 'coffeescript'

let compiledCode = compile(src, opts)
```

**Comment by akfish** [comment]
@connec Coffee-script's main script contains references to nodejs-only modules. Hence it cannot be packed. The alternative is to set a browser field in package.json pointing to a browser-specific entry script. I'll send a PR later.

**Comment by connec** [comment]
@akfish I see! That makes sense. Perhaps any file-handling logic should be moved into `cli.coffee`, since people directly using the main script (via `require 'coffeescript'`) are also likely to be working with strings.
