### ISSUE TITLE
Splats with other parameters having default value

### ISSUE THREAD

**Issue by Matthijn** [jashkenas/coffeescript#4281]
It seems default values do not always work properly when a splat is involved. 

Let say I have this function: 
    
    foo = (bar..., baz = true) ->
        return bar

It compiles to:
```
  var foo,
    slice = [].slice;

  foo = function() {
    var bar, baz, i;
    bar = 2 <= arguments.length ? slice.call(arguments, 0, i = arguments.length - 1) : (i = 0, []), baz = arguments[i++];
    if (baz == null) {
      baz = true;
    }
    return bar;
  };
```
Now when not passing the `baz` parameter it does not increase arguments.length to the `2` the system expects. Even though there is a value there (it is only set after the slicing). 

If I call this function with: `foo("test")` the output is an empty array: `[]`
If I call it with `foo("test", true)` (which has the same second value as the default) the output is correct, namely: `["test"]`.

A possible solution might be pushing the default value check to the top and add it to the arguments

```
  var foo,
    slice = [].slice;

  foo = function() {
    var bar, baz, i;

    if (baz == null) {
      baz = true;
      arguments.push(baz);
    }

    bar = 2 <= arguments.length ? slice.call(arguments, 0, i = arguments.length - 1) : (i = 0, []), baz = arguments[i++];
    return bar;
  };
```

**Comment by lydell** [comment]
Splats have the lowest priority by design. All other parameters are filled up first, then rest (if any) end up in the splat. This has nothing to do with parameter defaults.

> If I call this function with: `foo("test")` the output is an empty array: `[]`

That’s expected.

> `arguments.push(baz);`

`arguments.push` does not exist.

**Comment by carlsmith** [comment]
Just out of interest, why does `arguments.push` not exist? I thought `arguments` was a normal array in CoffeeScript, specifically so you could do stuff like that directly to it.

**Comment by lydell** [comment]
> I thought arguments was a normal array in CoffeeScript, specifically so you could do stuff like that directly to it.

It’s not. `arguments` in CoffeeScript is the same `arguments` as in JavaScript. You might be thinking of the common/recommended way to _avoid_ the `arguments` object in CoffeeScript by using `(args...) ->` (ES2015: `(...args) => {}`).
