### ISSUE TITLE
Lexer: SyntaxError: unexpected nonexistent `(`

### ISSUE THREAD

**Issue by 1j01** [jashkenas/coffeescript#4283]
When missing a comma in an object literal, you get `SyntaxError: unexpected (` even though there's no parentheses.

``` coffee
console.log {search, users, contacts users_to_display}
```

From what I know of how CoffeeScript works, it's inserting a parenthesis for a function call to `contacts` making for the terrible error message.
(So I ended up looking for an extra parenthesis [somewhere in some file](https://github.com/jashkenas/coffeescript/issues/2368).)

This is fixed in redux. Is there a path for fixing problems like this that come from the rewriter?

**Comment by lydell** [comment]
```
$ node -p 'require("coffee-script").tokens("{f a}")'
[ [ '{',
    '{',
    { first_line: 0, first_column: 0, last_line: 0, last_column: 0 } ],
  [ 'IDENTIFIER',
    'f',
    { first_line: 0, first_column: 1, last_line: 0, last_column: 1 },
    variable: true,
    spaced: true ],
  [ 'CALL_START',
    '(',
    { first_line: 0, first_column: 1, last_line: 0, last_column: 1 },
    generated: true ],
  [ 'IDENTIFIER',
    'a',
    { first_line: 0, first_column: 3, last_line: 0, last_column: 3 },
    variable: true ],
  [ 'CALL_END',
    ')',
    { first_line: 0, first_column: 3, last_line: 0, last_column: 3 },
    generated: true,
    origin: [ '', 'end of input', [Object] ] ],
  [ '}',
    '}',
    { first_line: 0, first_column: 4, last_line: 0, last_column: 4 } ],
  [ 'TERMINATOR',
    '\n',
    { first_line: 0, first_column: 5, last_line: 0, last_column: 5 } ] ]
```

The `generate: true` bit tells us that the `(` has been generated by CoffeeScript, by the rewriter.

My guess is that the token comes from [here](https://github.com/jashkenas/coffeescript/blob/ec333a061b45a6d5980303acda08935db64b7e95/src/rewriter.coffee#L163). Passing the `origin` parameter to the `generate` function on that line (just like it is done a few lines further down) might be the solution.

**Comment by anodynos** [comment]
This code `console.log {search, users, contacts users_to_display}` isnt valid - what would it transpile to `console.log({search: search, users: users, ?????});` ?

**Comment by 1j01** [comment]
@anodynos Yes, the code has a syntax error. The issue is with the error message.
The correct code would be `console.log {search, users, contacts, users_to_display}` (a very useful pattern when logging things)

**Comment by vendethiel** [comment]
@lydell yes, that seems to be the solution

**Comment by YoYoYonnY** [comment]
@1j01 The error message actually comes from CoffeeScript right, not the compiled JavaScript? (For anyone not able to test it themselves, if this issue is still not fixed)

**Comment by 1j01** [comment]
@YoYoYonnY Yes, it's from CoffeeScript.
```
C:\Users\Isaiah>coffee -v
CoffeeScript version 1.11.1

C:\Users\Isaiah>coffee -e "console.log {search, users, contacts users_to_display}"
[stdin]:1:36: error: unexpected (
console.log {search, users, contacts users_to_display}
                                   ^
```
