### ISSUE TITLE
Wrapping function arguments gives an extra object literal

### ISSUE THREAD

**Issue by CyborgMaster** [jashkenas/coffeescript#4287]
Right now 

``` coffeescript
foo(a: 1, b: 2,
  c: 3)
```
compiles to 
``` javascript
foo({
  a: 1,
  b: 2
}, {
  c: 3
});
```

[live example](http://coffeescript.org/#try:foo(a%3A%201%2C%20b%3A%202%2C%0A%20%20c%3A%203))

shouldn't it compile to
``` javascript
foo({
  a: 1,
  b: 2,
  c: 3
});
```
?

I can get the desired output by compiling
``` coffeescript
foo(a: 1, b: 2, 
c: 3)
```
but isn't it standard to indent further arguments when wrapping a function call?

This doesn't even work and gives a compilation error
``` coffeescript
foo({a: 1, b: 2, 
  c: 3})
```

The only way I can wrap this call is to move to one argument per line
``` coffeescript
foo
  a: 1, 
  b: 2, 
  c: 3
```

Is there a way to wrap a function call using a hash argument onto two lines and still indent properly?

**Comment by CyborgMaster** [comment]
Any thoughts?

**Comment by CyborgMaster** [comment]
I agree completely.  My problem is that even explicit braces don't work.  This gives a compilation error

``` coffeescript
foo({a: 1, b: 2, 
  c: 3})
```

[live example](http://coffeescript.org/#try:foo(%7Ba%3A%201%2C%20b%3A%202%2C%0A%20%20c%3A%203%7D)%20)

**Comment by jashkenas** [comment]
CoffeeScript generally takes its indentation-sensitivity pretty seriously. See other tickets. This bug/feature is what's allowing you to do this:

```coffeescript
foo a: 1, b: 2, c: 
  one: 1
  two: 2
  deep:
    [1, 2, 3]
```

**Comment by CyborgMaster** [comment]
But should the braces allow you to override it?  Why can't I write it this way?

``` coffeescript
foo({a: 1, b: 2, 
  c: 3})
```

**Comment by vendethiel** [comment]
That's still indented. You can use `\` as a continuation. Your code is parsed as

```
foo({a: 1, b: 2, {
  c: 3}})
```

**Comment by CyborgMaster** [comment]
Gotcha, so if you are using named parameters there is only two options in coffeescript.  Either all of them must fit on one line, or they must each be on their own line.

**Comment by vendethiel** [comment]
Right. And `\` allows to cheat as to what a "line" is.
