### ISSUE TITLE
Dead links at coffeescript.org

### ISSUE THREAD

**Issue by andrzejkrecicki** [jashkenas/coffeescript#4295]
I found dead links at coffeescript homepage.
For instance:
_jashkenas' Underscore.coffee, a port of the Underscore.js library of helper functions._
http://coffeescript.org/documentation/docs/underscore.html
http://documentcloud.github.io/underscore/

Above links lead to 404 error page.

I suppose that the following file is responsible for it:
https://github.com/jashkenas/coffeescript/blob/master/index.html

May I ask for guidance on how to proceed with pull requests, forks etc? I would love to contribute by resolving this issue.

**Comment by vendethiel** [comment]
You're *almost* correct! The actual file [is in the `documentation/` folder](https://github.com/jashkenas/coffeescript/blob/master/documentation/index.html.js).

If you want to fix it, just send a PR to that (don't send the rebuilt file. We'll do that on the next release). An example is #4212.

To work locally, you'll want to run [`cake doc:site`](https://github.com/jashkenas/coffeescript/blob/master/Cakefile#L170).
