### ISSUE TITLE
Error when parsing multi-line function call w/o object literal

### ISSUE THREAD

**Issue by toomim** [jashkenas/coffeescript#4297]
Coffeescript cannot parse this function call into `func(3)`:

```coffeescript
# Coffeescript
func
  3
```

Trying to parse this results in: `➤ Error on line 2: unexpected indentation`

However, if we insert an object literal as the first argument, it parses just fine:

```coffeescript
# Coffeescript
func
  1:2
  3

# Javascript
func(
  {1: 2},
  3
);
```

We can even take away the 3. As long as there's an object literal on the first argument line, it can parse:

```coffeescript
# Coffeescript
func
  1:2

# Javascript
func(
  {1: 2}
);
```

Coffeescript should be able to parse multi-line function calls without requiring the first argument to be an object literal.

Note that this is *not* about an ambiguity issue—it's only giving Coffeescript the ability to make meaning of strings that it currently raises parse errors for.

**Comment by vendethiel** [comment]
That's a decision that was made a long time ago.

It also allows us not to pull our hair on cases such as:
```
if f
  3 # parsed as a call with your scheme
```

**Comment by toomim** [comment]
@vendethiel Thanks for responding! But it seems you are thinking of a different issue.

You're pointing out an ambiguity in the grammar. But as I wrote above (in "Note that this is *not* about an ambiguity issue") this issue is *not* about ambiguity in the grammar. Furthermore, the ambiguity you point out is already solved.

Specifically, you're thinking about an ambiguity where a multi-line function call begins with an "if", and the parser must choose whether the next line is the (a) "then" clause for the "if", or the (b) first argument to the function call.

This is an important ambiguity—but it isn't the problem here. The coffeescript parser already knows how to handle this ambiguity—it chooses interpretation (a):
```
# Input
if f
  3:4         # Ambiguity: Is this the (a) "then" clause, or (b) first argument to "f()"?

# Output
if (f) {
  ({3: 4});   # Parser successfully chooses interpretation (a)
}
```

And if we remove the ambiguity, the parser successfully falls back to interpretation (b):
```
# Input
f
  3:4          # No more ambiguity

# Output
f(
  { 3: 4 }     # Now it's a function call, interpretation (b)
);
```

So this ambiguity is already solved. The problem I'm raising is orthogonal. It's not about where to insert the `3:4` into the syntax tree—it's about whether the `3:4` can be just a `3`.

If you still think that this is related to the ambiguity issue, could you please link me to the old discussion?

**Comment by toomim** [comment]
And just to be extra clear, this claim is not true:

```
if f
  3 # parsed as a call with your scheme
```

It's not parsed as a function call in my scheme; it's parsed as an if statement. Just like:

```
if f
  3:4
```

...is parsed as an if statement in the current release of coffeescript.

**Comment by lydell** [comment]
There _is_ an older discussion somewhere – I remember reading it. I spent some time yesterday trying to find it, but couldn't.  I would really like to see if there are any arguments that we're missing, because what @toomim says really makes sense.

**Comment by vendethiel** [comment]
#1549 – disallowed in #2746, as a follow-up of [#2712](https://github.com/jashkenas/coffeescript/pull/2712#issuecomment-14229166). Also see #3595, #4284, #3737, #2617 for the discussion of `if`/braceless object literals.

**Comment by lydell** [comment]
@vendethiel Thanks, that was exactly what I was looking for. I knew you would be able to dig out all the old issues :)

**Comment by connec** [comment]
As a workaround to this, you can use `\` to continue a function call over multiple lines (though it still requires commas):

```coffee
f \
  1,
  2,
  3
```

**Comment by toomim** [comment]
@vendethiel Thank you very much! A very useful collection of links.
