### ISSUE TITLE
Proposal: Deeply nested property-setting

### ISSUE THREAD

**Issue by cchan** [jashkenas/coffeescript#4298]
There's already something to test if a deeply nested property exists:

```
obj.a?.b?.c?  #checks whether obj.a.b.c exists, absorbing undefineds
```

If you try to set it, it only sets the variable if the parent properties exist, which seems reasonable - these are question-mark operators, after all:

```
obj.a?.b?.c = 4  # only sets c if obj.a?.b?
```

What if you want to set `obj.a.b.c` whether the parent properties exist or not? It would work kind of like `mkdir -p`. Perhaps the following syntax, with exclamation marks instead:

```
obj.a!.b!.c = 4  # sets obj.a.b.c, creating empty objects for a and b if they do not exist (and throwing if a or b are set to primitives)
```

Thoughts?

**Comment by Inve1951** [comment]
> `obj.a!.b!.c = 4`

i don't see any benefit in this

**Comment by edemaine** [comment]
Definitely concise!  The alternative would be

    obj.a = {} unless obj.a?
    obj.a.b = {} unless obj.b?
    obj.a.b.c = 4

**Comment by GeoffreyBooth** [comment]
Closing due to lack of interest.

**Comment by 1j01** [comment]
The example could be written:
```coffee
obj.a ?= {}
obj.a.b ?= {}
obj.a.b.c = 4
```
or even (if you really want a one-liner):
```coffee
((obj.a ?= {}).b ?= {}).c = 4
```

I don't think the new syntax would be worth it, especially since it would only work with plain objects.
