### ISSUE TITLE
Plans for next release version?

### ISSUE THREAD

**Issue by distracteddev** [jashkenas/coffeescript#4299]
Seems like quite a few patches/features have landed in master since 1.10. Just curious when/if we're planning on publishing a new version to npm?

**Comment by JimPanic** [comment]
Since https://github.com/jashkenas/coffeescript/pull/4300 has been merged yesterday, a new release is probably on the way in the next days or weeks, I suppose!

**Comment by lydell** [comment]
CoffeeScript 1.11.0 has now been released.
