### ISSUE TITLE
Can't use ES6 tagged template literals embedded in Coffeescript

### ISSUE THREAD

**Issue by greghuc** [jashkenas/coffeescript#4301]
Use of ES6 tagged template literals is currently broken in Coffeescript, unless I'm missing a trick.

Since tagged template literals are not directly supported in Coffeescript, the obvious way of using them is to embed the Javascript directly, like:

``` coffee
`
 var a = 5;
 var b = 10;

 function tag(strings, ...values) {
   return "Bazinga!";
 };

 tag`Hello ${ a + b } world ${ a * b }`;
`
```

However, testing this code on http://js2.coffee, I'm seeing 'unexpected identifier' error on the final "tag" line.

I'm assuming the root cause is that backticks are already used by Coffeescript to mark the start and end of the embedded Javascript section. As such, backticks can't also be used inside the embedded Javascript to make the tagged template literal call.

FYI, I ran into this problem when exploring the newish [bel](https://github.com/shama/bel) DOM templating library. Since it uses tagged template strings, I believe it's inoperable with current Coffeescript. This is the first time I've seen incompatibility between Coffeescript and Javascript..

**Comment by greghuc** [comment]
Some related discussion from a bug opened in July 2011: https://github.com/jashkenas/coffeescript/issues/1504

**Comment by GeoffreyBooth** [comment]
Added by #4352
