### ISSUE TITLE
implement ruby style symbols

### ISSUE THREAD

**Issue by yairper** [jashkenas/coffeescript#4310]
using es6's Symbol we can have:
`:some_symbol` -> complies into -> `Symbol.for('some_symbol')`

WDYT?

**Comment by vendethiel** [comment]
Since @jashkenas said we aren't going to support Symbol stuff, I'll close this one.

( https://github.com/jashkenas/coffeescript/pull/4003#issuecomment-129554995 )

**Comment by yairper** [comment]
maybe we could add an helper function like `sym` or `to_sym` or `as_sym` to `String.prototype`?

**Comment by yairper** [comment]
what about
`'hey'.to_sym` to become `Symbol.for('hey')`
it could be more readable in some cases

**Comment by vendethiel** [comment]
CoffeeScript doesn't add helpers, especially not ones extending the builtins :).
