### ISSUE TITLE
Class bodies shouldn't reference arguments in 1.11.0

### ISSUE THREAD

**Issue by monstersintokyo** [jashkenas/coffeescript#4320]
Define a class that defines an _arguments_ object on the class prototype:

```coffeescript
class Test
    arguments: null
```

Since CS 1.11 this is throwing: _Class bodies shouldn't reference arguments_

While it might be a questionable decision to name a variable like a keyword, the above example should still compile.

**Comment by vendethiel** [comment]
Interesting. I'm surprised at the "CS 1.11", because [that warning has been added in 1.7.0](1df8abf1cb55d1fba8e7d74df225945758124933), though...

**Comment by lydell** [comment]
I probably broke it in #4198.

**Comment by lydell** [comment]
Workarounds:

```coffee
class Test
    "#{}arguments": null
```

```coffee
class Test
    @prototype.arguments = null'
```

**Comment by monstersintokyo** [comment]
That was fast - thank you both!
