### ISSUE TITLE
Shorthand broken (x[index] or =[]).push(item) in 1.11.0

### ISSUE THREAD

**Issue by jjog1** [jashkenas/coffeescript#4321]
In 1.11.0 the follow shorthand has been broken.

`(result[groupByIndex] or =[]).push(item)`

Previously this would have compiled to

`(result[groupByIndex] || (result[groupByIndex] = [])).push(item);`

Now it throws a compilation error. Its not a major issue and a quick fix on our side but I wanted to bring it up to make sure you were aware of it.

**Comment by vendethiel** [comment]
You mean spacing `or =` instead of writing `or=`?

**Comment by jjog1** [comment]
Just `or =[]` it worked previously, now its throwing `ParseError: unexpected =`

**Comment by vendethiel** [comment]
Seems like that was changed on purpose in #4221 (you just need to globally find-and-replace "or =" with "or=" and your code will work again).

@lydell That might want to be documented

**Comment by jjog1** [comment]
@vendethiel you're right. Thats fixed it thank you! 👍

**Comment by vendethiel** [comment]
Reopening until added to the changelog :)
