### ISSUE TITLE
1.11.0 - dynamic object keys bug

### ISSUE THREAD

**Issue by charlierudolph** [jashkenas/coffeescript#4324]
See example here:

http://coffeescript.org/#try:field%20%3D%20%22sqftForLease%22%0Astate%20%3D%20%22California%22%0A%0Ax%20%3D%20%7B%22%23%7Bfield%7D%22%3A%20%7B%24ne%3A%200%7D%2C%20state%7D%0A%0Ay%20%3D%20%7Bstate%7D%0A

For x, it should still be `obj.state = state` instead of `obj[state] = state`

**Comment by charlierudolph** [comment]
Thanks! Any idea when a new version will be released?

**Comment by lydell** [comment]
Hopefully we'll release 1.11.1 this weekend with all the bug/regression fixes we've done since 1.11.0.

**Comment by lydell** [comment]
1.11.1 is now released.

**Comment by charlierudolph** [comment]
Thanks!
