### ISSUE TITLE
Could CSON style be maybe shorter?

### ISSUE THREAD

**Issue by lazytyper** [jashkenas/coffeescript#4325]
`[1 2 3]` results in an error:

```
coffee> [ 1 2 3 ]
[stdin]:1:5: error: unexpected number
[ 1 2 3 ]
    ^
```

But couldn't it be compiled same as `[1, 2, 3]` ?

**Comment by vendethiel** [comment]
It *could* (coco and livescript do that). However I'm not sure you're not using the actual CSON instead of the repo.

Anyway, this kind of features is "you think it's cute now". And a few years down the line you realize people write stuff like `a 15 b+0 c`. "Say no to literal overloading"
