### ISSUE TITLE
Coffeescript 1.11 fails to build...

### ISSUE THREAD

**Issue by smblott-github** [jashkenas/coffeescript#4326]
Coffeescript build fails on [this line](https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L32).

Coffeescript 1.10.0 works fine.

Any ideas?

**Comment by vendethiel** [comment]
From the 1.11 Changelog:

> &&=, ||=, and= and  or= no longer accidentally allow a space before the equals sign.

**Comment by smblott-github** [comment]
Thank you.

**Comment by lydell** [comment]
@smblott-github After changing that one occurrence of `|| =` to `||=`, `cake build` finished successfully for me.
