### ISSUE TITLE
memory leak from `results` array in `loop` blocks  

### ISSUE THREAD

**Issue by kenOfYugen** [jashkenas/coffeescript#4328]
When using [js-csp](https://github.com/ubolonton/js-csp) or other generator based libraries, a very common pattern is wrapping logic in `while(true)` blocks for running processes.

For example:

```javascript
function listen(el, type) {
  var ch = chan();
  el.addEventListener(type, function(e) {
    csp.putAsync(ch, e);
  });
  return ch;
}

go(function*() {
  var el = document.querySelector('#ui1');
  var ch = listen(el, 'mousemove');
  while(true) {
    var e = yield take(ch);
    el.innerHTML = ((e.layerX || e.clientX) + ', ' +
                    (e.layerY || e.clientY));
  }
});
```
You can see it run [here](http://jlongster.com/Taming-the-Asynchronous-Beast-with-CSP-in-JavaScript#Taming-User-Interfac).

Currently `coffee-script@1.11.1` does the following transformation:

```coffeescript
go -> loop
  console.log yield dataCh
```
```javascript
go(function*() {
    var results;
    results = [];
    while (true) {
      results.push(console.log((yield dataCh)));
    }
    return results;
  });
```
Won't the `results` array keep growing indefinetely as the process is kept running?
Is there any use for the `results` array in infinite loops? Shouldn't it be there only in the presence of a `break` statement? 

Is there a way to avoid creating the `results` array?

**Comment by GeoffreyBooth** [comment]
By design, CoffeeScript always returns from functions. Hence the `results` array, so that there’s something to return.

If you don’t want the implied `results` array, just add an empty return statement:
```coffee
go -> loop
  console.log yield dataCh
  return
```

This becomes:
```js
go(function*() {
  while (true) {
    console.log((yield dataCh));
    return;
  }
});
```

**Comment by kenOfYugen** [comment]
@GeoffreyBooth using the `return` statement is the  way I tried to fix this. Unfortunately the `return` statement breaks the process and it executes just once, just as if the `loop` keyword doesn't exist. This destroys the whole concept of having a localized 'event-loop' that handles asynchronous code as if it was synchronous.

**Comment by kenOfYugen** [comment]
Ok, one possible way to do this is always checking for the yielded value and returning a break if it signals the end of the data, even if it never arrives.

```coffeescript
go -> loop
  data = yield dataCh
  return break if data is null
  console.log data
```
```javascript
go(function*() {
    var data;
    while (true) {
      data = (yield dataCh);
      if (data === null) {
        break;
      }
      console.log(data);
    }
  });
```
I am closing this for now.

**Comment by GeoffreyBooth** [comment]
Thanks @kenOfYugen. That doesn’t sound like an ideal solution . . . I guess what would you prefer CoffeeScript did? We’re not getting rid of implicit returns, so what else would you suggest?

**Comment by kenOfYugen** [comment]
I wouldn't suggest getting rid of the implicit returns since I happen to love them.
I believe always having to check  a yieldable data source isn't bad. Just a little verbose in some cases, nevertheless it is a good practice.
It's not worth altering the current behavior for such a case. Maybe if another reason appears.

Well, since generators are baked in CoffeeScript in an excellent way, and the language has already moved away from ES3, I'd dare say that 'native' channels would be the ideal solution.
I'll have to further investigate before making such a suggestion/implementation though.
