### ISSUE TITLE
coffee-script.js:8 Uncaught TypeError: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by sahaj2912** [jashkenas/coffeescript#4332]
hi All,

when i run the sample standalone with html page i am don't see any error on browser but when i integrate this with my Primefaces application i get below error 

![coffee-script_1 11](https://cloud.githubusercontent.com/assets/15608727/19088528/254bad7a-8aa9-11e6-8d0a-325aa1fbb2ba.png)

Any idea why i am getting this Error

----.XHTML page is 

<html xmlns="http://www.w3c.org/1999/xhtml"
 xmlns:ui="http://java.sun.com/jsf/facelets"
 xmlns:h="http://java.sun.com/jsf/html"
 xmlns:p="http://primefaces.org/ui"
 xmlns:f="http://java.sun.com/jsf/core">
<h:head>
 <meta charset='utf-8'/> 
   

    <script type="text/javascript" src='resource/js/jquery-2.0.0.js' ></script> 
     <script>
	    var $j = jQuery.noConflict();
	</script>
  <script type="text/javascript" src='resource/js/coffee-script.js' ></script> 
    
  <script type="text/javascript" src='resource/js/jumly.min.js'></script>  
  
</h:head>
<h:body >
 
   
  <script type='text/jumly+sequence'>
  @found "Scenner", ->
    @message "12.5 sec", "GCA"
   
    @message "14.5 sec", "GCA FEC"	
  </script>
                      
</h:body>
</html>

**Comment by GeoffreyBooth** [comment]
CoffeeScript is intended as a build tool, not usually for running in browsers. I would investigate Primefaces.
