### ISSUE TITLE
Many old issues are still open

### ISSUE THREAD

**Issue by YoYoYonnY** [jashkenas/coffeescript#4337]
See #1114 or [the full list of oldest issues](https://github.com/jashkenas/coffeescript/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc)

Many resolved issues are still open. Is this intended, or is there an insentive to close these issues down? I may hope you don't expect us to create an issue for every resolved issue still open (define recursion)? Anyway, here might be a good place to report any open issues that should be closed.

**Comment by lydell** [comment]
#1114 is not resolved. Which of those other open issues are? Closing this until you provide a concrete list of the issues you had in mind.
