### ISSUE TITLE
Question: how to run my script in browser?

### ISSUE THREAD

**Issue by vlad1777d** [jashkenas/coffeescript#4362]
That, what is in <script> tags without src="" works well.
But I need those in tag.
I read somewhere that it's possible. Could someone help me with it?

![2016-11-17 02-51-01](https://cloud.githubusercontent.com/assets/12682937/20371957/b962a818-ac70-11e6-96fc-59c7595a2711.png)
![2016-11-17 02-51-05](https://cloud.githubusercontent.com/assets/12682937/20371958/b9638184-ac70-11e6-913a-23b66b449a69.png)

**Comment by GeoffreyBooth** [comment]
http://coffeescript.org/#scripts
