### ISSUE TITLE
You can put comma after last argument in function call

### ISSUE THREAD

**Issue by malios** [jashkenas/coffeescript#4364]
When you call function with brackets like this
`foo('bar', 'baz', )`

the coffeescript code will actually compile down to this JS code
`foo('bar', 'baz');`

so if the foo function expects 3rd argument it will be with default undefined value.
I  actually made this stupid mistake in my code and it "broke" my app on production :(

**Comment by vendethiel** [comment]
I'm not sure what's the issue here. you want the removal of the consistency comma ?

**Comment by malios** [comment]
Sorry, I don't know what that "consistency comma" is supposed to mean. Does it actually have any use purpose/use case?
I just was expecting this code not to build because of syntax error.

**Comment by malios** [comment]
The application I'm working on sends some emails to the users. So we have this function send
`@send: (title, content, emails) ->`
and when refactoring the code I have deleted (stupid mistake) the third argument in a place where this function is called
`@send(title, html, emails)` ----> `@send(title, html, )`
so this compiled without any errors and later I realized that emails are not being sent, because the emails argument was undefined.
Now I've learned my lesson but I just wanted to open an issue in case this is a bug in the language design itself.

**Comment by vendethiel** [comment]
> Sorry, I don't know what that "consistency comma" is supposed to mean. Does it actually have any purpose/use case?

Yes, it does. It allows for consistency:

```
f(
  1,
  2,
  3, # I can reorder my arguments without any issue
)
```

I'm unconvinced by your example at hand. You could've written `@send(title, html)` and it'd have been an error as well. or `@send(title, html, emalis)`.

**Comment by malios** [comment]
Fair enough, thanks for the explanation!
