### ISSUE TITLE
JS error when omitting destructured Object arguments

### ISSUE THREAD

**Issue by intrr** [jashkenas/coffeescript#4366]
When I have a function:

foo: ({ bar = 1, baz = 2 }) -> ...

And I call this function without any arguments:

foo()

I get a Javascript error when the compiled code tries to initialize the default values of the non-existent object.

Shouldn't it be possible to call such a function without arguments? I would assume that I then simply get all default values for the object and not a crash...

Thanks for considering.

**Comment by intrr** [comment]
Oh and thanks for creating CoffeeScript -- has redefined Javascript programming for me. Wonderful language.

**Comment by GeoffreyBooth** [comment]
> Shouldn’t it be possible to call such a function without arguments? I would assume that I then simply get all default values for the object and not a crash…

But assigned to what?

**Comment by intrr** [comment]
Maybe I have misunderstood the whole mechanism?

I'm using this to emulate named arguments:

foo({ bar: 11, baz: 22 })

This gives me two variables in function scope, bar with value 11 and baz with value 22. Is this undocumented behavior? I find it quite useful. That's why I was surprised when I couldn't just omit the argument entirely (I would then expect bar to be 1 and baz 2).

**Comment by GeoffreyBooth** [comment]
You can’t combine destructuring with function parameter default values. I think what you want is:
```coffee
foo = ({bar, baz} = {bar: 1, baz: 2}) ->
  console.log bar, baz

foo() # 1, 2
foo({bar: 3, baz: 4}) # 3, 4
```

**Comment by connec** [comment]
> You can’t combine destructuring with function parameter default values.

Not quite right. The error in this case is just because there's no default for the destructured object. You can do:

```coffee
foo = ({ bar = 1, baz = 2 } = {}) ->
  console.log bar, baz

foo()              # 1, 2
foo bar: 3, baz: 4 # 3, 4
```

**Comment by intrr** [comment]
@connec: yeah, what you suggested is actually what I'm currently doing as a workaround.

However, I'm not sure why it is necessary? It's not really elegant and IMO this should be considered a bug... I mean, the JS error (can't access property 'bar' of undefined) occurs in automatically generated code after all... why not generate a null check?

**Comment by GeoffreyBooth** [comment]
With CoffeeScript 2, we’re moving toward equivalency with ES2015+ when it comes to function parameters and destructuring. So the workaround will have to do, unfortunately, as ES follows CoffeeScript in this case:
![image](https://cloud.githubusercontent.com/assets/456802/20459560/1c479f0e-ae7b-11e6-9281-33f54a1d6543.png)

**Comment by intrr** [comment]
OK, thanks anyway, I see what you're getting at. Well, CoffeeScript is Open Source. Firing up my IDE... :)
