### ISSUE TITLE
coffee --nodejs '--nodejs-option' fails with fs.createReadStream

### ISSUE THREAD

**Issue by mrft** [jashkenas/coffeescript#4379]
At least that is my problem, maybe other things go wrong too. The actual option that i was trying to use was --max_old_space_size=size but then I found out it also failed with another (valid) option like for example --trace-deprecation. If I compile the script first and then run it using nodejs with the extra options, everything works as expected.

Here is an example script that reproduces the problem:
<pre>
console.log( "loading fs" )
fs = require( 'fs' )

console.log( "fs loaded, creating readstream" )

rs = fs.createReadStream( "2016-11-27.zip" )
console.log( "readstream created" )

unzip = require( 'unzipper' )
zs = rs.pipe( unzip.Parse() )
console.log( "unzipper created" )

zs.on( 'entry', (e) ->
    console.log( e.path )
    e.autodrain()
)
</pre>

when run with `coffee --nodejs '' test2.coffee` successfully logs all messages and then starts echoing all the files in the zip-file.

But when I run the same with `coffee --nodejs '--trace-deprecation' test2.coffee` or `coffee --nodejs '--max_old_space_size=1000' test2.coffee` the process exits at fs.createReadStream:
<pre>
loading fs
fs loaded, creating readstream
</pre>

It actually worked on my OSX laptop, but trying to run the same script remotely on Debian 4.8.4-1 doesn't work, the script just exits.

If it matters: I compiled nodejs myself and have it installed as the local user (both on OSX where it does work and on Debian where it doesn't work) [very similar to what is described here](https://degreesofzero.com/article/how-to-install-nodejs-as-a-non-root-user.html). Nodejs version was 4.x when I first encountered the problem, and didn't understand what was going on, so then I upgraded to 6.9.1, before I'd find out that the nodejs option was what made it fail.

**Comment by GeoffreyBooth** [comment]
The `coffee` command is meant more as a way to convert CoffeeScript to JavaScript, not necessarily as a replacement for the node runtime. We don’t support all of Node’s command-line arguments. Use `coffee` to convert your `.coffee` file into a `.js` file, and run the latter with `node`.
