### ISSUE TITLE
[CS2] Interpolated strings containing backticks are not properly escaped.

### ISSUE THREAD

**Issue by TheBITLINK** [jashkenas/coffeescript#4380]
If a backtick is found inside an interpolated string, it doesn't get escaped, causing syntax errors.

Input:
```coffeescript
console.log("This is a test: `#{process.pid}`")
```
Result:
```javascript
console.log(`This is a test: `${process.pid}``);
```
Expected result:
```javascript
console.log(`This is a test: \`${process.pid}\``);
```

**Comment by connec** [comment]
Nice catch!

**Comment by GeoffreyBooth** [comment]
@greghuc, can you tackle this one?

**Comment by greghuc** [comment]
@GeoffreyBooth I'll fix this, aiming to do by the weekend.

I'm thinking I'll have to do two PRs, one for the `master` and one for the `2` branch. The downsides of maintaining two branches..

**Comment by GeoffreyBooth** [comment]
What about `${` and `}`? If someone types
```coffee
console.log "This is a test: `#{process.pid}` and ${should not be interpolated}"
```
?

**Comment by lydell** [comment]
Also a good catch. That needs to be escaped, too.
