### ISSUE TITLE
High-Rez logo

### ISSUE THREAD

**Issue by jerome724** [jashkenas/coffeescript#4382]
![](http://i.imgur.com/srCMqUS.png)

The High-Rez logo isn't available. 

Link redirects to https://github.com/jashkenas/coffeescript/downloads

**Comment by GeoffreyBooth** [comment]
@jashkenas I guess we need to commit these files into the repo? Maybe under `docs/assets`? That can be where we put files that are common between the v1 and v2 documentation.
