### ISSUE TITLE
extras/coffee-script.js disappeared in v1.12.0

### ISSUE THREAD

**Issue by ukoloff** [jashkenas/coffeescript#4389]
The browser version `extras/coffee-script.js` is not available in repo since v1.12.0.

Is it a bug or a feature?

In the latter case where should one get it now ?

**Comment by GeoffreyBooth** [comment]
http://coffeescript.org/v1/browser-compiler/coffee-script.js

**Comment by ukoloff** [comment]
Okay, thank you!
