### ISSUE TITLE
Cannot read property 'readFileSync' of undefined

### ISSUE THREAD

**Issue by murrayju** [jashkenas/coffeescript#4391]
Everything works fine with CoffeeScript v1.10, but if I drop in v1.11 or newer I get this error in both the browser (using require-cs plugin) and in my r.js (requirejs) build.

> Cannot read property 'readFileSync' of undefined

If I debug this in the browser (sorry for the minified code):
```
f._compileFile = function(c, d, f) {
    var g, k;
    null == d && (d = !1);
    null == f && (f = !1);
    k = v.readFileSync(c, "utf8");
```
with a breakpoint on the last line above, `v` is `undefined`.

Let me know what else I can provide to help debug this.

**Comment by GeoffreyBooth** [comment]
Please provide your original coffee code. Also, `require('fs')` shouldn't work in a browser.

**Comment by murrayju** [comment]
Ok, I've made a plnkr that reproduces this:
https://embed.plnkr.co/WnoV7Q7MiB7CZ505FdAp/

Run that with the chrome debugger open, and you'll see the `Uncaught TypeError` that happens in `coffee-script.js`. I'm using the "browser-compiler" available at https://raw.githubusercontent.com/jashkenas/coffeescript/master/docs/v1/browser-compiler/coffee-script.js

I did a bit of digging, and it seems that this is only a problem when there is an Error stack trace that contains a reference to a .coffee file.

**Comment by GeoffreyBooth** [comment]
`Error.stack` is nonstandard: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack. I don’t know why you would be using it in production code.

**Comment by murrayju** [comment]
It is not my code, it is actually in kriskowal/q. They are doing some feature detection to see if the browser supports stacks, and it is [this detection code](https://github.com/kriskowal/q/blob/7e4c79a5715b3981b2d4339381a0a3faa01f3b21/q.js#L86) that invokes `e.stack` which in turn invokes your code, which throws an exception.

Anyways, I think this is a moot point. There is a code path in your "browser-compiler" build that will try to invoke `require('fs')`, which is obviously a bug.

In the meantime, I can probably fork q as a workaround.

**Comment by GeoffreyBooth** [comment]
`parser.js`, which is generated by `jison`, has the following at its end:

```js
if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
```

Which is clearly supposed to only run in a CommonJS environment, but presumably your require.js setup is confusing it. I suggest you shadow `require` within the function that includes CoffeeScript, so that `require` is undefined when this code checks it.

This code isn’t part of CoffeeScript anyway, it’s `jison`, so it’s not in our domain to change.

**Comment by murrayju** [comment]
This is also very similar to #3890. I may try to implement something similar to atom/coffee-cash#1 as a workaround.

Seems reasonable to ask that CoffeeScript's `Error.prepareStackTrace` should not throw exceptions.

**Comment by GeoffreyBooth** [comment]
Please open a ticket against `jison`. That’s the module generating the problematic code.

**Comment by murrayju** [comment]
@GeoffreyBooth I'm not trying to be difficult here, but I find your stance frustrating. The fact that you are using `jison` is an implementation detail. From the user's perspective, CoffeeScript has a bug, and it is up to you guys to fix it.

Let's say that this is fixed in `jison` tomorrow. CoffeeScript would still have this bug at least until the new version of `jison` is pulled in and CoffeeScript is recompiled. The burden is still on you to track this and make sure that it gets fixed.

While I could try to open a ticket against `jison`, this would be difficult for me because I know nothing about `jison`, or how CoffeeScript is using it. It would make much more sense for you to create this ticket, since you have all of this information.

There is also a simple temporary workaround measure that could be implemented in the CoffeeScript source. Just add a try-catch around the function here: [coffee-script.coffee#L352](https://github.com/jashkenas/coffeescript/blob/master/src/coffee-script.coffee#L352). I could make a pull request that does this if you'd like, but I don't want to waste my time if you won't merge it.

**Comment by GeoffreyBooth** [comment]
I would be open to accepting a PR, but I’m not familiar with that part of the codebase. It would need to be approved by @lydell or @jashkenas.

**Comment by murrayju** [comment]
@GeoffreyBooth @lydell @jashkenas see the pull request above. This totally solves this issue for me, but is more of a workaround. You may want to consider fixing the root of the problem (with `jison`?) at some point, but I think this would be fine for now.

**Comment by davibe** [comment]
The "fix" removed an important feature making all stack traces useless in my backend implementations. https://github.com/jashkenas/coffeescript/issues/4418
