### ISSUE TITLE
Shorthand syntax for Underscore’s extend and pick

### ISSUE THREAD

**Issue by danschumann** [jashkenas/coffeescript#4392]
CS should assimilate underscore
----------------------------------------------------------------

To achieve
`_.extend(targetOb, _.pick(sourceOb, 'param1', 'param2'))`,

I propose
`targetOb{param1, param2} = sourceOb` 

--------------------------------------------------------------

To achieve
 `_.pick(sourceOb, 'param1', 'param2')`

I propose
`sourceOb{param1, param2}`

-----------------------------------------------------------------

To achieve
`_.extend(targetOb, sourceOb)`

I propose
`targetOb {}= sourceOb`

---------------------------------------------

The javascript would be transpiled as
-----------------------------------------

extended pick (transfer properties)
`targetOb{param1, param2} = sourceOb`
transpiles to
```
targetOb.param1 = sourceOb.param1;
targetOb.param2 = sourceOb.param2;
```
--------------------

pick
`sourceOb{param1, param2}`
transpiles to
```
{param1: sourceOb.param1, param2: sourceOb.param2}
```

-----------------------

extend
`targetOb {}= sourceOb`
transpiles to
```
for (var key in sourceOb) {
  targetOb[key] = sourceOb[key];
}
```

**Comment by connec** [comment]
I really like the pick ones, I've wished for something like that before and it feels like a reasonable extension of the destructuring syntax. Not as sure about `{}=`, though it's also a very useful operation.

**Comment by jashkenas** [comment]
It's certainly a neat idea that's been proposed before, but your suggested syntax doesn't quite work:

    sourceOb{param1, param2}

    # Already means something.
    sourceOb {param1, param2}

**Comment by vendethiel** [comment]
yeah, extends needs rework. the other syntaxes already exist in coco/livescript and seem to work quite well.

**Comment by danschumann** [comment]
We can ditch extend, it's a little bad.  Can we do pick though?  I hate declaring strings of `param1` and `param2` when I'm talking about object properties.  I could get a lot of use out of a native CS pick method. 

What about `sourceOb.{param1, param2}`?

Both of these currently break the transpiler
`sourceOb{param1, param2}`
`sourceOb.{param1, param2}`

**Comment by jashkenas** [comment]
I don't think so -- it's a little cryptic, not terribly useful, and doesn't extend well to implicit objects.

**Comment by danschumann** [comment]
`{e.pageX, e.pageY}` would be an alternative pick syntax

producing `{pageX: e.pageX, pageY: e.pageY}`
