### ISSUE TITLE
[CS2] async/await doesn't transpile?

### ISSUE THREAD

**Issue by kenOfYugen** [jashkenas/coffeescript#4398]
I was trying out the `2` branch. According to [Progress as of December 2016](https://github.com/coffeescript6/discuss/issues/56), `async/await` is in.

Using the `coffee --nodejs --harmony-async-await script.coffee` command to run code works fine.

Transforming it to JS via `coffee --nodejs --harmony-async-await -c script.coffee`, the resulting code lacks all `async` statements! Am I doing something wrong?

And of course `node@7.2.1` complains with `ReferenceError: await is not defined`.
I saw the #4351 contains an example of transpiled code, is the code written by hand?

**Comment by vendethiel** [comment]
> Transforming it to JS via coffee --nodejs --harmony-async-await -c script.coffee, the resulting code lacks all async statements! Am I doing something wrong?

It's hard to tell without seeing any piece of code (input and output).

Passing `--harmony-async-await` when compiling is unnecessary, however.

> I saw the #4351 contains an example of transpiled code, is the code written by hand?

No, as you did confirm: running the code directly works fine.

**Comment by kenOfYugen** [comment]
It was frustrating because any code, even the `async` tests didn't transpile correctly.
I just wanted confirmation, turns out there was a mistake on my part in the configuration, using two versions of coffee. Thanks, closing this.
