### ISSUE TITLE
coffee-script-source Gem is missing the source sode

### ISSUE THREAD

**Issue by nick-desteffen** [jashkenas/coffeescript#4403]
https://rubygems.org/gems/coffee-script-source/versions/1.12.1

Below is the contents of the file: `lib/coffee_script/coffee-script.js` 

```javascript
/**
 * CoffeeScript Compiler v1.12.1
 * http://coffeescript.org
 *
 * Copyright 2011, Jeremy Ashkenas
 * Released under the MIT License
 */
undefined
````

**Comment by thiago-negri** [comment]
Lost some time trying to figure out why my CI stopped working with `"CoffeeScript" is not defined".
Forced version `1.11.1` on Gemfile to get it back to work.

**Comment by rafaelfranca** [comment]
To reproduce this error, just goes to the 1.12.1 tag and run `MINIFY=false cake build:browser`

**Comment by vendethiel** [comment]
Paging @josh because I seem to remember he was the one maintaing it.

**Comment by rafaelfranca** [comment]
I'm maintaining it but the problem is actually at Cakefile in this repository. If you do `MINIFY=false cake build:browser` the content generated is only `undefined`.

**Comment by vendethiel** [comment]
Ah! Alright. I understand the issue now.

**Comment by rafaelfranca** [comment]
`cake test:browser` is also broken

**Comment by haberbyte** [comment]
Not sure if this has been taken care of somewhere else, but i think my PR fixes this!
