### ISSUE TITLE
Inconsistent default handling in destructured arrays and arguments

### ISSUE THREAD

**Issue by za-creature** [jashkenas/coffeescript#4408]
Possibly related to #4406

```coffee
# bar, bar
meth = (foo = bar, bar) -> console.log(foo, bar)
meth(null, "bar")


# null, bar; should arguably be bar, bar for consistency
[foo = bar, bar] = [null, "bar"]
console.log(foo, bar)


# foo, foo
meth = (foo, bar = foo) -> console.log(foo, bar)
meth("foo", null)


# foo, foo
[foo, bar = foo] = ["foo", null]
console.log(foo, bar)
```

**Comment by lydell** [comment]
ES2015 for comparison:

```js
// throws: ReferenceError: bar is not defined
let meth = (foo = bar, bar) => console.log(foo, bar)
meth(undefined, "bar")
```

```js
// throws: ReferenceError: bar is not defined
// or, if using var: logs: undefined 'bar'
let [foo = bar, bar] = [undefined, "bar"]
console.log(foo, bar)
```

```js
// logs: foo foo
let meth = (foo, bar = foo) => console.log(foo, bar)
meth("foo", undefined)
```

```
// logs: foo foo
let [foo, bar = foo] = ["foo", undefined]
console.log(foo, bar)
```

**Comment by GeoffreyBooth** [comment]
Is this issue for 1.12.2 or for 2?

**Comment by za-creature** [comment]
1.12, though it _might_ be an issue in 2 as well (I haven't tested)

**Comment by connec** [comment]
I think you could use the case from #4406 (destructured arguments) to show the same issue.

The first example is definitely something else, though, since the params aren't destructured. That may actually be *fixed* in `2` since we're compiling to ES6 defaults.

**Comment by GeoffreyBooth** [comment]
In #4478 your example compiles to (with `null` replaced by `undefined`, because that’s how default values get applied in CS2):

```js
var bar, foo, meth;

meth = function(foo = bar, bar) {
  return console.log(foo, bar);
};

meth(void 0, "bar");

[foo = bar, bar] = [void 0, "bar"];

console.log(foo, bar);

meth = function(foo, bar = foo) {
  return console.log(foo, bar);
};

meth("foo", void 0);

[foo, bar = foo] = ["foo", void 0];

console.log(foo, bar);
```
Running it generates the same output as @lydell’s ES2015 example (first two are `bar is not defined` errors, latter two are `foo foo`).

I would consider this to be fixed in CS2 via #4478. I don’t plan on many (if any) more bug fixes for CS1, but pull requests are welcome 😄

**Comment by za-creature** [comment]
So, is reference error to be expected? Asking because I expect I'll need to update my linter soon enough

**Comment by GeoffreyBooth** [comment]
Yes, in the first two when you have `foo = bar` `bar` isn't defined yet, so it's a reference error.
