### ISSUE TITLE
Cannot use @variable as index in for ... in

### ISSUE THREAD

**Issue by intrr** [jashkenas/coffeescript#4411]
`for char, @srcPos in @src`

gives

> index cannot be a pattern matching expression

(background: I would like to be able to access the index variable in other functions in the same object...)

**Comment by jashkenas** [comment]
It doesn't make useful sense to set an instance variable to the value of the index for every loop ...

But that said, should we allow this to compile anyway?

**Comment by vendethiel** [comment]
Not sure, but `for (this.x of [1, 2, 3]) console.log(this.x)` works in JS.

**Comment by jashkenas** [comment]
Right -- It works and we can make it compile. It's just never a good idea, right? You'd never want to write that?

**Comment by vendethiel** [comment]
That I agree with.

**Comment by intrr** [comment]
Maybe to shed some light on all this. The code structure is more or less like this:

`@Tea =

  compile: (@src) ->

    for char, @pos in @src
      doSomethingWith(@nextChar())
      ...

  nextChar: -> @src[@pos+1]

`

I generally don't use Classes, I just put my functions and "global" variables into Objects ('@Tea'), so I use them more or less as a namespace. In this particular project (a transpiler), there's the function 'compile' that iterates through the source (@src), and I'd like the current position to be available to all functions in the '@Tea' object. Of course, I could just use a "normal" index variable and then set '@pos = index' on each iteration, I just thought that it's more elegant how I intended to do it, and I assumed it to work... if anything, the error message sounds slightly misleading...

Apart from all that, MAD RESPECT for developing CoffeeScript to you all! I'm just now beginning to notice how hard it is to write even a parser for code that uses indentation instead of braces...

**Comment by jashkenas** [comment]
Ah, that is a great use case! Nice.

That makes this officially a bug. Let's fix it.

**Comment by intrr** [comment]
Haha, thanks. I'm always afraid that the way I do things is too extraterrestrial, but seems like it's OK this time :). Thanks for the consideration.
