### ISSUE TITLE
"set"/"use statement to make setting lots of properties easier

### ISSUE THREAD

**Issue by Swissnetizen** [jashkenas/coffeescript#4414]
Currently when we are setting lots of properties it can get quite tedious (unless they are bound to `this`):
````coffeescript
emitter.makeParticles particles
emitter.setXSpeed speed, -speed
emitter.setYSpeed speed, -speed
emitter.minParticleScale =  150 /1000
emitter.maxParticleScale = 250 /1000
emitter.minRotation = 0
emitter.maxRotation = 100
emitter.width = 10
emitter.height = 10
emitter.gravity = 0
````
I propose the following shorthand, the `set` statement
````coffeescript
set emmitter
  minParticleScale =  150 /1000
  maxParticleScale = 250 /1000
 [...]
````
The only issue here is that function calls (`makeParticles`, `setXSpeed`, `setYSpeed`) can't be used, so I propose an alternative: the `use` statement
````coffeescript
use emmitter
  makeParticles particles
  setXSpeed speed, -speed
  setYSpeed speed, -speed
  minParticleScale =  150 /1000
  [...]
````
While I understand that the following solution exists:
````coffeescript
e = emmitter
e.minParticleScale =  150 /1000
[...]
````
I think it simply isn't as readable than the `use` or `set` statement. I only want one statement to be introduced (ideally the `use` statement).

Example JS for `use` (based on example):
````Javascript
emmitter.makeParticles particles
emmitter.setXSpeed speed, -speed
emitter.setYSpeed speed, -speed
emitter.minParticleScale =  150 /1000
[...]
````
This statement is similar to [VB's `with` statement](https://msdn.microsoft.com/en-us/library/wc500chb.aspx) but does not include nesting (maybe we should include nesting?).

**Comment by jashkenas** [comment]
Use a function!

```coffeescript
set emmiter,
  minParticleScale: 150 / 1000
  maxParticleScale: 250 /1000
  minRotation: 0
  maxRotation: 100
  width: 10
  height: 10
  gravity: 0
```

**Comment by Swissnetizen** [comment]
While I understand that is another option, according to [a JSPerf I created](https://jsperf.co/direct-assignment-vs-set-function), 
![image](https://cloud.githubusercontent.com/assets/2052887/21553125/d1f5856e-ce06-11e6-806e-18c64f72d7ff.png)
the `set` function is about 60% slower than a `set` statement (which would compile into direct assignment).

I think that adding a `use` statement has the most merit because it also supports functions and it would be about 150% faster than a `use` function.

**Comment by TheNerdyDev** [comment]
I think that a `use` statement will be more useful because it is broader and we should probably just call it `with` since that's basically what it is, and it's the CS replacement for JS's bad `with` like with the `switch` statement.

**Comment by Swissnetizen** [comment]
@TheNerdyDev The reason I didn't originally call it a `with` statement was to avoid any negative clout that `with` has in JS, but I agree, `with` would make a lot more sense and is a good analogue with the `switch` statement.

**Comment by vendethiel** [comment]
```coffee
use = (o, fn) -> fn.call o

use emitter, ->
  @setXSpeed 50
  @setYSpeed 50
```

**Comment by Swissnetizen** [comment]
@vendethiel That's a good suggestion, but what if I want do say:
````coffeescript
class Body
  constructor: () ->
    @test = 1
    @emitter = {}
    that = @
    use @emitter, ->
      # Doesn't work
      @range = @test
      # Does work
      @range = that.test
````
I have to use `that`, which is a minor inconvenience, but it works, and there isn't much of a [speed penalty on most browsers](https://jsperf.co/use-vs-direct). I still think that `with` makes sense, after all `switch` could easily be a function too (I realise the bottom example isn't a full implementation, but it's an example)
````coffeescript
switch = (value, conditions) -> conditions[value]()
````
But I'm not going to push this any more.
