### ISSUE TITLE
CoffeeScript compiler as a CommonJS module

### ISSUE THREAD

**Issue by fatcerberus** [jashkenas/coffeescript#4419]
Using the "core compiler" here:
http://coffeescript.org/v1/browser-compiler/coffee-script.js

`require('coffee-script')` currently doesn't work - it returns `undefined`.  This prevents me from integrating CoffeeScript support into my Cell compiler without pre-loading the script and polluting the global object as a result.  Any chance this could be changed to allow the compiler to be loaded as a CommonJS module?

**Comment by GeoffreyBooth** [comment]
Have you tried `require('coffee-script/register')`?

**Comment by fatcerberus** [comment]
I'm not trying to use it in Node.js but in my own CommonJS environment which doesn't have the same bindings and built-in modules.  I want to use the compiler API directly (`CoffeeScript.compile()`), not register it as a `require()` handler.

**Comment by GeoffreyBooth** [comment]
The only supported environments are Node via `require('coffee-script/register')` and the browser via the browser compiler. There are no plans to support CommonJS in a non-Node environment at this time.

The browser compiler only creates a global `CoffeeScript` object, if I’m not mistaken; is this really a problem?

**Comment by fatcerberus** [comment]
Mostly I'm just concerned about encapsulation.  My use case: The SCons-like compiler for my game engine has a `transpile` module that supports both CoffeeScript and TypeScript; to avoid an external dependency on specific versions of CoffeeScript I'd like to have the transpile module load the bundled CS compiler as a module.  This way if a third-party module wants to use CS as well, there are no conflicts even if it's a different version.

**Comment by GeoffreyBooth** [comment]
The code that wraps the browser compiler is in `Cakefile`:

```coffee
  code = """
    (function(root) {
      var CoffeeScript = function() {
        function require(path){ return require[path]; }
        #{code}
        return require['./coffee-script'];
      }();

      if (typeof define === 'function' && define.amd) {
        define(function() { return CoffeeScript; });
      } else {
        root.CoffeeScript = CoffeeScript;
      }
    }(this));
  """
```

So if a global `define` function exists and has an `amd` property, the browser compiler calls `define` with a function that returns the `CoffeeScript` object. You could create a global `define` function that takes a function as input, and executes the function and assigns its return value to wherever you were trying to save the `CoffeeScript` object. Pseudocode:

```js
// Assumes your global root object is `window`
// Assumes global `App` object; replace with wherever you want to save `CoffeeScript`
window.define = function(getCoffeeScript) {
  App['CoffeeScript1.12.1'] = getCoffeeScript();
}
window.define.amd = true;
require('browser-compiler'); // Or however you are getting the browser compiler in via CommonJS
delete window.define; // If you want to keep your globals tidy
```

**Comment by fatcerberus** [comment]
It's a bit roundabout but that should get the job done.  Thanks :)
