### ISSUE TITLE
Lexer: Plusplus operator (++) on braced expression leads to parse error. 

### ISSUE THREAD

**Issue by cueedee** [jashkenas/coffeescript#4422]
Please, consider:

```coffeescript
++(foo)
```

While perfectly valid as JavaScript, as CoffeeScript it leads to an "Error on line 1: unexpected end of input".  Should that happen?

Otoh, `+(foo)` is fine, as is `++foo`.

Tried for CoffeeScript `v1.12.1`.

**Comment by vendethiel** [comment]
Just FMI, what's the use-case for this?

**Comment by cueedee** [comment]
I wanted to `++foo.bar` but I think that expression doesn't immediately and unambiguously convey what exactly is meant to be incremented; `++( foo.bar )` does express that intention.
