### ISSUE TITLE
CS class constructor incompatible with custom elements

### ISSUE THREAD

**Issue by paulpflug** [jashkenas/coffeescript#4423]
In Chrome this will throw and break
```coffee
window.customElements.define "custom-element", class CE extends HTMLElement
  constructor: ->
     super()
     console.log "test"
     return @
```
```Uncaught DOMException: custom element constructors must call super() first and must not return a different object```
if `super()` is omitted the same error is thrown, but `test` shows up in console
when using the [polyfill](https://github.com/WebReflection/document-register-element), this doesn't happen.

I know there is an ES2015 implementation of classes in CS2, but I didn't try it yet as I'm unsure if the ES5 output of bable/buble is any better than that of CS ?

Is there a way I can use `constructor` without using the polyfill and without getting an error?

**Comment by jashkenas** [comment]
On CoffeeScript.org, in Chrome, your example isn't throwing for me, and is registering the custom element correctly.

**Comment by paulpflug** [comment]
sorry, I wasn't 100% specific. The error only throws once the constructor is evaluated - when the custom element is inserted into the DOM.

**Comment by connec** [comment]
You may find that custom elements require a 'real' class (i.e. ES3 inheritance isn't good enough).

Does the same code work when compiled by babel?

**Comment by paulpflug** [comment]
No, it is even worse with babel. 
Without `super()` it refuses to compile and with `super()` it throws:
`Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

I think I will stick with the polyfill+CS for now?

**Comment by connec** [comment]
Yeh, that sounds best.

If you want to be a pioneer you could check out the `2` branch of CoffeeScript, and drop babel. You should find that will work (though only in browsers that support ES2015 `class` natively).
