### ISSUE TITLE
Try Coffeescript weird tab behavior

### ISSUE THREAD

**Issue by MatteoVH** [jashkenas/coffeescript#4433]
When using the 'TRY COFFEESCRIPT' editor on coffeescript.org pressing the tab key will deposit a tab character (`\t`) and move the cursor to the end of the next line. This can lead to not realizing that a tab character is interspersed with space-indents which will cause unhelpful syntax errors on otherwise valid code:

![image](https://cloud.githubusercontent.com/assets/4573586/22563870/5eac49a2-e950-11e6-8e14-e098ec36ed60.png)

The syntax checker should be able to display an indentation mismatch and the tab key should not have this weird mixed behavior.

**Comment by GeoffreyBooth** [comment]
We’re not planning on further updates to the CoffeeScript 1.x live editor. You can use the coming-soon CoffeeScript 2 live editor here: https://rawgit.com/jashkenas/coffeescript/2/docs/v2/index.html. It uses CodeMirror, like jsfiddle and other similar sites do, so it should have better support for indentation.
