### ISSUE TITLE
Regression in 1.12.3: attempts to compile comments in litterate

### ISSUE THREAD

**Issue by shimaore** [jashkenas/coffeescript#4434]
This only happens when running a litterate CoffeeScript file from the command-line:
```console
$ ./node_modules/.bin/coffee ./config.coffee.md
…/ccnq4-opensips/node_modules/coffee-script/lib/coffee-script/coffee-script.js:54
        throw helpers.updateSyntaxError(err, code, options.filename);
        ^

…/ccnq4-opensips/config.coffee.md:6:30: error: reserved word 'package'
Configuration for the entire package.
                             ^^^^^^^
$ ./node_modules/.bin/coffee -v
CoffeeScript version 1.12.3
```

The error:
- still appears if I use `coffee -l file.coffee.md`
- does not appear in 1.12.2
- does not appear with `cat ./file.coffee.md | ./node_modules/.bin/coffee -l -s`
- does not appear with `coffee -c`

The [source file](https://raw.githubusercontent.com/shimaore/ccnq4-opensips/master/config.coffee.md) used in the example; a minimal case could be:

```coffeescript
    3

something
---------

    a 4
```

**Comment by cha0s** [comment]
Same here, latest version breaks literate completely. :(

Very painful coming back to a dormant project written entirely in literate and trying to chase updates!

**Comment by cha0s** [comment]
bisect indicates commit `3108244c20a015de5be19bf0c39da499d7362968` introduced the regression. I'm investigating further.

**Comment by cha0s** [comment]
Can confirm reverting only changes in `src/coffee-script.coffee` from offending commit (and disregarding broken tests) fixes the regression. This is my first time in this codebase so I'm really just stone-hammering it here. I'm going to try individual hunks from the patch until I can hopefully narrow down the exact change.

**Comment by cha0s** [comment]
Commenting this code:

```
# Based on [michaelficarra/CoffeeScriptRedux](http://goo.gl/ZTx1p)
# NodeJS / V8 have no support for transforming positions in stack traces using
# sourceMap, so we must monkey-patch Error to display CoffeeScript source
# positions.
Error.prepareStackTrace = (err, stack) ->
  getSourceMapping = (filename, line, column) ->
    sourceMap = getSourceMap filename
    answer = sourceMap.sourceLocation [line - 1, column - 1] if sourceMap?
    if answer? then [answer[0] + 1, answer[1] + 1] else null

  frames = for frame in stack
    break if frame.getFunction() is exports.run
    "    at #{formatSourcePosition frame, getSourceMapping}"

  "#{err.toString()}\n#{frames.join '\n'}\n"
```

Fixes the regression. I'm going to see if I can figure out why.

**Comment by cha0s** [comment]
As you can see I filed a pull request for this issue. I haven't written a test yet.

I simply passed in the `literate` flag to the `compile()` invocation in `getSourceMap`.
