### ISSUE TITLE
Lexer: Chaining: Variable scope varies depending on whether its calling function starts with a leading dot

### ISSUE THREAD

**Issue by shanebdavis** [jashkenas/coffeescript#4437]
I have a question about the scoping of "myVar" here:
```coffeescript
# CoffeeScript:
foo myVar = 1
.bar -> myVar = 2

# Generates this Javascript:
var myVar;
foo(myVar = 1).bar(function() {
  var myVar;
  return myVar = 2;
});
```

In the example above, myVar gets scoped in two places, but if we remove the dot (.), it's only scoped in the enclosing scope:

```coffeescript
# CoffeeScript:
foo myVar = 1
bar -> myVar = 2

# Generates this Javascript:
var myVar;
foo(myVar = 1);
bar(function() {
  return myVar = 2;
});
```

My understanding of CoffeeScript scoping is: if the variable is assigned in the enclosing scope lexically-before it is used in a function sub-scope, the sub-scope will use that binding. The first case above breaks this rule. Is this a bug? Or am I not understanding CoffeeScript scoping fully?

**Comment by jashkenas** [comment]
Neat find! That looks like a bug to me. How did you stumble across it?

**Comment by vendethiel** [comment]
Oh, that's a fun one. I guess we're not visiting the nodes in the "right" order for this case.

I'm gonna guess this happens because CS doesn't consider the expression as a whole. And when it looks at the function, it may not have looked at the call, which declares the variable.

Note: the bug **does not** exist when doing `c x=1, ->x=2`

**Comment by shanebdavis** [comment]
I was working with promises and tests. It was something like this:

```coffeescript
returnsAPromise captureMyTestInputs = a: 1, b: 2, c: 3
.then (result) ->
  assert.equal results, captureMyTestInputs
```

**Comment by connec** [comment]
Probably as a result of compiling the `Assign` value before the variable, [here](https://github.com/jashkenas/coffeescript/blob/master/src/nodes.coffee#L1442).

**Comment by vendethiel** [comment]
> I can't see why they couldn't be reversed, but can't test it just now.

Probably not to make `a(-> x = 5).f x = 5` miscompile then?
