### ISSUE TITLE
[CS2] javascript code style preferences

### ISSUE THREAD

**Issue by davibe** [jashkenas/coffeescript#4446]
I usually write coffee in such a way that generated js is friendly to a javascript user. I'd love if the generated javascript was slightly different. Here are my preferences. I would like to get some feedback

1. no wrapping await with parenthesis

```coffeescript
    deletedCount = await db.remove({}, multi: true)
```

becomes

```javascript
    deletedCount = (await db.remove({}, {
      multi: true
    }));
```

but i would prefer

```javascript
    deletedCount = await db.remove({}, {
      multi: true
    });
```

2. I don't like that all variables are declared at the top of the scope. I would prefer each variable to be declared right before the first usage to avoid having stuff like this at the top of a file

```
var SALT_WORK_FACTOR, bcrypt, bearerTokenAdd, bearerTokenRemove, create, datastore, db, findByBearerToken, findByEmail, findById, findByUsername, hashPassword, hat, remove, save, structure, ...
```

3. I would like comments to be kept. Also the ones starting with just `#`. They have a meaning.

4. I would like the source to be [standard](https://github.com/feross/standard). I have noticed sometimes some whitespaces are off. For example between `function` and `()` there should be a space `function ()`

**Comment by vendethiel** [comment]
> Here are my preferences.

I'm not sure what you're trying to achieve. Getting everyone to agree on *your* set of preferences?

> no wrapping await with parenthesis

arguably could be removed, yes.

> I don't like that all variables are declared at the top of the scope.

Adding a lot of complexity to the compiler for something like this sounds like a terrible idea. Case in point:

```coffee
x = for a in [1..2]
  value = 5
```
I'm fairly sure you'd expect `value` to be available outside the `for`.


> I would like comments to be kept. Also the ones starting with just #. They have a meaning.

That's a technical limitation. PR welcome.

> I would like the source to be standard.

Calling something a "standard" doesn't make it a standard.

**Comment by GeoffreyBooth** [comment]
Your request for comments preservation can be achieved by using [Decaf](http://decaffeinate-project.org/).

**Comment by davibe** [comment]
@vendethiel 

> I'm not sure what you're trying to achieve. Getting everyone to agree on your set of preferences?

I clearly stated I just wanted to get some feedback and I thank you for yours.

@GeoffreyBooth :(
