### ISSUE TITLE
Following a splat with a destructured object results in lost value

### ISSUE THREAD

**Issue by iconmaster** [jashkenas/coffeescript#4450]
**Summary:** 
Following a splat with an object for named parameters in a function's parameters results in the last value of the splat being lost.

**STR:**
Try the following code...

```coffeescript
testSplat = (items..., namedParameters = {}) ->
	return items
		
print testSplat("text", "moreText", "stillMoreText")
```

**Expected Results:**
This should log `["text", "moreText","stillMoreText"]`.

**Actual Results:**
In fact it logs `["text", "moreText"]`. The final value of the splat is lost. Supplying a value for `namedParameters` will fix the issue however:

```coffeescript
print testSplat("text", "moreText", "stillMoreText", namedParameters: null)
```

**Comment by connec** [comment]
That's just how CS' splats work. The splat will only soak parameters that won't be consumed by a positional parameter.

It might help to understand this behaviour if you consider that there's nothing special about `namedParameters` - it's just another parameter, and it's given the value of the last argument (`"stillMoreText"` in your first example, and `{namedParameters: null}` in your second).
