### ISSUE TITLE
[CS2] yield  in =>

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [jashkenas/coffeescript#4452]
```coffeescript
func = => yield this // compile error
```

cuz coffee `=>` compile to es5 `=>`
BUT WHY??? WHY????

solution:
====

if body of arrow (=>) function contains `yield` operator, it must compile in classic mode:

```javascript
func = (function(_this) {
  return function* () {
    return (yield _this);
  };
})(this);
```

If NOT contains  `yield` operator, then compile to es5 mode:
```javascript
func = () => return this
```

CUZ
==========
From the viewpoint of the programmer, there is no physical difference between normal functions and arrow functions

```javascript
var func = function () { }
var func2 = () => { }
```

/// HOW TO KNOW ON RUNTIME WHERE ARROW FUNCTION AND WHEHE NORMAL FUNCTION???

P.S. `func.toString()` in arrow functions return different string code, But this is not significant at all, compared to the terrible restrictions that you impose on a programmer,  forbidding to write yield in arrow functions

**Comment by connec** [comment]
This is something I thought about when making that change. We can narrow down the compiler error to the case that there's a `yield` *and* a reference to `arguments` or `super` (both of which depend on running in an arrow function to have correct behaviour).

```coffee
=>
  yield this
# (function (_this) {
#   return function* () {
#     return (yield _this);
#   }
# })(this)

=>
  doSomethingWith arguments
  yield
# [stdin]:3:3: error: yield cannot occur inside bound (fat arrow) functions with arguments or super
#   yield
#   ^^^^^
```

This could still be problematic though, as there are some semantic differences between ES5 arrow functions and regular functions (e.g. arrow functions can't be used as constructors).

**Comment by connec** [comment]
Hrm, looks like I was thinking about implicit closures with `super` -

```coffee
class A
  foo: ->
    result = try
      super()
      yield
```

This throws `yield cannot occur inside bound (fat arrow) functions` even though there appear to be no bound functions. This is because the `try` expression is wrapped in an arrow function to account for the `super`.

**Comment by uMaxmaxmaximus** [comment]
> (e.g. arrow functions can't be used as constructors).

Easy
===

```javascript
func = (function(_this) {
  return function* __func__() {
    if(this instanceof __func__) throw new TypeError("is not a constructor");
    return (yield _this);
  };
})(this);
```

**Comment by uMaxmaxmaximus** [comment]
> ES5 arrow functions and regular functions (e.g. arrow functions can't be used as constructors).
generator functions can't be used as constructors to =)

**Comment by connec** [comment]
Good point. I'm not sure if there are other differences, perhaps, but it does seem like a good candidate for a PR.

**Comment by GeoffreyBooth** [comment]
This is already covered in the breaking changes documentation: http://coffeescript.org/v2/#breaking-changes

If you disagree, submit a PR.

**Comment by uMaxmaxmaximus** [comment]
no, you submit a PR.

**Comment by retorquere** [comment]
A little late to the game, but I used this construct in an existing app. What is my alternative now that his has gone?

**Comment by connec** [comment]
The currently working alternative would be to write the CS1 compilation directly:

```coffee
func = do (_this = this) ->
  -> yield _this
```

---

I agree this isn't ideal and we have the option of being more clever here, choosing the right strategy based on whether the function contains `arguments`, `super`,  and/or `yield`.

**Comment by GeoffreyBooth** [comment]
I would be hesitant to implement a sugar for this, because generator functions and asynchronous functions seem to be areas with a lot of activity in the standards process right now. I wouldn't want us to implement something that then becomes slightly incompatible with what ECMA standardizes.
