### ISSUE TITLE
[CS2] Dynamic class keys exclude executable class scope??? WHY?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [jashkenas/coffeescript#4453]
Problem
===

```coffeescript
class A
  name = 'method'
  "#{name}": ->   # This method will be named 'undefined'
  @::[name] = ->  # This will work; assigns to `A.prototype.method`
```

Solution
===
Just if method name  contains dynamiс expression, just AUTOMATIC compile it as:

```coffeescript
@::[name] = -> 
```

Why not?

**Comment by vendethiel** [comment]
[That's wrong.](http://coffeescript.org/#try:class%20A%0A%20%20name%20%3D%20'method'%0A%20%20%22%23%7Bname%7D%22%3A%20-%3E%20alert%20%22x%22%20%20%23%20This%20method%20will%20be%20named%20'undefined'%0A%0A(new%20A).method())
