### ISSUE TITLE
Dynamic Method Names in Class (dont close this ticket, go talk)

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [jashkenas/coffeescript#4454]
Problem
===

```coffeescript
class A
  name = 'method'
  "#{name}": ->   # This method will be named 'undefined'
  @::[name] = ->  # This will work; assigns to `A.prototype.method`
```

Solution
===
Just if method name  contains dynamiс expression, just AUTOMATIC compile it as:

```coffeescript
@::[name] = -> 
```

Why not?

@vendethiel dont touch this ticket. If you do not understand what is at stake, do not participate in the discussion, but do not interfere with others.

**Comment by vendethiel** [comment]
You are not welcome here. Go away.
