### ISSUE TITLE
vendethiel used Ad_hominem

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [jashkenas/coffeescript#4456]
@vendethiel https://en.wikipedia.org/wiki/Ad_hominem

You prevent us from participating in the development and improvement of the language, because of your personal emotions. This is a logical error. And I do not understand why the community has to suffer because of you. I'll create this ticket exactly when you sleep.

If Hitler finds a bug and reports this, you will not fix this bug, because it was found by Hitler ?????

**Comment by wryk** [comment]
that's so sad ...
![sad](https://cloud.githubusercontent.com/assets/1964408/23659991/4a73f7d4-0348-11e7-8690-d2a14a27a4e9.jpg)

fast godwin point btw

**Comment by uMaxmaxmaximus** [comment]
In general that, that you knew, EXACTLY I offered to translate Coffeescript in es6.

It was I who came up with a way to implement private members of the class in Coffeescript. And it is I who am now entering the team that develops for them the official standard #privates

**Comment by GeoffreyBooth** [comment]
There are enough open issues already in this repo. Please find another forum for discussion.
