### ISSUE TITLE
[CS2] coffeescript-loader

### ISSUE THREAD

**Issue by michael-ciniawsky** [jashkenas/coffeescript#4462]
👋  We currently are a bit clueless how to handle upgrading `coffeescript-loader` to coffescript v2, the 'problem' is the package rename between v1/v2 from `coffee-script` to `coffeescript`since we handle the version via `peerDependencies` atm. But also `coffeescript@latest` seem to point to `v1.12.x` (v1), which would be fine for v1 support in `coffeescript-loader`. Can someone please confirm that at least versions >= 1.12 of the v1 branch will be available under `coffeescript` aswell? Thx in advance :stuck_out_tongue:

**Comment by mrmowgli** [comment]
Same question here.  My understanding is that in npm you can link in
whatever version you want for latest or stable?

The work around I am using currently is to symlink
node_modules/coffeescript@next to node_modules/coffee-script

The coffee-script branch isn't being changed yet to avoid accidental
upgrades. It's also possible to do some magic with local npm repos or
possibly Yarn.

**Comment by michael-ciniawsky** [comment]
@mrmowgli yep, the tricky thing isn't setting e.g `coffee-script` && `coffeescript` in `peerDependencies` but when `require()` them both in the loader => Error

**Comment by jashkenas** [comment]
Pinging @GeoffreyBooth for his plans on this...

**Comment by GeoffreyBooth** [comment]
The plan at the moment is that `coffeescript` will have all versions (going back to 1.8.x or so) through the latest, including future versions of 2.x. Future releases of 2.x will be on `coffeescript`. You can simply consider `coffeescript` to be the new primary NPM module name for CoffeeScript.

`coffee-script` for now will only get the latest 1.x releases. [If we determine that it’s safe for downstream tools](https://github.com/coffeescript6/discuss/issues/71#issuecomment-282810709) to put 2.x on it as well, then it will become a mirror of `coffee-script`. But for now it’s stuck at 1.x, so please change your code to use `coffeescript` instead.

**Comment by michael-ciniawsky** [comment]
@GeoffreyBooth Awesome 👍 just to confirm `coffeesscript` set as `peerDependency` will  definitely not 'exclude' v1 users using >= 1.8.x ? 🙃  Can we use it now or is it in the transition phase?

**Comment by GeoffreyBooth** [comment]
@michael-ciniawsky You can use it now. `coffeescript` should already have all the same old versions as `coffee-script`, except I think it was 1.7.0 which NPM wouldn’t let me publish (I guess because it had already been published and unpublished). If that’s an issue I can reach out to NPM and ask them to override.

Also when I published I went by git tags; if someone happened to `npm publish` a version from a commit different than what was tagged, then the two repos have slightly different versions with the same version number (grr). But I don’t think that happened for any versions, at least not for any 1.12.x versions. Again if it did I hope the NPM maintainers would fix it for us.

**Comment by michael-ciniawsky** [comment]
kk we'll see 😛 should normally be fine. Last question 🙃 , are there any breaking changes in the **Node API** between v1 => v2 ?

**Comment by GeoffreyBooth** [comment]
Aside from requiring `coffeescript` or `coffeescript/register` instead of `coffee-script`, no. See http://coffeescript.org/v2/#breaking-changes

**Comment by GeoffreyBooth** [comment]
But CS2 requires Node 7+; the compiler itself is now in ES2015 (features supported by Node 7 only) so that’s one thing to be aware of.

**Comment by michael-ciniawsky** [comment]
@GeoffreyBooth Alright thx appreciated

**Comment by LosEagle** [comment]
What do I do to use CS2 with coffee-loader? It keeps telling me that I need coffee-script@1.x to fullfill it's peer dependency and won't let me compile anything. I have coffeescript 2.0.0-beta2 in my project.

**Comment by GeoffreyBooth** [comment]
That's a question for coffee-loader. See https://github.com/webpack-contrib/coffee-loader/issues/39
