### ISSUE TITLE
Example code in .litcoffee files

### ISSUE THREAD

**Issue by edgerunner** [jashkenas/coffeescript#4466]
Is there a way in putting example code blocks in .litcoffee files that are part of the annotation rather than the actual code to be executed?

**Comment by GeoffreyBooth** [comment]
Yes: wrap them in HTML tags, like `<p>` or `<pre>`. See https://github.com/jashkenas/coffeescript/blob/2/test/literate.litcoffee, especially the section with the comment “# should not execute, this is just HTML para, not code!”
