### ISSUE TITLE
Make Light version of Coffeescript that compiles to ES6

### ISSUE THREAD

**Issue by aurimus** [jashkenas/coffeescript#4468]
It would be great to use some features of Coffeescript, like `@` for `this`, indentation syntax etc. but it could compile to es6, instead of JS, so making it much lighter.

Also would be great that any es6 would be valid coffeescript, so making it easy to use any features we want.

Thanks for your work @jashkenas

**Comment by vendethiel** [comment]
That's pretty much what CoffeeScript 2.0 is striving to be.

**Comment by aurimus** [comment]
Where can I find the specification? Is it in development?

**Comment by GeoffreyBooth** [comment]
http://coffeescript.org/v2/

**Comment by aurimus** [comment]
So it compiles the current coffeescript syntax to ES6? .. That's pretty much useless. For example, for string interpolation, it should simply use the ES6 syntax, not invent the wheel. Think of it from a perspective of someone who is just now coming to JS world - why would you switch ES6 to a similar language, just different. 

I would use coffeescript3 if it would enhance the ES6 with additional features (with indentation syntax, additional operators from `Math` or even think of a syntax for all the JS features that are on `Object` or `Array`).

Is there such project in works?

**Comment by aurimus** [comment]
Basically, any Javascript should be valid Coffeescript, add whatever you like to that.

**Comment by GeoffreyBooth** [comment]
That wouldn’t be CoffeeScript. You’re welcome to design your own language.

**Comment by aurimus** [comment]
ok, so basically CS2 is to perform better, that's all, right?
