### ISSUE TITLE
[CS2] [Docs] Examples of module loading with external tools

### ISSUE THREAD

**Issue by mrmowgli** [jashkenas/coffeescript#4470]
Currently the V2 docs mentions the need for an external transpiler, however since this will be an issue for novices, perhaps we could put a quick example in?  Or add a default cake task?

**Comment by GeoffreyBooth** [comment]
Yes, we should add an example. I remember suggesting somewhere that the docs should have the most minimal version in the docs, like `coffee file.coffee | babel` or whatever the bash one-liner is, with links to GitHub repos showing examples with Gulp and Webpack and so on.

Adding a cake task for this would mean adding Babel as a dependency, which might ignite a firestorm . . .

**Comment by danielbayley** [comment]
Maybe a recommended list of babel plugins to go after CoffeeScript 2 in the build pipeline, or even some kind of _babel-preset-coffeescript_ would be useful?

**Comment by GeoffreyBooth** [comment]
Closed by #4469
