### ISSUE TITLE
a +'' yields unexpected behavior

### ISSUE THREAD

**Issue by xxv** [jashkenas/coffeescript#4474]
The Coffeescript:

```
a + ''
```
produces the Javascript:

```javascript
a + '';
```
Whereas the Coffeescript:
```
a +''
```
produces:

```javascript
a(+'');
```

which is very surprising. You can see [this sketch](http://coffeescript.org/#try:a%2B%27%27%0A%0Aa%20%2B%27%27%0A%0Aa%20%2B%20%27%27%0A%0Aa%2B%20%27%27
) for all the permutations

Keywords of symbols: plus apostrophe quote whitespace

**Comment by lydell** [comment]
Thanks for the very clear issue!

This is simply one of [common gotchas](https://github.com/jashkenas/coffeescript/wiki/Common-Gotchas#q-why-is-foo-a-different-from-foo--a-) of CoffeeScript.

See also previous issues: #2703 #2469 #2754

**Comment by vendethiel** [comment]
See #1036 / the FAQ, "Grammar", point #2 (it doesn't seem like I can hyperlink to that...).
