### ISSUE TITLE
child_process.fork doesn't work when using node -r coffee-script/register

### ISSUE THREAD

**Issue by wastl-junior** [jashkenas/coffeescript#4476]
When calling the following script stored in file program.coffee
```coffee
cp = require "child_process"
cp.fork "otherFile.coffee"
```
It works properly using "coffee programm.coffee".
But when using "node -r coffee-script/register program.coffee" the child process won't be spawned and the error "TypeError: Cannot set property 'filename' of undefined" is shown on command line.

The error occurs when trying to write the filename to a non existing mainModule at https://github.com/jashkenas/coffeescript/blob/ca0fd229e12d51a6429e6a91a094063bbc00ea56/src/coffee-script.coffee#L165

(using node v6.10.0 on Windows 7)

**Comment by GeoffreyBooth** [comment]
The recommended way to require CoffeeScript files is like:

```coffee
require 'coffeescript/register'

App = require './app' # The .coffee extension is optional
```

See also #3431. Please comment if neither of these solve your issue and I’ll reopen.

**Comment by wastl-junior** [comment]
The problem is, that coffee-script itself is overriding the cp.fork function to use `bin/coffee`:
https://github.com/jashkenas/coffeescript/blob/cd6daf0b79c38af7092e0f7126ac0bf0bfd44919/src/register.coffee#L42

That should then be changed to `node -r coffee-script/register`?
