### ISSUE TITLE
[CS2] Regression in handling default for destructured param

### ISSUE THREAD

**Issue by connec** [jashkenas/coffeescript#4477]
In CS 1.x the following pattern could be used to set a default for a destructured parameter:

```coffee
({ a } = {}) ->
```

This outputs:

```js
(function(arg) {
  var a;
  a = (arg != null ? arg : {}).a;
});
```

In CS 2.0.0-alpha1 the output has changed to:

```js
(function(arg) {
  var a, arg;
  if ({
    a: a
  } === void 0) {
    a = {}.a;
  }
});
```

The undefined check is now happening on the destructuring expression, rather than the argument name.

**Comment by greghuc** [comment]
@connec I just ran into this when migrating a project to CS2.

Test case:

```
test = ({ value } = {}) -> console.log "Value: #{value}"
test value: 42
```

Output:
```
CS1: Value: 42
CS2: Value: undefined
```

**Comment by GeoffreyBooth** [comment]
In #4478, this:
```coffee
test = ({ value } = {}) -> console.log "Value: #{value}"
```
now outputs as this:
```js
var test;

test = function({value} = {}) {
  return console.log(`Value: ${value}`);
};
```
and `test { value: 42 }` prints `Value: 42`.

**Comment by connec** [comment]
Neat! Yeh I ran across this when doing tests for destructuring.

I suspect we will have a similar issue with any non-assignable destructured parameter with a default).

```js
// ([head..., last] = []) ->
var slice = [].slice;

(function(arg) {
  var arg, head, i, last, ref;
  // this should be checking `arg`, not its default value
  if ([...head, last] === void 0) {
    ref = [], head = 2 <= ref.length ? slice.call(ref, 0, i = ref.length - 1) : (i = 0, []), last = ref[i++];
  }
});
```

Additionally, it looks like #4478 has broken expansions in destructured parameters:

```
stdin]:1:3: error: Expansion must be used inside a destructuring assignment or parameter list
([..., last] = []) ->
  ^^^
```
