### ISSUE TITLE
Existential Operator doesn't handle right with Destructuring Assignment

### ISSUE THREAD

**Issue by CallmeNezha** [jashkenas/coffeescript#4486]
When i wrote code like this
```
constructor: (option = undefined) ->
    {initializer} = option?
```
Coffee interpreted it as
```
initializer = (option != null).initializer;
```

But the **right** one should be 
```
initializer = option != null ? (option.initializer != null ? option.initializer : null) 
                             : null;
```
And it make no sense that **Bool** has any property.. So coffee doesn't handle it right.

**Comment by lydell** [comment]
@CallmeNezha You’re looking for one of these:

```coffee
constructor: (option = undefined) ->
    {initializer} = option ? {}

constructor: (option = {}) ->
    {initializer} = option

constructor: ({initializer} = {}) ->
```

- `a?` is for checking if `a` exists – so it turns into a boolean. That’s the unary `?` operator.
- `a ? b` chooses `a` if it exists, other wise `b`. That’s the binary `?` operator.
- `a?.b` tries to access the `b` property on `a` if `a` exists. That’s the binary `?.` operator.

**Comment by CallmeNezha** [comment]
Ok i figure it out. TKS!
