### ISSUE TITLE
import- and export-specific lexing should stop after import/export statement

### ISSUE THREAD

**Issue by helixbass** [jashkenas/coffeescript#4491]
In `lexer.coffee`, `@seenImport` and `@seenExport` only get reset by an explicit `;`. Thus allowing some devious edge cases to fail that should work, eg this works:
```
import * as lib from 'lib';
foo as       # foo(as)
3 * as 4     # 3 * as(4)
from 'foo'   # from('foo')
```
But if you remove the `;`, any of the following lines would break

Will submit what I believe to be a fixing pull request momentarily

**Comment by GeoffreyBooth** [comment]
Thanks! So . . . who are you and what caused you to take a sudden interest in finding and fixing lots of bugs in the lexer? :smile:

**Comment by helixbass** [comment]
@GeoffreyBooth sure, I've been a big fan of CoffeeScript for a while, so much so that I hacked the compiler to output PHP (in [`helixbass/copheescript`](https://github.com/helixbass/copheescript)) so that I could keep using it on the back end. But it's super dirty since I have no real understanding of the implementation, so I've wanted to clean it up and add some missing PHP language features before publicizing it to the CoffeeScript/PHP communities. Just started reading Language Implementation Patterns so I'd like to work my way through the book and codebase in parallel, thanks

**Comment by GeoffreyBooth** [comment]
Ah, I haven’t coded in PHP for awhile but there was a period where I used both CoffeeScript and PHP and wished that there was a similar project that would clean up PHP’s syntax. Thanks for attempting it! There is also a project called Mammouth you should be aware of: http://mammouth.boutglay.com/
