### ISSUE TITLE
[CS2] "core compiler" link has duplicated version in URL

### ISSUE THREAD

**Issue by Kern3l** [jashkenas/coffeescript#4496]
coffeescript/documentation/sections/installation.md

We get:
http://coffeescript.org/v2/v2/browser-compiler/coffeescript.js

Instead of:
http://coffeescript.org/v2/browser-compiler/coffeescript.js

Try yourself: http://coffeescript.org/v2/#installation - "core compiler" link.

Thanks in advance for a fix!

**Comment by GeoffreyBooth** [comment]
Already fixed in #4480
