### ISSUE TITLE
Make more human-readable output code

### ISSUE THREAD

**Issue by novellizator** [jashkenas/coffeescript#4500]
After es6 many people try to switch back to es6 by converting their code frmo coffee script. When the codebase is huge, it's a very hard task to do manually. We also cannot just paste the transpiled coffee script, since it's much much harder to read than the original coffee script. So that got me wondering if you could make the transpiler transpile the code more cleanly (to, say es6) so that it could be used as a source to work on.

**Comment by GeoffreyBooth** [comment]
That’s the purpose of CoffeeScript 2: http://coffeescript.org/v2/
