### ISSUE TITLE
cake tasks "test" and "test:browser" exits 0 even if tests fail

### ISSUE THREAD

**Issue by jonassmedegaard** [jashkenas/coffeescript#4503]
The cake targets "test" and "test:browser" suppress the return value of the tests, and always return 0.

The following change (borrowed from testBuiltCode) properly exits 1 on failure:

before:

runTests CoffeeScript

after:

  testResults = runTests CoffeeScript
  process.exit 1 unless testResults

...and similar for "test:browser" target.

**Comment by GeoffreyBooth** [comment]
Do you care to submit a pull request?

**Comment by jonassmedegaard** [comment]
Quoting Geoffrey Booth (2017-04-15 20:54:47)
> Do you care to submit a pull request?

Sorry, I understand how that would be more helpful, but I am not 
comfortable with the Github terms of service: 
http://joeyh.name/blog/entry/what_I_would_ask_my_lawyers_about_the_new_Github_TOS/

I will therefore constrain myself to contributing bugreports here but no 
actual code.

The patch applied to the Debian packaging of Coffeescript is here: 
https://anonscm.debian.org/cgit/collab-maint/coffeescript.git/tree/debian/patches/fix_test_exitcode.patch


Hope that helps,

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
