### ISSUE TITLE
shorter syntax for effective Array::filter  --  for array when condition

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#4511]
Hello -

Currently possible:

```coffeescript
tmp2.filter (x) -> some-conditional
tmp2 = (t for t in tmp when some-conditional) # not as nice
```

I am proposing:
```coffeescript
tmp2 = (for t in tmp when some-conditional)
```
The only reason (imo) to avoid Array::filter() is to avoid another call (presuming it's not inlined) in a performance-critical area.  I think the `t for t` could be optional here - is it necessary so the parser doesn't have a hard time?

**Comment by vendethiel** [comment]
That only saves 2 characters, one of them being a space. I really don't believe that's worth adding syntax for. Your first example also should be `tmp.filter -> someConditional`, no need for `(x)`.

**Comment by blitmap** [comment]
I made a few typos here.

1) the `(x)` was necessary in the code I pulled this proposal from

2) I meant to propose:

```coffeescript
tmp2 = (for tmp when some-conditional)
```

This can save more than just "2 characters" depending on how long your unnecessary identifier would be.

**Comment by vendethiel** [comment]
> This can save more than just "2 characters" depending on how long your unnecessary identifier would be.

There's no reason to make the identifier any longer, because then `.filter fn` becomes shorter.

**Comment by blitmap** [comment]
```coffeescript
tmp2.filter (x) -> x % 2 is 0
(for tmp2 when x % 2 is 0)
```

I'm trying to make it so the for-when is as short as the filter version - I think the `t for t in ...` should be unnecessary?

**Comment by blitmap** [comment]
Ahh okay, I'm going to concede - bad proposal.

I was trying to make these comparible:

```coffeescript
tmp2.filter (x) -> x % 2 is 0
(for tmp2 when x % 2 is 0)
```

But then I realized I forgot to actually declare the `x` I use in the condition.  This can't work how I wanted.  I'm a bad proposer. :x
