### ISSUE TITLE
[CS2] Splicing output for static ranges could be optimized

### ISSUE THREAD

**Issue by isiahmeadows** [jashkenas/coffeescript#4515]
[Per here](http://coffeescript.org/v2/#slices)

You could optimize and simplify the splicing output in a few different ways to avoid most of the overhead, and leverage ES6 better:

```coffee
# Source
numbers[3..6] = [-3, -4, -5, -6]
numbers[3..6] = list
```

```js
// Output
numbers.splice(3, 4, -3, -4, -5, -6)
numbers.splice(3, 4, ...list)
```

**Comment by GeoffreyBooth** [comment]
I don’t quite understand what you’re getting at with your example, but PRs with improvements are always welcome.
