### ISSUE TITLE
Multiple inheritance? Mixins?

### ISSUE THREAD

**Issue by TrevorBurnham** [jashkenas/coffeescript#452]
I'm loving the `extends` keyword, but in the course of developing a complex project, I really wish I could give a class functionality from multiple sources. Obviously I could do this by extending the prototype manually, but it feels like a hack to mix the `extends` syntax with JavaScript-style prototype manipulation.

For my purposes, it would be great to be able to say

```
class A extends Foo, Bar
```

but I realize that multiple inheritance is a huge headache, so Ruby-style mixins or Scala-style traits would probably be a better solution. The Scala syntax would be especially nice for CoffeeScript:

```
class A extends Foo with Bar
```

Obviously `with` is already a keyword, but its meaning in this syntax is unambiguous.

Of course, this is something that a standard library could do, but it would be much clearer to have something like the above syntax rather than something like

```
class A extends foo
   # properties...

lib.mixin A, bar
```

What does everyone else think?

**Comment by carlsmith** [comment]
Unless you are creating lots of these objects, the benefits of delegation are not great. It saves a little bit of RAM. The use cases for multiple delegation are few if any. Crockford is recommending we never delegate these days, whatever you want to make of that.

If you're willing to copy over the methods of an object and call that inheritance, you can achieve the same thing, arbitrarily passing an object through any number of constructor functions, using simple closures.

I have [a little gist][1] if anyone's interested. The 'library' is 5 lines of code. It was written for students, so it's a bit toyish, but the example of 'super inheritance' is at Line 27.

On the whole, it seems better to wait for proxies to flesh out and revisit. Just my two pennies.

[1]: https://gist.github.com/carlsmith/eed8717d88288f7c2832

**Comment by arximboldi** [comment]
Hi!

Just wanted to bring awareness to a little module I made, which implements multiple inheritance: https://github.com/arximboldi/heterarchy

The interesting thing about this implementation is that, unlike the mixin-based approaches discussed here so far, it supports cooperative multiple inheritance, in a way similar to how Python does it. It has some drawbacks, so I'm unsure it's appropriate for the core language, but it should help pythonistas to import their beloved patterns.

Cheers!
