### ISSUE TITLE
[CS2] `get` as method should not require parentheses

### ISSUE THREAD

**Issue by GeoffreyBooth** [jashkenas/coffeescript#4524]
This should not throw an error:

    location = App.locationCollection.get @model.get('location')
                                      ^^^
    ParseError: 'get' cannot be used as a keyword, or as a function call without parentheses

We should find a way to detect when `get` is used as `.get`, rather than bare `get`; and restrict the error to only the latter.

**Comment by MadcapJake** [comment]
I still get this error if I do something like `@get @someProp`
