### ISSUE TITLE
"Error: unexpected ," in calling method

### ISSUE THREAD

**Issue by vlad1777d** [jashkenas/coffeescript#4542]
When calling methods with passing two or more arguments, if to place space between scope and method name, it causes error.

Example:
-- Code: `history.pushState ({}, "")`
-- Error: `Error on line 1: unexpected ,`

Example without error:
-- Code: `history.pushState({}, "")`

Example without error 2:
-- Code: `top_panel.classList.remove ('top_panel_sticky')`

Version of Coffeescript: 1.12.5

**Comment by lydell** [comment]
Yep, CoffeeScript is a whitespace significant language. You are basically doing this:


```coffee
foo = ({}, "")
history.pushState foo
```

... which is invalid since CoffeeScript has no comma operator.
