### ISSUE TITLE
Array literal of function calls

### ISSUE THREAD

**Issue by lzrski** [jashkenas/coffeescript#4545]
This Coffee source:

```coffeescript
[
  fn1 "arg-to-fn1",
  fn2 "arg-to-fn2"
]
```

get's compiled to this JS:

```javascript
// Generated by CoffeeScript 1.12.5
(function() {
  [
    fn1("arg-to-fn1", fn2("arg-to-fn2")) // <-- single element
  ];
}).call(this);
```

To get this results I would expect that call to `fn2` should be on the same line or indented.

What I would expect is:

```javascript
// Generated by CoffeeScript 1.12.5
(function() {
  [
    fn1("arg-to-fn1"),
    fn2("arg-to-fn2")
  ];
}).call(this);
```

The workaround is not to use comma (which I usually do), to place comma on own line or use comma first style.

I'm surprised I've never noticed it, but apparently it's like that at least since version `1.9.3` up to current `master` and `2.0.0-beta1`. Is this intended?

**Comment by vendethiel** [comment]
It's normal, you use that everywhere without realizing it.
  ```coffee
fn1 "arg-to-fn1",
fn2 "arg-to-fn2"
```

and it's been like that for the longest times:

```
➜  coffeescript git:(master) git checkout 1.0.0
HEAD is now at 33d2577... CoffeeScript 1.0.0
➜  coffeescript git:(33d2577) echo -n "[\n  a b,\n  c d\n]" | ./bin/coffee -scb
[a(b, c(d))];
```

**Comment by lzrski** [comment]
Well, I accept that, but also I would prefer your example to result in syntax error. To get the continuation IMO the following line should be indented. 

The way it is right now it seems error prone. Consider this more real life example:

```coffee
Promise
  .all [
    db.open "db.sqlite",
    request "https://example.com/data"
  ]
  .then ([db, data]) =>
    # db is opened correctly (second argument was ignored)
    # data is undefined - WHY? Oh, comma :P
  .catch (error) =>
    # Sorry, no error here.
```
