### ISSUE TITLE
Referencing 'this' without super call in class constructor

### ISSUE THREAD

**Issue by brunovandamme** [jashkenas/coffeescript#4547]
Compiling the following with v2:
```
class x

class y extends x
	constructor: ->
		@state = {}
```
results in an error:
**Can't reference 'this' before calling super in derived class constructors**

This compiled without problems in coffeescript v1. Is this a bug or a change in policy regarding calling the super constructor?

**Comment by GeoffreyBooth** [comment]
It’s not a change in policy, it’s just how ES2015 classes work. http://coffeescript.org/v2/#breaking-changes

**Comment by mrmowgli** [comment]
This is one of the breaking changes for 2, it unfortunately is a limitation
of ES6, so CoffeeScript lets you know.

If you have a bunch of existing code, you should either refactor or stick
with 1.x for that code.

**Comment by KernelDeimos** [comment]
Why not implicitly add a missing call to `super()` with no parameters when a reference to `this` is detected? As far as I can tell that's exactly what the behaviour used to be.

I know it's a bit late, but if I figured out how to implement this and submitted a PR, would it be considered?

**Comment by GeoffreyBooth** [comment]
If there’s a reason to not do the automatic thing, then we probably shouldn’t do the automatic thing.

**Comment by Inve1951** [comment]
@KernelDeimos 
>As far as I can tell that's exactly what the behaviour used to be.

That's not the case. The super call was entirely optional. Here's a demo: [v1/#try](https://coffeescript.org/v1/#try:class%20B%20extends%20A%0A%09%23%20no%20explicit%20constructor%2C%20arguments%20are%20forwarded%0A%0Aclass%20C%20extends%20A%0A%09constructor%3A%20-%3E%0A%09%09%23%20explicit%20constructor%2C%20no%20super%20call%0A%0Aclass%20D%20extends%20A%0A%09constructor%3A%20-%3E%0A%09%09%40abc()%0A%09%09%23%20same%20as%20C%0A%0Aclass%20E%20extends%20A%0A%09constructor%3A%20-%3E%0A%09%09%40abc()%0A%09%09super%09%09%23%20forwards%20arguments%0A%09%09super()%09%23%20empty%20call)

**Comment by KernelDeimos** [comment]
Oh, that makes sense. So that behaviour is actually impossible to implement the ES6 way, short of deliberately reversing whatever the super call does

**Comment by Inve1951** [comment]
exactly.

**Comment by jayarjo** [comment]
> I sometimes forget about the super call and find the error more convenient than an implicit empty call, as often times the intention is to forward the arguments (but not always of course).

How would one fix something like that? I'm trying to upgrade legacy lib to coffeescript 2 not knowing coffeescript syntax itself.
