### ISSUE TITLE
"in" keyword doesn't work with arrays

### ISSUE THREAD

**Issue by Qwerp-Derp** [jashkenas/coffeescript#4549]
When I do something like this:

```coffee
console.log [0, 1] in [[0, 1], 2, 3, 4]
```

this outputs `false`. I'm not sure if this is intended behaviour or not.

**Comment by GeoffreyBooth** [comment]
It is. In JavaScript, arrays are objects, so you can’t compare them blindly like that:

```js
[0, 1] === [0, 1] // false
```

They’re not the same object, so an equality comparison returns false; even though they “equal” each other in the sense that they have the same values.

`[0, 1] in [[0, 1], 2, 3, 4]` is asking if the object `[0, 1]` appears in the array after the `in`. It does not. _Another object_ with the same value does.
