### ISSUE TITLE
Error thrown when attempting to assign var using ?= or ||= in block-loops

### ISSUE THREAD

**Issue by danielkalen** [jashkenas/coffeescript#4555]
Consider the following code:
```coffeescript
matcher = (items, test)->
  for item in items
    if test(item)
      matchingItems ?= []
      matchingItems.push(item)

  return matchingItems
```

The compiler will throw the following error: `Error on line 4: the variable "matchingItems" can't be assigned with ?= because it has not been declared before`

The intent of this function is to loop through the provided items and return an array of items that pass the provided test function; if none of the items are matched, undefined should be returned.

**Why not just define `matchingItems = []` at the head of the function?**
Although it doesn't seem as much of a problem in this example, sometimes we have similar functions being invoked thousands of times and when using as least memory as possible is a high priority creating such unused objects is unwanted (e.g.!when the matching result
set is empty is a common case).

**Why not just define `matchingItems = null` at the head of the function?**
Because... **we shouldn't have to**. Think about it: what is the reason the compiler needs to check that the variable was previously declared? To save us from unexpected `ReferenceError`s? If that's the case then why doesn't to compiler throw an error for the following code?:
```coffeescript
matcher = (items, test)->
  for item in items
    if test(item)
      matchingItems = [] if not matchingItems
      matchingItems.push(item)

  return matchingItems
```

Both code samples will produce the same results when compiled, whether `matchingItems` is defined or not (i.e. if not, a reference error will be thrown in both cases) so why does the compiler only complain about the first example? Why don't I have to define `matchingItems = null` at the head of the second example? If the reasoning behind it is to protect the user from unexpected reference errors then that reasoning should be applied to the second code sample as well as any other type of check on a non-declared variable (_regardless of whether it is in a loop or not!_).

If the reasoning is for user protection then no thanks, I don't think we need this protection as I can name many scenarios in which such code would be intentional. And yes I know that in the second example the compiler declares the `matchingItems` variable at the top when it encounters `matchingItems = []` mid-compilation, but I can't see a reason as to why this behavior shouldn't be with ||= or ?=; just as the compiler adds `var matchingItems;` when it encounters the declaration in the second code sample if it wasn't previously defined in the scope, it should do the same for the first code sample.

If there is another reason behind this behavior that I cannot see then I'd appreciate if my thinking would be corrected.

**Comment by vendethiel** [comment]
See [Common Gotchas](https://github.com/jashkenas/coffeescript/wiki/Common-Gotchas#q-why-does-coffeescript-require-foo-to-be-defined-when-doing-foo--value-or-foo--value).

**Comment by danielkalen** [comment]
Thanks for the reference, but kindly read the rest of my comment and see what I wrote about declaring the variable at the top of the current scope when not found...
