### ISSUE TITLE
[CS2] Support asynchronous generators (async and yield)

### ISSUE THREAD

**Issue by tphecca** [jashkenas/coffeescript#4557]
Asynchronous generators are currently a stage 3 ECMAScript proposal: https://github.com/tc39/proposal-async-iteration

For this code:
```coffeescript
thing = () ->
  while true
    yield await new Promise (res, rej) ->
      setTimeout () -> res("hey")
```
... `coffeescript@next` throws:
```
[stdin]:3:11: error: function can't contain both yield and await
    yield await new Promise (res, rej) ->
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

For the `for await` loop in this code:
```coffeescript
() ->
  alert(something) for await something of thing()
```
... the error is:
```
[stdin]:2:24: error: unexpected await
  alert(something) for await something of thing()
                       ^^^^^
```

In my opinion, the behavior should be as simple as `await` or `yield`. A function that `yield`s and `await`s should be an `async function*`. Also, a function that contains `for await` should be an `async function`. Maybe the `for await` syntax conflicts in some way and could be different for CS. The addition of this functionality may further simplify working with asynchronous code in CoffeeScript.

Unfortunately, I couldn't find any implementations of this functionality besides Babel; it may have to be put on hold until it is natively supported.

**Comment by GeoffreyBooth** [comment]
If you want to output using the ES syntax, our policy is to wait until a syntax has reached Stage 4. http://coffeescript.org/v2/#contributing

**Comment by tphecca** [comment]
Oops! I missed that part. Sorry about that.

**Comment by SirCmpwn** [comment]
The syntax is now standardized in Ecmascript 2017.

**Comment by GeoffreyBooth** [comment]
@SirCmpwn link?

**Comment by SirCmpwn** [comment]
https://tc39.github.io/ecma262/2017/#sec-async-function-definitions

**Comment by GeoffreyBooth** [comment]
I don’t see mention of `async function*` there, but that link is awfully confusing. The other link (from above on this thread) still says Stage 3. Is there another reference you could point to?

**Comment by SirCmpwn** [comment]
https://github.com/tc39/proposals/blob/master/finished-proposals.md ("finished" and "stage 4" mean the same thing). But it was my fault for not reading the issue clearly, I thought it was just regarding the async/await keywords for function definitions and calls.

**Comment by GeoffreyBooth** [comment]
[Async functions are supported in CoffeeScript 2](http://coffeescript.org/v2/#async-functions). (And generators in 1.x and 2.)
