### ISSUE TITLE
CLI: `--` option is ignored

### ISSUE THREAD

**Issue by kaime** [jashkenas/coffeescript#4560]
When running files with the `coffee` command, rewritten `process.arv` does not  include "empty"  `--` options, usually used to disambiguate. So a script can behave differently when run with `coffee` or when transpiled to js and then executed with `node`. I don't know if this could be possibly intentioned.

`argv.coffee`
``` coffee
console.log process.argv
```
`argv.js`
``` js
console.log(process.argv);
```

``` sh
$ node argv.js --foo -- --bar
[ '/usr/local/bin/node',
  '/home/jaume/argv.js',
  '--foo',
  '--',
  '--bar' ]

$ coffee argv.coffee --foo -- --bar
[ 'coffee',
  '/home/jaume/argv.coffee',
  '--foo',
  '--bar' ]

$ coffee -v
CoffeeScript version 1.12.6
```
I've seen so far literal `--` arguments are being descarted internally when parsed in `optparse.coffe`. And they are given back to the running script.

Try to alter the `opts.arguments` array would make the tests break. But don't I see why not passing the raw remining slice of `process.argv`:

``` diff
diff --git a/src/command.coffee b/src/command.coffee
index 6bcf2ed4..b929be78 100644
--- a/src/command.coffee
+++ b/src/command.coffee
@@ -79,7 +79,11 @@ exports.run = ->
   return compileStdio()                         if opts.stdio
   return compileScript null, opts.arguments[0]  if opts.eval
   return require('./repl').start(replCliOpts)   unless opts.arguments.length
-  literals = if opts.run then opts.arguments.splice 1 else []
+  if opts.run
+    literals = process.argv[3..]
+    opts.arguments.splice 1
+  else
+    literals = []
   process.argv = process.argv[0..1].concat literals
   process.argv[0] = 'coffee'

```

**Comment by GeoffreyBooth** [comment]
See #3946. Assistance finishing that PR is welcome.

**Comment by kaime** [comment]
Isn't the above a much simpler solution?

**Comment by GeoffreyBooth** [comment]
I think that PR is aiming to solve other CLI issues in addition to this one.

**Comment by kaime** [comment]
Yes, and those 6 lines should address them all. I've read the conversation and the code (sorry I did not find it before), and while that PR is trying to change the way the `coffee` command parses the arguments, I say: "keep parsing them the way you feel for your internals, but give them untouched to me". 

`optparse` is not a public API nor is being used anywhere else. Changing its internals may or not be considered a breaking change, but what I propose could even be considered a fix (now you get all arguments, unmodified!), unless current behavior is documented.

**Comment by GeoffreyBooth** [comment]
Do you care to submit a PR then?

There should also be tests that the various CLI flags work as expected, for example by running `execSync('./bin/coffee -v')` and confirming that the output is `"CoffeeScript version #{CoffeeScript.VERSION}"`.

**Comment by GeoffreyBooth** [comment]
Closing as #3946 addresses this, as far as I can tell. Please comment if otherwise.
