### ISSUE TITLE
Proposal: `do` keyword when used with the existential operator on a function should conditionally call the function

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#4562]
`do a.b?` currently copiles to `(a.b != null)();` which has no usecase and defeats the purpose of the `?` operator.

i expect the output to be the same as for `a.b?()` which gives
```
if (typeof a.b === "function") {
  a.b();
}
```
i'm using 2.0.0-beta2 but this also bit me before cs2.

**Comment by GeoffreyBooth** [comment]
Minimal case:

```coffee
do a   # a();

do a?  # (typeof a !== "undefined" && a !== null)();
```

There’s also this weird case:

```coffee
do a?()
```
___
```js
if (typeof a === "function") {
  a()();
}
```

**Comment by GeoffreyBooth** [comment]
I’m not sure anything should necessarily be changed. The `do` keyword is meant to [wrap a closure around a passed function](http://coffeescript.org/v2/#loops), not to call a function—as in, it’s not a substitute for putting `()` after a function name. One could argue that it should throw an error or otherwise behave differently than it currently does when passed plain identifiers rather than inline functions.

The current way to write the OP’s desired output is fairly simple, if not quite as concise as desired:

```coffee
if a.b? then a.b()
```

**Comment by Inve1951** [comment]
@GeoffreyBooth 

I interpret the **do** keyword as an invocation _operator_.

`do ->` calls a function defined in the same line. You can also write `do a = ->` which does the same but also allows reusing that function.

`do a?()` seems logical to me; just like `do a()` it invokes the result of `a()` but with the added null check.

Note that also `do a.b?.c` compiles as expected:
```
var ref;

if ((ref = a.b) != null) {
  ref.c();
}
```

`if a.b? then a.b()` could as well be achieved thru `a.b?()`, i'm aware of that.

I got used to using the **do** keyword to call functions without arguments. It get's rid of the parens and IMO is more readable.

It's a great feature that bugs out in that one case where you got the `?` operator at the end of the statement.

Changing/fixing this doesn't brake existing code.
I really hope you reconsider.

**Comment by lydell** [comment]
@GeoffreyBooth I’d say that `do foo` instead of `foo()` is pretty common.

**Comment by GeoffreyBooth** [comment]
I’m not saying it isn’t, but as designed this isn’t a bug. It’s more a request that we change the behavior of `do` when it’s passed an identifier instead of an inline function. If there’s no reason to keep the current behavior, sure, let’s do it.

@Inve1951 please feel free to submit a PR.

**Comment by jashkenas** [comment]
This should not be changed.

`?()` Is a special form, with `foo?()` calling `foo` only if `foo` a function.

`do expression` calls that expression. It's not meant to be used directly — the `do` keyword only exists to make immediately-invoked closure wrappers cleaner to write, but `do` can invoke arbitrary expressions as a consistent courtesy.

`a.b?` is an expression. `do a.b?` should call the value of it. Just like it does.

**Comment by Inve1951** [comment]
@jashkenas 

> This should not be changed.

Why's that? Changing it won't break anything and adds functionality.


@GeoffreyBooth 

> please feel free to submit a PR.

I'd love to. Unfortunately i didn't get my head around the compiler's code in the past. I'll give it another try tho.
