### ISSUE TITLE
[CS2] Lexer: Destructuring with nested default values

### ISSUE THREAD

**Issue by helixbass** [jashkenas/coffeescript#4566]
@GeoffreyBooth I just ran into something that broke (I assume unintentionally) as a result of #4478: eg `({a: {b = 1}}) ->` compiled ok before this PR but gives `error: unexpected =` after. This destructuring also breaks in a destructured assignment: `{a: {b = 1}} = c` also gives `error: unexpected =`

**Comment by GeoffreyBooth** [comment]
@helixbass you feel like taking a crack at fixing it? Maybe after #4493 is finished?

**Comment by helixbass** [comment]
@GeoffreyBooth sure

**Comment by zdenko** [comment]
@GeoffreyBooth @helixbass this is fixed in my last commit. 
@connec reported the same error on [#4493](https://github.com/jashkenas/coffeescript/pull/4493) yesterday.

**Comment by GeoffreyBooth** [comment]
@zdenko just noticed your comment. Sorry, I already merged the other PR in. I guess merge `2` into your branch and resolve conflicts?
