### ISSUE TITLE
Support for Node's `--inspect` flag

### ISSUE THREAD

**Issue by Chris911** [jashkenas/coffeescript#4571]
Node now has a [`--inspect` debug flag](https://nodejs.org/api/cli.html#cli_inspect_host_port) which activates the Google DevTools for the given process. Is there a way to get that flag to work with Coffeescript through the `coffee` command? I tried using the `--nodejs` argument (`--nodejs="--inspect"`) but it doesn't give me a debug link.

Thanks!

**Comment by GeoffreyBooth** [comment]
It’s possible now. You just need to call `node --inspect` first, with your next argument the path to the `coffee` executable:

```bash
printf 'console.log "Hello,"\ndebugger\nconsole.log "World!"\n' > test.coffee
node --inspect-brk $(which coffee) ./test.coffee
```

**Comment by Chris911** [comment]
Thanks.
