### ISSUE TITLE
ES6 syntax of coffeescript/register

### ISSUE THREAD

**Issue by metalim** [jashkenas/coffeescript#4573]
Previously I've been using following in my JS entry points:
```
require('coffeescript/register');
module.exports = require('./entry.coffee');
```

What is the corresponding ES6 syntax of this?
Following does not seem to register anyhing.
```
import register from 'coffeescript/register';
export * from 'entry.coffee';
```

Tested on Coffeescript 2.0 beta2.

**Comment by GeoffreyBooth** [comment]
I don’t know what you’re trying to do with exports, but just play with [Babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=import%20'coffeescript%2Fregister'%0A) until you find the compilation that you want:

```coffee
import 'coffeescript/register'
```
___
```js
'use strict';

require('coffeescript/register');
```
