### ISSUE TITLE
[CS2] Nodes: Renamed destructured parameters break when having same default value

### ISSUE THREAD

**Issue by rodovich** [jashkenas/coffeescript#4577]
The following function declaration produces a compilation error: `multiple parameters named 0`.

```coffee
({ a: aa = 0, b: bb = 0 }) ->
  "#{aa}, #{bb}"
```

If the default values are different, it works as expected:

```coffee
f = ({ a: aa = 0, b: bb = 42 }) ->
  "#{aa}, #{bb}"

f({}) # '0, 42'
f({a: 5}) # '5, 42'
f({b: 6}) # '0, 6'
f({a: 5, b: 6}) # '5, 6'
```

Likewise, it works as expected if either parameter is not renamed, and it works as a destructuring assignment:

```coffee
(arg) ->
  { a: aa = 0, b: bb = 0 } = arg
```

**Comment by GeoffreyBooth** [comment]
Fixed by #4596.
