### ISSUE TITLE
Lexer: Input of colon (:) throws exception

### ISSUE THREAD

**Issue by richdougherty** [jashkenas/coffeescript#4578]
One other exception on CoffeeScript 1.11.0 and 1.12.6. An input of `:` results an exception with the text `Cannot read property 'newLine' of undefined`. Sorry I haven't got the stack trace for this one.

This may be related to https://github.com/jashkenas/coffeescript/issues/4575.

I've informally tested most other punctuation on my keyboard and these are the only two lexer errors I get.

**Comment by lydell** [comment]
@richdougherty Is this what you mean? http://coffeescript.org/#try:%3A

**Comment by richdougherty** [comment]
Yes that's what I mean. Expected output is something like `Error on line 1: unexpected :`. Actually, I don't have a stack trace so I'm not sure if the error is in the lexer or not.

**Comment by GeoffreyBooth** [comment]
Fixed by #4662.
