### ISSUE TITLE
[CS2] super.x.y throws a compiler error

### ISSUE THREAD

**Issue by helixbass** [jashkenas/coffeescript#4591]
Starting to go through `nodes.coffee` for comprehension, noticed that in the `SimpleAssignable` grammar rules, `Value Accessor` assumes that it can call `.add()` on the `Value`, but `Super` (which is a `Value` in the grammar) doesn't have an `.add()` method. So things like `super.x.y` and `super['x'].y` throw compiler errors when trying to call the missing `.add()` method

**Comment by GeoffreyBooth** [comment]
Fixed by #4592
