### ISSUE TITLE
[CS2] Enhancement: Support object spread syntax in multiline objects without braces or commas

### ISSUE THREAD

**Issue by laurentpayot** [jashkenas/coffeescript#4600]
```coffeescript
foo =
  a: 1
  b: 2

bar =
  foo...
  c: 3
```
results in
```
error: unexpected ...
	foo...
	   ^^^
```
For now we have to use:
```coffeescript
bar = {
  foo...,
  c: 3
}
```
It's a bit ugly and it adds an exception to the nice CS way of object notation.

**Comment by connec** [comment]
Copying https://github.com/jashkenas/coffeescript/pull/4493#issuecomment-312258561

---

That's probably related to [`looksObjectish`](https://github.com/jashkenas/coffeescript/blob/master/src/rewriter.coffee#L110) in the rewriter, which seems to only accept implicit object literals when there's a `:` involved (which is consistent with being unable to use shorthand properties in implicit objects.

Tbh we probably want to leave it like this, or we'll need to face down ambiguities in expressions like

```coffee
f k: v, rest...
```

Which, currently, will compile to two arguments (an object literal and a splat param) but would be ambiguous if we allowed splats to exist in implicit objects.

**Comment by connec** [comment]
As an aside, commas are still optional, even with explicit braces:

```coffee
{
  foo...
  bar
  baz: 'qux'
}
```

**Comment by GeoffreyBooth** [comment]
I ran into this just writing the documentation. I think it's a thing that will be very common for people to want to do. Could we find a way to allow spreads in multiline objects, while leaving function arguments unaffected (i.e. to avoid ambiguity problems)?

**Comment by zdenko** [comment]
@GeoffreyBooth, @connec, @helixbass 
 I've started to play with this and made some progress.

```javascript
foo =
  bar...
  c: 3
```
compiles to
```javascript
foo = Object.assign({}, bar, {
    c: 3
  });
```

`f a:x, rest...` into `f({a:x}, ...rest)`

`f {a:x, rest...}` into 
```javascript
f(Object.assign({
    a: x
  }, rest))
```

And if I'm correct, there is also this case
```javascript
foo = 
  bar
  c: 3
```
which should compile to
```javascript
foo = {
   bar,
   c: 3
}
```

**Comment by vendethiel** [comment]
> And if I'm correct, there is also this case
> ```
> foo = 
>   bar
>   c: 3
> ```
> which should compile to
> ```
> foo = {
>    bar,
>    c: 3
> }
> ```

I'm not sure we want this. I read it as `foo = bar c: 3` at first, and we don't do that for function calls.

**Comment by zdenko** [comment]
Current status:

```coffeescript
# foo = 
#   bar 
#   c: 3
foo = {
  bar,
  c: 3
}

# foo = 
#   bar c: 3
foo = bar({c:3))

# foo = 
#   bar 
#     c: 3
foo = bar({c:3))
```

**Comment by GeoffreyBooth** [comment]
See also https://github.com/jashkenas/coffeescript/pull/4551#issuecomment-313492106

**Comment by GeoffreyBooth** [comment]
Closing per discussion in #4618.
