### ISSUE TITLE
Using CS2 with babel/webpack

### ISSUE THREAD

**Issue by eskhool** [jashkenas/coffeescript#4608]
Now that CS2 is well on its way to ES2015 compatibility, how would one go about integrating it with a babel/webpack which brings other benefits like polyfills etc where required and concatenating js files into a bundle and handling imports and dependencies

**Comment by GeoffreyBooth** [comment]
Webpack: https://github.com/webpack-contrib/coffee-loader/issues/39
Babel: http://coffeescript.org/v2/#usage
