### ISSUE TITLE
CLI: support both versions

### ISSUE THREAD

**Issue by paulpflug** [jashkenas/coffeescript#4614]
I created a wrapper to be able to compile coffee files in v1 and v2 within the same project.
[coffee-cli](https://github.com/paulpflug/coffee-cli)

I think such functionality would be great in core..

What do you think?

**Comment by GeoffreyBooth** [comment]
1.x is closed to further development. We're trying to avoid a split in community, where some people continue on 1 while others move to 2; the hope is that everyone can and does move to 2. Building in official support for continued use of 1 goes against this goal.
