### ISSUE TITLE
1.12.17 tag not published to github

### ISSUE THREAD

**Issue by MylesBorins** [jashkenas/coffeescript#4619]
Seems like the latest tag was not pushed to github. This is breaking citgm.

Thanks in advance for helping with this 😊

**Comment by GeoffreyBooth** [comment]
Sorry about that! https://github.com/jashkenas/coffeescript/tree/1.12.7

**Comment by MylesBorins** [comment]
Thanks for the swift update. Everything is working now and we'll update you if we see any regressions in Node v6 >

**Comment by GeoffreyBooth** [comment]
FYI we’re working on [CoffeeScript 2](http://coffeescript.org/v2/), which is using the `coffeescript` name on NPM (as opposed to `coffee-script`). The `coffeescript` package has all the 1.x versions as well. You might want to consider adding `coffeescript` or `coffeescript@next` (the tag for 2-beta) to citgm.
