### ISSUE TITLE
[CS2] Clarify the project status

### ISSUE THREAD

**Issue by carlsmith** [jashkenas/coffeescript#4620]
I just started a little project, and decided to try the new CoffeeScript compiler. The new website's really helpful, but isn't clear about how ready the compiler is. [The progress reports][1] over at `coffeescript6/discuss` are also useful, but still left me unsure of the overall status.

Could someone please clarify how ready the compiler is, and whether you'd like people to start using it for less serious stuff yet? It may be worth adding this info to the website too. -- thanks

[1]: https://github.com/coffeescript6/discuss/issues?utf8=%E2%9C%93&q=is%3Aissue%20progress%20as%20of%202.0.0%20

**Comment by GeoffreyBooth** [comment]
I think it’s ready to use for real projects. I want to get #4607, #4611 and #4572 merged in and release another beta, and if there are no serious bugs reported from that beta then we’ll release 2.0.0. But there have been very few bug reports for the last several betas, so hopefully it’s pretty stable and ready to use.

**Comment by carlsmith** [comment]
Awesome. Thank you. Those issues are all relatively minor.

You've done an epic job with this mate. It's amazing how far you've come. I remember when most people doubted it would ever happen. ES6 support is obviously useful, but having it also gives people a lot more optimism about the future of the language generally, with all the benefits that come from that.

I'll let you know if anything comes up. Thanks again man.

**Comment by danielbayley** [comment]
> You've done an epic job with this mate.

@GeoffreyBooth You really have! Thank you for basically saving the language… we all owe you! 🍺
