### ISSUE TITLE
[CS2] Lexer: `do super` in constructor

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#4623]
[code:](http://coffeescript.org/v2/#try:class%20a%0Aclass%20b%20extends%20a%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20do%20super)
```coffee
class a
class b extends a
  constructor: ->
    do super
```
output:
```
[stdin]:4:12: error: unexpected indentation
    do super
           ^
```
expected output is same as for [`super()`](http://coffeescript.org/v2/#try:class%20a%0Aclass%20b%20extends%20a%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20super())
```js
var a, b;

a = class a {};

b = class b extends a {
  constructor() {
    super();
  }

};
```

**Comment by GeoffreyBooth** [comment]
Fixed via #4627.
