### ISSUE TITLE
Proposal: Decorators

### ISSUE THREAD

**Issue by stevefan1999** [jashkenas/coffeescript#4626]
https://github.com/babel/proposals/issues/11

https://github.com/babel/proposals/issues/13

Sample input:
```cs
decorateClass = klass -> klass.isDecorated = yes, klass

@decorateClass
class DecorateMe
  constructor: ->

console.log new DecorateMe().isDecorated // true
```
Expected output (Babel):
```js
const decorateClass = klass => {
  klass.isDecorated = true
  return klass
}
@decorateClass
class DecorateMe {
  constructor() {
  }
}

console.log(new DecorateMe().isDecorated) // true
```
Current workaround: Apply the decorate as a high-order function like in ES5
```cs
decorateClass = klass -> klass.isDecorated = yes, klass

decorateClass class DecorateMe
  constructor: ->

console.log new DecorateMe().isDecorated // true
```
Or:
```
decorateClass = klass -> klass.isDecorated = yes, klass

class DecorateMe
  constructor: ->

DecorateMe = decorateClass DecorateMe

console.log new DecorateMe().isDecorated // true
```

_You may find it difficult to understand, but please proof-read as much. I'm not English-native._

**Comment by GeoffreyBooth** [comment]
It is our policy to not support outputting any ES syntax that has yet to reach stage 4 (i.e. finalized). See http://coffeescript.org/v2/#contributing. We can support the feature, like we support object spread syntax, but the compiler’s output would need to use finalized ES syntax. What this means in practice is that if support for the feature is added, the CoffeeScript compiler’s output would generally be similar or identical to Babel’s output for that feature.

See related #4552.

**Comment by unadlib** [comment]
const decorateClass = klass => {
  klass.isDecorated = true
  return klass
}
@decorateClass
class DecorateMe {
  constructor() {
  }
}
// use babel-plugin-transform-decorators-legacy
console.log(DecorateMe().isDecorated) //true
console.log(new DecorateMe().isDecorated)//undefined

**Comment by unadlib** [comment]
`const decorateClass = klass => {
klass.isDecorated = true
return klass
}
@decorateclass
class DecorateMe {
constructor() {
}
}
// use babel-plugin-transform-decorators-legacy
console.log(DecorateMe().isDecorated) //true
console.log(new DecorateMe().isDecorated)//undefined`

**Comment by unadlib** [comment]
> const decorateClass = klass => {
klass.isDecorated = true
return klass
}
@decorateclass
class DecorateMe {
constructor() {
}
}
// use babel-plugin-transform-decorators-legacy
console.log(DecorateMe().isDecorated) //true
console.log(new DecorateMe().isDecorated)//undefined

**Comment by GeoffreyBooth** [comment]
Closing due to lack of interest.
