### ISSUE TITLE
[question] async call in constructor

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#4632]
this is my first time trying to use await/promises

in a class constructor i put [this](http://coffeescript.org/v2/#try:class%20abc%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20if%20await%20new%20Promise%20(r)%20%3D%3E%0A%20%20%20%20%20%20cache.get%20%40url%2C%20(b)%20%3D%3E%0A%20%20%20%20%20%20%20%20r%20b%0A%20%20%20%20%20%20%20%20return%0A%20%20%20%20%20%20return%0A%20%20%20%20then%20return%0A):
```coffee
if await new Promise (r) =>
  cache.get @url, (b) =>
    r b
    return
  return
then return
```
since that gave me `error: Class constructor may not be async` when compiling i tried to work around it by [wrapping it with `do =>`](http://coffeescript.org/v2/#try:class%20abc%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20do%20%3D%3E%0A%20%20%20%20%20%20if%20await%20new%20Promise%20(r)%20%3D%3E%0A%20%20%20%20%20%20%20%20cache.get%20%40url%2C%20(b)%20%3D%3E%0A%20%20%20%20%20%20%20%20%20%20r%20b%0A%20%20%20%20%20%20%20%20%20%20return%0A%20%20%20%20%20%20%20%20return%0A%20%20%20%20%20%20then%20return%0A):
```coffee
do =>
  if await new Promise (r) =>
    cache.get @url, (b) =>
      r b
      return
    return
  then return
```
which throws at runtime with `Uncaught SyntaxError: Unexpected token (` after `async`
i get the same result when adding a space after `async`

so my question is, what am i doing wrong?

**Comment by Inve1951** [comment]
just realized the electron environment i'm forced to deal with is based on chrome 53 and node 6.5 which didn't have asynch/await yet

**Comment by GeoffreyBooth** [comment]
[ES2015 class constructors cannot be async.](https://github.com/jashkenas/coffeescript/pull/4354#issuecomment-264684619)

**Comment by Inve1951** [comment]
see what the second snippet compiles to
if that's bad js should the compiler catch that too?
@GeoffreyBooth

**Comment by GeoffreyBooth** [comment]
Second snippet runs for me in Chrome, as long as `cache` is defined.

**Comment by Inve1951** [comment]
then i was right with the environment just being outdated, thanks
