### ISSUE TITLE
[CS2] Requiring external module Failed to load external module coffeescript/registercoffee-script/register

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4637]
![image](https://user-images.githubusercontent.com/30184325/29152437-15e25318-7d90-11e7-9ead-259fd928bd53.png)

If i try fun gulp with `gulpfile.coffee`, then i get error. Apparently this is due to the fact that there are two `coffeescript` and `coffee-script` modules installed.

If i uninstall coffee-script -g i get error too:

![image](https://user-images.githubusercontent.com/30184325/29152647-1e078ec2-7d91-11e7-93d3-d09873a4280b.png)

It is gulp problem, or it coffeescript/register problem?
---

**Comment by MegaUITeam** [comment]
Here's what I noticed, if I do this, then I can not use import:

index.js
```javascript
require('coffeescript/register')
require('./file.coffee')
```

file.coffee
```coffeescript
import lol from 'module'
```

i get:
```
import q from 'del';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by GeoffreyBooth** [comment]
It’s a problem with your project. [Gulp should automatically use](https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md#370) the version of CoffeeScript installed locally in your project:

```bash
npm install coffeescript
```

See https://github.com/geoffreybooth/coffeescript-gulp for an example. That project has `coffeescript` in its `package.json`, and I have `coffeescript@next` installed globally.

**Comment by objectkit** [comment]
@GeoffreyBooth I realise this thread is closed, but I didn't want to open another unnecessarily. Presently working on finishing a project that uses CS2 ^2.0.0-beta4. I worked around the coffee-script/coffeescript issue by using [module-alias](https://www.npmjs.com/package/module-alias) and with the following in ``package.json``

```
    "_moduleAliases": {
        "coffee-script": "node_modules/coffeescript/lib/coffeescript"
    }
```
This did seem to work, but while doing a fresh install during testing, the legendary ``Failed to load external module coffee-script/register`` message has started up again.

Trying to rule out project setup, but its not looking to be the case. Any suggestions? Is there an official stance on how to manage coffee script/coffee-script moving forward? Hoping to get some time next week to get more involved.

**Comment by GeoffreyBooth** [comment]
See https://github.com/js-cli/js-interpret/pull/45

Do you get this error, but then everything works? Or it gets this error and dies? 

The js-interpret module is the source of this error. If you see the error but then everything works, you're fine, don't do anything. That's just js-interpret guessing which module you have installed until it guesses correctly. If you get the error and then it does, you need to upgrade js-interpret, which might mean upgrading Gulp or using Gulp 4 (installed from the Git repo 4 branch).

**Comment by objectkit** [comment]
I get the error, basic tasks work, but one quite important one, fails.

I'm using github:gulpjs/gulp#4.0 which npm lists as version 4.0.0-apha.2. The error began just after updating it as well as a few other dependencies, so yes, as above, _this is a project management issue and not a coffee script issue_. This is going to take a few days to sort out. Thanks for your time!
