### ISSUE TITLE
CLI: Options to control output of comments

### ISSUE THREAD

**Issue by danielbayley** [jashkenas/coffeescript#4638]
Now that #4572 has landed, it might be handy to be able to control the output of comments in the CLI.

I briefly started on a PR, but figured it would be a good idea to discuss first.

So, bike-shedding… maybe this could look like:

~~~
--no-comments		discard all comments in output
--block-comments	output ### block comments ### only
~~~
or maybe just `--comments=` where one of `[ true, 'block', 'inline', false ]` is given as the value (corresponding to output all comments, block comments only, line comments only, or output comments).

Thoughts?

**Comment by lydell** [comment]
Why?

**Comment by GeoffreyBooth** [comment]
The last time command-line flags were discussed, the strong preference was to not add any more of them. Each one we add introduces more complexity, a need for more tests, etc. So if one is to be added, it needs a strong justification.

In this particular case, one could pipe the CoffeeScript compiler’s output through Babel with its `comments: false` option set, and the comments will be stripped out. Is there a reason that’s not good enough? With CoffeeScript 2 we’re intentionally not trying to duplicate Babel’s functionality, hence the output as ES2015 only without options for ES5 output etc. We’re leaving to Babel the things that it can do and that it already does well.

So if you’d like to make a case for why this is needed, please feel free and I’ll reopen if there’s consensus.

**Comment by nilskp** [comment]
@GeoffreyBooth I would really like to see this re-opened.

I use lots of comments that I don't want emitted in the Javascript output, nor do I need an additional transpiler step, which would make my workflow too slow.

Since retaining comments is a breaking change from CS1, it really ought to have been an opt-in feature to retain comments. However that's history now, so at the very least there should be an option to retain old behavior.

**Comment by GeoffreyBooth** [comment]
There are lots of breaking changes, but none of them are opt-in. We don't want the complexity of making this configurable, especially since it's so easily managed through other tools. We're not trying to reproduce Babel.
