### ISSUE TITLE
Feature request: var keyword!

### ISSUE THREAD

**Issue by Romaboy** [jashkenas/coffeescript#4641]
In my coffeescript code I often do such thing:
```coffeescript
foo = bar = baz = undefined
somefunction = ->
  foo = value
otherfunction = ->
  "I'm need that variables too!"
```
Sometimes there is a need of global variables per file.
I would be very pleasent if in coffeescript2 I could do that not worth than in plain javascript:
```
var foo, bar, baz
somefunction = ->
  foo = value
```

**Comment by GeoffreyBooth** [comment]
Sorry, that’s a design decision that has been settled. See http://coffeescript.org/v2/#unsupported-let-const

**Comment by Romaboy** [comment]
@GeoffreyBooth so, `foo = bar = baz = undefined` is correct coffeescript way to declare variables in right scope? Maybe there is better way?

**Comment by lydell** [comment]
@Romaboy Yes, that's a perfectly fine way to do it.

**Comment by jashkenas** [comment]
That works, but `foo = null` is even more correct.

**Comment by connec** [comment]
`foo = null` might be dangerous in CS2, since it's not 'empty' from the perspective of argument defaults.

```coffee
f = (param = 'default') -> param

foo = null
f foo # null
```

**Comment by jashkenas** [comment]
A beautiful demonstration of why treating `undefined` and `null` differently (w/r/t default arguments, or anything else) is wrong!
