### ISSUE TITLE
[CS2] Docs: Erroneous statement in "unsupported named functions" section

### ISSUE THREAD

**Issue by connec** [jashkenas/coffeescript#4642]
I would push a PR for this but I'm not setup to build the docs etc. so I'm making an issue so I don't forget!

---

The "unsupported named functions" section of the docs currently says:

> given that not all functions in function expressions can be named (for example, the functions in first.fn = ->; second.fn = -> can’t both be named fn)

This isn't true, as the following is perfectly valid JS:

```js
var first = {}, second = {}
first.fn = function fn () {}
second.fn = function fn () {}
```

Afaik, any function expression can be named in this way.

**Comment by GeoffreyBooth** [comment]
Fixed by #4682.
