### ISSUE TITLE
[CS2] Geters and Setters in object and classes

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4647]
Since we change the version to 2, then we lose backward compatibility, and we must use this fact to the maximum.

```coffeescript
obj = 
  get name:      -> @_name
  set name: (val)-> @_name = val
```

```coffeescript
class Cat
  get name:      -> @_name
  set name: (val)-> @_name = val
```

**Comment by connec** [comment]
This has been discussed extensively and rejected in https://github.com/coffeescript6/discuss/issues/17.

The TL;DR is that we shouldn't be encouraging liberal use of getters/setters. If you must use them, you can do so with `Object.defineProperty`.

**Comment by MegaUITeam** [comment]
Why do browsers encouraging liberal use, and you should not?

**Comment by GeoffreyBooth** [comment]
http://coffeescript.org/v2/#unsupported-get-set

**Comment by MegaUITeam** [comment]
@GeoffreyBooth 
why `return 33` is not call return(33) but `get 33` is `get(33)` ?
