### ISSUE TITLE
[CS2] JSX: Enable Disentangling Code and Element Tags

### ISSUE THREAD

**Issue by ralmidani** [jashkenas/coffeescript#4648]
As it currently stands, JSX support in CS2 is already "enhanced" in comparison to plain JSX, by virtue of Coffee's support for inline if/else (which gets transpiled to the ternary operator which is supported in plain JSX).

Is there a plan to take things a step further and allow code to live in its own `{}` block, and then elements indented under that code would be evaluated (or not) depending on what is indicated in the code above it?

Using the example from the docs, could we enable users to modify this:

```coffeescript

renderStarRating = ({ rating, maxStars }) ->
  <aside title={"Rating: #{rating} of #{maxStars} stars"}>
    {for wholeStar in [0...Math.floor(rating)]
      <Star className="wholeStar" key={wholeStar} />}
    {if rating % 1 isnt 0
      <Star className="halfStar" />}
    {for emptyStar in [Math.ceil(rating)...maxStars]
      <Star className="emptyStar" key={emptyStar} />}
  </aside>
```

So it looks like this:

```coffeescript
renderStarRating = ({ rating, maxStars }) ->
  <aside title={"Rating: #{rating} of #{maxStars} stars"}>
    {for wholeStar in [0...Math.floor(rating)]}
      <Star className="wholeStar" key={wholeStar} />
    {if rating % 1 isnt 0}
      <Star className="halfStar" />
    {for emptyStar in [Math.ceil(rating)...maxStars]}
      <Star className="emptyStar" key={emptyStar} />
  </aside>
```
Notice how curly braces for the conditional and looping statements open and close on their own lines, rather than after the element tags. The change may seem trivial, but consider a more elaborate layout with nested maps and a conditional (taken from [here](https://github.com/udacity/reactnd-udacimeals-complete/blob/2b60fe731b2e4f8ebcfaaafc0ac36ecd11e5215d/src/components/App.js#L96-L113), but with the ternary operator converted to if/else):

```CoffeeScript
<div className='icon-grid'>
  {calendar.map(({ day, meals }) => (
    <ul key={day}>
      {mealOrder.map((meal) => (
        <li key={meal} className='meal'>
          {if meals[meal]
            <div className='food-item'>
              <img src={meals[meal].image} alt={meals[meal].label}/>
              <button onClick={() => remove({meal, day})}>Clear</button>
            </div>
            else
              <button onClick={() => this.openFoodModal({meal, day})} className='icon-btn'>
                <CalendarIcon size={30}/>
              </button>}
        </li>
      ))}
    </ul>
  ))}
</div>
```
This example is part of Udacity's React Nanodegree, in which I am enrolled. Even when I had the code in front of me, adding it to my own version of the project (and making sure all the closing curlies were in the right place) felt like sheer torture.

When I finish the program, I hope to use CS2 with React (I currently use CS1 with Ember), and was wondering if the compiler could, like Django, Erb, Handlebars, etc., enable developers to write templates that are cleaner, more readable, and more maintainable.

As I mentioned, CS2 already enhances JSX with support for inline if/else. Is this another enhancement worth considering?

**Comment by helixbass** [comment]
@ralmidani the JSX syntax won't be updated the way you envision since that would depart greatly (and kind of unintuitively) from actual JSX syntax, and it was decided that official CoffeeScript 2 JSX syntax would be less opinionated/divergent

But I recommend you check out my [`coffeescript-jsxy`](https://github.com/helixbass/coffeescript-jsxy) package (syntax explained [here](http://helixbass.net/projects/jsxy)), which is based on CoffeeScript 2 and implements a nice whitespace-indented [Haml](http://haml.info)-inspired JSX syntax

In JSXY, your example could be written like:
```
.icon-grid
  = for {day, meals} in calendar
    %ul{ key: day }
      = for meal in mealOrder
        %li.meal{ key: meal }
          = if meals[meal]
            .food-item
              %img{ src: meals[meal].image, alt: meals[meal].label }
              %button{ onClick: -> remove {meal, day}} Clear
           else
            %button.icon-btn{ onClick: => @openFoodModal {meal, day}}
              %CalendarIcon{ size: 30 }
```
Or if you prefer you can eg still use `.map()`, don't have to use shorthand class syntax, can spread attributes onto separate lines, ...:
```
...
= mealOrder.map (meal) ->
  %li{
    className: 'meal'
    key: meal
  }
...
```

And that example from the docs could be written like:
```
renderStarRating = ({ rating, maxStars }) ->
  %aside{ title: "Rating: #{rating} of #{maxStars} stars" }
    = for wholeStar in [0...Math.floor(rating)]
      %Star.wholeStar{ key: wholeStar }
    = if rating % 1 isnt 0
      %Star.halfStar
    = for emptyStar in [Math.ceil(rating)...maxStars]
      %Star.emptyStar{ key: emptyStar }
```
or using some nice postfix `if`/`unless`/`for`:
```
renderStarRating = ({ rating, maxStars }) ->
  %aside{ title: "Rating: #{rating} of #{maxStars} stars" }
    = %Star.wholeStar{ key: wholeStar } for wholeStar in [0...Math.floor(rating)]
    = %Star.halfStar unless rating % 1 is 0
    = %Star.emptyStar{
      key: emptyStar
    } for emptyStar in [Math.ceil(rating)...maxStars]
```

**Comment by ralmidani** [comment]
@helixbass Wow, I didn't know about your project. The syntax is really nice!
