### ISSUE TITLE
[CS2] Geters and Setters in object and classes

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4650]
Maybe I'll change your mind.
---

Why `return 33` is not `return(33)`, but `get 33` is `get(33)` ?
Because we made a `return` as keyword operator. What prevents do `get` as keyword operators?

Since we change the version to 2, then we lose backward compatibility, and we must use this fact to the maximum.

By entering a new keyword, we will lose backward compatibility, but we have already lost it, when going to version 2.0. So why do not we use this fact as much as possible? So you do not have to do 3.0

We lose backwards compatibility, then we get all the features es6. For example, we lost the  backwards compatibility, and now if we call function with `null` parameter, the default value is not applied. A lot of code has stopped working. BUT YOU DO NOT STOP!!! And rightly so.

Es6 supports getters? So we must support. For this purpose the transition to version 2.0 was made! We must add OPERATORS `get` and `set`
---

```coffeescript
obj = 
  get name:      -> @_name
  set name: (val)-> @_name = val
```

```coffeescript
class Cat
  get name:      -> @_name
  set name: (val)-> @_name = val
```

How many people will be upset if we realize this? NO ONE. How many people will rejoice? ALL! So what are we waiting for?
---

You can even arrange a vote, and you'll find out what people want. After all, do you do language for people, not for yourself?

Let's discuss, do not close the ticket.

**Comment by GeoffreyBooth** [comment]
The discussion already happened: https://github.com/coffeescript6/discuss/issues/17 and a decision was made: http://coffeescript.org/v2/#unsupported-get-set.

I’m sorry you disagree with it. You’re welcome to fork the project and modify it as you see fit. Please don’t continue to open new issues regarding this.

**Comment by MegaUITeam** [comment]
@GeoffreyBooth Okay, take one minute and parry my arguments. WE will not implement this in the Coffeescript once the decision is made. I just want to hear your opinion. Can you refute my arguments?

**Comment by MegaUITeam** [comment]
lol noob

**Comment by MegaUITeam** [comment]
@GeoffreyBooth on the points name the reasons that interfere with the introduction of what I suggested
