### ISSUE TITLE
[CS2] object spread destructuring bug

### ISSUE THREAD

**Issue by helixbass** [jashkenas/coffeescript#4651]
This throws a compiler error:
```
{person: {mobile}, attrs...} = @props
```
Removing the `@` or the `attrs...` spread param or the `person: {mobile}` destructured param all compile ok

@zdenko @GeoffreyBooth

**Comment by GeoffreyBooth** [comment]
@zdenko do you mind looking into this?

**Comment by zdenko** [comment]
@GeoffreyBooth I'm checking this.

**Comment by connec** [comment]
Fixed by #4652.
