### ISSUE TITLE
Should ES2015 features be transpiled with 1.x?

### ISSUE THREAD

**Issue by JamesMGreene** [jashkenas/coffeescript#4654]
Should ES2015 features be transpiled with `1.x`?  I'm not terribly familiar with CoffeeScript's goals.

I was planning to utilize the [ipaddr.js]()
 module but I see that it uses [`Array.prototype.fill` in its code](https://github.com/whitequark/ipaddr.js/blob/9a275c31fca43380e0a4e9a49597da2d75a02d5e/src/ipaddr.coffee#L462) and that [`coffee-script@~1.12.6`](https://github.com/whitequark/ipaddr.js/blob/9a275c31fca43380e0a4e9a49597da2d75a02d5e/package.json#L11) does [**NOT** transpile that](https://github.com/whitequark/ipaddr.js/blob/9a275c31fca43380e0a4e9a49597da2d75a02d5e/lib/ipaddr.js#L521) into an ES5-compliant format/polyfill/shim.

As `Array.prototype.fill` doesn't have a particularly good [compatibility story](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Browser_compatibility) with older browsers (e.g. no support in any version of IE or Opera), this means a current consumer of the module would also need to shim the `Array.prototype.fill` functionality in before they could use that module.  Is this the correct approach, or should CoffeeScript be transpiling such language additions?

Related: https://github.com/whitequark/ipaddr.js/issues/64
cc: @whitequark

**Comment by vendethiel** [comment]
No, that's not a goal.

**Comment by JamesMGreene** [comment]
Thanks for clarifying, @vendethiel.

**Comment by GeoffreyBooth** [comment]
CoffeeScript isn’t meant to do Babel’s job. The CoffeeScript compiler only transforms CoffeeScript syntax to JavaScript syntax; you then need to pass that output through Babel to get browser-safe code.

**Comment by JamesMGreene** [comment]
:+1:
