### ISSUE TITLE
[CS2 FEATURE] Array accessor operator

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4655]
example 1
---

```coffeescript
cats = [new Cat, new Cat, new Cat]
cats[*].sayMeow()
```

compile to:
```javascript
var cats = [new Cat, new Cat, new Cat]

for(var i = 0; i < cats.length; i++) {
   cats[i].sayMeow()
}
```

example 2
---

```coffeescript
cats = [new Cat, new Cat, new Cat]
names = cats[*].name
```

compile to:
```javascript
var cats = [new Cat, new Cat, new Cat]
var names = []

for(var i = 0; i < cats.length; i++) {
   names.push(cats[i].name)
}
```

example 3
---

```coffeescript
matrix = [[new Point, new Point], [new Point, new Point], [new Point, new Point]]
matrix[*][*].destroy()
```

compile to:
```javascript
var matrix = [[new Point, new Point], [new Point, new Point], [new Point, new Point]]

for(var i = 0; i < matrix .length; i++) {
  for(var j = 0; j < matrix .length; j++) {
    matrix[i][j].destroy()
  }
}
```

example 4
---

```coffeescript
friends = users[*].friends[*]
friends_ids = users[*].friends[*].id
```

example 5 (maybe)
---
Exps with `[*]` operator always return arrays, if we compare two expressions with `[*]` operator, we must compare them by item

```coffeescript
arr1 = [1, 2, 7]
arr2 = [1, 2, 7]

arr1 is arr2       # false
arr1[*] is arr2[*] # true, compare by value as (item1 === item2)

#or
video1.tags[*] is video2.tags[*] # true, compare by value as (item1 === item2)
```

**Comment by MegaUITeam** [comment]
People, lets vote, express opinions. If you like it, then I will do PR.

**Comment by vendethiel** [comment]
Reminescent of Groovy's spread operator, which was proposed in #112 quite a long while ago, and bumped a year ago without much more happening.

FWIW, even if it were added, I don't think the last case would be supported. It's more akin Perl 6's junctions.

**Comment by connec** [comment]
I guess the implementation of this could be similar to the soak operator (e.g. `a?.b`). I agree that "example 5" shouldn't be supported, in the same way that `a?.b is c?.d` isn't supported.

That said, I'm not sure it adds enough to merit additional syntax... I like that it allows easy 'flat-map' operations and simple `forEach`/`map` operations, but it's strictly less powerful than `for` (e.g. `transform x for x in xs` cannot be represented).

**Comment by vendethiel** [comment]
It theoretically can, albeit using a different syntax (Perl 6 has support for `array>>.&fn`, say), which would make it overkill.

------

There's also the question of whether `a.*b.*c` should return a nested array or a simple one, but consistency seems to indicate the former.

All in all, I don't see much value over `attr = (name) -> (xs) -> xs.map (x) -> x[name]`, then `attr 'friends', users`.

**Comment by MegaUITeam** [comment]
`[*]` instead `*` =) Square brackets will give a programmer to understand that this is an accessor.

**Comment by jashkenas** [comment]
Thanks, but I don't think this is a wise feature to add to CoffeeScript. In a very locked-down language with a strong standard library, and a consistent API to do collection operations over maps, arrays, tuples, and so on — such a "collection operator" might make sense. JavaScript is very, very far from such a language.

**Comment by MegaUITeam** [comment]
@jashkenas The meaning of this operator is not to add a new functionality, but to provide sugar for the already existing one. Is not that the point of Coffeescript?
