### ISSUE TITLE
Proposal: Improve object and array literals

### ISSUE THREAD

**Issue by misanthrop** [jashkenas/coffeescript#4656]
The only annoying thing in CoffeeScript to me is array literals, especially array of objects. They are currently almost like JSON.

The problem is solved in LiveScript, for example

```ls
table =
  * id: 1
    name: 'george'
  * id: 2
    name: 'mike'
  * id: 3
    name: 'donald'
```

compiles to

```js
var table;
table = [
  { id: 1,
    name: 'george' },
  { id: 2,
    name: 'mike' },
  { id: 3,
    name: 'donald' }
];
```

And

```ls
x = 
  * a, b, c
  * d, e
```

compiles to

```js
var x;
x = [[a, b, c], [d, e]];
```

In my opinion it would be great to have a similar functionality in CoffeeScript.

**Comment by vendethiel** [comment]
The probelm is not solved in LiveScript because of the 1-element case that's broken by virtue of `*` being `void =`

**Comment by misanthrop** [comment]
I don't know the advantage of `*` being `void =`.
As for me, it would be better if

```
x =
  * a
```

compiled to `x = [a]`, not `x = a` like in LiveScript.

Looks like it shouldn't cause any problems, but maybe I missed something.

**Comment by sa-0001** [comment]
The following works:

```
items = Array
  a: 'b'

items = Array
  a: 'b'
,
  c: 'd'
```

However it can be a bit funny when there is a variable somewhere in among the object literals; in this case i fallback to []

**Comment by GeoffreyBooth** [comment]
Closing due to lack of support.
