### ISSUE TITLE
Where did extras/coffee-script.js go?

### ISSUE THREAD

**Issue by jsakas** [jashkenas/coffeescript#4677]
I have a legacy project that uses this extras/coffee-script.js file which compiles coffeescript in the browser with requirejs, and the require-cs plugin. 

At some point in the history of coffeescrpt the file disappeared and is also npmignored, so I can't get my legacy project working with the newer versions of coffeescript. So my question is how can I generate this same file with newer versions of coffeescript? Everything seems to require nodejs, where as using this older compiler I can run it standalone in a browser.

**Comment by GeoffreyBooth** [comment]
It’s now in `docs/browser-compiler`:

http://coffeescript.org/v1/browser-compiler/coffee-script.js
http://coffeescript.org/v2/browser-compiler/coffeescript.js

**Comment by jsakas** [comment]
Hi @GeoffreyBooth , thanks for the quick reply! The docs do not come with the npm installed package... is there a way to build this file?

**Comment by GeoffreyBooth** [comment]
`cake build:browser` will build it, but you don’t need to. In Node you can do `require('coffeescript/lib/coffeescript/browser')` to get it. See `package.json`’s `browser` key.
