### ISSUE TITLE
Bracets inconsistencies

### ISSUE THREAD

**Issue by chrapkowski** [jashkenas/coffeescript#4678]
There seem to be a number of inconsistencies how CoffeeScript handles parentheses, not sure if they are bugs or there is a reason behind them.

Let's consider:

    [a 
    ]

is `[a]` 

once:

    [
    a]

is `unexpected newline`

The same for parentheses:

    (a 
    )

is `a` 

once:

    (
    a)

is `unexpected newline`

but:

    (
    a) ->

is `(function(a) {});`

also:

    [
        a
    ]

is fine and gives `[a]` but:

    a[
        b
    ]

is `unexpected indentation`

To me those seem a bit inconsistent and confusing.

**Comment by GeoffreyBooth** [comment]
CoffeeScript is a whitespace and indentation significant language. Imagine there were a JavaScript semicolon where every one of those newlines was. If anything, they should mostly or all throw errors; but the compiler tries to be as forgiving as it can be, probably too forgiving in fact but it's too late now to tighten the rules.
