### ISSUE TITLE
Compiler directives

### ISSUE THREAD

**Issue by TrevorBurnham** [jashkenas/coffeescript#468]
In large projects I inevitably wind up with some files where it would be nice to compile them with `--no-wrap`. Now that `#`-style comments are omitted from JavaScript output, perhaps it would make sense to use a syntax along the lines of

```
# flags: no-wrap
```

for such directives. Or maybe the syntax should be more clearly differentiated from comments aimed at humans, e.g. starting with `#!`.

I would allow this after human-readable comments, but before any expressions. There may be other directives in the future (perhaps a way of including another file, or a flag that adds comments to the output with the line numbers of the original CoffeeScript), but this is the only one that I feel a real need for, and it should be fairly easy to implement (I'd be happy to write the patch myself if there's support for it). Thoughts?

**Comment by GeoffreyBooth** [comment]
Line comments are now output, via #4572. So comment-based directives should now be possible.
