### ISSUE TITLE
[FEATURE] Error type

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4681]
```coffeescript
try func()
catch ApiError error
  alert(error)
```

compile to
```javascript
try{ 
 func() 
} catch(error) {
  if(!(error instanceof ApiError)) throw error;
  alert(error)
}
```

Perhaps it adds a new semantics, and goes beyond "just sugar", and we should not realize this.
On the other hand it is quite convenient sugar.

**Comment by GeoffreyBooth** [comment]
We’re not adding static types or type checking to CoffeeScript. #4563, #2576, #2551, #1852, #116. Please search the closed issues before opening new ones.

**Comment by GeoffreyBooth** [comment]
Also: http://coffeescript.org/v2/#type-annotations

**Comment by MegaUITeam** [comment]
IS NOT TYPE CHEKING!11111111111111111
