### ISSUE TITLE
Proposal: Elision

### ISSUE THREAD

**Issue by danielbayley** [jashkenas/coffeescript#4684]
Following on from #3972 (and this [comment] in particular)…

Should we not align with ES6 and implement _elision_?

~~~ js
const [,,c] = [1,2,3];
console.log(c) // 3
~~~

~~~ coffee
[,,c] = [1,2,3]
console.log c # Error
~~~

[comment]: https://github.com/jashkenas/coffeescript/issues/3972#issuecomment-98233763

**Comment by jashkenas** [comment]
Yes, as soon as we compile into ES6 destructuring, we should allow it.

(Distasteful as it may be)

**Comment by GeoffreyBooth** [comment]
[We already are for arrays.](http://coffeescript.org/v2/#try:%5Ba%2Cb%2Cc%5D%20%3D%20%5B1%2C2%2C3%5D)

**Comment by vendethiel** [comment]
@GeoffreyBooth It's about elision, so `[,,thing]`

**Comment by GeoffreyBooth** [comment]
Yes. We don’t currently support elision (for anything) but as of 2.0.0-beta5 we output into ES syntax for array destructuring; and into ES2015 (fallback) syntax for object destructuring, until object destructuring reaches Stage 4 in ES2017 or ES2018.

So to support elision, we could support it for array destructuring now and output like the example above; but for object destructuring, if that even makes sense for elision, we would need to output into Stage 4-compatible syntax like how object destructuring is output now.

**Comment by danielbayley** [comment]
> (Distasteful as it may be)

😄 I think this is one of those problems to which there is no real stand-out/elegant solution. If you just give the unused params a name that will throw linter errors when [as you ideally would be] checking for unused variables in general.

It does feel more elegant to me than other suggestions Iv'e seen… and of much more use than say, trailing commas in arrays.

Also, I wonder if this should be a thing with function parameters? (for consistency)
~~~ coffee
fn = (,,c) => console.log c
fn 1,2,3 # 3
~~~

**Comment by connec** [comment]
Don't forget that 'expansions' are a thing in CS:

```coffee
[..., c] = [1, 2, 3]
((..., c) -> c) 1, 2, 3
```

**Comment by jashkenas** [comment]
Trailing commas in arrays are a good example of why elisions are kinda stinky, syntax-wise.

Because if: `[,b,] = [1,2,3]` destructures a three-element array ... then `[1,2,].length` ought to equal `3`. But it doesn't.

**Comment by GeoffreyBooth** [comment]
> Because if: `[,b,] = [1,2,3]` destructures a three-element array … then `[1,2,].length` ought to equal `3`. But it doesn’t. 

But destructuring and literal syntaxes aren’t equivalent. `{ x } = obj` is not `obj = { x }`. Your `[1,2,].length` is a literal syntax.

Besides, is this something we need to worry about? We can just compile more or less one-to-one with ES, and let the runtime handle it however the ES committee has decided these cases should go.

**Comment by jashkenas** [comment]
> Besides, is this something we need to worry about?

It's not. We should support elision. I'm just grumbling a little.

**Comment by danielbayley** [comment]
> if: `[,b,] = [1,2,3]` destructures a three-element array

The trailing comma here is entirely superfluous though, so not sure why anyone would actually write that? Elision is only useful for _skipping_ arguments… to discard the rest one just ends the destructuring early.

> `[1,2,].length` ought to equal `3`

Not sure I agree here… to me `2` is correct as this reads as having only 2 actual items. Although having said that; `[1,2,undefined].length` is `3`…

Maybe trailing commas are the 'bad part' here as opposed to elision.

**Comment by danielbayley** [comment]
> Don't forget that 'expansions' are a thing in CS:
> ~~~ coffee
> [..., c] = [1, 2, 3]
> ((..., c) -> c) 1, 2, 3
> ~~~

@connec A fine thing! But not so handy when you want to do:
~~~ coffee
[,second,,fourth] = [1,2,3,4] # Don't need 1 or 3
~~~

**Comment by GeoffreyBooth** [comment]
> @connec A fine thing! But not so handy when you want to do:
> ~~~ coffee
> [,second,,fourth] = [1,2,3,4] # Don’t need 1 or 3
> ~~~

Yes, but I think @connec’s point is that how common is the case where you don’t want the first or last? Because the old-fashioned:

```coffee
elements = [1,2,3,4]
second = elements[1]
fourth = elements[3]
```
Can always work for those edge cases. I get that the whole point of elision is that it’s a convenience shorthand, that it doesn’t add anything we can’t do already, but I guess that question is how much more useful is it than simple expansion? How common are the cases that elision would help with that expansion doesn’t already cover?

**Comment by danielbayley** [comment]
@GeoffreyBooth Sure. Obviously my example was contrived… the main one I keep running into in reality where I think elision would be nice is with `[,stuff,from] = string.match //` which is fairly common (for me anyway).

**Comment by GeoffreyBooth** [comment]
Sure. That's the only use case I can think of either, but it's certainly common. I would be fine with adding this unless it presents other issues.
