### ISSUE TITLE
[CS2] Apply default parametrs by (null and undefined)

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4685]
```coffeescript
# by undefined
func = (step = 10)->

# by undefined and null
func = (step ?= 10)->
```

Generally speaking, the given syntax reminds already available in Coffeescript and by appearance, and by semantics. 

Like:
```coffeescript
prop ?= 200
```

For example, I get data from the server by json, and all undefined values will be replaced with null. and now I have to write something like:
```coffeescript
func = (step)->
  step ?= 10
  # code
```

instead of
```coffeescript
func = (step ?= 10)->
  # code
```

**Comment by GeoffreyBooth** [comment]
That’s already been suggested, discussed, and rejected:

- https://github.com/jashkenas/coffeescript/issues/4225#issuecomment-294097844
- https://github.com/jashkenas/coffeescript/pull/4311#issuecomment-255343318
- https://github.com/coffeescript6/discuss/issues/51#issuecomment-263147824

You’ll just have to use `?=` in the function body.

**Comment by MegaUITeam** [comment]
@GeoffreyBooth Once again, your team takes the wrong and stupid decision. Someday I'll fork coffeescript and make a normal language. As when I influenced you and made you do CoffeeScript 2. So now, you just do not listen to me, although I'm right again. bye
