### ISSUE TITLE
Bug: Nodes: Comments in JSX end up in text nodes

### ISSUE THREAD

**Issue by jaredp** [jashkenas/coffeescript#4686]
```cjsx
<div>
   {
      # a useful comment
      <div />
   }
</div>

<div>
  <div anAttr={
    # a useful comment
    "value"
  } />
</div>
```
emits
```jsx
<div>
   // a useful comment
   <div />
</div>;

<div>
  // a useful comment
  <div anAttr={"value"} />
</div>;
```

These line comments are not in curly braces, so JSX/babel treats them as text, not comments, and we see 
```
a useful comment
a useful comment
```
 on screen in the browser.

Coffeescript2 should instead be generating

```jsx
<div>
   {
      // a useful comment
      <div />
   }
</div>;

<div>
  <div anAttr={
    // a useful comment
    "value"
  } />
</div>;
```

**Comment by GeoffreyBooth** [comment]
Do you mind splitting this into two issues?

As a workaround for now, I suggest you format your comments as their own interpolations, like this:

```jsx
<div>
  {### a useful comment ###}
  <div />
</div>
```

FYI our target output is JSX, that’s parseable by Babel. We may not support all syntax of the former CJSX.

**Comment by GeoffreyBooth** [comment]
I’m going to treat this issue as concerning the comments. For the indentation, please open another issue.

I think indentation needs to be looked at in more depth. This, for example, compiles:

```coffee
<div>
  {
    ###
    multiline comment
    ###}
  <ATag />
</div>
```
And all I did was move the closing brace onto the end of the previous line. I’m not sure how significant indentation is handled within these JSX interpolation blocks; but presumably we could be handling it better.

**Comment by jaredp** [comment]
Split out the multiline comment issue into https://github.com/jashkenas/coffeescript/issues/4692

**Comment by GeoffreyBooth** [comment]
Thanks. Please let me know if #4689 fixes this issue for you.
