### ISSUE TITLE
Proposal: syntactic sugar for repeating strings.

### ISSUE THREAD

**Issue by fa7ad** [jashkenas/coffeescript#4691]
Not a very complex thing to do (I assume).

JS already does concatenation using an arithmetic operator (`+`).
If we use + for concat, why not use * for repeat?
In my mind, this seems logical.
```coffee
hi = "hi!" * 3
```
AFAIK, the translation shouldn't be too hard to do.
The statement above would translate to
```js
var hi;
hi = "hi!".repeat(3);
```

**Comment by lydell** [comment]
Closing for the same reason as [`array[-1]` (negative indices like Python)](https://github.com/jashkenas/coffeescript/wiki/FAQ#static-analysis) won't be done:

Having to compile

```coffee
a * b
```

to

```js
typeof a === "string" && typeof b === "number" ? a.repeat(b) : a * b
```

is a bit heavy.

Also, adding a brand new operator for this seems like to much of a niche use case.

**Comment by vendethiel** [comment]
We don't do literal overloading, and we don't overload operators either.
