### ISSUE TITLE
Lexer documentation typo

### ISSUE THREAD

**Issue by dahn-d** [jashkenas/coffeescript#4694]
hi, the following line doesn't look right in the documentation of the lexer
https://github.com/jashkenas/coffeescript/blob/d172405244b7510f8cf4455ad4483accbac85d1d/docs/v2/annotated-source/lexer.html#L816
![image](https://user-images.githubusercontent.com/6011365/30237713-80272db2-9540-11e7-9e48-20b88fc689a2.png)
i'm not sure what it actually meant to be unfortunately, otherwise would send a pr instead

**Comment by GeoffreyBooth** [comment]
It comes from this: https://github.com/jashkenas/coffeescript/pull/4357#discussion_r88178285

It makes my head hurt. I’m not sure there’s a clearer way to explain it, but if you can think of one, I’m happy to change it.

**Comment by lydell** [comment]
As far as I understand, this issue isn’t about the correctness about the comment, but rather about how the comment looks in the generated documentation (after being interpreted as markdown and converted to HTML)? See that random grey box in the second line of @dahn-d’s comment. I guess we could add some more `` ` ``s to wrap all single-quote strings in there in `<code>` tags, but that would make the comment a lot harder to read in raw source code form where it matters the most.
