### ISSUE TITLE
Proposal: Implement `await*` syntax

### ISSUE THREAD

**Issue by phaux** [jashkenas/coffeescript#4710]
There was once the `await* …` syntax implemented in babel which was basically equivalent to `await Promise.all(…)`

**Comment by vendethiel** [comment]
Why? Is `await Promise.all` too long?

**Comment by phaux** [comment]
I think it's a nice and obvious sugar and it fits CS perfectly

**Comment by connec** [comment]
If something similar were to appear in CS I'd say `await array...` would be a more consistent syntax (but then it's even clearer that it's a trivial substitution).

**Comment by molszanski** [comment]
Might be confusing.

**Comment by GeoffreyBooth** [comment]
There’s also a proposal to allow async generators, and `await*` looks awfully like it should mean that this is a call to an async generator.

**Comment by molszanski** [comment]
@GeoffreyBooth, that was exactly my first thought. 
JS evolution is quick and volatile. Better not to touch anything that can be discarder or somehow throw things into a disarray.

**Comment by phaux** [comment]
Async generators are currently consumed via for-await-of loop

**Comment by GeoffreyBooth** [comment]
Closing due to lack of support.
