### ISSUE TITLE
[CS1] Add postinstall message telling people about module rename, possible upgrade

### ISSUE THREAD

**Issue by GeoffreyBooth** [jashkenas/coffeescript#4714]
We should release a 1.12.8 that has an NPM `postinstall` hook that checks if the module being installed is `coffee-script` (with hyphen), and if so prints this message (feedback welcome) for local installs:

```
CoffeeScript has moved! Please update your package.json from "coffee-script" to "coffeescript".
Also make sure you specify version bounds that you know work for you, such as "^1.12.8" or "1.x".
A breaking change version 2 of CoffeeScript has been released, which you can learn about at
http://coffeescript.org.
```

The `1.12.8` above would be pulled from the version being installed.

This would be the message for global installs:

```
CoffeeScript has moved! The primary NPM module is now "coffeescript", not "coffee-script".
You can run `npm install --global coffeescript` to get the latest version, or run
`npm install --global coffeescript@1` to get the latest 1.x version. Learn more at
http://coffeescript.org.
```

The 1.x versions of CoffeeScript are mirrored on `coffeescript`, so there’s no need to use `coffee-script` anymore.

Again, feedback welcome. One thing to note is that we have _not_ definitively decided that 2.x releases won’t be added to `coffee-script` at some point in the future. We put the 2.x versions only on `coffeescript` in the first place to avoid breaking downstream tools that may not be bounding versions of `coffee-script`, and that might be the way things stay indefinitely; or we may decide at some point in the future that downstream tools have had enough time to adapt and make both module names full mirrors of each other. Let’s not debate that here, as putting 2.x releases on `coffee-script` isn’t something we plan to do anytime soon. I just don’t want the messages above to make claims that block us from revisiting this decision in the future.

**Comment by jashkenas** [comment]
Although a message is a great way to get the attention of folks who are installing `coffee-script` directly — I'm a little worried it's going to piss off folks who only install `coffee-script` through a dependency, and don't care about it directly, and aren't responsible for changing the dependency.

There were 1,230,474 downloads in the past week, but its depended on by 5,367 packages. How many of the downloads came from those?

Is there a better way to get the dependents to move over to `coffeescript` first, before pestering everyone with a message?

I guess the least hassle / most compatible approach would just be to suck it up, document `coffeescript` as the official location, and just maintain `coffee-script` and `coffeescript` as exact mirrors of each other.

**Comment by GeoffreyBooth** [comment]
> How many of the downloads came from those?

Probably the overwhelming majority of them. I guess this message should only appear on direct installs, not installs occurring as a result of `coffee-script` being another module’s dependency—in other words, only for installs that the user has control over (either `npm install` or the user’s project’s `package.json`). I wonder if it’s possible to differentiate between them. If it’s not, I guess we probably shouldn’t print this message.

I think the dependents will sort themselves out. The ones that are still popular will get [PRs](https://github.com/jnordberg/coffeeify/pull/42) or forks to update their dependencies. The ones that aren’t . . .

**Comment by jashkenas** [comment]
> I guess this message should only appear on direct installs, not installs occurring as a result of coffee-script being another module’s dependency

That would be perfect, if it's at all possible.

**Comment by emptist** [comment]
Great! Please don't forget to append a line or two to home page (before Overview)
# to get the latest 1.x version
`npm install --global coffeescript@1`

**Comment by GeoffreyBooth** [comment]
Implemented via #4759.

**Comment by GeoffreyBooth** [comment]
Okay, so in light of #4807 this clearly needs some more thought.

Someone on that thread mentioned `npm deprecate`, and it was discussed in #4759. I wanted to bring it up again, for a few reasons:

- It doesn’t break any builds.
- You can deprecate an entire package, so we could deprecate all of `coffee-script`.
- **It’s reversible.**

The [objection raised](https://github.com/jashkenas/coffeescript/pull/4759#issuecomment-344015710) previously was that we would get lots of people complaining about why we’ve deprecated. But per https://docs.npmjs.com/cli/deprecate, we can specify a deprecation message. Like the example from [here](https://www.triplet.fi/blog/how_node_package_deprecation_works/):

```
npm WARN deprecated gulp-rimraf@0.1.1: Use npmjs.org/del instead, see https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md
```

I think if we write a specific enough deprecation message, that should prevent a flood of complaints. Something like:

```
npm WARN deprecated coffee-script@1.12.9: Use "coffeescript" (no hyphen) instead. CoffeeScript has moved to the "coffeescript" package name on NPM.
```

And if it blows up in our faces, `npm deprecate coffee-script ''` turns it off.

**Comment by GeoffreyBooth** [comment]
Speaking of which, running `npm install` on a fresh checkout of _our_ repo produces [this](https://ci.appveyor.com/project/GeoffreyBooth/coffeescript/build/job/jmojsbt3dib2l26c):

```
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify.
Please update to babel-preset-minify
```

**Comment by GeoffreyBooth** [comment]
@jashkenas @lydell What do you think about trying this tomorrow? Apparently only the package owner can run the command, so I assume that means it needs to be Jeremy.

**Comment by jashkenas** [comment]
Works for me. Just let me know what exactly you'd like me to type.

**Comment by GeoffreyBooth** [comment]
It’s just `npm deprecate coffee-script 'message'`, with whatever you want `message` to be. I think mentioning the “new major version” might be confusing in this context, because someone might think that we’ve deprecated `coffee-script` and the package `coffeescript` has _only_ the new major version. Better to keep it simple and just say we’ve moved. Once they start using the new package name they’ll discover 2.x.

How about:

```bash
npm deprecate coffee-script 'CoffeeScript on NPM has moved to "coffeescript" (no hyphen)'
```

And we can always change it later.

**Comment by jashkenas** [comment]
I've now deprecated `coffee-script` with the message you provided. Please let me know if this causes any trouble.

Hopefully that's the end of the "how to warn people" saga!

**Comment by GeoffreyBooth** [comment]
Thanks! No issues yet...
