### ISSUE TITLE
Proposal: "for i in foo?" checked for loop with a question mark.

### ISSUE THREAD

**Issue by treeform** [jashkenas/coffeescript#4716]
right now 
```coffee
for i in foo?
  bar()
```

produces basically 
```coffee
for i in true
```
or
```coffee
for i in false
```

Which never makes sense, so that syntax is pretty much bad, no one ever wants to iterate a boolean on purpose.

I propose it does a check for existence of foo instead. Then does the loop if there is a foo and does not do a loop if there isn't. Basically a shortcut for this:

```coffee
if foo?
  for i in foo
    bar()
```

**Comment by jashkenas** [comment]
`foo?` is a value — it shouldn't have a special-cased meaning just because you happen to be iterating over it.

Your final example is the much clearer way to write this.
