### ISSUE TITLE
Proposal: indented argument list for function call

### ISSUE THREAD

**Issue by misanthrop** [jashkenas/coffeescript#4722]
Currently the code
```coffee
fn
  x
  y
  z
```
causes compilation error:
```
[stdin]:2:1: error: unexpected indentation
  x
^^
```

Is there any problem to compile this code to `fn(x,y,z)`?

For example,

```coffee
fn 0,
  x
  y
  z
```

Compiles to `fn(0, x, y, z)`

**Comment by vendethiel** [comment]
See https://github.com/jashkenas/coffeescript/issues/4297#issuecomment-242659507
