### ISSUE TITLE
Function overrides variable in global scope

### ISSUE THREAD

**Issue by vlad1777d** [jashkenas/coffeescript#4723]
Hello.

**Problem.**
If variable with some name was declared in global scope of ".coffee" file, and variable with the same name was declared in some function, than fuction will override variable in global scope.

_It's takes vary much time to look over all large script and find: are in global and local scopes variables with the same name, or no. And so in all scripts. If I'll forget to do it - receive errors._

In such case all is well:
```coffeescript
p = 0
text = (y) ->
  x = 10
  x + y
console.log p # 0
test(0)
console.log x # 10
```

It produces such output:
```javascript
var p, text;

p = 0;

text = function(y) {
  var x;
  x = 10;
  return x + y;
};

console.log(p); // 0

test(0);

console.log(x); // 10
```

But in such case when function will be launched, it'll override global variable "x":
```coffeescript
x = 0
text = (y) ->
  x = 10
  x + y
console.log x # 0
test(0)
console.log x # 10
```

Output:
```javascript
var text, x;

x = 0;

text = function(y) {
  x = 10;
  return x + y;
};

console.log(x); // 0

test(0);

console.log(x); // 10
```

And there's no way to do it correctly.

**Possible decision.**
To make similar, as in Python. After compiling Coffeescript to Javascript, all variables inside of function must be declared with "var" statement 
_(not depending on: are variables with such name already were present in global scope, or no)_.

Best regards,
Vladislav

**Comment by vendethiel** [comment]
Hi,

That decision has been taken a long time ago, the ship's sailed a long time ago.

**Comment by GeoffreyBooth** [comment]
There are many structures now that make this less of an issue. Define your functions as methods in a class, or as modules that get imported. There should be much less of a need nowadays to define variables “one level up” of a scope.

**Comment by vlad1777d** [comment]
@vendethiel , Thanks for answer.
But, maybe, it would be better to correct it?
Than there'll be no need in finding workarounds. And such behavior, which has no user case, will be forgotten.

@GeoffreyBooth , thank you. I think so too =)

**Comment by GeoffreyBooth** [comment]
@vlad1777d Unfortunately it’s a backward-compatibility issue at this point. When CoffeeScript 2 was designed, we discussed changing scope to be block-scoped (like ES2015 `let`) rather than function scoped (`var`) but decided against making the change because it would break too much existing code. There’s a lot of CoffeeScript code out in the world, and we have to preserve backward compatibility for it if we can. Now that `let` exists, we probably would choose block scoping if we were making the decision today and didn’t have backward compatibility to worry about, but that’s not the state we’re in. And it’s becoming less of an issue as classes and modules become more commonly used.

You can also try https://github.com/pwlmaciejewski/coffeelint-variable-scope, that might help you catch these errors.

**Comment by vlad1777d** [comment]
@GeoffreyBooth , thank you for the detailed answer. I understood.
_I still have a little doubt that we're talking about same things, because it changes global variable only in case when it exists. Otherwise it uses "var" keyword and all is well. It looks like more an error, than expected behavior._

Anyway, is it difficult to write a patch for it ? 
I'd like to make one for myself, if it's not difficult.
_(I had some experience with Genie scanner/parser, but I spend near week to read it's code, so I don't want to spend it again for CoffeeScript, if it's difficult)_
Because I had issue with it, which I found a lot of time, than I saw on forum message about this issue.

**Comment by GeoffreyBooth** [comment]
What you’re calling global variables are really just variables declared in a higher scope. They’re not supposed to be redeclared in inner scopes. Doing so would introduce a breaking change. Most of the time when people use the same variable name twice in the same section of code, they mean to refer to the same variable, not create a new variable with an identical name.

So sorry, this can’t be changed without breaking backward compatibility.

**Comment by vlad1777d** [comment]
@GeoffreyBooth , you understood me wrongly.
I mean, maybe you know, would it be easy to add "expected behavior", which I wrote in first post, to my own copy of coffeescript compiler ?
If easy, could you point me to line or file, from where to search for it ?

Thanks.

**Comment by GeoffreyBooth** [comment]
What you’re looking for is in `src/scope.litcoffee`.
