### ISSUE TITLE
what if I want to use CoffeeScript 2 in liftoff

### ISSUE THREAD

**Issue by jiyinyiyong** [jashkenas/coffeescript#4726]
js-liftoff is using a very old version of `coffee-script`. And Webpack relies on it.
https://github.com/js-cli/js-liftoff/blob/master/package.json#L27

How to change to `coffeescript` 2?

**Comment by GeoffreyBooth** [comment]
Please open a PR with that project.

**Comment by jiyinyiyong** [comment]
Well. Seems you already did that. https://github.com/js-cli/js-interpret/pull/45
