### ISSUE TITLE
Version 99.999.9999 and 99.999.99999 still in NPM

### ISSUE THREAD

**Issue by rwky** [jashkenas/coffeescript#4732]
Running `npm show coffeescript` returns 
```
  versions: 
   [ '0.7.0',
     '0.7.1',
   ....
     '2.0.0',
     '2.0.1',
     '99.999.9999',
     '99.999.99999' ]
```
It would be good if the 99.x ones can be removed since they're cropping up when I run npm outdated

**Comment by GeoffreyBooth** [comment]
I’ve asked NPM if they can remove them.

**Comment by GeoffreyBooth** [comment]
NPM support responds:

> I’ve spoken with our executive team about this, and I’m afraid we’ll be unable to unpublish those two versions.
> 
> Ideally, the registry should be as immutable as possible. Meaning, if a user can access something today, they should be able to access it a week, month, year…from today. We understand that accidents happen, so we’ve allowed a 24 hour window for users to unpublish packages they’ve just created. Beyond that, unless in extreme cases, we’ll prefer a deprecation path.
> 
> I’d recommend changing the deprecation message to encourage users to update to the latest version.

In a previous message they had recommended running `npm deprecate`, which I’ve done.

So I guess that’s it. If you’d like to try to persuade them, they’re at support@npmjs.com.
