### ISSUE TITLE
ideas for static type checking

### ISSUE THREAD

**Issue by sbimikesmullin** [jashkenas/coffeescript#4735]
Re:
> If you know of another way to achieve static type checking with CoffeeScript, please create an issue and let us know.

BTW Great job on CoffeeScript 2.

IMO if we could type it like this:

```
type Obj
  num: number

fn = (str: string, obj: Obj): string ->
  str + obj.num
```

and get this output:

```js
// @flow
var fn;

/*::
type Obj = {
  num: number,
};
*/
fn = function(str/*: string */, obj/*: Obj */)/*: string */ {
  return str + obj.num;
};
```

Then I could use my beloved CoffeeScript again.

Well, that and VSCode or some IDE support for click-through to definition.

Have been forced to write in one of plain ES6 JS, TypeScript, or Haxe by my team. They say CoffeeScript is unreadable, and the lack of IDE support was a show stopper. So tragic 💔

**Comment by GeoffreyBooth** [comment]
`str: string` already means “implicit object,” e.g. `{str: string}`

But more broadly, we’re not looking for syntax suggestions. The plan isn’t to add static type checking into the compiler. The invitation in the docs was just to let us know if there are any other ways to achieve type checking using existing technologies, like the example with Flow. If there are, we’ll add more examples to the docs.
