### ISSUE TITLE
Support babel-register

### ISSUE THREAD

**Issue by stevefan1999** [jashkenas/coffeescript#4738]
It sounds crazy but it is still sensible to go without `babel-core`.
```js
require('babel-register')({
  presets: ['env'],
  plugins: ['transform-decorators-legacy']
})

require('coffeescript/register')
// require('**.coffee') is not handled by babel-register
```
I know `require('babel-register')` is only a require file hook that couldn't really do much...I have occupied the .babelrc for my SSR client and it's insensible to change that.

**Comment by GeoffreyBooth** [comment]
You can `require` .coffee files and have them transpiled by Babel since #4728. It will be in the next release.
