### ISSUE TITLE
Recommendation on Linter?

### ISSUE THREAD

**Issue by stevefan1999** [jashkenas/coffeescript#4739]
Since CS has been dead so long —— and so none of the CS linters (not even CoffeeLint) supported the latest features of CS2, namely JSX and import/export declaration.

**Comment by vendethiel** [comment]
This is the second time you post a comment here with this attitude. I don't think it is necessary to be so condescending.

**Comment by stevefan1999** [comment]
@vendethiel Whoa...I don't mean to be rude but really am I? I just want to see if anybody has a working linter and all of a sudden I was accused of being verbally strong...

**Comment by stevefan1999** [comment]
Turns out I misconfigured my upstream [CoffeeLint](https://github.com/clutchski/coffeelint) package version and config...Now it works. Partially, JSX is still not working, judging from https://github.com/clutchski/coffeelint/issues/619, I've also ran over that issue.

And I won't beg for more, that's definitely precious and satisfactory to me. I'm closing this issue as I redirect my linter-of-interest to CoffeeLint.

Be remember CoffeeLint v2 has only been released a week ago, so it is still broken ATM.

**Comment by aminland** [comment]
I was in the same boat, so I made a fork of coffeelint that fixes the many issues. They don't seem to be accepting prs for coffeelint, so I published here: https://www.npmjs.com/package/@fellow/coffeelint2

Recommended tooling is with ESlint, using this plugin I made: https://www.npmjs.com/package/@fellow/eslint-plugin-coffee
