### ISSUE TITLE
Reviving the Ecosystem

### ISSUE THREAD

**Issue by stevefan1999** [jashkenas/coffeescript#4740]
I would pluck two directions first.

For me, a `coffee-standard` would also be interesting: https://github.com/standard/standard

https://github.com/uhub/awesome-coffeescript should be rewritten——like https://github.com/sorrycc/awesome-javascript. Compared to the cleanliness and elegant of `awesome-javascript`, it could really scare newbies off with all those word pasta in `awesome-coffeescript`. but `awesome-coffeescript` was maintained by external community users so this is almost impossible.

I know reviving CS will be a great challenge, since ES2015+ has been successfully established for long. People are too lazy and conservative to change their pedantic mind, I know.

Anything more should be done you could add below in the comments.

**Comment by GeoffreyBooth** [comment]
Sounds like a great project for you to take on!

Closing as this isn’t an issue with the `coffeescript` repo.
