### ISSUE TITLE
Import statement should be first in JS file

### ISSUE THREAD

**Issue by minshawcopy** [jashkenas/coffeescript#4741]
I'm learning CoffeeScript. My browser supports ES2015 modules and this is a private project so I'm trying those out. But this CS code:

```
import * as app from 'view/app'

main = ->
	app = new App
	app.run()

```
produces this JS code:

```
// Generated by CoffeeScript 2.0.1
var main;

import * as app from 'view/app';

main = function() {
  app = new App;
  return app.run();
};

//# sourceMappingURL=laclient.js.map
```

Both Opera and Firefox complain that the import statement is in the wrong place. It should be on the first line of the generated file, before the var statement. Am I doing something wrong or is this a bug?

**Comment by lydell** [comment]
No, the `import` statements do not have to be the very first thing in a module. They are hoisted to the top like function declarations. I tried the following example in both Firefox 57 and Chrome 61, and it worked just fine.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Modules test</title>
  </head>
  <body>
    <p>This page should have an orange background.</p>
    <script type="module">
      var color = 'orange';

      import setBackgroundColor from "./index.js";

      setBackgroundColor(color);
    </script>
  </body>
</html>
```
```js
// index.js
export default function setBackgroundColor(color) {
  document.body.style.backgroundColor = color;
}
```

Note that in Firefox, you have to enable modules support by flipping `dom.moduleScripts.enabled` in about:config.

You must have run into some other error.

**Comment by minshawcopy** [comment]
Got it. I had to add type="module" to my html script tag. Didn't know that was required. Thanks.
