### ISSUE TITLE
Lexer: Importing some reserved keywords fails

### ISSUE THREAD

**Issue by boris-petrov** [jashkenas/coffeescript#4742]
I'm using Ember.js and since version 2.16 they have a new modules API. There are a bunch of cases where I have to import a CoffeeScript-reserved keyword: `Ember.computed.and` becomes `import { and } from '@ember/object/computed'` for example. There are also cases for `or`, `not`, `on`.

I saw a [pull-request](https://github.com/jashkenas/coffeescript/pull/4347) that is merged and should allow this but this doesn't seem to work in my case. CoffeeScript version 2.0.0. I'm trying the following: `import { and as computedAnd } from '@ember/object/computed'` but it complains about an `unexpected and`. Am I doing something wrong, is this a regression, or what?

**Comment by GeoffreyBooth** [comment]
It appears that _some_ CoffeeScript keywords are allowed, and others aren’t. If you look at that PR, you’ll see it adds tests for `import { unless as bar } from 'lib'`, which works; but `and` doesn’t. So there’s a bug there that needs fixing. @GabrielRatener, do you mind taking a look?

As a workaround for now, just enclose the `import` line in backticks:

```coffee
`import { and as computedAnd } from '@ember/object/computed'`

computedAnd.method()
```

**Comment by GabrielRatener** [comment]
Yeah, I will take a look later today.

**Comment by GabrielRatener** [comment]
@GeoffreyBooth Should the changes go into 1 or 2?

**Comment by GeoffreyBooth** [comment]
Just 2, which is `master` now.
