### ISSUE TITLE
Merge coffee-script and coffeescript projects on npm

### ISSUE THREAD

**Issue by ruslux** [jashkenas/coffeescript#4743]
Some packages (for example, gulp or mocha) need coffee-script/register module for use .coffee files.

**Comment by GeoffreyBooth** [comment]
NPM is immutable: #4732. Please open pull requests with those projects to tell them to use the `coffeescript` module now.

Gulp relies on js-interpret, which has already been updated: #4726

**Comment by ruslux** [comment]
I mean need pump version in package `coffee-script` can solve many problems. Both packages, `coffeescript` and `coffee-script` have same git repo, but most packages depend on `coffee-script` package.
