### ISSUE TITLE
cli --transpile option is not transpile imported files, got syntax error.

### ISSUE THREAD

**Issue by yutaszk** [jashkenas/coffeescript#4745]
This example my-module.coffee is imported from app.coffee,
but running app.coffee with coffee interpriter with --transpile option,
imported modules (in this example, my-module) are not transpiled.

Is anyone there to transpile imported files when running with transpile options?

- - -

app.coffee
```coffee
import myModule from './my-module'

myModule.greet()
```

my-module.coffee
```coffee
greet = => 'Hello'
export default greet
```

.babelrc
```
{
  "plugins": ["transform-es2015-modules-commonjs"]
}
```

To run coffeescfript interpriter with --transpile option.
```
$ coffee --transpile app.coffee
/path/to/app/module.coffee:7
export default greet;
^^^^^^

SyntaxError: Unexpected token export
```

**Comment by GeoffreyBooth** [comment]
Fixed in #4728, will be in next release.
