### ISSUE TITLE
How to produce static getter for a class property?

### ISSUE THREAD

**Issue by chabib** [jashkenas/coffeescript#4746]
Like this
```
class User extends Model {
  static get table () {
    return 'my_users'
  }
}
```

**Comment by GeoffreyBooth** [comment]
We treat getters and setters as a discouraged practice. See http://coffeescript.org/#unsupported-get-set. That said, it’s possible to create a getter for a class using the verbose syntax, and such a getter is automatically available statically:
```coffee
class User extends Model

Object.defineProperty User, 'table', {get: -> 'my_users'}

User.table  # 'my_users'
```

**Comment by chabib** [comment]
Ok, thanks, I'll try it. I appreciate your awesome works on coffeescript.

**Comment by GeoffreyBooth** [comment]
See http://coffeescript.org/#unsupported-get-set and https://github.com/jashkenas/coffeescript/pull/4484.

**Comment by chabib** [comment]
Sorry to bother again, but I cannot produce this
```js
class User extends Model {
  static get dates () {
    return super.dates.concat(['dob'])
  }
}
```
Any idea?

**Comment by chabib** [comment]
Anyway, I still cant implement your previous example, and I end up set it as property like this
```js
```

**Comment by GeoffreyBooth** [comment]
Getters and setters are a [discouraged practice](http://youtu.be/RO1Wnu-xKoY?t=21m22s) in JavaScript. Instead I would advise:

```coffee
class User extends Model
  @getDates: ->
    super.dates.concat ['dob']
```
which becomes:
```js
User = class User extends Model {
  static getDates() {
    return super.dates.concat(['dob']);
  }
};
```
and call it via `User.getDates()` rather than `user.dates`.

**Comment by chabib** [comment]
This is what I use in the end:
```coffee
export default
class User extends Model
  @dates: @getDates()

  @getDates: -> super.dates.concat(['period'])
```
The thing is it is required by framework I use, so I have no other choice.
I hope there will be better interoperability with existing js lib, regardless what practice they use.

**Comment by GeoffreyBooth** [comment]
You can create getters and setters using the verbose syntax, as shown in the docs: http://coffeescript.org/#unsupported-get-set.

```coffee
class Model
  @dates: ['era']
  
class User extends Model
  @getDates: -> super.dates.concat(['period'])

Object.defineProperty User, 'dates',
  get: -> @getDates()
  
alert User.dates # era,period
```

What framework are you using that “requires” getters and setters?

**Comment by chabib** [comment]
Yeah, that works too, thanks.
It is [Adonis Framework](https://github.com/adonisjs/adonis-framework).
