### ISSUE TITLE
Implement shuffle method for arrays

### ISSUE THREAD

**Issue by log69** [jashkenas/coffeescript#4751]
I'm studying CoffeeScript, nice work, thank you for it.

I'd like to inquire if you could implement a "shuffle" method for the arrays just like in Ruby that would randomize the order of their content. I'd find it very useful. I believe it would serve CS's primary goal of efficiency and simpleness.

Possible syntax:
[1,2,3,4,5].shuffle  => [2, 3, 4, 1, 5]

Possible JavaScript solution:
[1,2,3,4,5].sort(function(){return Math.random() - 0.5})

Also it would be nice to do something about the numerical sorting of arrays because the sorting method of JavaScript does alphabetical sorting only by default.

Possible syntax:
[10,2,4,77,8].sortn

Possible JS solution:
[10,2,4,77,8].sort(function(a,b){return a-b})

Or it could be a much more intelligent sort checking the data types in the array.

Thanks.

**Comment by GeoffreyBooth** [comment]
Sorry, we don't add methods to primitives. You're looking for a sugar library, such as Sugar: https://sugarjs.com/docs/#/Array/shuffle

**Comment by log69** [comment]
Well, it's the same work and code increase as if I created my own lib for inclusion. I thought the language's goal was to cut off work wherever it could. I'm sorry to hear that adding more sugar is not possible. Any other option to extend what we can do with arrays?
