### ISSUE TITLE
Invalid JS: super in constructor shouldn’t accept @params

### ISSUE THREAD

**Issue by ruslux** [jashkenas/coffeescript#4752]
This code:
```coffeescript
class A
  constructor: (@name) ->
    alert @name, 'name'
    
class B extends A
  constructor: (@name) ->
    super @name
```
produce wrong code (See class b#super):
```javascript
var A, B, b;

A = class A {
  constructor(name) {
    this.name = name;
    alert(this.name, 'name');
  }

};

B = class B extends A {
  constructor(name) {
    super(this.name);
    this.name = name;
  }

};
```
where `this is not defined`
If I replace `@name` with `name`, like here:
```coffeescript
class A
  constructor: (@name) ->
    alert @name, 'name'
    
class B extends A
  constructor: (@name) ->
    super name
```
will produce:
```javascript
var A, B, b;

A = class A {
  constructor(name1) {
    this.name = name1;
    alert(this.name, 'name');
  }

};

B = class B extends A {
  constructor(name1) {
    super(name);
    this.name = name1;
  }

};
```

**Comment by GeoffreyBooth** [comment]
You can't put `this` before `super`. ES doesn't allow it.

That said, maybe we should throw an error here? @connec?

**Comment by GeoffreyBooth** [comment]
@ruslux You want to rewrite your code like this:
```coffee
class B extends A
  constructor: (name) ->
    super name
    @name = name
```
I think there’s probably no way for the compiler to do this for you. It would just throw an error, and it would be on you to rewrite your code like the above.

**Comment by ruslux** [comment]
@GeoffreyBooth It's real code written coffee 1.x. I have tons code like this. Operator @ in args need for reduce this assign hell. I like coffe, because it helps write code rapidly. I don't need coffee without sugar like this. What next? Braces? Really nice feature from coffee 2 it `await`, but I paid so high price for it: compatability, npm errors. To satisfy your own ambitions you had to fork project, but not to parasitize on it.

**Comment by vendethiel** [comment]
No need to act so dramatically.
The Coffee 2.x motto is "ES6 integration". That means also forbidding what ES6 forbids.

Probably should error out. Does `super((this.name = name, this.name));` work though? (most probably not..)

**Comment by connec** [comment]
Yup, I'd say it's a bug that `super(@)` compiles. I might have a chance to look at this in the next day or so.

We do also have the option of doing some compiler shenanigans to handle `@`-params more transparently through rewriting, i.e. compiling:

```coffee
class B extends A
  constructor: (@name) ->
    super @name
    alert @name
```

to

```js
class B extends A {
  constructor (name) {
    // Rewrite references to `this.name` prior to `super`
    super(name)
    // Use `this.name` as usual afterwards
    alert(this.name)
  }
}
```

There are inconsistencies with this though, such as using `@` in any other way it wouldn't compile, including an attempt to do something like `prop = 'name'; @[prop]`.

**Comment by GeoffreyBooth** [comment]
@connec it sounds like the safest thing to do at least for now would be to throw an error? And then if you find some shenanigans that makes this work, we can follow up with that?
