### ISSUE TITLE
Proposal: arr[i, j] beside arr[i][j] for referencing multidimensional array elements

### ISSUE THREAD

**Issue by psmitt** [jashkenas/coffeescript#4755]
Pros and cons?
IMHO arr[i, j] fits better to the CS philosophy of reducing the pollution of parentheses in the code...
BR, Peter

**Comment by vendethiel** [comment]
To me, it looks like a different construction than a JavaScript array (like a 1D array being represented as a 2D array).

**Comment by stevefan1999** [comment]
we should also do that for multi-dimensional arrays too!

```
arr[i] === arr[i]
mat[i, j] === mat[i][j]
mat[i, j, k] === mat[i][j][k]
mat[i, j, k, l] === mat[i][j][k][l]
...
mat[args...]
```

**Comment by jashkenas** [comment]
There's no need for the shorthand here — it hides what you're really doing, and makes it more obscure to try and read. If you have nested arrays, you can access them through accessors.

I agree with @vendethiel that it appears as though you're using a single linear array as a backing store for a 2d representation.
