### ISSUE TITLE
Incorrect Use of STDOUT in Error Cases

### ISSUE THREAD

**Issue by bdkjones** [jashkenas/coffeescript#4761]
I'm upgrading to CoffeeScript 2.0 and I suppose that I'm not using the new CLI correctly. That's all well and good; I can fix that.

But, I noticed that CoffeeScript is exiting with a `non-zero` exit code but printing error messages to `stdout` instead of `stderr`. For example, this got logged to `stdout` when I misused the CLI:

    EISDIR: illegal operation on a directory, open '/var/folders/r0/zp_00n3s3mn42k6gv2x98hx00000gn/T/CodeKitTempFolder.two4YtHmS7lIANN'

The general rule is that if the program does not run correctly, output goes to `stderr`. The reason it matters is that integrators (I build CoffeeScript support into an app) inspect the exit code to decide WHERE they should look for output (stderr or stdout). If you don't follow the convention, it becomes impossible to reliably get the output in build scripts, apps, etc.

**Comment by GeoffreyBooth** [comment]
That’s a Node error, not a CoffeeScript one. Though it might be CoffeeScript’s fault for piping it to `stdout` somewhere. What command did you type to cause this?

**Comment by bdkjones** [comment]
It's a little complex because I'm not typing these in the Terminal. Rather, I'm using an Apple class called `NSTask` to run a program in BASH. The program I'm running is Node itself, which is why the first argument I pass is the path to the Coffee executable inside my application bundle. I'm telling Node to run Coffee and then the rest of the arguments are those for the Coffee executable. 

The cause of this appears to be passing the *directory* indicated to the `--output` parameter. If I pass, instead, a full path to the filename I want to use for the output file, everything runs fine. For many years, CoffeeScript was the only tool around that would not allow me to specify an output filename (just an output folder, and the filename was automatically set to `[input filename].js`. Because of this, I had CoffeeScript compile files to an intermediate, temporary folder, then moved them into place at their final path (to handle the case where the output file's name was not the same as the input file's name). I had to manually update source maps and other things as well; it was a GIGANTIC headache. 

I am glad to see that V2 now handles `--output` well. It will let me eliminate hundreds of lines of code.

Here are the arguments I passed to Node to produce the issue:

<img width="1170" alt="screen shot 2017-10-28 at 15 54 41" src="https://user-images.githubusercontent.com/926566/32139276-f48dd370-bbf8-11e7-9e31-8ff5583adc78.png">

**Comment by bdkjones** [comment]
My first guess would be possibly the spaces in the path?

**Comment by GeoffreyBooth** [comment]
Can you please find a way to reproduce this via a direct command, rather than wrapped in some other environment? And produce a stack trace for the exceptIon.

**Comment by bdkjones** [comment]
I'll just go ahead and close, as changing my script to use the new CLI filename interface works just fine. That said, I'm about to open a new bug on that feature...
