### ISSUE TITLE
CLI: When compiling a single file where --output specifies a .js filename, the .map file generated by --map should correspond to the output filename

### ISSUE THREAD

**Issue by bdkjones** [jashkenas/coffeescript#4765]
Suppose I have a file `main.coffee` and I use this command to compile it:

    coffeescript --map --output "/path/to/newname.js" --compile "/path/to/main.coffee"

This command works, and generates the following files:

    newname.js
    main.js.map

This is not correct. The source map should be named `newname.js.map`. This is the standard convention followed by every language that uses source maps. It's always `[output filename].[output extension].map`

Even though this bug exists, the maps still work because the `//# sourcemappingurl` comment in `newname.js` is set to `main.js.map`. However, it's very confusing to see the wrong source map name in the Finder and the map file won't show up next to the output file in sorted lists, etc.

**Comment by GeoffreyBooth** [comment]
It’s not _incorrect,_ it’s just not doing what you want it to do 😄  Since `--inline-map` was added, most people tend to just use that. It hasn’t been a priority to update `--map` to follow the “renamed output” functionality added to `--output` when compiling a single file.

I wouldn’t be opposed to a pull request that detected when `--output` is a filename (as opposed to a folder) and has `--map` (if enabled) rename the `.map` file to match. You’ll probably want to start in the `src/command.coffee` file.

**Comment by bdkjones** [comment]
https://sourcemaps.info/spec.html#h.9ppdoan5f016

---- 

Source Map Naming

Optionally, a source map will have the same name as the generated file but with a “.map” extension.  For example, for “page.js” a source map named “page.js.map” would be generated.

**Comment by bdkjones** [comment]
It's also worth pointing out that I know of at least a couple tools that, when they look for an "input" source map to modify, rather than use the `//# sourcemappingurl` path, just look for the correctly-named `.map` file next to the "input" file. 

For example, suppose we wanted to minify the `newname.js` file above. The minifier would want to modify the existing map that CoffeeScript created, and it would look for the existence of `newname.js.map`, fail to find it, and therefore create a new source map that breaks the link back to the original Coffee files.

**Comment by GeoffreyBooth** [comment]
Most tools and build chains these days seem to prefer inline source maps, as they’re simpler to work with (one less file to open) and faster (again, one less file to open). Also if you use CoffeeScript via the Node API, as opposed to a command-line-based approach, you can get both the generated JavaScript and the source map returned to you in an object; and it’s even faster still, as there’s no writing the JS and/or source map to disk.

That’s not to say that you’re wrong or that what you’re proposing isn’t a good idea. Please feel free to submit a pull request. This is an open-source project, and we depend on the generosity of volunteers.

**Comment by bdkjones** [comment]
Yea, I wish I were fluent in CoffeeScript so I could help out. I'm afraid you wouldn't like my attempts at hacking a fix.

**Comment by bdkjones** [comment]
Thanks very much for knocking this one out!
