### ISSUE TITLE
Getters and Setters

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4766]
In class
---

```coffeescript
class Line
  {get} length: -> @getLength()
  {set} length: -> @setLength()
```
1) `{get} length` syntax does not cause ambiguity, cuz objects can not be called
2) Shorter than `Object.defineProperty @, 'length', get: -> @getLength()`
3) In the future, you can enclose all property accessors (which will be invented by the creators of javascript) in curly brackets

```coffeescript
class Line
  {private get} length: -> @getLength()
  {protected set} length: -> @setLength()
```

In object literal
---

```coffeescript
cat = 
  age: 11
  {get} name: -> 'Cat'
```

**Comment by GeoffreyBooth** [comment]
https://github.com/jashkenas/coffeescript/issues/4650#issuecomment-322939837

Please stop opening issues.
