### ISSUE TITLE
Getters anв Setters (NEW DESCUSSION NEW ARGUMENTS NEW VECTOR)

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4767]
I suggest forgetting all the old discussions, and all the old arguments, a new solution has appeared.

In class
---

```coffeescript
class Line
  {get} length: -> @getLength()
  {set} length: -> @setLength()
```
1) `{get} length` syntax does not cause ambiguity, cuz objects can not be called
2) Shorter than `Object.defineProperty @, 'length', get: -> @getLength()`
3) In the future, you can enclose all property accessors (which will be invented by the creators of javascript) in curly brackets

```coffeescript
class Line
  {private get} length: -> @getLength()
  {protected set} length: -> @setLength()
```

In object literal
---

```coffeescript
cat = 
  age: 11
  {get} name: -> 'Cat'
```

**Comment by GeoffreyBooth** [comment]
@MegaUITeam You have opened four issues about this. As I said in https://github.com/jashkenas/coffeescript/issues/4650#issuecomment-322939837, a decision has been made. It is final. We do not plan on supporting the `get`/`set` shorthand syntax, for the reasons discussed in https://github.com/coffeescript6/discuss/issues/17: we consider getters and setters to be an antipattern that CoffeeScript does not intend to encourage with a simplified syntax. You may still create them using the verbose syntax, as explained in http://coffeescript.org/#unsupported-get-set.

You are welcome to fork this repo and add getter and setter shorthand syntax to your own version of CoffeeScript if you wish. Please stop opening issues regarding this.
