### ISSUE TITLE
Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by liminspace** [jashkenas/coffeescript#4770]
I always take error like `Couldn't find preset "env" relative to directory ...` when I try to use `--transpile` option.

What I do:
`sudo apt install nodejs`
`sudo npm i -g npm`
`sudo npm i -g coffeescript`
`sudo npm i -g babel-core`
`sudo npm i -g babel-preset-env`

`nano .babelrc`
```
  {
    "presets": ["env"]
  }
```
`/usr/bin/coffee --compile --transpile my.coffee`

What do I do wrong?

Ubuntu: 14.04
nodejs: 6

**Comment by GeoffreyBooth** [comment]
Babel is telling you it can’t find `babel-preset-env`. Babel prefers to be installed locally, and it looks for its plugins locally. Please refer to the Babel docs for ways to try to run it globally.
