### ISSUE TITLE
V2 translate class has some issue

### ISSUE THREAD

**Issue by kelvinlee** [jashkenas/coffeescript#4771]
CoffeeScript version 2.0.2

App.coffee
```
class App extends React.Component
	constructor: (@props)->
		super props
	render: ->
		return (<div>Div</div>)
```

I use this command `coffee --compile --bare --output src/ src/` got app.js

app.js
```
// Generated by CoffeeScript 2.0.2
var App;
App = class App extends React.Component {
  constructor(props1) {
    super(props); // here is the problem, Is it should be props1?
    this.props = props1;
  }

  render() {
    return <div>Div</div>;
  }

};
```

Is it the `super(props); ` should be props1?

**Comment by vendethiel** [comment]
That changed in 1.9.0 (Jan 2015).

**Comment by GeoffreyBooth** [comment]
Or what you meant to write was `super @props`, which isn't allowed because JavaScript doesn't permit it.

**Comment by kelvinlee** [comment]
@GeoffreyBooth I was wrong, there should not be @
