### ISSUE TITLE
multi-lines template string starting with a newline

### ISSUE THREAD

**Issue by namiwang** [jashkenas/coffeescript#4773]
##### repro

```
a = ->
  `
  <div>
  </div>
  `
```

##### expected

```
var a;

a = function() {
  return <div>
    etch panel
  </div>
  ;
};
```

##### actual

```
var a;

a = function() {
  return 
  <div>
    etch panel
  </div>
  ;
};
```

forgive me if this is indeed the expected result.

**Comment by GeoffreyBooth** [comment]
Backticks mean something else in CoffeeScript. You want `'` or `"`: http://coffeescript.org/#strings

**Comment by GeoffreyBooth** [comment]
Sorry, I was responding to the earlier version of this issue. Regarding your edited version, XML nodes are supported as is in CoffeeScript 2:

```coffee
a = ->
  <div>
    etch panel
  </div>
```
```js
var a;

a = function() {
  return <div>
    etch panel
  </div>;
};
```

**Comment by namiwang** [comment]
Ah clearly I've missed some reading before opening the issue.

Thanks!
