### ISSUE TITLE
Continuous scrolling interrupted at each section of the website in Chrome

### ISSUE THREAD

**Issue by 1j01** [jashkenas/coffeescript#4776]
Middle mouse button auto-scrolling stops at each section when the hash changes, presumably due to the `scrollIntoView` call on `hashchange`.

Scrolling causes changes to the hash, which causes a programmatic scroll, which interferes with scrolling. 

Possible solution: when changing the hash due to scrolling, set a flag, and on `hashchange` don't call `scrollIntoView` if the flag is set, just unset the flag.

**Comment by GeoffreyBooth** [comment]
I can’t reproduce this.

**Comment by 1j01** [comment]
It continues scrolling if you move the mouse by a pixel. I naturally stop moving the mouse when auto scrolling, and unless I move the mouse constantly it causes jank, feels like the page is super laggy.

Chrome 63 on Windows 10

**Comment by 1j01** [comment]
It's so bad, tho...

![it s so bad](https://user-images.githubusercontent.com/3630663/34007629-7bbc308e-e0d0-11e7-8738-e131e5798273.gif)

**Comment by GeoffreyBooth** [comment]
Pull requests are welcome. You can also read the docs at http://devdocs.io/coffeescript/
