### ISSUE TITLE
Can I use node `--experimental-modules` option in coffee?

### ISSUE THREAD

**Issue by euxn23** [jashkenas/coffeescript#4777]
From node v8.5.0, `--experimental-modules` option has come, enable to use `import/export` statements.
In coffeescript@2, using `import/export` statements requires to use `-t` option and babel plugin `transform-es2015-modules-commonjs`.
Can I use ES Modules `import/export` statements without babel, only coffeescript@2?

**Comment by GeoffreyBooth** [comment]
You can pass options to Node via `--nodejs`: http://coffeescript.org/#cli

```bash
coffee --nodejs --experimental-modules input.coffee
```

Though this particular flag doesn’t appear to work with `coffee` at the moment.
