### ISSUE TITLE
Firefox 56 fail when open http://coffeescript.org/

### ISSUE THREAD

**Issue by jkeks** [jashkenas/coffeescript#4778]
open http://coffeescript.org/ , wait some seconds and Firefox will fail.

**Comment by arroadie** [comment]
Only thing I see is
![image](https://user-images.githubusercontent.com/3903371/32626052-053ee71a-c543-11e7-898e-ca5db27992a7.png)

**Comment by GeoffreyBooth** [comment]
That warning is thrown by Google Analytics. It doesn’t affect the CoffeeScript site. “Try CoffeeScript” still works.
