### ISSUE TITLE
Fail when doing "not x in y"

### ISSUE THREAD

**Issue by DiThi** [jashkenas/coffeescript#4779]
We've been bitten by this too many times. Despite using CS instead of Python for 4-5 years already, sometimes we write `not x in y` because that worked in Python and makes sense. In CS it fails silently doing `false in y`.

Ideally, CS should change the priority between `not` and `in` operators. But I understand that change may break some things. As a compromise it should disallow `not x in y`, saying something like:

    Ambiguous expression. Do you mean "(not x) in y" or "x not in y"?

Also for the `of` operator. I wrote `not x of y` yesterday and 4 eyes couldn't spot the problem for a while.

**Comment by GeoffreyBooth** [comment]
It’s not really any more ambiguous than `2 + 3 * 4`. It’s just order of operations/operator precedence. We also can’t change this at this point without it being a breaking change.

This seems like a great case for a linter, however. I suggest you take a look at CoffeeLint, perhaps you can submit a PR to that project to warn or error on `not x in y`.

**Comment by DiThi** [comment]
@GeoffreyBooth @jashkenas  I suggested disallowing this because it's very rare to search for `true` or `false` in an array or object, in that way.

Would you consider this change if I find all examples of `not x in y` and `not x of y` in open source code and turns out all of them are unintended?

@GeoffreyBooth `2 + 3 * 4` is not ambiguous in any language with operator priorities, it comes from math conventions and it's always the same. However `not` and `in` are exclusive of programming languages.

**Comment by jashkenas** [comment]
It's an operator precedence thing. `not` is just `!`. 

It shouldn't have different semantics than `!`, and it should behave the same way as `!x in y` — which you wouldn't expect to work without parentheses.
