### ISSUE TITLE
Provide option to not output '//# sourceURL=' in the inline sourcemaps

### ISSUE THREAD

**Issue by pbgc** [jashkenas/coffeescript#4782]
For example while using coffeescript to develop NativeScript apps ... when doing:

tns debug android/ios 

and trying to use the given url (chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000) to debug the app on chrome dev tools ... the breakpoints don't work ...

The Inline sourcemap include:
//# sourceURL=/Users/pbeck/Development/projects/NativeScript/coffee2/app/home/home-view-model.coffee

With this line the debug fails ... because the files are being used inside the emulator ... so I guess the path will be different ... because if I remove this line .... everything works!
Inline sourcemaps produced by TypeScript don't have this line!

**Comment by GeoffreyBooth** [comment]
I think that line is used by DevTools to know what filename to show in the sidebar. Removing it would be a breaking change.

I would suggest you delete the line as part of your build process. We don’t intend `coffee` to be a replacement for a full-featured build tool like Gulp or Webpack, or even shell commands:

```bash
coffee --inline-map --bare --print ./test.coffee | sed '/^\/\/# sourceURL/ d'
```

**Comment by pbgc** [comment]
I really find that having the full path of the file is wrong ... but ok ... it was just a suggestion (not a bug report).
Thanks.

**Comment by pbgc** [comment]
Imagine if jquery.min.js (or any other lib) had a //# sourceURL= with the FULL path of the file when it was compiled ... the jquery.min.map would not be useful for nothing ...

for a file like: home-view-model.coffee 
The Inline sourcemap should include:
//# sourceURL=home-view-model.coffee

and NOT (like now):

//# sourceURL=/Users/pbeck/Development/projects/NativeScript/coffee2/app/home/home-view-model.coffee

just my 0.001c

**Comment by GeoffreyBooth** [comment]
I think it needs a path because an app could have multiple files with the same name, e.g. `/index.coffee`, `/module/index.coffee` etc.

**Comment by pbgc** [comment]
That doesn't seem logical to me ... multiple files but not on same location ...
Take a look at: https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
where it says:
"sourceURL and displayName in action: Eval and anonymous functions"
and: //# sourceURL=sqrt.coffee
and in the example they give: https://www.thecssninja.com/demo/source_mapping/compile.html

I'm sorry if I'm wrong and I'm taking your time ...

**Comment by VoidVolker** [comment]
My solution using `awk` and `trap` to run cleanup command after watching:
```JSON
"scripts": {
    "cleanup-urls": "for f in src/*.js test/*.js; do awk '!/^\\/\\/# sourceURL/' $f > tmpfile && mv tmpfile $f; done",
    "make": "coffee -c -b -M ./ && npm run cleanup-urls",
    "watch": "trap 'npm run cleanup-urls' SIGINT && coffee -c -b -M -w ./",
}
```
