### ISSUE TITLE
coffeescript.js doesn't show where compiling error happened

### ISSUE THREAD

**Issue by vlad1777d** [jashkenas/coffeescript#4788]
Hello dear friends.

Now if to add coffeescript compiler to web page (it's more easy while development), when in my .coffee files there are errors, it shows in console only line number of coffeescript.js file itself, not my compiler.
So to find exact line I need to go to website and paste my code there.
Video: https://youtu.be/KyJtimodVTA
Video in .zip archive: [coffeescript___no_debug_data.mkv.zip](https://github.com/jashkenas/coffeescript/files/1476652/coffeescript___no_debug_data.mkv.zip)
It would be great to make coffeescript compiler logging to console line number of .coffee file, where error happened.

Best regards,
Vladislav

**Comment by GeoffreyBooth** [comment]
The errors in your video are runtime errors, thrown by the browser’s JavaScript runtime. If there were compilation errors, the compiler _would_ print the line number of the CoffeeScript line that failed to compile. You can see this by typing invalid CoffeeScript into http://coffeescript.org/#try.

Within Node, CoffeeScript patches the built-in `Error.prepareStackTrace` to reference the source `.coffee` files. Unfortunately I don’t think this is possible for a browser runtime environment. In Chrome, for example, `Error.prepareStackTrace` doesn’t exist.

**Comment by vlad1777d** [comment]
@GeoffreyBooth , thank you for response.

But on video there is a SyntaxError, which appears on compiling stage (0m 10s on video).
After this I go to text editor and look to that line, specified in error (line 8), it was empty, and near there were no any lines with error.
Then I paste my code to coffeescript.org to "try coffeescript" section (1m 09s) and see, on which line error was: it was on 318 line.
After I look to text editor and right, it's 318 line (1m 31s)

**Comment by vlad1777d** [comment]
@GeoffreyBooth , hello.

Can you please check video another time, seems that is a compile-time error.
In browser I can't see line with error, on coffeescript.org - can.
