### ISSUE TITLE
Bring more sugar - add is/isnt/and aliases

### ISSUE THREAD

**Issue by Zydnar** [jashkenas/coffeescript#4789]
Sometimes it sounds better to use propper grammar:
```coffeescript
things are bad but not tragic
```
Now it should look like:
```coffeescript
things is bad and not tragic
```

**Comment by jashkenas** [comment]
No thanks.

**Comment by GeoffreyBooth** [comment]
Unfortunately this isn’t possible, as `are` and `but` aren’t currently keywords, so people might be using them as variable names. We can’t make them keywords without introducing a breaking change.

**Comment by Zydnar** [comment]
Seems resonable but then and .then do not colide. Anyway you're the bosses here.

**Comment by GeoffreyBooth** [comment]
Keywords are allowed as method names, in both CoffeeScript and JavaScript. `foo.class` is valid in both.

Your `are` example is currently valid CoffeeScript: http://coffeescript.org/#try:things%20are%20bad%20but%20not%20tragic

So changing the meaning of this would be a breaking change that might break existing code, for example if anyone has variables or functions named `are` or `but`.

**Comment by danschumann** [comment]
Is there ever going to be a breaking change version of coffee script released.. ever?  I would think keeping a list of good ideas that are breaking changes would be nice, for that time when the threshold is reached where moving forward finally trumps avoiding breaking changes.

**Comment by GeoffreyBooth** [comment]
We just released one: http://coffeescript.org/#coffeescript-2

**Comment by danschumann** [comment]
Ah, nice.  I understand the route of making minimal changes, being a widely used library and not wanting to alienate people.

One solution would be a 3rd party library to parse through and apply any aliases first, then run through normal coffee script.
