### ISSUE TITLE
Implement LSP

### ISSUE THREAD

**Issue by brutalcrozt** [jashkenas/coffeescript#4794]
I do like when we have `ide-coffee` on atom listed [here](https://ide.atom.io/).
we do list atom on [example](http://coffeescript.org/#examples) as a hackable text editor built on web technologies. Personally i feel it a contradiction, when we not process the implementation of `ide-coffee`.

When i ask why `ide-coffee` not there, someone point me to [langserver](https://langserver.org/).

**Comment by Arcanemagus** [comment]
Atom's `ide-*` packages are wrappers _around_ language servers, which are a generic tool that _many_ different editors can take advantage of.

**Comment by GeoffreyBooth** [comment]
This sounds like a separate project, not something that becomes part of the CoffeeScript compiler itself.
