### ISSUE TITLE
Heregex comments cannot contain three slashes in a row

### ISSUE THREAD

**Issue by lydell** [jashkenas/coffeescript#4811]
```coffee
///
 # Comment with three slashes: ///
///
```
```
[stdin]:3:1: error: missing ///
///
^^^
```

[Try CoffeeScript link](http://coffeescript.org/#try:%2F%2F%2F%0A%20%23%20Comment%20with%20three%20slashes%3A%20%2F%2F%2F%0A%2F%2F%2F)

This is because the lexing of heregexes does not take comments into account.

**Comment by vendethiel** [comment]
Originated from #4804.
