### ISSUE TITLE
React error: Import in body of module; reorder to top

### ISSUE THREAD

**Issue by ChristerNilsson** [jashkenas/coffeescript#4815]
I have to manually move one line of code after every compilation.

```
// Generated by CoffeeScript 2.0.3
var App, code, div, fix, h1, header, img, p;

import React, {
  Component
} from 'react';

import logo from './logo.svg';

import './App.css';
```
must be changed to 

```
// Generated by CoffeeScript 2.0.3
import React, {
  Component
} from 'react';

import logo from './logo.svg';

import './App.css';

var App, code, div, fix, h1, header, img, p;
```
to avoid this error message from React:

![capture](https://user-images.githubusercontent.com/3437195/33504132-9b14cf0c-d6e6-11e7-8cb2-2eae77cc9805.JPG)

[App.txt](https://github.com/jashkenas/coffeescript/files/1523024/App.txt)

**Comment by lydell** [comment]
Hi!

The messages in your screen shot are not from React. They are from [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/), specifically the [import/first](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md#first) rule.

Both pieces of code are actually equivalent! If you run them, you'll see that both work exactly the same. However, your tooling seems to prevent you from running if the `import/first` rule is not satisfied. It does not make much sense to run the compiled JS from a CoffeeScript program, so I'd recommend not doing that.

**Comment by ChristerNilsson** [comment]
Really hard to tell eslint to stop checking this.
This is the only way I could make it work:

```
###
eslint-disable 
###
```
I tried 
`# eslint-disable
`
but that does not work.

**Comment by lvl99** [comment]
In my case I was doing an async import and used `//eslint-disable-line`:
``` 
async componentWillMount () {
  const { hugeGreenBean }  = await import('bag-o-beans') // eslint-disable-line
}
```

**Comment by quangv** [comment]
Ran into this while using [create-react-coffee-app](https://github.com/quangv/create-react-coffee-app)

Workaround would be to add backticks so the above code would be:

```
`
import React, { Component } from 'react'
`

class App extends Component
  render: ->
    <div>Hello React</div>
```

**Comment by Inve1951** [comment]
While `### eslint-disable ###` fixes this specific issue, there are other linter rules that cause problems. Only feasable workaround for CRA without ejecting i found was to replace their linter config (with an npm task) before building.

**Comment by bichotll** [comment]
For the record:
```
/* eslint-disable import/first */
```

**Comment by bojegowda** [comment]
I recently got this problem .
Import statements must declare before the variable.
//example
import React, { Component } from "react";
import { withRouter } from "react-router-dom";

import { Container, Grid, Card, Button, Form, Icon, Table } from "tabler-react";
var user = xyz.

**Comment by ORESoftware** [comment]
how do I disable eslint?

**Comment by rbabayoff** [comment]
To clarify, you can put the following at the top of .coffee files (worked for me):

```
###
eslint-disable import/first
###
```

Only block level comments work and this will be compiled to:

```
/* eslint-disable import/first */
```

**Comment by Grv-Singh** [comment]
I'm a bit new to this JS library, where should one mention '/* eslint-disable import/first */' ?

**Comment by kayoch1n** [comment]
Is there a way to disable this lint in a project-wide setting? Unfortunately `.eslintignore` doesn't help:-(

**Comment by edemaine** [comment]
@kayoch1n This is not a CoffeeScript question, but rather an eslint question.  See [Configuring ESLint](https://eslint.org/docs/user-guide/configuring/). For example, you can make `.eslintrc.yaml` contain the following:
```yaml
rules:
  import/first: off
```

**Comment by babul101** [comment]
in react  you get this error when you declare a variable in between the imports
So its better to write the code in the last after the final import is done

**Comment by PassyahRaffi** [comment]
this really affects my error

`/* eslint-disable import/first */`

**Comment by blitmap** [comment]
> Hi!
> 
> The messages in your screen shot are not from React. They are from [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/), specifically the [import/first](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md#first) rule.
> 
> Both pieces of code are actually equivalent! If you run them, you'll see that both work exactly the same. However, your tooling seems to prevent you from running if the `import/first` rule is not satisfied. It does not make much sense to run ESLint on the compiled JS from a CoffeeScript program, so I'd recommend not doing that.

With respect, I cannot generate code where the imports are always at the top.  I wish there were a compile option to the `coffee` binary for this.  ESLint is commonly used, and saying not to run it - where in many projects it's a given - doesn't seem like a solution.  I've looked lower on this thread, and disabling the warning for it doesn't feel like a fix either.

Would love more attention on this. :-)

**Comment by GeoffreyBooth** [comment]
> Would love more attention on this. :-)

The `var` line that’s added at the top scope exists because the code in question has variables declared at the top scope. Another solution is to simply not declare any variables at the top scope. For example, instead of this:

```coffee
import React, { Component } from 'react'

class App # Will cause a `var` line at the top of the file
  constructor: ->
```

Do this:

```coffee
import React, { Component } from 'react'

do ->
  class App # Will cause a `var` line at the top of the inline function created by `do ->`
    constructor: -> # Do something
```

Or prepend `export`:

```coffee
import React, { Component } from 'react'

export class App # Will not cause a `var` line
  constructor: -> # Do something
```

There are many ways to avoid the top-scope `var` line; you use the [playground](https://coffeescript.org/#try:import%20React%2C%20%7B%20Component%20%7D%20from%20’react’%0A%0AReact.createComponent(%7B%20foo%3A%20’bar’%20%7D)) to investigate.
