### ISSUE TITLE
compiler feature request: add source filenames as comments into generated js

### ISSUE THREAD

**Issue by ericnewton76** [jashkenas/coffeescript#4829]
Just looking for a helping fix that would've saved me a good bit of time trying to find a stowaway coffee file within my project that was adding a javascript statement that just so happened to take it all down.  Probably by a rogue developer.  Maybe a joke, i dunno.

Would've made it faster to find it by having option on the compiler to include coffee source file information  into the generated js files, which then all get concat together via gulping the coffee... 

```javascript
gulp.src("**/*.coffee")
.pipe(gulp_coffee())
.pipe(concat("app.js"))
.pipe(gulp_if(process.env["CI"]==="true", gulp_uglify()))
.pipe(gulp.dest('dist/'))
```

so that like lib/a.coffee gets output as dist/lib/a.js:
```
// source file: lib/a.coffee

// end of source file: lib/a.coffee
```

concat of project with lib/a.coffee, lib/b.coffee would be:
```
// source file: lib/a.coffee

// end of source file: lib/a.coffee
// source file: lib/b.coffee

// end of source file: lib/b.coffee
```

uglify clearly would zap out the comments

**Comment by GeoffreyBooth** [comment]
You can achieve that with Gulp. There's no reason for the compiler to have this functionality.
