### ISSUE TITLE
The future of coffeescript again

### ISSUE THREAD

**Issue by wdanilo** [jashkenas/coffeescript#4831]
Hi!
I love Coffeescript syntax. It is shorter than JS and it is usable. I can see whats going in my code much better without removing all the parens, semicolons and syntactic garbage as I do when looking at JS code. 

However, everyone i speak to tell that coffeescript gives us nothing more than ES6 does. It is not true - the syntax is enough for me to use it. Of course it lacks typechecking etc, but TypeScript which offers it makes the syntax even worse with its C++ - like template generics, ouch. Coffeescript with TC with syntax ala Haskell would be much better.

Anyway, I want to ask you what do you - users and developers of Coffeescript think in this matter. Do you feel the days of Coffeescript are slowly ending or do you support this porject as hard as possible and do you belive it will be living and being actively developed long from now?

**Comment by GeoffreyBooth** [comment]
The project is active. We just released version 2 a few months ago. CoffeeScript is staying current with ES features. CoffeeScript 2 even supports type checking through Flow: http://coffeescript.org/#type-annotations

It’s great that JavaScript has caught up with CoffeeScript in regard to most features. It’s a good thing that there’s more parity between the two, even if that means that CoffeeScript has fewer advantages over JavaScript. CoffeeScript will always have the advantage of cleaner syntax, and for many people that’s enough.

This was more throughly discussed at the beginning of the CoffeeScript 2 effort. You can read the manifesto that started that here: https://github.com/coffeescript6/discuss/. The issues in that repo, especially the closed ones, include a lot of discussion of CoffeeScript’s future and direction.

**Comment by wdanilo** [comment]
Thanks, im happy to hear that. The only downside is the Flow types syntax, its so ugly, its unusable
