### ISSUE TITLE
Lexer: error: unmatched OUTDENT

### ISSUE THREAD

**Issue by metalim** [jashkenas/coffeescript#4832]
Coffeescript 2.1.0
Do I miss something here? Seems like CSX is interfering. This makes golfing harder.
```coffeescript
a = s.length<len

###
[stdin]:1:14: error: missing />
a = s.length<len
             ^^^
###
```
Inserting space after <, or reverting the order, "fixes" the issue
```coffeescript
a = s.length< len
a = len>s.length
```

**Comment by zdenko** [comment]
http://coffeescript.org/#jsx

> To avoid compiler errors, when using < and > to mean “less than” or “greater than,” you should wrap the operators in spaces to distinguish them from XML tags. So i < len, not i<len. The compiler tries to be forgiving when it can be sure what you intend, but always putting spaces around the “less than” and “greater than” operators will remove ambiguity.

**Comment by metalim** [comment]
Have seen that. IMO, it should treat spacing the same, as with other operators and regex:
```
a+b == a + b
a +b == a(+b)
a/b/g == a / b / g
a /b/g == a(/b/g)
# but
a<b == a <b... #why csx?
```
