### ISSUE TITLE
Proposal: Named Regex

### ISSUE THREAD

**Issue by ndrewtl** [jashkenas/coffeescript#4840]
Hi! I'm an enormous fan of Coffeescript  and love using the language. I wanted to ask if you would consider adding named Regex captures to the language

Ruby currently [supports](https://ruby-doc.org/core-2.2.0/Regexp.html#class-Regexp-label-Capturing) this feature with the syntax `(?<name>) `, like this example from the documentation:
```rb
/(?<vowel>[aeiou]).\k<vowel>.\k<vowel>/.match('ototomy') # => #<MatchData "ototo" vowel:"o">
```

Currently, the `String::match()` and `Regexp::exec()` methods in Coffeescript return `Array` objects, however, given the fact that Arrays in Javascript are also Objects, it would be possible to allow these methods to still return arrays, with the addition of named properties.

I'm not sure if this breaks this "it's just Javascript" paradigm of the Coffeescript we all love, but named captures are a very useful feature and it would be great if they existed!

**Comment by lydell** [comment]
Thanks for the idea, but you'll have to wait for this to land in JS: https://github.com/tc39/proposal-regexp-named-groups. It's in [stage 3](https://github.com/babel/proposals), so it shouldn't be too far away.

**Comment by GeoffreyBooth** [comment]
Actually, you could use it now. CoffeeScript basically passes through regex contents to JavaScript, so the example from the proposal is valid CoffeeScript today:

```coffee
re = /(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})/u
result = re.exec '2015-01-02'
```

With the [Babel plugin](https://github.com/DmitrySoshnikov/babel-plugin-transform-modern-regexp#named-capturing-groups) configured, you should get `result.groups.year` etc. like in their example.

**Comment by ndrewtl** [comment]
Thanks!
