### ISSUE TITLE
const problem, sequelize example

### ISSUE THREAD

**Issue by abalam666** [jashkenas/coffeescript#4841]
Hello,
How can i use the Sequelize Operators with coffeescript ?
http://docs.sequelizejs.com/manual/tutorial/querying.html#combinations

```
const Op = Sequelize.Op;
{
  rank: {
    [Op.or]: {
      [Op.lt]: 1000,
      [Op.eq]: null
    }
  }
}
```

I found the following ugly workaround for now, but is there any official solution for this kind of problem ?

```
    `var s=require('sequelize'); const Op=s.Op; var fails = { [ Op.lt ] : 5 };`
    db.u.findOne
      where:{email, status, verified:0, fails }
```

**Comment by vendethiel** [comment]
You can just remove the const.

**Comment by abalam666** [comment]
No i can't : 

```
    s=require 'sequelize'
    Op=s.Op
    fails = { [ Op.lt ] : 5 }
```

```
error: unexpected [
    fails = { [ Op.lt ] : 5 }
              ^
```

**Comment by vendethiel** [comment]
You should update your coffee version then. You can verify your code works in the "Try CoffeeScript" page on the website.

**Comment by abalam666** [comment]
You are right, i had in my package.json : 
`"coffeescript": "^2.0.0",`
Now with 2.1.1 it works... thank you very much !
