### ISSUE TITLE
Parcel?

### ISSUE THREAD

**Issue by fa7ad** [jashkenas/coffeescript#4842]
Any idea how I can hookup coffee to [Parcel]? I couldn't find any documentation or plugin.

[Parcel]: https://parceljs.org

**Comment by GeoffreyBooth** [comment]
Compile your `.coffee` files to `.js`, then run Parcel. You can use the `coffee` command or a build tool like Gulp to recursively compile across your app tree. Make sure you do lines like `import foo from './foo'`, not `'./foo.coffee'`, as the `'./foo'` will refer to `foo.js` once it’s created.

**Comment by fa7ad** [comment]
Sorry for troubling you guys, I just had to update parcel. they added support for coffee ([PR])

[PR]: https://github.com/parcel-bundler/parcel/pull/118
