### ISSUE TITLE
Nodes: Bad output when assigning to @prop in destructuring assignment with defaults

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#4843]
illustrated [here](http://coffeescript.org/v2/#try:works%20%3D%20%22maybe%22%0A%0Aclass%20A%0A%20%20constructor%3A%20(%7B%40works%20%3D%20%22no%22%7D)%20-%3E%0A%20%20%20%20alert%20%22provided%3A%20%23%7Barguments%5B0%5D.works%7D%2C%20handled%3A%20%23%7B%40works%7D%22%0A%0Anew%20A%20works%3A%20%22yes%22).
input:
```coffee
works = "maybe"
class A
  constructor: ({@works = "no"}) ->
```
current output:
```js
var A, works;

works = "maybe";

A = class A {
  constructor({works1 = "no"}) {
    this.works = works1;
  }

};
```
expected output:
```js
var A, works;

works = "maybe";

A = class A {
  constructor({works: works1 = "no"}) {
    this.works = works1;
  }

};
```

**Comment by aimerald** [comment]
```
some_works = "maybe"
class A
  constructor: ({@works = "no"}) ->
```

```
var A, some_work;

some_work = "maybe";

A = class A {
  constructor({works = "no"}) {
    this.works = works;
    alert(`provided: ${arguments[0].works}, handled: ${this.works}`);
  }

};

new A({
  works: "yes"
});
```
Will not it solve with this?

**Comment by GeoffreyBooth** [comment]
So in other words, `new A({works: 'yup'}).works` should equal `'yup'`, whereas in the current output it equals `'no'`.

@aimerald the reason we can’t use `works` in the arguments is because that variable name might already be claimed in that scope. That’s why @Inve1951 has `works = "maybe"` in his example. The compiler can’t rename variables that the user has named. That’s why `works1` gets generated by the compiler to use in the arguments here. (If `works1` was taken, it would choose `works2`, etc.)

Changing the output to @Inve1951’s expected output would fix this. @zdenko or @connec, either of you mind taking a look?

**Comment by zdenko** [comment]
I don't think you can use `constructor: ({@works = "no"}) ->`, which is actually   
`constructor: ({this.works = "no"}) ->`. The proper destructuring notation in this case should be   
`constructor: ({this: {works = "no"}}) ->`.
This is the same as this example

```coffeescript
class A
  constructor: ({a.works = 'no'}) ->

###
output:
[stdin]:3:26: error: unexpected =
  constructor: ({a.works = 'no'}) ->
                         ^
###
```

This works:

```coffeescript
works = "maybe"
class A
  constructor: ({a: {works = 'no'}}) ->
    @works = works

a = new A {a: {works: 'yes'}}
a.works   # 'yes'
```

If I understand your proposal, this 
```coffeescript
class A
  constructor: ({@works = 'no'}) ->
```

should compile into this:

```javascript
A = class A {
    constructor({this: {works = 'no'}) {
      this.works = works;
    }
  };
```

But even so, you would have to pass a complete object as an argument:    
`a = new A {this: {works: 'yes'}}`

**Comment by zdenko** [comment]
Oops. Disregard my previous comment. 
You're correct.

```coffeescript
works = 'maybe'
class A
  constructor: ({@works = 'no'}) ->
```
Should compile as suggested:
```javascript
A = class A {
  constructor({works: works1 = "no"}) {
    this.works = works1;
  }
};
```
