### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Kern3l** [jashkenas/coffeescript#4844]
Hey! 

Not really an issue. I'm here to thank you for this project! Every time I program in CoffeeScript I feel as if it was a beautiful gift from god, allowing me to express myself clearly and concisely. The `->` notation is a work of beauty. How it stacks with jQuery is marvelous. I spill ideas from my head and it just works. Lack of cruft makes programming more immersive.

As a long time Python programmer, this is for me like a next strep. Even more clear. Even more concise. But, of course, this is "just JavaScript" (-just- not in the normal abomination version), so replacing Python wouldn't be straightforward in non-front-end-web situations. Could you point me where I can learn how to, for example, make IO operations on files, run a web server or issue a shell command? Especially without cruft. This would be awesome!

Thanks!

**Comment by connec** [comment]
> Could you point me where I can learn how to, for example, make IO operations on files, run a web server or issue a shell command?

Sorry if I'm missing something, but these are all libraries available in [Node.js](https://nodejs.org/en/) - namely [fs](https://nodejs.org/api/fs.html), [http](https://nodejs.org/api/http.html)/[http2](https://nodejs.org/api/http2.html)/[https](https://nodejs.org/api/https.html), and [child_process](https://nodejs.org/api/child_process.html) respectively.

**Comment by GeoffreyBooth** [comment]
Thanks for the kind words. Yes, CoffeeScript is just JavaScript, so however you would do those things in JavaScript (in your specific case, generally via Node) is how you’d do them with CoffeeScript. You might want to look through the [Resources](http://coffeescript.org/#resources) section of the docs, there are some books and other longer-form guides there.
