### ISSUE TITLE
CLI doesn't register exec() or spawn() callbacks correctly

### ISSUE THREAD

**Issue by activestylus** [jashkenas/coffeescript#4846]
Problem 1: The CLI doesn't register the normal NodeJS callbacks

``` coffeescript
exec "coffee --compile --transpile -o  #{go.dist} -cw #{path}", (err, stdout, stderr)->
  if err
    console.error err
    throw err

  # None of this is called, even though the task is successful
  console.log "stdout: #{stdout}"
  console.log "stderr: #{stderr}"
```    

Problem 2: The task appears to run twice when defining the exec as a var

``` coffeescript
child = exec "coffee --compile --transpile -o  #{go.dist} -cw #{path}"
child.stderr.on "data", (data) -> console.log data

# The following output is printed twice
child.stdout.on "data", (data) -> console.log data  
```

Am I calling the CLI correctly here, or does Coffeescript simply not jive with node child processes in the normal way?

**Comment by GeoffreyBooth** [comment]
If you’re calling from Node, you probably want to use the [Node API](http://coffeescript.org/#nodejs-usage).

I’m calling `cake` in https://github.com/GeoffreyBooth/coffeescript-gulp/blob/master/gulpfile.coffee and it seems to work just fine, and it’s the same as `coffee`.

**Comment by GeoffreyBooth** [comment]
Your command includes `-cw`, which is shorthand for `--compile --watch`. Since you’re telling the `coffee` process to watch, it never exits, and therefore the callback never fires.

**Comment by activestylus** [comment]
Thanks @GeoffreyBooth! I've managed to fix this bypassing the command entirely and just using the CoffeeScript API directly in my node code. Works a treat!
