### ISSUE TITLE
Missing breaking change: __super__

### ISSUE THREAD

**Issue by mitar** [jashkenas/coffeescript#4858]
With CoffeeScript2, one cannot anymore do:

```
Class.__super__.method
```

to access a `method` definition on the parent class of `Class`. I do not see this documented anywhere.

**Comment by GeoffreyBooth** [comment]
I don’t see `__super__` documented in the V1 docs: http://coffeescript.org/v1/

It looks to me like it was intended for private use by CoffeeScript itself to make `super` calls work. It wasn’t intended as a public API.
