### ISSUE TITLE
Missing breaking change: of does not iterate over all instance properties

### ISSUE THREAD

**Issue by mitar** [jashkenas/coffeescript#4859]
This has bitten me now multiple times as I am porting packages to new CoffeeScript version and can be detected only through tests.

Before I had such code in multiple places:

```coffee
for methodName, methodFunc of @
  # do something with a method
```

This when through all properties on current object and then I could find out which one are functions/methods and do something with them.

Now, the best I found is to do:

```coffee
getAllProperties = (obj) ->
  names = new Set()
  properties = []
  while obj
    for name in Object.getOwnPropertyNames(obj) when name not in names
      properties.push([name, obj[name]])
      names.add(name)
    obj = Object.getPrototypeOf(obj)
  properties

for [methodName, methodFunc] in getAllProperties(@)
  # do something with a method
```

I think this should be documented somewhere.

**Comment by GeoffreyBooth** [comment]
`for…of` didn’t change in CS2. Is the `this` in your example a class?

There’s also `for own key, val of obj` (also not new to CS2) but it looks like you _want_ the prototype methods.

**Comment by mitar** [comment]
No, `this` is an instance of the class. Syntax didn't change, but I think this is a consequence of changing underlying implementation from custom classes to ES6 classes.

Also, this is in node.js.

**Comment by mitar** [comment]
OK, here is an example:

```javascript
class Foo {
  constructor() {
    this.foo = 1;
  }

  method() {
  }
}

class Bar extends Foo {
  constructor() {
    super();
    this.bar = 2;
  }

  list() {
    for (const name in this) {
      console.log(name);
    }
  }
}

function Foo1() {
  this.foo = 1;
}

Foo1.prototype.method = function () {
}

function Bar2() {
  Foo1.call(this);
  this.bar = 2;
}

Bar2.prototype = Object.create(Foo1.prototype);
Bar2.prototype.constructor = Bar2;

Bar2.prototype.list = function () {
  for (const name in this) {
    console.log(name);
  }
};

console.log('New:');
new Bar().list();
console.log('Old:');
new Bar2().list();
```

This outputs for me:

```
New:
foo
bar
Old:
foo
bar
constructor
list
method
```

So, a breaking change. And one hard to catch because there is no syntax error. So if you didn't have a test to exercise this code path you have a bug once you upgrade to CoffeeScript 2.

**Comment by GeoffreyBooth** [comment]
The fact that `class` now compiles into the ES `class` is the biggest breaking change in CoffeeScript 2, and amply documented: http://coffeescript.org/#breaking-changes-classes

We cover many of the differences in the docs, but the docs can’t be an exhaustive reference of all the differences between function prototypes and ES classes. Yes, iterating over the properties of a function prototype behaves differently than iterating over the properties of an ES class. I don’t think that’s necessarily surprising, or something the docs need to point out. See also #4233.

**Comment by mitar** [comment]
So this is my feedback after porting around 20 CoffeeScript packages. This is the only real issue I had which was not captured by syntax/compilation issues. I am not sure about "can’t be an exhaustive reference", but I really think this one is the most surprising and nasty.

**Comment by GeoffreyBooth** [comment]
I’m only speaking for myself, of course, but I’ve never seen the need to iterate over the methods of a class instance. I’m not sure why one would. But who knows, maybe other people are coding much more interesting things than I am. If this is a common use case that I’m just unfamiliar with, sure, let’s mention it in the docs.

I think in general, the docs could say something like this: “If you’re doing things with classes that don’t fit cleanly into the generic ES class example, such as fat-arrow methods or an executable body or working with native-JS properties of the class or its instances, you should port that class by hand and check it carefully.” I feel like the current “Breaking Changes: Classes” section already says that in not so few words, but we could make it more explicit if you think that would help. cc @connec.

But also, you migrated 20 CoffeeScript packages and this was the worst you ran into? That’s awesome!

**Comment by mitar** [comment]
> But also, you migrated 20 CoffeeScript packages and this was the worst you ran into? That’s awesome!

Yes. I have to discover how to port some compilation errors, but once I figured patterns for those out, the rest was a breeze. The main obstacle for me was Meteor bug (https://github.com/meteor/meteor/issues/9528), because I first didn't know it is bug and not me. And this was a big surprise. `__super__` issue was detected also through tests.

There were some `@` being accessed before `super`, but luckily I was able to change those while keeping the intended logic.

Oh, and use of private class-level variables inside class body, but I just moved them out of class definition and it worked.

**Comment by GeoffreyBooth** [comment]
If you would be so kind, I’d love to have links to example projects that use CoffeeScript 2 and have tests, the more the better, so that I have more than just the CoffeeScript repo’s own tests to reassure me that new PRs don’t break things. For example, I’d love to run a project with good passing tests against current 2.1.1 and then against `master` with #4825, to see if it breaks your project’s tests. Projects that do more unusual things, especially things that change in CS2 like classes, would be especially good candidates for this.

**Comment by mitar** [comment]
You can find them here: https://github.com/peerlibrary?language=coffeescript

Not all have been ported, those from `meteor-middleware` up.

Not sure how could they be integrated into your testing suite though.

BTW, thank you for all your work with CoffeeScript!

**Comment by connec** [comment]
> Oh, and use of private class-level variables inside class body, but I just moved them out of class definition and it worked. But these are easy because compiler complains.

Do you mean something other than:

```coffee
class A
  CONSTANT = 1
```

Because that [compiles](http://coffeescript.org/v2/#try:class%20A%0A%20%20CONSTANT%20%3D%201%0A%20%20%0A%20%20foo%3A%20-%3E%0A%20%20%20%20console.log%20CONSTANT) just fine.

**Comment by mitar** [comment]
```coffee
class A
    @value = 1
```

But it seems it also works. It might be that it was something else. I also had some floating `@Foo = class extends Bar`. Pretty ugly code. It ought to be moved out anyway. :-)

**Comment by vendethiel** [comment]
That's not really private, though
