### ISSUE TITLE
In Windows CMD prompt, the coffee command is failing to interpret wildcard (*) correctly.

### ISSUE THREAD

**Issue by skylarjhdownes** [jashkenas/coffeescript#4864]
After poking around it looks like this has been an issue for a while: https://stackoverflow.com/questions/23491814/coffeescript-joining-multiple-files-using-wilcard-not-working

For me, running 
`c:\my-project>coffee -c  *.coffee`
in CMD on Win10 gives the output
`File not found: c:\my-project\*.coffee`

I wasn't able to find any issue documenting this.  My coffeescript version:
```
c:\>coffee -v
CoffeeScript version 1.12.7
```

Hope this is helpful.

**Comment by GeoffreyBooth** [comment]
CoffeeScript relies on your command interpreter to resolve the paths, and it looks like `cmd` does not. Try installing Git for Windows, which includes Bash. Your command should work there.

**Comment by vendethiel** [comment]
Cmd does not do shell expansion.

**Comment by MonsieurMan** [comment]
It doesn't work for me on git `bash`, `powershell` nor `cmd`. Any updates on this ?

**Comment by Inve1951** [comment]
Instead of `*.coffee` pass the containing directory.
In your example `c:\my-project>coffee -c *.coffee` would be `c:\my-project>coffee -c ./`

**Comment by RogerHardiman** [comment]
I also switched to using the containing folder. Thanks to @Inve1951
