### ISSUE TITLE
str.match /regex/ is null outputs wrong code

### ISSUE THREAD

**Issue by falafflepotatoe** [jashkenas/coffeescript#4866]
tldr `str.match /bar/ is null` produces `str.match(/bar/ === null)` for me

    str = '....'
    print str
    console.log str.match /someregex/ is null  #this produces str.match(/somergex/ === null)
    console.log not str.match /someregex/ #works
    console.log not str.match /someregex/ == str.match /someregex/ is null #this prints true somehow
    
    #example:
    if str.match /someregex/ is null
    	console.log('one')
    if not str.match /someregex/
    	console.log('two')
    
    #should output  'one two'
    #outputs: 'two'

**Comment by lydell** [comment]
Yes, that's how CoffeeScript works :) Too late to change now – that'd be a massive breaking change!

Basically all operators have lower precedence than function calls, allowing you to do things like:

```coffee
console.log 1 + 2
```

Here are some things you can do:

```coffee
unless /someregex/.test str
  console.log('one')

unless str.match /someregex/
  console.log('one')

if str.match(/someregex/) is null
  console.log('one')

if (str.match /someregex/) is null
  console.log('one')

if null is str.match /someregex/
  console.log('one')

match = str.match /someregex/
if match
  console.log('match', match)
```
