### ISSUE TITLE
Nodes: Incorrect ‘Can’t call super with @params’ error

### ISSUE THREAD

**Issue by misanthrop** [jashkenas/coffeescript#4868]
```coffee
class A
  constructor: (fn) ->
class B extends A
  constructor: -> super -> @x
```

does not compile:

```
[stdin]:4:28: error: Can't call super with @params in derived class constructors
  constructor: -> super -> @x
                           ^^
```

`@x` is not `this` of the `class B`, but of the function `fn`. The code should compile.

**Comment by GeoffreyBooth** [comment]
It would appear the code that looks for references to `this` inside `super` calls doesn’t respect scope boundaries. @zdenko @connec 

This is a workaround:
```coffee
class B extends A
  constructor: ->
    superArg = -> @x
    super superArg
```

**Comment by vendethiel** [comment]
This is the case I talked about here: https://github.com/jashkenas/coffeescript/pull/4754#issuecomment-338923372
