### ISSUE TITLE
Lexer: Backslash not supported in import or export statements

### ISSUE THREAD

**Issue by eugenet8k** [jashkenas/coffeescript#4874]
This works:
```
import my_module from 'my/path/nodule'
```

This doesn't work:
```
import my_module
  from 'my/path/nodule'
```

```
[stdin]:2:1: error: unexpected indentation
  from 'my/path/nodule'
```

This doesn't work as well:
```
import my_module \
  from 'my/path/nodule'
```

```
[stdin]:1:8: error: unexpected implicit function call
import my_module \
       ^^^^^^^^^
```

As a result, there is no way to wrap long imports into few lines.

**Comment by eugenet8k** [comment]
The only workaround I could found is to use backticks. This works:

```
`import my_module
  from 'my/path/nodule'`
```

**Comment by GeoffreyBooth** [comment]
The first “doesn’t work” example isn’t really a bug; CoffeeScript is a significant-whitespace language, so in the absence of something that implies that a statement should continue onto the next line, a line return is treated as the end of a statement. The second example, however, _should_ work; the backslash there should allow a line continuation.

@zdenko, this looks to be a sibling to #4861? Could we generalize that fix to all of the `seen*` flags in the lexer?

**Comment by zdenko** [comment]
@GeoffreyBooth, yes it looks very much like #4861. 
I'll take a look into this later this weekend and try to come up with a robust solution which would also cover other similar cases.
