### ISSUE TITLE
Nodes: Compile error when using destructuring with a splat or expansion in an array

### ISSUE THREAD

**Issue by MattKunze** [jashkenas/coffeescript#4878]
```coffee
foo = (list) ->
  [ first, ..., last ] = list
```

results in `TypeError: Cannot read property 'indexOf' of undefined`

That’s the simplest case I could come up with. It’s pretty finicky though, if you reference the values after the destructuring statement it compiles:

```coffee
foo = (list) ->
  [ first, ..., last ] = list
  [ first, last ]
```

However other more complex variations also fail, for instance having that statement inside conditional assignment:

```coffee
foo = (list) ->
  ret =
    if list.length
      [ first, ..., last ] = list
      [ first, last ]
    else
      []
```

removing the `ret = ` part of the last example compiles fine

Not a huge deal, it can be replaced with code that explicitly uses `list.slice -1`, it’s just we had some code that was compiling previously and stopped working with a minor update somewhere along the way

**Comment by GeoffreyBooth** [comment]
Probably due to #4825 @zdenko

**Comment by GeoffreyBooth** [comment]
This is also broken:

```coffee
foo = (list) ->
  [ first..., last ] = list
```
