### ISSUE TITLE
Bug: 2.2.0 breaks range generation

### ISSUE THREAD

**Issue by IlyaSkriblovsky** [jashkenas/coffeescript#4886]
CoffeeScript 2.2.0 seems to break range expressions when range is big enough to be generated with for-loop:

`[1..100]`

compiles into:

```
(function() {
  var results = [];
  for (i = 1; i <= 100; i++){ results.push(i); }
  return results;
}).apply(this);
```

(proof: http://coffeescript.org/#try:%5B1..100%5D)

Notice there is no `var` or `let` before `i = 5`, so this code is failing to run in strict mode.

**Comment by vendethiel** [comment]
Fixed in #4883. We'll publish 2.2.1 soon.
