### ISSUE TITLE
Issue with npm registry when resolving 1.12.8

### ISSUE THREAD

**Issue by ftdube** [jashkenas/coffeescript#4890]
Since yesterday, I've been having issues fetching my dependencies from npm.  Some of my dependencies have coffee-script@^1.10.0 as a dependency.  When trying to fetch this, it is resolved as 1.12.8, which is currently unavailable on the npm registry.  Because of this, my attempts to install my dependencies fail systematically.

**Comment by GeoffreyBooth** [comment]
1.12.8 is unpublished. It was just a deprecation warning, which we no longer need because we deprecated all of `coffee-script`. If you’re having issues resolving dependencies, please file an issue with NPM.
