### ISSUE TITLE
ES2015 sets comprehension support

### ISSUE THREAD

**Issue by laurentpayot** [jashkenas/coffeescript#4892]
I'm using [ES2015 Set type](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) to store lists of unique elements. I was surprised to see that CS2 does not provide comprehension for them (version 2.2.1):

```coffeescript
coffee> a = [3, 2, 3, 1]
[ 3, 2, 3, 1 ]
coffee> e for e in a
[ 3, 2, 3, 1 ]
coffee> s = new Set([3, 2, 3, 1])
Set { 3, 2, 1 }
coffee> e for e in s
[]
coffee> e for e in s.values()
[]
coffee> e for e in s.keys()
[]
```

**Comment by vendethiel** [comment]
Our `for ... of` for iterators is spelled `for ... from`

```coffeescript
> s = new Set([3, 2, 3, 1])
Set { 3, 2, 1 }
> console.log v for v from s
3
2
1
```

**Comment by laurentpayot** [comment]
D'oh! Thanks @vendethiel :+1:
