### ISSUE TITLE
Could not use coffeescript in html directly

### ISSUE THREAD

**Issue by hyh888** [jashkenas/coffeescript#4894]
Recently, I couldn't find the coffeescript.js file which can be use in html directly. With this file I needn't install nodejs in my PC. But now who can tell me where can I download the coffeescript.js file which can be directly used in html?

**Comment by GeoffreyBooth** [comment]
http://coffeescript.org/v2/browser-compiler/coffeescript.js

**Comment by hyh888** [comment]
thank you very much.
