### ISSUE TITLE
Getters and Setters [I came up with the syntax]

### ISSUE THREAD

**Issue by MegaUITeam** [jashkenas/coffeescript#4895]
```coffeescript
class Cat
  [get] name: -> 'Tom'
  [set] name: (value)-> 
```

The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
Ingeniously and simply. Enjoy!

![image](https://user-images.githubusercontent.com/30184325/36166256-f1c966c2-1102-11e8-96db-4bc207864d15.png)

![image](https://user-images.githubusercontent.com/30184325/36166261-f62b608a-1102-11e8-9e32-9d5f5427b404.png)

**Comment by GeoffreyBooth** [comment]
If we were to support this, it would probably be with `get` and `set` as literal keywords. That’s why they were reserved in 2.0.0. It’s not like we just couldn’t think of a workable syntax.

A decision has been made on this. [Getters and setters can be defined using the verbose syntax](http://coffeescript.org/#unsupported-get-set), and that’s all we choose to support for now. The only reason we might revisit this is if someday the shorthand syntax becomes required for compatibility with other JavaScript libraries, but as far as I can tell it’s always equivalent to the verbose syntax.

**Comment by MegaUITeam** [comment]
@GeoffreyBooth 

This is to avoid grammatical ambiguity, since in CoffeeScript such a construct looks identical to a function call (e.g. get(function foo() {})); and because there is an alternate syntax that is slightly more verbose but just as effective:


> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.


> The literal "array" can not be called as a function, this eliminates the ambiguity of the syntax.
===
