### ISSUE TITLE
Lexer: backslash line continuation is inconsistent

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#4898]
<table><tr><td >input</td><td>input</td><td>output</td></tr><tr><td><pre lang="coffee">if ( \
    false \
    or \
    true \
  )
  42</pre></td><td/><td><pre lang="js">[stdin]:1:1: error: unexpected if
if ( \
^^</pre></td></tr><tr><td><pre lang="coffee">if ( \
    false \
    or \
    true \
 )
  42</pre></td><td><pre lang="coffee">if ( \
    false \
    or \
    true \
   )
  42</pre></td><td><pre lang="js">if (false || true) {
  42;
}</pre></td></tr><tr><td><pre lang="coffee">if ( \
    false \
    or \
    true \
)
  42</pre></td><td/><td><pre lang="js">[stdin]:4:10: error: unexpected \
    true \
         ^</pre></td></tr><tr><td><pre lang="coffee">if ( 
    false
    or
    true
  )
  42</pre></td><td/><td><pre lang="js">[stdin]:3:5: error: unexpected or
    or
    ^^</pre></td></tr><tr><td><pre lang="coffee">if ( 
    false \
    or
    true
  )
  42</pre></td><td><pre lang="coffee">if ( 
    false or
    true
  )
  42</pre></td><td><pre lang="js">if (false || true) {
  42;
}</pre></td></tr><tr><td><pre lang="coffee">if ( \
    false \
    or
    true \
  ) then 42</pre></td><td><pre lang="coffee">if (
    false \
    or
    true
  ) then 42</pre></td><td><pre lang="js">if (false || true) {
  42;
}</pre></td></tr></table><br>and so forth...

**Comment by GeoffreyBooth** [comment]
@zdenko This is similar to #4874 and related.

**Comment by zdenko** [comment]
Previous backslash issues (#4874 and #3909) were due to preemptive resetting flags for detected `for`, `import` and `export` tags in the `Lexer::lineToken`.

This seems more like whitespace than backslash issue (#995, #3559).
The first example compiles if I add or remove one space before `)`, or if I add one space before `42`.
The third example is similar. If I add a space before `)` it compiles.  
Take this example. Even with the backslash, line indention matters. 
```coffeescript
if \
  false \
  or \
  true 
  42
```

It seem that `Rewriter::tagPostfixConditionals` changes `IF` into `POST_IF` expressions in these cases. I'll take a closer look in a day or two.

I think the fourth example is a syntax error, as logical or relation operators must follow immediately after the expression.

**Comment by Inve1951** [comment]
i might be wrong here but shouldn't the backslash just join two lines together and make it behave as it was all 1 line?
if so then there can't be a whitespace issue.
```coffee
if ( false or true )
  42
```
compiles just fine

**Comment by zdenko** [comment]
You're not wrong, but the thing is that, even with the backslash, `Lexer` parses each line separately (this was also the problem with #4874 and #3909). So, when indent before `42` is parsed and checked with the current indent level (e.g. from `  )`), it's stripped.
I'm onto something with this and will create PR soon.

**Comment by Inve1951** [comment]
The way I see it, those last two patches shouldn't be special cases when using a backslash.
Am I correctly understanding that this new PR provides a general solution to _all issues_ of that sort or do those two still require special treatment (despite using a backslash)?

**Comment by zdenko** [comment]
Last two patches were needed to prevent resetting flags for detected `for`, `import` and `export` tags, which were set to `false` immediately when a newline is detected.
New PR will hopefully provide a general  solution for other cases (e.g. besides the `IF`).    
If you could come up with some test cases that would be very helpful.  

I guess the ideal solution would be stripping backslashes before running code thru `Lexer`, but that would probably require major rework.

**Comment by Inve1951** [comment]
lexer could also first check if the line ends in `\` and strip the newline + whitespace if that's the case.
will look into some tests.

**Comment by Inve1951** [comment]
this shouldn't compile at all i think
<table>
<tr><td>input</td><td>output</td></tr>
<tr><td><pre lang=coffee>
[ \
  b: 1, \
   c: 2
 d: 3
e: 4
]
</pre></td><td><pre lang=js>
[
  { b: 1, c: 2  },
  { d: 3 },
  { e: 4 }
];
</pre></td></tr>
<tr><td><pre lang=coffee>
[
  b: 1, \
   c: 2
 d: 3
e: 4
]
</pre></td><td><pre lang=js>
[
  { b: 1, c: 2 },
  { d: 3, e: 4 }
];
</pre></td></tr>
</table>
