### ISSUE TITLE
Proposal: allow more syntax for spread operator

### ISSUE THREAD

**Issue by gucki** [jashkenas/coffeescript#4987]
This code

    user =
      name: 'Werner Heisenberg'
      occupation: 'theoretical physicist'

    currentUser =
      status: 'Uncertain'
      user...

Fails with

    [stdin]:6:22: error: unexpected newline
      status: 'Uncertain'
                        ^

It works like when using `{}`

    user =
      name: 'Werner Heisenberg'
      occupation: 'theoretical physicist'

    currentUser = {
      status: 'Uncertain'
      user...
    }

Would it be possible to make the `{}` optional in this case?

**Comment by zdenko** [comment]
Check previous proposal #4600 and PR #4618 for it.
