### ISSUE TITLE
Bug: `{default, ...imgprops} = props` doesn't compile

### ISSUE THREAD

**Issue by crisward** [jashkenas/coffeescript#5001]
### Input Code
http://coffeescript.org/#try:%7B%20default%2C%20...imgprops%7D%20%3D%20props

```coffee
{default, ...imgprops} = props
```

### Expected Behavior
I expect it to unpack the object, removing the default property. This worked with typescript but not coffeescript. It does however work if I don't use the default property name.

### Current Behavior
`[stdin]:1:3: error: unexpected default`

### Context
Trying to unpack properties inside a React component. I'd like to copy some properties, but not default. I could do this another way, but this is the neatest and works in typescript, which I am converting from.

### Environment
* CoffeeScript version:2.2.2
* Node.js version:8

**Comment by zdenko** [comment]
The `default` is a reserved keyword in JS.

You can use `default` as a property name ([CS](http://coffeescript.org/#try:o%20%3D%20%0A%20%20default%3A%2042), [JS](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBA9hC8EG8AmBTAZiArgGwC4C4IAWAJgF8AoKoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=&prettier=false&targets=&version=6.26.0&envVersion=), [TS](https://www.typescriptlang.org/play/index.html#src=var%20o%20%3D%20%7Bdefault%3A%2042%7D%0D%0A%0D%0A)):

```coffeescript
o = 
  default: 42

a = o.default

b = o["default"]
```


In the destructuring assignment you can assign it to a new variable:

```coffeescript
{default: def} = o
```

Can you provide a short example of TS where `default` can be used?

**Comment by crisward** [comment]
This is taken from the code I was using in TS.

```typescript
function(options:any) { 
    let {default: string, ...imgprops} = options
}
```
Below is a link to their online playground showing what this compiles to.

https://www.typescriptlang.org/play/#src=%0D%0Afunction(options%3Aany)%20%7B%20%0D%0A%20%20%20%20let%20%7Bdefault%3A%20string%2C%20...imgprops%7D%20%3D%20options%0D%0A%20%20%20%20%0D%0A%7D

**Comment by crisward** [comment]
Sorry, looks like it was converting the default to a variable named string. This just looks like a 'string' type.?? Pretty confusing.
