### ISSUE TITLE
Bug: Conditional (ternary) operator breaks in version 2.2.2

### ISSUE THREAD

**Issue by microdou** [jashkenas/coffeescript#5009]
In version 2.2.2, conditional (ternary) operator breaks when a dot operator `.` exists between `?` and `:`

```coffeescript
b = {c: 'c'}
m = a ? b.c : d

# error: unexpected :
# m = a ? b.c : d
#            ^^
```

**Comment by microdou** [comment]
`[]` operation is also not allowed.

```coffeescript
b = {c: 'c'}
m = a ? b['c'] : d

# error: unexpected :
# m = a ? b['c'] : d
#               ^
```

**Comment by GeoffreyBooth** [comment]
In CoffeeScript, ternaries are written using `if`...`then`:

```coffee
m = if a then b.c else d
```

**Comment by microdou** [comment]
@GeoffreyBooth I know, but it was compatible before I think. Is it officially not supported?

**Comment by microdou** [comment]
OK, looks like it's not supported anymore. Thank!

**Comment by GeoffreyBooth** [comment]
The `?` operator has always meant something else. `a ? b` is a shorthand for `if a? then a else b`:

```coffee
a = null

result = a ? b

result = if a? then a else b
```
Becomes:
```js
var a, result;

a = null;

result = a != null ? a : b;

result = a != null ? a : b;
```

This hasn’t changed recently as far as I’m aware.

**Comment by connec** [comment]
You may have been confused by something like [this](http://coffeescript.org/v2/#try:a%20%3F%20b%20%3A%20c) which *does* compile, but doesn't do what you think:

```
a ? b : c
```

If `a` is null-y it will instead evaluate `a : b`, which is an implicit object literal (`{a: b}`).
