### ISSUE TITLE
Proposal : symbol type like ruby?

### ISSUE THREAD

**Issue by Argorate** [jashkenas/coffeescript#5011]
What do you think about add a new sugar to use symbol in javascript with same simple syntax than ruby with ":"

Ruby :
foo[:bar] = 42

coffee/JS
foo[Symbol('bar')] = 42

why not integrate ":XXX" ==> "Symbol('XXX')" ? 

It's easier to read, faster to write, no?

**Comment by vendethiel** [comment]
#3950, https://github.com/jashkenas/coffeescript/pull/4003#issuecomment-129554995, #4310
