### ISSUE TITLE
Bug: when using (b=1; return) if true followed by any statement

### ISSUE THREAD

**Issue by rosenfeld** [jashkenas/coffeescript#5013]
Choose one: is this a bug report or feature request? **Bug**

### Input Code
```coffee
a = ->
  (b=1; return) if true
  #b=2
```

The code above compiles successfully in the last release, but if you uncomment the last line then it throws "error: cannot use a pure statement in an expression". This used to work but after upgrading to latest CoffeeScript my existing code is broken. Was this change intentional?

* CoffeeScript version: 2.2.3
* Node.js version: 8.9.1

**Comment by rosenfeld** [comment]
This bug seems to have been introduced in release 2.0.2 since it was working on 2.0.1.

**Comment by vendethiel** [comment]
The compiler in 2.0.2+ tries to compile `(b=1;return)` using the comma operator.
Seems like 6faa7f2b35289c817d78537148c5c124fcb247d6 is the culprit, removing a `unwrapAll`.
The removal was to accomodate with Flow, but broke this particular behavior.

**Comment by zdenko** [comment]
This looks more like #3441. The PR for it (#4849) didn't cover `Return` (which is the instance of `Return` and not `StatementLiteral`).

**Comment by vendethiel** [comment]
@zdenko Ah, I tend to forget Coffee doesn't have the HURL type. Anyway, if you add the `unwrapAll` back where I linked, you'll see the Flow tests failing, but this one bug fixed. It's better fixed where you did, though :-).

**Comment by zdenko** [comment]
@vendethiel why is this not allowed [`-> (yield return)`](https://github.com/jashkenas/coffeescript/blob/5a43b2d7c560934f2f4b069ecf31eb21429e477a/test/error_messages.coffee#L958)?

**Comment by zdenko** [comment]
`(function* () {});` like [here](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=BQMwrgdgxgLglgewgKmASgAQG8BQBfNAbiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=env&prettier=false&targets=Node-7&version=6.26.0&envVersion=1.6.2)?

**Comment by zdenko** [comment]
@lydell I think you might be the right person to ask about this. Why can't `-> (yield return)` compile to  `(function* () {});`?

**Comment by vendethiel** [comment]
Oh, that's right, we have this syntax. Well, `yield return` is a `YieldReturn` is a `Return`, so the fix for this issue probably fixes that as well.

**Comment by lydell** [comment]
@zdenko Sorry, I have no idea why that doesn't compile. Your suggested compilation sounds sensible, though.
