### ISSUE TITLE
Regression in generated output when using a fixed range

### ISSUE THREAD

**Issue by bugnano** [jashkenas/coffeescript#5015]
Older versions of CoffeeScript (I'm using version 2.1.1), given this input:

### Input Code
```coffee
a = []

for x in [0...a.length] by 1
	alert(x)
```

generate an optimized output for the "for" statement

### Expected Behavior
```js
  for (x = i = 0, ref = a.length; i < ref; x = i += 1) {
```

### Current Behavior
Newer versions of CoffeeScript (Sorry, I don't know when this new behaviour was introduced), generate some useless checks
```js
for (x = i = 0, ref = a.length; 1 !== 0 && (1 > 0 ? i < ref : i > ref); x = i += 1) {
```
The problem is that  1!==0 and 1 > 0 are checked at each loop iteration, and are completely useless, as they can be (and were) optimized at compile time.

### Possible Solution
Triage where this optimization has been cancelled out, and put it back in (not sure if possible, given the refactoring of the compiler), or implement again the optimization when the part after the "by" keyword is a constant.

**Comment by zdenko** [comment]
I missed that one while working on #4889 :man_facepalming:
