### ISSUE TITLE
for in loop optimisation

### ISSUE THREAD

**Issue by imegamaximus** [jashkenas/coffeescript#5017]
this:
```coffeescript
for event in events
  handlers.push -> event
```

compile to:
```javascript
var event, i, len;

for (i = 0, len = events.length; i < len; i++) {
  event = events[i];
  handlers.push(function() {
    return event;
  });
}
```

However, if the programmer wants to give the variable "event" a block scope, he needs to do this:
```coffeescript
for event in events then do (event)=>
  handlers.push -> event
```

compile to:
```javascript
var event, i, len;

for (i = 0, len = events.length; i < len; i++) {
  event = events[i];
  ((event) => {
    return handlers.push(function() {
      return event;
    });
  })(event);
}
```

but this is not optimal. The optimal solution would be to use let operator.

Do you have any idea what kind of syntax you need to come up with, to indicate the block scope of the iterated variable?

maybe we should by default compile like this:
```coffeescript
for event in events
  handlers.push -> event
```

compile to:
```javascript
var i, len;

for (i = 0, len = events.length; i < len; i++) {
  let event = events[i]; // let operator
  handlers.push(function() {
    return event;
  });
}
```

**Comment by vendethiel** [comment]
This was the way it worked in 2010-2011, where it was emulated using IIFEs.
See the issue on scope in future versions: #4985.

**Comment by GeoffreyBooth** [comment]
There are many ways to solve this problem that don’t involve changing CoffeeScript. One is to just write it [the way Babel transpiles](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAlgNBA2BTAdgbgFDoGYHtIAooIBeCABjiWRIkWBQBcBnAOioHMGALVaCAHgQpeUANSiAlBADe6CEIa16yRaTqMmAbSgBdXgHp9CiDgAOiMCAZ45ELiGQATJGFamArky74s75AGMGKBxkfClZeXkwRAZ3MGp1FQx5AF8JDBSgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=) your `let` inside `for`. Another is to use `.forEach`:

```coffee
events.forEach (event) ->
  handlers.push -> event
```

Obviously block scope is a convenient tool for certain scenarios, but it adds complexity.

**Comment by connec** [comment]
It's possibly worth noting that at one time this situation was optimised somewhat by pulling the function definition out of the loop, e.g. in 1.9.3 this outputs:

```coffee
// Generated by CoffeeScript 1.9.3
var event, fn, i, len;

fn = (function(_this) {
  return function(event) {
    return handlers.push(function() {
      return event;
    });
  };
})(this);
for (i = 0, len = events.length; i < len; i++) {
  event = events[i];
  fn(event);
}
```

**Comment by GeoffreyBooth** [comment]
@connec What you’re referring to had a bug, #1403, dating back to 2011. @zdenko fixed it in #4854, and the fix involved undoing the optimization unfortunately. Now if you want that optimization you’ll need to define the function explicitly.

**Comment by imegamaximus** [comment]
@GeoffreyBooth  Another is to use .forEach

you do not understand, I now and do, but I can not reverse iterate for example. and in general I am now talking about the development of the CoffeeScript language and not about my problems.

**Comment by imegamaximus** [comment]
if changing the behavior of old operators makes us lose backward compatibility, then let's create a new, universal operator to iterate over anything.

**Comment by GeoffreyBooth** [comment]
We already have `for`...`from`. I don’t think `for` loops are special enough to warrant them being a unique case where block scoping is allowed, while block scope is otherwise unsupported in CoffeeScript. We’re discussing potentially adding block scoping in general in #4985.

**Comment by imegamaximus** [comment]
@GeoffreyBooth 

if changing the behavior of old operators makes us lose backward compatibility, then let's create a new, universal operator to iterate over anything.

it will support iteration and objects, and arrays, and array-like objects, and iterators. and it will also buffer the object so that if the object suddenly changes during the iteration, it would not affect the operation of the loop. how do you like the idea? the only problem I see is that all the beautiful words are already occupied by other operators, and we will need to come up with a new short beautiful and understandable operator)))


```for item at obj```  =)
or 
```for item with obj```  =)

**Comment by Inve1951** [comment]
Here's a former discussion bout changing for-loop scoping: https://github.com/coffeescript6/discuss/issues/63.
There's also still this which seemed very promising IMO: https://github.com/coffeescript6/discuss/issues/61.

Note that currently you can achieve your desired result with an extra variable and backticks like so:
```coffee
for _event in events
  `let event = _event`
  handlers.push -> event
```
[*[try it]*](http://coffeescript.org/v2/#try:events%20%3D%20%5B1..3%5D%0Ahandlers%20%3D%20%5B%5D%0A%0Afor%20_event%20in%20events%20by%20-1%0A%20%20%60let%20event%20%3D%20_event%60%0A%20%20handlers.push%20-%3E%20event%0A%0Aalert%20handlers.map%20(handler)%20-%3E%20handler()%0A)

**Comment by Inve1951** [comment]
the syntax with `do (whatever) ->` is fine and already well established
