### ISSUE TITLE
[Docs] Enhance the Documentation usage

### ISSUE THREAD

**Issue by s-pace** [jashkenas/coffeescript#5021]
:wave:  team,

I am Sylvain from Algolia. At Algolia we are big fans of CoffeeScript.

We would love to help you adding search to your docs.

We provide a free tool called [DocSearch](https://community.algolia.com/docsearch/) which take care of creating and updating an index automatically for you.

We can grant you access to your search analytics which allow you to see what people search for and don't find.

![Preview here](https://cl.ly/3M1x2i1Y0r2n/Screen%20Recording%202018-03-22%20at%2007.02%20PM.gif)

[Try it here](http://coffeescript-docsearch.surge.sh/)

---

If you're interested, here are the instructions to integrate it in your website:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'd8c0290b3e915152f833b7eb80aa8d45',
  indexName: 'coffeescript',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input in your page if you don’t have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in our github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/coffeescript.json).

A crawler will run every 24h updating your search index.

Feel free to get back to us if you have any issues or questions.

Have a nice day :slightly_smiling_face:

**Comment by GeoffreyBooth** [comment]
Ah, I’ve seen this at http://getbootstrap.com/docs/4.0/getting-started/introduction/

@jashkenas?

**Comment by s-pace** [comment]
Yep exactly!

**Comment by jashkenas** [comment]
Since we have single-page docs, I don't think we really need to depend on a third-party (that may not provide this API freely, forever) for this.

Command-F, while not nearly as pretty, gets you in the end to pretty much the same results.

**Comment by s-pace** [comment]
👋 @jashkenas,

You raise a good point!

DocSearch is 3 years old and is a free gift to the community. It will remain free.

It provides typo tolerance, filters, result at every keystroke, analytics on your search... It is way more than a `Ctrl + F`

Let us know if you think it may help your project.

**Comment by GeoffreyBooth** [comment]
Well, the API-driven search is certainly better for a query like “class” that has 155 results. And it’s not like Command-F goes away.

**Comment by jashkenas** [comment]
Then go for it!

**Comment by s-pace** [comment]
👋 @GeoffreyBooth @jashkenas,

Huge news 🎉. Happy to PR if you guys need it. Just point me out which repo and branch to use.

Let me know

**Comment by GeoffreyBooth** [comment]
Sure, please submit a PR against this repo and I'll review it. Please check the box that lets maintainers edit. Thanks.

**Comment by s-pace** [comment]
@GeoffreyBooth  ✅ https://github.com/jashkenas/coffeescript/pull/5035

**Comment by GeoffreyBooth** [comment]
Closing to keep the discussion focused in #5035.
