### ISSUE TITLE
Bug: when compiling to nested async functions

### ISSUE THREAD

**Issue by zhanzhenzhen** [jashkenas/coffeescript#5029]
### Input Code

```coffee
# output "a" after 100 ms
a = ->
  new Promise((resolve, reject) ->
    setTimeout(->
      console.log("a");
      resolve()
    , 100)
  )

b = ->
  console.log("b")

do ->
  foo =
    try
      await b()
      a()
    catch
      null
  await b()
```

### Expected Behavior

```
b
b
a
```

### Current Behavior

```
b
a
b
```

### Possible Solution

Really don't know. Seems it's very hard to fix. Because the `try` block is compiled to a nested async function, and the nested function returns a promise, it will behave as if `a()` has an `await` before it. But actually it shouldn't because the CoffeeScript code doesn't have nested async functions.

### Context

Here's the "correct" JS code that reflects the intention of the above CoffeeScript code:

```js
"use strict";

let a = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log("a");
      resolve();
    }, 100);
  });
};

let b = () => {
  return console.log("b");
};

(async () => {
  try {
    await b();
    a();
  }
  catch (ex) {
  }
  await b();
})();
```

which outputs:

```
b
b
a
```

### Environment

* CoffeeScript version: 2
* Node.js version:

**Comment by vendethiel** [comment]
You're await-ing `b`, which isn't an async function. What for?

**Comment by zzz-shadow** [comment]
`await b()` is just to make the `do` function an async function.

**Comment by vendethiel** [comment]
Fair enough. But still, the issue is semantic:

You have `foo` depending on the return value of `a`. How do you suggest the `async () => {...}` keep running, if we don't yet have a value we depend on?

**Comment by zhanzhenzhen** [comment]
@vendethiel `await b()` is just to make the `do` function an async function.

**Comment by zdenko** [comment]
`foo` is missing from the ES example.
If you remove it from the CS code

```coffeescript
do ->
  try
    await b()
    a()
  catch
    null
  await b()
```

you'll get

```javascript
(async function() {
  try {
    await b();
    a();
  } catch (error) {
    null;
  }
  return (await b());
})();
```

I think the result will then be as expected: `b, b, a`.

**Comment by zhanzhenzhen** [comment]
@vendethiel Please also run the "correct" JS code to see their differences.

**Comment by vendethiel** [comment]
I ran the "correct" code. The "correct" doesn't have a variable that keeps track of `a()` 's return value, and thus doesn't have that issue.

**Comment by vendethiel** [comment]
See @zdenko 's code: when you don't depend on the value, it is not "blocked on". When you *do* need th e value, well, there is no other way than to wait for the Promise to be resolved.

**Comment by vendethiel** [comment]
Unless you are suggesting that the try-block be *not* wrapped with an `await`/`async` function. But that only happens because you pretend you need `b` to run.

**Comment by zhanzhenzhen** [comment]
Why close it? isn't it a bug? `foo` shouldn't be blocked at all because it doesn't have an `await` operator. I deliberately used `foo` because to trigger this bug it must generate a nested async function.

**Comment by vendethiel** [comment]
> foo shouldn't be blocked at all because it doesn't have an await operator.

It does. You have `await b()`. That's an await operator.

**Comment by zhanzhenzhen** [comment]
When you do need th e value, well, there is no other way than to wait for the Promise to be resolved.

No, @vendethiel `foo` shouldn't be blocked because this CoffeeScript example expects `foo` to be a Promise itself, not a result of a Promise, just because `a()` doesn't have `await`.

**Comment by connec** [comment]
You can fix your code by changing the `try` to:

```coffee
try
  await b()
  a()
  null  # `null` prevents `a()` from being implicitly returned
```

There's arguably a bug in the compilation of `try`/`catch` with `await`. It's not really clear that this _should_ `await baz` imo:

```coffee
foo = try
  await bar()
  baz
```

I'd maybe expect this instead:

```js
foo = (async () => {
  try {
    await bar()
    return baz
  } catch(_error) {}
})()
```

That would have the downside of needing quite a lot of `await`s to get the alternative though:

```coffee
foo = await try
  await bar()
  baz
```

**Comment by vendethiel** [comment]
> That would have the downside of needing quite a lot of awaits to get the alternative though:

The meanings are different. `baz` could return a `Promise` we want to await at the `foo` level here.

**Comment by connec** [comment]
> The meanings are different. baz could return a Promise we want to await at the foo level here.

As in `await foo`? If that's what you wanted, you would omit the `await` from `await try`. Atm there's no way of getting `foo` to be the promise since the `await` gets propagated out to the assignment.

**Comment by zhanzhenzhen** [comment]
@vendethiel @connec Sorry misword. Not that `foo` should be blocked, but `a()` shouldn't be blocked. I just want to report a bug. I know there're many workarounds. Or, you already have noticed this issue before?

**Comment by vendethiel** [comment]
> As in await foo? If that's what you wanted, you would omit the await from await try. Atm there's no way of getting foo to be the promise since the await gets propagated out to the assignment.

I'd be very uncomfortable if – in a world where the functions `a` and `b` don't throw exceptions – these two acted differently:

```
->
  x = (await a(); b())
# and
->
  x = try
    await a()
    b()
```

**Comment by zhanzhenzhen** [comment]
@vendethiel the only difference between the CS code and the JS code is that the CS code has a `foo =`. You mean a language should make the async behavior different not by whether using `await`, but by whether using something like `foo =`? That seems very unreasonable. Could you open it again?

**Comment by vendethiel** [comment]
> Not that foo should be blocked, but a() shouldn't be blocked

Well, the issue is that JS "folds" promises, i.e. `Promise.resolve Promise.resolve 1` is the same as `Promise.resolve 1`. This was a really bad decision then and is still now...

Is this compilation closer to what you expect?

```javascript
(async function() {
  var foo;
  foo = (await (async function() {
    return new Promise)(resolve, reject) {
      b.then(function () {
        resolve(a())
      });
  })());
  return (await b());
})();
```

Because if I remember correctly, this still folds the promise.

**Comment by vendethiel** [comment]
@zhanzhenzhen or do you agree with @connec 's suggestion?

**Comment by zhanzhenzhen** [comment]
@vendethiel I already know these workarounds like adding a `null` or `undefined` to prevent it returning a promise. As I mentioned above, I just want to report a bug, not wanting to know workarounds. Why you labelled it as "question"? You don't agree this is a bug?

**Comment by vendethiel** [comment]
> You don't agree this is a bug?

This is a breaking change. This is why it's dangerous. We don't know how many people rely on the current behavior. If more people support this change, we can consider it, but we still need to be careful.

**Comment by vendethiel** [comment]
@connec there's a "simple hack" to make the OP's case work (it's still a breaking change), that is:
- `await b()` is correctly awaited
- `return a()` is not awaited:

```javascript
var foo = (await (async () => {
  await b();
  return [a()];
})())[0];
```
Yes, it's awful, but removing the `await` like you suggest means the order of operations is not guaranteed anymore, and `return a()` is the reason we're discussing this...
