### ISSUE TITLE
Proposal: get & set

### ISSUE THREAD

**Issue by rafikalid** [jashkenas/coffeescript#5033]
Hi coffeescript,

This is a proposal form for getters & setters
`getter() -> ...
setter(value) -> ...
`
example
`myObject = 
    myGetter() -> 'the value'
    mySetter(value) -> @_hiddenAttr= value
`

what you think about?

**Comment by GeoffreyBooth** [comment]
http://coffeescript.org/#unsupported-get-set and #4915, among others.
