### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by iamMonzurul** [jashkenas/coffeescript#5036]
Choose one: is this a bug report or feature request?

### Input Code

```coffee
reactDom.render  <ViewContainer opts... />, eleRef
```

### Context

I am trying to render ViewContainer component but while I try to compile it, I am getting unexpected "<".

### Environment

* CoffeeScript version: 2.2.4
* Node.js version: 8

**Comment by vendethiel** [comment]
This is the error message I get:

```
Unexpected token. Allowed CSX attributes are: id="val", src={source}, {props...} or attribute.
reactDom.render  <ViewContainer opts... />, eleRef
```

**Comment by iamMonzurul** [comment]
Could you please tell me what would be the correct way to write that line? @vendethiel

**Comment by vendethiel** [comment]
The syntax, it seems for both JSX *and* CoffeeScript, is `<ViewContainer {opts...} />`, as the error message points out.

**Comment by iamMonzurul** [comment]
`<ViewContainer {opts...} />, `

In that case I am getting "expected end of line" error in webstorm.

**Comment by vendethiel** [comment]
We do not support the CoffeeScript WebStorm plugin, you'll have to take that issue to JetBrains. Seems like it works fine on CoffeeScript's end.

**Comment by iamMonzurul** [comment]
Well, I understand you guys don't support webstorm plugin but if you can go to http://js2.coffee and put this line `reactDom.render  <ViewContainer {props...} />, eleRef` you will see it's not a problem with webstorm.

Let me know if you have any explanation on that. I would really appreciate that.

**Comment by vendethiel** [comment]
js2coffee hasn't been updated (except for deps) since mid 2016. So it doesn't support CSX.
You'll have to take this with the js2coffee people.
See https://github.com/js2coffee/js2coffee/issues/369.

**Comment by GeoffreyBooth** [comment]
If you’re looking for an online CoffeeScript testing environment, the CoffeeScript webpage has one called Try CoffeeScript that is always up to date:

http://coffeescript.org/#try:reactDom.render%20%3CViewContainer%20%7Bprops…%7D%20%2F%3E%2C%20eleRef
