### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by BridgeAR** [jashkenas/coffeescript#5040]
The current coffeescript version fails in https://github.com/nodejs/citgm and it would be great if a new version e.g., 2.2.5 could be released as that would fix the issue :-).

**Comment by GeoffreyBooth** [comment]
Coming soon! #5043

**Comment by GeoffreyBooth** [comment]
@BridgeAR Not sure if there’s anything you need to do on your end, but a new version 2.3.0 is out that has #5028 included.
