### ISSUE TITLE
not operator discrepancy

### ISSUE THREAD

**Issue by chrapkowski** [jashkenas/coffeescript#5041]
Not, sure if this has been discussed I haven't found.

Doc says: You can use not as an alias for !

which sound like they are aliases but:

```coffeescript
! a ** b
```

compiles to:

```javascript
!Math.pow(a, b);
```

and

```coffeescript
not a ** b
```

compiles to:

```javascript
Math.pow(!a, b);
```

JS considers

```javascript
!a ** b
```

as syntax error: 

```
SyntaxError: unparenthesized unary expression can't appear on the left-hand side of '**'
```

**Comment by jashkenas** [comment]
Looks like a bug to me! (Perhaps in the `**` implementation?)

**Comment by GeoffreyBooth** [comment]
We’re about to release 2.3.0 which updates the `**` implementation to use the new ES2018 `**` rather than `Math.pow`. See #4881. You’ve found one of the very few differences between our old implementation and the official syntax (as was discussed on that thread).
