### ISSUE TITLE
Lexer: “unexpected indentation” with `yield` followed by implicit object

### ISSUE THREAD

**Issue by izotos** [jashkenas/coffeescript#5054]
Possible bug or unintended behavior:

```coffee
gen = ->
    yield
      k: 'v'
```
[/#try link ](http://coffeescript.org/#try:gen%20%3D%20-%3E%0A%20%20%20%20yield%0A%20%20%20%20%20%20k%3A%20'v')

### Expected Behavior
Compile same as:
```coffee
gen = ->
    yield k: 'v'
# or
gen = ->
    yield {
        k: 'v'
    }
```

### Current Behavior
Gives compile error:
```
[stdin]:3:1: error: unexpected indentation
      k: 'v'
^^^^^^
```

### Context
I was expecting to use `yield` same as functions and statements like `return` or `throw`. This type of syntax is quite handy when returning multi key objects.

### Environment
* CoffeeScript version: 2.3.0
* Node.js version: 8.4.0

**Comment by GeoffreyBooth** [comment]
Related to #4532 most directly, and also #4783 and #4599 and #4605. @helixbass any thoughts?

**Comment by helixbass** [comment]
@GeoffreyBooth yup makes sense to me that `yield` would follow the same pattern as `return`/`throw`/`export default`, opened #5072

**Comment by GeoffreyBooth** [comment]
Well that was fast. Does it make any sense to do the same for `await`? Not sure when you’d be awaiting an object, but it feels like the syntax should be the same for `yield`, `await`, `throw`, `return` etc.

**Comment by helixbass** [comment]
@GeoffreyBooth ya agreed I'm not sure if you'd ever await an object, but no harm allowing it syntactically, updated #5072
