### ISSUE TITLE
List comprehension make memory leak

### ISSUE THREAD

**Issue by osddeitf** [jashkenas/coffeescript#5060]
I found memory leak in list comprehension. Here is Coffee script:

    fetch = ->
      ['abc', 'abcd', 'efgh']

    [a, b, c] = fetch()
    length = (x.length for x in [a, b, c])
    a = b = c = null    # Free up memory (garbage collect)

    console.log a, b, c, x

After running this code, it output `null null null 'efgh'`, this happened because after compile to js, it declare x variable in global scope:

    var a, b, c, fetch, length, x;

    fetch = function() {
      return ['abc', 'abcd', 'efgh'];
    };

    [a, b, c] = fetch();

    length = (function() {
      var i, len, ref, results;
      ref = [a, b, c];
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        x = ref[i];
        results.push(x.length);
      }
      return results;
    })();

    a = b = c = null; // Free up memory (garbage collect)

    console.log(a, b, c, x);

The memory leak is not significant in this example but will if there is bigger object. When x be only used in the closure scope, why not declare it in this scope instead of global scope?

**Comment by GeoffreyBooth** [comment]
`x` in your example is not declared in global scope. It's declared in the same function scope as you're using it, as it should be. CoffeeScript happens to create a closure and only use the variable inside that closure, but that's beside the point; _you_ didn't create that closure, so the variable is declared at the top of the function scope it's used in, per CoffeeScript's rules. 

And assigning a variable to null doesn't release it for garbage collection. `a` and its friends are still around, holding a value of `null`. As a developer you have little control over garbage collection in JavaScript.
