### ISSUE TITLE
 How not to strip empty lines? 

### ISSUE THREAD

**Issue by d9k** [jashkenas/coffeescript#5064]
input:

```
console.log 1



console.log 2


```

coffeescript compiler output:

```
(function() {
  console.log(1);

  console.log(2);

}).call(this);
```

expected output:

```
(function() {
  console.log(1);



  console.log(2);


}).call(this);
```

How not to strip empty lines?

**Comment by vendethiel** [comment]
This isn't possible. CoffeeScript doesn't keep this information.

**Comment by carlsmith** [comment]
Why? Just out of interest.

**Comment by d9k** [comment]
@GeoffreyBooth, for the visual separation of code blocks.
