### ISSUE TITLE
Class as prop value error: unexpected indentation

### ISSUE THREAD

**Issue by imegamaximus** [jashkenas/coffeescript#5065]
```coffeescript
Encoder.addCustomType
  type  : class Cat
  encode: 999
```

![image](https://user-images.githubusercontent.com/37433887/39968255-d7cc2802-56d2-11e8-9c4a-d761d5b20447.png)

**Comment by GeoffreyBooth** [comment]
I think this was fixed by #5053. [It compiles in Try CoffeeScript now.](https://coffeescript.org/#try:Encoder.addCustomType%0A%20%20type%20%20%3A%20class%20Cat%0A%20%20encode%3A%20999)
