### ISSUE TITLE
npm update coffeescript error

### ISSUE THREAD

**Issue by Skalkaz** [jashkenas/coffeescript#5071]
If you try to npm update coffeescript without npm installing, then you got an error. All other npm packages work and get installed.

##npm install coffeescript ##--> never installed
**npm update coffeescript**

`npm WARN deprecated coffeescript@99.999.99999: This version has been deprecated, please use coffeescript@latest instead

> coffeescript@99.999.99999 preinstall /node_modules/coffeescript
> node super-evil-script-omg-for-reals.js

You misspelled 'coffee-script'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffeescript@99.999.99999 preinstall: `node super-evil-script-omg-for-reals.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the coffeescript@99.999.99999 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sysop/.npm/_logs/2018-05-22T11_49_44_175Z-debug.log`

**Comment by vendethiel** [comment]
Quoting the error message:

> You misspelled 'coffee-script'

**Comment by vendethiel** [comment]
@GeoffreyBooth Oh, it seems like I got it backwards. My bad, I stand corrected.
