### ISSUE TITLE
call chain error  (get 1 2 3 4 5)

### ISSUE THREAD

**Issue by imegamaximus** [jashkenas/coffeescript#5073]
```coffeescript
get 1 2 3 4 5
```

must compile to
```javascript
get(1)(2)(3)(4)(5)
```

**Comment by GeoffreyBooth** [comment]
I don’t see how you get that. Chained functions, such as
```coffee
fnC fnB fnA arg
```
compile into
```js
fnC(fnB(fnA(arg)));
```
But integers aren’t permissible identifiers, so you can’t name a function `3`, for example. Also `get` is not a permissible function name.

You could rewrite your example as
```coffee
getFn arg1 arg2 arg3 arg4 arg5
```
and it would compile.
