### ISSUE TITLE
Proposal: Transform bind support

### ISSUE THREAD

**Issue by Zydnar** [jashkenas/coffeescript#5074]
Babel has transform-bind plugin (see: https://babeljs.io/docs/plugins/transform-function-bind/ ). It is quite useful, because developer do not need to think if he should use call or bind. Also pipeing with `::` is easy.
eg: 
```javascript
arr.map(foo)::flatMap()::otherStuff()
```

Currently in coffeescript:
```coffeescript
foo::bar
```
will compile to:
```javascript
foo.prototype.bar:
```
Note the colon at the end. So it looks like it would not colide.

**Comment by GeoffreyBooth** [comment]
Our [policy](https://coffeescript.org/#contributing) to is adopt new syntax when it reaches Stage 4 (release) in the ECMAScript standards process. [The ES `::` syntax is only Stage 0](https://github.com/tc39/proposals/blob/master/stage-0-proposals.md), so there’s a good chance it won’t get standardized or will change significantly between now and then.

**Comment by Zydnar** [comment]
Anyway I made mistake - it would colide. It was semicolon not colon, just font on your site in sandbox is not nice to read.
