### ISSUE TITLE
@ in closure before super constructor call

### ISSUE THREAD

**Issue by imegamaximus** [jashkenas/coffeescript#5076]
![image](https://user-images.githubusercontent.com/37433887/40531676-b75cca7c-6005-11e8-81aa-013657e7e83a.png)

![image](https://user-images.githubusercontent.com/37433887/40531685-bcc0502e-6005-11e8-924d-5a5a36ef72c6.png)

but is correct javascript code and correct compile with babel

The JavaScript engine itself makes sure that you do not have access to "this" before calling the parent constructor. But while you can safely take "this" in the closure, and use later.
---

![image](https://user-images.githubusercontent.com/37433887/40531956-8931c91c-6006-11e8-9835-6667857f8e09.png)

Correct work cuz we not use `this`:
---

![image](https://user-images.githubusercontent.com/37433887/40532000-b49a9b74-6006-11e8-850b-62b1072272f6.png)

**Comment by Inve1951** [comment]
@GeoffreyBooth This isn't quite invalid.

[Input](https://coffeescript.org/v2/#try:class%20Bla%20extends%20Object%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20x%20%3D%20%3D%3E%20%40y()%0A%20%20%20%20super()%0A%20%20%20%20%40x%20%3D%20x%0A%20%20%20%20%0A%20%20y%3A%20-%3E%20123%0A%20%20%0Anew%20Bla().x()%20%20%23%20123):
```coffee
class Bla extends Object
  constructor: ->
    x = => @y()
    super()
    @x = x
    
  y: -> 123
  
new Bla().x()  # 123
```
Output:
```
[stdin]:3:12: error: Can't reference 'this' before calling super in derived class constructors
    x = => @y()
           ^
```
Expected output (runs without errors):
```js
var Bla;

Bla = class Bla extends Object {
  constructor() {
    var x = () => {
      return this.y();
    };
    super();
    this.x = x;
  }

  y() {
    return 123;
  }
};

new Bla().x(); // 123
```

**Comment by vendethiel** [comment]
Yeah, this is something we disallowed to keep the check simple.

**Comment by GeoffreyBooth** [comment]
If someday JavaScript adds support for `=>` class methods, we will change our output to that style rather than the current rewriting. When that day comes, I have a feeling that JavaScript will still prohibit this “referencing `this` before `super`“ business. So by barring it now, we avoid a potential breaking change.

It also doesn’t make much sense why you’d be able to use `this` before super in a `=>` method but not a `->` method.
