### ISSUE TITLE
THIS in arrow functions before call super constructor

### ISSUE THREAD

**Issue by imegamaximus** [jashkenas/coffeescript#5077]
javascript engine scan access to "this" in runtime!!!
===

IN RUNTIME!!! CARL
===

Example:
===
![image](https://user-images.githubusercontent.com/37433887/40574682-06271728-60df-11e8-9ec5-f64e22b5a003.png)

Real Example:
===

![image](https://user-images.githubusercontent.com/37433887/40574559-e49a63c8-60dc-11e8-9d4a-dfc5dcc45b87.png)

IN JAVASCRIPT IT WORKS CORRECTLY 
===

![image](https://user-images.githubusercontent.com/37433887/40574589-42c366de-60dd-11e8-8a69-1154d68f0571.png)

BUT in CoffeeScript we have ERROR:
===

![image](https://user-images.githubusercontent.com/37433887/40574599-6d943b40-60dd-11e8-8115-85b331144c88.png)

=================================

![image](https://user-images.githubusercontent.com/37433887/40574466-e30dadfa-60da-11e8-9883-b096fb11fe1d.png)

I pointed out to you the ERROR IN YOUR LANGUAGE, AND YOU HAVE CLOSED MY ISSUE!
===

WHY?????

![image](https://user-images.githubusercontent.com/37433887/40574489-7ef0ba3c-60db-11e8-93e9-e1d160a08688.png)

![image](https://user-images.githubusercontent.com/37433887/40574491-85717536-60db-11e8-8b9b-2904c40a3811.png)

EVEN BABEL WORKS CORRECTLY
===

![image](https://user-images.githubusercontent.com/37433887/40574608-a67f7d70-60dd-11e8-95c1-879dba113ec3.png)

Works even with BOUNDED methods!!!
===

![image](https://user-images.githubusercontent.com/37433887/40574712-90a4ea92-60df-11e8-8cbd-2df833490e5c.png)

Why so many inadequate behavior from developers? CoffeeScript is SIMPLE SYNTACTIC SUGAR for Javascript! If I WANT to write such a code! Then he is simply obliged to compile it! I WILL SOLVE, I WANT SUCH CODE OR NOT!
===

**Comment by imegamaximus** [comment]
P.S. Im not crasy =)

**Comment by vendethiel** [comment]
I don’t understand what you don’t understand in « you are not welcome here ».
