### ISSUE TITLE
Bug: @ reference to class not maintained in do block

### ISSUE THREAD

**Issue by mohd-akram** [jashkenas/coffeescript#5085]
### Input Code

```coffee
class Thing
  @foo = 2
  do =>
    console.log @foo
```

### Expected Behavior

This should print `2`.

### Current Behavior

Prints `undefined`.

### Context

This broke existing code that I had tested with CoffeeScript 1.

### Environment

* CoffeeScript version: 2.3.1
* Node.js version: 10.4.1

**Comment by connec** [comment]
Good catch!

**Comment by GeoffreyBooth** [comment]
@connec Do you have time to tackle this one? I’m going to cut a new release soon and this is the only open bug 👀
