### ISSUE TITLE
Bug: Inline Comments in JSX cause unnecessary expression wrapping

### ISSUE THREAD

**Issue by ryansolid** [jashkenas/coffeescript#5086]
Adding Comments in JSX cause unnecessary expression wrapping. I'm working on a JSX transpiler that uses Flow-like annotations so this is completely broken in Coffeescript currently. 

```coffee
<div>
  <div ###comment### attribute={value} />
</div>
```
Produces
```js
<div>
  {<div /*comment*/attribute={value} />}
</div>;
```
Where it should produce
```js
<div>
  <div /*comment*/attribute={value} />
</div>;
```
Also true for attribute comments like
```coffee
<div>
  <div attribute={###attr comment###value} />
</div>
```

Produces
```js
<div>
  {<div attribute={/*attr comment*/value} />}
</div>
```

EDIT: Actually it does this in a nested manner so:
```coffee
<div>
  <div>
    <div>
      <div ###comment### attribute={value} />
    </div>
  </div>
</div>
```
Produces:
```js
<div>
  {<div>
    {<div>
      {<div /*comment*/attribute={value} />}
    </div>}
  </div>}
</div>
```

* CoffeeScript version: CS 2.3.1
* Node.js version: 8.11.1

**Comment by GeoffreyBooth** [comment]
Can you try this on the `ast` branch? We refactored comments in JSX on that branch, I wonder if it’s any different.

**Comment by ryansolid** [comment]
Yeah, it looks to still have the same behavior on the ast branch.
