### ISSUE TITLE
Proposal: Syntax for reducing chaining code duplication?

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#5089]
Hello,

In d3 you frequently do things like:

```coffeescript
d3.select 'something'
  .append 'rect'
    .attr 'x', 0
    .attr 'y', 0
    .attr 'width', width
    .attr 'height', height
```

Would there be any value in having a syntax that allowed you to expand to multiple chained calls to the same function?  `.attr()` is called with just 2 arguments, but there are others like `.style(name, value, priority)`  In the last day I've found myself writing more than 20+ lines together with `.attr()` or `.style()` as a prefix.  For CSS styling I would normally split it into another file, but React and Vue tend to encourage everything within the same file (as part of the JS).

I am in no way proposing this as the 'final form':
```coffeescript
d3.select 'something'
  .append 'rect'
    .style 'fill', 'darkseagreen'
      .. 'stroke', 'white'
      .. 'stroke-width', '4px'
      .. 'opacity', '0.5', 'important'
```

So 2 things:

1) Chaining is a common enough idiom, is this worth introducing a shorthand for?
2) If it's worth it, what would be a better syntax than the above?

This thread might be over quick.

**Comment by GeoffreyBooth** [comment]
Generally libraries that have chaining where you would call the same method over and over have a version of that method that takes an object. In your case, there’s `attrs` from the [d3-selection-multi](https://github.com/d3/d3-selection-multi) script, per [here](https://stackoverflow.com/a/38209449):

```coffee
d3.select 'body'
.append 'svg'
.selectAll 'circle'
.data data
.enter()
.append 'circle'
.attrs
  cx: (d) -> d.x
  cy: (d) -> d.y
  r: (d) -> d.r
```

A similar case is the jQuery [`css` method](http://api.jquery.com/css/), which takes an object for setting multiple properties at once.

**Comment by vendethiel** [comment]
FTR, that’s the « smalltalk cascade » implemented in Coco/LiveScript.

**Comment by blitmap** [comment]
I did have a look at d3-selection-multi.  I thought it was worth raising as something to consider for Coffeescript (a shorthand for repeated chaining of the same method). :)

**Comment by GeoffreyBooth** [comment]
Closing as this doesn’t appear to be in so much demand as to warrant inventing new syntax.
