### ISSUE TITLE
Bug: REPL is broken.

### ISSUE THREAD

**Issue by FreezePhoenix** [jashkenas/coffeescript#5093]
### Input Code

```bash
coffee -i
```

### Expected Behavior

It should load the repl, and respond with 
```
coffee>
```

### Current Behavior

It errors with this:
```
/coffee-script/lib/coffee-script/repl.js:46
      initialPrompt: repl.last.replace(/^[^> ]*/, function(x) {
                              ^

TypeError: Cannot read property 'replace' of undefined
```

### Possible Solution

I've toyed around with it, and it appears the following works:
```javascript
      // line 46:
      initialPrompt: (repl.last || '').replace(/^[^> ]*/, function(x) {
        return x.replace(/./g, '-');
      }),
      prompt: (repl.last || '').replace(/^[^> ]*>?/, function(x) {
        return x.replace(/./g, '.');
      })
```

### Context

I'd been writing a version of CoffeeScript, but noticed that the REPL doesn't work. It seemed to be the fact that `repl.prompt` was actually a function, not a string.

### Environment

* CoffeeScript version:  1.6.2

**Comment by Inve1951** [comment]
latest 1.x release is `1.12.7`

**Comment by FreezePhoenix** [comment]
@Inve1951 ... Excuse me, I'll be on my way then.
