### ISSUE TITLE
Proposal: Check for even pairs of  ' ' and " "

### ISSUE THREAD

**Issue by Karl01** [jashkenas/coffeescript#5094]
Some errors result from typos mixing '...' with "..." in the same line. If during parsing there were a check for even pairs of ' and of " in a given line of code this would come up immediately. (I'm using zappa minimum framework)

**Comment by GeoffreyBooth** [comment]
`'` or `"` strings can be multiline, like [the example in the docs](https://coffeescript.org/#strings):

```coffee
mobyDick = "Call me Ishmael. Some years ago --
  never mind how long precisely -- having little
  or no money in my purse, and nothing particular
  to interest me on shore, I thought I would sail
  about a little and see the watery part of the
  world..."
```

These strings are different from `'''` or `"""` strings, in that they get collapsed into a single line string.
