### ISSUE TITLE
Proposal: support for BigInt literals (`1n`)

### ISSUE THREAD

**Issue by shimaore** [jashkenas/coffeescript#5103]
Note: this should be tagged with `[Awaiting Stage 4]` at this time.

Node.js supports BigInt, including some niceties such as `process.hrtime.bigint()`.

This doesn't seem to mean a lot of changes for CoffeeScript, besides maybe adding BigInt literals.

### Input Code
```coffee
42n
0b101010n
0o52n
0x2an
```
### Expected Behavior
The number grammar is expanded to support the `n` suffix: https://tc39.github.io/proposal-bigint/#sec-grammar-change

### Current Behavior
`unexpected identifier` error when compiling a BigInt syntax

### Possible Solution
I don't know how CoffeeScript currently handles number literals, but essentially the textual representation of the literal should be copied over to the output: `42n` in coffee → `42n` in ecmascript.

(In the interim, using ``` `42n` ``` works as expected.)

### Context
Using native BigInt instead of external libraries, etc. in recent Node.js

### Environment
* Node.js version: 10.8.0 (apparently all 10.x versions have some form of BigInt support)

**Comment by rdeforest** [comment]
I've only spent a few minutes on this, but from looking through lexer.coffee, grammar.coffee and nodes.coffee, it seems that adding '\d+n' to the NUMBER pattern in lexer.coffee will "just work." On versions of node which don't have BigInt the result is the same in coffee as in node.

So I created PR #5104. I hope it's helpful. :)
