### ISSUE TITLE
Bug: string interpolation introduces invalid newline in nested object

### ISSUE THREAD

**Issue by BrownBear2** [jashkenas/coffeescript#5112]
There is a bug in how string interpolation in an object within an array are handled if they are followed by a comma. In short, the following issue should be self-explanatory.

### Input Code
```coffee
[
  foo: "#{x}, #{y}"
]
```

### Expected Behavior
```js
[
  {
    foo: `${x}, ${y}`
  }
];
```

### Current Behavior
```js
[
  {
    foo: `${x},
  ${y}`
  }
];
```

### Possible Solution
unkown, it seems that the parser misidentifiers the content of the string as part of an object?

### Context
the newline causes bugs in the following code

### Environment
coffeescript v2.3.2

**Comment by BrownBear2** [comment]
even simpler error case:

```coffee
[
  foo: ", #{b}"
]
```

```js
[
  {
    foo: `,
  ${b}`
  }
];
```

**Comment by GeoffreyBooth** [comment]
Good catch!
