### ISSUE TITLE
Bug: stack trace line numbers are incorrect

### ISSUE THREAD

**Issue by thisredone** [jashkenas/coffeescript#5129]
### Expected Behavior
When running code with `coffee` line numbers in stack traces should be correct

### Current Behavior
They're not

### Context
This goes pretty far in history of CoffeeScript. I don't think they were ever correct in 2+

* CoffeeScript version: 2.3.2
* Same situation in Windows and Linux
* Node.js version: 8.11.2 but others as well

**Comment by GeoffreyBooth** [comment]
Please provide a reproducible example.

**Comment by GeoffreyBooth** [comment]
Can you find an example that doesn’t involve another library?

**Comment by thisredone** [comment]
I'm honestly not sure. Pretty much all code involves some libraries so is this really necessary? I might keep looking but it might take some time, Maybe tomorrow I'll find some

**Comment by GeoffreyBooth** [comment]
If I change the first line of your example to `config = require './package.json'` (where that file exists) I get a correct stack trace:

```bash
coffee ./test.coffee
Error: bad thing
    at Foo.error (~/Sites/coffeescript/test.coffee:5:11)
    at Object.<anonymous> (~/Sites/coffeescript/test.coffee:7:11)
    at Object.<anonymous> (~/Sites/coffeescript/test.coffee:1:1)
```

So clearly not every import causes this.

If you can produce a minimal test case, with either no library involved or a very minimal (like “hello world”) library that doesn’t have any complexity, I’ll reopen the ticket.

**Comment by Inve1951** [comment]
I've too seen wrong locations in stack traces but can't come up with a concrete example at the moment.
Only thing I got in a quick attempt to reproduce was line numbers being off by 1 line [#try](https://coffeescript.org/v2/#try) on subsequent runs of the code, first run they appear to be correct.

**Comment by thisredone** [comment]
Maybe having this issue closed isn't such a good idea after all? Either I'm living in a bubble; am I the only coffeescript coder in the world; or everyone else is affected by this as well so keeping this issue open could lead to some external help.
The burden of finding the exact conditions in which this problem shows up shouldn't lay on me alone, considering we know nothing about it and it's non-obvious and potentially time-consuming to figure out.
