### ISSUE TITLE
Confused about existential operator / is this a bug or a feature?

### ISSUE THREAD

**Issue by WaKeMaTTa** [jashkenas/coffeescript#5132]
```coffee
# COFFEESCRIPT
obj = JSON.parse('{ "name":"John", "age":30, "city":"New York"}')
obj.name?
```

### Expected Behavior
```js
// JAVASCRIPT
var obj;
obj = JSON.parse('{ "name":"John", "age":30, "city":"New York"}');
typeof obj.name !== "undefined" && obj.name !== null;
```

### Current Behavior
```js
// JAVASCRIPT
var obj;
obj = JSON.parse('{ "name":"John", "age":30, "city":"New York"}');
obj.name != null;
```
* CoffeeScript version: `1.9.2` or `2.3.2`
* Node.js version: `v8.12.0`

**Comment by vendethiel** [comment]
[This is explained in the wiki](https://github.com/jashkenas/coffeescript/wiki/Common-Gotchas#q-why-is-the-existential--operator-only-checking-thisfoo--null-shouldnt-it-also-check-for-typeof--undefined-).
