### ISSUE TITLE
Docs: Document usage of object shorthand creation

### ISSUE THREAD

**Issue by phil294** [jashkenas/coffeescript#5133]
### Input Code

```coffee
foo = 
  bar
  c: 3
```

### Expected Behavior
I would expect it to compile to
```javascript
foo = {
   bar,
   c: 3
}
```
It's common object shorthand notation, after all.

### Current Behavior
It has been discussed in https://github.com/jashkenas/coffeescript/issues/4600#issuecomment-313382121, is not supported. You will need braces around the object body, if I am not mistaken.

### Possible Solution
This should be addressed in the documentation. After thorough reading I had assumed there was nothing further to consider.

* CoffeeScript version: Liveedit on coffeescript.org.

**Comment by GeoffreyBooth** [comment]
There is some discussion of the shorthand syntax in https://coffeescript.org/#objects-and-arrays, though it doesn't mention explicitly that braces are required. Would you care to submit a pull request? https://github.com/jashkenas/coffeescript/wiki/%5BHowTo%5D-Update-the-docs
