### ISSUE TITLE
`void` keyword (or dot, or bang, for no-arguments function calls)

### ISSUE THREAD

**Issue by sstephenson** [jashkenas/coffeescript#514]
I'd like to open discussion for a `void` keyword, such that

```
x void
```

compiles to

```
x()
```

The idea came up in an IRC conversation about the dissonance of optional parentheses on function calls in cases like this:

```
if expression
  @pass()
else
  @fail message
```

In general, CoffeeScript style is to omit parentheses where possible. Omission is not possible for argument-less function calls. A `void` keyword could mitigate that:

```
if expression
  @pass void
else
  @fail message
```

I'm not convinced it's an improvement over `@pass()`. But maybe there's something here. Quoth jashkenas: "it's an interesting idea to have a keyword that has a presence like a variable in the language, but disappears before use."

**Comment by lzrski** [comment]
Just a funny discovery - you can use [backtics (embedded js)](http://coffeescript.org/#embedded) to call a function without arguments, without `do` keyword and without parens:

```coffeescript
fn `` # backticks
```

It allows for (nice?) chaining:

```coffeescript
fn = (args...) -> args.length

fn ``
  .toString ``
  .repeat 5
```

Above will give you nice `'00000'`, as it compiles to: 

```javascript
fn().toString().repeat(5);
```
