### ISSUE TITLE
Hovering over the text examples on the main page (#introduction) the cs and JS go away when hovering over them, eventually collapsing the div completely

### ISSUE THREAD

**Issue by specialorange** [jashkenas/coffeescript#5142]
Choose one: is this a bug report or feature request?

### Input Code

```coffee
your (code) => here
```

### Expected Behavior

One should be able to select the text to copy, or just hover over it, and the text should not disappear. 
### Current Behavior

Hovering over the text examples on the main page (#introduction) the cs and JS go away when hovering over them, eventually collapsing the div completely

### Context

https://coffeescript.org/#introduction

### Environment

Chrome - Version 71.0.3578.80 (Official Build) beta (64-bit)
Firefox - 63.0.3 (64-bit)

* CoffeeScript version:
* Node.js version:

**Comment by GeoffreyBooth** [comment]
Hovering over them causes them to be initialized with CodeMirror, a code editor. It works on my machine. Perhaps the CodeMirror library is being blocked in your environment for some reason.
