### ISSUE TITLE
Feature: convert JS api to functional

### ISSUE THREAD

**Issue by TrungRueta** [jashkenas/coffeescript#5147]
**Feature**

### Input Code
Although all CoffeeScript's syntax help us make very clear and small code, we still must use a lot of JS api such as:

```coffee
list = []
list.filter n -> n is yes
list.map n -> yes
```
and so on

### Expected Behavior
My think, code will be better a lot when we allow writing built-in api as function
```coffee
list = []
filter list, (n) -> n is yes
map list, (n) -> yes
```
### Context
I think this feature is small but will help writing code more functional style, because nowaday almost people use external package to help their JS code look like functional like : Lodash-fp, ramda, ...
whichs only slowing down js because mlti nested function just to help clearer js code. it not worlth.

If CoffeeScript itself can support with small bundle function like this, i think people no need add any package to simulate functional style.

if you see in functional packages, famous function people use is compose and pipe:
```javascript
let a = compose(func1, func2)
a(something)
```
without compose js code must write in nested and hard to see. but with coffee we can have free the functiional style (at least in my think):
```coffeescript
a = (val) -> func1 func2 val
a something
```
I also think that with trend writing everything like functional style nowadays ( facebook make reasonml, haskell try convert to js, purescript, haxel ... ) CoffeeScript will open to more people if we can support nice hack way like this. Let's think, no longer external library, just CoffeeScript and project :)

I also want suggest feature to have nice syntax to import file which convert to `require()` and `module.exports` in js . but maybe will write in other topic to easy keep discussing

i suggest look a bit in this tiny package:
https://selfrefactor.github.io/rambda

it lighweight then ramda a lot, and faster x5 also. contains all core tool for me to write nice code.
we can think about pick some function as built in because they used almost of time.

### Environment

* CoffeeScript version: 2.3.2
* Node.js version: v10

ps: my english really bad, i hope you guy can understand my idea :(

**Comment by vendethiel** [comment]
CoffeeScript explicitly doesn’t want to provide a stdlib of sorts. Use underscore lodash ramda sanctuary or whichever library you want that suits you.

**Comment by GeoffreyBooth** [comment]
The biggest problem, in my view, is that `filter list` is already taken; that compiles to `filter(list)` currently. There’s no way we would change that (it would be the most breaking of breaking changes, rendering all previous CoffeeScript ever written incompatible). Even if you limited it to known prototype methods, like `filter` and `map`, there’s no way for CoffeeScript to know that `list` is an array or array-like object with such methods; and we need to preserve support for users defining their own functions named `filter` and `map` etc.

**Comment by GeoffreyBooth** [comment]
Sorry, `find n in list` is already valid CoffeeScript. We can’t just change what it compiles out to. Breaking changes are very damaging to the community and need to be avoided at all costs.

You can look in https://github.com/jashkenas/coffeescript/pulls to see what people are working on. Currently there’s an effort to get the CoffeeScript compiler to output not just JavaScript source code, but an abstract syntax tree (basically, a JSON representation of the JavaScript source). This AST can then be used by tools like Prettier and ESLint. That’s the next big feature coming in 2019. Aside from that, CoffeeScript currently supports all of ES2018, so when more features reach Stage 4 as part of ES2019 and beyond, we will continue adding support for them when possible.

**Comment by hsmyers** [comment]
Just read the blog (and etc.) about Google's V8 and BigInts. That should be
a lot of fun should it be accepted by the PTB (Powers That Be)…

**Comment by Inve1951** [comment]
@TrungRueta This is probably a bad idea but maybe exactly what you are looking for.
I previously wrote that [here](https://github.com/jashkenas/coffeescript/issues/620#issuecomment-435822290).

```coffee
_with = (context, args..., block) -> Reflect.apply block, context, args

list = []
_with list, ->
  @filter (n) -> n is yes
  @map (n) -> yes
```
