### ISSUE TITLE
Use `puts` as alias for `console.log`

### ISSUE THREAD

**Issue by lanzhiheng** [jashkenas/coffeescript#5148]
Coffeescript is a programming language which syntax similar to ruby. So I think is it possible to use `puts` command to replace `console.log` in it. For compatibility, Can we use the `puts` alias for `console.log`? some time `console.log` make some programmer suck.

#### REPL

``` shell
coffee> puts "hello"
hello
```

#### Compile

``` coffeescript
puts "hello"
```

to 

``` javascript
console.log("hello")
```

**Comment by mrmowgli** [comment]
You realize you can just do
`puts = console.log`

**Comment by lanzhiheng** [comment]
@mrmowgli Yep, I also know that I can define the new method named `puts` and delegate to `console.log`. But the purpose of this issue is that is it possible to improve the native syntax of coffeescript so we can use the more simplified statement.

**Comment by vendethiel** [comment]
CoffeeScript has no stdlib.
