### ISSUE TITLE
Bug: Scientific notation should allow uppercase E

### ISSUE THREAD

**Issue by hsmyers** [jashkenas/coffeescript#5164]
Choose one: is this a bug report or feature request? This is a Bug report.

### Input Code

```coffee
your (code) => Z = math.complex(1.6E-100)


```

### Expected Behavior
I expected a clean compile.

### Current Behavior
coffee --map --bare --compile --output lib/ ./
C:\Users\hsmyers\Documents\LilyPond\mug\drop.coffee:65:21: error: exponential notation in '1.6E-100' must be indicated
with a lowercase 'e'
Z = math.complex(1.6E-100)
............................................^

### Possible Solution
It would be better to accept either case as this would conform to both JS and normal scientific use patterns. It would also mean one less error message!

use of a case sensitive regex

modify the regex used  to be case insensitive
### Context

slight annoyance

Context is the normal give and take of the code/compile/deploy cycle.

### Environment

* CoffeeScript version: 2.3.2
* Node.js version: v11.2.0

**Comment by vendethiel** [comment]
Ok.

**Comment by hsmyers** [comment]
BUG report.

Code:
Z = math.complex(1.6E-100)
Expected this to compile without error.
Current behavior:
error: exponential notation in '1.6E-35' must be indicated with a lowercase 'e'
Z = math.complex(1.6E-35)
Possible solution:
Take both, the rest of the world does!

C:\>coffee --version
CoffeeScript version 2.3.2

C:\>node --version
v11.2.0

**Comment by phil294** [comment]
@hsmyers You should open a new issue and actually fill out the template (not just open it and answer, put the information in the starting post as described)

I think you should do that because your point is valid, in JS, `1 + 2E-3` works, but in coffee fails.

**Comment by hsmyers** [comment]
Oh! Will do, first time ignorance and all that.

**Comment by rdeforest** [comment]
In 2012 uppercase E was deemed an anti-feature in #2060.

The issue was originally opened because TC39 had deemed the octal constant `0O123` to be visually ambiguous and were therefore discussing limiting radix prefixes in ES6 to lowercase letters (`0o123`). Since CS didn't have any backwards compatibility restrictions the CS crew decided that they would prohibit them. While `0E` isn't a radix prefix, they decided to prohibit it anyway "for consistency".

I'd be interested in submitting a PR to allow `0E` but I'd like to get the go-ahead from someone on the core team first.

**Comment by GeoffreyBooth** [comment]
It seems like this wouldn’t be a breaking change? Other than that I don’t really have an opinion on this; would people then want the other letters to be allowed as uppercase too?

Part of CoffeeScript’s mission is to hide some of the bad parts of JavaScript, and `0O` definitely feels like a bad part; but `E` doesn’t strike me as such. That said, I wasn’t part of the earlier debate.

**Comment by rdeforest** [comment]
It's a trivial change so I put together a PR for the team to accept or reject at their discretion.

**Comment by Inve1951** [comment]
I'm opposed to uppercase letters in number literals for the abovementioned reasons. `E` should not be an exception. The `0O` ambiguity aside, it's still harder to parse since there's no visual separation.
