### ISSUE TITLE
CITGM issues

### ISSUE THREAD

**Issue by BridgeAR** [jashkenas/coffeescript#5179]
While checking coffeescript with [CITGM](https://github.com/nodejs/citgm/) for the upcoming Node.js v12 a couple of test failures popped up. I could not identify the actual source of the problem, so I kindly ask to have a look at the output on your own:

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1773/nodes=aix61-ppc64/testReport/junit/(root)/citgm/coffeescript_v2_3_2/
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1773/nodes=rhel72-s390x/testReport/junit/(root)/citgm/coffeescript_v2_3_2/ 

### Environment

* CoffeeScript version: v2.3.2
* Node.js version: v12.0.0-pre

**Comment by GeoffreyBooth** [comment]
I built the latest Node locally (from latest `master`) and ran the same test, but I don’t get any errors:

```
✦ ~/Sites/node/node ./bin/cake test
(node:49660) [DEP0124] DeprecationWarning: REPLServer.rli is deprecated
passed 1283 tests in 4.47 seconds
```

The tests that are failing have to do with properly passing along the arguments sent into shebang scripts. Did anything change regarding that in Node 12?

**Comment by BridgeAR** [comment]
@GeoffreyBooth thanks for looking into it right away!

It might also be an issue with something on the Node.js side. I'll talk to the build working group to see if it is infrastructure related.

**Comment by richardlau** [comment]
https://github.com/nodejs/build/issues/1743#issuecomment-478801378

> > The most likely explanation is that something is wiping out the `LD_LIBRARY_PATH`/`LIBPATH` environment variables and then trying to execute Node.js, which then cannot load the correct C/C++ runtime libraries.
> 
> I think it's https://github.com/jashkenas/coffeescript/blob/7f8b36a8bde340b1039423ecc0e10ec0546e15bd/test/invocation_argument_parsing.coffee#L14-L15 but I don't really know enough about the coffeescript syntax to PR the fix to extend `process.env` instead of replacing it.

**Comment by GeoffreyBooth** [comment]
That code is spawning a new Node process. Here’s the equivalent JS:

```js
var coffeeBinFolder, coffeeCommand, execFileSync, extraArgsScript, initialSpaceExtraArgsScript, initialSpaceScript, path, shebangScript, spawnOptions, spawnSync;

path = require('path');

({execFileSync, spawnSync} = require('child_process'));

// Get the folder containing the compiled `coffee` executable and make it the
// PATH so that `#!/usr/bin/env coffee` resolves to our locally built file.
coffeeBinFolder = path.dirname(require.resolve('../bin/coffee'));

// For some reason, Windows requires `coffee` to be executed as `node coffee`.
coffeeCommand = isWindows() ? 'node coffee' : 'coffee';

spawnOptions = {
  cwd: coffeeBinFolder,
  encoding: 'utf8',
  env: {
    PATH: coffeeBinFolder + (isWindows() ? ';' : ':') + process.env.PATH
  },
  shell: isWindows()
};

shebangScript = require.resolve('./importing/shebang.coffee');

initialSpaceScript = require.resolve('./importing/shebang_initial_space.coffee');

extraArgsScript = require.resolve('./importing/shebang_extra_args.coffee');

initialSpaceExtraArgsScript = require.resolve('./importing/shebang_initial_space_extra_args.coffee');

test("parse arguments for shebang scripts correctly (on *nix platforms)", function() {
  var expectedArgs, realArgs, stdout;
  if (isWindows()) {
    return;
  }
  stdout = execFileSync(shebangScript, ['-abck'], spawnOptions);
  expectedArgs = ['coffee', shebangScript, '-abck'];
  realArgs = JSON.parse(stdout);
  return arrayEq(expectedArgs, realArgs);
});
```

The key line is `execFileSync(shebangScript, ['-abck'], spawnOptions);`, where `spawnOptions` contains the `PATH` environment variable as defined above (which includes `process.env.PATH`). I did a test on `execFileSync`, using this `test.js`:

```js
#!/usr/bin/env node
console.log(process.env);
```
```js
// Run via REPL
> execFileSync('./test.js', ['-a'], {}).toString()
'{ LS_COLORS: \'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:\',\n  HOSTNAME: \'395f4856059d\',\n  PWD: \'/app\',\n  HOME: \'/root\',\n  TERM: \'xterm\',\n  SHLVL: \'1\',\n  PATH: \'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\',\n  _: \'/usr/bin/node\',\n  OLDPWD: \'/\' }\n'

> execFileSync('./test.js', ['-a'], {env: {PATH: process.env.PATH}}).toString()
'{ PATH: \'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\' }\n'
```

So in the two commands I ran via the REPL, when I didn’t define `env` the child process inherited my system’s environment variables; but when I _did_ set `env`, those were the only environment variables that the child process received.

It looks to me like your latest version of Node is expecting an environment variable other than `PATH` to be present, and it crashes if that other variable isn’t there. I’m not sure that this is correct behavior. Shouldn’t it be looking for its libraries in `$PATH`, not in `$LD_LIBRARY_PATH` or `$LIBPATH`?

**Comment by richardlau** [comment]
`LD_LIBRARY_PATH`/`LIBPATH` are used to set the search path for dynamically linked libraries and is an OS-level feature, not specific to Node.js. 

We use it in the Node.js CI because different versions of Node.js are built against different versions of C/C++ and our CI machines need to set the path to the correct C/C++ runtime libraries as they have multiple versions installed. 

This isn't specific to the latest version of Node.js and I don't know if coffeescript has ever worked on the affected systems in our Node.js CI before.

**Comment by GeoffreyBooth** [comment]
If this is specific to your CI machines, and not that Node in general just requires these environment variables to be set all of a sudden, then I suggest you add them to your CI machine’s `PATH`.

```sh
export PATH="$LD_LIBRARY_PATH:$LIBPATH:$PATH"
```

It feels wrong to change CoffeeScript’s tests because of a configuration issue in the Node CI pipeline. CoffeeScript has been part of CITGM for many years and this only just broke, and the tests in question were last modified two years ago.

**Comment by richardlau** [comment]
`PATH` and `LD_LIBRARY_PATH`/`LIBPATH` are not the same thing: https://unix.stackexchange.com/questions/44990/what-is-the-difference-between-path-and-ld-library-path
so adding `LD_LIBRARY_PATH` to `PATH` isn't going to help as the dynamic loader doesn't look at `PATH`. Again, this is a Unix thing, not Node.js specific.

> 
> CoffeeScript has been part of CITGM for many years and this only just broke, and the tests in question were last modified two years ago.

I'm confident this has not only just broke -- It has probably been broken for quite a while on the platforms affected (most platforms in the Node.js CI only have a single compiler toolchain installed). Unfortunately we only keep around a week's worth of CI results so I have no proof.

**Comment by sam-github** [comment]
That summary of that stackexchange answer is that `PATH` is what Windows uses to look for `.dll`s, but on Unix-like, a different env variable is used for `.so`s. There are even some variations among different Unix-like systems. Generally, when spawning a child process, unless you have an explicit reason to do otherwise (rare), you should pass on the entire existing environment, just adding/removing/changing env variables that you specifically know the meaning of and need to change.

**Comment by edemaine** [comment]
@GeoffreyBooth On UNIX architectures, `LD_LIBRARY_PATH` can be necessary to run an executable (such as `node`) that has shared libraries. See e.g. http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html .  So it is kind of impolite to remove it (and any other environment variables), though admittedly this is only testing code.  We're already preserving existing `PATH` settings.  I think it would be good to replace [those lines](https://github.com/jashkenas/coffeescript/blob/7f8b36a8bde340b1039423ecc0e10ec0546e15bd/test/invocation_argument_parsing.coffee#L14-L15) with
```cs
  env: Object.assign {}, process.env,
    PATH: coffeeBinFolder + (if isWindows() then ';' else ':') + process.env.PATH
```
Let me know if you'd like a PR.

**Comment by GeoffreyBooth** [comment]
> Let me know if you'd like a PR.

Sure.

**Comment by BridgeAR** [comment]
@GeoffreyBooth would you mind releasing a patch release with this fix included? That would be awesome!

**Comment by GeoffreyBooth** [comment]
@BridgeAR Done: #5195
