### ISSUE TITLE
Go more functional -- syntax for immutable containers?

### ISSUE THREAD

**Issue by winstonwolff** [jashkenas/coffeescript#5192]
I've been reading a lot about functional languages and I've been playing with PureScript. But really my favorite language is still coffeescript. What do people think about adding support for immutable lists and objects/Maps to the language? I'm thinking of special syntax to create new immutable lists and objects from an old one, with some changes?

**Comment by GeoffreyBooth** [comment]
CoffeeScript compiles to JavaScript, so anything supported in JavaScript is supported here. JavaScript has `Map`, therefore so does CoffeeScript. Any immutable libraries supported in JavaScript are usable in CoffeeScript.
