### ISSUE TITLE
Proposal: different compilation targets es6, es7, es8 and so on

### ISSUE THREAD

**Issue by aleksandrlat** [jashkenas/coffeescript#5198]
Choose one: is this a bug report or feature request?
Feature request

### Expected Behavior
Compile CS to different JS standards or at least to latest standard instead of just es6.

### Current Behavior
Compilation target is es6 only now.

### Possible Solution
Probably `nodes.coffee` can be updated or multiple `nodes.coffee` can be created for each compilation targets.

### Context
It makes sense for me to compile to different targets to be used by different environments. If some environment supports new features we just need to provide JS without additional changes.
Also if needed we can let other tools do the rest.

But I'm not sure about the effort to do it :)

### Environment

* CoffeeScript version: N/A
* Node.js version: N/A

**Comment by GeoffreyBooth** [comment]
You can use the `transpile` option to configure Babel to output whatever target you want. By default (without using `transpile`), CoffeeScript 2 outputs modern, latest-version JavaScript; `transpile` attaches Babel as a second step to transpile the output to whatever compatibility level you desire.

**Comment by aleksandrlat** [comment]
Thank you @GeoffreyBooth!

Sorry maybe I was not clear but I mean coffeescript compiler does not compile to lates modern JS now. 

And I cannot upgrade JS level with babel. I can only downgrade. I.e. if I have es6 I cannot make it es7 with babel. I can only make it es5 and lower.

So my problem is I want to have output JS like this:
```
class Component extends React.Component {
  instanceField = 'value'

  method = () => {
    // ...
  }
}
```

instead of
```
class Component extends React.Component {
  constructor(props) {
    super(props)
    this.method = this.method.bind(this);
  }

  method() {
    // ...
  }
}

Component.prototype.instanceField = 'value';
```

**Comment by GeoffreyBooth** [comment]
When new features are added to JavaScript, CoffeeScript lags behind and adds support for them after they're standardized. You're referring to class fields: https://github.com/jashkenas/coffeescript/issues/4552

It happens that CoffeeScript already supports arbitrary code in a class body, not just assignments, which makes it look like CoffeeScript supports class fields.

**Comment by aleksandrlat** [comment]
Ok. Thank you @GeoffreyBooth!
I just realized that `field` in
```
class Test
  field: 5
```
is on prototype level and shared between instances. 
It is not obvious and it is very confusing because in many other languages it is instance level field.

But what about methods?
Because these look almost equivalently for me except problems with inheritance:
```
// JS current
class Test {
  constructor() {
    this.getAll =this.getAll.bind(this) 
  }

  getAll() {
    return []
  }
}

// JS desired
class Test {
  getAll = () => {
    return []
  }
}
```

**Comment by GeoffreyBooth** [comment]
This isn’t currently valid JavaScript:

```js
class Test {
  getAll = () => {
    return []
  }
}
```

You’re using experimental features here. See [Babel REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqCmEAu0DeAoa0Dm8kEEQRoBeaACgEpSA-NTLaAJzwFcmA7aAbQF0GAvugFA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=&prettier=false&targets=&version=7.4.3&externalPlugins=).

This is because you’re defining the method via `=` instead of `:`. Try this:

```coffee
class Test
  getAll: ->
    []
```

There’s also no benefit to using `=>` over `->` here, as far as I’m aware, as the value of `this` is the class instance in both cases.

My suggested CoffeeScript [outputs as](https://coffeescript.org/#try:class%20Test%0A%20%20getAll%3A%20-%3E%0A%20%20%20%20%5B%5D):

```js
var Test;

Test = class Test {
  getAll() {
    return [];
  }

};
```

Which I think should function identically to your desired output.

**Comment by aleksandrlat** [comment]
Thank you @GeoffreyBooth!

This was bad example without this inside method. But of course I meant cases when we use `this` inside method. 

I know I need babel to transpile class properties. But this is my feature request to target different ES versions and let other tool to do the rest or in some cases we need to use latest node or chrome and all these features are supported by them.

**Comment by GeoffreyBooth** [comment]
CoffeeScript supports targeting various ES versions through the `transpile` option and configuring Babel. Babel has presets for the various ES versions, and does a good job of converting CoffeeScript’s output to whichever minimum version(s) you need to support. See https://coffeescript.org/#transpilation
