### ISSUE TITLE
Proposal: try/catch convenience based on error type

### ISSUE THREAD

**Issue by dmtaub** [jashkenas/coffeescript#5203]
Feature Request: provide shorthand for checking error type in try/catch 

Previously, support for conditional catch was requested, but the proposed solution was rejected because a concern that stack information would be lost. In a follow up, this was pointed out to be a chrome bug: https://github.com/jashkenas/coffeescript/issues/3573#issuecomment-126568208

It would be really nice to support conditional try/catch but this feature request is for the limited case of catch based on error type only, with the implementation as re-throwing in the event that the type isn't matched.

### Input Code
something like...

```coffee
try
  doesSomething()
catch err instanceof SyntaxError
  fixesTheProblem(err)
```

...or the more pythonic `catch SyntaxError as err`

### Expected Output Code
```js
var err;

try {
  doesSomething();
} catch (error) {
  if (error instanceof SyntaxError) {
    err = error;
    fixesTheProblem(err);
  } else {
    throw(error);
  }
}

```

**Comment by Inve1951** [comment]
Food for thought:

First of, if this were to be implemented then it should support multiple catch blocks. Without them it doesn't add much at all and IMO doesn't even warrant getting added. With your proposed syntax that could look like this:
```coffee
try doesSomething()
catch err instanceof SyntaxError
  fixesTheProblem err
catch err instanceof RangeError
  fixesTheProblem err, yes
```
Until recently there has even been an [implementation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Conditional_catch_clauses) of something like that in firefox.
Of course other languages have implemented that too. Here's what it could look like with C#'s syntax:
```coffee
try doesSomething()
catch SyntaxError err
  fixesTheProblem err
catch RangeError err
  fixesTheProblem err, yes
```

You can already do something very similar in coffee [today](https://coffeescript.org/v2/#try:try%20doesSomething()%0Acatch%20err%20then%20switch%0A%20%20when%20err%20instanceof%20SyntaxError%0A%20%20%20%20fixesTheProblem%20err%0A%20%20when%20err%20instanceof%20RangeError%2C%20err%20instanceof%20TypeError%0A%20%20%20%20fixesTheProblem%20err%2C%20yes%0A%20%20else%20throw%20err%0A):
```coffee
try doesSomething()
catch err then switch
  when err instanceof SyntaxError
    fixesTheProblem err
  when err instanceof RangeError, err instanceof TypeError
    fixesTheProblem err, yes
  else throw err
```
This also allows you to handle multiple types of errors in the same block.
With that in mind a syntax like this might be beneficial:
```coffee
try doesSomething()
catch err when SyntaxError
  fixesTheProblem err
catch err when RangeError, TypeError
  fixesTheProblem err, yes
```
If conditional-catch were to be implemented I'm in favor of this last syntax and think it would make for a nice addition to CoffeeScript (with that syntax). That said, I can live without it.

**Comment by GeoffreyBooth** [comment]
Closing due to lack of interest.
