### ISSUE TITLE
Compiles to invalid JS: computed class property

### ISSUE THREAD

**Issue by helixbass** [jashkenas/coffeescript#5204]
@GeoffreyBooth I came across this while working on class AST:

This:
```
class A
  [b]: 3
```
compiles to:
```
var A;

A = (function() {
  class A {};

  A.prototype.[b] = 3;

  return A;

}).call(this);
```
which doesn't parse

Does it make sense to allow computed class properties like this?

If so, it's probably just a question of omitting the `.` when compiling (so here generate `A.prototype[b] = 3` instead)?

Fwiw, it looks like this didn't compile (as Coffeescript source) in Coffeescript 1.x. I didn't trace when it became allowed Coffeescript syntax

**Comment by helixbass** [comment]
For the static case, it's currently inconsistent as far as allowed syntax:
```
# this compiles
class A
  @[b] = 3

# but this doesn't
class A
  @[b]: 3
```
but the version that compiles (`@[b] = 3`) generates valid JS it appears (`A[b] = 3`)

**Comment by GeoffreyBooth** [comment]
I guess it might as well compile, since we support the same for objects since #4803. That might’ve been the PR where this broke for classes.

Can we fix this on `master`?
