### ISSUE TITLE
[FEATURE] Add alias for obj.constructor.prop

### ISSUE THREAD

**Issue by iMegaMaximus2** [jashkenas/coffeescript#5207]
Reason
===
It is often necessary to gain access to static methods of class from ordinary methods. We cant use class name to get access to static methods cuz they can be overridden in child classes. But writing the word `@constructor.method` every time is too lazy

Solution
---
We need add alias for `obj.constructor.prop`

Like `Class::prototypeProp`, but the opposite

Solution example:
---
```coffeescript
obj..name
# compiles to:
obj.constructor.name

@..totalCount
# compiles to:
this.constructor.totalCount
```

nice syntax we need to come up, my ideas:

```coffeescript
# one dot is access to instance props
@.prop
obj.prop

# two dots is access to static props
@..staticProp
obj..staticProp
````

Usage example (compare classes):
---
```coffeescript
if obj1 instanceof obj2.. 
  console.log('siblings')

#compiles to:
if obj1 instanceof obj2.constructor
  console.log('siblings')
```

Usage example 2 (simply get class name):
---
```coffeescript
console.log( 'instance name is ' + obj.name )
console.log( 'class name is ' + obj..name )
```

Usage example 3 (override static methods):
---
```coffeescript
class Animal

  @wasCreated: -> 
    console.log('Animal created')

  constructor: ->
    @..wasCreated() # call static method



class Cat extends Animal

  # override static method
  @wasCreated: -> 
    super()
    console.log('Cat created')



new Cat() # console.log('Animal created') and console.log('Cat created')
```

Usage example 4 (access to constants):
---
```coffeescript
class Cat

  @RUN: 0
  @WALK: 1

  constructor: ->
    @state = @..RUN


cat = new Cat()
cat.state is cat..RUN # true
```

Usage example 5 (simply get static information):
---
```coffeescript
class Cat

  @count: 0

  constructor: ->
    @..count++

cat = new Cat()
cat = new Cat()

cat..count # 2
```

Two dots will be remembered in the programmer's brain as a synonym for the word "static"
This construction `cat..count` programmers read something like `cat.static.count`

**Comment by Inve1951** [comment]
The only prefix that would make sense is two `@`s.
E.g.:
```coffee
class Animal
  constructor: ->
    @@wasCreated()   # call static method

  @wasCreated = ->
    console.log "Animal created"

class Cat extends Animal
  @wasCreated = ->   # override static method
    super()
    console.log "Cat created"
```
Note that using two dots would be ambiguous. Also you don't neet the dot when accessing an instance prop: `@func()` is valid code.

**Comment by iMegaMaximus2** [comment]
@Inve1951 I understand that all symbols are already taken. but I want to come up with the opportunity to access static properties not only "this". but we must not forget that we can use two-character constructs.

Example 1
---
```coffeescript
obj->name
this->name
```

Example 2
---
```coffeescript
class Animal
  constructor: ->
    @->wasCreated()   # call static method

  @wasCreated = ->
    console.log "Animal created"

class Cat extends Animal
  @wasCreated = ->   # override static method
    super()
    console.log "Cat created"
```

the disadvantage is that this construction is similar to the function declaration

**Comment by iMegaMaximus2** [comment]
```coffeescript
obj~prop
@~prop
```

**Comment by aurium** [comment]
Triple colon is ok, however `@@` is more meaningful and also rubysh, and that makes the notation more easy to understant for many devs.

Why more meaningful?
Because `::` means prototype access, not attribute access. `:::` Should be more strongly related to `::` and it is not. The `@` is about attribute access, `@@` makes sense as class attribute access.

The most significant usage (to me) is to access class constants
```coffee
class Cat
  @RUN: 0
  @WALK: 1
  constructor: ->
    @state = @@RUN
```

**Comment by GeoffreyBooth** [comment]
Closing due to lack of interest.
