### ISSUE TITLE
Bug: Check failed: U_SUCCESS when using the `--watch` option

### ISSUE THREAD

**Issue by pal03377** [jashkenas/coffeescript#5210]
Choose one: is this a bug report or feature request? **bug report**

When I try using the coffeescript `watch` option in a command like
```coffee --watch --map --output coffee/out --compile coffee```
, the following error message appears:

```#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0000003DBD72DF70
```

(the ID after the "FailureMessage Object" part is changing per execution)

### Input Code

```console.log "Hello world" ```

For the exact minimal setup see the attached zip file: 
[coffee-test.zip](https://github.com/jashkenas/coffeescript/files/3132991/coffee-test.zip)

### Expected Behavior
No errors appear and coffeescript goes into watch mode.

### Current Behavior
The code is compiled (JavaScript files are created), but watch mode is not enabled and instead an error message is shown, with varying IDs:
![console screenshot](https://user-images.githubusercontent.com/9006596/56990126-8b6cb580-6b94-11e9-871f-599412623b42.png)

The bug does not appear when the `--watch` option is not in use.

The `--map --output coffee/out` options seem not to matter, the error still occurs when I omit them.

### Possible Solution
?

### Context
Trying to `watch` my environment and let `coffee` auto-compile my code.

### Environment

* CoffeeScript version: 2.4.1
* Node.js version: v12.0.0
* npm version: 6.9.0
* Windows version: Windows 10 Home 64 bit build 17763.437 (freshly installed about 3 days ago)

**Comment by pal03377** [comment]
Seems to be a bug with Node.js 12.0. Rolling back to 10.15.3 like suggested [in an issue in the vue-cli repo](https://github.com/vuejs/vue-cli/issues/3879) helped. I will close this as it seems that the bug is not caused by coffeescript itself.

**Comment by GeoffreyBooth** [comment]
Dunno if this matters, but your output folder seems to be inside the path you're watching; as in, the output could itself be getting watched. I would suggest you move your watched files into a subfolder, like coffee/src.

**Comment by pal03377** [comment]
[coffee-test.zip](https://github.com/jashkenas/coffeescript/files/3135027/coffee-test.zip)
```coffee --watch --map --output coffee/out --compile coffee/src```

I now set it up like you suggested and the error message doesn't change when I use node 12 (changing versions with `nvm`). Still thanks for the suggestion.
