### ISSUE TITLE
CoffeeScript "try online "syntax highlighting bug

### ISSUE THREAD

**Issue by iMegaMaximus2** [jashkenas/coffeescript#5212]
CoffeeScript "try online "syntax highlighting bug 

![image](https://user-images.githubusercontent.com/49617181/57586324-f60ae300-74fc-11e9-8d2c-4e3e7195b246.png)

**Comment by GeoffreyBooth** [comment]
Please file a bug with https://github.com/codemirror/CodeMirror, that's what the website uses for syntax highlighting.
