### ISSUE TITLE
Bug: MINIFY=false no longer generates deminified coffee-script.js?

### ISSUE THREAD

**Issue by ajvincent** [jashkenas/coffeescript#5213]
### Input Code

In /bin/bash for version 1.10.0, I had the following:
<pre>
(Download coffeescript tarball from website and extract, then cd to working directory)
npm install
cake build
MINIFY=false cake build:browser
cp extras/coffee-script.js (destination)
</pre>

I'm aware via #4677 that extras/coffee-script.js has moved to docs/v2/coffeescript.js.  However, when I download and extract 2.4.1.tar.gz and run the `MINIFY=false cake build:browser`, I get a minified coffeescript.js.

### Expected Behavior
coffeescript.js is not minified.

### Current Behavior
coffeescript.js is minified.

Note:  It's entirely possible that my build instructions are wrong and this bug is invalid.  A quick glance at the Cakefile suggests that this part of it shouldn't have changed, though...

Please advise.

**Comment by ajvincent** [comment]
Fedora 29 Linux is my operating system, not running in a Docker container.

**Comment by GeoffreyBooth** [comment]
The browser compiler has moved again since I started outputting a legacy and ES module version:

```
  outputFolders = [
    "docs/v#{majorVersion}/browser-compiler-legacy"
    "docs/v#{majorVersion}/browser-compiler-modern"
    "lib/coffeescript-browser-compiler-legacy"
    "lib/coffeescript-browser-compiler-modern"
  ]
```

So you should see it in `lib/coffeescript-browser-compiler-modern/coffeescript.js` for example.

**Comment by ajvincent** [comment]
OK, but that's still minified...

**Comment by GeoffreyBooth** [comment]
Looks like the Babel options changed slightly. Try the branch in https://github.com/jashkenas/coffeescript/pull/5214.

**Comment by ajvincent** [comment]
The changes in that pull request do exactly what I wanted.  Thank you for that, and for the rapid fix.
