### ISSUE TITLE
cs3 Discussion : use new file suffix .cs3 , and change for ... of / for ... in /  for ... from   to the same  semantic  as es6

### ISSUE THREAD

**Issue by TqLj** [jashkenas/coffeescript#5221]
Use new file suffix .cs3 , and change for ... of / for ... in /  for ... from   to the same  semantic  as es6 .

The semantics now are one patch after another, which is confusing

**Comment by GeoffreyBooth** [comment]
This came up when `from` was introduced, and when CoffeeScript 2 was designed. At the time it wasn’t judged worth the confusion of breaking existing code (and all the documentation around the Web for those meanings). It’s unfortunate that CoffeeScript and JavaScript differ in this regard, but I don’t think it’s worth changing at this point. If/when there is ever serious discussion around a potential CoffeeScript 3, we can revisit.
