### ISSUE TITLE
Proposal: optional try (when unambiguous)

### ISSUE THREAD

**Issue by JhonnyJason** [jashkenas/coffeescript#5227]
Hello guys, 
First off all you are awesome! :D Love Coffee and Coffeescript and just today I fell in love with coffeescript again.

So a pain I noticed many times - coffeescript could annihilate it :D

**Making try optional.**

##### Proposed valid synthax
```coffee
minorFunction ->
    doSomeStuff()
    doOtherStuff()
    catch error then report(error)
    finally weAreHappy()
```
##### Would be equivalent to this ugly version here
```coffee
minorFunction ->
    try
        doSomeStuff()
        doOtherStuff()
    catch error then report(error)
    finally weHateTryCatch()
```

It would be unambiguous that any `finally` or `catch` block inside a function requires the whole part of the function before that `catch` or `finally` block to be within a `try` block. 

We could make it more complicated also and extend it further. But actually that one simple use-case would be enough IMO :-)

**Comment by Inve1951** [comment]
Maybe this covers your use case.

```coffee
reportErrors = (args..., cb) ->
  try Reflect.apply cb, this, args
  catch err
    report err
    throw err

minorFunction -> reportErrors ->
  try
    doSomeStuff()
    doOtherStuff()
  catch then maybeHappy()
  # or
  finally maybeHappy(); return
  # prevents error bubbling

minorFunction -> reportErrors someResourceHandle, (handle) ->
  try
    await someAsyncStuff()
    doOtherStuff()
  finally close handle
  # error bubbles up the call stack after reporting it and closing the handle
```

Using a `catch` block also allows you to do additional error handling.
When all the error handling you do is reporting the error then it leaves you with 4 lines of code like the code in your proposal.

That said, I don't think this is common enough to warrant such an indentation-defying syntax.

What's your take on a case like this?:
```coffee
func = ->
  try something()
  finally
    dealWithIt()
  catch error then report error
  finally gotItBackwards()
```
While this is a minimal example you can see how the `catch` block looks like it could only be invoked with errors generated by `dealWithIt()` when in fact errors generated by  `something()` would go there too.

IMO this is too confusing to have a place in CoffeeScript.

**Comment by JhonnyJason** [comment]
Humm I don't undertand how it could cover my use-case.

Now I really think we should not make it more complicated xD

So just that one simple usecase - maybe cut out more precicely:

- If there is no try block first 
- thus a `catch` or a `finally` block comes first on the first indentation level of a function.
- Then assume it was meant to try all those lines of code from the beginning of the function to that block.
- Instead of just throwing an synthax error.

From how I see it, it is unambigous how it is meant at that point so the synthax error is unnecessary - but logical because the compiler does not understand that there is only one logical way how it was meant xD

But we do so we can add it :-)

```coffeescript
func = ->
  try something()
  finally
    dealWithIt()
  catch error then report error
  finally gotItBackwards()
```
My so the take on that code would be it will not activate the usecase as it has a try block first.

I'm not thinking about error bubbling or any behaviour of how the catch and finally should behave.

**Comment by JhonnyJason** [comment]
This:
```coffeescript
reportErrors = (args..., cb) ->
  try Reflect.apply cb, this, args
  catch err
    report err
    throw err

minorFunction -> reportErrors ->
  try
    doSomeStuff()
    doOtherStuff()
  catch then maybeHappy()
  # or
  finally maybeHappy(); return
  # prevents error bubbling

minorFunction -> reportErrors someResourceHandle, (handle) ->
  try
    await someAsyncStuff()
    doOtherStuff()
  finally close handle
  # error bubbles up the call stack after reporting it and closing the handle
```
To this:
```coffeescript
reportErrors = (args..., cb) ->
  Reflect.apply cb, this, args
  catch err
    report err
    throw err

minorFunction -> reportErrors ->
  doSomeStuff()
  doOtherStuff()
  catch then maybeHappy()
  # or
  finally maybeHappy(); return
  # prevents error bubbling

minorFunction -> reportErrors someResourceHandle, (handle) ->
  await someAsyncStuff()
  doOtherStuff()
  finally close handle
  # error bubbles up the call stack after reporting it and closing the handle
```

Beautiful, isn't it? :D

**Comment by GeoffreyBooth** [comment]
This kind of feels like having an `else` without an `if`. In your example

```coffee
minorFunction ->
    doSomeStuff()
    doOtherStuff()
    catch error then report(error)
```

the only way to know how far back to apply the `catch` would be via indentation, so the two previous lines would need to be indented. But we don’t have anywhere else in the language where an indentation is set off by a trailing line rather than a leading one.

**Comment by edemaine** [comment]
If leading `catch` could fit into CoffeeScript, I think it would be like the leading `.` function chaining, i.e., `catch` would apply just to the previous line (which I recall being frowned upon now, though I still like it).  But given that the original poster thinks it should apply to multiple lines, it's definitely too ambiguous.

**Comment by JhonnyJason** [comment]
> This kind of feels like having an `else` without an `if`. In your example
Hummm maybe feels like - because of being so used to the appearance
The `try` has no other functionality than to define a section of code to then have some exit strategies attatched to it.

So just defining a section of code.

> the only way to know how far back to apply the `catch` would be via indentation, so the two previous lines would need to be indented. But we don’t have anywhere else in the language where an indentation is set off by a trailing line rather than a leading one.

Hummm why the indentation?

If there was no try before and it is in the first intendation level of a function - then what is defined as the section of code to be "tried" is unambiguous.

Everything to the start of the function.

If the catch is not in the same indentation level as a function -> error




> If leading `catch` could fit into CoffeeScript, I think it would be like the leading `.` function chaining, i.e., `catch` would apply just to the previous line (which I recall being frowned upon now, though I still like it). But given that the original poster thinks it should apply to multiple lines, it's definitely too ambiguous.

It definately needs to be multiple lines, otherwise it's useless^^ 
I mean
```coffeescript
try doSomeStuff()
catch error then report error
```
Is not too bad.

While this is:
```coffeescript
minorFunction ->
    try
        if case1
            makeCookies()
            eatThem()
         else if case2
             doChores()
             relax()
          else sleep()
     catch error then drinkCoffee()
```
The desired upgrade:
minorFunction ->
    if case1
        makeCookies()
        eatThem()
    else if case2
         doChores()
         relax()
     else sleep()
     catch error then drinkCoffee()
```
Would be worth it if it is not really troublesome in the implementation.

Maybe I'm missing out on some implementation specific complexities.

**Comment by edemaine** [comment]
@JhonnyJason Your latest example is actually one line, so you can do the following today:
```coffee
minorFunction ->
    try if case1
        makeCookies()
        eatThem()
    else if case2
        doChores()
        relax()
    else sleep()
    catch error then drinkCoffee()
```

I think what we're objecting to is that `catch` without a preceding `try` block has two natural interpretations: affect the previous single line, and affect the previous rest of the block (as you propose).  The former is natural (to me) given function chaining notation, but as you point out, isn't that useful; the latter has no precedent, so feels weird.  And because there are two natural interpretations, not one, it makes the code difficult to read.

**Comment by JhonnyJason** [comment]
@edemaine Ah yess xD unfortunate example case

**Comment by JhonnyJason** [comment]
> I think what we're objecting to is that `catch` without a preceding `try` block has two natural interpretations: affect the previous single line, and affect the previous rest of the block (as you propose). The former is natural (to me) given function chaining notation, but as you point out, isn't that useful; the latter has no precedent, so feels weird. And because there are two natural interpretations, not one, it makes the code difficult to read.

Yhea it's mainly about readability and the opinions about it might diverse.

Never considered a possible interpretation about that it could only mean single line.

So I'm not sure how to count it as ambiguous. It would also be optional anyways, so people who don't like it wouldn't use it anyways.

And I'm pretty sure people who like it know that only the mulit-line version makes sense.

That people have different coding standards and might regard a different one as unreadable. Then finding a code which has been written in said "bad" coding standard. I don't think that we can prevent that scenario at this level anyways.

**Comment by Inve1951** [comment]
Another thing:
```coffee
# While
try do ->
  try cheapCatering()
  catch germs then die()

# is equivalent to
try do -> try cheapCatering() catch germs then die()


try do ->
  cheapCatering()
  catch germs then die()

# would have different meaning than
try do -> cheapCatering() catch germs then die()
```

**Comment by JhonnyJason** [comment]
@Inve1951 Wow that is confusing, need to wrap my head around this here.

Just learned that something which seemed very simple is actually already a mess.^^ Of course don't want to introduce a confusing mess.

**Comment by JhonnyJason** [comment]
@Inve1951 Ok just learned more :-)

The stated equivalence is not true.
```coffeescript
try do ->
  try cheapCatering()
  catch germs then die()
```
Transpiles to:
```javascript
try {
  (function() {
    var germs;
    try {
      return cheapCatering();
    } catch (_error) {
      germs = _error;
      return die();
    }
  })();
} catch (_error) {}
```
While the inline statement transpiles to:
```javascript
var germs;

try {
  (function() {
    try {
      return cheapCatering();
    } catch (_error) {}
  })();
} catch (_error) {
  germs = _error;
  die();
}
```
This is not bad it makes sense IMO when the inline version which does the complete catch-then already. Essentially takes this catch-then as associated to the outer try.

**Comment by JhonnyJason** [comment]
Regarding the other case
```coffeescript
try do ->
  cheapCatering()
  catch germs then die()
```
This does logically not compile. As the try is for the inner catch. The said big nuissance.

Following the proposal it would unabiguously mean the same as:
```coffeescript
try do ->
  try cheapCatering()
  catch germs then die()
```

Pro pro plus plus?^^

**Comment by GeoffreyBooth** [comment]
Thanks for the suggestion! I’m going to close this because there doesn’t seem to be consensus for pursuing this.
