### ISSUE TITLE
What's the difference between legacy and modern in lib ?

### ISSUE THREAD

**Issue by kid-wumeng** [jashkenas/coffeescript#5229]
node_modules/coffeescript/lib/coffeescript-browser-compiler-legacy/coffeescript.js
node_modules/coffeescript/lib/coffeescript-browser-compiler-modern/coffeescript.js

what is the difference ?

**Comment by GeoffreyBooth** [comment]
The first works in modern browsers that support `import`, the latter works in older browsers. https://coffeescript.org/#2.4.1
