### ISSUE TITLE
existential operator does not work with for loops

### ISSUE THREAD

**Issue by smartbomb** [jashkenas/coffeescript#5232]
coffeescript: 2.4.1

```coffeescript
object = null
for value in object?.array
    pass
```

JS output:
```javascript
object = null;
ref = object != null ? object.array : void 0;
for (j = 0, len = ref.length; j < len; j++) {
    value = ref[j];
    pass;
}
```

Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by vendethiel** [comment]
It works. It’s just that you can’t iterate null/undefined. Try `a ? []` to give it an empty array as a default value.

**Comment by smartbomb** [comment]
Sorry but the object is null, so i believe the existential operator should prevent any errors here?
to clarify perhaps the code generator could have written '[]' instead of 'void 0'

**Comment by vendethiel** [comment]
It prevents there being an error on `.array`. But then you try to iterate on it, and `object?.array` is itself `undefined`. So `for` tries to access `undefined.length` and that doesn't work.

**Comment by smartbomb** [comment]
Thanks for explaining, I see what you mean now.
