### ISSUE TITLE
Website Performance

### ISSUE THREAD

**Issue by heronils** [jashkenas/coffeescript#5235]
The performance of http://coffeescript.org/#language is slow (Tested with Firefox and a laptop without graphics card)! For example if i type ten 'a'´s into a string as fast as possible, then it will only have entered three, once im done, and will it need three more seconds to enter the other seven. The laptop cooler goes wooo.

If i remove all sections below the first code example it performs much better, yet is still a little bit sticky. So the first optimazion may be to split the big document up into many. The second may be to let the compilation happen asynchronously using eg. webworkers.

**Comment by GeoffreyBooth** [comment]
We’re not splitting the document into multiple pages, the single-page-ness is part of the design. The code editors only activate on hover, which is meant to lower the overhead of them. The previous docs weren’t editable, and of course performed much better, but I value the editability.

If you’d like to improve the performance by refactoring into web workers, a PR would be welcome. The code is here: https://github.com/jashkenas/coffeescript/blob/master/documentation/site/docs.coffee

**Comment by heronils** [comment]
Even if you only activate an editor on hover: Whenever the output or input text entry changes its dimensions it will force a [reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a) of the whole document.

**Comment by heronils** [comment]
To be more visual, [this is reflow](https://www.youtube.com/watch?v=ZTnIxIA5KGw) and it – did not check – may happen on the whole document whenever the user types a letter.

**Comment by laurentpayot** [comment]
Lighthouse says the main issue is accessibility, not performance…
https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://coffeescript.org/

**Comment by heronils** [comment]
@laurentpayot thanks for posting this

Yes this test detects a few more issues, like the duplicated ids of the _aside#try_ elements.

When i run it directly in chrome the results are worse: _50, 53, 79, 78_.

The first issue reported is the DOM size. Quote:
_Avoid an excessive DOM size – 8,008 elements. Browser engineers recommend pages contain fewer than ~1,500 DOM elements. (...) A large DOM can increase memory usage, cause longer style calculations, and produce costly **layout reflows**._ (highlighting by me)

This reflow happens indeed on this document, eg. when the scroll event on _div.CodeMirror.cm-s-twilight.CodeMirror-wrap_ fires. This calls line 6933 in the _codemirror.js_, which is part of this function:

```
goLineRight: function (cm) {
    return cm.extendSelectionsBy(function (range) {
        var top = cm.cursorCoords(range.head, "div").top + 5;
        return cm.coordsChar(
            {
                left: cm.display.lineDiv.offsetWidth + 100,   // uses offsetWidth, causing reflow
                top: top
            },
            "div"
        )
    }, sel_move);
}
```

Here the _offsetWidth_ causes the slow performing [reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#box-metrics). _offsetWidth_ is also used in other locations in the _codemirror.js_.

You can test it like follows: In the inspector, remove all `main.main > section`s after the `main.main > section#overview` (which contains the first code example). if you then type letters into the remaining text entry then the performance improves heavily.

It follows that the single page approach does not play well together with these dynamic text entries, even when they are just enabled on hover.

I suggest to reopen this issue.

**Comment by GeoffreyBooth** [comment]
I don’t think the issue needs to be open because this isn’t a problem that necessarily needs to be solved (i.e. it’s not a bug). That said, improvements are welcome if you’d like to open a PR.
