### ISSUE TITLE
Issue :Angular Grid OnregisterApi Method is not binding to Grid Api

### ISSUE THREAD

**Issue by mohanji** [jashkenas/coffeescript#5236]
Choose one: is this a bug report or feature request?

### Input Code

```coffee
$scope.grid =
    data: null
    enableHorizontalScrollbar: 2
    rowHeight: 30
    enableRowSelection: false
    multiSelect: false
    flatEntityAccess: true
    fastWatch: false
    enableGridMenu: true
    exporterCsvFilename: 'resources.csv'
    exporterMenuPdf: false
    gridMenuShowHideColumns: true
    enableColumnMenus: false
    enableFiltering: true
    columnDefs: []
   onRegisterApi: (gridApi) -> $timeout ->
    alert("test")
    , 250
```

### Expected Behavior

   Test alert message should come

### Current Behavior
   Test alert message not comming

### Environment
"gulp-coffee": "~2.3.1",
  "engines": {
    "node": ">=0.10.0"
  }

* CoffeeScript version:
* Node.js version:

**Comment by Inve1951** [comment]
Your code is invalid. [#try](http://coffeescript.org/#try:%24scope.grid%20%3D%0A%20%20%20%20data%3A%20null%0A%20%20%20%20enableHorizontalScrollbar%3A%202%0A%20%20%20%20rowHeight%3A%2030%0A%20%20%20%20enableRowSelection%3A%20false%0A%20%20%20%20multiSelect%3A%20false%0A%20%20%20%20flatEntityAccess%3A%20true%0A%20%20%20%20fastWatch%3A%20false%0A%20%20%20%20enableGridMenu%3A%20true%0A%20%20%20%20exporterCsvFilename%3A%20'resources.csv'%0A%20%20%20%20exporterMenuPdf%3A%20false%0A%20%20%20%20gridMenuShowHideColumns%3A%20true%0A%20%20%20%20enableColumnMenus%3A%20false%0A%20%20%20%20enableFiltering%3A%20true%0A%20%20%20%20columnDefs%3A%20%5B%5D%0A%20%20%20onRegisterApi%3A%20(gridApi)%20-%3E%20%24timeout%20-%3E%0A%20%20%20%20alert(%22test%22)%0A%20%20%20%20%2C%20250)
