### ISSUE TITLE
Bug: Trailing comments after colons not output

### ISSUE THREAD

**Issue by Asc2011** [jashkenas/coffeescript#5241]
seems buggy to me ?
```coffee
CS = require 'coffeescript'
d = """
string : 'a string'  # string with a comment behind it
array : [] # array with trailing comment, this gets eaten
"""
n = CS.nodes d
n.compile bare: on
```
### Expected Behavior
```
({
  string: 'a string', // string with a comment behind it
  arr: [] // array with trailing comment, this gets eaten
});
```

### Current Behavior
```
({
  string: 'a string', // string with a comment behind it
  arr: []
});
```

### Context
working on a Atom-package to preserve comments in CSON/JSON

* CoffeeScript version: 2.4.1
* Node.js version: 10.16.3

**Comment by Asc2011** [comment]
seems there is another one here
```coffee
d = """
string : 'a string'  # string with a comment behind it
object :   # object open with trailing comment, it looks as if this gets eaten, too
  member: 'string'
"""
```
```
({
  string: 'a string', // string with a comment behind it
  object: {
    member: 'string'
  }
});
```
sry for mentioning - i know how much effort went into comment-handling already...

**Comment by GeoffreyBooth** [comment]
Comments are a tough case. Can you try with the `ast` branch and use a proper AST rather than the call to `nodes`?

**Comment by Asc2011** [comment]
tried that, and it looks **much** better. Both missing comments show up in the AST.

**Comment by GeoffreyBooth** [comment]
The issue is that comments aren't part of the grammar; they're like whitespace, in that they become part of the metadata of a nearby token (in whitespace's case, the indent level). When tokens get rewritten, such as to insert implied things like curly braces, metadata can get lost. We try to avoid that whenever possible, but it can happen; and it's hard to write tests to cover all edge cases.

**Comment by helixbass** [comment]
> You could theoretically take the AST output and create generated JavaScript from that, via something like Babel or Prettier, if the AST output has better comments preservation than the generated JS output

That won't be true until we have a "transformed AST" (which we've talked about maybe being the next phase of the AST work - having a printer that consumes a transformed-to-JS-structure AST)

With the "Coffeescript AST", there are structures that don't correspond directly to JS output so you couldn't directly pass it to a JS printer like Prettier
