### ISSUE TITLE
ES 2017 #private class fields

### ISSUE THREAD

**Issue by MegaJSDeveloper** [jashkenas/coffeescript#5282]
@GeoffreyBooth sayd: https://github.com/jashkenas/coffeescript/issues/4552#issuecomment-536413003
> Obviously we need to choose a different syntax than # to denote “private.” Maybe whoever wants to work on that can start a new issue with a proposal? And a PR can follow.

I create a new issue with a proposal:
===

coffeescript `~name` is like javascript `#name`

private:
`@~name`
`@.~name`
`this.~name`

public:
`@name`
`@.name`
`this.name`

Wherever we can write `obj.~prop` we can write `obj~prop`, its both compile to `obj.#prop`

Example:
===
CoffeeScript:
```coffeescript
class Cat
  
  constructor: ->
    @~name = 33
    return
    
  say: ->
    return @~name
```

Must compile to:
```javascript
class Cat {
  #name
	
  constructor(){
    this.#name = 33
  }
	
  say(){
    return this.#name
  }

}
```

Private methods:
===
```coffeescript
class Cat
    
  ~privateMethod: ->
    
  @~privateStaticMethod: ->
```

must compile to:
```javascript
class Cat {

  #privateMethod(){ }
	
  static #privateStaticMethod(){ }

}
```

Access to another object:
---

```coffeescript
class Point

  constructor: ->
    @~x = 0
    @~y = 0
    return
  
  
  equals: (point)->
    return @~x is point~x and @~y is point~y
```

Destructuring params to private vars:
---

```coffeescript
class Point

  constructor: ({@~x,@~y})->
    return

  # or short syntax
  constructor: ({~x, ~y})->
    return
```

**Ugly but not the CoffeeScript 3.0**

**Comment by MegaJSDeveloper** [comment]
Usage examples:
===
```coffeescript
class Point

  constructor: ->
    @~x = 0
    @~y = 0
    return
  
  
  equals: (point)->
    return @~x is point~x and @~y is point~y

```

**Comment by GeoffreyBooth** [comment]
Please stop opening issues in this repo. You’ve been banned several times and I would prefer not to keep contacting GitHub support for assistance.
