### ISSUE TITLE
Bug: Parser: soaks/prototype shorthands in object spreads

### ISSUE THREAD

**Issue by helixbass** [jashkenas/coffeescript#5291]
This was raised by https://github.com/helixbass/prettier-plugin-coffeescript/issues/165

It's pretty clearly a parsing bug that these don't parse:
```
{a::b...}
{a?.b...}
{a?()...}
```
while the corresponding array/argument spreads work:
```
[a::b...]
[a?.b...]
[a?()...]

f(a::b...)
f(a?.b...)
f(a?()...)
```

**Comment by GeoffreyBooth** [comment]
Yup, and the “dots on the left” variants too.

**Comment by eugenet8k** [comment]
Thank you guys!

**Comment by vendethiel** [comment]
Is this yet another case of #1089?

**Comment by helixbass** [comment]
Opened #5293 to fix

@vendethiel no I think that issue is orthogonal since this only has to with splat targets (eg `{a.b...}`) while that issue has to do with object shorthand properties (eg `{a.b}`)
