### ISSUE TITLE
Compiler Types

### ISSUE THREAD

**Issue by ForgivenNin** [jashkenas/coffeescript#5305]
_Feature Request_

In the `README` or on the CoffeeScript website, could you please describe the difference between the `coffeescript-browser-compiler-legacy` and `coffeescript-browser-compiler-modern`/(core) compilers?

P.S.: _Great job at not having any dependencies :)_

**Comment by GeoffreyBooth** [comment]
Legacy is transpiled for older browsers; modern requires a new browser that supports ES module syntax. Legacy also automatically evaluates `script type=coffeescript` tags while the modern one does nothing by default.

**Comment by ForgivenNin** [comment]
Okay, that makes sense. Does it make a difference whether the script type is `text/coffeescript` or just `coffeescript`?

**Comment by GeoffreyBooth** [comment]
> Okay, that makes sense. Does it make a difference whether the script type is `text/coffeescript` or just `coffeescript`?

Sorry, I was being brief. It's `text/coffeescript`: https://coffeescript.org/#scripts
