### ISSUE TITLE
Method Overloading

### ISSUE THREAD

**Issue by devongovett** [jashkenas/coffeescript#531]
A useful addition to CoffeeScript's class implementation would be method overloading.  This would make working with functions that accept a variable number of arguments much easier.  For example:

```
class Users
  find: (id) ->
    # find user by id

  find: (first, last) ->
    # find user by first and last name
```

could be written instead of:

```
class Users
  find: (one, two) ->
    switch arguments.length
      when 1
        id: one
        # find user by id
      when 2
        first: one
        last: two
        # find user by first and last name
```

which is much more code, and is more complex.  John Resig experimented with Method Overloading, and has a good post on how it can be [implemented in JavaScript](http://ejohn.org/blog/javascript-method-overloading/) (very simple, actually).  Here is the function.

```
// addMethod - By John Resig (MIT Licensed)
function addMethod(object, name, fn){
    var old = object[ name ];
    object[ name ] = function(){
        if ( fn.length == arguments.length )
            return fn.apply( this, arguments );
        else if ( typeof old == 'function' )
            return old.apply( this, arguments );
    };
}
```

This method would only need to be run when the CoffeeScript compiler detects that there are two functions with the same name and with a different number of arguments.
#### Caveats
1. Moving objects from one object to another at runtime: which version of the method is copied?  Answer: all of them.  Just like if you wrote the function using a switch on arguments.length (see above), all versions of the method would be copied.  This fits in with Resig's implementation.
2. Functions with a variable number of arguments using splats - Not sure how to fix this problem.  If you have a suggestion, please post it in the comments.  The only thing I can think of right now is that these methods would not be overloadable.  If you tried to overload them, either a compile-time error would be thrown or they would just get overwritten like they are currently.

I think that Method Overloading could be a very useful feature to add to CoffeeScript.  It would require no syntax changes whatsoever, it is easy to explain to people, and it is very convenient.  What do you think?

**Comment by zackarychapple** [comment]
Was really hoping to be able to do this... Any hope of resurrections?
