### ISSUE TITLE
Coffeescript translates 'of' into 'in' in the 'for' function

### ISSUE THREAD

**Issue by NFellGill** [jashkenas/coffeescript#5313]
Choose one: is this a bug report

### Input Code

```coffee
Discord = require('discord.js')
Logger = require('./Logger')

module.exports = class WebhookPlugin
    constructor: (webhooks) ->
        if !webhooks
            return null

        @webhooks = []

        # Here   \/
        for hook of Object.keys webhooks
            @webhooks.push hook
            webhookCredentials = webhooks[hook].split('/').slice(-2)
            @[hook] =
                url: webhooks[hook]
                id: webhookCredentials[0]
                token: webhookCredentials[1]

            @[hook].client = new (Discord.WebhookClient)(@[hook].id, @[hook].token)

    send: (webhook, content) ->
        if @webhooks and @webhooks.includes(webhook)
            if typeof content == 'object' and !(content instanceof Array)
                content = embeds: [ content ]
            if content
                @[webhook].client.send(content).catch Logger.error
```

### Expected Behavior

The code should be compiled correctly

### Current Behavior

On this code the function 'for' is not compiled correctly since the 'of' becomes 'in'

### Context

I just wanted to compile my program with this command: "`coffee --compile --transpile --map --no-header --output dist/ src/`". Everything works fine except that.

### Environment

* @babel/core version: ^7.9.0
* @babel/preset-env: ^7.9.0
* CoffeeScript version: ^2.0.2
* Node.js version: v12.14.1

**Comment by vendethiel** [comment]
That's how it is in CoffeeScript.

**Comment by NFellGill** [comment]
Wtf ?

**Comment by NFellGill** [comment]
It's stupid

**Comment by mrmowgli** [comment]
@NFellGill These have been in Coffeescript much longer than they were in Javascript.  This was a feature of CS that was adopted, but not translated by the ES consortium in the same way.  Now it's a matter of breaking a lot of existing Coffeescript code and is unlikely to change.
