### ISSUE TITLE
Proposal: Functional piping + OO chaining

### ISSUE THREAD

**Issue by GabrielRatener** [jashkenas/coffeescript#5316]
I am aware that chaining is quite a hot topic for CS, but I hope this proposal will improve significantly on previous piping proposals like #4144 that didn't make the cut.

I'm proposing to have an OO chaining operator `|.` that performs a chain of operations on a given object, while always returning the original object, much like Dart does.

This is in addition to supporting the `|>` piping operator that exists in languages like LiveScript, F#, and Elixir.

I'm not sure if `|>` should append or prepend arguments to function calls, but the general idea is the same.

### Example

For an illustration of what this could look like, check out this code.

```coffee

users = [
  { user: 'barney',  active: false, age: 37}
  { user: 'fred', active: true,  age: 21}
  { user: 'pebbles', active: true,  age: 19}
]

add = (n, value) => n + value

arrayOfNumbers = users
  |.pop() # pop value from users but return `users`
  |[1].age = 1 # also support computed props and assignment in chains
  |.reverse() # oo chain expressions still resolves to `users` array!
  |> .map ({age}) => age # end oo chain & return value, no parens needed!
  |> ['reduce'] (sum, age) => age + sum # do same with newly created array
  |> add 2 # append argument and return call value
  |> ([1 ,2, 4]).concat # pipe to end of new array

```

### Context

This solves two major issues, call over-nesting and tediously doing repeated operations on the same object.

The `|> .` syntax is optional, and can be replaced with just `.` but this requires adding parens to method calls, so I was thinking `|> .` could have lower precedence and make for nicer looking code.

Thoughts?

I can create a PR for this if we come to a consensus!

**Comment by FelipeSharkao** [comment]
This is a very cool feature that I'd love to see in CoffeeScript, but it was already reject once, I didn't get why it wouldn't now.

**Comment by GeoffreyBooth** [comment]
There’s a proposal for adding this in JavaScript: https://github.com/tc39/proposal-pipeline-operator

If that reaches Stage 4, we should support it; but our version would just output to the equivalent syntax in JavaScript.
