### ISSUE TITLE
Grammar, Nodes: Support import.meta and import.meta.*

### ISSUE THREAD

**Issue by aurium** [jashkenas/coffeescript#5317]
### Expected Behavior
`import.meta.url` should return module's full path in a `file://` protocol.

### Current Behavior
```
$ coffee -pe 'dirname = path.dirname import.meta.url'
[stdin]:1:24: error: unexpected import
dirname = path.dirname import.meta.url
                       ^^^^^^
$ coffee -pe 'dirname = path.dirname(import.meta.url)'
[stdin]:1:30: error: unexpected .
dirname = path.dirname(import.meta.url)
                             ^
```
### Workarrownd
We can workarrownd it with backticks
```coffee
dirname = path.dirname `import.meta.url`
```
...however it is not good to the language.

### Context
`import.meta.url` is necessary source of information to replace `__(dir|file)name` features.

### Environment
* CoffeeScript version: 2.5.1
* Node.js version: 14.1.0

**Comment by GeoffreyBooth** [comment]
Yes, we need to add support for `import.meta` (and `import.meta.*`). Apparently `meta` is the only valid property on `import`, per [the error that Babel throws if you type e.g. `import.foo`](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgdAMwhA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2017%2Creact%2Cstage-3&prettier=false&targets=&version=7.9.6&externalPlugins=).

See https://github.com/jashkenas/coffeescript/blob/master/src/grammar.coffee#L453-L461. We would need to add a rule there for `IMPORT . Property` with a check somewhere that the `name` of `Property` must be `meta`. Then probably a second rule for `IMPORT . Property . Property`. You get the idea. You might need to trace the classes that get referenced here, e.g. `ImportDeclaration` (https://github.com/jashkenas/coffeescript/blob/master/src/nodes.coffee#L3225) and `PropertyName` (https://github.com/jashkenas/coffeescript/blob/master/src/nodes.coffee#L1171) to add the check for `meta`. If the `meta` check/restriction is too hard, we could just permit `import.*` and `import.*.*` and let the runtime throw on `import.<unsupported property>`.

There are bunch of special cases in `lexer.coffee` for `IMPORT` tokens; hopefully nothing at all needs to change in `lexer.coffee`, but it's something to be aware of if you run into issues. https://github.com/jashkenas/coffeescript/blob/master/test/modules.coffee will also need to be updated with appropriate tests.

**Comment by jashkenas** [comment]
> Yes, we need to add support for `import.meta` (and `import.meta.*`). Apparently `meta` is the only valid property on `import`, per [the error that Babel throws if you type e.g. `import.foo`](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgdAMwhA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2017%2Creact%2Cstage-3&prettier=false&targets=&version=7.9.6&externalPlugins=).

Wow, that’s so ugly!

**Comment by aurium** [comment]
I'm working in this.

**Comment by aurium** [comment]
I'm in trouble to understand what i missed. Please, see this diff: https://github.com/aurium/coffeescript/commit/788540a0549141b6c84e0dc5dad150a8c278c6e9

Adding the grammar alternative `'IMPORT_META . Property'` into `Import` group, it fails like this:
```
$ ./bin/coffee -ep 'foo = import.meta'
[stdin]:1:18: error: unexpected end of input
foo = import.meta
                 ^
```

Adding the grammar alternative `'IMPORT_META'` into `Import` group (and try to let `'. Property'` to `Accessor` group), it fails like this:
```
$ ./bin/coffee -ep 'foo = import.meta'
[stdin]:1:13: error: unexpected .
foo = import.meta
            ^
```

The same happens if I don't create the `IMPORT_META` token and let it to `ImportDeclaration`.

If I set the tag to `IDENTIFIER` instead of `IMPORT_META` in the lexer, it works. However the `IMPORT_META` gives a richer AST and helps to validate the property name easily.

**Comment by GeoffreyBooth** [comment]
This is the Babel AST for `import.meta`:

![image](https://user-images.githubusercontent.com/456802/81461419-7db31e00-9160-11ea-80fa-9f51e2e66943.png)

So maybe using `IDENTIFIER` isn't terrible.

**Comment by aurium** [comment]
@GeoffreyBooth, Good News!
I'm very grateful for your help. I almost gave up and would use the `IDENTIFIER` token, nevertheless I managed to define a specific token for `import.meta`.

**Comment by GeoffreyBooth** [comment]
> I still do not understand many things, like the `LOC(#)(...)` helpers.

Those are for fixing location data. @helixbass is there somewhere that this is documented? If not we should do so, either in a comment where `LOC` is defined or in https://github.com/jashkenas/coffeescript/wiki/%5BHowTo%5D-How-parsing-works (or both).

**Comment by helixbass** [comment]
I explained `LOC()` in a comment on the corresponding PR (#5319)

I'm not sure if it's explained anywhere, I think I had to suss it out for myself when I was learning about the grammar
