### ISSUE TITLE
Bug: DOM manipulation can cause unexpected behavior when executed (specifically a TypeError)

### ISSUE THREAD

**Issue by derrelldurrett** [jashkenas/coffeescript#5322]
Given the following DOM:
```
<button id="killer">Kill them what goes.</button>
<div class="stays">
  <div class="goes">one</div>
  <div class="goes">two</div>
  <div class="goes">three</div>
  <div class="goes">four</div>
  <div class="goes">five</div>
</div>
```
and a document ready handler:
```coffee
$ ->
  s = new ShowTheBug()
  $('#killer').on 'click', () -> s.killThem()
```
calling `node.removeChild()` on all values in a comprehension,
```coffee
class @ShowTheBug
  killThem: () ->
    @removeChild(c) for c in document.getElementsByClassName('goes')

  removeChild: (c) ->
    p = c.parentNode # throws an exception
    p.removeChild(c)
```
### Expected Behavior
I expected all children of `<div class="stays">` to be removed.

### Current Behavior
Because the above code compiles thus:
```
(function() {
  this.ShowTheBug = (function() {
    function ShowTheBug() {}

    ShowTheBug.prototype.killThem = function() {
      var c, i, len, ref, results;
      ref = document.getElementsByClassName('goes');
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        c = ref[i];
        results.push(this.removeChild(c));
      }
      return results;
    };

    ShowTheBug.prototype.removeChild = function(c) {
      var p;
      p = c.parentNode;
      return p.removeChild(c);
    };

    return ShowTheBug;

  })();

}).call(this);
```
eventually the call to `this.removeChild(c)` fails, because the values in the array `ref[]` cease to exist once removed, thus shortening the array's length. So, given the example above, once three elements of the array have been removed, the next value for `i` is `3`, `ref[3]` is outside the bounds of the existing array, and the `TypeError: c is undefined` is thrown.

### Possible Solution
I think this is something CoffeeScript should be aware of in one way or another, but I can't see polluting the compiler with tests for DOM manipulations. The *only* thing I can imagine that might fix this is to make walking through the values generated in a comprehension in reverse order (`ni`, perhaps?) a thing that can be done.

### Context
I'm trying to manage values sent in an AJAX call, and I add, through events, temporary, hidden inputs to a part of my form. When the send event fires, those values are read and sent along, and the the DOM is scrubbed of the values (in case they need to be generated again).

I have a work-around, so if this isn't something you feel like supporting, I will understand. I can even think of a second work-around that builds an invisible container in the DOM in the first place, and then deletes the container. Nevertheless, this seems worth knowing about.

* CoffeeScript version: 2.4.1

**Comment by GeoffreyBooth** [comment]
I think it's a general thing in JavaScript that if you have a comprehension, and the code you're evaluating modifies the thing you're iterating over while you're iterating over it, unexpected results may happen. For example consider [`Array.prototype.map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map): its signature is `map(element, index, elements)`. Within that callback could definitely modify `elements` to remove an element, and then you might not get what you want when it's done. That's not really a bug in `map`, it's just user error.

**Comment by derrelldurrett** [comment]
As it turns out, you missed the mark a touch. It turns out there is a right way (from the perspective of solving this problem) to build the list, and that is to use a function that returns a static list (as opposed to a live list): `[ParentNode.querySelectorAll()](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/querySelectorAll)`. Doing this, the removal of DOM elements doesn't modify the list, and so you don't "lose your place" as you loop over them, deleting them.
