### ISSUE TITLE
Cut JS some slack.

### ISSUE THREAD

**Issue by adjenks** [jashkenas/coffeescript#5328]
On the website it compares coffeescript's list comprehension to javascript like so:

CoffeeScript:
```coffeescript
cubes = (math.cube num for num in list)
```
vs JavaScript:
```js
cubes = (function() {
  var i, len, results;
  results = [];
  for (i = 0, len = list.length; i < len; i++) {
    num = list[i];
    results.push(math.cube(num));
  }
  return results;
})();
```
I know coffeescript wants to look good, but you can achieve the same thing in JavaScript like so:
```js
cubes = list.map(math.cube)
```
List comprehension still looks nice and is easier to understand/read, so perhaps not every comparison needs to be more terse.

**Comment by adjenks** [comment]
Anyhow, this isn't really a valid ticket, so I'll just close it myself.

**Comment by vendethiel** [comment]
This comparison is from a time where `.map` wasn't available, and that's not strictly equivalent because of ETA-reduction. The odd case also doesn't work in your case (i.e. if `list` isn't an Array, just something with a `.length` property, like a NodeList)
