### ISSUE TITLE
Static method syntax is unatural

### ISSUE THREAD

**Issue by evilpie** [jashkenas/coffeescript#533]
This was already discussed on irc and in that [issue](http://github.com/jashkenas/coffee-script/issues/issue/279). This ticket is here until someone finds a better alternative or we accept the current way.

I dont like the @ syntax, because in class context it refers to 'this', wich can only exits in an instance, and the @ for staticmethod has explicitly nothing to do with the instance.

Here are a few ideas, although i think these arent perfect solution.
1. Prefix every instance method with @ and dont prefix staticmethods
2. Prefix every instance method with :: and  dont prefix staticmethods (the :: already stands for prototype to this would be someway consistent)
3. Lets try to find some other not yet used cool character, like ♥ ;)

**Comment by aminland** [comment]
Is this still something that is out of the question?

Classes weren't that common in use before, but nowadays i find they are everywhere, and I am almost never having to access the prototype, but rather the static methods on the class from within a class instance. This pattern is really encouraged with react...

Thoughts?

**Comment by GeoffreyBooth** [comment]
I’m not sure we need another syntax for static methods. What would it be?

Keep in mind there are class decorators (#4917) working their way through the ES approval process, and we’ll probably need `@@` for those.

**Comment by aminland** [comment]
My suggestion was to keep static method declaration as is, and use @@ for
this.constructor shortcut, and an alternative syntax for class decorators,
given that @ has special meaning for coffeescript. There are plenty of
alternative decorator syntaxes in the decorator discussion thread.
