### ISSUE TITLE
Filename missing in transpilation

### ISSUE THREAD

**Issue by binarykitchen** [jashkenas/coffeescript#5335]
Think I've found a bug. Unable to webpack compile Coffeescript when there is the `exclude` option in my Babel config.

This error caught my eye:
```
CoffeeScriptError: Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel
```

The fix is simple. In coffeescript/lib/coffeescript/coffeescript.js you just add the filename to the transpilerOptions like that:

```js
      transpilerOptions.filename = filename; // fixes it!
      transpilerOutput = transpiler(js, transpilerOptions);
```

Then all is swell and I can compile using the exclude option.

**Comment by binarykitchen** [comment]
Related to this discussion https://github.com/babel/babel/discussions/12205

**Comment by GeoffreyBooth** [comment]
This seems like a bug in `coffee-loader`, but if there’s anything you can see within CoffeeScript itself and how we handle Babel options, please let us know.
