### ISSUE TITLE
feature request: Use wildcard character

### ISSUE THREAD

**Issue by J-P-S-O** [jashkenas/coffeescript#5343]
It would be nice if I could use the following comment from the cli:
### Input code
```
coffe -c *.coffee
```
### Expected output
```
Compiling foo.coffee
Compiling bar.coffee
```
### Actual output
```
File not found: *.coffee
```

**Comment by edemaine** [comment]
Most shells will automatically expand `*.coffee` into `foo.coffee bar.coffee`.  If you're using `CMD.EXE`, consider using a different shell?

`coffee` also supports directory arguments.  So you can already do `coffee -c .` to compile `*.coffee` in the current directory (for example).
