### ISSUE TITLE
Doubly declared var in range

### ISSUE THREAD

**Issue by edemaine** [jashkenas/coffeescript#5345]
This is a feature request for nicer code output, ~~which surfaces as a bug when using eslint with standard rules, specifically [the `no-unused-vars` rule](https://eslint.org/docs/rules/no-unused-vars)~~.

### Input Code
```coffee
[i..f(j)]
```

[try link](https://coffeescript.org/#try:%5Bi..f(j)%5D)

### Expected Behavior
I would expect `ref` to be declared with `var` exactly once.

### Current Behavior
Currently it is declared twice: once at the beginning, and once within the `for` loop:
```js
var ref;

(function() {
  var results = [];
  for (var k = i, ref = f(j); i <= ref ? k <= ref : k >= ref; i <= ref ? k++ : k--){ results.push(k); }
  return results;
}).apply(this);
```

### Possible Solution
Perhaps the intended first part of the `for` loop is the equivalent of `(var k = i), ref = f(j)`.  Unfortunately, this is not a valid comma chain in JavaScript.

### Context
The duplicate declaration of `var ref` [is not an error, even in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var#description). ~~However, it leads to an ESLint error of `no-unused-vars`.~~ Actually not an error with `eslint-plugin-coffee`.

[ESLint demo](https://eslint.org/demo#eyJ0ZXh0IjoidmFyIHJlZiwgaSA9IDAsIGogPSA1O1xuZnVuY3Rpb24gZih4KSB7IHJldHVybiB4LTE7IH1cblxuKGZ1bmN0aW9uKCkge1xuICB2YXIgcmVzdWx0cyA9IFtdO1xuICBmb3IgKHZhciBrID0gaSwgcmVmID0gZihqKTsgaSA8PSByZWYgPyBrIDw9IHJlZiA6IGsgPj0gcmVmOyBpIDw9IHJlZiA/IGsrKyA6IGstLSl7IHJlc3VsdHMucHVzaChrKTsgfVxuICByZXR1cm4gcmVzdWx0cztcbn0pLmFwcGx5KHRoaXMpO1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBvcnQtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNldHRlci1yZXR1cm4iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==)

### Environment
Live CoffeeScript try demo

**Comment by edemaine** [comment]
Sorry, I misinterpreted the hoisting.  In fact, the outer `var ref` is outside the `function`, so these are different `ref`s, which explains why `no-unused-vars` triggers but `no-redeclare` didn't trigger.

So the issue is just that a completely useless `var ref` is being output in this case.

**Comment by GeoffreyBooth** [comment]
> So the issue is just that a completely useless `var ref` is being output in this case.

I don’t think this is worth fixing, as it seems almost certain to introduce other bugs.
