### ISSUE TITLE
Proposal: Support `for await...of`

### ISSUE THREAD

**Issue by celalo** [jashkenas/coffeescript#5351]
There is the [`for-await...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) statement, that creates a loop iterating over async iterable objects as well as on sync iterables, including: built-in String, Array, Array-like objects (e.g., arguments or NodeList), TypedArray, Map, Set, and user-defined async/sync iterables.

At the moment,
```coffee
for await (variable of iterable)
  variable
```
does not compile with following error:
```
[stdin]:1:11: error: unexpected (
for await (variable of iterable)
```

A workaround is to embrace the coffeescript with backticks (`) like:
```coffee
`for await (variable of iterable)
  variable`
```
which than compiles into:
```javascript
for await (variable of iterable)
  variable;
```

**Comment by edemaine** [comment]
This ECMAscript feature is in fact supported by CoffeeScript syntax, using the `for ... from` syntax that it uses for iterating iterables:

```coffee
f = ->
  for await variable from iterable
    x
```

(On the other hand, I didn't know about this cool ECMAscript feature &mdash; sounds very handy! &mdash; and just found this out while testing what I thought would be the natural syntax. So I appreciate learning about it!)

**Comment by GeoffreyBooth** [comment]
Closing as it appears we already have support.

**Comment by celalo** [comment]
I was such a dumb. I forgot to place it inside a function. Thanks!
