### ISSUE TITLE
Question: Is it possible to make api(post) that accepts xml

### ISSUE THREAD

**Issue by RenAlbiorix** [jashkenas/coffeescript#5357]
I am new to coffescript. So just like to know.

Is it possible to make api(post) that accepts xml? Currently i have done with getting sting then parse it. But if post data can be passed using xml that'd be great.

* CoffeeScript version:
* Node.js version:

**Comment by vendethiel** [comment]
Hi!

This is not handling by CoffeeScript the language. It is also not a bug report or a feature request, so I recommend you try asking on forums or looking up tutorials related to that.
