### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by nschurmann** [jashkenas/coffeescript#5360]
Hi! Is the project alive yet? Is there any roadmap? Is there any other language that is supposed to be the continuation of coffeescript?

**Comment by hsmyers** [comment]
Yup! And 'Nothing comes to mind.' are the answers I come up with…

**Comment by phil294** [comment]
> May I propose something? In development run the code in coffeescript, in production transpile to JavaScript and run that.

You cannot run CoffeeScript natively in the browser, so what you are suggesting is the standard way of doing things already

**Comment by nschurmann** [comment]
I just realised a good workflow, thanks guys! is there any metric besides npm that shows the usage of coffeescript?

**Comment by GeoffreyBooth** [comment]
Hi, please find another forum for this kind of discussion.
