### ISSUE TITLE
Bug: coffeescript/register does not work for es modules

### ISSUE THREAD

**Issue by johndeighan** [jashkenas/coffeescript#5361]
Choose one: is this a bug report or feature request?
Bug Report

### Input Code

```coffee
console.log "Hello, World!"
```
And my package.json includes:

```javascript
"type": "module",
```
### Expected Behavior

When I run `node --require coffeescript/register temp.coffee
`, it outputs "Hello, World!" to the console

### Current Behavior

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".coffee" for C:\Users\johnd\Dropbox\webcoding\temp2.coffee

### Possible Solution

 
What I think is happening is that since I have "type": "module" in my package.json, node assumes that the register script is an ES module, which it's not. Unfortunately, it seems that the code hides the actual error message, so the registration simply doesn't work and node simply reports that it doesn't understand the .coffee file extension.

The registration system needs to work whether or not I have "type": "module" in my package.json file. I'm not sure of the best way to do that, but I know it can be done. Maybe having both *.mjs and *.cjs files?

### Context

I found this problem by starting to use WebStorm, which internally uses the command line above to run *.coffee files. I can modify the command line being used, but not sure what that should be.

### Environment

* CoffeeScript version: 2.5.1
* Node.js version: 16.5.0

**Comment by GeoffreyBooth** [comment]
`coffeescript/register` is CommonJS-specific and will never work with ES modules; however a loader could be written to provide equivalent functionality once Node.js loaders are more fully developed. See https://github.com/jashkenas/coffeescript/issues/5362#issuecomment-884649994.

Closing in favor of #5362, as the solution will be the same for both.
