### ISSUE TITLE
Bug: Destructuring Assignment edge case error

### ISSUE THREAD

**Issue by rdeforest** [jashkenas/coffeescript#5368]
### Input Code

```coffee
{ a
  b: { c }
} = {}
```

### Expected Behavior
Should compile to
```javascript
var a, c;

({
  a,
  b: {c}
} = {});
```

### Current Behavior
```
[stdin]:2:12: error: unexpected }
  b: { c } } = {}
           ^
```

### Work-around
New line after opening brace:

```coffee
{      # New line added here
  a
  b: { c }
} = {}
```

It also works to swap a and b:
```coffee
{ b: { c }
  a
} = {}
```

### Context
This came up for me in the context of passing behavior functions around in a non-trivial object structure.

### Environment

* CoffeeScript version: 2.5.1
* Node.js version: 16.6.2

**Comment by rdeforest** [comment]
CoffeeScript 1.12.7 behaves the same way though the error it reports is different:

```console
2021-08-19 08:02:14
robert@egeria.lan:~
$ node -e 'cs = require("coffee-script"); cs.compile("{\n  a,\n  b: { c } } = {}")'
$ node -e 'cs = require("coffee-script"); cs.compile("{  a,\n  b: { c } } = {}")'
[/Users/robert/node_modules/coffee-script/lib/coffee-script/coffee-script.js:54
        throw helpers.updateSyntaxError(err, code, options.filename);
        ^

[stdin]:2:4: error: unexpected :
  b: { c } } = {}
   ^] {
  location: { first_line: 1, first_column: 3, last_line: 1, last_column: 3 },
  toString: [Function: syntaxErrorToString],
  code: '{  a,\n  b: { c } } = {}',
  filename: undefined
}
$
```

**Comment by rdeforest** [comment]
While looking at #4952, I discovered another workaround:

```coffee
{ a
, b: { c }
} = {}
```

The more I look at this, the more I think it may be a topic for CoffeeScript 3.0?

**Comment by edemaine** [comment]
If you look at the tokenized output (`coffee --tokens -c filename.coffee`), you'll see that this is getting interpreted as `{a({b:{c}})} = {}`, which is invalid (`{c}` is invalid without an `=` after it).  The relevant rule of CoffeeScript is this:

https://github.com/jashkenas/coffeescript/blob/6fd58ef11cb9deeacb64887ce33c40b9fe4e9702/src/rewriter.coffee#L301-L318

So the ambiguity makes sense, but given that we're in a brace context, it should be possible to disambiguate at the rewriter level. Curiously, the comment says "don’t allow this in literal arrays, as that creates grammatical ambiguities", but the code doesn't actually implement that rule, and the following example has the same issue:

```coffee
[a
 b: x
] = [a, b]
```

Another weird example that's treated like a function call (`y` is the function):

```coffee
{a: y
 b: x
}
```

I'm not entirely sure whether this is intended behavior, as these parses make *some* sense. But given the comment that array literals should be excluded, I think the same should be true for object literals. I'll put together a PR that fixes this.
