### ISSUE TITLE
Bug: --nodes 'StatementLiteral: continue' not indented

### ISSUE THREAD

**Issue by isral** [jashkenas/coffeescript#5369]
Bug report
Running ```coffee --nodes``` resulting ```StatementLiteral: continue``` not indented.

### Input Code
```coffee
for i in [0...10]
	continue if i == 5
	console.log i
```

### Current Behavior
```
Root
  Block
    For
      Block
        If
          Op ===
            Value IdentifierLiteral: i
            Value NumberLiteral: 5
          Block
StatementLiteral: continue
        Value
          Call
            Value IdentifierLiteral: console
              Access PropertyName: log
            Value IdentifierLiteral: i
      Value
        Range
          Value NumberLiteral: 0
          Value NumberLiteral: 10
```

### Context
```coffee --nodes continue.coffee```

### Environment
Windows 10
* CoffeeScript version: 2.5.1
* Node.js version: v14.17.2

**Comment by GeoffreyBooth** [comment]
`--nodes` is a debugging tool, and it works well enough for its intended use. If you’d like to fix this, a PR would be welcome, but I’m closing this as it isn’t a “bug” that necessarily needs fixing.
