### ISSUE TITLE
Bug: Browser-compiler doesn't load programmatically added <script> files

### ISSUE THREAD

**Issue by mbirth** [jashkenas/coffeescript#5370]
### Input Code

```coffee
$ 'head'
.append "<script type=\"text/coffeescript\" src=\"#{coffeeFilename}\"></script>"
```

### Expected Behavior

The given coffeescript file is loaded and transpiled by the browser compiler.

### Current Behavior

The `<script>` tag is added to the DOM and then nothing happens.

(If I change the type to `text/javascript`, the browser - Safari in my case - loads the file just fine.)

### Possible Solution

Make it work like with `text/javascript` files.

### Context

I'd like to lazy load different coffeescript files depending on some variables.

### Environment

* CoffeeScript Compiler v2.5.1 (coffeescript.legacy.min.js)
* Safari 14.1.2

**Comment by GeoffreyBooth** [comment]
This is out of scope for the browser compiler. If you’re already programmatically adding `script` tags, you can call the browser compiler to transpile and evaluate them.
