### ISSUE TITLE
Proposal: Provide a way to avoid unnecessary compilations

### ISSUE THREAD

**Issue by johndeighan** [jashkenas/coffeescript#5383]
The coffee command is so fast (congratulations!) that I, honestly, thought that this was already happening. But apparently, it's not. If I have a file named stub.coffee and I run, e.g. `coffee -c .` in the current directory, it will output a file named stub.js. However, if the most recent modify date of stub.js is later than the the most recent modify date of stub.coffee, I obviously haven't changed stub.coffee since I last created stub.js. Of course, it's conceivable that I modified stub.js manually, but really, I'd never do that.

What I propose, to keep backward compatibility, is that a new command line option be added to the coffee command that checks the modify dates of any *.coffee file and it's corresponding *.js file (if it exists), and bypasses compilation if the *.js file was modified more recently than the *.coffee file. That seems completely safe to me since it only happens with the new command line option.

You may wonder why it's an issue for me. I'm using sveltekit, and it has a config file named 'svelte.config.js'. However, since I like CoffeeScript, I instead have a file named 'svelte.config.coffee', then when I start my development server via `npm run dev`  (which I've got configured to first run `coffee -c .`), I always get the following error message:

[plugin:vite-plugin-svelte] Svelte config change detected, restart your dev process to apply the changes.

**Comment by GeoffreyBooth** [comment]
There’s a strong aversion against adding more command-line options unless they have a strong justification. I’m not sure this qualifies.

Many build tools already support this conditional compilation that you’re looking for. The https://github.com/GeoffreyBooth/coffeescript-gulp repo that I use for my own development of the CoffeeScript project is an example of using Gulp to watch source files and recompile only the ones that changed. Hooking into operating system file events to watch for changes is more robust and less problematic than just comparing timestamps; however it’s significantly expanded functionality relative to what `coffee -c` offers now. I don’t think we’d want to offer a substandard or buggy watching experience as part of `coffee` when a robust version is already available by compiling CoffeeScript via a fuller-featured build tool.

**Comment by Inve1951** [comment]
Note that this can corrupt your working directory when switching branches in git for example (with .js in the .gitignore). The local .js files don't necessarily have been compiled from the local .coffee file in that case. Assuming they were would give unpredictable results and to resolve it you'd have to manually go and delete all local .js files.

**Comment by GeoffreyBooth** [comment]
Since you’re already using Vite, I think the way to handle this is to use Vite to transpile your CoffeeScript. It strikes me as unusual to have two build tools in the same project.

Regardless, the `coffee` command is not intended to be a full-featured build tool. There are many other projects that add sophisticated features like caching of files within a build tree, and CoffeeScript doesn’t need to duplicate what’s already out there.
