### ISSUE TITLE
A function to stringify the AST

### ISSUE THREAD

**Issue by ch1c0t** [jashkenas/coffeescript#5399]
Sometimes I want to stringify the AST. Like so:

```coffee
{ compile } = require 'coffeescript'

source = """
  console.log 'something'
"""

ast = compile source, ast: yes
result = stringify ast

# `result` would be a String semantically equivalent to the original `source`.
# For example:
result #=> "console.log 'something'"
```

It feels like a language feature, but I would implement `stringify` in a separate package. Is this a good place to discuss implementing it?

**Comment by GeoffreyBooth** [comment]
You’re looking for https://github.com/helixbass/prettier-plugin-coffeescript. cc @helixbass

**Comment by ch1c0t** [comment]
@GeoffreyBooth Thank you. It could be helpful to investigate how this plugin works.

I am not looking merely for a code formatter, however. I am looking for a `stringify`(or `format`) function, because I want CoffeeScript to be more programmable(more suitable for [symbolic programming](https://en.wikipedia.org/wiki/Symbolic_programming)). I imagine being able to modify the AST, and then turn the modified version to a string:

```coffee
{ compile } = require 'coffeescript'
astify = (string) ->
  compile string, ast: yes

source = """
  console.log 'something'
"""

ast = astify source
{ expression } = ast.program.body[0]
expression.callee.property.name = 'error'
expression.arguments[0].value = 'something modified'

format ast #=> "console.error 'something modified'"
```

This could enable many new things for CoffeeScript(like tools for [mutation analysis](https://en.wikipedia.org/wiki/Mutation_testing) and [macros](https://en.wikipedia.org/wiki/Macro_(computer_science))).

**Comment by GeoffreyBooth** [comment]
The way Prettier works is that it takes an AST as input and generates source code as output. So it can handle the “turn an AST into runnable CoffeeScript code” part for you. CoffeeScript itself handles the “turn CoffeeScript source code into an AST” part. So all you would need to write is whatever mutations to the AST you want to make, in between those other two steps.

**Comment by ch1c0t** [comment]
Great, thank you!

The only thing which is not quite satisfying about it is that Prettier entails additional complexity(all the things which are not needed to format CoffeeScript, but are there). I find myself wondering how much work would it take to do it without Prettier.
