### ISSUE TITLE
Writte a parser for tree-sitter

### ISSUE THREAD

**Issue by n-rodriguez** [jashkenas/coffeescript#5400]
https://tree-sitter.github.io/tree-sitter/

**Comment by vendethiel** [comment]
Feel free.

**Comment by n-rodriguez** [comment]
At least it's now official, cs is dead

**Comment by MadcapJake** [comment]
I've tried my hand at this and it's incredibly challenging:

> Tree-sitter is based on the [GLR parsing](https://en.wikipedia.org/wiki/GLR_parser) algorithm. This means that while it can handle any context-free grammar, it works most efficiently with a class of context-free grammars called [LR(1) Grammars](https://en.wikipedia.org/wiki/LR_parser). In this respect, Tree-sitter’s grammars are similar to (but less restrictive than) [Yacc](https://en.wikipedia.org/wiki/Yacc) and [Bison](https://en.wikipedia.org/wiki/GNU_bison) grammars, but different from [ANTLR grammars](http://www.antlr.org/), [Parsing Expression Grammars](https://en.wikipedia.org/wiki/Parsing_expression_grammar), or the [ambiguous grammars](https://en.wikipedia.org/wiki/Ambiguous_grammar) commonly used in language specifications.

[Tree-sitter | Creating Parsers # Writing the Grammar](http://tree-sitter.github.io/tree-sitter/creating-parsers#writing-the-grammar)

iiuc, CoffeeScript's parsing strategy is two layers, one more regular and one where a lot of assumptions are made.
