### ISSUE TITLE
Unnecessary `splice` ref added for Array destructuring with rest element not in last position

### ISSUE THREAD

**Issue by STRd6** [jashkenas/coffeescript#5437]
Choose one: is this a bug report or feature request?

### Input Code

https://coffeescript.org/#try:%5Ba%2C%20...b%2C%20c%5D%20%3D%20x

```coffee
[a, ...b, c] = x
```

### Expected Behavior
```javascript
var a, b, c;

[a, ...b] = x, [c] = b.splice(-1);
```

### Current Behavior
```javascript
var a, b, c,
  splice = [].splice;

[a, ...b] = x, [c] = splice.call(b, -1);
```

As far as I can tell `b` is always an instance of `Array` when destructured, even if `x` is an `Array` subclass. If so it won't need a separate reference to the `splice` method. I think this just may be some extra clean up that fell through the cracks in https://github.com/jashkenas/coffeescript/pull/4884/

### Environment

* CoffeeScript version: 2.7.0

**Comment by GeoffreyBooth** [comment]
I think `splice = [].splice` might be slightly faster than `b.splice`, because there’s just one reference already resolved for every time that `splice` is used, rather than `b.splice` causing a prototype chain lookup every time.

**Comment by STRd6** [comment]
Right you are, thanks!

My simple benchmark test says its ~4% faster with the ref. https://jsbench.me/x9lb2z4rmn/1

**Comment by shurko0x4cfd** [comment]
`c = b.pop()` looks faster. Maybe I will express a seditious thought, but speed is not very important imho.
