### ISSUE TITLE
CoffeeScript is fantastic, please don’t give it up

### ISSUE THREAD

**Issue by vzakharov** [jashkenas/coffeescript#5439]
I only learned about CoffeeScript recently and was amazed by its simplicity and elegance. I know if you google for “is CoffeeScript stil relevant in 2020,” the consensus is a resounding “no,” but frankly I don’t care. Reading CS code, compared to JavaScript, is like night and day.

I know, with the advent of Copilot, any syntax-related arguments become kind of moot, but I’ve always appreciated beauty in code, and CoffeeScript is an encapsulation of everything I find beautiful in programming.

Anyway, this post is just a token of appreciation for the language and its creators. You’ve done a great job, and the fact that the repo keeps getting updated gives me hope that we’ll be able to keep enjoying it for a while.

So, yeah, keep up the good work, and thank you for such an amazing language ☕🤎

**Comment by GeoffreyBooth** [comment]
Thanks for the feedback! Closing as nothing to do here.
