### ISSUE TITLE
Proposal: Add end word to close method or class

### ISSUE THREAD

**Issue by thadeu** [jashkenas/coffeescript#5457]
What do you think that add end word to close class/method like Ruby?

For example.

```
class GetByObjectOrKey
  get: (key) -> console.log(key)
end
```

**Comment by vendethiel** [comment]
I’m afraid that ship sank a long, long time ago!
There are other Ruby-to-JS compilers if you prefer to use that. Or if you must absolute have `end`ful coffee, something like `(window ? global).end = null` should do tve trick.

**Comment by thadeu** [comment]
@vendethiel It's awful believe this. CoffeeScript is so nice!
