### ISSUE TITLE
Bug: yield cannot be used in do -> expressions reliably?

### ISSUE THREAD

**Issue by borkdude** [jashkenas/coffeescript#5461]
I expect yield to be used anywhere in a function, but it seems do -> breaks this expectation since it's compiled to an IIFE.

Repro:

https://coffeescript.org/#try:perfectSquares%20%3D%20-%3E%0A%20%20num%20%3D%200%0A%20%20do%20-%3E%0A%20%20%20%20y%20%3D%201%0A%20%20%20%20yield%20y%3B%0A%20%20loop%0A%20%20%20%20num%20%2B%3D%201%0A%20%20%20%20if%20num%20%3E%2010%20%0A%20%20%20%20%20%20break%0A%20%20%20%20yield%20num%20*%20num%0A%20%20return%0A%0AglobalThis.foo%20%3D%20perfectSquares()%0A%0A

* CoffeeScript version: playground's version

Note that I'm only theoretically interested in a solution as I'm writing my own to-JS transpiler and was wondering if CoffeeScript authors have thought about this more than I have. [More info here](https://github.com/squint-cljs/squint/issues/450#issuecomment-1864952860).

**Comment by edemaine** [comment]
I would not view this as a bug, but as intended semantics: `do ->` literally means to build a function (`->`) and call it (`do`) — very different from the [TC39 `do` proposal](https://github.com/tc39/proposal-do-expressions). This functionality of `do ->` is useful, for example, if you want to build a generator right now. [For example](https://coffeescript.org/#try:processGenerator%20do%20-%3E%0A%20%20yield%201%0A%20%20yield%202%0A%20%20yield%203%0A):

```coffee
processGenerator do ->
  yield 1
  yield 2
  yield 3
```

Here's [a more real-world example with async](https://coffeescript.org/#try:await%20Promise.all(%0A%20%20for%20url%20of%20urls%0A%20%20%20%20do%20-%3E%20await%20(await%20fetch%20url).json()%0A)), where `do` enables `await` syntax without "infecting" the entire function:

```coffee
Promise.all(
  for url of urls
    do -> await (await fetch url).json()
)
```

I think where CoffeeScript's behavior is less intuitive is when it happens with *implicit* IIFEs; see #5363 where I asked about `return` inside a `for` loop, but the same applies to `yield` within a `for` loop. We actually get my intended behavior from #5363 [in Civet](https://civet.dev/playground?code=ZiA9IC0%2BCiAgZm9yIHggb2YgWzEuLjVdCiAgICByZXR1cm4gbnVsbCBpZiBiYWQgeAogICAgeA%3D%3D), but [not when it's a for-loop expression](https://civet.dev/playground?code=ZiA9IC0%2BCiAgbnVtYmVycyA9IGZvciB4IG9mIFsxLi41XQogICAgcmV0dXJuIG51bGwgaWYgYmFkIHgKICAgIHg%3D) which, as #5363 details, is hard to transpile. We've discussed this some in a Civet context, where we plan to do more thorough rewriting to handle cases like this, but haven't tackled it yet. See https://github.com/DanielXMoore/Civet/issues/202 and https://github.com/DanielXMoore/Civet/issues/381.

**Comment by borkdude** [comment]
Makes sense, I interpreted `do ->` as the TC39 proposal. The babel transpiler for that proposal does the thing I would expect (for implicit IIFEs).

**Comment by edemaine** [comment]
Cool, I didn't know about [that plugin](https://babeljs.io/docs/babel-plugin-proposal-do-expressions). I agree that it [works well with `yield`](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mAVAAmACgJTIN4ChnIQIDOUyAHsgLzIAmcO-BhJZAntcgIwAMTBbGAFMANrWQBWJgF9c0oA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.6&externalPlugins=%40babel%2Fplugin-proposal-do-expressions%407.23.3&assumptions=%7B%7D), but it [doesn't work well with `return`](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMAFASkQbwFCMRBAZykQA9EBeRAEzi1z3yJIE9LEBGABgbwCcAplBB8kAVgYBfbJKA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.6&externalPlugins=%40babel%2Fplugin-proposal-do-expressions%407.23.3&assumptions=%7B%7D) (compare with [the proposal](https://github.com/tc39/proposal-do-expressions?tab=readme-ov-file#breakcontinuereturn)) and [doesn't support `break`](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMAFASkQbwFCMQdwAsYAbAUxSgCcQy0c88IEBnKRAD0QF5EATOFlyMmrdgE8eiAIwAGYSIBGVMgEMA1gsQBfYbu1A&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.6&externalPlugins=%40babel%2Fplugin-proposal-do-expressions%407.23.3&assumptions=%7B%7D).

**Comment by borkdude** [comment]
> but it doesn't work well with return and doesn't support break

luckily for my language (squint) this isn't a problem since it is expression-oriented and therefore doesn't support explicitly returning things. I think it could be a reasonable trade-off for do expressions too since they have an implicit return value, maybe it should even barf on an explicit return

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMAFASkQbwFCMRBAZykQA9EBeRAEzi1z3yJIE9LEBGABgbwDYGAX2yCgA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.6&externalPlugins=%40babel%2Fplugin-proposal-do-expressions%407.23.3&assumptions=%7B%7D

**Comment by borkdude** [comment]
Here is an illustration of generator functions in squint

https://squint-cljs.github.io/squint/?src=KGRlZm4gXjpnZW4gZm9vIFtdCiAgKGpzLXlpZWxkIDEpCiAgKGpzLXlpZWxkKiBbMiAzXSkKICAobGV0IFt4IChpbmMgMyldCiAgICAoanMteWllbGQgeCkpCiAgKGxldCBbeCAoZG8gKGpzLXlpZWxkIDUpCiAgICAgICAgICAgIDYpXQogICAgKGpzLXlpZWxkIHgpKSkKCih2ZWMgKGZvbykp
