### ISSUE TITLE
[not an issue] An embeddable playground for CoffeeScript

### ISSUE THREAD

**Issue by hatemhosny** [jashkenas/coffeescript#5462]
Please excuse the issue. I did not find the discussions section enabled in this repo.

Please allow me to introduce [LiveCodes](https://livecodes.io), a [feature-rich](https://livecodes.io/docs/features/), [open-source](https://github.com/live-codes/livecodes), [client-side](https://livecodes.io/docs/why/#client-side), code playground that supports [80+ languages and frameworks](https://livecodes.io/docs/why/#language-support). The [announcement post](https://blog.livecodes.io/introducing-livecodes/) gives a general overview.

**CoffeeScript** has a first-class support in LiveCodes.

CoffeeScript starter template is available for a quick start:  
https://livecodes.io/?template=coffeescript  
(see all [starter templates](https://livecodes.io/?new)).

![CoffeeScript starter template in LiveCodes](https://github.com/jashkenas/coffeescript/assets/10176547/656fc276-5816-4db5-a792-57ca3543d3fa)

You can start an empty CoffeeScript project using this link: https://livecodes.io/?coffeescript

Projects can be [shared](https://livecodes.io/docs/features/share/), [exported](https://livecodes.io/docs/features/export/) and [deployed](https://livecodes.io/docs/features/deploy/) (to GitHub Pages).

Playgrounds can be [embedded](https://livecodes.io/docs/features/embeds) in any webpage, using a powerful, yet easy-to-use, [SDK](https://livecodes.io/docs/sdk).

This is an example for an embedded CoffeeScript playground:

```html
<div id="container"></div>

<script type="module">
  import { createPlayground } from "https://unpkg.com/livecodes";

  createPlayground("#container", {
    config: {
      activeEditor: "script",
      markup: { 
        language: "html",
        content: "<h1></h1>",
      },
      script: {
        language: "coffeescript",
        content: "(document.querySelector 'h1').innerText = 'CoffeeScript'",
      },
    },
  });
</script>
```
[Preview](https://livecodes.io/?x=code/N4IgLglmA2CmIC4QFUB2kawCYAIAKATgPYBWsAxmCADQhawDO5BEADpEaoiDSABawAhlm4AeALawwgnOT6CCDKQF4AOigAqAMQC0ADnU4A9AD5VqCVJmpBktSABuEWAHdWRAmEPlOYWOnsXCCwwPmV6J3JYHSCQvmocCFQoCEFoHSY02GUARgA6AAZDU14+MHFoAEEwMEVuaEFUAHN7f28GhgZ7dV5pJoZEAG0AXVpBSggHWABRLCgPbiYWdl5xBQBrAFdWRFAG5s3BJvgkMoreH3R-KiRRPhyTUSN7kxAAX1oGMABPOF2QfZNQ7HbjkToXXzXbjvT7MNg3PaNIFHE4gHwAM3RsEYcJWtEufnQ3AAFFgiORNpJ0HkAI6bWAEb4AZVgcEoHhwAHJ7pyAJR5JKoBkaWAADzAOGUXIAwkRMdimbiwJyYSAvr9GAIpAMECNYcswDq9WjOoRGFJobRWMQop0PEbRmjNl8iOIWTUkv1dh8QBBxO5PDrgD6fqxGN7aH4vkGAUjgajQziDRCrkSkKqpooIJxuAAmXO8AhCMmoaDfRDotJKMbQaBEFwAGSR0vkzROtXptHERHo3HRm1rvSIRGgMf8ggARnAREg0tBeONIFNQZwGCP4J9pGBnaC60oRD6AF7D8SIHJvIA)

Screenshot:
![embedded CoffeeScript playground](https://github.com/jashkenas/coffeescript/assets/10176547/eb06797a-d2a9-474f-90d3-de9fd67066f6)

Please refer to the [SDK documentations](https://livecodes.io/docs/sdk) for details.

Comprehensive [documentations](https://livecodes.io/docs/) are available with live demos, code samples and screenshots.

LiveCodes is free with unlimited usage, no ads and no account required. It can be easily [self-hosted](https://livecodes.io/docs/features/self-hosting) (if you want), and can be used for commercial projects ([MIT license](https://livecodes.io/docs/license)).

Disclosure: obviously, I'm the author of LiveCodes.

I thought you would be interested. Otherwise, please feel free to close this.
Thank you.

**Comment by GeoffreyBooth** [comment]
Thanks so much! You can add it to this list: https://github.com/jashkenas/coffeescript/wiki/In-The-Wild.

Closing as this isn’t an issue that requires action.
