### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by bushyice** [jashkenas/coffeescript#5466]
# I AM SO SORRY
## but this is not an issue

I am just so confused about coffeescript, is it being maintained? are there any forks that maintain it? i am in love with coffeescript and would love real type annotations in it other than that it's perfect, but i can't find ANY support for it anywhere, and it's slowly but surely forgotten and dying...

If i am wrong, i'd like the people who still use it speak. I really want coffeescript to rival typescript and even more javascript variants, rival as in being as functional and supported as typescript. 

Why are people giving up on it? WHY???

**Comment by STRd6** [comment]
You may be interested in https://github.com/DanielXMoore/Civet/, the spiritual successor to CoffeeScript.

**Comment by GeoffreyBooth** [comment]
CoffeeScript is still maintained, but there’s a lot less activity nowadays then there once was.
