### ISSUE TITLE
ECMAscript v5/Strict complience

### ISSUE THREAD

**Issue by Rixius** [jashkenas/coffeescript#566]
ES5/Strict requires that you put at the top of the function call  the string literal "use strict";
While theres only one current implementation of strict mode ( http://besen.sourceforge.net/ ),
it would be useful to allow the parser to check if the first line of your coffee is the string "use strict" and place it above all the var declarations in the final converted js

**Comment by GeoffreyBooth** [comment]
See [2337](https://github.com/jashkenas/coffeescript/pull/2337#issuecomment-295093854).
