### ISSUE TITLE
quote-word operator

### ISSUE THREAD

**Issue by patch** [jashkenas/coffeescript#582]
It would be nice to have a quote-word operator like Ruby's `%w/foo bar/` and Perl's `qw/foo bar/`, which splits the quoted string on whitespace and returns a list `['foo', 'bar']`.  Perl 6 added `<foo bar>` as a shorthand where the delimiters must remain angle brackets, which I think would be a nice fit for CoffeeScript.

```
song = <do re mi fa so>

lunch = eat food for food in <
  toast
  cheese
  wine
>

matrix = <
  1 0 1
  0 0 1
  1 1 0
>
```

References:
- http://perldoc.perl.org/perlop.html#qw/STRING/
- http://ruby-doc.org/docs/ProgrammingRuby/html/language.html#UF
- http://perlcabal.org/syn/Differences.html#qw()_changes%3B_new_interpolating_form

**Comment by alexander-sharshun** [comment]
a="
Array
Boolean
Date
Function
Number
Object
String
RegExp
".split(" ")
