### ISSUE TITLE
With Statement

### ISSUE THREAD

**Issue by danielribeiro** [jashkenas/coffeescript#620]
It would be nice to have with statement on coffescript. Actually, instance eval would be nicer, but with stament is close enough for most dsls.

**Comment by GeoffreyBooth** [comment]
@carlsmith Can you add what the intended JavaScript output would be?

**Comment by vendethiel** [comment]
Isn't `do (o = foo) -> console.log o.bar` good enough?

**Comment by mrmowgli** [comment]
I personally think it adds value, and it fulfills an underlying principle
of CS, in that it improves a core idea of Ecmascript.

**Comment by jashkenas** [comment]
We shouldn't re-use `with` for this (fairly odd) pattern. Writing it this way is just fine:

```coffeescript
(->
  @fillStyle = "rgb(200, 0, 0)"
  @fillRect 10, 10, 50, 50
  @fillStyle = "rgba(200, 0, 200, 0.5)"
  @fillRect 30, 30, 50, 50
).call canvas.getContext "2d"
```

**Comment by carlsmith** [comment]
> Isn't `do (o = foo) -> console.log o.bar` good enough?

Not really. That code just assigns the longer name to a shorter name that is automatically cleaned up at the end of the block, which wouldn't be applicable to the original example, as you would just use a shorter name to begin with. It's examples like this that I think `with` would help with:

``` coffee
const context = canvas.getContext("2d");
context.fillStyle = "rgb(200, 0, 0)";
context.fillRect(10, 10, 50, 50);
context.fillStyle = "rgba(200, 0, 200, 0.5)";
context.fillRect(30, 30, 50, 50);
```

Most developers would use an abbreviation, so would probably do this:

``` coffee
const ctx = canvas.getContext("2d");
ctx.fillStyle = "rgb(200, 0, 0)";
ctx.fillRect(10, 10, 50, 50);
ctx.fillStyle = "rgba(200, 0, 200, 0.5)";
ctx.fillRect(30, 30, 50, 50);
```

In these cases, there's no way to apply your suggestion, except to just use an even shorter abbreviation:

``` coffee
const c = canvas.getContext("2d");
c.fillStyle = "rgb(200, 0, 0)";
c.fillRect(10, 10, 50, 50);
c.fillStyle = "rgba(200, 0, 200, 0.5)";
c.fillRect(30, 30, 50, 50);
```

It would be nice to get rid of the temporary variable altogether:

``` coffee
with canvas.getContext "2d"
  @fillStyle = "rgb(200, 0, 0)"
  @fillRect 10, 10, 50, 50
  @fillStyle = "rgba(200, 0, 200, 0.5)"
  @fillRect 30, 30, 50, 50
```

**Comment by carlsmith** [comment]
@jashkenas' example would work the same way, so yeah, I'd like to use `with` to sugar this:

``` coffee
(->
  @fillStyle = "rgb(200, 0, 0)"
  @fillRect 10, 10, 50, 50
  @fillStyle = "rgba(200, 0, 200, 0.5)"
  @fillRect 30, 30, 50, 50
).call canvas.getContext "2d"
```

**Comment by GeoffreyBooth** [comment]
I’m concerned by the overloading of `@`; you’re creating a new function scope without necessarily being explicit about it, i.e. users would need to know that `with` is compiling into a function, despite there being no `->` or `=>`. And what if you wanted to access the enclosing scope’s `this`? We’d need a fat arrow variant of `with`.

Most libraries solve this problem through chaining:

```coffee
xAxis = d3.scaleBand()
  .rangeRound [0, width]
  .padding 0.15, 0.15
  .domain data.periodNames
```

I know the vanilla DOM methods don’t chain, and that’s what you appear to be working with; and maybe you don’t want to use jQuery, but there’s probably a simpler library out there that wraps those methods into chainable variants.

**Comment by carlsmith** [comment]
Yeah, on balance, it seems best to just use one of the workarounds. The `(-> block).call context` approach works pretty well as is, and you can wrap it in a nice API based on method chaining easily enough.

Thanks for considering this.

**Comment by Inve1951** [comment]
If anyone really ever needs it:
```coffee
_with = (context, args..., block) -> Reflect.apply block, context, args

_with {a: 1, b: 2}, ->
  @a * @b

_with canvas.getContext("2d"), this, (self) ->
  for {rect, color, bActive} in self.regions when bActive
    @fillStyle = color
    @fillRect rect...
  this
```
