### ISSUE TITLE
Allow place-separating underscores for number literals a la Ruby

### ISSUE THREAD

**Issue by jameshfisher** [jashkenas/coffeescript#632]
This is a simple one.  Ruby allows the underscore to be used in numeric literals to increase readability  of large numbers.  The underscore is simply ignored when the number is parsed.

I propose the same thing in CS.  It's simply implementable and has no issues with ambiguity AFAICS.  So we will be able to write:

```
while a < 1_000_000_000_000
  do_this_one_trillion_times()
```

Which is equivalent to:

```
while a < 1000000000000
  do_this_one_trillion_times()
```

Any takers?

**Comment by antonpiatek** [comment]
Shame - I love this feature in perl

**Comment by henrik** [comment]
A consideration that I didn't see mentioned explicitly so far: it's not just for zero filling.

So whereas `1e9` might be a good alternative to `1_000_000_000`, I don't think anyone would argue that `1.234567e12` is as readable as `1_234_567_000`.

**Comment by lydell** [comment]
`1e9 + 234e6 + 567e3`. Nah, just kidding :)

**Comment by tristil** [comment]
Not expecting you to change this but wanted to throw this out as a counterargument to consider: you said in 2010 that in Ruby very few people actually use this feature. But these days it's part of the Rubocop style guide so I would guess that it gets used quite frequently now: http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/NumericLiterals Just a FWIW

**Comment by lydell** [comment]
Related: babel/babylon#538

**Comment by Leftium** [comment]
Most JS platforms should [support numeric separators](https://v8.dev/blog/v8-release-75#numeric-separators) in the [future](https://youtu.be/c0oy0vQKEZE?t=595), so they can be used in CoffeeScript by momentarily escaping to JS:

    v = `1_019_436_871.42`

If [@babel/plugin-proposal-numeric-separator](https://babeljs.io/docs/en/next/babel-plugin-proposal-numeric-separator.html) is used, I think the above CoffeeScript will work on all platforms today.
