### ISSUE TITLE
Get/Set syntax

### ISSUE THREAD

**Issue by zmthy** [jashkenas/coffeescript#64]
Would a bit of syntax for getters and setters be a good idea? Its use would obviously make it incompatible with implementations of JS that don't support them, but that's the case with using them in the JS anyway. It would just be a little nicer than throwing **defineGetter** all over the place.

**Comment by aurium** [comment]
Six years after, with all ES6 discussion, @StanAngeloff's proposal looks more compatible to the reality and strongly necessary.
