### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by weepy** [jashkenas/coffeescript#76]
Was looking at Python for ideas to plunder. Not sure about the usefulness of them, but they looked interesting, and as they are syntactic sugar, they might be relevant. Here's the relevant section in Wikipedia:

<pre>
A decorator is a Python object that can be called with a single argument, and that modifies functions or methods. Python decorators were inspired in part by Java annotations, and have a similar syntax; the decorator syntax is pure syntactic sugar, using @ as the keyword:

@viking_chorus
def menu_item():
    print "spam"
is equivalent to
def menu_item():
    print "spam"
menu_item = viking_chorus(menu_item)
Decorators are a form of metaprogramming; they enhance the action of the function or method they decorate. For example, in the above sample, viking_chorus might cause menu_item to be run 8 times for each time it is called:
def viking_chorus(myfunc):
    def inner_func(*args, **kwargs):
        for i in range(8):
            myfunc(*args, **kwargs)
    return inner_func
</pre>

**Comment by rstuven** [comment]
I've just implemented a wrapper function to apply decorators using the API proposed in https://github.com/wycats/javascript-decorators which is supported in Babel 5+ and TypeScript 1.5.

Here's the code: https://gist.github.com/rstuven/65c782ac004a4da8bb9a

**Comment by denisw** [comment]
I know this issue has been closed years ago, but your decision to not include decorators might need to be reconsidered in the light of newest developments in the framework space. Several frameworks, such as Angular 2 and React-related libraries such as Alt or Redux, now make extensive use of decorators in their APIs for declaratively enhancing classes.

Of course, support for decorators is not strictly needed - they can still be called as functions. But requiring developers to do so is awkward, and I feel like it's not in line with CoffeeScript's vision of being a pleasan no-fuzz syntactic sugar layer above JavaScript.

**Comment by rstuven** [comment]
@denisw This could be helpful in the meantime: https://github.com/rstuven/es-decorate
