### ISSUE TITLE
Inline block comments can introduce unwanted commas in a function parameter list

### ISSUE THREAD

**Issue by dpritchett** [jashkenas/coffeescript#769]
Please see http://gist.github.com/624272

I was trying to caffeinate some JS of the form 

`callThisFunction( /* block comment here */ firstArgument)`

but my compiled JS output came out looking like

`callThisFunction( /* block comment here */, firstArgument)`.

 Note the extra comma.

**Comment by GeoffreyBooth** [comment]
Inline block comments that aren’t treated as expressions happens now via #4572. Sorry it took awhile.
