### ISSUE TITLE
coffee -w results in "EADDRINUSE, Address already in use" error

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#778]
Not sure if this is a coffeescript issue or express issue but using the "hello world" example from http://expressjs.com/guide.html:

```
app = require('express').createServer()
app.get '/', (req, res) -> res.send 'hello world'
app.listen 3000
```

Using this with

```
coffee -w app.coffee
```

Results in 

```
EADDRINUSE, Address already in use
```

When the app.coffee file is changed, and the server is not restarted.

This is on linux 2.6.35 x86_64

**Comment by Soviut** [comment]
Another option is to use nodemon. It's designed to restart servers on code changes or failures. You also need coffeescript installed so that node can automatically require it for compilation.
```
npm install nodemon coffee-script --save-dev
```
then start your server with nodemon
```
nodemon index.coffee
```
You should see the following
```
11 Jan 02:52:17 - [nodemon] v1.2.1
11 Jan 02:52:17 - [nodemon] to restart at any time, enter `rs`
11 Jan 02:52:17 - [nodemon] watching: *.*
11 Jan 02:52:17 - [nodemon] starting `coffee.cmd src\index.coffee`
```
