### ISSUE TITLE
switch-case-default over switch-when-else

### ISSUE THREAD

**Issue by satyr** [jashkenas/coffeescript#785]
#### Before

```
switch a
  when b
    foo()
  when c, d
    bar()
  else
    baz()
```
#### After

```
switch a
case b
  foo()
case c, d
  bar()
default
  baz()
```
- Less indentation
- Mirrors JS keywords
- No ambiguity against `if`-`else` (#562)

**Comment by JhonnyJason** [comment]
Does anybody have an Idea why this does not work?

```coffee
switch state
    when "stateA"
        console.log "we are at state stateA"
        stateIndicator.innerHTML = "stateA"
    when "stateB"
        console.log "we are at state stateB"
        stateIndicator.innerHTML = "stateB"
    else
        console.log "we had a weird state: " + state
        stateIndicator.innerHTML = "weirdState"
```

It gives me an Error for the line having the else:

**error: indentation mismatch**

As I would say the error message is not true^^... I know they usually are true but still I need to understand why - from this thread it appears to be the right indention - as my logic also would support

**Comment by GeoffreyBooth** [comment]
[It works fine](http://coffeescript.org/#try:switch%20state%0A%20%20%20%20when%20%22stateA%22%0A%20%20%20%20%20%20%20%20console.log%20%22we%20are%20at%20state%20stateA%22%0A%20%20%20%20%20%20%20%20stateIndicator.innerHTML%20%3D%20%22stateA%22%0A%20%20%20%20when%20%22stateB%22%0A%20%20%20%20%20%20%20%20console.log%20%22we%20are%20at%20state%20stateB%22%0A%20%20%20%20%20%20%20%20stateIndicator.innerHTML%20%3D%20%22stateB%22%0A%20%20%20%20else%0A%20%20%20%20%20%20%20%20console.log%20%22we%20had%20a%20weird%20state%3A%20%22%20%2B%20state%0A%20%20%20%20%20%20%20%20stateIndicator.innerHTML%20%3D%20%22weirdState%22). Generally “indentation mismatch” means you’re mixing tabs and spaces.

**Comment by JhonnyJason** [comment]
OK got it thnx :-) 

**Beware of trailing spaces!!**
