### ISSUE TITLE
Dynamic object keys

### ISSUE THREAD

**Issue by satyr** [jashkenas/coffeescript#786]
By allowing parenthesized expression as keys, we could write:

    return {(key): val}
instead of:

    o = {}
    o[key] = val
    return o
The compilation would be:

    return (_obj = {}, _obj[key] = val, _obj);
Not sure if we can go braceless with it, but worth a try.

**Comment by mikermcneil** [comment]
> There's something nice about having the {key: value, key: value} form be restricted to "pure" identifiers as keys.

very true

**Comment by joaomilho** [comment]
There may be something nice, but it is not pragmatic. Look at React's `React.addons.classSet` for instance. It's meant to help defining a list of class names for a component. That's the way it works:
```coffeescript
React.addons.classSet
  'classA': true
  'classB': hasClassB()
  'classC': hasClassC()
```

But most of the time you need dynamic keys (specially if you follow BEM), like:

```coffeescript
React.addons.classSet
  "block__element#{if hasModifier() '--modifier' else '--no-modifier'}": true
```

**Comment by Spadavecchia** [comment]
obj = "#{someVar}": true

This is generating `Unexpected :` error in coffeelint and karma coffee-preprocessor.

You can write a comment `# coffeelint: disable=coffeesrcipt_error` to avoid coffeelint error, but karma is not working.

**Comment by lydell** [comment]
@Spadavecchia Are you sure coffeelint and and karma use coffee-script 1.9.1?

**Comment by Spadavecchia** [comment]
@lidell, is true, this project are using an old CS version, but should it to fail with version 1.7?

**Comment by vendethiel** [comment]
yes.
