### ISSUE TITLE
Operator Overloading

### ISSUE THREAD

**Issue by ptarjan** [jashkenas/coffeescript#846]
I'd love to use coffeescript as my 'go to' language choice, but having to worry if I'm hitting a number > 9e15 is a big pain point in Javascript.

I'd like to create a BigInteger class that would handle arbitrary precision integer operation. There are a few hooks I'd like:

1) Let me override the base integer. `Integer = require('./BigInteger')`
2) Allow operator overloading. `1 + 3` maps to `(new BigInteger(1)).ADD(3)`, or `1 == 3` maps to `(new BigInteger(1)).EQUALS(3)`. 

Is there anything preventing coffeescript from supporting this?

**Comment by al6x** [comment]
Actually this issue is not related to CS. 

It's possible to do it as `CS -> CoffeeScript Compiler -> JS -> JS Operator Overloading Trasnpiler -> JS`
