### ISSUE TITLE
multi-line statement with the ending-with-an-operator trick

### ISSUE THREAD

**Issue by edc** [jashkenas/coffeescript#995]
coffee-script allows a long if statement to be broken into two lines as long as the first line ends with an operator. For instance, 

```
if a and b or
    c and d
       doIt()
```

compiles to

```
(function() {
  if (a && b || c && d) {
    doIt();
  }
}).call(this);
```

However, this requires the `doIt()` line has a higher or lower (!) indention level than the second line. In other words, the following won't compile:

```
if a and b or
    c and d
    doIt()
```

However, this would

```
if a and b or
        c and d
    doIt()
```

It took me a while to figure this out. I think this needs to fixed or documented.

**Comment by GeoffreyBooth** [comment]
Closing this issue as it doesn’t appear to be affecting enough people to warrant attention. If someone wants to do further investigation into this and can devise a fix, a pull request is welcome.
