### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by DmitrySoshnikov** [jashkenas/coffeescript#996]
Unfortunately, the search by issues is currently broken, so cannot check whether such a feature was already proposed.

What about to have a bit sugar for AOP in respect of <em>decorators</em> or (pre/post) <em>annotations</em>?

Python has a common strategy of decorating an annotating methods. E.g.:

<pre>def foo(original_fn):
    def decorated_fn(x):
        print("Log", x)
        original_fn(x)
    return decorated fn

@foo
def bar(x):
    print("bar: ", x)</pre>

Thus, a syntax can be chosen any (since `@` is used in Ruby-style for "instance variables"). Python uses such decorators not only to wrap some functions (i.e. `@foo def bar ...` is just a sugar for `bar = foo(bar)`) but also to change a semantics of some methods -- e.g. `@classmethod` decorator, etc.

Additional info for Pythons decorators: http://www.python.org/dev/peps/pep-0318/

Also, besides the Python's common decorators, `pre-` and `post-` `annotations` can be considered.

E.g. (abstract syntax):

<pre>[pre checkArguments]
[pre validatePost]
[post formatResponse]

handleRequest = (...) ->
    data = [...]
    data</pre>

I.e. before entering the `handleRequest` first `checkArguments` and `validatePost` methods should be called. Then the `handleRequest` itself and after that `formatResponse`.

Thus, methods-annotations should accept/return a data of a special format. If e.g. `checkArguments` isn't passed, it should either throw or return a special `error` data (a signal that other annotation in chain shouldn't continue). In the successful passing, it just returns handled data which are passed next to the following annotation/decorator.

Dmitry.

**Comment by light24bulbs** [comment]
Well this is basically the end of coffeescript if they don't start supporting modern features like this.

**Comment by vendethiel** [comment]
Dearh rumors again?

**Comment by LoveIsGrief** [comment]
Hello,

Passing by from codetriage.com and trying to help sort (trier?) issues.

Since this is an [ES6 proposal](https://github.com/tc39/proposal-decorators) as well, it soon might not be considered an extension anymore. Only problem I see is choice of a new character for denote a decorate, because **@** has already been taken.

Since this was reopened maybe adding the `enhancement` tag would help?

(If I'm doing this triage wrong, do tell. I'm here to learn :) )

**Comment by vendethiel** [comment]
> Since this was reopened maybe adding the enhancement tag would help?

It wasn't reopened on purpose. It was just closed so long ago, posting a comment removed the "closed" tag.
