### ISSUE TITLE
Compiler can't handle large files

### ISSUE THREAD

**Issue by TrevorBurnham** [jashkenas/coffeescript#998]
Bit of an obscure use case, but worth figuring out: I tried creating a CoffeeScript file of this form:

```
bigArray = ['a','b','c','a','b','c', ...
```

continuing for about 2MB. Anything I try to do to that file—`coffee bigArray.coffee`, `coffee -c bigArray.coffee`, or say `require './bigArray'` from a Node app in the same directory—causes a freeze-up. If I instead create a JavaScript file with the same contents, I have no such problems—it can run or be `require`d just fine.

While it's not a huge issue, it'd certainly be nice to find out what the choke point is and fix it.

**Comment by GeoffreyBooth** [comment]
Closing this issue as it doesn’t appear to be affecting enough people to warrant attention. If someone wants to do further investigation into this and can devise a fix, a pull request is welcome.
